### ISSUE TITLE
Pregunta Tarea 1 Pregunta 1.c

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2343/syllabus#1]
En la pregunta se nos pide extender **las** expresiones analíticas relevantes para caracterizar 'β' y 'γ'. ¿Pero que son estas letras?
En la pregunta 1.b asumí que 'β' se trataba de la base en este contexto, pero para la pregunta C no me queda clara la notación.

**Comment by jnlarrain** [comment]
Estimado, 'β' sigue siendo una base y 'γ' vendría siendo un exponente.

**Comment by frvalenzuela** [comment]
Me quedo claro ahora, gracias!

**Comment by malopez16** [comment]
El β de la b) es el mismo valor que la de la pregunta a) o las preguntas son completamente independientes entre si?

**Comment by FranLucchini** [comment]
Son independientes; una pista de eso es que en la b) se pide una expresión mientras que en a) se pide un valor.
