### ISSUE TITLE
Supociones Proyecto

### ISSUE THREAD

**Issue by jnlarrain** [IIC2343/syllabus#1]
Se puede suponer que en la multiplicación el resultado sera de 16 bits, o debemos trabajar estas excepciones??

**Comment by Hernan4444** [comment]
Hola, el resultado puede ser mayor a 16 bits, pero nosotros solo trabajaremos con los 16 bits menos significativos.
Por ejemplo, en decimal:
> 56797 * 2 = 113594

En hexadecimal es
> DDDD * 0002 = 1BBBA

En este caso, el resultado debería ser `BBBA`

Saludos ✌️
