### ISSUE TITLE
Instalación Vivado

### ISSUE THREAD

**Issue by lldavico** [IIC2343/Syllabus#1]
Hola!

Para la instalación de Vivado que recomiendan más, ocupar Windows? o Linux? Es que en mi computador tengo Windows y Windows subsystem for Linux con Ubuntu 18.04 y no sé que podría ser más recomendable para ocupar Vivado, o si en verdad da igual con cualquier sistema operativo.

Gracias!

**Comment by Arcoirisky** [comment]
Te recomendaría más Windows, el programa está hecho para correr en ese sistema operativo O:
