### ISSUE TITLE
Llamada a Subrutinas

### ISSUE THREAD

**Issue by BSamilla** [IIC2343/syllabus#10]
Hola!
¿Podrían explicarme como funcionan las llamadas a sub-rutinas?

Se que tengo que poner CALL label, para llamarla y RET para retornar.
Pero no me queda claro el tema de las variables, se que puedo salvar el valor de los registros con PUSH y POP, pero como tendría que hacerlo para que las sub-rutinas trabajen con "variables locales", estaba pensando en definirlas en DATA y tener cuidado de dejarlas "limpias", antes de hacer el return. ¿O hay una manera mejor de hacerlo?
Y como funcionaria en caso de hacer llamadas "recursivas". 

Si me pueden dar un mini tutorial con un ejemplo, así me queda todo mas claro.
Gracias! :D
Saludos

**Comment by MainScientist** [comment]
Estimado,
te recomiendo leer el siguiente [apunte de Hans sobre subrutinas](https://github.com/IIC2343/syllabus/blob/master/Material/Apuntes%20de%20Hans/5%20-%20Saltos%20y%20Subrutinas.pdf), el cual tiene muy bien explicadas tus dudas. Si después de leerlo continuas con preguntas no dudes en volver a preguntar por esta misma issue. Saludos.
