### ISSUE TITLE
Tarea 1 - 2.b 

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2343/syllabus#10]
Hola! qué tal? ¿las representaciones numéricas de los naturales tienen que mantenerse iguales? Es decir, el 000 tiene que ser 0, el 001 tiene que ser 1, etc? o pueden cambiar sus valuaciones? 
Gracias

**Comment by FranLucchini** [comment]
Deben mantenerse iguales. En el enunciado se dice que se debe modificar el algoritmo de complemento a 2, por lo que la representación de los naturales se debe mantener.

**Comment by frvalenzuela** [comment]
Pero si se mantienen iguales, entonces los número que comienzan con 0 como serían positivos y por la inclusión del 0 implicaría que automáticamente que tendrán un número menos que los negativos. 
Si tomamos el algoritmo de los apuntes: 1. Agregar un cero a la izquierda, 2.  Reemplazar los 0’s por 1’s. 3.  Sumar uno al número.
La única opción que quedaría sería cambiar el primer paso para mantener la consistencia aritmética, osea que los positivos comiencen con 1 y eso implicaría que la representación de los números naturales sería distinta.
Si se mantuviese igual, la opciones que quedarían para modificar el algoritmo sería dejarlo como complemento 1, u otra opción totalmente distinto que no estoy considerando.
