### ISSUE TITLE
Pregunta escrita Y2k38

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/Syllabus#10]
Esta issue es en respuesta a @Lfuenzalida2 ya que cerramos el foro de canvas.

Lo que se pide es el "efecto" y2k38 causando problemas, no uno parecido. En realidad, sin necesidad de estar en el año 2038, ya hemos visto cómo sí ha causado problemas. Cuando publiquemos las soluciones de la tarea estará el caso particular que nosotros encontramos.

Saludos!

**PD:** un problema parecido no será 0 puntos, tranquilos con eso.

**Comment by fncabrera** [comment]
Hola @jmwielandt ,

Cuando dices que se pide el efecto y2k38, ¿te refieres a que tiene que ser debido a una variable de 32-bit signed integer contando **específicamente segundos**, o podría ser estar contando otra cosa?

Saludos

**Comment by jmwielandt** [comment]
Es específicamente contando segundos, desde el 1 de enero de 1970 a las 00:00 horas.
Igual lo dicho, usar un problema parecido no van a ser 0 puntos.

**Comment by cacosandon** [comment]
Hola @jmwielandt 

Cuando nos piden 

> Investiga sobre el problema del año Y2k38, describe una solución por software y explica algún problema relacionado a su aplicación.

La parte 
> ...explica algún problema relacionado a su aplicación.

Se refiere a la aplicación de mi solución por software o algún problema relacionado con Y2k38?

Gracias!

**Comment by jmwielandt** [comment]
@cacosandon Un problema de tu solución
