### ISSUE TITLE
[Tarea1] [P4] Promedio Springfield?

### ISSUE THREAD

**Issue by yerkko** [IIC2343/Syllabus#10]
>Además sumar los n elementos le adicionamos un uno, y luego lo dividimos en la cantidad de elementos, tal como el promedio regular. Finalmente, al promedio de Springfield se divide por dos obtener 5 bits como resultado. Esta última división debe dar un resultado aproximando por redondeo simple, es decir, se aproximar hacia abajo en caso de que el primer decimal es menor a 5, y hacia arriba en caso contrario.

En la P4 se hace referencia a que para el promedio springfield, se suma 1, luego se divide por n (en este caso 3 por R, G, B) y finalmente se divide en 2, redondeando el resultado. Viendo los sample input y output está este caso.

> R: 0 G: 0 B: 22
8

Pero 22 + 1 = 23
23/3 = 7.67 ( 7 si es división entera)

Luego,

7/2 = 3.5 que redondea a 4.

Haciendo la división por dos mediante bitshift también queda incorrecto ya que 7 queda en 3 y 8 en 4 (?)

No sé qué estoy entendiendo mal del procedimiento :( 

Gracias

![image](https://user-images.githubusercontent.com/48332955/63203575-5e1e1780-c05e-11e9-8b17-9b01363b324f.png)

**Comment by jeschuwirth** [comment]
Te ayudo porque igual estuve mucho rato haciendo eso, cuando en el enunciado dice:

![image](https://user-images.githubusercontent.com/37160256/63206835-60966680-c08a-11e9-9bec-948acba3d8b6.png)

Aumentar los valores de 5 a 6 bits se hace agregando un 0 a la derecha del número, en tu ejemplo:

R: 0 G: 0 B: 22

B es 10110, por lo que pasa a 101100, lo que es 44

44+1 = 45

45/3 (los 3 valores) = 15

15/2 (como regla) =7,5

7,5 se aproxima hacia arriba te queda el 8

Pase mucho rato pensándolo, pero así es como se hace.
Suerte!

**Comment by Arcoirisky** [comment]
Es como dice @jeschuwirth :D Su razonamiento es correcto c:

**Comment by yerkko** [comment]
Gracias, creía que aumentar los bits era sólo para evitar overflow.

**Comment by jmwielandt** [comment]
Hola!

Por favor no cierren las issues, nosotros las cerraremos cuando sea oportuno.

Por cierto, ¿a qué te refieres con evitar overflow?

Saludos~
