### ISSUE TITLE
Forma de input del json

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#10]
Tengo una duda, al leer el archivo json suponemos por ejemplo que va a partir de atras para adelante, es decir por ejemplo que al leer el json vamos a leer primero un input en vez de un not, es decir esto:

Ejemplo de la tarea:
{"from": "input1", "to": "not1"},
  {"from": "input2", "to": "not2"},
  {"from": "not1", "to": "or1"},
  {"from": "input2", "to": "or1"},
  {"from": "input1", "to": "or2"},
  {"from": "not2", "to": "or2"},
  {"from": "or1", "to": "and1"},
  {"from": "or2", "to": "and1"},
  {"from": "and1", "to": "output1"}

Ejemplo mio:
 {"from": "input1", "to": "or2"},
 {"from": "not2", "to": "or2"},
  {"from": "not1", "to": "or1"},
  {"from": "input2", "to": "or1"},
  {"from": "input1", "to": "or2"},
  {"from": "or1", "to": "and1"},
  {"from": "or2", "to": "and1"},
  {"from": "and1", "to": "output1"}
{"from": "input1", "to": "not1"},
  {"from": "input2", "to": "not2"},

O sea me refiero al orden en que nos entregan el circuito, porque no se si ir evaluando altiro o bien tengo que crear el circuito para sacar el resultado. gracias y ojala se entienda

**Comment by Arcoirisky** [comment]
Hola!
No pueden asumir un orden concreto. De hecho, si miras algunos de los ejemplos que les subimos hay algunos que empiezan por el output O:!!

**Comment by auirarrazaval** [comment]
Para complementar a @Arcoirisky, no pueden asumir ningun orden específico (adelante para atras, o atras para adelante). Es completamente valido un input comoletamente desordenado.
