### ISSUE TITLE
convención flip-flops

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#100]
Hola!
No me quedó claro la convención de los flip-flops

![image](https://user-images.githubusercontent.com/24725124/45101074-15957480-b101-11e8-930c-90e9f00ea344.png)

¿Podrían dar un ejemplo (json) porfavor?

**Comment by FranLucchini** [comment]
Hola, la convención que usaremos será igual al de la Tarea 3.  Un ejemplo:

``` json
{  
    "sequential": [
    {"from": "input1", "to": "ffd1", "gate": "C"},
    {"from": "ffd1", "gate": "Q", "to": "not1"},
    {"from": "ffd1", "gate": "Q", "to": "out1"}
    {"from": "not1", "to": "ffd1", "gate": "D"}
    ],
    "delays": [
    {"gate":"ffd1", "delay":4.1},
    {"gate":"not1", "delay":0.1}
    ]
}
```
En este ejemplo, se usa `gate` para indicar que `input1` va hacia `ffd1` usando la entrada `C`. También se usa para indicar que la salida `Q` de `ffd1` va hacia `out1` y `not1`.

**Comment by LuisFros** [comment]
Podemos asumir que el delay de un flip-flip D sera fijo (estable) ? Como en ejemplo el delay de "ffd1" es 4.1

**Comment by FranLucchini** [comment]
El valor 4.1 es el tiempo en que la corriente se demora en recorrer el flip-flop hasta lograr el estado de salida Q fijo ¿Tu duda era referente a esto?

**Comment by LuisFros** [comment]
Gracias @FranLucchini, efectivamente queria confirmar que era el tiempo de permanencia en un Flip Flip. 
Lo unico que no me queda claro de esta tarea es que dado cierto input, el circuito puede oscilar y nunca terminar en un output. Esto entregando un tiempo de permanencia **infinito** segun la issue #103 . Por lo tanto , entiendo que en los casos de tiempo **finito** el tiempo de permanencia sera constante en el tiempo. Es decir, si hago la simulacion dos veces con el mismo input deberia entregarme el mismo tiempo de permanencia. 
Estoy en lo correcto?
