### ISSUE TITLE
Duda Circuito Figura 1

### ISSUE THREAD

**Issue by llloyola** [IIC2343/syllabus#101]
Hola! Ando medio perdido 😢
En la figura 1 de la tarea 4, cómo puede funcionar el ```or1```, si necesita la salida del ```not1``` para funcionar y ```not1``` se encuentra a la salida de ```or1```? 

Gracias de antemano

**Comment by FranLucchini** [comment]
Es un loop del circuito; es un ejemplo para mostrar que pueden existir este tipo de circuitos.

**Comment by rfenzo** [comment]
Te recomiendo que revises el material de clases, especificamente los flip flops. Pero en general son circuitos que en esos cables que mencionas tienen "basura" inicialmente, es decir podria tener o no voltaje (0 o 1). Pero una vez que el circuito es inicializado el valor será conocido (según los inputs que le proporcionarás).
Espero haberte aclarado un poco, saludos!

**Comment by paula-ds** [comment]
Pero para las simulaciones esa "basura inicial" de los cables la ponemos nosotros? por ejemplo definir que si llega un 0 de input1 al primer or1, este circuito no podrá seguir avanzando por ahí, por esta razón hay que darle un valor al cable que llega del not1 hacia el or1, esta sería la "basura" y yo decido si es un 1 o un 0?

**Comment by jheysen** [comment]
Piensa, no estaba energizado el circuito, qué podría tener....

**Comment by Nicolasvegam** [comment]
me sumo a lo que dice @paula-ds, puedo decir que toda la basura es "0"?

**Comment by FranLucchini** [comment]
Pueden pensar que como no hay corriente inicialmente, entonces vale 0.
