### ISSUE TITLE
[Tarea 3 - Programada] Test

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2343/syllabus#101]
Hola, ¿podrían subir mas test con distintas instrucciones por favor?
Gracias

**Comment by ignacioaraya1995** [comment]
¿?

**Comment by Arcoirisky** [comment]
Pueden probarlos con sus propios programas. Incluso modificar los de la tarea pasada para que sean con octogonal :)

**Comment by emontecinos** [comment]
Hola, aprovecho esta issue para preguntar respecto al formato de los test con los que se evaluarán las partes de la tarea.
Serán como [precomp](https://github.com/IIC2343/syllabus/blob/master/Tareas/T03/ejemplos%20(programada)/precomp.asm), donde se indica el numero de línea con ":\n"?
También los códigos máquina serán como los del enunciado (separados por ";")?

Gracias
