### ISSUE TITLE
Parte 1: Input decimal

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2343/syllabus#102]
En la parte 1 de la tarea tenemos que tomar un numero de una cierta base, pasarlo a binario y luego pasarlo a base 10 nuevamente según un cierto tipo de base.
Si el numero es decimal, el cambio a binario se hace según un formato especifico? Es decir en 32 o 64 bits? O queda a elección nuestra?

**Comment by FranLucchini** [comment]
Si no estoy equivocada en el enunciado aparece float_32 en el estándar IEEE 754.

**Comment by Hernan4444** [comment]
@Rudyjb24 tal como dice Francesca es con float_32 pero solo si ponemos tipo de dato "float". Si ponemos double, es float_64.

Ps: No cierren las issues, nosotros lo haremos por usted 👍

**Comment by Rudyjb24** [comment]
Gracias

**Comment by Rudyjb24** [comment]
Me acabo de dar cuenta que no me quedo claro. Entiendo que al pasarlo de binario a base 10 hay que tomar la cantidad de bits, 32 o 64, dependiendo si es float o double.

Mi duda es si el input es por ejemplo 355,2 5 double, significa que que debemos pasar el numero 355,2 de base 5 a base 2, luego interpretar este numero binario como un float de 64 bits y pasarlo a base 10.
Mi problema es que al hacer el cambio de base de 5 a 2 (en este ejemplo) tenemos que representarlo con punto flotante. Esta representacion debemos hacerlo con 32 o 64 bits? Supongo que no depende del tercer argumento puesto que tengo entendido que un input 355,2 5 int seria valido, a que el tercer argumento segun el enunciado corresponde al tipo al cual queremos transformar, no el tipo del dato que nos entregaron.

**Comment by Hernan4444** [comment]
@Rudyjb24 Excelente punto 😅. En la issue #92 aclaré unos puntos que talvez te ayuden más. Al final decidimos que siempre el float lo pasas a 32 bits y para tu ejemplo, luego lo analizas con 64 bit para interpretarlo. 
Al final no haría ningún cambio pero para ser honesto no pensabamos pasar float 32 a float 64 (no teníamos test como el tuyo), teníamos pensado testear mas como un número gigante o pequeñisimo en float de 32 bits y en 64 bits.

Saludos!!

**Comment by Rudyjb24** [comment]
Gracias

**Comment by crabarca** [comment]
@Hernan4444  
Que se entiende por analizarlo con 64 bits ?

**Comment by Hernan4444** [comment]
@crabarca esta imagen explica como es el formato IEEE734 para 64 bits. precisamente es lo segundo que dices tu "agregar correspondientemente los bits a cada parte del float_32 de manera de transformar a float_64"
![image](https://user-images.githubusercontent.com/15641721/29965751-4bd406ea-8ee5-11e7-9e67-4bbc8672eaf1.png)

Ns = bit de signo
Nc = bit exponente
Nm = bit mantisa

**Comment by Rudyjb24** [comment]
De la misma manera que al pasar un decimal a binario lo representamos en 32 bits, al pasar un entero a binario lo representamos con 16 bits? Que pasa si en el input nos ponen un numero no representable?

**Comment by Hernan4444** [comment]
@Rudyjb24 en el caso de un entero, debe ser con todos los bits que sean necesarios. Al momento de transformarlo a otro tipo de dato tendrás que acotar los bits que usarás. Es por esto que los números enteros siempre serán representables para esta tarea y en el caso de un float, puede que les entreguemos numeros que el estandar no soporta y ahí ustedes deben representar el numero más cercano al input.

Saludos!
