### ISSUE TITLE
Recorreccion Tarea 1

### ISSUE THREAD

**Issue by BSamilla** [IIC2343/syllabus#102]
He visto mis notas de la recorreccion y me han bajado nota en tests que estaban correctos.

:/

**Comment by Hernan4444** [comment]
@BSamilla hola, lo veo altiro

**Comment by Hernan4444** [comment]
@BSamilla puedes revisar ahora porfa?, corri los test con tu entrega anterior para que los que estaban correctos tuvieran su puntaje correspondiento.

**Comment by BSamilla** [comment]
Si ahora si están bien
Gracias!
