### ISSUE TITLE
[T04]Cantidad de inputs y outputs

### ISSUE THREAD

**Issue by fgbruna** [IIC2343/syllabus#102]
Para la tarea podemos asumir que los circuitos tendrán solo un bus de salida?
O deberíamos poder implementarlo para cantidades arbitrarias?
**Edit**: solo salida, me di cuenta que si hay varios inputs en el ejemplo

**Comment by FranLucchini** [comment]
Con esto te refieres a que si pueden haber "subcircuitos" independientes?

**Comment by fgbruna** [comment]
No, simplemente si la cantidad de componentes tipo `outn` será arbitraria.

**Comment by jheysen** [comment]
Lo será

**Comment by fgbruna** [comment]
Ok! Gracias
