### ISSUE TITLE
Duda registros de estado

### ISSUE THREAD

**Issue by miortiz1** [IIC2343/syllabus#102]
Cual es la diferencia de el registro de estado O y el C?
Segun lo que entiendo solo habra overflow si es que hay carry, por lo tanto siempre seran iguales esos registros?

**Comment by frvalenzuela** [comment]
Hola @miortiz1 !

Lo que tu dices **no se cumple siempre**. Por ejemplo, digamos que que tenemos una ALU de tres bits con complemento 2, y que queremos restar los número `"001"` y `"111"`. Esto dará como resultado `"010"`, y **esta resta no producirá carry** (debido a que como se vio en clases para restar en un subtractor negamos las entradas y una entrada es de `'1'` para simular el complemento 2).

Por lo que, **no siempre serán iguales**. Para más información del manejo de overflow te recomiendo revisar la issue #65.

Saludos!
