### ISSUE TITLE
T04 Ejemplo

### ISSUE THREAD

**Issue by Dunkan1** [IIC2343/syllabus#103]
una duda, pueden decirnos cuanto debería arrojar el ejemplo que se da en el enunciado de la tarea

**Comment by FranLucchini** [comment]
Sí, podemos!

**Comment by Arcoirisky** [comment]
Osea... El caso más largo es infinito?

**Comment by FranLucchini** [comment]
Sip

**Comment by malopez16** [comment]
Hola!  Aquí : https://github.com/IIC2343/syllabus/issues/104#issuecomment-419041499 se indica que debemos seleccionar el mayor de los estables, pero al leer esta issue me queda la idea de que simplemente es inestable y por lo tanto es infinito. ¿Con cuál nos quedamos? 🤨🤨 
Gracias :)

**Comment by nmaturana97** [comment]
Una pregunta, si seguimos el camino del ejemplo input1-or1-not1-xor1-or2 da un tiempo de 18.7, porque no se considera ese camino?

**Comment by LuisFros** [comment]
Hola @FranLucchini  perdon por la molesta, 
segun este comentario : https://github.com/IIC2343/syllabus/issues/103#issuecomment-419113426
hay solo 1 loop del ejemplo que es inestable, pero despues de mucha revision (a mano , algoritmicamente y con software externo) estoy seguro que ambos loops son inestables. 
Estoy en lo correcto?

**Comment by eiherrera** [comment]
Hola! 

No sé si este es el medio para compartir esto, pero me gustaría hacer una crítica constructiva respecto a las tareas. Espero que nadie se lo tome como un ataque personal. De hecho agradezco mucho su buena disposición al momento de responder las issues, la buena calidad de tanto clases como ayudantías, el hecho de que se esfuercen para subir los resultados de estas últimas y en fin, que el curso funcione tan ordenadamente. 

Sin embargo, me parece que para esta tarea fue muy poco claro el enunciado. Comprendo el espíritu de esperar que como alumnos vayamos más allá de lo aprendido y nos enfrentemos a problemas que requieran poner en práctica los conocimientos adquiridos de una forma nueva y creativa. Pero creo que en el caso de esta tarea, no sería posible solucionarla sin antes haber clarificado muchas cosas mediante el syllabus. Quizás esto no tenga nada de malo en sí, pero a mi parecer esto genera los siguientes problemas:

1. Al depender tanto de lo respondido en el syllabus, es difícil realizar la tarea con anticipación, dado que es necesario clarificar tantos supuestos y demases. Si bien alguien que no tiene claro qué hacer y cómo hacerlo podría preguntar cada una de sus dudas hasta tener el panorama claro, pero creo que en virtud de no caer en el spam y quizás por vergüenza nadie se sentiría cómodo con esto. Además, hay dudas y supuestos que a uno no se le ocurren pero sí a otro, por lo que es a veces necesario esperar a que alguien realice la pregunta correcta.

2. Se puede caer en contradicciones y discrepancias entre lo respondido y por ende, generar confusiones o errores al trabajar en la tarea. Una muestra de esto es lo que pasó en esta issue, donde a menos de 24 horas de la entrega se corrige lo planteado por un ayudante. Me refiero al hecho de que la respuesta original a esta issue fue que en el ejemplo del enunciado existía inestabilidad y por tanto frecuencia infinita, pero 3 días después se cambia y corrige lo anterior. Esto a su vez aumenta el problema de no poder realizar la tarea con anticipación, dado que alguien que hubiera hecho la tarea hace un par de días con esta respuesta en mente tendría mal su código.

Sé que nada de lo anterior se hace con el fin de perjudicarnos y que desean lo mejor del curso. Por esta misma razón espero que comprendan de dónde vienen mis inquietudes y que, en conclusión, ojalá los enunciados a futuro sean menos ambiguos respecto a los supuestos básicos, sin necesariamente restarle dificultad y valor pedagógico.
