### ISSUE TITLE
Administrativa | Video ayudantía 3

### ISSUE THREAD

**Issue by stmorales** [IIC2343/Syllabus#103]
Hola! 

No pude asistir a la ayudantía 3 y encuentro todo el material menos el video de la ayudantía misma. Quisiera saber si van a subirlo, o si van a subir las soluciones en formato PDF.

Muchas gracias!

**Comment by jmwielandt** [comment]
Hola, está subido el video, link en el readme.

Estoy priorizando subirles las correcciones y recorrecciones antes que las soluciones de la ayudantía.

Saludos!

**Comment by stmorales** [comment]
Muchas gracias!!!
