### ISSUE TITLE
[Tarea 3 Programada] Duda sobre labels

### ISSUE THREAD

**Issue by NoemiCC** [IIC2343/syllabus#103]
Hola,
Es necesario conservar los labels de las distintas partes del código Assembly? Porque son necesarios para los jump cuando los volvemos a convertir en Assembly. Si es así, como puedo guardarlos dentro del código de máquina?

![ej](https://user-images.githubusercontent.com/20797815/57185283-5adb9300-6e96-11e9-8d19-10cc3b8aee54.png)

**Comment by fgbruna** [comment]
Si te fijas en los archivos de ejemplo lo que hacen es guardar la posición de los labels ya que al final eso es todo lo que necesitas de ellos

**Comment by ignacioaraya1995** [comment]
¿Pero el input del disassembler_x86 no era como el enunciado? En el código maquina del enunciado no  aparece la posición de los labels new_iteration ni end_program.

**Comment by Arcoirisky** [comment]
Es como dice @fgbruna :D No necesitas de los labels para poder dar saltos, solo su posición para poder saber la siguiente instrucción que tiene que ser ejecutada :D

**Comment by NoemiCC** [comment]
Ok, gracias!

**Comment by javierabao** [comment]
Sobre lo mismo, en el ejemplo del enunciado cuando hace `JG Dir` en el código de máquina, la línea siguiente envía la dirección al label "start" (`Dir=label:start`), siendo que en el código assembly el loop correspondiente se denomina "loop". ¿Da lo mismo el nombre que le pongamos al label, mientras la dirección a la que apunte esté bien?

**Comment by Arcoirisky** [comment]
@javierabao Al parecer es solo un error de tipeo, debería ser ```Dir=label:loop``` 
Pero sí, da lo mismo el nombre mientras la dirección esté bien y tenga sentido.
