### ISSUE TITLE
Cálculo de delays en un circuito con ciclos

### ISSUE THREAD

**Issue by eiherrera** [IIC2343/syllabus#104]
¡Hola!

Tengo bien claro cómo calcular el retraso en un circuito combinacional, pero no entiendo cómo realizar el cálculo cuando existen loops en un circuito. He revisado los apuntes y buscado en internet pero no he encontrado una solución. 

Utilizando como ejemplo el siguiente circuito:
```
"sequential": [
    {"from":"input", "to":"A"},
    {"from":"A", "to":"B"},
    {"from":"B", "to":"A"},
    {"from":"B", "to":"output"}
]
```
¿Se realiza el cálculo de la misma forma que en un circuito combinacional, es decir, sin contar el loop (`delay(A) + delay(B)`), contando el loop una vez (`delay(A) + delay(B) + delay(A) + delay(B)`) o de otra manera distinta?

**Comment by BSamilla** [comment]
Hola!

Lo que debes hacer es simular el circuito un determintado numero de veces, (de preferencia has que este numero sea configurable) hasta que logres que el delay del loop se vuelva estable, (puedes pensarlo como que estas calculando el delay de una sola puerta cuyo valor desconoces) luego escoges el delay de mayor valor de entre los estables.

No es buena idea subestimar estos valores ya que como habran visto en clases arruinaria el circuito, pero no puedes sobreestimarlos mucho ya que pierdes tiempo por cada clock.

Saludos y exito! :)

**Comment by malopez16** [comment]
Hola! Tampoco lo entiendo. ¿Qué significa "el delay de mayor valor de entre los estables"? ¿Son varias simulaciones? ¿Cómo quieren que definamos exactamente un circuito "estable"? Dado que dependerá directamente del delay de las gates que lo componen, asumo que tendría que ser variable por cada flip flop. Habrían infinitas maneras de hacerlo, en las que habrían infinitos resultados, pero dudo que quieran eso.. Entonces ¿habrá algún estándar/reglas mínimas para evaluar la simulación/modelación?

Gracias

**Comment by malopez16** [comment]
Si hay componentes con delays fijos y en la #100 se ejemplificó con el delay de un flip flop, que tb es fijo, entonces por qué el delay sería variable?

**Comment by jheysen** [comment]
Estás tomando el flip-flop como un componente cerrado de alto nivel (i.e compuerta), mientras que un loop explícito del circuito tienes que ver qué pasa.

**Comment by malopez16** [comment]
Entiendo, pero en es caso sigo con la misma duda de @fgbruna , a qué se refieren entonces con que el delay de un loop se vuelva estable? a la cantidad de loops que se requieren para que los valores no cambien más? No se estarán refiriendo entonces al tiempo para que el **resultado** del loop se vuelva estable? Creo que esa sutileza es la que está confundiéndome

**Comment by FranLucchini** [comment]
Con que el delay de un loop se vuelva estable nos referimos a que el valor de los outputs del circuito total tengan valores fijos.

**Comment by naquiroz** [comment]
@FranLucchini  no me queda claro una cosa. Encuentro que esa definición de estable es media subjetiva. Me explico.

Supongamos tengo un ciclo que luego de n iteraciones, los tiempos son estables, y el output es siempre 1. Cómo puedo yo asegurar que la iteración numero n+1 va a ser 0?. Porque, por lo que entendí por la definición que diste, uno debe detenerse cuando las iteraciones tengan un output constante (fijo), pero encuentro que el decidir cuando eso ocurrirá, es bien subjetivo. Queda a nuestro criterio nomas?

**Comment by FranLucchini** [comment]
@naquiroz por qué podría suceder que cambie en la iteración n+1 si el input es fijo? Se te ocurre algún caso o es una duda teórica?

**Comment by naquiroz** [comment]
@FranLucchini  Es una pregunta teórica, pero un caso que se me ocurre es que una de las compuertas (un `not gate` por ejemplo) tenga un delay de `(n + 1) * tiempo_promedio_iteración`. En ese caso, esta compuerta permanecería inactiva hasta la iteración n+1, por lo que no veríamos su resultado hasta la iteración numero `n+1`, y como asumimos en la iteración `n`, que el output es estable, entonces nuestro resultado sería incorrecto.

Pero mi punto va mas allá. La pregunta es, en qué momento consideramos que un circuito alcanzó la estabilidad?

**Comment by jheysen** [comment]
Puedes ver en primer lugar si queda alguna compuerta que pueda cambiar estado en el futuro
Otra opción es dar un horizonte razonable (y ojalá configurable) hasta donde se va a considerar.

**Comment by naquiroz** [comment]
@jheysen  Gracias!

**Comment by Vicentevialpaul** [comment]
@FranLucchini en el caso de los loops, se tiene que sumar al delay el tiempo que demoro en estabilizarse? o sólo se cuenta el delay en el momento que ya esta estabilizado?

**Comment by FranLucchini** [comment]
Hola,

No puedo responder a esa pregunta directamente. Pero, te puedo mencionar que la respuesta está relacionada con la razón por la que queremos calcular el delay máximo.

**Comment by jmwielandt** [comment]
Es que considerando que no hemos visto en clases inestabilidad de circuitos ni sale en los apuntes, no estoy considerando eso. 
No creo que sea criterioso centrar una tarea en 100% lo que salga en google, de ahí mi supuesto.
Por favor, corrígeme si no es un supuesto válido.

**Comment by jheysen** [comment]
La tarea está centrada en que apliquen lo que han visto en clases, y entiendan también ciertas limitantes a las que los computadores están sometidos.

**Comment by eiherrera** [comment]
Sólo para confirmar, pero entonces ¿calculamos el período luego de confirmar que **todos** los outputs son estables? Y de lo contrario asumimos período infinito. ¿O bien necesitamos que sólo un output sea estable, y calculamos el período sólo para los outputs estables?

**Comment by Geeermy** [comment]
¡Hola @eiherrera !

1. No es necesario que todos los _outputs_ sean estables. Lo que buscamos es que, de los estables, busquen el de mayor periodo y a partir de ese determinen la frecuencia máxima.

2. Por si queda la duda: No les entregaremos circuitos donde todos los _inputs_ generen inestabilidad (ver #109).

Y aprovecho de aterrizar un poco la pregunta de @jmwielandt : Piensa, por ejemplo, en una compuerta ```and``` que tiene dos entradas, una proveniente de la salida de un conjunto gigante de compuertas interconectadas entre sí, y la otra proveniente directamente del _input_. Si la que proviene del _input_ se establece como 0, sabes que realmente **no necesitas** esperar la salida de este conjunto gigante dado que la salida de tu compuerta ```and``` no cambiará (será 0 sí o sí). Por eso el supuesto que indicas no es válido, dado que **realmente depende** de la compuerta con la que estás trabajando, como indicaba @jheysen . Esperamos que realicen ese análisis para que vean las combinaciones de _input_ en las que es necesaria una espera mayor para poder obtener la salida correcta del circuito.

¡Mucho éxito y que estén bien! 👾

**Comment by naquiroz** [comment]
@Geeermy  Entonces si mal no entiendo:

Si un circuito tiene un `out1`  y un `out2`, no es necesario que los dos sean estables? Basta que uno lo sea?

**Comment by Geeermy** [comment]
@naquiroz No, cuando hice referencia a _output_ quise referirme al **vector de _ouput_**.

En el caso que planteas, el _output_ final **no es estable** dado que al menos una de sus salidas no lo es. A lo que voy es que, para una combinación de _inputs_ el _output_ final sea estable en su totalidad. De esos casos (ya que puede haber más de una combinación que genere un _output_ final estable), nos quedamos con el de periodo mayor. ¿Se entiende mejor?

Gracias por la pregunta, lo aclararé un poco mejor en mi mensaje anterior. 😄

**Comment by naquiroz** [comment]
@Geeermy  Sip se entiende mejor ahora, lo único que no me queda claro es, dado un vector de _inputs_ con un respectivo vector de _outputs_ estables, el tiempo de este sería el máximo que demoró en salir el último `outX` de ese vector?

Y luego, dado lo anterior y dado un conjunto de vectores _outputs_ estables: debemos retornar como tiempo máximo de la simulación, el tiempo máximo entre los tiempos de cada vector de outputs estables?

**Comment by Geeermy** [comment]
Solo una acotación: No es el tiempo máximo el que pedimos, sino que la frecuencia. 😃

Con respecto al resto: 👍

**Comment by savelozo** [comment]
@Geeermy me genera una duda ya que dijiste "Lo que buscamos es que, de los casos estables, busquen el de mayor periodo y a partir de ese determinen la frecuencia máxima." Sin embargo para obtener la mayor frecuencia necesitamos obtener el menor período, ya que son recíprocos o no?

**Comment by Geeermy** [comment]
Con frecuencia máxima me refiero a **la frecuencia máxima que puede tener el circuito.** Si tiene una frecuencia mayor, significa que consideran un periodo _menor_ y, por ende, pueden tener problemas con los resultados del circuito. ¿Se entiende?

No se compliquen por esto, es simplemente la fórmula que les compartió @naquiroz jaja 😅.

**Comment by ajahr95** [comment]
@Geeermy respecto a lo ultimo, la frecuencia max permitida seria entonces tomar el caso en que se demora menos mi circuito y calcularlo bajo f= 1/T ? O el caso en que mi circuito se demora mas? ya que eso me daria un limite de frecuencia en donde sobre esta tendria problemas

**Comment by valerojasm** [comment]
@Geeermy +1 ☝️

**Comment by savelozo** [comment]
@Geeermy +1 ☝️ 😄

**Comment by Geeermy** [comment]
Paciencia, estoy escribiendo 😆

**Comment by Geeermy** [comment]
@ajahr95 es el **segundo caso**. Pensémoslo así: tengo dos casos estables tales que _p1_ < _p2_.

Ahora, supongamos que establezco _f1_ = _1/p1_ como la frecuencia de mi _clock_. Evidentemente, _f1_ > _f2_. ¿Qué pasa, entonces? Al establecer _f1_, lo que pasará es que al encontrarme en el caso donde toma _p2_ generar el _output_, este no va a alcanzar a terminar ya que itero mi circuito a partir de un **periodo menor**.

Por ende, si no quiero tener problemas, debo establecer _f2_ como mi frecuencia. Esta es la **máxima** que puedo tener, porque si llegase a tener una **mayor**, entonces **voy más rápido que la ejecución**. Si tengo una menor, me da lo mismo, porque de todas formas no tendría problemas de sincronización ya que todo el _output_ alcanzaría a actualizarse, el tema problemático es el de frecuencias mayores que no me permiten que se actualice por completo.

@savelozo @valerojasm ¿Se entiende mejor ahora por qué hablamos de **frecuencia máxima**? 😅.

**Comment by Geeermy** [comment]
@naquiroz Con respecto a tu **edit**, si hay al menos una señal inestable en ese vector, **no se considera estable.** Si te refieres a que en las últimas _n_ iteraciones el vector _output_ se mantuvo igual, sí puedes considerarlo. :)

**Comment by jmwielandt** [comment]
@Geeermy retomando lo que me dijiste más arriba de una compuerta and que recibe del input y de un circuito gigante con muchas cosas... el clock no puede depender del input (al menos según tengo entendido).
Piensa que metes eso en un computador y dices "ah, si el input es 0 no necesito esperar al circuito, entonces mi clock es de periodo infinitesimal". Entonces tienes un computador que funciona a veces y otras no.
El análisis que estoy haciendo es que si tienes un circuito con la siguiente estructura:
A -> B
C -> B
B -> output
con A, B y C componentes cualesquiera, el periodo mínimo del clock debe ser: `max(A, C) + B` (sustituyendo las letras por los valores de los delays respectivos.
Siguiendo un razonamiento de este estilo es cómo se llega a T = 14.5 en el circuito de ejemplo, como sale en la primera respuesta de la issue #103 .
Toda mi tarea se basa en aplicar estos principios :/
Como dijo jurgen más arriba, "La tarea está centrada en que apliquen lo que han visto en clases (...)" y en clases no hemos visto estabilidad, por tanto asumo que no es algo que debamos considerar.

Y bueno, esto también es una duda: si tengo un circuito real va a estar arrojando cosas todo el tiempo. ¿No es irreal eso de sacar como output de un circuito solo los valores que se estabilizan?
Si tengo un valor output_estable_1 y otro output_estable_2, pero en el medio tengo 15 valores inestables, para el circuito que viene después (que recibió todos esos 17 valores) no es como si los 15 del medio no hayan existido.

**Comment by naquiroz** [comment]
@Geeermy  me refería a lo segundo, gracias!

**Comment by Geeermy** [comment]
@jmwielandt Iré por puntos:

1. Era un caso puntual el que puse, obviamente si consideras _input_ = 1 en el ejemplo que puse vas a tener que esperar a que se obtenga el resultado del otro circuito gigante, eso no lo he negado. Tampoco dije en ningún momento que por eso el caso del _output_ más rápido determinaba el _clock_. Lo que quise decir es que las combinaciones de _input_ **sí pueden influir** en el tiempo que te toma obtener un _output_, por lo que **merece la pena** revisar los distintos casos existentes, ya que quizás tu circuito puede tener compuertas que, independiente de la combinación, su resultado no influye en el _output_ final, por lo que no necesitas llegar y sumar sus _delays_, ¿me explico? Si estableces siempre un clock mínimo en base a tu pensamiento, siempre funcionará en la práctica, eso no se descarta. Lo que estoy diciendo es que podría existir la opción de establecer un clock más rápido sin influir en la ejecución del circuito, eso es lo que buscamos al pedirles la frecuencia máxima.

2. Estás pensando siempre en el computador básico, cuando no te lo estamos pasando. Recuerda que estamos trabajando con circuitos específicos, así que necesitas desprenderte un poco de él. En un computador básico todo este tema es mucho más complejo, por eso analizamos esta tarea con circuitos particulares para que puedan ver su comportamiento en casos mucho más acotados.

3. Quizás en clases no se vio en particular lo que es _estabilidad_, pero entendiendo que es, básicamente, la salida de un valor constante de un circuito, no veo la imposibilidad de aplicar los contenidos vistos en clases. Más aún, si tienes problemas entendiéndolo y tu búsqueda personal no ha sido fructífera, tenemos disponibilidad y disposición para juntarnos con ustedes y verlo en profundidad, ya lo hemos hecho con otros compañeros tuyos.

4. Con tu última duda, nuevamente estás pensando en esta situación como un computador. Estamos analizando un circuito **particular**, así que a pesar de que puedan haber 15 casos inestables, no va a influir en nada más, estamos analizando un caso particular.
