### ISSUE TITLE
Parte 2: Overfloat

### ISSUE THREAD

**Issue by SebaCardenas** [IIC2343/syllabus#104]
Hay que hacerse cargo del Overfloat en la parte dos? si es así tenemos que generar un error al sumar por ejemplo 1111111111111111 + 00000000000000001 = 0000000000000000 en 16 bits

**Comment by Hernan4444** [comment]
@SebaCardenas precisamente. Y te sugiero revisar las señales porque hay una involucrada en esa.

Saludos!!

**Comment by SebaCardenas** [comment]
Claro, entonces la señal Z tendrá que ser 0 y no 1 verdad? Ya que hay que hacerse cargo

**Comment by Hernan4444** [comment]
@SebaCardenas la señal Z se prende cuando el resultado es 0, en este caso es 0 por lo que se debe prender. 

Saludos!
