### ISSUE TITLE
Problemas de acceso a cuenta xilinx desde maquina virtual

### ISSUE THREAD

**Issue by bedefrunner** [IIC2343/syllabus#105]
Hola! Soy mac y me descargue windows 10 en una maquina virtual. Me hice una cuenta en xilinx desde mac os pero no puedo acceder a ella desde windows 10, entonces no me puedo descargar vivado. Traté de cerrar la cuenta en xilinx para registrarme de nuevo, pero esta vez registréndome desde windows 10 (quizás eso resuelve el problema), pero en ningún lado se me da la opción de cerrarla.

**Comment by FranLucchini** [comment]
Que problema tan extraño, me puedes mandar screenshots de lo que te aparece?

**Comment by bedefrunner** [comment]
![screen shot 2017-09-01 at 19 41 22](https://user-images.githubusercontent.com/20782509/29990034-a42461d8-8f4d-11e7-9c0f-581a099e9e55.png)

Esto es todo lo que me muestra, me hace ingresar los datos para entrar, los ingreso, apreto enter, se refresca la pagina y me muestra esto mismo. O sea, no pasa nada.

**Comment by FranLucchini** [comment]
Ya activaste tu cuenta, o no? Si no te funciona, voy a tratar de mandarte el ejecutable.

**Comment by bedefrunner** [comment]
si, la active, aun asi no funciona

**Comment by adisrael** [comment]
Hubo alguna solución para esto... yo tengo un problema similar, también tengo Mac OS y tengo una máquina virtual con Windows 8.5, no tuve problema en la creación de la cuenta, de hecho accedo bien pero luego al completar los datos para descargar el programa (dirección, país, etc.) me sale este error:
![image](https://user-images.githubusercontent.com/17645654/30220945-d7c78ebc-9497-11e7-8532-3c03aa4069d9.png)
pero no me dice que campos de información están mal, he probado con diversas direcciones y no hay diferencia...

**Comment by FranLucchini** [comment]
Personalmente, no sé qué puede estar pasando. Puedes ser más específico sobre los datos que estás ingresando? Obviamente, mándalo por mail si es que es información privada.
