### ISSUE TITLE
[Tarea 3 - Placa] Duda Control Unit

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2343/syllabus#105]
Todas las instrucciones que debe soportar el Control Unit son las que están especificadas al final del enunciado? O hay alguna simplificación?

**Comment by Arcoirisky** [comment]
Todas las instrucciones que debe poder ejecutar tu computador deben ser todas las que han sido declaradas por la Isa (el montón de tablas que está a lo largo del enunciado) :D

**Comment by frvalenzuela** [comment]
Hola! 

Solo agregar revisar la issue #96 , donde se mencionan unas modificaciones para la parte de placa. 

Saludos!

**Comment by frvalenzuela** [comment]
Hola!

Edite la issue antes mencionada para volver a revisar las modificaciones.

Lamento las molestias.

Saludos!
