### ISSUE TITLE
[Tarea 3] Paso de parámetros en subrutina B

### ISSUE THREAD

**Issue by FloValdes** [IIC2343/Syllabus#105]
Hola, ¿dónde se pasan los parámetros (el número de horas) para la subrutina b, usando stdcall? ¿Antes de llamar al boton_2? ¿O después (y llamando a otra subrutina adentro de boton_2?)?

Gracias.

**Comment by josefinaijb** [comment]
Buenas! Yo lo que hice fue llamar a la subrutina A dentro de mi subrutina B, la cual se inicia por el boton_2. En definitiva, pienso que la subrutina A con el boton_1 no tendría mucha más utilidad que ser demostrativa en el programa.  Pero me entra la duda si eso es legal para el puntaje completo o no.

**Comment by Allmoz** [comment]
Como dice el enunciado "Una vez atendida la interrupción por la ISR correspondiente, su programa debe llamar la subrutina apropiada de acuerdo a la última interrupción atendida."

Por lo que es programa y no las ISR (Interuption Service Rutine) las que deben llamar a las subrutinas requeridas.  Se termina de atender una interrupción al llamar la instrucción IRET.

Revisen la materia para entender como completar correctamente una ISR,

Las 4 cosas que tienen hacer segun enunciado es:

"Para esto deberá **definir variables**, **escribir subrutinas,** **completar correctamente
las ISRs** y **escribir el código del programa**."

Saludos

**Comment by Marialuisaclaro** [comment]
Hola @Allmoz ,
No entiendo la parte de 
"Por lo que es programa y no las ISR (Interuption Service Rutine) las que deben llamar a las subrutinas requeridas. Se termina de atender una interrupción al llamar la instrucción IRET."
En las ISR se deben llamar a las subrutinas correspondientes o no? Por ejemplo, en la ISR del boton_1 se debe llamar a la subrutina A.

**Comment by Allmoz** [comment]
Tienes dentro del código una sección donde completar el programa principal. El programa principal va a ser interrumpido y se atenderá una de las ISR, una vez que se regrese al programa principal este debe llamar a la subrutina que corresponda.
