### ISSUE TITLE
Duda tiempo de retardo Flip Flop

### ISSUE THREAD

**Issue by Cschavez** [IIC2343/syllabus#105]
Hola!
No sé si con "loops" se refieren a lo mismo que diré, pero en el caso que en la secuencia exista una compuerta que va hacia la 'entrada' D del flip-flop, debo considerar nuevamente el tiempo de retardo del flip flop? o solo considero el tiempo de retardo cuando se actualiza el valor de la puerta 'C' del flip flop?

Gracias!

**Comment by Cschavez** [comment]
Además, en las compuertas como xor, or, and que tienen dos 'inputs', el tiempo de retardo se considera desde que llegan valores a sus dos entradas cierto?

**Comment by naquiroz** [comment]
Tengo la misma duda!

**Comment by jnlarrain** [comment]
Respecto a los loops, siempre que se cambia una entrada de un operador lógico va a haber una salida. Por esto el tiempo de retardo se considera cuando llega un valor a un operador lógico. Por otro lado, considera el flip-flop como un componente que tiene una entrada y una salida, y sus respectivas demoras.
