### ISSUE TITLE
Ayudantía 3 | Pregunta 2 | Microarquitectura

### ISSUE THREAD

**Issue by narierao** [IIC2343/Syllabus#106]
Hola! estaba revisando la ayudantía y no me queda claro el cómo en el componente "Generador señal cargar pc" se hace la comparación de los dos registros dado que solo les llega una entrada de 16 bits. ya que lo modelé de manera personal y tuve que usar el valor de la ALU(haciendo resta) y enviándolo a un componente parecido.

Gracias!

**Comment by jmwielandt** [comment]
Al generador le llegan dos valores de los registros en un bus de 16 bits.
Lo que hago es una operación XOR entre ellos y luego hace un OR o un NOR generalizado con el resultado, según la señal de control "eq?". Un nor para el beq y un or para el bne.

**Comment by stmorales** [comment]
Hola! En esta pregunta debemos explicitar las señales de control para cada instrucción? O basta con explicar con palabras lo que hace la microarquitectura?

**Comment by jmwielandt** [comment]
@stmorales mira el anuncio que acabo de mandar. (Creo que te refieres a la I3, esta issue es de la ayudantía).

**Comment by stmorales** [comment]
Jajaja si! Perdón! Ahí lo vi, gracias!
