### ISSUE TITLE
[Tarea 3 - Programada] RET

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2343/syllabus#106]
Hola, me podrían explicar porque hay dos RET en el código máquina del enunciado y por que sus opCodes son distintos.

Gracias

**Comment by jmwielandt** [comment]
Porque para volver de una subrutina necesitas el doble de ciclos que cualquier otra instrucción en esta isa, entonces esto se soluciona haciendo que tome dos opcodes y en la práctica `RET` sean dos instrucciones. 
En el assembler deben crear el segundo y poner los opcodes correspondientes.

**Comment by frvalenzuela** [comment]
Hola! 
Complementando lo que dice Jose. 
Existe dos RET, uno que  no recibe parámetros, y otro que si. El primer RET (que no recibe parámetros) es para retornar la salida de una subrutina de uso común (solo con SP). 

Mientras que el segundo RET (que si recibe parámetros) retorna una salida de alguna función utilizando el registro BP y stdcall (ya sea para alguna función recursiva o una función con parámetros). 

Espero que eso resuelva tu duda.

Saludos !

**Comment by elramirezv123** [comment]
@frvalenzuela Considerando lo que dijo @jmwielandt, con el primer RET te refieres a 0o0051 y 0o0052? Y para el segundo 0o0065 y 0o0066 ?

**Comment by frvalenzuela** [comment]
Hola @elramirezv123 !

Si exactamente lo que dices!

Saludos!

**Comment by seba608** [comment]
Hola,

En el caso del RET que no recibe parámetros, entiendo que se debe traducir como: 0051, 0000, 0052 y 0000, pero en el caso del RET que recibe parámetros, deben ir los otros opcodes pero con que valor para las variables? ambos con Lit? La misma duda aplica para los POP.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @seba608! 

Basta con que luego del primer opcode se de el literal, ya que en el tercer ciclo tendrá la información suficiente para hacer la operación. Ahora si pones el literal despues ambos opcodes, no afectará el resultado. 

Saludos !

**Comment by Jj1martinez** [comment]
Hola, tengo ciertas dudas con la instrucción RET

1.- Puede haber más de un RET por programa ? Que aparezca por ejemplo un RET y luego más abajo un RET Lit o RET.
2.- Si es que fuera solo un RET por programa, siempre debajo de este estarían las variables?

Saludos

**Comment by frvalenzuela** [comment]
Hola @Jj1martinez 

Pueden ser varios RET por programa, (pueden haber más varias funciones definidas en un mismo programa).

Saludos!

**Comment by Jj1martinez** [comment]
Y por ejemplo, en el disassembler, cómo podríamos ubicar el último RET para saber cuando empiezan las variables? Ya que por ejemplo si es un RET, los últimos Opcodes serían 0o0051,0o0000,0o0052,0o0000 pero eso podría ser equivalente a unas variables definidas después del RET,  51,0,52,0.

**Comment by Jaluco** [comment]
No me queda claro, los RET siempre vienen en pares? Osea si aparece un ret se traduce siempre como dos opcodes con sus literales(o nulos)?

**Comment by frvalenzuela** [comment]
Hola @Jaluco !

Asi es !

Saludos!
