### ISSUE TITLE
Notas Recorrección E2

### ISSUE THREAD

**Issue by Dalal15** [IIC2343/syllabus#106]
Hola,

Cuándo estarán las notas luego de la recorrección de la entrega 2? Sería bueno tener ese feedback antes de enviar la recorrección de la E3. 

Saludos!

**Comment by Hernan4444** [comment]
Hola, el ayudante ha tenido algunas complicaciones. Es por ello que te subo aquí el zip con los resultados de cada test (secuencia de como cambia A y B) [Algoritmos E2 solucion.zip](https://github.com/IIC2343/syllabus/files/2172225/Algoritmos.E2.solucion.zip)

Con lo anterior pueden tener un ligero feedback de como estuvo tu entrega 2.

Saludos ✌️

**Comment by Dalal15** [comment]
Gracias!
