### ISSUE TITLE
[Tarea 3] Free evaluation period has expired

### ISSUE THREAD

**Issue by josem7** [IIC2343/Syllabus#106]
Hola, cuando intento correr alguno de los ejemplos me sale  

>your free evaluation period has expired.

Qué puedo hacer en ese caso?

**Comment by mbvanwersch** [comment]
Hola! Pudiste solucionarlo?

**Comment by josem7** [comment]
Hola, si logré solucionar el problema. Hablé con el profesor y me dijo que lo liberaron con el serial 27R3VDEFYFX4N0VC3FRTQZX. El usuario puede ser cualquiera.
