### ISSUE TITLE
Duda sobre cu

### ISSUE THREAD

**Issue by miortiz1** [IIC2343/syllabus#107]
La CU puede mandar más de 12 señales aunque solo tengamos 12 bits?

**Comment by frvalenzuela** [comment]
Hola @miortiz1 !

Podría mandar millones de señales si tuviésemos un montón de componentes! El tamaño de nuestras palabras o lo que reciben algunos componentes como los registros, no es un limite para el manejo de señales.

Por ejemplo, los registros Ax y Bx reciben señales "enable", que les permite cargar lo que entra en será guardado (que si es de 12 bits). Pero si algún fabricante de registros quiere darle más poder al registro podría dar más señales para que el registro internamente hiciera más cosas, como por ejemplo una señal "reset" que haga que todo dentro el registro se transforme a cero. Esto no cambiaría cuantos bits puedo guardar en mi registro, pero si aumentaría la complejidad interna del mismo y las señales que expulsa mi control unit.

Espero que quedase más claro, si no fuese así hacerlo saber!

Saludos!

**Comment by miortiz1** [comment]
Si quedo claro
