### ISSUE TITLE
T4 - Supuestos

### ISSUE THREAD

**Issue by Geeermy** [IIC2343/syllabus#107]
¡Hola a todas y a todos!

En pos de que puedan terminar su tarea más rápido y complicándose menos, pueden (recomendado fuertemente) seguir los siguientes supuestos:

1. Dos _flip-flops_ **solo** estarán conectados entre sus compuertas ```Q``` y ```D```. Es decir, el estado de un _flip-flop_ **nunca será** el ```clock``` de otro. Esto en el JSON se podrá ver así:

```
{"from": "ffd1", "to": "ffd2"}
```
 Es decir, de la mera conexión entre ```ffd1``` y ```ffd2``` sabemos que la conexión es entre la compuerta ```Q``` de ```ffd1``` y la compuerta ```D``` de ```ffd2```.

2. Al tener un circuito **con** _flip-flops_, **todos** compartirán el mismo _input_ de ```clock```. Es decir:

```
{"from": "input1", "to": "ffd1", "gate": "C"},
{"from": "input1", "to": "ffd2", "gate": "C"},
{"from": "input1", "to": "ffd3", "gate": "C"},
...
```

Esperamos que estos cambios les ayuden a acotar los casos que deben abarcar. :-)

**Comment by frvalenzuela** [comment]
Esto quiere decir que no debemos preocuparnos del caso de flip flops en serie?

**Comment by BSamilla** [comment]
@frvalenzuela 

Aun pueden existir flip-flops en serie, entendiendo como "en serie" que la salida de Q de uno este conectada a la entrada D de otro. 
Lo que no puede ocurrir es que la salida Q de un flip-flop este conectada a la entrada C (clock) de un segundo flip-flop.

Saludos!

**Comment by frvalenzuela** [comment]
Ahh okey, entendido muchas gracias!

**Comment by malopez16** [comment]
¿Podemos asumir que siempre habrán 2 flip flops o más?

**Comment by Cschavez** [comment]
Hay algo que no me queda claro, entonces si es que no voy de un flip flop a otro, NO puedo asumir que el flip flop está conectado por 'C', por ejemplo, no puede pasar
{"from": "not1", "to": "ffd1"}, pero si : {"from": "not1", "to": "ffd1", "gate": 'C'} o {"from": "not1", "to": "ffd1", "gate": 'D'}

**Comment by BSamilla** [comment]
@Cschavez 
Exacto como mencionas el cambio solo ocurre para la conexión entre 2 flip-flops, quedando como:
{"from": "ffd1", "to": "ffd2"}

Mientras que la conexión entre flip-flops y otras compuertas se mantiene como:
 {"from": "input1", "to": "ffd1", "gate": 'C'}
o
{"from": "not1", "to": "ffd1", "gate": 'D'}

Saludos!
Mucho éxito!
