### ISSUE TITLE
Interrogación 3 | Pregunta 2 | Duda comandos

### ISSUE THREAD

**Issue by arbiocanpion** [IIC2343/Syllabus#107]
Hola!

Estaba resolviendo la pregunta 2 de la interrogación y me surgio la siguiente duda, ¿Que deben hacer las instrucciones JOD y JEV?. 

Me explico, por ejemplo JEQ chequea que los dos numeros del reg sean iguales, ¿En este caso que chequearan estas instrucciones?

Gracias desde ya, y disculpen si la pregunta es un poco básica, pero no encontre el significado de estas dos operaciones

**Comment by jmwielandt** [comment]
JOD -> salta si la salida de la AU/LU es impar.
JEV -> salta si la salida de la AU/LU es par.

**Comment by arbiocanpion** [comment]
Muchas gracias!
