### ISSUE TITLE
[Tarea 3] Problemas con el robot

### ISSUE THREAD

**Issue by movalle4** [IIC2343/Syllabus#108]
Hola

Tengo un problema en la parte del robot.

En la documentación sale lo siguiente : "You should always check bit#1 of status register before sending data to port 9, otherwise the robot will reject your command and "busy!" will be shown."

Cada vez que voy a enviar data al port 9 chequeo el bit#1 usando la siguiente subrutina que se encuentra en los ejemplos del syllabus.

waitcommand:
      loop1:  IN AL, 11  
              AND AL, 10b
              JNE loop1              
              RET

El problema es que el robot a veces está "busy!" como si le estuviera mandando instrucciones sin chequear si está disponible y esto provoca que el robot deje de ejecutar acciones que debería ejecutar. ¿Estaré haciendo algo mal o cómo puedo solucionarlo?

**Comment by Allmoz** [comment]
El robot detecta cuando hay un cambio en el comando. Por lo que tienes que alternar "comando repetidos" con comando de no hacer nada. Tienes que esperar a que este disponible despues de cada uno de esos comandos. Puede que en algunos casos el robot  no alcance aún a leer el comando que le mandaste y por ende no te diga que está ocupado aún,  en esos casos puedes hacer un pequeño ciclo for para gastar un par de ciclos despues de mandarle el comando, o algunos NOP.

Saludos
