### ISSUE TITLE
Interrogación 3 | Pregunta 7 | Dudas sobre valores R1 y R2

### ISSUE THREAD

**Issue by t-schilling** [IIC2343/Syllabus#108]
Cuando se habla de R1 y R2 en los comandos, se refiere a cualquier par de registros? O a dos registros en particular? En otras palabras, los valores R1 y R2 pueden referirse a cualquiera de los 4 registros (A,B,C,D) o son siempre los mismos dos registros?
Gracias!

**Comment by ceosorio** [comment]
Hola @t-schilling !

Cuando nos referimos a R1 y R2, nos podemos referir a cualquiera de los 4 registros. Te recomiendo revisar el [readme](https://github.com/IIC2343/Syllabus/blob/master/interrogaciones/i3/Pizzarra%20I3.md) que subimos :)

Mucho éxito ✨
