### ISSUE TITLE
Duda con respecto al valor de una compuerta, con su respectivo delay

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2343/syllabus#108]
Cuando los valores de entrada de una compuerta lógica cambian en menos tiempo que el valor de salida de dicha compuerta, ¿ dicho valor de salida se va actualizando con una diferencia de tiempo igual al de los cambios?
Por ejemplo si yo tengo una compuerta AND que tiene un de delay de 8 unidades de tiempo, digamos que esta compuerta tiene entradas A y B. Si A = B = 1, y luego de 8 unidades de tiempo yo comienzo a cambiar el valor A de 0 a 1, cada 2 unidades de tiempo. La compuerta AND cambiara su valor a los 10, 12, 14, 16... unidades de tiempo, o acaso cambiara su valor a las 16 unidades de tiempo?

**Comment by jnlarrain** [comment]
Hola!!! 

El tiempo de propagación de una compuerta lógica es cuanto se demora en salir el resultado de un input. es decir que si tienes una entrada que cambia cada 2 y un delay de compuerta de 8, las salidas son en 10, 12, 14..... 

Saludos

**Comment by frvalenzuela** [comment]
Me quedo claro! muchas gracias!

**Comment by malopez16** [comment]
Pero si tenemos un tiempo de propagación menor al tiempo de cambio de entrada, podría producirse inestabilidad en el componente.. o me estoy confundiendo y eso sólo ocurre en los flip flops?

**Comment by jheysen** [comment]
Tiempo de cambio de entrada para una compuerta dada?

**Comment by malopez16** [comment]
Si me refiero por ejemplo si tengo una compuerta cualquiera cuyo tiempo de propagación es de 5 y le hago cambios en el input cada 2, por lo que no ha alcanzado a cambiar su valor de output completamente aún, pero ya le he realizado cambios en su input

**Comment by Geeermy** [comment]
Esa es la gracia de la tarea, calcular el tiempo máximo para que eso **no pase** (puedes pensar en la frecuencia no solo como el cambio en el _clock_, sino que también como el cambio de los valores del _input_).

Establecido lo anterior, **no es necesario** que definas tú un tiempo de cambio por _input_, ya que lo que debes hacer realmente es sacar "fotos" de lo que pasa en cada en un circuito para cada combinación de _inputs_, y obtener el tiempo total que toma obtener el _output_ en cada una de estas para así obtener el _delay_ máximo entre todas estas. Más aún, no les definimos un tiempo de cambio de entrada ya que, en el fondo, ese es el resultado que debiese obtener su programa.

¡Éxito! 🙉
