### ISSUE TITLE
[Tarea 3 - Placa] Operaciones con BP

### ISSUE THREAD

**Issue by MrEarle** [IIC2343/syllabus#108]
Hola,
Las operaciones `MOV` en el manejo avanzado de stack utilizan el valor en BP para realizar sumas y restas. Asumo que esto se haría en la ALU.

El problema es que la unica manera de que llegue el valor de BP a la ALU es a traves de la memoria principal. No me queda claro como funcionaría en ese caso, porque para acceder a un literal en la memoria principal, tiene que estar escrito, y no puede ser el que esta entrando por DataIn a no ser que tambien se este escribiendo al mismo tiempo.

**Comment by frvalenzuela** [comment]
Hola Benjamin!

Lo que asumes es incorrecto. Las sumas y restas lo hace el componente Adder/Sub, que se conecta al mux addres. De esta forma no tienes que ocupar la ALU y no generá el problema que indicas.

Si algo no quedo claro, favor hacerlo saber.

Saludos!

**Comment by MrEarle** [comment]
Pero, por ejemplo, con el comando `MOV Ax, [BP + Lit]`, la operación que se ejecuta es `Ax = Bp + Lit`.

Para esto hay que escribir en el registro `Ax`.
Para escribir en el registro `Ax`, se necesita el valor a escribir en la ALU.
Entonces, de alguna manera y en algun momento, la operación debe pasar por la ALU.

Mi pregunta es, cuando y como? Ya que no encuentro (puede que no lo esté viendo) una ruta para hacer esto que no pase por Main Memory.

**Comment by frvalenzuela** [comment]
Hola Benjamín!

En este caso hubo un error de nuestra parte al describir la operación que se ejecuta. Debería ser `Ax = Memory[Bx+Lit]`

Lamento los inconvenientes que esto pudo haber causado.

Saludos!

**Comment by MrEarle** [comment]
Aaaah ya.
Muchas Gracias!

**Comment by MrEarle** [comment]
Asumo que es `Ax = Memory[BP + Lit]` o no?

**Comment by frvalenzuela** [comment]
Hola Benjamín!

Sip, así es. De todas formas fue actualizado el enunciado con el error de la operación solucionado.

Saludos!

**Comment by mundurragac** [comment]
@frvalenzuela Lo antes mencionado es el opcode 0o0057, pero en el enunciado actualizado, la operación sigue siendo "Ax = Memory[Bx+Lit]". Entonces asumimos que ninguno de stack avanzado ocupa la ALU?

**Comment by Arcoirisky** [comment]
No puedes asumir tal cosa D: mira bien las issues porque ahí se hace la diferencia en 3 instrucciones modificadas.

**Comment by mundurragac** [comment]
No entiendo, no estan hablando de la instruccion 0o0057??

**Comment by frvalenzuela** [comment]
Hola @mundurragac !

La instrucción 0o0057 dice `Ax = Memory [BP + Lit]`  NO BX !! Para realizar dicha suma existe el componente Adder/Sub cerca del registro BP.

Saludos!

**Comment by frvalenzuela** [comment]
Hola nuevamente! 

Le corrijo, es como dices hasta la 62!! 

Para que quede más claro toda instrucción con corchete cuadrado significa que será guardado en memoria. 

Saludos !

**Comment by Arcoirisky** [comment]
Si miras los argumentos está el valor de memoria que está en la posición BP+-Lit O:

**Comment by mundurragac** [comment]
Con respecto a lo mismo, en los jumps el Dir simpre será una referencia de label o puede ser una variable?

**Comment by frvalenzuela** [comment]
Hola @mundurragac !

Será un label.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @mundurragac!

Si debiese ser como dices ! 

Saludos !
