### ISSUE TITLE
[Tarea 3 - Programada]

### ISSUE THREAD

**Issue by seba608** [IIC2343/syllabus#109]
Hola,

Tengo dos consultas:

1) En la tabla de stack avanzado, la última instrucción del MOV el primer operando debería decir Bx cierto?

2) En esa misma sección, puedo asumir que vendrá un símbolo +  o - dentro de las instrucciones que contienen corchetes?

Saludos

**Comment by frvalenzuela** [comment]
Hola @seba608 !

1.  Así es! En unos momentos modifico ese error de typeo
2. Si puedes asumir eso! Pero solo para las instrucciones del MOV de la tabla de stack avanzado.

Saludos!
1.

**Comment by seba608** [comment]
Me surgió otra duda con respecto a la pregunta 2. Si por ejemplo la instrucción es MOV Ax, [BP + Lit], se debe traducir como una linea para el opcode y otra línea para el literal cierto?

**Comment by frvalenzuela** [comment]
Hola @seba608

Así es! 

Saludos !

**Comment by seba608** [comment]
@frvalenzuela Gracias!
