### ISSUE TITLE
Interrogación 3 | Pregunta 7 | Ciclo Instrucciones

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2343/Syllabus#109]
Hola!
Se puede hacer que alguna/s instrucciones se ejecuten en más de un ciclo? Gracias!

**Comment by ceosorio** [comment]
Hola @kelseyfranken!

Si puedes :) Lo que nos importa es que la arquitectura sea funcional, no te preocupes de que las instrucciones deban hacerse en solo 1 ciclo.

Animo! ✨
