### ISSUE TITLE
Test Case RUT

### ISSUE THREAD

**Issue by fabarros** [IIC2343/Syllabus#11]
Hola! Para el caso del problema del dígito verificador hay dos TestCases que son públicos, el #0 y el #1. Resulta que cuando oprimo "Run Code" mi código pasa los dos test públicos, pero cuando coloco "Submit Code" me aparece que los TestCase#0 y TestCase#1 no los apruebo (el TestCase#5 tampoco, todos los demás si). Esto es un problema de mi código o un problema de HackerRank?

Gracias! Saludos.

**Comment by ceosorio** [comment]
Hola @fabarros !

Sucede que si bien al hacer "Run Code" te dice que son `TestCase#0 `y `TestCase#1`, cuando haces submit, esos test pueden cambiar de número. (Si colocas el mouse sobre los test que pasaste, habrán 2 que dicen "sample"). Entonces, dentro de los test que sí pasaste están los públicos, solo que con otro número de TestCase.

Espero esto haya resuelto tu duda :)

**Comment by jrrosas** [comment]
Hola! 

Cuál debe ser el output si como input se recibe un string sólo con caracteres especiales?

Gracias! Saludos.

**Comment by ceosorio** [comment]
Hola @jrrosas !

Ese caso no va a pasar durante la tarea, pero si quieres puedes asignarle un valor por default a tu variable.

Éxito! 😄
