### ISSUE TITLE
[T01 Equivalencia] Cantidad de compuertas equivalentes

### ISSUE THREAD

**Issue by cdlepe** [IIC2343/syllabus#11]
Hola! 
Quería saber si hay alguna restricción respecto a la cantidad de compuertas NAND o NOR que usemos para generar la equivalencia con el circuito original o debemos intentar "optimizar" la conversión? 

Gracias 😄

**Comment by ariel-m-s** [comment]
Hola @cdlepe!

No hay ninguna restricción en cuanto al número de compuertas utilizadas. Tampoco es necesario optimizar el circuito de ninguna manera.

La única restricción es que el circuito debe componerse únicamente de compuertas NAND o únicamente de compuertas NOR.

Salutres

**Comment by Arcoirisky** [comment]
@cdlepe

Complementando con la respuesta anterior, ten en cuenta que la cantidad de inputs y outputs deben mantenerse en ambos circuitos. 

Piensa que estás cambiando una caja negra que recibe N inputs y libera M outputs por otra compuesta por Nands y Nors. Así que ojo con eso :D Que sea equivalente significa que existe la misma tabla de verdad para ambos circuitos. 

Eso~
Saludos~

**Comment by ignacioaraya1995** [comment]
Tienen tests para corroborar mis respuestas?

**Comment by CristobalHV** [comment]
Hola! 
La idea es que ustedes mismos puedan desde el enunciado construir sus propios casos de prueba.
Si nosotros les entregamos los tests, harán su tarea enfocándose solo en los tests y no en ver que su tarea efectivamente hace lo que debería hacer.
Saludos!
