### ISSUE TITLE
[T01] Base Beta pregunta 1.b

### ISSUE THREAD

**Issue by acrojas2** [IIC2343/syllabus#11]
Hola:
Tengo la duda si es que se puede considerar que existen las bases negativas, ya que buscando un poco acerca del tema encontré que existen las bases negabinarias, negaoctales, etc. Siento que cambia mucho la respuesta si nos restringimos a lo que vimos en la clase y lo que aparece en los apuntes, ya que en ellos no se ha mencionado a que dominio se restringe el valor de una base.
Saludos!

**Comment by FranLucchini** [comment]
Lo mejor es restringirse a bases positivas.

**Comment by FranLucchini** [comment]
@jmopaso puedes hacerlo si lo deseas, pero no es requerido. Si lo haces así, debes hacer lo mismo que explico más abajo.

@frvalenzuela No está mal si las tomas en cuenta, pero vas a tener que dar una explicación clara de que estás trabajando con bases negativas y explicar su uso. Además, debes referenciar tus fuentes (por ejemplo, debes incluir el paper que mencionaste).
