### ISSUE TITLE
Bits que salen del Instruction memory

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2343/syllabus#11]
Por lo que entiendo son 8 bits para el literal, 6 bits del opcode y el bit restante no entiendo para que es.
¿Para que es?

**Comment by Hernan4444** [comment]
@jorgeriesco hola, en el diagrama visto en clases del computador son 8  bits para el literal y **el resto** se da de opcode aunque no se ocupe. Así que no son 6 bits de opcode, sino 7, aunque el séptimo bit no se ocupe, igual se manda a la Control Unit.

Espero haber respondido tu duda
Saludos ✌️

**Comment by jorgeriesco** [comment]
Osea en el fondo es por el numero de operaciones posibles que hace q se necesiten 7 bits.
Buenísimo, gracias!
