### ISSUE TITLE
[Tarea 1] [P1] {-truncated-}

### ISSUE THREAD

**Issue by cahinostroza** [IIC2343/Syllabus#11]
![image](https://user-images.githubusercontent.com/53799216/63220931-4aa6a580-c15f-11e9-98b2-b8b76334e491.png)
Hola, los test cases de la pregunta 1.1 me aparecen de la siguiente manera, no entiendo de donde viene el {-truncated-} que aparece al lado de la respuesta.

**Comment by jmwielandt** [comment]
Hola

El truncated es algo que agrega hackerrank por su cuenta, por lo general cuando los tests son demasiado largos. En el caso que indicas, no estoy seguro de por qué lo pone.

Sobre tu respuesta, le pusiste el salto de línea al final? Es necesario.

Saludos.

**Comment by ceosorio** [comment]
Hola! Yo tenia el mismo problema, pero es por el espacio que agregaste al principio. Sin el espacio debería aceptar la respuesta.
