### ISSUE TITLE
Numero de Loops por componente

### ISSUE THREAD

**Issue by LuisFros** [IIC2343/syllabus#110]
Podemos asumir que cada componente pertenece a lo mas a un loop en el circuito? Es decir no pueden haber 2 loops que tienen el mismo componente?

**Comment by FranLucchini** [comment]
Te refieres a que las entradas de una compuerta les llegue input de diferentes loops?

**Comment by LuisFros** [comment]
Si , me refiero a por ejemplo un circuito como este: 

![image](https://user-images.githubusercontent.com/21247721/45267745-0a1bb380-b449-11e8-9950-a468ae2bbaa3.png)

La diferencia principal con el ejemplo de la tarea es que los 2 loops tienen componentes en comun.

**Comment by FranLucchini** [comment]
Ya perfecto. No esperamos que manejen esos casos.

**Comment by LuisFros** [comment]
Ok, Gracias!
