### ISSUE TITLE
Duda con el ejemplo de la parte 2

### ISSUE THREAD

**Issue by roy350** [IIC2343/syllabus#110]
Hola! en la parte 2 en el ejemplo sale que 4 + 7 como resultado debe dar 1-0-0-1 en orden P-N-Z-C, pero en el enunciado dice que se activa C si es que el numero es el resultado es menor que el numero, en este caso creo que deberia ser 0 ya que como contamos con registros de 16 bits al transformar en binario seria 
4 = "0000000000000100"
7 = "0000000000000111"
4 + 7 = "0000000000001011"
aunque entiendo la razon por que pusieron que era verdad, por el carry final pero como contamos con 16 bits no deberia activarse creo, esa es mi duda muchas gracias de antemano!

**Comment by Hernan4444** [comment]
@roy350 el ejemplo del enunciado solo es una ejemplificación del formato en que iban a llegar los datos y el formato que queríamos que salieran, los resultados no coinciden con el calculo. (Por lo mismo pusimos X, Y en las primeras lineas)

Saludos!

**Comment by roy350** [comment]
Muchas gracias! :D
