### ISSUE TITLE
Interrogación 3 | Pregunta 8.1 | Que hacer con el while

### ISSUE THREAD

**Issue by bvallejo1** [IIC2343/Syllabus#110]
Hola, me surge la duda de que tengo que hacer con la sentencia while del código assembly, mi pregunta es si tengo que añadir las instrucciones que se ven implicadas. 
Para saber si tengo que considerar esta para analizar los hazards.

Muchas gracias.

**Comment by jmwielandt** [comment]
Hola,
Sí, tienes que considerar e incluir todas las instrucciones por las que pasas, se borren estas (por una mala predicción) o no.

Saludos

**Comment by bvallejo1** [comment]
Pero hay que considerar como si fuese otro jump o una comparación? Me interesa saber si esta también usa los registros de alguna manera implícita? o solo "estadísticamente" entra pudiendo equivocarse o no?

**Comment by jmwielandt** [comment]
No sé si entiendo bien tu pregunta, pero creo que es lo segundo, siempre va a creer que tiene que saltar, pudiendo equivocarse o no.
