### ISSUE TITLE
[CONTENIDO] Duda Carry y Overflow

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#110]
Hola! Alguien me puede explicar detalladamente la diferencia entre un Carry (C) y un overflow(V)? No logre entenderlo muy bien leyendo los apuntes. Además es importante para los JC y JO de la tarea. Gracias!

**Comment by frvalenzuela** [comment]
Hola @chocopiano !

La diferencia radica en su significado. Cuando una señal de carry esta activada, quiere decir que al realizar una operación (como puede ser una suma) hubo un bit que "sobro". Mientras que cuando una señal de overflow está activada indica que luego de una operación, el resultado es mayor a lo que es posible representar con una cantidad limitada de bits disponible. 

En ocasiones, como por ejemplo sumar dos números muy grandes, se tendrá que sobrará un bit (el carry) y además existirá un overflow (porque el número resultante es más grande que el máximo número que mis bits pueden representar). Pero esto **no siempre ocurre**.

Esto esta más detallado en la issue #102 la cual recomiendo revisar.

Si algo no quedo claro, o sigues con la duda, favor hacerlo saber para poder explicarlo de otra forma o explayar algún punto de mejor manera.

Saludos!

**Comment by cmp831** [comment]
Para el caso del shift left y shift right, el bit que se sobra va en el Carry o no?

**Comment by frvalenzuela** [comment]
Hola @cmp831! 

Así es ! 

Saludos !

**Comment by cmp831** [comment]
@frvalenzuela Muchas gracias

**Comment by rjdelrio** [comment]
en que caso el shift right dejaria un carry out, y ya que este reduce el numero no lo aumento osea por ejemplo: 0110 pasaria  ser 0011 y 0001 quedaria en 0000 pero no deveria dejar eso un carry out o si ?

**Comment by tomasrivera** [comment]
Hola, en el caso de las operaciones `SHIFT` puedes o no considerar el _carry out_. En caso de considerarlo, para la operación que mencionas si puede ser tomada como una operación con _carry_.
Para la corrección de la tarea sólo usaremos el _carry_ luego de una operación aritmética, por lo que esto no debería afectar.
Saludos

**Comment by chocopiano** [comment]
Mi duda es si por ejemplo tengo Add Ax, 1 (Ax=3777), los cuales en octal serian Ax=4000 como resultado, cual seria el nuevo valor de Ax, ya que se estan sumando positivos pero se esta obteniendo un negativo? Yo hasta ahora dejo en ese caso a Ax como 0 ya que paso el numero maximo que podia tomar un positivo. Por otra parte si sumo 7777 + 0002 queda 10001, lo cual es un overflow o carry ya que queda con un numero "extra", en ese caso que hacemos? Nos quedamos con el valor 0 tambien o no?

**Comment by jmwielandt** [comment]
> Mi duda es si por ejemplo tengo Add Ax, 1 (Ax=3777), los cuales en octal serian Ax=4000 como resultado, cual seria el nuevo valor de Ax, ya que se estan sumando positivos pero se esta obteniendo un negativo? 

Eso es un overflow, va a tu registro status y se puede usar para la instrucción  `JOV`.

> Por otra parte si sumo 7777 + 0002 queda 10001, lo cual es un overflow o carry ya que queda con un numero "extra", en ese caso que hacemos? Nos quedamos con el valor 0 tambien o no?

**Solo si no tienes signo, que NO es el caso,** `0o7777 + 0o2 = 0o1` (ajustado a 12 bits) y tienes carry. Por lo que la señal iría al registro status y se puede usar para la instrucción `JCR`.

Para más información: `Apuntes/05 - Saltos y subrutinas.pdf`

Ánimo con la tarea!

PD: recuerda que estamos simulando el comportamiento de un computador real, donde no tendrías "un bit extra".
