### ISSUE TITLE
[Tarea 3 - Placa] Adder/Sub

### ISSUE THREAD

**Issue by FelipeCampbell** [IIC2343/syllabus#111]
Cómo hay que manejar un caso de overflow en las entities Add/Subb.

**Comment by frvalenzuela** [comment]
Hola Felipe!

No es necesario que te preocupes el caso de overflow en esas entidades, si llegase ocurrir sería problema de quién programo la máquina, no de la máquina en si.

Saludos!

**Comment by FelipeCampbell** [comment]
Gracias Felipe, me quedó claro. Pero después me surgió otra pregunta sobre los overflow en la ALU. Las operaciones shift left y shift right tienen overflow posible?  No me queda muy claro cómo funcionan estos shifts tampoco. Para un shift right o left simplemente relleno con un 0 el lugar que queda "vació" luego del shift o hay que hacer algo en particular si el número, por ejemplo, es un negativo y se hace un shift right ? Otro ejemplo sería un número positivo en que si realizo el shift left se transforma en negativo?

**Comment by frvalenzuela** [comment]
Hola Felipe!

Las operaciones de shift left y shift right si tienen overflow posible por definición (tratar de representar un número más grande que nuestra cantidad de bits disponibles). Sin embargo, para no añadir más complejidad a la tarea pueden asumir que no aplicaremos el caso de overflow a las operaciones con shift.

La primera descripción de rellanado de cero es correcta y si se transforma en negativo o en positivo no es algo que tengas que manejar. 

Saludos!

**Comment by vaetchegaray** [comment]
> Hola Felipe!
> 
> Las operaciones de shift left y shift right si tienen overflow posible por definición (tratar de representar un número más grande que nuestra cantidad de bits disponibles). Sin embargo, para no añadir más complejidad a la tarea pueden asumir que no aplicaremos el caso de overflow a las operaciones con shift.
> 
> La primera descripción de rellanado de cero es correcta y si se transforma en negativo o en positivo no es algo que tengas que manejar.
> 
> Saludos!

Hola, entonces la actualización del registro de status solo se realiza con las instrucciones ADD y SUB? O en las operaciones lógicas también tenemos que verificar si se genera algún flag?

**Comment by frvalenzuela** [comment]
Hola @vaetchegaray ! 

La acotación solo hacía referencia al caso de overflow. Cuando me refería a si se transforma a negativo o positivo es que no es manejable me refería que no debías hacer algo aparte de lo regular con ello. 

Pero si por ejemplo, el resultado de ALU es cero entonces el flag de Z debe estar activo independiente de que operación. Lo mismo para todos los flags. El único que cae en la excepción es el overflow con shift, que si bien ocurre no lo consideraremos para esta tarea. 

Saludos !

**Comment by cjdelacuadra** [comment]
![image](https://user-images.githubusercontent.com/37161679/57815815-fdbdc800-7746-11e9-9a21-a4902f0d6361.png)
hola, no entiendo que señales entran  aca, hasta ahora le entrego un 1 de 12 bits y una señal '0' , pero no va a cambiar, como se debe conectar??

**Comment by frvalenzuela** [comment]
Hola @cjdelacuadra ! 

Cambia porque la entrada es lo que sale del PC el cual cambia. 

Saludos !

**Comment by cjdelacuadra** [comment]
me refiero a que es lo mismo que entregarle la señal del pc mas un 1, por lo tanto era mas facil entregarle al mux el pc y que este le sumara 1

**Comment by frvalenzuela** [comment]
Hola @cjdelacuadra ! 

Es que para eso necesito que PC avance, y lo haría en la próximo ciclo, yo necesito el PC+1 en el mismo ciclo donde lo ejecutó, por eso no escogería PC. 

Espero que se haya entendido. 

Saludos !
