### ISSUE TITLE
Interrogación 3 | Pregunta 7 | Descripción de instrucciones

### ISSUE THREAD

**Issue by furzuadr** [IIC2343/Syllabus#111]
Hola!
Estaba revisando la descripción de las instrucciones y me quedan dudas sobre algunas, como por ejemplo:
- Ret no dice nada
- Push y Pop no dicen que decrementen o aumenten el SP
- Call no guarda PC+1 en el Mem[SP]
En general cosas de ese estilo, que se contraponen con lo que hacemos en el proyecto.
Mi duda va a si tienen que hacer extrictamente lo que dice en la descripción, o tienen que hacer lo que hemos hecho en el proyecto?

Gracias!

**Comment by arbiocanpion** [comment]
@furzuadr  no soy ayudante, pero creo que esta correcto considerar las instructions codes como si fueran las del proyecto ( o al menos asi lo hice yo).

**Comment by jmwielandt** [comment]
> Push y Pop no dicen que decrementen o aumenten el SP
Dado que tenemos instrucciones especiales para incrementar y decrementar el sp, no se hace de manera automática.

Ret y Call sí, considéralos como en el proyecto.
