### ISSUE TITLE
Cálculo de la frecuencia máxima

### ISSUE THREAD

**Issue by Nicolasvegam** [IIC2343/syllabus#111]
Hola, estoy perdido calculando la frecuencia máxima. Por lo que he entendido, el clock mete en un flaco de subida el valor de 1, esto lo debo simular en mi circuito hasta que se vuelva estable (me entregue el mismo output). Pero después tengo que ver el flaco de bajada y ver que se vuelva estable (vi que no hacer esto provoca problemas de "metaestabilidad"). ¿La suma de esos dos tiempos de estabilidad es mi T mínimo (f máxima)?

![fmax3](https://user-images.githubusercontent.com/26209122/45259466-1a2d8780-b3a4-11e8-9273-2b62833c9cc4.png)

**Comment by FranLucchini** [comment]
Hola, estoy un poco confundida con la pregunta. Dada la foto, tu duda se relaciona al caso de dos flip flop en serie?

También me entra la duda de que menciones el flanco de bajada, ya que los flip flop tipo D sólo guardan el valor de entrada D cuando el reloj está en flanco de subida.
