### ISSUE TITLE
[TAREA 3 - PLACA] Control Unit

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#112]
Hola, podrían explicarme un poco lo de la control unit, que no entiendo bien que hay que hacer.  Por lo que entiendo, recibe un opcode (vector de que tamaño 12 creo) y las cosas de status, pero dpes no entiendo nada. Muchas graacias!! Sería de gran ayuda cualquier información! gracias

Leyendo un poco mas, cada opcode esta asociado a un numero binario y estos numeros (cada posicion significa que poner para el enableA, enableB , etc... ) pero donde puedo extraer esto?

**Comment by RobinCuevas** [comment]
x2

**Comment by sipoblete** [comment]
x3

**Comment by Arcoirisky** [comment]
Aquí viene una explicación de madrugada:

La _Control Unit_ en esta micro-arquitectura trabaja en tres fases (leer opcode - leer literal - ejecutar) pero ¿qué es lo que realmente hace una _CU_? **Recibe instrucciones para convertirlas en palabras de control** 

¿Que es esto?
### Instrucciones
Las instrucciones no son nada más ni nada menos los _Opcodes_ de sus instrucciones, estos son "procesados" (por así decirlo) por la _CU_ de forma que cada combinación de _Opcodes_ me entregue una palabra de control distinta. 

### Palabras de control
Estas son el montón de señales que tira la _CU_ para esparcirla a todos los componentes que están a su alcance. Desde la elección de operación de la _ALU_ hasta si escribe o no en memoria. Dicho de otra forma:

Extrae la instrucción de la memoria principal (Opcode + Literal), hace un el proceso de decodificación para interpretar su tipo y la naturaleza de sus argumentos (Registro o literal). Con el fin de proveer la señalización de control hacia los distintos componentes en ejecución.

Cada _CU_, así mismo su configuración, depende netamente del computador. Recuerden que las verdaderas instrucciones están escondidas en los _Opcodes_ para ahorrar mucho en instrucciones, espacio y claro, dinero. 

##Qué tienen que hacer

Re-interpretar estos _Opcodes_ de forma que se generen las instrucciones que ustedes deseen. **NO ES NECESARIO QUE SE INVENTEN UNA CIRCUITERÍA QUE LES RETORNE LA PALABRA DE CONTROL** Este no es un curso de eléctrica como para que tengan que hacerlo (Si les interesa, existe el curso de Sistemas digitales ;D)

Según pueden ver en el diagrama del enunciado, de la _CU_ salen 15 señales de 23 bits (Estaré hablando en binario para no confundirnos con la transformación al Octagonal) ¿Cómo sé que son 23bits?

* enableA --> (1bit) Cargar Registro Ax
* enableB --> (1bit) Cargar Registro Bx
* selA[1:0] --> (2bit) Selector Mux Ax
* selB[1:0] --> (2bit) Selector Mux Bx
* loadPC --> (1bit) Cargar PC con valor de Memoria
* selALU[2:0] --> (3bits) Operación ALU
* W --> (1bit) Escribir en Memoria
* IncSP --> (1bit) SP = SP + 1
* DecSP --> (1bit) SP = SP - 1
* LSP --> (1bit) Cargar SP con valor de Memoria
* Sub --> (1bit) Un Sumador-Restador 
* selDin[1:0] --> (2bit) Selector Mux Data In
* selAdd[3:0] --> (4bits) Selector Mux Address
* loadBP --> (1bit) Cargar BP con el valor que le entregue el Mux BP
* selBP --> (1bit) Selector Mux BP

##Cómo puedo traspasar una instrucción sabiendo esto ;---; 

La forma más fácil que se me ocurre ahora mismo es crear una especie de tabla de verdad con las entradas (opcodes + literal) junto a sus respectivas salidas. Por ejemplo, para la instrucción **POP Ax**

Por la ISA sabemos que significa (Desapilar dato desde el stack)
```
SP = SP + 1
Ax = Memory[SP]
```
Entonces, si vemos lo obvio de lo que estamos haciendo:
1) Escribimos en Ax
2) Sumamos SP + 1
3) Sumamos (Se debe pasar por la ALU)
4) Cargo *de* memoria

Ahora, veamos el diagrama de nuevo. si estamos usando el registro B entonces, el selector debería ser~ 01 (Por convención la más significativa es la más a la izquierda -cuando se ve en horizontal- a no ser que se especifique lo contrario. Son las 3am y decidiré que se queda así para el ejemplo)

Ya tenemos nuestra primera entrada en la tabla de señales. Solo nos faltan 14 🔢 

| enA | enB | selA | selB | loadPC | selAlu | W | IncSP | DecSP | LSP | Sub | selDin | selAdd | loadBp | selBP |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|   |   |   | 00 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |

Al SP le sumamos 1 y no escribimos en memoria:

| enA | enB | selA | selB | loadPC | selAlu | W | IncSP | DecSP | LSP | Sub | selDin | selAdd | loadBp | selBP |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|   |   |   | 00 |   |   | 0 | 1 | 0 |   |   |   |   |   |   |   |   |   |   |

Estamos escribiendo el valor de la dirección de memoria SP, BP no nos importa, etc. Este es el momento de aplicar todos los conocimientos de cómo funciona un computador básico e ir rellenando el resto de señales con basura, el cero es un buen número para eso. Al menos a mi me gusta. Luego, me terminan quedando estas señales que hacen el POP Bx tal y como se especifica en la ISA.

| enA | enB | selA | selB | loadPC | selAlu | W | IncSP | DecSP | LSP | Sub | selDin | selAdd | loadBp | selBP |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 0 | 1 | 01 | 00 | 0 | 000 | 0 | 1 | 0 | 0 | 0 | 00 | 0001 | 0 | 0 |

Para la ALU elegí 000 como la suma entre la salida del MuxBx (Mem[SP]) y la del MuxAx (0) para luego guardar el valor en el registro Ax (enA) porque la mía la conectaré de forma que 000 sea una suma dentro de mi ALU y no se me ocurrió mejor forma de hacerlo que esta.

---------

Al final es cosa de seguir el diagrama con calma, que para eso están. Buenas noches cabros~ El cómo implementarlo en su tarea de Placa lo dejo en vuestras manos~

Tómense un tiempo en leer e intentar llenar su propia tabla si es que no entienden algo para luego preguntar. Esto es solo **una** forma de hacerlo, si ya tienes la tuya y funciona, **do it ❤️**

**Comment by NicolasAguirre** [comment]
@Arcoirisky uuh muchas gracias por la respuesta te pasaste!! me quedo mucho mas claro!!! Pense en q se hacia en la manera en que dices pero encontre que era mucha pega, pero creo que me quedo clarisimo! Muchas gracias por la respuesta!

**Comment by jgespinosa10** [comment]
Hola, tengo una duda sobre una instrucción específica. Para la instrucción:
MOV Ax, [Dir]
¿La dirección Dir se recibe de la memoria principal o del PC? (Para luego enviarlo de vuelta a la memoria principal para obtener el valor Memory[Dir]).

**Comment by frvalenzuela** [comment]
Hola @jgespinosa10 !

Se recibe de la memoria principal, en forma de literal.

Saludos!

**Comment by NicolasAguirre** [comment]
@Arcoirisky @frvalenzuela disculpen, el literal de donde proviene?? 
Por ejemplo para Mov Ax, Lit --> Ax = Lit para esto es como Ax = 0 + Lit y supongo que ese lit debe provenir de cm la memoria ?? tengo como dudas respecto a eso! gracias!

**Comment by frvalenzuela** [comment]
Hola @NicolasAguirre !

Efectivamente ese literal proviene de la memoria en el segundo ciclo.

Saludos!

**Comment by NicolasAguirre** [comment]
@frvalenzuela Por otro lado, cuando realizo un jmp, je, etc que codigo se pone en la alu (cualquiera no mas porque da igual o no, yo toy poniendo como suma de vector 0 + vector 0). Por otro lado, no logro cachar bien lo de stack avanzado, para que sirve eso del BP. Gracias, cualquier comentario se agradece (prguntare harto, porque estoy un poco confundido)

**Comment by NicolasAguirre** [comment]
@Arcoirisky respecto a lo q me respondiste arriba, puede ser que hayas jugado entre Pop Ax y Pop Bx??

**Comment by Arcoirisky** [comment]
Ojo cuidado con las señales que elijas para la ALU. No te vayas a sobrescribir los registros u operes.

Y el BP, como su nombre lo indica, es el base pointer. Es usado para marcar la posición base del frame de una subrutina ó direcciones indirectamente en el stack.

Cualquier cosa tienes los apuntes si te sigues preguntando por si existencia :D

**Comment by Arcoirisky** [comment]
@NicolasAguirre no me sorprendería mucho pensando que estaba madrugando pero al final terminé haciendo el Bx 🤔 estoy segura 🤔

**Comment by NicolasAguirre** [comment]
@Arcoirisky sisi, segun yo era el Bx pero en una parte pusiste Ax entonces cm q me confundi no mas. Pero se entendio perfect. Sisi, lo de la ALU lo entiendo perfecto pero igual cm q siempre en cada instruccion la alu ejecuta algo o no ?

**Comment by NicolasAguirre** [comment]
@Arcoirisky en q parte de los apuntes estan (no lo he visto, pero toy leyendolos jajaja)

**Comment by Arcoirisky** [comment]
Sip, es prácticamente la única forma que tienes de acceder a ciertas cosas. O de cargar ciertos registros. En realidad, todo en el computador siempre está ejecutando algo, la diferencia radica en qué es lo que te importa y por ahí controlas las señales.

**Comment by Arcoirisky** [comment]
El 7!

**Comment by NicolasAguirre** [comment]
Me surgio una duda muy grande, solo para corroborar.
Cuando hago una operacion MOV A, Lit en el tercer ciclo el MUX B queda con el valor de Memory[Program Counter] y cuando hago MOV Ax, [Dir] lo que tengo q realizar aca es Memory[Literal]. Me surgio la duda debido al tercer ciclo donde este extrae los datos de memora dos veces! gracias!

**Comment by Arcoirisky** [comment]
Nani? Mov A, Lit usa el MuxB para llamar el Lit que viene de la memoria, opera con la Alu para poder salir y activando el enableA te permite guardar este en Ax 🤔 

Recuerda que en el primer ciclo se mandan las señales que salieron según el opcode, el segundo se carga el literal y el tercero solo ejecuta

**Comment by frvalenzuela** [comment]
Hola @NicolasAguirre !

Efectivamente lo extrae dos veces, pero eso no genera una inconsistencia o mayor complicación, el resultado final al tercer ciclo cumplirá la instrucción pedida. Y selAdd efectivamente basta con 3 bits para seleccionar como indicas (error de typeo), pero que sobren muchas entradas no es un gran dilema tampoco (se puede rellenar con ceros las opciones que no se ocupen como se menciona en #113 ).

Saludos!

**Comment by NicolasAguirre** [comment]
@frvalenzuela @Arcoirisky les entiendo la idea, pero si lo extrae dos veces entonces el valor en Mux B cm q se "actualiza" dos veces (creo, por lo que entiendo). Entonces si tengo Mov A, Lit y Mov A, Dir cm que el MUX B se hace dos veces (ciclo dos cuando ejecuta literal, y tambien cargada de memoria). Entonces is quiero escribir en Ax (tercer ciclo) lo que sucederia es que en MUX B, tengo que si o si hacer como Memory[PC] (para no perder el valor del literal. 
PD: tal vez no este cachando nada y es muy probable jaaj

**Comment by NicolasAguirre** [comment]
Por otro lado, hay un error en el enunciado (deberia salir Memory[Bx + Lit]), para que la gente no se confunda yo me confundi harto rato hasta que vi un issue anterior

<img width="789" alt="Captura de pantalla 2019-05-07 a la(s) 04 33 07" src="https://user-images.githubusercontent.com/20804346/57285519-5fb06a80-7081-11e9-942c-6ed321bf1045.png">

**Comment by Arcoirisky** [comment]
1) Creo que estás viendo el MuxB como algo más que un simple selector de salidas 🤔

2) el opcode 44 y 45 no son lo mismo 🤔 yo solo aproveché y los hice a la vez 🤷🏻‍♀️ Solo es un ejemplo de cómo deberían ver la Control Unit 🤔

3) Que bueno que lograste resolver tu duda mirando otras Issues :D para eso están y No es ningún error. A estas alturas ya deben de entender que es lo que se está haciendo según los argumentos y la operación que presenta la ISA :D 

Ya si no te queda muy claro puedes preguntar por issue, tal como se hizo en este caso :)

**Comment by fenahurtado** [comment]
Hola! Tengo una duda con la obtención de datos en la memoria... Si tengo por ejemplo la instrucción Ax = Memory[Dir], lo que debo hacer hacer es que en el muxAdd se seleccione el literal que venía de la memoria (Dir). Esto haría que luego ese sea el address del siguiente literal que sale de la memoria (Memory[Dir]). Pero mi problema es que luego ese dato sería seleccionado en el muxAdd entonces de la memoria saldría Memory[Memory[Dir]] y despues Memory[Memory[Memory[Dir]]] y asi recursivamente...  Como evito esto? O esta mal mi razonamiento?

Por último, como sabría mi programa que luego de ejecutar esta instrucción debe volver a seleccionar el PC en el muxAdd?

**Comment by Jiparavich** [comment]
@fenahurtado  x2

**Comment by NicolasAguirre** [comment]
@fenahurtado no soy ayudante, pero segun yo es Ax = Memory[Dir] entonces la direccion deberia venir de la memoria, y no habra esa recursion por los ciclos del computador (creo). Y luego en el segudno ciclo que se elige esa direccion de la memoria, ahora mem(dir) pasa a la alu y se ejecuta todo. No se si se cacho bien.

**Comment by frvalenzuela** [comment]
Hola @fenahurtado !!

Favor revisar el nuevo diagrama y la issue #144 

Espero que eso solucione tu duda, saludos!
