### ISSUE TITLE
[Tarea 3] Problema Generador de Interrupción

### ISSUE THREAD

**Issue by mericci** [IIC2343/Syllabus#112]
Hola, el generador de interrupción me dejo de funcionar. Llegue a la subrutinaC y me muestra el siguiente error:

![image](https://user-images.githubusercontent.com/42249674/68042572-02a11480-fcb2-11e9-866e-857c25e2689a.png)

Ahora no puedo probar ninguna de las subrutinas, ya que al apretar cualquiera de los 3 botones me muestra lo mismo. Ya probé reemplazando el archivo y sigue apareciendo lo mismo.

**Comment by Allmoz** [comment]
Puede que por alguna razón ya no tenga acceso a los archivos, borra la carpeta c:/Arqui/ para que la cree de nuevo el programa.
