### ISSUE TITLE
Interrogación 3 | Pregunta 7 | Operación DIV en AU.

### ISSUE THREAD

**Issue by jmsilvas** [IIC2343/Syllabus#112]
Hola! 
Se nos dijo que las unidades (tanto aritmética como lógica) pueden realizar las operaciones que se indican en la ISA. Pero me quedó una duda, para el caso de la división la UA podría entregar tanto cociente como módulo en el mismo ciclo? Es decir, tener 2 outputs?

**Comment by jmwielandt** [comment]
Hazlo como prefieras. Mientras la microarquitectura sea funcional, todo bien.
Particularmente, si vas a hacer que tenga dos salidas, recuerda indicar qué pasa cuando tienes las otras operaciones que no la necesitan.
