### ISSUE TITLE
Ayudantía hoy

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#112]
Hola! Hoy habrá clases en el horario de ayudantía o no habrá nada?

Gracias!!

**Comment by Geeermy** [comment]
No habrá nada. :) ¡Disfruta el día! jejeje

**Comment by Arcoirisky** [comment]
Wat? No hay Ayudantia??

**Comment by Geeermy** [comment]
Nop... revisa el último correo que mandé. 👀
