### ISSUE TITLE
[T3] Interrupciones Seguidas

### ISSUE THREAD

**Issue by BFFV** [IIC2343/Syllabus#113]
Según se dijo en la Issue #105, la llamada y ejecución de la Subrutina asociada a una cierta Interrupción deben ser realizadas DESPUÉS de atender a dicha Interrupción (tras volver al programa mediante IRET). 

Esto hace posible que al momento de volver al programa ocurra otra Interrupción ANTES de poder llamar a la Subrutina de la anterior, por lo que esta no se ejecutará y simplemente se atenderá a la NUEVA Interrupción. ¿Se puede asumir que si se quiere probar una Interrupción entonces no se gatillará otra antes de poder llamar a la subrutina de la primera?

**Comment by Allmoz** [comment]
Efectivamente, en este caso eso va a pasar y por eso el enunciado dice "de acuerdo a la última interrupción atendida".  Respecto a tu pregunta, en ese caso, se esperaría que llame la subrutina solo respecto a la última interrupción atendida.

**Comment by BFFV** [comment]
Gracias!

**Comment by Pipelao** [comment]
Hola @Allmoz,

Hay algo que no logro hacer, y eso es saber cuál es la última interrupción atendida por la respectiva ISR, lo que se me ocurre a la rápida es mediante una variable ir asignándole manualmente que interrupción es atendida pero me da la impresión que no es la manea correcta de hacerla, que debe haber algo propio de la ISR que me permitan obtener esa información, si es de la última manera que menciono, ¿en qué documentación podría encontrar dicha información?. 

Otra pregunta es con respecto a lo que dijo de 

> se esperaría que llame la subrutina solo respecto a la última interrupción atendida.

¿interrupción atendida se refiere a que entra en la ISR correspondiente?

Gracias de ante mano.
