### ISSUE TITLE
[T03 - Placa] - Mux que reciben cantidad de inputs no en base 2

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2343/syllabus#113]
Hola,

Quería saber como se hace un Mux cuando este recibe, por ejemplo, 3 inputs. Como es el caso de Mux A, el cual puede recibir 0, el valor del Registro A y algún valor de la memoria RAM.

Saludos.
@dfvasquez

**Comment by frvalenzuela** [comment]
Hola @Jiruiz2 !

Se hace la misma forma que los muxes normales con los comandos `with/select`. Si te sobran espacios puedes rellenarlos con ceros o al final del with select escribir `others` como se muestra a continuación.

```
with f select h <=
” 1000 ” when ”00” ,
” 0100 ” when ”01” ,
"0000" when others ;
```

Saludos!
