### ISSUE TITLE
Interrogación 3 | Pregunta 7 | Instrucción división

### ISSUE THREAD

**Issue by cacosandon** [IIC2343/Syllabus#113]
Hola!

En la instrucción DIV:

![image](https://user-images.githubusercontent.com/30879716/84097274-19d77b80-a9d2-11ea-8118-423e141eae54.png)

A qué se refieren con retornar R1 **y** R2?

Gracias!

**Comment by jmwielandt** [comment]
R1 y R2 son registros cualquiera.

Si intento dividir 5/3, va a retornar un 1 y lo va a guardar en R1, y un 2 que lo guardará en R2.

Pero si intento dividir 5/0, retornará el 5 a R1 y el 0 a R2.

Saludos!
