### ISSUE TITLE
Interrogación 3 | Pregunta 8.1 Parte A | Caso Saltos Condicionales

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2343/Syllabus#114]
En el enunciado dice que en caso de saltos incondicionales siempre asumamos que se salta. Pero no menciona el caso de los saltos condicionales. Si salta o no en estos casos queda a nuestro criterio?
Gracias!

**Comment by viantirreau** [comment]
Hola!
Actualizaron el enunciado, se asume el salto para condicionales e incondicionales :)

**Comment by kelseyfranken** [comment]
@viantirreau  Gracias!

**Comment by clementeross** [comment]
Tengo una duda con respecto a eso mismo. Si asumimos que salta siempre, entonces no es necesario "frenar" el pipelining para el caso de los saltos?

Gracias!

**Comment by jmwielandt** [comment]
Hola @clementeross 

Se hace lo que se explicó en clases, no se meten NOPs.

Saludos
