### ISSUE TITLE
[TAREA 3 - PROGRAMADA] Números negativos.

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#114]
Tengo una duda, quizas estoy entendiendo mal. Al ser octal los números positivos seran del 0000 al 3777 y del 4000 al 7777 negativos o no? Y segundo; poniendome en el caso de que fueran binarios, al sumar siempre 2 negativos ocurre overflow o no ya que tienen un 1 adelante señalando que son negativos. Es cierto eso o estoy mal?

**Comment by Arcoirisky** [comment]
1) ¿En qué te basas para separar los números positivos y negativos así? :eyes:

2) Tendría cuidado con sumar dos números negativos. Porque si aceptas ese overflow así sin más, estarías en casos donde la suma de dos números negativos te daría positivo. Yo que tu me quedaría pensando un poco más ese tema y el porqué no siempre ocurre overflow.
