### ISSUE TITLE
[Tarea 3] Ejecución de la Subrutina C

### ISSUE THREAD

**Issue by BFFV** [IIC2343/Syllabus#114]
Hola,
Al final de la Subrutina C en el enunciado se indica que el robot deberá cumplir con los requisitos indefinidamente en el tiempo, ¿cuál de las siguientes interpretaciones es la correcta? (si no es ninguna de las 2 favor indicar cómo se debería interpretar):

1) Al apretar el botón 3 se entra a la Subrutina del robot y esta simula sus acciones infinitamente, por lo que NO se volverá al programa principal ni se atenderán más Interrupciones.

2) Al apretar el botón 3 se entra a la Subrutina del robot, se ejecuta 1 sola acción (avanzar, girar, darse la media vuelta, girar y apagar bombilla) y después se vuelve al programa principal dejando al robot en el estado posterior a la acción realizada.

**Comment by Allmoz** [comment]
3.- Al apretar el botón 3, se interrumpe el programa y se ejecutara la ISR del botón 3. Luego el programa, sabiendo que la última interrupción que fue atendida es la del botón 3, llamará a la subrutina C, la cual nunca retornará. Sin embargo, las ISR van a seguir atendiendo las interrupciones de los botones, porque de cualquier modo pueden interrumpir la ejecución del programa.

Saludos

**Comment by BFFV** [comment]
Gracias!

**Comment by tomcan127** [comment]
Hola
Cuando el robot se encuentra con una bombilla apagada, la prende o solo da media vuelta?

**Comment by josefinaijb** [comment]
Respecto a esta respuesta:

> 3.- Al apretar el botón 3, se interrumpe el programa y se ejecutara la ISR del botón 3. Luego el programa, sabiendo que la última interrupción que fue atendida es la del botón 3, llamará a la subrutina C, la cual nunca retornará. Sin embargo, las ISR van a seguir atendiendo las interrupciones de los botones, porque de cualquier modo pueden interrumpir la ejecución del programa.
> 

Cuando las ISR atiendan las interrupciones con los botones 1 o 2, ¿se debe volver al programa principal y llamar las subrutinas A o B  aun cuando la subrutina C esté en permanente ejecución?

**Comment by frvalenzuela** [comment]
Hola @josefinajb ! 

No, el programa no ejecutará otra subrutina después de entrar a la subrutina C. 

Saludos!

**Comment by Pipelao** [comment]
Hola @frvalenzuela y @Allmoz 

Me quedan algunas dudas. ¿Entonces el botón 3 sólo se puede apretar una vez? Pregunto porque entendí que al no retornar la subrutina C estará infinitamente ejecutando esta subrutina, moviendose el robot "sólo" por decirlo de alguna forma, entonces no tiene mucho sentido apretar el botón 3 de nuevo. Mi otra duda es con respecto a los otros botones, si ya se apretó el botón 3, estará en la subrutina C constantemente y @Allmoz mencionó que: 

> Sin embargo, las ISR van a seguir atendiendo las interrupciones de los botones, porque de cualquier modo pueden interrumpir la ejecución del programa.

y @frvalenzuela dijo que:  

> el programa no ejecutará otra subrutina después de entrar a la subrutina C.

no entiendo como puede atender las interrupciones pero no ejecutar las subrutinas correspondientes a los botones 1 y 2.

Gracias de ante mano.

**Comment by Allmoz** [comment]
Asumiré por tu otro issue que ya lograste hacerlo.
