### ISSUE TITLE
Duda de display operaciones

### ISSUE THREAD

**Issue by sebawarrior** [IIC2343/syllabus#114]
Hola, con mi grupo deseamos saber si el resultado de cada operación de la ALU debe estar dado por los 4 displays (16 bits) o bien, que sólo nos quedemos con los 8 bits menos significativos y eso lo mostremos en el display C y D, por ejemplo. Y qué ocurriría con la pantalla de la calculadora, mostraría el número decimal real asociado a un posible número escrito en 12 bits?

**Comment by FranLucchini** [comment]
Saludos,

Primero, el comportamiento del display es el siguiente: si el botón central está apretado, debe recibir los 16 bits del resultado de la ALU; en caso contrario, debe recibir los 8 bits menos significativos de cada registro y mostrar en una mitad el regitro A y en la otra el B.

Segundo, el display mustra números hexadecimales. Así que, con 4 displays de 4 bits queda justo para los 16 bits de la ALU. Debes recordar que todos los número que opera la ALU y que guardan los registros son de 16 bits. Mostramos la mitad de los registros por problemas de espacio. Por esto, no me queda muy claro a qué te refieres con 

> Y qué ocurriría con la pantalla de la calculadora, mostraría el número decimal real asociado a un posible número escrito en 12 bits?
