### ISSUE TITLE
Compañero T05 práctico

### ISSUE THREAD

**Issue by cilopez** [IIC2343/syllabus#114]
¿Que pasa si mi compañero botó el ramo?, no existe la posibilidad de buscar otro alumno que esté en mis mismas condiciones o simplemente lo tendré que hacer solo😓 .

**Comment by FranLucchini** [comment]
Hola, hasta ahora, hay otra persona con el mismo problema. Lo ideal sería que no lo hagan sólos y vamos a hacer todo lo posible para evitar esto. Por interno te mando los datos.

**Comment by cilopez** [comment]
Muchas gracias @FranLucchini  !!

**Comment by Geeermy** [comment]
Vuelvo a abrir esta _issue_ en caso de que vuelva a existir un alumno con problemas en su grupo.
