### ISSUE TITLE
Error al crear el repo Tarea 3

### ISSUE THREAD

**Issue by Dyoma3** [IIC2343/syllabus#115]
Escribi mal el nombre del repo crearlo y no lo puedo cambiar :/ que hago?

**Comment by Arcoirisky** [comment]
¿Tu compañero está contigo? 
¿Que nombre tienen? O:
Si tú y tu compañero están de tiro puedes dejar el nombre que deseen ó, en este caso, que el destino les dejó ksndkskd 

Pero agradecemos agregar el número del grupo en el Readme uwu)/

**Comment by Dyoma3** [comment]
Si esta en el grupo gracias !
