### ISSUE TITLE
[Tarea 3] Ejecución emulador y botones

### ISSUE THREAD

**Issue by mbfuster** [IIC2343/Syllabus#115]
Holaa
Había podido instalar bien el emulador, cambié la linea de emu8086.ini, y los archivos a la carpeta DEVICES. Pero ahora intenté correr el ejemplo en clases n°10 robotInterrupt.asm, pero me sale esto:

![Captura](https://user-images.githubusercontent.com/24833859/68145015-96bde680-ff13-11e9-98a8-ab08615805a2.PNG)

Me pasa lo mismo al ejecutar el archivo de la tarea. Honestamente ni se me ocurrió como resolver esto. ¡Ojalá alguno me pueda ayudar! ¡Gracias!

EDIT: Hace esto cuando apreto alguno de los botones

**Comment by Allmoz** [comment]
Estás apretando los botones antes de iniciar el programa. Por lo tanto, al iniciar la ejecución hay interrupciones pendientes, pero no hay ni una ISR asociada a esas interrupciones aún. Por eso te da ese error, tienes que apretar los botones después de que estén suscritas las ISR.

**Comment by JohnTrombon** [comment]
Me pasó lo mismo, corrí un par de otros archivos, volví a la tarea y se me arregló solo, quizás así se limpia la cola de interrupciones pendientes (?)

**Comment by Allmoz** [comment]
Solo tienes que apretar en "run" nuevamente, y efectivamente va a fallar mientras queden interrupciones pendientes. Solo tienes que ponerle correr nuevamente, y efectivamente se va a ir fallando y limpiando las interrupciones pendientes.
