### ISSUE TITLE
Interrogación 3 | Pregunta 7 | Subida de archivo Zip

### ISSUE THREAD

**Issue by viantirreau** [IIC2343/Syllabus#115]
Hola!

Podemos subir un `.zip` con un PDF para el diagrama y el excel con las señales de control?
El formulario al parecer solo deja subir PDF.

Gracias desde ya!

**Comment by ceosorio** [comment]
Hola @viantirreau!

Como el form no permite archivos .zip, lo que puedes hacer es exportar tu excel a PDF y juntar ambos PDFs en uno. Esto puedes hacerlo con herraminetas online como [iLovePDF](https://www.ilovepdf.com/merge_pdf).

Te recomiendo siempre revisar que tu PDF quede legible y, en caso de tener problemas, avisa por esta misma issue y te intentaremos ayudar en lo que podamos.

Ánimo! ✨

**Comment by raespinoza4** [comment]
Yo estoy con la misma duda, mas que nada porque el diagrama me quedó un poco grande y al guardarlo en pdf las señales de control (en el diagrama) no se alcanzan a ver mucho :(

**Comment by ceosorio** [comment]
@raespinoza4 

Si tu diagrama lo estas armando en draw.io, debes exportarlo directamente como PDF (File ->Export as->PDF). Si ya estas haciendo eso y aun no se lee, avisa por aqui :)

**Comment by viantirreau** [comment]
Tremendo, gracias por tu consejo @ceosorio !

**Comment by ceosorio** [comment]
@viantirreau y @raespinoza4 

Al final, quitamos la restricción de formato a las preguntas 7 y 8,  ahora pueden subir un **.zip** sin problemas. espero que esto les acomode mas para sus entregas 😄 

Éxito en la prueba! ✨
