### ISSUE TITLE
[TAREA 3-PROGRAMADA] OPCODE 0o0050

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#116]
Hola nuevamente, en las operaciones de ese opcode no debería ser Memory[sp]=PC+1 en vez de Memory[sp]= pc, ya que en teoría cuando se use el ret volveriamos a la linea despues de donde se ejecuto el Call o me equivoco?

**Comment by tacorrea** [comment]
x2

**Comment by chocopiano** [comment]
y en el 0o0053, la operación PC=Dir no debería estar o sí?

**Comment by Arcoirisky** [comment]
Si bien tienes razón en que se supone que debes de ubicarte en la línea siguiente, recuerda que una vez tú ejecutas la instrucción correspondiente, se avanza a la siguiente para repetir el proceso.

Entonces, si fuera PC + 1 te estarías saltando una lectura de Opcode y tomarías el Literal como el Opcode que sigue y si no está en la isa todo explota!! :boom:

**Comment by Arcoirisky** [comment]
Y xq no debería estar PC = Dir? 🤔 tienes una señal de LoadPC y además la necesitas para hacer los saltos 🤔

**Comment by chocopiano** [comment]
Pero no entiendo pq habría un salto usando PUSH BP, si el salto se debería hacer cuando exista un J'ALGO' o un CALL?

**Comment by Arcoirisky** [comment]
¿De Cual instrucciones estamos hablando? La 53?🤔

**Comment by chocopiano** [comment]
Si, esa misma jajaja!

**Comment by Arcoirisky** [comment]
Entiendes que el BP es el puntero a donde se debe de regresar el programa después de irse a realizar una Subrutina ¿no? 🤔 Entonces, una vez guardado el dónde debe regresar (la base) en nuestro querido stack, debes de pegar el salto a la dirección dónde estarán las instrucciones a ejecutar hasta que puedas regresar con el POP.

Es por eso que en Push se guarda el valor donde apunta SP y luego sube uno (recuerda que estamos de abajo hacia arriba entonces es -1) y hace el salto. Mientras que POP, retrocede el SP en uno (+1)  y regresa a la normalidad el BP O:

**Comment by chocopiano** [comment]
@Arcoirisky disculpa, en la primera pregunta me referia a que en tería entonces es Memory[sp]=pc+2

**Comment by Arcoirisky** [comment]
Tampoco, sobretodo porque PC avanza prácticamente solo con la ayuda de su Clock. Sería lo mismo que dije arriba O: (teniendo en cuenta el cómo funciona este computador en especial Mips tiene 4 líneas por instruccion skndks)

**Comment by Arcoirisky** [comment]
@chocopiano, lo del pc+2 si tiene sentido en este computador! Porque son dos líneas!!!

**Comment by frvalenzuela** [comment]
Hola @chocopiano !

Primero y formal, si debería ser Memory[sp]=PC+2 en el opcode 0o0050. Y en el 0o0053 el pc=Dir esta de más ( no se pasa ningún Dir en esa operación tampoco ).

Lamento todo inconveniente que pueda haber causado.

Saludos!

**Comment by chocopiano** [comment]
Buenísimo! gracias!

**Comment by dedarritchon** [comment]
Cómo podemos sumarle 2 al PC?

**Comment by frvalenzuela** [comment]
Hola @dedarritchon !

Con el Adder antes del MuxDatain 

Saludos!

**Comment by VicenteMelin** [comment]
Hola! me surgió la duda de si esto afecta en alguna medida a la parte de placa, pues el adder que esta antes del MuxDatain solo puede sumar uno.
Ademas no tengo muy claro como lo hace el programa para avanzar de una instruccion a la siguiente, si me pudieran explicar la idea general y los componentes involucrados lo agradeceria mucho

**Comment by frvalenzuela** [comment]
Hola @VicenteMelin !

Porque solo podría sumarse uno? Puedes dar una señal "000000000010" que representaría el dos. El programa avanza por instrucción gracias al PC, que va sumando uno en cada ciclo, y como el PC apunta la dirección de la memoria se va de instrucción en instrucción.

Saludos!

**Comment by VicenteMelin** [comment]
1. Creo que entendí mal por donde se mueve la señal. Esta suma al valor de pc donde ocurre? por un momento pense que la hacia el adder/sub que suma 1 y que esta conectado al MuxDatain (pero esa suma llega al data in de la main memory, por lo que no tendría sentido que el valor de PC al que apunte en el siguiente ciclo entre por ese lado cierto?). 
2. Nos tenemos que preocupar de esto en la placa o el mem[sp] = pc + 2 solo aplica a la parte programada (o quiza en placa no afecta)? (porque en el enunciado dice que la instrucción hace mem[sp] = pc), pregunto porque esta issue tiene tag de programada y por eso no estoy seguro si debería darle más vueltas para entender a lo que esta dicho aquí si estoy haciendo la parte de placa.
