### ISSUE TITLE
Interrogación 3 | Pregunta 8 | zip en lugar de pdf

### ISSUE THREAD

**Issue by Cadagan** [IIC2343/Syllabus#116]
Duda corta: en la P8 hice un gran desarrollo de la parte A en un excel, pero la B en un pdf, ¿puedo entregar un zip que contenga ambos archivos? en el excel hice el pipeline completo debido a que explique varias cosas y siento que quedo mucho más ordenado asi :) le facilitará el trabajo a quien deba corregir :raised_hands:

**Comment by ceosorio** [comment]
Hola @Cadagan!

Revisa la respuesta que di en la issue #115
Si aun tienes problemas (por ejemplo, no logras que se lea bien en el PDF), responde por esa issue :)

Éxito! ✨

**Comment by Cadagan** [comment]
Se me fue agregar eso: al pasar el excel a PDF algunas casillas quedan más grandes que otras y se desordena mucho :(

**Comment by ceosorio** [comment]
@Cadagan,

al final quitamos la restricción de formato, así que ahora puedes subir un **.zip** sin problemas a las preguntas 7 y 8. 

Éxito y ánimo en la prueba ✨

**Comment by Cadagan** [comment]
Muchas gracias! 🙌🙌🙌🙌
