### ISSUE TITLE
Uso de librería fraction

### ISSUE THREAD

**Issue by JoseRomeroi** [IIC2343/syllabus#116]
Hola, podemos usar la librería fraction? En particular, las funciones: Fraction, numerator y denominator

**Comment by Hernan4444** [comment]
Sí la van a usar para no perder precisión en los float y no un para facilitar el cambio de base sin la fórmula vista en clases. Si puedes

Saludos

**Comment by JoseRomeroi** [comment]
ok, gracias! y se puede usar la funcion str() ?  Por ejemplo para pasar de 10 a "10"

**Comment by Hernan4444** [comment]
Sí puedes
