### ISSUE TITLE
Cuando atender ISR

### ISSUE THREAD

**Issue by Pipelao** [IIC2343/Syllabus#116]
Hola, tengo una duda con respecto a las interrupciones. Quisiera saber cuando debe atender la ISR; por ejemplo si se está ejecutando la subrutina A, y aprieto el botón 2, ¿debería dejar de ejecutarse la subrutina A y atender la interrupción del botón 2? o ¿dejar que termine la subrutina A y luego ejecutar la isr del botón 2?. Actualmente lo que ocurre en mi programa es ninguna de estas, si por ejemplo aprieto el botón 2 durante la ejecución de la subrutina A, no pasa algo, sigue ejecutando la subrutina A y luego vuelve al programa esperando alguna interrupción.

También lo pregunto para el botón 3, una vez que se apretó el botón 3 el robot debería moverse infinitamente por lo tanto el programa se encuentra ejecutando la subrutina C, si aprieto el botón 2, ¿debería ejecutar la subrutina B? Por lo que entendí de la issue #114 no debería ejecutarse la subrutina pero sí la ISR, esto no lo logro entender.

Gracias de ante mano.

**Comment by Allmoz** [comment]
"¿debería dejar de ejecutarse la subrutina A y atender la interrupción del botón 2?" 

no, aunqué si se ejecuta la IRS no sales de la subrutina A a causa de ella.

"¿dejar que termine la subrutina A y luego ejecutar la isr del botón 2?"

no escrictamente, podria perderse la ejecución de la subrutina B  (pero si se atiende la ISR), depende de tu imlementación. 

"Actualmente lo que ocurre en mi programa es ninguna de estas, si por ejemplo aprieto el botón 2 durante la ejecución de la subrutina A, no pasa algo, sigue ejecutando la subrutina A y luego vuelve al programa esperando alguna interrupción."

Lo que estas haciendo es correcto, y es válido.

"También lo pregunto para el botón 3, una vez que se apretó el botón 3 el robot debería moverse infinitamente por lo tanto el programa se encuentra ejecutando la subrutina C, si aprieto el botón 2, ¿debería ejecutar la subrutina B? Por lo que entendí de la issue #114 no debería ejecutarse la subrutina pero sí la ISR, esto no lo logro entender." 

Si lo que mencionas está bien

"¿debería ejecutar la subrutina B? "

No despues de que se llama a la subrutina C.

**Comment by Pipelao** [comment]
Ya perfecto, logro entender. Pero lo que aún no me queda claro es  a qué se refiere con atenderla ISR. Por ejemplo se está ejecutando la subrutina C y aprieto el botón 2, ¿debería irse a la ISR del botón 2? como un JMP por decirlo de alguna forma o se refiere a que esté implementado la ISR??

Gracias.

**Comment by Allmoz** [comment]
Si, el emulador te está funcionando correctamente. al apretar el botón tu programa se va a interrumpir y va a ejecutar la ISR correspondiente (el código base para la tarea corresponde a la base de las ISR y su asociación vector de interrupciones). Puedes verificarlo corriendo el ejemplo de interrupciones visto en clases.
