### ISSUE TITLE
Interrogación 3 | Pregunta 8.2 | Casos para cada hazard

### ISSUE THREAD

**Issue by nbnavarro** [IIC2343/Syllabus#117]
Hola!
 
Para la pregunta 8.2, ¿bastaría con mostrar un caso a modo de ejemplo para cada tipo de hazard? ¿o seria necesario más de un caso por cada tipo de hazard?

Muchas gracias de antemano

**Comment by jmwielandt** [comment]
@nbnavarro con uno por tipo basta
