### ISSUE TITLE
Duda señal de entrada a la ALU

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2343/syllabus#117]
En la ALU la señal de entrada sop, esta definida como 3 bits, pero son 9 operaciones diferentes contando con la multiplicacion, por lo  que ¿no deberia de ser de 4 bits esa señal para poder representar las 9 operaciones?

**Comment by FranLucchini** [comment]
Tienes razón, debería ser de 4.

**Comment by FranLucchini** [comment]
Pequeño error de enunciado.
