### ISSUE TITLE
[Tarea 3 - Programada] Consulta Dir

### ISSUE THREAD

**Issue by seba608** [IIC2343/syllabus#117]
Hola!

En las instrucciones que usan Dir, el literal que se debe entregar siempre será la linea en que esté la variable que se pase como Dir o podría ser un literal directamente (para expresar la dirección de memoria en que quiero leer/esrcibir)?

**Comment by Arcoirisky** [comment]
Ahí entra la discusión de las variables con o sin corchetes/paréntesis. Lo que intento decir es que:
‘’’
Mov Ax, var != Mov Ax, [var]
‘’’

Porque “var” es solo una dirección de memoria (hasta puede tomarse como un literal “”predefinido””). Luego, “[var]” es buscar en memoria el dato/valor ubicado en la posición “var” de memoria.

(Básicamente y respondiendo a tu pregunta, depende de cómo le estamos dando esta instrucción, si es un literal o una dirección)

**Comment by seba608** [comment]
Entiendo como abordar la diferencia desde el assembler, pero para el disassembler si el archivo de entrada tiene dos líneas: 0o0003 y 0o000X, ¿cómo se si el valor para el Lit corresponde al de lo que haya en la dirección 0o000X o si debo poner el literal directaente?

**Comment by Arcoirisky** [comment]
Lo sabes por el opcode o: en tu caso es 0o0003 (no estoy mirando la Isa ahora pero estoy segura que corresponde a Mov Reg,Lit)

**Comment by seba608** [comment]
Sii nada que ver el ejemplo, me confundí. Si tengo la instrucción MOV Ax, [Dir], ¿el valor para Dir puede ser un literal o siempre será una variable?

En el ejemplo del enunciado: MOV Bx , [ x ], el valor para Dir es una variable pero puede ser directamente un número (Por ejemplo MOV Bx, [5])?

Saludos

**Comment by Arcoirisky** [comment]
Aaaaaah~ 
Si, es exactamente lo mismo que hacer Mov Bx, [var] con var posición de memoria 5

**Comment by seba608** [comment]
@Arcoirisky gracias!

**Comment by Arcoirisky** [comment]
Explicita un poco más lo último 🤔

**Comment by seba608** [comment]
Para el último ejemplo, para el archivo de salida del disassembler se esperaría que el output diga MOV Bx , [ x ] o también puede ser MOV Bx, [5] si es que la variable x está en la posición 5?

**Comment by Jaluco** [comment]
+1 a eso ultimo

**Comment by Arcoirisky** [comment]
Estarías cambiando el programa al hacer eso y hasta romperlo como el peor de los casos. 

Se espera que el programa que salga del disassembler sea igual al que entró en el assembler.

**Comment by seba608** [comment]
Entonces debe ser MOV Bx, [x] ?? Y si es así, para que sea igual al programa que entró al assembler como puedo adivinar el nombre que le pusieron a la variable (en este caso x)?

Tampoco entendí por qué estaría cambiando y hasta rompiendo el programa.

Saludos

**Comment by jmwielandt** [comment]
@seba608 
Por "igual" nos referimos a que se respeten las instrucciones y variables (ver la última respuesta a la #120 ). Es normal que cambien los nombres de las variables y labels por nombres "genéricos" si quieres decirles así. Al final, en vez de `MOV Bx, [x]` puede que quede `MOV Bx, [var0]` y nadie se queja.

**Comment by seba608** [comment]
@jmwielandt 
Entiendo lo que quieren, pero no entiendo por qué no sería válido poner MOV Bx, [5] si es que x está en la posición 5 de memoria (por ejemplo)

**Comment by Arcoirisky** [comment]
Porque estás cambiando el tipo de direccionamiento y por lo tanto, la instrucción.
