### ISSUE TITLE
Duda char

### ISSUE THREAD

**Issue by Okhan97** [IIC2343/syllabus#118]
Hola, como paso del binario que me quede (despues de hacer todos los pasos respectivos) al caracter?
Ocupo codigo ascii u otra cosa ?

**Comment by Hernan4444** [comment]
Dejalo expresado cómo un número en base 10

**Comment by Okhan97** [comment]
No debemos cerrar las issues ?

**Comment by Hernan4444** [comment]
@Okhan97 preferimos que no, nosotros las cerraremos por usted despues.... así hacemos que solo busquen entre las issues abiertas.
