### ISSUE TITLE
Interrogación 3 | Pregunta 7 | Especificación señales de control 

### ISSUE THREAD

**Issue by Franco1605** [IIC2343/Syllabus#118]
Hola !
Para esta pregunta se deben especificar las señales de control para cada una de las instrucciones que aparecen en la tabla ?, o se puede explicar de forma general cómo funciona cada señal ?
Gracias !

**Comment by ceosorio** [comment]
Hola @Franco1605!

Como mencionamos en el [readme](https://github.com/IIC2343/Syllabus/blob/master/interrogaciones/i3/Pizzarra%20I3.md), puedes indicar con palabras las señales.

Ánimo! ✨
