### ISSUE TITLE
[TAREA 3 - PROGRAMADA] Fin data

### ISSUE THREAD

**Issue by achadwicka** [IIC2343/syllabus#118]
Hola,
El archivo binario que usarán para corregir la tarea tendrá como fin el ultimo dato? o serán puros 0 como en el que se encuentra en el syllabus.
Ya que si me baso en que pueden haber variables sin utilizarse en el código todos los 0 que siguen para abajo son posibles variables con valores 0, mientras que si tiene como fin el ultimo valor de variable es mas fácil ver cuantas variables tengo.
Gracias!

**Comment by Arcoirisky** [comment]
La memoria debe llenarse aunque sea con nops.

**Comment by jmwielandt** [comment]
Estimado, eso está en el enunciado.
Saludos.
