### ISSUE TITLE
[TAREA 3 - PLACA] Mux address

### ISSUE THREAD

**Issue by brayanmoreno** [IIC2343/syllabus#119]
Hola, tengo una duda sobre la cantidad de bits que recibe el mux address, ya que este en el diagrama solo tiene 5 entradas y recibe 4 bits, pero solo con 3 bits ya se pueden formar todas las combinaciones necesarias. ¿Para que es el bit extra?

**Comment by frvalenzuela** [comment]
Hola ! 

No tiene finalidad, solo tendrán más espacios sobrante. Pueden conectar ceros o manejarlo con un others en el with/select

Saludos !
