### ISSUE TITLE
Interrogación 3 | Pregunta 8 | Saltos condicionales.

### ISSUE THREAD

**Issue by clementeross** [IIC2343/Syllabus#119]
Hola!
Podríamos darle valores a A y B de tal manera que se cumpla el salto condicional? Para efectos de la respuesta podría ayudar más.

Por ejemplo: A = 6 y B = 10.

Gracias!

**Comment by ceosorio** [comment]
Hola @clementeross!

No puedes hacer lo que mencionas, ya que esto simplificaría tu desarrollo.

Ánimo! ✨
