### ISSUE TITLE
RAM

### ISSUE THREAD

**Issue by Dunkan1** [IIC2343/syllabus#119]
En el archivo correspondiente a la RAM  se define `dataout: out  std_logic_vector (15 downto 0)`, mientras que en el diagrama de la tarea aparece que el out es de 8 bits:
![imagen](https://user-images.githubusercontent.com/26102365/45576084-24400200-b84c-11e8-88eb-c97740aeb8ae.png)

Modificamos el archivo RAM para que cumpla con esto, a pesar de que en el código este comentado que no?

Por otro lado, en la imagen no se especifica la cantidad de bits de output del Mux Stack. Usamos el numero de bits que nos parezca mas conveniente?

**Comment by FranLucchini** [comment]
Hola,

La decisión de si quieren mantener que el computador sea de 16 bits es libre. Pueden cambiarlo, usar los 16 bits completos o usar los 8 menos significativos. Pueden modificar la RAM, no hay problema. Eso es un residuo de semestres anteriores.

Sobre la pregunta final, dado que es un MUX, el tamaño de la salida depende de las entradas, no?

**Comment by Dunkan1** [comment]
gracias

**Comment by Geeermy** [comment]
¡Hola!

@Dunkan1 para la próxima, por favor comenta esta _issue_: #116 

Se entiende que era una duda del enunciado y el código asociado, pero al final sigue siendo parte de los supuestos que pueden hacer. Por esta ocasión la dejaré abierta ya que fue respondida.

¡Gracias desde ya!
