### ISSUE TITLE
Pregunta 2 Shifting Tarea 1

### ISSUE THREAD

**Issue by mariana-ortega** [IIC2343/Syllabus#12]
Hola!

Tengo dos consultas sobre la pregunta 2 de shifting:

1) Siempre debo imprimir los números con 32 bits?

2) Quería consultar sobre el procedimiento para los shifts lógicos en el caso de números negativos como el que se muestra en hackkerran para -93. 
Mi conclusión era que en ese caso lo pasaron con complemento de 2 a número binario y de ahí lo pasaron a 32 bits y después hacen los shifts siempre agregando 0's a izquierda o derecha (no como vimos en clase que dependiendo del signo en el SHR se podía poner un 1 o un 0). Pero no me funciona así por lo menos entonces me queda la duda.

![image](https://user-images.githubusercontent.com/30672931/78637938-65a66100-7879-11ea-9548-d1400f24f4c8.png)

Gracias de antemano!
Saludos

**Comment by ceosorio** [comment]
Hola @mariana-ortega !

1. Si, los resultados siempre estarán en 32 bits.
2. Lo que vieron en clases con el profesor eran los shifts aritméticos, en la tarea les estamos pidiendo shifts lógicos, que son un poco distintos. Puede que la confusión del método sea por eso.

Ojala esto haya resuelto tus dudas! 😄
