### ISSUE TITLE
pregunta 2, enunciado inicial

### ISSUE THREAD

**Issue by nmaturana97** [IIC2343/syllabus#12]
En la pregunta 2 indica "Considere una representacion posicional de base beta, en la cual se desean representar numeros enteros", no estoy seguro si esto esta bien puesto en la pregunta 2 o debería ir en la pregunta 1.
Si es el segundo caso, esto es para las 3 preguntas? (1.a, 1.b, 1.c)

**Comment by FranLucchini** [comment]
Está bien puesto en la pregunta 2.
