### ISSUE TITLE
Bits de exponente en IEE754

### ISSUE THREAD

**Issue by glbello** [IIC2343/syllabus#120]
Para la cantidad de bits del exponente, ¿si este no me es suficiente para representar el exponente que corresponde, debo considerar los bits más significativos?

Por ejemplo, si tengo 8 bits para el exponente. el desfase es de 127, y el exponente que necesito para representar mi número es 383, luego para llegar a 383 -> x - 127 = 383 -> x = 256, que en binario es 100000000, luego tengo 9 bits! entonces ¿qué debería poner en los bits de exponente si este es de solo 8 bits?

**Comment by Hernan4444** [comment]
Debes poner los bits que te acerquen lo más posible al número que quieres,  en este caso sería 11111111. 

Saludos

**Comment by glbello** [comment]
¡Great! Muchas gracias ☜(⌒▽⌒)☞
