### ISSUE TITLE
[Tarea 3] Prueba Demo Expirada

### ISSUE THREAD

**Issue by eitandv** [IIC2343/Syllabus#120]
Hola!
Tengo un problema con el emulador. Cuando intento correr el código me dice que mi prueba expiro, y me pide comprar el programa. Adjunto foto del mensaje. 
![image](https://user-images.githubusercontent.com/30673518/68532405-8df65780-02fb-11ea-9329-5fbeb7a7b2ee.png)

Si alguno sabe como solucionarlo le agradecería un montón!

**Comment by Snorlax8** [comment]
Hola! En la issue #106 alguien comenta sobre cómo solucionarlo :).

**Comment by eitandv** [comment]
Toda la razón! Gracias!!
