### ISSUE TITLE
Add/Sub

### ISSUE THREAD

**Issue by NicolasCourt** [IIC2343/syllabus#120]
Cuando hago un add o un sub, este sera con los 2 valores que esten mas arriba en el stack o sera con todos los valores que hayan en el stack?

**Comment by BSamilla** [comment]
Hola @NicolasCourt 

Usara los 2 valores del tope del stack, (y luego los eliminará)0. Esta especificado en el enunciado ;P

Saludos!

**Comment by NicolasCourt** [comment]
Ups jeje Gracias!
