### ISSUE TITLE
Interrogación 3 | Pregunta 7 | Registros C y D para direccionamiento.

### ISSUE THREAD

**Issue by fernandamansilla** [IIC2343/Syllabus#120]
Hola, no que me queda tan claro a que se refiere el enunciado cuando dice los "Registros C y D para direccionamiento".  Vimos distintos tipos de direccionamiento ¿se refiere a algún tipo en especifico? 

Gracias :)

**Comment by ceosorio** [comment]
Hola @fernandamansilla!

Nos referimos a direccionamiento indirecto por registro :)

Ánimo! ✨
