### ISSUE TITLE
[Tarea 3 - Programada] Data

### ISSUE THREAD

**Issue by JaviFerrada** [IIC2343/syllabus#120]
Hola, puedo asumir que las variables en el código assembly siempre serán declaradas al final? En ayudantía dijeron que no necesariamente, pero así aparece en el enunciado.

**Comment by Arcoirisky** [comment]
Te estás confundiendo de arquitectura O:
En esta está especificada de esa forma por lo que **necesariamente** deben ir al final pero ojo, no es al final de la memoria, sino al final del código a ejecutar.

**Comment by JaviFerrada** [comment]
oka, gracias!!

**Comment by fgbruna** [comment]
Reviviendo está issue aprovecho de preguntar lo siguiente:
Existe algun patron para diferenciar las variables de las instrucciones en el disassembler?
Digo esto por que creo que a priori podría considerar que cualquier número que estoy leyendo es una variable o bien un opcode? o por otro lado, si bien al parecer los datos están declarados luego de una instrucción `RET`, tampoco  creo poder saber con seguridad si lo que leo es esta instrucción(o su version para subrutinas), una variable con valor (51, 52, 65, 66) o bien un literal con ese valor.
Tal vez hay algo que no estoy viendo o algún fragmento del enunciado que lo deja claro y no lo entendi, si es asi haganmelo saber.
Gracias de antemano!

**Comment by mundurragac** [comment]
@frvalenzuela Lo que pregunta @fgbruna  + despues de las variables solo puede venir la instruccion NOP?

**Comment by jmwielandt** [comment]
```
Existe algún patrón para diferenciar las variables de las instrucciones en el disassembler?
```
@fgbruna 
Felicidades! Has encontrado la "cosa difícil" y el **propósito** (uno de ellos) de la tarea. 🎉🎉🎉 
En una arquitectura von neumann como la de nuestro computador VonTwelve o los computadores que usamos todos los días, tenemos una sola memoria principal, y en ella viven juntos tanto datos como instrucciones. [Así funcionan algunos virus](https://www.linkedin.com/pulse/reboot-computer-security-iot-michael-figueroa-cissp). 👀 

¿Cómo diferenciarlos? Ese es trabajo suyo. Les puedo asegurar que todos los tests tendrán la estructura del enunciado y en el propio enunciado menciono algo que les debería servir de pista (no es explícito, tiene que ver con la estructura del código máquina).

PD: en el caso feo en el que haya un salto hacia donde se guardan las variables, el simulador ejecuta lo que tenga que ejecutar. Recuerden manejar de alguna forma un posible opcode inválido.
PD2: solo ríjanse por la estructura y si hacen supuestos, arguméntenlos basándose en esta en su readme.
<hr/>
@mundurragac sí, tienes que llenar la memoria con "algo" y por defecto les decimos que la llenen con NOPs.

**Comment by mundurragac** [comment]
@jmwielandt Perfecto! Y que tamaño debe tener la memoria? Y en el caso de ser impar el PC (ya que las variables 'suman' 1)?

**Comment by jmwielandt** [comment]
Sobre el tamaño de la memoria, está explícito en el enunciado.
¿A qué te refieres de lo segundo?

**Comment by javierabao** [comment]
Sobre lo segundo, si para llenar la memoria con "NOP" me queda una cantidad de líneas impar, es decir, cuando llegue a la línea 4096 va a hacer un 'NOP' sin su respectivo '---' ¿tengo que llenar hasta la línea 4095, estando todos los 'NOP' con sus respectivos '---' o hasta la línea 4096 con un 'NOP' sin su '---')

**Comment by jmwielandt** [comment]
Las direcciones parten en 0.
Como posibles direcciones donde encuentres opcodes están:
0, 2, 4, 6, ... 4092, 4094 y sería.
Porque tu última dirección de memoria corresponde a 4095 y es un literal (o variable, en caso de tener una data muy muy grande).

**Comment by javierabao** [comment]
Creo que estoy confundida. Es que si tengo posibles direcciones donde encuentro opcodes en 0, 2, 4, hasta 12 por ejemplo, y luego tengo 5 variables, en 14, 15, 16, 17 y 18. Desde 19 en adelante tendría que llenar la memoria con NOPs, entonces en el espacio 4095 tendría un "0o0000 ; NOP" sin su respectivo "0o0000 ; ---", porque la cantidad de variables es impar. ¿Qué hago en ese caso? ¿O no estoy entendiendo bien cómo funciona?

**Comment by frvalenzuela** [comment]
Hola @javierabao ! 

Lo que sucedería en ese caso es que el program counter al siguiente ciclo para obtener tu literal, se sumará uno. Pero como el número máximo que puede representar es 4095, entonces tendrás un overflow del Program Counter ! Y por tanto comenzar a leer tus opcodes como literales y tus literales como opcodes recorriendo la memoria por segunda vez :0 ! 

Espero que eso aclare tu confusión. 

Saludos !

**Comment by javierabao** [comment]
Creo que aclara mi confusión, pero ahora mi duda ¿tengo que controlar ese caso de overflow? No se como llenar la memoria con variables impares y evitar eso jajaj.

**Comment by frvalenzuela** [comment]
Hola @javierabao ! 

No, no tienes que controlarlo. Puedes verlo como una porción de data muy grande donde todas son variables con cero si quieres manejar dicho caso. 

Saludos !

Saludos !
