### ISSUE TITLE
Problemas con MOV Ax, [BP+Lit]

### ISSUE THREAD

**Issue by miortiz1** [IIC2343/syllabus#121]
Viendo los cable, no logro encontrar la forma de cargar bp ni en el registro A de manera que pueda sumarle un literal y que salga de la alu de forma de cargar ese valor en A. Sólo puedo llevar sp al reg A.¿ Hay algo que no estoy viendo?

**Comment by frvalenzuela** [comment]
Hola!

Primero mencionar que esa instrucción debiese operar lo siguiente `Ax = Memory[BP+Lit]`. Siempre que exista un corchete cuadrado es en memoria. El literal puede sumarse con el componente Adder/Sub que esta conectado a BP.

Saludos!
