### ISSUE TITLE
Tarea 3 | Pregunta 1.2 | Archivos de prueba

### ISSUE THREAD

**Issue by nbnavarro** [IIC2343/Syllabus#121]
Hola,

Para las preguntas de pipelining ¿Es posible que nos entreguen archivos con ejemplos, tanto de entrada como de salida? Creo que serviría harto para verificar que lo que hagamos esté bien e incluso podría servir para aclarar un poco lo que se pide. 

Muchas gracias de antemano

**Comment by ceosorio** [comment]
Hola @nbnavarro!

No puedo subirles outputs, pero durante la tarde les puedo subir algunos ejemplos de input para que vayan probando el código :)

Espero que de todas formas les sea de ayuda para la tarea 😄 
Ánimo! ✨

**Comment by GbPoblete** [comment]
Hola! Por favor reconsiderar el no subir archivos de ejemplo de outputs.  Esto nos ayudaría mucho, para generar un conocimiento común y estándar de lo que se quiere que lleguemos. (sería como un hackerrank) No solo en términos de poder probar si nuestro código está generando lo que debería, si no también, para ver si se cumple con el formato que ustedes esperan que tenga el output. 

Por eso, estoy muy de acuerdo con mi compañero y me sumo a su petición.

Gracias de antemano! 😄

**Comment by ceosorio** [comment]
Hola @GbPoblete!

No es que no queramos subirselos, si no que los ayudantes también estamos colapsados :cry: 

Estamos haciendo lo posible para tenerles los outputs antes de la fecha de entrega pero tampoco se los podemos garantizar. Si logramos tenerlos a tiempo les avisaremos :3 

Ánimo con la tarea! :sparkles:
