### ISSUE TITLE
[TAREA 3] Subrutina A

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2343/Syllabus#121]
Es valido haber redondeado las horas en la Subrutina A?
Que descubrí una forma simple de determinarlas, pero el error máximo es de 9 segundos. Osea en el peor caso estoy considerando 22,9975 horas como 23 horas.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @ignacioislae !

Las horas truncadas. Si son 11 59 significa que son las 11. 

Saludos !

**Comment by Ignacioislae** [comment]
Vale gracias!
