### ISSUE TITLE
[Práctico] Duda sobre el Program Counter

### ISSUE THREAD

**Issue by eiherrera** [IIC2343/syllabus#121]
¡Hola!

En el computador básico visto en clases el PC, mediante un MUX, recibe señales provenientes de la ROM, la RAM y la unidad de control, además de otra señal que recibe directamente de esta última componente. Pero en el caso del diagrama del enunciado, el PC no recibe inputs además del clock. Quizás estoy entendiendo mal la materia pero no comprendo cómo se va a lograr elegir las instrucciones si es que el PC no recibe feedback alguno.

**Comment by BSamilla** [comment]
Efectivamente en el computador básico el PC puede recibir datos desde la RAM y la ROM, ademas de las respectivas señales de control que se usan para elegir cual usar. Pero esto solo se usa a la hora de los saltos donde hay que darle a PC el valor al que debe apuntar.

La maquina de stack no tiene funcionalidades de salto, por lo que no requiere de esta retro-alimentacion, el PC va a ir instrucción por instrucción de manera secuencial partiendo desde la instrucción 0.

Saludos!

**Comment by eiherrera** [comment]
¡Gracias! Me quedó clarísimo, estaba confundiendo conceptos. Respecto a las instrucciones de la ROM, ¿podrían darnos alguna batería de instrucciones de prueba válidas para ver si está funcionando correctamente nuestro programa?

Saludos!

**Comment by BSamilla** [comment]
Tienes todas las herramientas para crear tus propios test. (Básicamente es colocar un opcode mas un literal :P).

Saludos y exito!
