### ISSUE TITLE
Multiplicacion

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2343/syllabus#121]
¿La multiplicación también hay que implementarla?. Un ayudante nos había comentado que no.

**Comment by Hernan4444** [comment]
@berrazuriz1 Si hay que implementar la multiplicacion, talvez el ayudante pensó en su semestre porque todos cuando dimos el curso no se pedía la multiplicación, pero en el enunciado se especifica que hay que implementarla.

Saludos

**Comment by berrazuriz1** [comment]
¿y se puede usar el comando de multiplicación o tenemos que implementarla nosotros?

**Comment by Hernan4444** [comment]
Tienen que implementarla ustedes con compuertas lógicas
