### ISSUE TITLE
Administrativa | Horarios Examen

### ISSUE THREAD

**Issue by bpardobravo** [IIC2343/Syllabus#122]
Hola, se tiene claridad ya de que hora a que hora será el examen? Necesito saberlo para inscribirme en horarios de presentaciones de otro ramo.

**Comment by jmwielandt** [comment]
Hola,
Lo que tenemos hablado es que sea el 9 de julio durante la mañana. Apenas tengamos fijo el horario lo avisaremos.
Saludos!
