### ISSUE TITLE
Plazo Tarea 3

### ISSUE THREAD

**Issue by Okhan97** [IIC2343/syllabus#122]
Hola,

¿Podrían dar mas tiempo para hacer la tarea 3? (Hasta el Domingo por ejemplo)

**Comment by ignacioaraya1995** [comment]
Sobretodo considerando todas las veces que se ha cambiado el enunciado.

**Comment by CmPoblete** [comment]
Por favor

**Comment by nicoparraguez** [comment]
plis

**Comment by Taeval** [comment]
Por favor! D:

**Comment by Jaluco** [comment]
+10000

**Comment by llloyola** [comment]
Por ✖️ Favor 🙏 Necesitamos 😭 Más ➕ Plazo ⏳ Para 🛑  La 🎵 Tarea 📝

No, pero hablando en serio, muchos estamos complicados con la tarea. ¿Podrían considerar la posibilidad de darnos más plazo? Por favor 😞

**Comment by jmwielandt** [comment]
En unos minutos les llegará un aviso al respecto.
Ánimo con la tarea~

**Comment by Okhan97** [comment]
Gracias por extender el plazo!
