### ISSUE TITLE
Bitstream error

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2343/syllabus#122]
Cuando creamos el archivo bit nos sale el siguiente error.

![image](https://user-images.githubusercontent.com/26139173/29999166-a5fb312c-9014-11e7-9140-d2a9b492422d.png)

Nos estaba funcionando pero de un minuto a otro lanzo este error.

**Comment by Hernan4444** [comment]
@Rudyjb24 es posible que suban su código para ver como están haciendo las conexiones??
Y por saber, cada vez que hacen un cambio hacen la syntesis e implementacion??

Espero respuesta

**Comment by Rudyjb24** [comment]
Ya lo resolvimos, gracias igual

**Comment by jisilvamc** [comment]
Nosotros tenemos el mismo error, pero no nos ha llegado a funcionar todavía... ¿cómo se resuelve?

**Comment by Rudyjb24** [comment]
No estamos 100% seguros de que era el error, que lo causaba ni como lo arreglamos. Creemos que se produjo porque le cambiamos el nombre a la carpeta del proyecto. Lo que hicimos fue guardar en bloc de notas todos los módulos que habíamos creado, borramos todo, descargamos el proyecto base de nuevo y creamos todos los módulos de nuevo y ahí volvió a funcionar.

**Comment by lileiva** [comment]
el error puede ser por muchas cosas asi que lo mejor es que nos digan el grupo y suban su proyecto para poder revisar bien, igual generalmente pueden ser errores se sintaxis
