### ISSUE TITLE
Robot encuentra bombilla apagada

### ISSUE THREAD

**Issue by Pipelao** [IIC2343/Syllabus#122]
Hola,

Al leer el enunciado nuevamente de la tarea me surgió la siguiente duda, ¿al final encontrarse con una bombilla o un pared se ejecuta la misma acción?, es decir, girar hacia lado de la mano dominante. Porque en el enunciado dice si encuentra una bombilla apagada debe dar media vuelta, ¿o media vuelta se refiere a un giro de 180° y no de 90° como sería un giro?

Gracias.

**Comment by Allmoz** [comment]
Media fuelta se refiere se refiere a un giro de 180°

**Comment by Pipelao** [comment]
Gracias @Allmoz
