### ISSUE TITLE
Tarea 3 | Pregunta 1 | Error en input_parser.py

### ISSUE THREAD

**Issue by jmsilvas** [IIC2343/Syllabus#123]
Hola! 
Estaba probando el parser y al parecer hay un error. Este empieza a leer instrucciones desde la posición 2 y la primera intrucción en el archivo de ejemplo está en la posición 3 (por lo que arroja error). Mi pregunta es, debemos corregir la función parse para que lea desde la posición 3 o es el ejemplo el que está malo?

**Comment by jmwielandt** [comment]
Hola,

Con un código como este funciona bien. Recuerda que se lee por stdin (usando `input`) y no como un archivo.

```python
import input_parser


n = int(input())  # número de líneas de la tabla
to_parse = []
for _ in range(n):
    to_parse.append(input())  # leo las n entradas siguientes

parsed = input_parser.parse(to_parse)
for i in parsed:
    print(i["instruction"])
```

Saludos!

**Comment by jmsilvas** [comment]
Perfecto! Si lo estaba haciendo por stdin, pero estaba enviando el n también al parser. Esa era la linea de diferencia en mi código, gracias!
