### ISSUE TITLE
[T3-Placa] Funcionamiento PC y memoria

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2343/syllabus#123]
Primera duda:
Cuando comienza el funcionamiento del computador el clock y PC parten en cero, luego la señal del pc llegaría al muxadress con el objetivo de llegar a la main memory, pero no sabemos que valor tiene el selector del muxadress que permitiría el acceso a la main memory ya que aun la CU no ha liberado las señales de control. 
Segunda duda:
Asumiendo que se logra llegar a la main memory, pasamos el dataout al registro CU, el cual se almacena en esta unidad y libera la señal stallingPC=0 lo que es recibido en el PC, luego el PC no aumenta su valor sino que se mantiene y como es posible entonces leer la siguiente palabra de la memoria que contiene el literal?.

**Comment by frvalenzuela** [comment]
Hola Daniel!

Primera duda: 
Durante al inicio primer ciclo debes pensar que lo que entregue la control unit estará todo los bits en cero. Por lo que la señal que recibe el selector del MUX será "000" (al igual que todos los selectores). Esa señal debiese ser la que debería ser seleccionado por el PC.

Segunda Duda:
De eso se encarga RegisterCU, quien manda la señal de staling en el segundo ciclo, y en el tercer ciclo apaga esa señal para que en cuarto ciclo sea lea nuevamente un opcode.

Ojalá quedase claro ahora. De no ser así por favor hacerlo saber.

Saludos!

**Comment by FelipeCampbell** [comment]
Nos quedó claro. Pero nos surgió otra duda al respecto del ADD/SUB que está unido al MUX Data In. Tiene dos inputs y uno de ellos es solo un 1,  debemos asumir que este es un 1 binario de 12 bits ( 0000 0000 0001)? . Por otro lado el selector es un 0 siempre por lo que siempre suma 1 al valor que sale del PC?

**Comment by frvalenzuela** [comment]
Hola Felipe!

Lo que asumes es correcto, y lo que dices es correcto suma PC+1.

Saludos!

**Comment by rafafdz** [comment]
Hola!  @frvalenzuela, sigo confundido con respecto al tema de los ciclos.

El RegisterCU, según el código que nos dieron, tiene dos estados posibles que van alternándose: *cargar = 0* y *cargar = 1*, que permitien que los opcodes pasen a la CU y los literales no.

Sin embargo, dado que estamos usando *3* ciclos, en el tercero el RegisterCU se encuentra en el estado *cargar = 1*, provocando que pase a la CU el valor almacenado en Memory[Literal] (Ya que en este ciclo el PC no avanzó, provocando que el literal llegue nuevamente al RegisterCU) y que (ahora sí) se propaguen señales de control que sobreescribirán a las que correspondían con la instrucción programada.

Por lo que  1) Se está leyendo una instruccion incorrecta. y 2) Se está sobreescribiendo la instrucción actual.

Está bien lo que digo? Si es así, que se hace al respecto?
Gracias!

**Comment by FelipeCampbell** [comment]
+1. Porfa podrían aclarar esto que creo que explica os problemas que me pasan cuando intento testear mis instrucciones. Se ejecutan las líneas más de una vez claramente

**Comment by Arcoirisky** [comment]
Estamos revisando el porqué no pueden testearlas desde el momento en el que surgieron los problemas. 

Trabajamos una solución que no les obligue a cambiar su tarea, en el peor de los casos.

De todas formas, solo falta que puedan probar sus tareas en caso de que ya tengan soporte a todas las instrucciones como se les pidió en el enunciado.

**Comment by frvalenzuela** [comment]
Hola @rafafdz y @FelipeCampbell 

Esta todo aclarado en #144. Si existe alguna otra duda favor hacerlo saber!

Saludos!
