### ISSUE TITLE
Señal P en floats

### ISSUE THREAD

**Issue by Pyralspite** [IIC2343/syllabus#123]
Hola!
En el caso de los floats, con el último bit del resultado se refieren al resultado "en bruto" o a una vez que lo transformamos al estandar de un float? Por ejemplo, el 3.5 en binario se escribiría como 11.1, por lo que la señal P debería activarse, pero una vez que se normaliza y escribe como float se rellena con 0 a la derecha, por lo que no debería activarse. Que hacemos?

**Comment by Hernan4444** [comment]
@Pyralspite considerando que queda 1 día para entregar vamos a optar por dejarlo a tu criterio. La unica condición es que especifiques en una sección del informe estas decisiones que tomaste. 

Para la interpretación de la señal P, basate solo en como funciona esta señal con los números enteros.

Saludos!!
