### ISSUE TITLE
números negativos programación

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#123]
Hola!

Nuestro programa tiene que manejar números negativos?
En caso de ser afirmativo, en python los negativos binarios se representan así:
'-0b1010' para el -10, por ejemplo. 
¿Podemos usar esa representación o tenemos que pasar a complemento a dos?

**Comment by FranLucchini** [comment]
Hola, sólo pedimos números positivos.

**Comment by frvalenzuela** [comment]
Y para el bonus donde se debe implementar saltos condiciones, seguimos la convención de complemento 2?

**Comment by Geeermy** [comment]
@frvalenzuela Lo que prefieras, ya que es parte de los supuestos que deben hacer. Toda decisión que tomes al respecto debe ser justificada en el archivo PDF solicitado. 🌝

**Comment by frvalenzuela** [comment]
Okey muchas gracias !
