### ISSUE TITLE
Tarea 3 | Pregunta 1.1 y 2  | Dudas generales enunciado

### ISSUE THREAD

**Issue by isiguelfand** [IIC2343/Syllabus#124]
Hola!
En la pregunta 1.1, se puede asumir que todas las instrucciones son del tipo MOV? Además, no entiendo a que forwarding units se refieren las fw1 y fw2, ni donde se debe indicar si es necesario hacer stalling. 
En la pregunta 2, no me quedó claro _cuando_ se debe redondear.

**Comment by jmwielandt** [comment]
> En la pregunta 1.1, se puede asumir que todas las instrucciones son del tipo MOV?

No, se usa la ISA completa. Mira los ejemplos subidos.

> Además, no entiendo a que forwarding units se refieren las fw1 y fw2

Esas forwarding units:

![image](https://user-images.githubusercontent.com/37153467/85166726-b5b88100-b235-11ea-816c-c3b9b7b945bb.png)

> ni donde se debe indicar si es necesario hacer stalling.

Acabo de resubir el enunciado agregando esa información

> En la pregunta 2, no me quedó claro cuando se debe redondear.

Justo antes de hacer el print. Lo agregaré como footnote.

**Comment by isiguelfand** [comment]
Muchas gracias!
