### ISSUE TITLE
Funcionamiento del control unit

### ISSUE THREAD

**Issue by naquiroz** [IIC2343/syllabus#124]
Hola! Estuve revisando el código de computador básico y no entiendo cómo funciona el control unit. Entiendo que al final este es el componente que guarda todas las instrucciones posibles del computador, pero no veo como esto está pasando en el CU entregado, podrían explicarme?

**Comment by nivek0o0** [comment]
Hola, la Control Unit se encarga de traducir un opcode en señales de control, por lo que debe almacenar la combinación de señales para cada una de las instrucciones. Puedes imaginarla como una tabla donde cada fila corresponde a una instrucción y cada columna a una señal. La forma más fácil es que almacene un arreglo y se acceda a él utilizando el opcode como índice.

Es similar al funcionamiento de la ROM, que posee un arreglo de instrucciones y se accede a ellas utilizando el valor del PC como índice. Deberás preocuparte de que el arreglo, sus elementos y las señales para su acceso tengan un tamaño adecuado para alcanzar a manejar todas las instrucciones.

**Comment by naquiroz** [comment]
@nivek0o0 gracias por la respuesta! Pero no era esa mi pregunta, mi pregunta era más a nivel de código. No entiendo cómo esa "tabla" que tú dices, está en el código entregado en la tarea

**Comment by nivek0o0** [comment]
En el código entregado para la tarea no está, porque ese código es solo una base que ustedes deben desarrollar para lograr las funcionalidades solicitadas. La tabla deben crearla ustedes y definirla en la CU, de manera similar a lo que hay en la ROM.
