### ISSUE TITLE
[Tarea 3 - Programada] Stack pointer

### ISSUE THREAD

**Issue by cristobalilabaca** [IIC2343/syllabus#124]
En el ejemplo de la ejecución del simulador sale que en las 5 primeras instrucciones el stack pointer(sp) vale 0. Pero este no deberia apuntar al final de la memoria y por lo tanto tener un valor de 7777?

**Comment by tomasrivera** [comment]
Hola, cuando utilizas **`PUSH`**, para agregar algo al **_stack_** estas haciendo `SP = SP - 1`. Por lo tanto, al ingresar el **primer** valor, este será guardado en la **última** dirección de la memoria.
De lo contrario, se estaría dejando un espacio de la memoria sin utilizar.

**Comment by cristobalilabaca** [comment]
Ok. Entonces esta mal que sp se inicialize en 0 como sale en la simulación de ejemplo del enunciado?

**Comment by tomasrivera** [comment]
No, porque no has metido nada en el _stack_ y necesitas que sea 0 para que el primer ingreso quede en la última posición.
Recuerda que primero mueves el `SP` y después guardas el valor.

**Comment by cristobalilabaca** [comment]
Pero si parte en 0 me va a quedar un valor negativo cuando haga `SP = SP - 1` y no existen direcciones de memoria negativas. Como funciona en ese caso?

**Comment by tomasrivera** [comment]
De 0 pasa a la última posición

**Comment by Jj1martinez** [comment]
Si hago el pimer PUSH Ax, el SP pasa a valer 7777 y entonces Memory[777] = Ax?

Aprovechando también, CMP viene acompañado siempre de un salto JMP,JE, etc? Y cuando hace el salto, entiendo que PC = DIR, pero en el simulador, en la primera columna, si PC estaba en 0o0023 por ejemplo, y Dir estaba en 0o0001, en la columna de PC, pasa a contar desde el 0o0001 hacia abajo?
Graciass

**Comment by auirarrazaval** [comment]
@Jj1martinez perdón por la demora. 
Respecto ala primera pregunta, la respuesta es si, ya que si te das cuenta en la ISA, el SP disminuye en 1 al hacer push, por lo que el stack de memoria se empieza a llenar desde la mayor dirección de memoria (7777) hasta la menor (0000). 

> CMP viene acompañado siempre de un salto JMP,JE, etc?
Si, ya que el salto que viene seguido de CMP usa los valores obtenidos como status del CMP (z, o, etc...), por lo que no tendría sentido hacer una comparación (CMP) y no usar esos valores en la siguiente intrucción. (En teoría podría ocurrir, pero sería un desperdicio)
