### ISSUE TITLE
Entrega tarea 1

### ISSUE THREAD

**Issue by sebawarrior** [IIC2343/syllabus#124]
Hola, quisiera saber si tenemos hasta las 23:59 del día lunes para entregar la tarea individual. Muchas gracias!

**Comment by IriSalazar** [comment]
En el readme sale esto!

![image](https://user-images.githubusercontent.com/26166202/30003705-157e3138-9098-11e7-8ef1-6e88e7697bcf.png)

**Comment by IriSalazar** [comment]
nosotros habiamos entendido que la tarea era grupal, igual que el proyecto. alguien sabe como es efectivamente?

**Comment by sebawarrior** [comment]
Gracias Iri!, yo tengo entendido que es individual... pero espera a que responda un ayudante mejor jaja

**Comment by Okhan97** [comment]
Tambien tenia entendido que la tarea era grupal (pues se sube al repo local)

**Comment by Hernan4444** [comment]
La tarea es 1 por grupo (por algo se les pide que la suban al repo que les dimos). Para quienes convalidaron el proyecto, es individual. La hora de entrega es a las 23:59 del día lunea, tienen hasta esa hora para subir la tarea e informes.

Saludos
