### ISSUE TITLE
Administrativa | Tarea 3

### ISSUE THREAD

**Issue by narierao** [IIC2343/Syllabus#125]
Hola! Me podrían aclarar este punto por favor?

Para efectos del cálculo del promedio de tareas, seguiremos considerando la tarea 3 como tres notas aunque una de las preguntas valga por dos. Si tienen una pregunta de la T2 con buena nota, lo que les conviene es enfocarse en 1 pregunta de pipeline para completar las 2 faltantes, pero si tienen 2 notas de la T2 con las que se quieran quedar, les conviene enfocarse en la pregunta de caché. Por último, si tienen las 3 preguntas de la T2, felicidades, pueden botar la T2 y usar su tiempo para estudiar otras cosas o invertirlo en ocio (es importante). De todas formas les recomiendo hacer las preguntas que no necesiten hacer de la tarea 3 por motivos de un mejor aprendizaje, pero es normal que no sea una prioridad en estos momentos.

No entiendo si debo hacer o no la Tarea 3, ya que aún no tengo mis notas de la T2. 

Gracias!

**Comment by jmwielandt** [comment]
Hola,

Allí hablo de las preguntas de programación de la tarea 2, que son las que importan para decidir si hacer o no la T3. Si no tienes notas de la T2, quiere decir que no la hiciste.

Saludos
