### ISSUE TITLE
[T3-Placa] Probar circuito

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2343/syllabus#125]
Como podemos testear las instrucciones (mas bien la CU) teniendo ya todos los componentes y conexiones necesarias????

**Comment by frvalenzuela** [comment]
Hola Daniel! 


Puedes escribir instrucciones en la MainMemory y ver los resultados de los registros en el display. 

Saludos !

**Comment by DanielCarrascoFalcon** [comment]
Correcto, solo que todo pasa muy rápido y no alcanzo a diferenciar los valores...
Hay alguna posibilidad de poner un delay o algo por el estilo?

**Comment by tomasrivera** [comment]
Es por eso que puedes modificar la velocidad del _clock_ en la instancia del _clock Divider_ :smile:

**Comment by DanielCarrascoFalcon** [comment]
Perfect! Graciaas

**Comment by Jiparavich** [comment]
Hola! Estamos teniendo problemas al probar los display, 
Le cambiamos unas pocas lineas al mainmemory y nos corrio la sintesis, la implementacion y el bitstream.
Pero a la hora de cambiar las lineas de codigo de los display nos tiro un errror gigante y llevamos harto rato viendo que pudo haber sucedido y estamos estancados. 
Adjunto imagenes.

LINEA DE LOS DISPLAY DONDE ax,bx son las señales de salida de los registros.
![image](https://user-images.githubusercontent.com/30678179/57422584-b2536900-71de-11e9-94f4-e6fa7d1dce88.png)

LINEAS MODIFICADAS DEL MAIN MEMORY
![image](https://user-images.githubusercontent.com/30678179/57422601-c8612980-71de-11e9-9eba-7f5909e8b95c.png)




IMAGEN DEL ERROR
![image](https://user-images.githubusercontent.com/30678179/57422584-b2536900-71de-11e9-94f4-e6fa7d1dce88.png)

**Comment by jgespinosa10** [comment]
Hola, yo también estoy intentando conectarme y estoy teniendo el mismo error! No tengo idea que hacer al respecto, me podrían guiar? De acuerdo con el error aparece que es en las instancias de register CU, main memory y BP.

![image](https://user-images.githubusercontent.com/30691527/57471126-765cea00-7258-11e9-88eb-08461d1d61ab.png)

**Comment by MrEarle** [comment]
Me sumo a la pregunta! Me esta pasando exactamente lo mismo

**Comment by Arcoirisky** [comment]
Estamos viendo el problema O: (Desde hace tiempo ;---;) No se preocupen por el tiempo e intenten probando otras instrucciones más básicas -que no necesiten más de un ciclo- en caso que no les funcione, checkeen las conexiones de sus componentes, ya que se estaría generando un loop combinacional (o eso es lo que dice el error)

**Comment by frvalenzuela** [comment]
Hola @MrEarle , @jgespinosa10 , @Jiparavich !

Favor revisar #144 , si queda alguna otra duda, favor hacerlo saber!

Saludos!
