### ISSUE TITLE
Significado código T05 -Práctico-

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#125]
Hola!
Quería saber qué es lo que hace el código de ejemplo de la tarea o: Corrí el programa en la placa y los 7 segmentos me muestran 0A11 y el led(0) no deja de flashear. Supongo que el led(0) se enciende al momento de cambiar de instrucción (o cada flanco de subida del clock) pero ¿qué hacen los led(1) y led(2)? ¿Qué significan 0A11? 
Entiendo que 0A es una salida y 11 es otra pero no entiendo qué significan al finalizar el programa o:

**Comment by Geeermy** [comment]
@Arcoirisky Por favor no cierren las _issues_ si ya resolvieron sus dudas. Más aún, si las resolvieron, sería ideal que lo comentaran ya que así otros compañeros pueden tener claridad de lo preguntado y se evita más _spam_. ¡Gracias! 😸

**Comment by Arcoirisky** [comment]
Al final fue leer mucho y completar mapa mental del computador u-u
