### ISSUE TITLE
T3 Placa - Instrucción CALL

### ISSUE THREAD

**Issue by Jiparavich** [IIC2343/syllabus#126]
Hola!
Tenemos una duda respecto a la siguiente operación:
CALL --> Memory[SP] = PC; SP = SP - 1; PC = Dir

Si quiero que M[SP] me guarde PC, tengo que hacer que selADD me deje pasar a SP para que se guarde en M[SP], pero luego tengo que hacer PC=Dir, y no veo como hacer que Dir llegue a PC ya que deje pasar a SP y no a DIR... No se si entiende la pregunta?

Esta es nuestra convención:
selAdd(3:0)

0000 | PC
0001 | SP
0010 | BP +- Lit
0011 | Bx
0100 | Dir

Entonces a lo que voy, es que para hacer la instrucción de arriba

1- Memory[SP] = PC
2. SP = SP - 1
3. PC = DIR
Para hacer el paso 1. Necesito SelAdd => 0001 | SP, por tanto, como despues obtengo DIR para PC = Dir ?

**Comment by Arcoirisky** [comment]
Estamos trabajando para usted~

**Comment by DanielCarrascoFalcon** [comment]
Según lo que yo entendí ese DIR es el literal que se nos entrega y se propaga en el primer ciclo, entonces para pasarlo al PC lo único que habría que hacer es activar el loadPC para que reciba lo que sale de la memoria y listo.
Me enredo con el orden en que ocurren las cosas no más, no se si se escribe en memoria el valor de PC o de DIR, pero quiero creer que están implementadas correctamente las entidades que nos pasaron y se encargan de ello. 😃 
Es la única forma de poder lograrlo según yo (y finalmente el PC que se guarda en Memory[SP] es el DIR, creo).

**Comment by brayanmoreno** [comment]
@DanielCarrascoFalcon Pero por lo que entiendo es una llamada a una subrutina, entonces queremos guardar el valor que tiene el PC antes de cambiarlo, pero eso no lo puedes hacer en un solo paso.

**Comment by frvalenzuela** [comment]
Hola @Jiparavich y @DanielCarrascoFalcon !

Favor revisar #144 . Si la duda persiste por favor hacerlo saber!

Saludos!
