### ISSUE TITLE
Error al compilar

### ISSUE THREAD

**Issue by dalliende** [IIC2343/syllabus#126]
Estimados, cuando compilamos nos arroja un error con los switches, quisieramos saber cual podria ser el motivo, adjunto una imagen con el error que nos tira vivado.

![image](https://user-images.githubusercontent.com/11409081/30004921-e49ec256-90ad-11e7-87cc-53bdfae663c9.png)

**Comment by Hernan4444** [comment]
@dalliende lo que pasa es que tus LED están conectados a los sw y a la ALU. Es decir que una conexion tipo `out` recibe señales de dos partes y no sabe a cual "hacerle caso" a los sw o al resultado de la ALU.

Saludos

**Comment by dalliende** [comment]
Ok, gracias
