### ISSUE TITLE
Tarea 3 | Pregunta 1.1 Pipeline 1 | Ejemplos pipelining y caché

### ISSUE THREAD

**Issue by mariana-ortega** [IIC2343/Syllabus#126]
Hola!

No me queda claro a qué preguntas de la tarea corresponden los archivos ejemplo1.txt, ejemplo2.txt, ejemplo3.txt y test_ejemplo_t3.txt ni por qué el ejemplo 3 tiene también un archivo test.
No hay ninguna forma de probar, por ejemplo con hackerrank como en la tarea 1 si nuestro programa es correcto para las de pipelining?

Saludos,
Mariana

**Comment by ceosorio** [comment]
Hola @mariana-ortega!

Ojo que el que dice test no está relacionado con el ejemplo3 (por eso termina en t3). Al final es otro ejemplo de input para que usen :) Estos inputs pueden ser usados para las preguntas de Pipeline y Caché. 
Además, el `test_ejemplo_t3.txt` corresponde al input que se genera a partir del archivo `código_bonus_t3.txt`

De momento no estaríamos subiendo los outputs de esos ejemplos (estamos todos con hartas cosas :c), pero haremos lo posible por ojalá tenerlos antes de la entrega de la tarea.

Ánimo y éxito! ✨
