### ISSUE TITLE
No usar int enunciado

### ISSUE THREAD

**Issue by glbello** [IIC2343/syllabus#127]
Bajo qué criterio no puedo usar int de python, ya que por ejemplo quiero expresar un numero decimal que viene en base b, luego mi algoritmo yo quiero realizar operaciones del tipo $$a * b^-(n+1)$$, y para simplificarme la vida, la base b lo paso a int, y realizo mi operacion deseada

y más bien quiero saber el criterio de no usar int... creo que es demasiada drástica esa desición 😢 😭

**Comment by Hernan4444** [comment]
el `int()` es para evitar el cambio de base. Para evitar complicaciones al momento de corregir, te recomiendo tener una funcion o un diccionario que cambie cada string en un numero por ejemplo:
```
transformar  = {"1": 1, "2": 2, .... , "9":9 }
```
Con eso pasas cada número a int y no ocupas esa función.

Saludos

**Comment by glbello** [comment]
omg!, esto soluciona mis problemas, felicidad ven a mí! mil graacias 🤗
