### ISSUE TITLE
Tarea 3 Preg. 1.a ¿Complejidad? [Tarea 3]

### ISSUE THREAD

**Issue by gebalassa** [IIC2343/syllabus#127]
Hola! Me encuentro haciendo la **T3** 1.a como ejercicio. He leído múltiples issues sobre la **T3** y he entendido lo esperado respecto a pasar **Q** como si fuese un input cualquiera. Sin embargo, me complica la complejidad que puedan alcanzar los circuitos que piden:

Considerando que las puertas lógicas pueden combinarse de infinitas maneras se le debe agregar n-Flip Flops, no se me ocurre una forma _generalizada_ de pasarlo a combinacional. En el ejemplo dado, si uno toma **Q** y **C** como input, da una tabla de verdad que es reemplazable por una compuerta **XOR**. Sencillo, considerando sólo dos inputs. El problema viene cuando se generaliza lo anterior a n-FF, n-inputs y n-outputs, sumados a combinaciones con puertas lógicas. Probé agregando un tercer _input_ **B** que entra, junto a **Q,**  a una compuerta **AND** y luego al **NOT** del ejemplo, como una pequeña modificación. Me encuentro actualmente intentando resolverlo pero no tengo idea cómo.

¿De qué manera puedo recortar las posibilidades para que sea manejable?

Disculpen por preguntar sobre una tarea pasada, pero no la pude hacer correctamente, entre varios factores, por lo anterior.

Mil gracias de antemano,
Gabriel.-

**Comment by Geeermy** [comment]
¡Hola!

Una forma de recortar tus posibilidades sería identificar los _flip-flops_ cuyo estado no afecta la salida del circuito, por lo que no van a afectar a tu tabla de verdad y puedes ignorarlos (si así lo deseas).

Por otra parte, si trabajamos con un circuito combinacional, ¿tiene sentido trabajar con las señales ```C``` de los _flip-flops_, si vamos a dejar de lado la idea de secuencia y cambio por flanco de subida? No digo que no pueden ser utilizadas, pero no debiesen ser vitales para tu tabla de verdad finalmente.

Considerando esos dos casos, puedes ver que el traspaso es más escalable. No obstante lo anterior, habrán circuitos gigantes donde claramente tendríamos un _input_ de un largo para nada despreciable. Puedes asumir que esos casos no serán (o no fueron) evaluados ya que nos interesa que vean la funcionalidad de esta transformación en circuitos bastante acotados.

¡Que estés bien!

**Comment by gebalassa** [comment]
Gracias por responder.

Para entenderte mejor, ¿Tienes alguna idea de cómo abarcar el ejemplo mismo
y el ejemplo modificado que hice después? Este ejemplo modificado recibe el
nuevo input **B** en interactúa con **Q**.

Adicionalmente, no logro entender por qué podría ignorar **C**, siendo que
es literalmente donde llega input del ejemplo en cuestión, más aún para
otros casos (digo yo).

Mil gracias,
Gabriel.-

**Comment by Geeermy** [comment]
El tema de la señal ```C``` es que su gracia es actualizar el estado del _flip-flop_ en un franco de subida, _i.e._ un cambio de 0 a 1 en esta señal. Ahora quieres ver su efecto en un circuito combinacional, así que simplemente puedes asumir que estarás siempre en un flanco de subida y olvidarte de ```C``` (no está mal asumir que sí tiene importancia, pero eso ya depende de cómo lo hayas pensado).

En el ejemplo, si tratas el estado como un _input_, puedes decir que la versión combinacional es un circuito que simplemente recibe una señal ```Q``` como _input_ y que tiene de salida el ```NOT``` de dicha señal. Eso es válido.

Finalmente, no entendí tu uso de una señal ```B``` como _input_, no me parece necesario independiente de la funcionalidad que hayas pensado para ella.

**Comment by gebalassa** [comment]
Se me había olvidado que C sólo importa en flanco de subida durante un
instante y por tanto se debía poder ignorar si se busca un análogo
combinacional. Ahora, ¿No volvería eso totalmente trivial el input?


Segundo, me surge otro problema:

Q está conectado directamente al output, y a D. Asumiendo C en flanco de
subida cte., ¿Qué hace más válido decir que el output es el NOT de Q,
versus decir que el output es simplemente Q?

**Comment by Geeermy** [comment]
1. Nadie dijo que era difícil, era más importante que pasaran por el proceso de darse cuenta de ello, lo que no era fácil o inmediato sin un análisis previo de su parte.

2. Prima el hecho de que al final del circuito lo que se obtiene es ```Qt = NOT(Qt-1)```, tanto para el nuevo estado del _flip-flop_ como para el _output_. Al final puedes pensar el nuevo _input_ como el estado previo más que el estado actual del circuito secuencial, ya que este estado previo es el que determina el resultado final.
