### ISSUE TITLE
Tarea 3 | Pregunta 3 | Duda print_cache

### ISSUE THREAD

**Issue by diegomendieta** [IIC2343/Syllabus#127]
Hola, la función print_cache retorna una lista con un formato diferente al del ejemplo del enunciado. Tenemos que usar el formato del enunciado o el retornado por print_cache?

**Comment by diegomendieta** [comment]
Además, no queda claro el orden en que se deben imprimir o llenar (cuando están vacíos) los bloques. Podrían especificarlo, por favor?

**Comment by jmwielandt** [comment]
¿Cuál es la diferencia en el formato? 🤔

El orden en el que se llenan los bloques es el del tipo de caché N-Way associative, con las características que se describen en el enunciado. Eso es materia.

**Comment by tomasmetroy** [comment]
La diferencia sería que en el ejemplo del enunciado la cache se imprime como una lista, pero usando print_cache y siguiendo el formato de los inputs que esta pide se imprimiría la caché como una lista que contiene una lista, ya que lo que retorna print_cache es del tipo

[lista1 + lista2 + lista3 + lista4], cuando según el ejemplo del enunciado debiera ser lista1 + lista2 + lista3 + lista4

**Comment by ceosorio** [comment]
Hola @tomasmetroy!

Revisamos el parser e hicimos los cambios en `print_cache` para que ahora retorne el resultado como sale en el ejemplo. Vamos también a subir un anuncio con este cambio para que todos estén al tanto :) Gracias por hacernoslo notar!

Éxito en la tarea! :sparkles:
