### ISSUE TITLE
Tarea 3 | Pregunta 1.3 | Ubicación para cada línea

### ISSUE THREAD

**Issue by mora4** [IIC2343/Syllabus#128]
Hola, 
En clases vimos que las caches _2-way associative_ tienen 2 ubicaciones posibles para cada dirección de memoria. ¿Hay una manera particular en la que debemos hacer este _mapping_ de dirección de memoria -> posibles ubicaciones? O independiente de eso deberiamos llegar a las mismas cantidades de hits y misses?

Y otra duda: ¿cual es el rango de direcciones de la memoria?

Gracias!

**Comment by ceosorio** [comment]
Hola @mora4!

Para una caché 2-way associative, direcciones de memoria te dicen en qué parte debes guardarlas. Lo explicaré usando la imagen de los apuntes:
![2-way associative](https://user-images.githubusercontent.com/18428726/85207166-f1fee680-b2f4-11ea-9653-8cb4a9c05e47.png)
En la parte izquierda están las direcciones de memoria y a la derecha la caché. En este caso estamos viendo una cache 2-way associative con bloques de 2 direcciones cada uno. 
Cuando uno guarda direcciones de memoria en la caché, uno en realidad toma el bloque entero (en este caso guardas 2 direcciones a la vez), por lo tanto los bits en **azul y celeste** te dirán la posición relativa de esa dirección _dentro_ del bloque.

Luego, para saber en qué conjunto debe guardarse el bloque, revisamos el bit que en este caso está en **naranjo (o amarillo, no se nota mucho)**. Si te fijas en la imagen, los que tienen un 0 corresponden al conjunto 0, por ejemplo. Los bits restantes serán el tag.

La cantidad de bits que se necesitas para cada ID (lugar dentro del bloque, y conjunto), dependerá de la cantidad de direcciones dentro de un bloque y la cantidad de conjuntos que tengas.

Espero que con esto te haya aclarado la duda. En caso de que tengas más dudas de esto, no dudes en avisar :3 

Ánimo y éxito en la tarea! :sparkles: 

PD: En la imagen sale 3 = 00111, debe ser 00011
