### ISSUE TITLE
Formato de input [t03-programada]

### ISSUE THREAD

**Issue by emontecinos** [IIC2343/syllabus#128]
Cómo será el formato de los inputs con los que evaluarán la tarea
Serán como [precomp](https://github.com/IIC2343/syllabus/blob/master/Tareas/T03/ejemplos%20(programada)/precomp.asm), donde se indica el numero de línea con ":\n"?
También los códigos máquina serán como los del enunciado (separados por ";")?

Gracias

**Comment by Arcoirisky** [comment]
Todo input/output debe ser como el enunciado.

Y los “;” designan comentarios O: esos solo es “basura” para tu programa.

**Comment by fgbruna** [comment]
Es decir para  el output del assembler no basta con tener los números como en [binario.asm](https://github.com/IIC2343/syllabus/blob/master/Tareas/T03/ejemplos%20(programada)/binario.asm) , es necesario poner "0o" y los ceros necesarios?

**Comment by emontecinos** [comment]
Entonces los ejemplos que subieron (por ejemplo [precomp](https://github.com/IIC2343/syllabus/blob/master/Tareas/T03/ejemplos%20(programada)/precomp.asm)) no es real, porque en el enunciado no tenemos los números de línea?

**Comment by Arcoirisky** [comment]
@fgbruna Si u-u Para que todos sean iguales 

@emontecinos esos archivos sólo están para ejemplificar lo que hace su programa entre outputs, se ha respondido lo mismo en otras Issues. Podrías echarle un vistazo si algo no te queda claro :D

**Comment by emontecinos** [comment]
Gracias
