### ISSUE TITLE
Uso Operaciones Aritméticas en Stack Pointer

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2343/syllabus#128]
Hola,
En el Stack Pointer del computador básico que nos entregaron se usa la suma y la resta para cambiar el valor de la dirección de memoria en la RAM (sp + 1, sp - 1). 
¿La operacion de sumarle 1 o restarle 1 al stack pointer se puede hacer directamente, o se debe hacer con algún componente?

**Comment by jheysen** [comment]
Eso forma parte de tu diseño

**Comment by pdesolminihac** [comment]
Ok Gracias

**Comment by mvcavieres** [comment]
Pero en el reg no aparece que use otro componente para sumar o restar, sino que en reg igual usan operaciones aritméticas.

**Comment by Geeermy** [comment]
@mvcavieres Como dice el enunciado: "tienen a disposición componentes que se encargan de esto". No usas aritmética directamente, haces uso del componente que te damos.

**Comment by cilopez** [comment]
@Geeermy ¿Tenemos también que editar la suma en el program counter o solo en el SP?

**Comment by Geeermy** [comment]
@cilopez ¿Cuándo dije que tenían que editar la suma en el ```SP```? Dije que tenían el componente ```Reg``` a disposición que tiene todos los elementos para poder manipular su valor. Da lo mismo si dentro del componente se usan operaciones aritméticas, nosotros se la estamos dando, ustedes la usan no más. Con el ```PC``` es lo mismo.

**Comment by pdesolminihac** [comment]
@Geeermy , entonces también podemos hacer uso del Stack Pointer que nos entregan como componente?

**Comment by jheysen** [comment]
Si
