### ISSUE TITLE
[TAREA 3- PROGRAMADA] bin

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#129]
Hola!
Puedo usar bin para hacer operaciones  de binarios? Y puedo pasar de octales a binarios para luego calcular el valor de un numero (Esto es ya que se me hace mas facil para calcular el valor de un numero negativo) Gracias!

**Comment by Arcoirisky** [comment]
Hola!
Solo para las operaciones que no son sumar/restar.

Queremos que aprendan a usar otras bases O: (y el octal es una de ellas uwu)

**Comment by chocopiano** [comment]
Yo lo que estaba haciendo hasta este minuto para sumar y restar era por ejemplo si tenia MOV Ax, LIT...pasaba el lit de octal a decimal y luego lo sumaba....Por lo que dices entonces esto estaria mal?

**Comment by Arcoirisky** [comment]
Básicamente, si. 
La idea es que usen el complemento a ocho.

**Comment by chocopiano** [comment]
Y para los J'ALGO', para ver el overflow o carry puedo usar binario o tambien es con complemento de 8?

**Comment by chocopiano** [comment]
Volviendo a lo de la suma y resta, se que la idea es usar complemento de 8 pero en el enunciado no se señala que no se puede sumar en decimales, y ya esa parte la hice sumando con decimales y no quiero tener que repetir el proceso nuevamente...

**Comment by Arcoirisky** [comment]
El complemento a n se utiliza para sumar y restar números enteros. Además, se menciona que se considerará inválido el no usarlo. 

Aprovecha estos dos días extras :D tienen tiempo para arreglarlo :D

**Comment by Arcoirisky** [comment]
J’algo’ Es direccionamiento, al ya haber hecho sumas y restas deberías de poder ir manejando los registros sin problemas :D
