### ISSUE TITLE
Memoria Tarjeta y Registros

### ISSUE THREAD

**Issue by dalliende** [IIC2343/syllabus#129]
Estimados, tenemos un problema no sabemos como dejar guardado el programa .bit en la memoria de la tarjeta, por lo que si apagamos la tarjeta tenemos que volver a cargar el programa. Y el segundo problema que tenemos es que al momento de apretar el botón para que se sume 1 al registro, nos varia en una cantidad muy superior, no sabemos si es porque al momento de tener apretado el botón el clock este  sube muchas veces, o simplemente porque funciona mal el registro.  Saludos.

**Comment by Hernan4444** [comment]
@dalliende lo primero no es un problema, es algo típico de la placa. Lo segundo es porque tienes el clock en velocidad full. Tienes que ir al archivo basys3 y buscar la instancia del clock donde dice que "00" es la velocidad full y cambiarla por velocidad normal.

**Comment by dalliende** [comment]
Ya hicimos eso tenemos el clock en velocidad normal "10". que mas podria ser?

**Comment by Hernan4444** [comment]
@dalliende necesitaré que suban su código actualizado para buscar que puede ser.

**Comment by dalliende** [comment]
Esta actualizado en el repositorio del grupo, somos grupo 8

**Comment by Hernan4444** [comment]
@dalliende a los registros deben entregarle el `clock` que es el `clk` reducido a la velocidad normal 😅

**Comment by dalliende** [comment]
Y con respecto a lo de la memoria, cual es la mejor forma para tener el programa "a mano" para la entrega?

**Comment by Hernan4444** [comment]
@dalliende tienen que llevar el pc y cargar el .bit en ese momento

**Comment by dalliende** [comment]
Ok, gracias por todo
