### ISSUE TITLE
Tarea 3 | Pregunta 1.1 | nro_clock y nro_clock_instruccion

### ISSUE THREAD

**Issue by figarcia3** [IIC2343/Syllabus#129]
Hola! No entiendo la diferencia entre el nro_clock y el nro_clock_instruccion.

**Comment by jmwielandt** [comment]
Lo cambié por "nro_clock_1" y "nro_clock_2". La instrucción cuyo número de clock es `nro_clock_1` tiene problemas con la instrucción cuyo número de clock es `nro_clock_2`.

**Comment by Jaluco** [comment]
osea que ese "nro_clock_2" es una instruccion anterior donde se origino el hazard?

**Comment by jmwielandt** [comment]
> osea que ese "nro_clock_2" es una instruccion anterior donde se origino el hazard?

sí
