### ISSUE TITLE
Ayuda P5 (floats)

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/Syllabus#13]
Hola, 

Les dejo el link a un conversor de punto flotante que sigue la convención IEEE754. Si usan el botón "+1" podrán ver algunos casos del sucesor que les pedimos y el "-1" el antecesor. 

No es totalmente lo que pedimos, por ejemplo, si están en 0.0 y hacen click en "-1" verán que en vez de salirles "-0.0" les sale "NaN", pero si están en 0.0 y hacen click en "+1" sí funciona.

**Como hint: revisen los casos con signo y los sin signo de forma independiente.**

Mucho éxito!

https://www.h-schmidt.net/FloatConverter/IEEE754.html

**Comment by mathiasvaldebenito** [comment]
Creo que existe un problema con los outputs de los test case, algunos tienen saltos de línea entre antecesor y sucesor mientras que otros tienen un espacio entre ellos. Por favor corrijanme de no ser asi.

**Comment by mathiasvaldebenito** [comment]
Creo que existe un problema con los outputs de los test case, algunos tienen saltos de línea entre antecesor y sucesor mientras que otros tienen un espacio entre ellos. Por favor corrijanme de no ser asi.

**Comment by jmwielandt** [comment]
Hola, acabamos de revisar los test cases y todos tienen salto de línea entre antecesor y sucesor
¿Qué te hace sospechar eso?

**Comment by mathiasvaldebenito** [comment]
Cuando hago el print con salto de linea tengo buenos los test case 3 y 4, pero cuando lo hago con espacio tengo buenos los 1 y 4

**Comment by ceosorio** [comment]
Hola @mathiasvaldebenito !

Es bastante extraño, pero para asegurarnos edité los outputs y les puse manualmente todos los saltos de linea de nuevo. Ahora todos debiesen estar solo con saltos de linea entre cada numero 😄

Si sigues teniendo problemas, no dudes en decirnos :)

**Comment by viantirreau** [comment]
Hola! 
¿En los casos especiales de +0 y -0 cómo debemos ponerlos en output?
-0.000000000000000000000000000000000000...
+0.000000000000000000000000000000000000...

O simplemente
-0
+0

Gracias desde ya!

**Comment by jmwielandt** [comment]
@viantirreau Siempre deben imprimirlos con la cantidad de decimales que pedimos. Printf tiene una forma de hacerlo muy fácil ;D

**Comment by viantirreau** [comment]
Ah ya bacán!
Muchas gracias @jmwielandt :raised_hands:

**Comment by viantirreau** [comment]
¿Debemos preocuparnos por que nos pasen un número cuyo sucesor sea +inf o su antecesor sea -inf?
Si es así, ¿cómo deberíamos imprimirlos?

Gracias!!

**Comment by jmwielandt** [comment]
Lo acabo de responder en #15 pero es tal y como dices, no es una preocupación ;D
