### ISSUE TITLE
[T01 PROG] Compuertas nand y nor en circuitos originales

### ISSUE THREAD

**Issue by Sforrego** [IIC2343/syllabus#13]
Los circuitos originales van a venir con las compuertas and or not y xor solamente, o pueden incluir nands y nors?

**Comment by ariel-m-s** [comment]
Hola! Te sugiero leer con mejor detención el enunciado de la tarea porque eso está explicitado ahí mismo. Los circuitos vendrán con AND, OR, NOT y XOR y no incluirán ni NAND ni NOR.

Saludos.

**Comment by Sforrego** [comment]
oops toda la razon!

**Comment by Arcoirisky** [comment]
Hola! No cierres las issues por favor :D alguien podría tener la misma duda que tu
