### ISSUE TITLE
[Ayudantía] - Duda

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2343/Syllabus#13]
Hola! quería saber cuál será el tema a tratar en la ayudantía de mañana lunes 19 de agosto

Saludos!! 😸

**Comment by jjaguillon** [comment]
Hola.

Veremos varias cosas:

- El enunciado de la entrega 1a en detalle y resolveremos dudas.
- Circuitos en draw.io.
- Simulación en Vivado.

**Comment by VicenteVicente** [comment]
Muchas gracias!!
