### ISSUE TITLE
Tarea 1 Parte 2 - Al menos un nodo

### ISSUE THREAD

**Issue by caespinoza5** [IIC2343/syllabus#13]
La variable "camino" comienza con 0, sin embargo, el camino más largo siempre estará compuesto por al menos un nodo (camino = 1). Lo anterior siempre y cuando el grafo cumpla con que posea nodos. ¿Podemos asumir que todos los grafos que se nos entregarán tienen al menos un nodo ("matriz" no vacía)?

**Comment by Hernan4444** [comment]
@caespinoza5 si puedes asumir eso.

Saludo ✌️
