### ISSUE TITLE
[TAREA 3-PROGRAMADA] Casos Bordes.

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#130]
Hola nuevamente!
Quería saber que pasa cuando ocurren casos bordes, es decir cuando hay un Add Ax, Lit o Sub Bx, Lit  y por ejemplo por ser 2 numeros positivos sumando pasan a ser "negativos" o "cuando son dos numeros negativos sumando hacen overflow"? Por ejemplo si sumamos 3777+0002 pasa a ser de una suma de 2 positivos a un negativo (4001)y si hacemos la suma de 2 negativos 7777+7777 pasa a ser 17776. Entonces mi pregunta es: como los guardo por ejemplo en el Ax, porqueq como son de 12 bits no podria guardar 17776 o en el primer caso no deberia guardar un negativo. Espero se entienda mi duda y que puedan ayudarme. Gracias!

**Comment by tomasrivera** [comment]
Hola, lo que mencionas no es un caso borde, ya que esto está presente en la operatoria normal del computador de la tarea y de uno en general.

¿A qué me refiero?, volvamos un poco a un sumador/restador a nivel de circuito lógico. Y aquí hay varios casos que pueden ocurrir:

Voy a ejemplificar con 4 bits en **binario**.

- Suma de números negativos sin _overflow_, acá al sumar por ejemplo `1110 + 1101`. El resultado es el siguiente, `1011` y se obtiene _carry_, pero el número resultante sigue siendo negativo, por lo que no ocurre _overflow_ y el _carry_ no tiene importancia.

- Suma de números negativos con _overflow_, acá al sumar por ejemplo `1010 + 1011`. El resultado es el siguiente, `0101` y se obtiene _carry_, pero el número resultante es positivo, por lo que ahora si ocurre _overflow_.

Para los números positivos es básicamente lo mismo.

Ahora, para ir respondiendo tu pregunta, los **registros** tienen un tamaño fijo pero los resultados de las operaciones no. Esto hace que en ocasiones el resultado que se obtiene no sea el valor real de la operación (casos de overflow).

**Comment by chocopiano** [comment]
Esa es mi pregunta, entonces dejo el resultado según el tamaño fijo y no el valor real?

**Comment by Arcoirisky** [comment]
Sip, de todas formas existen señales que controlan estos casos y ya es cosa de quién "programó" el programa si le afecta o no u0u
