### ISSUE TITLE
Tope Stack [Programación]

### ISSUE THREAD

**Issue by dmolina2** [IIC2343/syllabus#130]
Tengo una duda a que hacer cuando ocurra el siguiente caso:
Estamos en la posición 255 del stack y se aplica una operación "ADD" por ejemplo. Entonces, lo que ocurriría en primera instancia es que la señal Spadd = 1, lo que me provoca confusión donde guardar el valor de la suma, porque este es el "tope" del stack.
Leí en una issue que podríamos asumir el stack como circular, lo que produciría que guardemos el valor de la suma en la posición 0 del stack, pero no me hace sentido.
¿Podrían aclarar un poco que hacer en estos casos?

**Comment by FranLucchini** [comment]
Hola,

Esto es un supuesto que pueden hacer. Nosotros no vamos a evaluar el caso en el que se llene el stack. Puedes manejar el caso como prefieras para no sentir confusión.
