### ISSUE TITLE
Tarea 2 | Pregunta 3 | Largo de caracteres ISO/IEC

### ISSUE THREAD

**Issue by bpardobravo** [IIC2343/Syllabus#130]
Hola, hay alguna manera de ver las razones por las cuáles están buenos/malos los statements de las preguntas 1 y 3 de la tarea 2?

En particular demás tengo la duda con la del largo de los caracteres ISO, porque en internet pillé que son "variable length" y según tarea no.
![Inkedevidencedotzip1](https://user-images.githubusercontent.com/48322933/85190515-2471fa80-b287-11ea-8b9b-1606c37ff1d9.jpg)

![evidencedotzip2](https://user-images.githubusercontent.com/48322933/85190487-ebd22100-b286-11ea-99db-b9a7258c7acd.png)
*Sacados de wikipedia y la página de IBM respectivamente

**Comment by quememo** [comment]
Yo también había encontrado eso, en particular, que UCS-2 utiliza 2 bytes para representar el carácter y UCS-4 utiliza 4 bytes, indicado por el estándar ISO/IEC 10646:

![image](https://user-images.githubusercontent.com/48305214/85214144-6bb6c480-b335-11ea-97cd-43715ecc0cfb.png)

Como también que algunos estándar usaban 7 bits y otros 8:

![image](https://user-images.githubusercontent.com/48305214/85214188-f0094780-b335-11ea-8fd2-105b313f365c.png)
Fuentes:
- https://es.wikipedia.org/wiki/ISO/IEC_10646
- https://en.wikipedia.org/wiki/Universal_Coded_Character_Set
- https://en.wikipedia.org/wiki/ISO/IEC_JTC_1/SC_2
