### ISSUE TITLE
[Tarea 3 - Programada] Complemento base 8

### ISSUE THREAD

**Issue by seba608** [IIC2343/syllabus#131]
Hola,

No estoy seguro si entiendo cómo se debe hacer la conversión al complemento de 8, pero según lo que entiendo el mayo número positivo sería 6777 y el mayor número negativo sería 7777. Estoy equivocado?

Gracias!

**Comment by Arcoirisky** [comment]
Revisa bien tu comentario, porque 6777 te deja con muy pocos negativos.

**Comment by seba608** [comment]
Entonces del 0 al 3777 son positivos y del 4000 al 7777 negativos? Es que en la issue #114 preguntaron eso y no le respondieron si estaba en lo correcto

**Comment by jmwielandt** [comment]
Contestar eso sería darte la respuesta a algo que queremos que piensen ~~y busquen en google~~ ustedes mismos.
