### ISSUE TITLE
suma de positivo con negativo, parte 2 tarea

### ISSUE THREAD

**Issue by bedefrunner** [IIC2343/syllabus#131]
Hola! En la parte 2 de la tarea, si me entregan 1 + -2 lo considero como una suma (porque el signo es +) o como una resta? Si lo considero como suma, en estricto rigor no debiera activarse la señal n porque esta solo se activa **cuando es resta y con A<B** . Por enunciado, resta se define como "operador con signo -", y en este caso mi operador es signo +, ademas, en este caso A>B. 
Si lo considero como resta, entonces debiera activarse dado que el resultado es -1 en este ejemplo. 
La misma pregunta aplica para -1 + -2.

**Comment by Hernan4444** [comment]
@bedefrunner no haremos `1 + -2 `  solo será `1 - 2` .Y no pondemos un número negativo en el primer elemento: ` -1 + -2` solo serán enteros positivos y en el medio tendrán una operacion de las definidas.

Saludos

**Comment by bedefrunner** [comment]
perfecto, gracias!
