### ISSUE TITLE
Tarea 3 | Pregunta Recuperativa | Redondeo

### ISSUE THREAD

**Issue by mfortiz** [IIC2343/Syllabus#131]
Hola,
Tengo una duda. ¿El redondeo no debería ser en cada compra?
Estaba viendo el ejemplo y lo que se hace es redondear la suma de todas las compras.

![image](https://user-images.githubusercontent.com/37163461/85207274-a6990800-b2f5-11ea-8308-359fee618414.png)

Muchas gracias.

**Comment by jmwielandt** [comment]
Hola,

Es redondear al final de todo. ~~(Así es como lo hacen los supermercados.)~~

Saludos!

**Comment by mfortiz** [comment]
Si, pero lo que me refiero es que no tiene sentido redondear la suma de TODAS las compras. 
Sino que lo correcto sería redondear la suma de CADA compra. 
🤔

**Comment by jmwielandt** [comment]
Ahhh ya. No te preocupes por eso, ya lo tenemos de esa forma y lo vamos a mantener.
