### ISSUE TITLE
[T3- placa] Error compilandor

### ISSUE THREAD

**Issue by CmPoblete** [IIC2343/syllabus#132]
Hola, saben por que cuando compilo mi programa, me tira un error cuando agrego las 4 lineas para el display, pero si las comento me compila bien?

**Comment by Arcoirisky** [comment]
Sin el error no podríamos decirte mucho, la verdad :c

**Comment by CmPoblete** [comment]
![image](https://user-images.githubusercontent.com/37149937/57552531-2eae8f00-733a-11e9-8f1a-dc823140f0fe.png)

Ese es el error

**Comment by danyestay** [comment]
A mí y otras personas también nos tira el mismo error de Combinatorial Loop :'(

**Comment by frvalenzuela** [comment]
Hola @danyestay y @CmPoblete !

Favor revisar #144 , si queda alguna duda favor hacerlo saber.

Saludos!
