### ISSUE TITLE
Duda display 

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2343/syllabus#132]
Hola! No podemos lograr que se muestre el resultado de la operación al apretar el boton de al medio, intentamos haciendo otro archivo vhd display_resultado que funcionara con el clock y un if, que hiciera que al apretar el boton del centro los display cambiaran. Pero no nos resulto :(
Algun hint?

Saludos!

**Comment by Hernan4444** [comment]
Hint: Multiplexor para cada display (4 multiplexores)
Saludos y animo 👍

**Comment by BenjaPrograma** [comment]
esto fue lo que pusimos en el modulo display_resultado

with boton select
    display_a <= result(15 downto 12) when '1',
    operandoA(7 downto 4) when others;

with boton select
    display_b <= result(11 downto 8) when '1',
    operandoA(3 downto 0) when others;

with boton select
    display_c <= result(7 downto 4) when '1',
    operandoB(7 downto 4) when others;

with boton select
    display_d <= result(3 downto 0) when '1',
    operandoB(3 downto 0) when others;

pero nos tira un error horrible, y sacamos eso y no nos tira ningun error, entonces sabemos que la falla esta ahi.

**Comment by Hernan4444** [comment]
@BenjaPrograma puedes indicarmecuales el error?

**Comment by BenjaPrograma** [comment]
[DRC MDRV-1] Multiple Driver Nets: Net inst_regA/reg_reg[3]_0 has multiple drivers: inst_regA/reg[0]_i_7__0/O, and inst_regA/reg_reg[0]/Q.

**Comment by Hernan4444** [comment]
puedes subir tu código (e indicar grupo)

**Comment by BenjaPrograma** [comment]
somos grupo 13, ahi lo subimos a la repo en carpeta "modificaciones placa"

**Comment by Hernan4444** [comment]
@BenjaPrograma si lo que subiste es loque intentaste compilar, el error es que en tu mux le estás dando un valor pero en la basys3 linea 111 a 114 le dás otro valor a los display. Una señal no puedo recibir dos valores distintos al mismo tiempo

**Comment by BenjaPrograma** [comment]
Gracias Hernan, era eso jajaja.
