### ISSUE TITLE
Duda restriccion en parte practica

### ISSUE THREAD

**Issue by Dunkan1** [IIC2343/syllabus#132]
Hola, estaba haciendo la tarea con mi compañero y ocurre que no entendemos a que se refiere esta parte de la tarea
![imagen](https://user-images.githubusercontent.com/26102365/45913378-a2317980-be07-11e8-9bf8-a918fb842340.png)

se refiere a que para implementar una instruccion no debemos usar otras, o no?

**Comment by Arcoirisky** [comment]
Yo la había entendido como "cualquier instrucción que no esté en esa ISA, es Nop" (porque la idea es que la ISA sea la ley de tu computador. Si pudiera hacer instrucciones que no son parte de la ISA, sería terrible!!!)

**Comment by LuisFros** [comment]
Hola! Tengo un duda respecto a buenas practicas respecto al manejo de estos casos,
Si tengo una condicion para los casos que no son parte de la ISA, que señal debo entregarle?
He encontrado que si tengo un bus de 3 bits seria "---", donde "-" significa "no me importa" . Esto es porque me veo obligado a entregarle algo en esos casos. 
Esto fue por investigacion propia y quisiera saber si no es peligroso usar ese tipo de señal para Xilinx.

**Comment by jheysen** [comment]
Lo mejor sería entregarle una operación que sepas que es segura, en general usar cosas como "-" en las señales no es buena idea salvo que sepas que la electrónica después puede manejarlo
