### ISSUE TITLE
Tarea 3| Pregunta 1.1 | Duda Set de Instrucciones

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2343/Syllabus#132]
Hola,
Tengo una duda sobre qué instrucciones nos pueden pasar. Consideramos el set de instrucciones completo del computador básico?
Gracias :)

**Comment by ceosorio** [comment]
Hola @kelseyfranken!

Efectivamente, consideren el set de instrucciones completo del computador básico.

Saludos y éxito en la tarea ✨

**Comment by Cadagan** [comment]
Hola! estaba probando el "input_parser" y aparentemente se cae al poner instrucciones de 4 letras (como CALL o PUSH), ¿podemos asumir que no estarán estas instrucciones? ¿no habrán subrutinas en los txt con los que evaluaran las tareas?

Saludos y gracias de antemano 😁

**Comment by jmwielandt** [comment]
A mí no se me cae con CALL 🤔
Usé este código:

```
DATA:
CODE:
JMP main
aaab:
RET
main:
CALL aaab
```

Que generó este input para el programa:

```
6
 N° | PC    Instrucción [RegA|RegB]
----------------------------------
0001|0000   JMP 3      [0000|0000]
0002|0003   CALL 1     [0000|0000]
0003|0001   // SP++    [0000|0000]
0004|0002   RET        [0000|0000]
```

Mira de todas formas el código que puse en la issue #123 . Básicamente así es como me imagino que deberían estar procesando los inputs.

Manda de todas formas el código con el que se te cae para ver qué puede estar pasando.
