### ISSUE TITLE
[T3-Programada][simulador]

### ISSUE THREAD

**Issue by jnpoblete** [IIC2343/syllabus#133]
Hola!!, tengo una duda con el simulador, especificamente con el ejemplo del enunciado. En la linea donde PC = 0o0003 el valor del literal es 0o0022, pero tengo la duda si esto esta bien. Creo que deberia ser 0o0021 debido a que el opcode 0o0040 tiene a [resultado] y no a [cont], o no?

Saludos!!

**Comment by Arcoirisky** [comment]
Hola!

Si te das cuenta, ningún literal calza. En las primeras semanas de la tarea se encontró un error en las direcciones de los literales y al parecer se nos pasó arreglar la parte de la simulación al editar el opcode del assembler.

La respuesta debería ser:

---PC---|----SP---|----BP---|----Op----|----Lit----|----Ax----|----Bx----|
0o0000, 0o0000, 0o0000, 0o0036, 0o0036, 0o0000, 0o0000
0o0001, 0o0000, 0o0000, 0o0037, 0o0034, 0o0000, 0o0000
0o0002, 0o0000, 0o0000, 0o0005, 0o0000, 0o0000, 0o0003
0o0003, 0o0000, 0o0000, 0o0040, 0o0036, 0o0003, 0o0003
0o0004, 0o0000, 0o0000, 0o0036, 0o0037, 0o0003, 0o0003

**Comment by tgarcia5** [comment]
Hola, el Program Counter no debería estar avanzando de dos en dos, haciendo primero el ciclo para el opcode y el segundo ciclo para el literal?

Y el ejemplo anterior quedaría así ?
---PC---|----SP---|----BP---|----Op----|----Lit----|----Ax----|----Bx----|
0o0000, 0o0000, 0o0000, 0o0036, 0o0036, 0o0000, 0o0000
0o0002, 0o0000, 0o0000, 0o0037, 0o0034, 0o0000, 0o0000
0o0004, 0o0000, 0o0000, 0o0005, 0o0000, 0o0000, 0o0003
0o0006, 0o0000, 0o0000, 0o0040, 0o0036, 0o0003, 0o0003
0o0008, 0o0000, 0o0000, 0o0036, 0o0037, 0o0003, 0o0003

**Comment by Arcoirisky** [comment]
Pues, sí (lo confundí con un clock skndkskd mala mía) 
Hasta que llegue a las variables 🤔 luego sería de 1 en 1

Pero es como dice @tgarcia xD 
Sino la salida de la simulación sería más larga.

**Comment by leolivares** [comment]
@Arcoirisky 
Cuando llega a las variables, el valor de la variable se escribe en el espacio de opcode o de lit?
