### ISSUE TITLE
Duda de Error "Black Box"

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2343/syllabus#133]
Hola! Tenemos un error al compilar. Nos pasó después de hacer la ALU y definir las multiples operaciones en esta y en el modulo basys.

[DRC INBB-3] Black Box Instances: Cell 'inst_ALU/inst_XOR' of type 'inst_ALU/inst_XOR/XOR1' has undefined contents and is considered a black box.  The contents of this cell must be defined for opt_design to complete successfully.

Los archivos estan subidos en la repo (grupo 13).

Saludos!

**Comment by lileiva** [comment]
estoy revisando su codigo por ahora tienen que arreglar su alu, en la linea 25 tienen 
ins_FA: FA port map(a,b,c)
les falta definir las signals a las que van a b y c
algo asi como 
ins_FA: FA port map(a => x,b => y,c => z);
