### ISSUE TITLE
Tarea 3 | Pregunta 1.1 pipeline | Qué incluir como conflicto

### ISSUE THREAD

**Issue by mfocqueteau** [IIC2343/Syllabus#133]
Hola, para explicar más claro mi duda tengo este ejemplo:
MOV A, Lit
MOV B, A
MOV (Dir), A

Es claro que la segunda línea entra en conflicto con la primera, pero ¿debería incluir la tercera con la primera como otro conflicto más? ¿O puedo ingorar el segundo conflicto ya que desaparece junto con la solución del primero?

**Comment by jmwielandt** [comment]
Si te enfrentas con múltiples hazards de control, imprímelos en líneas separadas. El orden en estos casos no importa.

Si resolver un hazard te evita otro, no pongas el segundo porque no es un hazard que ocurra realmente. Ten cuidado a la hora de ver si efectivamente te lo resuelve o no.
