### ISSUE TITLE
Acceso Repo Grupo

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2343/syllabus#134]
Holaa, soy miembro del grupo 15, contesté el form respectivo hace tiempo pero aún no tengo acceso al repositorio del grupo.

**Comment by B-Dominguez** [comment]
Ahí me llegó la invitación, gracias!

**Comment by lfbesa** [comment]
Yo soy del grupo 18 y tampoco me dieron acceso, y también contesté el formulario.
Muchas gracias

**Comment by Hernan4444** [comment]
Todo aquel que no tenga acceso que conteste esta issue ✌️

**Comment by joaquincastillo** [comment]
Yo no tengo acceso!, grupo 14

**Comment by sebawarrior** [comment]
Hola yo no tengo acceso al repo del grupo! (grupo 2)

**Comment by bedefrunner** [comment]
Tampoco tengo acceso, grupo 2.
