### ISSUE TITLE
Tarea 3 | Pregunta 1.2 | Especulación Jump Condicionales

### ISSUE THREAD

**Issue by cjones27** [IIC2343/Syllabus#134]
Hola! 

Quisiera saber cómo debemos tomar los jumps condicionales. En el enunciado se explica cómo debe saltar el jump incondicional especulativamente. En el jump condicional debemos asumir que salta especulativamente o que no salta especulativamente? O tomamos que para los condicionales especula igual que para el incondicional?

Gracias de antemano

**Comment by jmwielandt** [comment]
Los jumps incondicionales siempre saltan, no hay ejecución especulativa (no hay nada que especular) y por tanto no hay hazards de control.

Para el caso de los jumps **condicionales**, debes asumir que siempre se equivoca.

**Comment by nbnavarro** [comment]
Hola @jmwielandt, creo que habíamos visto en clases que al momento de toparnos con un jmp condicional, podíamos tomar la decisión de "no saltar" o la decisión de "saltar" y que, en base a esa decisión, en ocasiones nos equivocaríamos y haríamos flush. 
Entonces, mi duda es ¿A qué te refieres cuando dices que "siempre se equivoca"? Siento que no es ninguna de las dos decisiones anteriores.

Gracias de antemano

**Comment by ceosorio** [comment]
Hola @nbnavarro!

Nos referimos a que la predicción que se haga para los saltos condicionales **siempre** estará mal. 
Es decir, si ocurre el salto, tu predicción fue que no ibas a saltar, y viceversa.
Espero que con eso se entienda mejor :3

saludos :sparkles:
