### ISSUE TITLE
Tarea 1 - puntajes de hackerrank vacios

### ISSUE THREAD

**Issue by Jaluco** [IIC2343/Syllabus#135]
Hola, en mi resumen de notas en hackerrank tengo todo vacio pero el usuario esta correcto y re-revise y estan mis programas arriba, ¿que hago?

**Comment by Jaluco** [comment]
![image](https://user-images.githubusercontent.com/17888126/85213176-cac20c80-b328-11ea-8391-4c66ec7db90e.png)

**Comment by Jaluco** [comment]
Revise commits anteriores y antes si tenia notas registradas

**Comment by jmwielandt** [comment]
Hola,

Tú eras uno de los que me tenía que escribir, como pedí en el anuncio.

Si todavía no tienes los puntajes, la próxima vez que cargue la planilla deberían aparecer.
