### ISSUE TITLE
[T03 - PROG] Base de los literales

### ISSUE THREAD

**Issue by Conjo1** [IIC2343/syllabus#135]
Hola!  

Solo para asegurarme: los literales en assembly estarán en base 10?

Por ejemplo, en ```MOV Ax, 10```  
```10``` representa un 10 y no un 8, cierto?

**Comment by Arcoirisky** [comment]
En ocho :O

**Comment by leolivares** [comment]
@Arcoirisky 
Hola! No debería ser en decimal? 
En el ejemplo del enunciado cuando se utiliza la instrucción ADD Ax, 1 lo toma como decimal me parece, ya que es un contador.

**Comment by Arcoirisky** [comment]
¿Qué sentido tendría hacer un computador base ocho si se escribe en base 10? 😱

Bueno, quizás se nos pasó. El assembly será en base 10 :D 

Disculpen el mal entendido u-u)
