### ISSUE TITLE
[BONUS] Calculo de desfase de exponente

### ISSUE THREAD

**Issue by egromero** [IIC2343/syllabus#135]
Hola, tenemos una duda para el calculo del exponente en el bonus, el desfase no sería 127 ni 1023 para esta parte verdad? sino va a depender del numero de bit que se ingrese en el input para el exponente? 

Esto, ya que encontramos una relación de calculo de desfase que es consistente en 8 y 11 bits, y podríamos usarla como función para cualquier numero de bits de exponente.

Gracias! 
Saludos,

**Comment by Hernan4444** [comment]
@egromero queda a tu criterio.
Saludos
