### ISSUE TITLE
Tarea 3 | Pregunta 1.2 | apartado de consideraciones

### ISSUE THREAD

**Issue by Cadagan** [IIC2343/Syllabus#136]
Espero que se encuentren bien, aquí un par de dudas que necesito aclarar de la de Pipeline II :

* ¿Podemos asumir que solo habrán hazards de control en esta y no hazards ni de datos ni estructurales?
* ¿A qué se refiere con "_solo están presentes los ciclos no borrados al hacer flush_"? ¿se refiere a que al "ejecutar" las instrucciones, si una instrucción fue descartada con flush, no contaria si fuese un JMP condicional por ejemplo para el conteo de hazards?
* Dice que "_El contador de hazards aumenta siempre que haya un salto condicional_", entonces **siempre** se cumplirán las condiciones de un JMP condicional para ejecutar ese JMP? ¿Qué pasa si es un JMP hacia atrás en las instrucciones? podríamos caer en un loop infinito, ¿Qué debiésemos contestar en ese entonces? ¿o podemos asumir que siempre serán hacia adelante?

Muchas gracias de antemano :grin:

**Comment by jmwielandt** [comment]
* Sí.
* Lo reescribí como "Se omitieron los ciclos borrados al hacer _flush_. Esas instrucciones no aparecen.
* No puedes asumir eso, pero está también la restricción de que no se encontraron hazards de control anidados así que no es algo que deba preocuparte.

**Comment by Cadagan** [comment]
Perdon @jmwielandt , pero con lo de "no puedes asumir eso" te refieres a que no puedo asumir que "_siempre se cumplirán las condiciones de un JMP condicional para ejecutar ese JMP_" o a que no puedo asumir que "_(...) que siempre serán hacia adelante_"?

No me quedó claro entonces esa parte, en especifico lo de que "_la ejecución
especulativa siempre se equivoca_", eso quiere decir que cada vez que nos topemos con un JUMP condicional, se pierden 3 instrucciones? o a que la condicion, cuando es False, en lugar de no saltar, salta y podria perder más de 3 instrucciones

**Comment by jmwielandt** [comment]
> Perdon @jmwielandt , pero con lo de "no puedes asumir eso" te refieres a que no puedo asumir que "_siempre se cumplirán las condiciones de un JMP condicional para ejecutar ese JMP_" o a que no puedo asumir que "_(...) que siempre serán hacia adelante_"?

No puedes asumir que siempre serán hacia adelante.

> No me quedó claro entonces esa parte, en especifico lo de que "_la ejecución especulativa siempre se equivoca_", eso quiere decir que cada vez que nos topemos con un JUMP condicional, se pierden 3 instrucciones? o a que la condicion, cuando es False, en lugar de no saltar, salta y podria perder más de 3 instrucciones

Cada vez que se topen con un jump condicional pierden 3 instrucciones.
