### ISSUE TITLE
[T3-Placa] Testear entidades

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2343/syllabus#136]
Ya hemos implementado la gran mayoría de las cosas pedidas (faltan un par de instrucciones) pero no logramos testear ninguna instrucción... La memoria se lee muchas veces, al inicio se nos asigna la instrucción a un registro y pasan muchas cosas raras a medida que se va leyendo. Hemos buscado errores de circuito, de implementaciones, de todo en verdad y no logramos ver en que fallamos. Lo único que logramos es que si ponemos solo una instrucción con un literal, se ejecuta medianamente bien (se entiende que es lo que está pasando en la placa) pero más que eso no hemos podido probar. 
Esta issue es para saber si algún otro grupo logró testear de manera correcta su placa y en ese caso nosotros tenemos algún error o simplemente hay algo que escapa de nuestro alcance y las entidades entregadas (quizás) no cumplen con sus labores. Me quedan muchas dudas del funcionamiento del ciclo y demases pero no es algo de lo que nos debiesemos preocupar se supone. 
De antemano muchas gracias, éxito a todos!!

**Comment by Arcoirisky** [comment]
Oh nooo, de todas formas, cuidado con que no puedan probar todas las instrucciones. Deberían tener problemas con aquellas en las que se necesitan más de dos ciclos en ejecutar. Pero el resto no debería de causarles problemas.

¿Cómo tienen conectadas sus instancias de componentes?

**Comment by FelipeCampbell** [comment]
Las tenemos conectadas en basis en mediante señales. Pero por ejemplo uno de los problemas que pasa es que si la primera línea de la main memory es un opcode que activa el registro A, entonces la instrucción pasa directo al registro A.
Por ejemplo al hacer: Ax = Lit,ponemos en main memory el opcode de la instrucción en la primera linea y en la segunda ponemos un literal. Luego nuestra placa primero pone el opcode en el registro A (supongo que ya liberó las señales de control que ese opcode mismo representa lo que produce que se active el registro A, se ponga 0 en mux_out A, y el valor que viene de memoria en mux_out b y luego se suman. esto produce que el opcode quede en el registro a). Después en una segunda instancia se aplica la instrucción del opcode anterior y se toma el valor que viene de memoria (el literal) y se pone en el registro A. 
Lo anterior me muestra que las señales de control se están liberando en el primer y segundo ciclo en vez de solo en el primer ciclo. ( Sí tenemos conectada la señal stalling tb). 
Además si añado más lineas pasan cosas raras como que líneas se leen dos veces y cosas de ese estilo ( por ejemplo primero como literal y después como opcode). Esto hace muy difícil el que probemos nuestras instrucciones

**Comment by Arcoirisky** [comment]
Por lo que estoy entendiendo, les hace falta manejar las instrucciones según la indicación del clock. Por lo que lee como señal todo lo que le llega 🤔 

Quizás es la CU la que les está metiendo el problema para interactuar con las instrucciones más básicas.

**Comment by FelipeCampbell** [comment]
No debería hacerse cargo el register cu de eso?

**Comment by FelipeCampbell** [comment]
Nuestra Cu lo único que hace es tomar como input lo que sale del register y luego con un with select elegir las señales de control que salen según lo que mandó el register cu que debería ser un opcode

**Comment by FelipeCampbell** [comment]
Quizás la cu tb tendría que recibir el stalling para que funcione solo después de que llegue el literal y no en todos los ciclos del pc? sino propagaría las señales del opcode que le llega cuando stalin = 0 y la ejecutaría con lo que sale de la memoria y llega al mux b o me equivoco?

**Comment by frvalenzuela** [comment]
Hola @FelipeCampbell !

Favor revisar #144 , si queda alguna duda hacerlo saber.

Saludos!
