### ISSUE TITLE
Assembler IIC2343.exe para qué?

### ISSUE THREAD

**Issue by cjgazali** [IIC2343/syllabus#136]
Hay un ejecutable en la carpeta Entrega 2 que no entiendo cómo se usa... para qué deberíamos usarlo? Perdonen si hay una explicación que no haya encontrado.

**Comment by Hernan4444** [comment]
@cjgazali es un emulador de assembly que sirve para simular los códigos assembly y vean si el resultado final es el mismo que en su placa.

Saludos
