### ISSUE TITLE
AND y otras instrucciones.

### ISSUE THREAD

**Issue by jmopaso** [IIC2343/syllabus#136]
Hola!

No me queda claro cual debe ser el resultado que retorna la operación **AND** entre dos literales.
Por ejemplo, si tengo el código de prueba entregado en el enunciado.
 ```
PUSH 3
PUSH 5
ADD
```
Finalmente tenía que mi stack quedaba de la forma:
`[0|8|5|0|0|0|0|...], SP = 254`
( Según el supuesto explicado en la issue #122 )
Donde mi el *stack pointer* queda apuntando al 8 que es el resultado de 3 + 5.

Ahora bien, ¿como quedaría el stack si en vez de la operación add ocupo la operación and?

**Comment by Geeermy** [comment]
¡Hola! Es una operación _bitwise_, puedes verla mejor viendo la representación binaria de los números:

```
00000011
    AND
00000101
      =
00000001
```

Entonces, para el programa:

```
PUSH 3
PUSH 5
AND
```

Tu _stack_ queda como sigue:

```
[0|1|5|0|0|0|0|...], SP = 254
```

Se sigue la misma lógica para ```OR, XOR, NOT```. 😄
