### ISSUE TITLE
Uso de operaciones aritmeticas para el display

### ISSUE THREAD

**Issue by CmPoblete** [IIC2343/syllabus#137]
Se pueden usar operaciones aritmeticas para transformar los numeros de 8 bits a formato BCD para mostrarlo en el display?

**Comment by FranLucchini** [comment]
Hola, 

La idea es usar los diplays en formado hexadecimal y eso esperamos que muestren cuando debamos corregir. Puedes hacer un circucito que hace la tranformación que deseas y puedes usar operaciones aritméticas, dado que es algo fuera de lo que pedimos en la tarea. Pero, al entregar, se deben mostrar los número en hexadecimal en los diplays.

**Comment by CmPoblete** [comment]
No entiendo por que se deben mostrar en formato hexadecimal. No tendria mas sentido mostrarlo en formato decimal?

**Comment by FranLucchini** [comment]
En realidad, es porque el controlador del diplay que tenemos está hecho para mostrar en hexadecimal. Además, usar hexadecimal permite expresar más número que la base decimal.

**Comment by naquiroz** [comment]
@FranLucchini entonces lo que debemos mostrar en el display es el resultado de la alu?
