### ISSUE TITLE
Administrativa | Actualización Enunciado Tarea 3 | Pregunta 1.2

### ISSUE THREAD

**Issue by quememo** [IIC2343/Syllabus#137]
Respecto a la actualización del enunciado de la pregunta 1.2 en la Tarea 3, donde se cambia `El contador de hazards aumenta siempre que haya un salto incondicional` a `condicional`, creo es necesario el envío de un aviso, pues es posible que muchos alumnos no se hayan dado cuenta de este cambio y afecta considerablemente el resultado del output al añadir los incondicionales a este contador.

**Comment by jmwielandt** [comment]
🤔 Claro... Anuncio enviado. Gracias por recordarlo~
