### ISSUE TITLE
Proceso completo entrega 2 

### ISSUE THREAD

**Issue by cjgazali** [IIC2343/syllabus#137]
Si pensamos en la ejecución de nuestro trabajo de la entrega dos como un proceso, ¿Cómo se podría 'narrar'? Nos falta una especie de resumen...

Entendemos que ocupamos nuestra tarea en la entrega, a diferencia de la entrega anterior.

Entendemos que nos dan un .txt en assembly que transformamos con nuestro assembler a instrucciones binarias de largo 33... de ahí no nos queda claro en qué formato guardamos esta información y cómo va a terminar esto corriendo en nuestra entrega física.

Favor de narrar qué va a ocurrir desde que nos entregan instrucciones, partiendo por cómo vienen las instrucciones mismas, hasta que se prueba que el resultado en nuestro circuito es correcto.

**Comment by Hernan4444** [comment]
@cjgazali el proceso completo es:
1) Les pasamos un assembly en formato txt
2) Lo pasan por su tarea (Assembler) y crean lineas en binario de largo 33
3) Copian esas lineas en la rom del vivado ( ⚠️ Si creas 20 lineas, tienes que reemplazar 20 del vivado, no pueden ser más ni menos lineas)
4) Generas el .bit en vivado
5) Lo pones en la placa y vez como se ejecuta comando por comando según la velocidad del clock

Saludos

**Comment by lefischer** [comment]
@Hernan4444  
Según lo que entendí a partir del código en assemby tenemos que crear otro archivo txt donde cada linea representa su respectiva linea en la rom, o hay que hacer otra cola?

**Comment by Hernan4444** [comment]
@lefischer es lo primero, tienen que crear otro archivo txt donde cada linea representa su respectiva linea en la rom.

Saludos ✌️

**Comment by lefischer** [comment]
@Hernan4444  

gracias 👍
