### ISSUE TITLE
[T03-PROGRAMADA] DUDA EJEMPLO ENUNCIADO VALOR SP

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#137]
En el ejemplo del enunciado hay un ret pero no un call, lo cual al llegar al ret hace sp=sp+1, lo cual me manda el puntero a 4096, es decir 10000 en octal. Que hago con respecto a eso? Gracias!

**Comment by Arcoirisky** [comment]
¿Por qué es un problema?

Lo que está haciendo el enunciado es definir una subrutina, si no hay _call_ a la subrutina no debería de ejecutarse. Ya que no se le está llamando O:
