### ISSUE TITLE
[T03- Placa] Combinatorial Loop Error (Compilando)

### ISSUE THREAD

**Issue by pgarnham** [IIC2343/syllabus#138]
Ya tenemos todo conectado, y al agregar dos instrucciones para probar el funcionamiento, nos tira este error.

Nuestra Main Memory parte así:

"000000000011"
"000000000001"
"000000000111"
"000000001000"

![Error Loop](https://user-images.githubusercontent.com/18725662/57574398-5c610a00-7406-11e9-821d-bbc18ea5e0cd.png)

A que se puede deber esto?

**Comment by danyestay** [comment]
A mí me pasa lo mismo :'(

**Comment by MrEarle** [comment]
A mi tambien

**Comment by Arcoirisky** [comment]
¿Que Es lo que intentas probar? Si toda la RAM es 0 ¿te pasa lo mismo?

**Comment by pgarnham** [comment]
Si pongo toda la RAM en 000000000000 me da el mismo error 😢 
La idea con esas instrucciones era poner un registro en 1, y luego sumarle 8. Queríamos partir probando algo básico pero no podemos compilar todavía.

**Comment by frvalenzuela** [comment]
Hola @pgarnham , @danyestay y @MrEarle !

Favor revisar #144 , si queda alguna duda favor hacerlo saber.

Saludos!
