### ISSUE TITLE
Duda sobre bits en el diagrama de la entrega 2

### ISSUE THREAD

**Issue by jisilvamc** [IIC2343/syllabus#138]
Hola, me queda una duda con el diagrama de la entrega... sale que la unidad de control recibe 17 bits de la ROM, más 3 del status, y saca 11 señales para el resto de los componentes. Por lo que entendí en clases, la idea de la unidad de control es que funcione al revés, guardando palabras muy largas con direcciones más cortas, ya que no todas las combinaciones de señales son válidas (como activar el cambio de valor de dos registros al mismo tiempo). ¿Esto es un error del dibujo o un problema conceptual mío?
Gracias de antemano

**Comment by Hernan4444** [comment]
@jisilvamc precisamente debe ser al revés. solo que nosotros disponemos de 17 bits y no podemos hacerlos desaparecer pero puedes dejarlos con `0` y analizar solo los bits que tu necesitas para ver el opcode.

**Comment by jisilvamc** [comment]
Perfecto, muchas gracias
