### ISSUE TITLE
Duda materia CACHE

### ISSUE THREAD

**Issue by csolguin** [IIC2343/Syllabus#138]
En la funcion directly mapped, cuando se carga una dirección que esta al final de un bloque, ¿este igual carga en el siguiente bloque su sucesor (como se muestra en la imagen) ?

![duda](https://user-images.githubusercontent.com/33853290/69916649-3e0f3a00-143c-11ea-88da-3c0ed0039c9b.jpg)

Asumir que son 4 bloques de 2 palabras.

**Comment by Snorlax8** [comment]
Según entiendo, vas cargando la memoria respetando los bloques. La dirección 1 de memoria principal va en el mismo bloque que la dirección 0, por lo que si tienes que cargar Mem[1] en caché, cargas también Mem[0] justo arriba.
