### ISSUE TITLE
Tarea 3 | Aplicable para todas las preguntas | Ejemplos con flush

### ISSUE THREAD

**Issue by quememo** [IIC2343/Syllabus#138]
Revisando los ejemplos me surgió una duda cuando tenemos un caso en el que exista un hazard de control y haya un flush asociado (también pasa en los stalling), en particular voy a tomar este ejemplo que aparece en el enunciado, que también es aplicable para el resto de casos:
![image](https://user-images.githubusercontent.com/48305214/85235914-0fac7880-b3e7-11ea-86db-a1d144e05a32.png)
Pareciera ser que "se congela el tiempo" entre instrucciones cuando hay flush, justo después de la instrucción JEQ 43 en el clock 38, ocurre la instrucción MOV B,(8) en el clock 39, pero me da la impresión que el clock debería tener en consideración estos flush y en verdad ese clock 39 debería ser 42. Lo mismo ocurre en presencia de stalling, aquel NOP que se introduce entremedio de instrucciones no retrasa el clock de la siguiente instrucción en 1 (sin considerar los flushes anteriores, se tiene clock 39 con instrucción MOV B,(8) y clock 40 en vez de 41 para la instrucción MOV (5),B )

¿Como debemos interpretar esto?

**Comment by Cadagan** [comment]
Siguiendo esa linea, si encontramos un hazard de control con este ejemplo basico:

N° Clock | PC....................Instruccion
-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-
1................| 0 ....................MOV A,120
2................| 1.....................MOV B,120
3................| 2.....................JEQ 42
4................| 42...................MOV A,15
5................| 43...................MOV B,15
6................| 44...................JEQ 53
7................| 53...................( . . .)

En el caso del primer hazard de control, el clock al momento de detectar seria 3 (N° clock del jump) + 3 = 6

Mi duda es: en el caso del segundo hazard, ¿Tomamos 6 (N° clock del jump) + 3 = 9, o debiésemos contar el clock con los ciclos que perdio? (en este ejemplo: 6 (N° clock del jump)  + los 3 perdidos en el salto anterior + 3 = 12)

Gracias de antemano 🙌

**Comment by jmwielandt** [comment]
En la pregunta de Pipeline II, ignoren la posibilidad de que ocurran hazards de datos. Preocúpense únicamente de los hazards de control.

Tampoco desfasen el número del clock para considerar los nops por hacer stalling ni las instrucciones borradas al hacer flush, quédense con los valores que les damos por STDIN. (En las 2 de pipeline)

**Comment by nbnavarro** [comment]
Hola @jmwielandt, siguiendo el ejemplo de martín, en el primer hazard de control, la respuesta esperada es 3 o 6?

Gracias de antemano

**Comment by ceosorio** [comment]
Hola @nbnavarro!

Como mencionó @jmwielandt, no tienen que hacer desfase del clock, por lo que la respuesta sería 3 :)

Saludos :sparkles:
