### ISSUE TITLE
[T03 - programada]

### ISSUE THREAD

**Issue by Okhan97** [IIC2343/syllabus#139]
Hola,
![image](https://user-images.githubusercontent.com/26289334/57575999-5f6af300-7424-11e9-83ee-eb973e3787f1.png)

¿hay problema si el output de mi programa está así?

**Comment by Arcoirisky** [comment]
Para estandarizar todas las tareas pedimos que sean como en el enunciado.

**Comment by Okhan97** [comment]
@Arcoirisky en la tarea aparece así:
![image](https://user-images.githubusercontent.com/26289334/57576330-0fdbf580-742b-11e9-8ef9-171f1415bec2.png)
Pero en el binario los numero están como en la primera imagen, ¿cual formato debo seguir?

**Comment by Arcoirisky** [comment]
El enunciado manda, los archivos de ejemplo solo son de ejemplo (ademas asi GitHub dejaba más estilizado el archivo según la extensión)

**Comment by JaviFerrada** [comment]
Y para el input del disassembler será un archivo como el binario o en el formato del enunciado?

**Comment by Arcoirisky** [comment]
@JaviFerrada Como el enunciado
