### ISSUE TITLE
Tarea 3 | Pregunta 1.2 | Tamaño registros

### ISSUE THREAD

**Issue by diegomendieta** [IIC2343/Syllabus#139]
Hola, en la pregunta de pipeline, de qué tamaño tenemos que considerar que son los registros? De eso depende el bit de Carry en el status. Y otro detalle, qué operaciones son las que debemos considerar que van a aparecer antes de un jump condicional?

**Comment by jmwielandt** [comment]
8 bits. Cualquier instrucción de las páginas 4 y 5 del capítulo 5.5 de los apuntes. Al menos las que es claro el valor de los condition codes.
