### ISSUE TITLE
Aclaración sobre el Bonus

### ISSUE THREAD

**Issue by norman123123** [IIC2343/syllabus#139]
Con respecto al bonus, por "todas las instrucciones de salto vistas en clases" se refiere a los saltos  incondicionales, condicionales o a la llamada a subrutinas?

o todas las anteriores?

**Comment by Geeermy** [comment]
Todo menos subrutinas. 🍸

**Comment by norman123123** [comment]
Y es necesario programarlas en el stack? o basta con describir todo en el pdf?

**Comment by Geeermy** [comment]
Si quieres optar al bonus completo, debes programarlo. En otro caso, dependerá de quién corrija si se asigna un porcentaje del puntaje o no, ya que quedará a criterio del corrector o correctora según lo estipulado en el enunciado.

**Comment by ValentinaAlvarezG** [comment]
Pero en el enunciado de la tarea solo habla del pdf con las cosas que se necesitarían 😢

**Comment by Geeermy** [comment]
@ValentinaAlvarezG cito el enunciado: 

> ...podrá optar a un bonus de hasta 1.0 puntos si **le añade a la máquina de _stack_** todas las instrucciones de salto vistas en clases.

Para añadirle a la máquina de _stack_ la funcionalidad de saltos no basta con poner un PDF con todas las indicaciones, eso es solo una guía para que el corrector vea cómo lo implementaron. La gracia del bonus era ver, efectivamente, el funcionamiento de saltos en su tarea (más aún, por eso entre los puntos pedidos se habla de "detalles de su implementación").

Hablando con otros alumnos antes de la entrega vi que varios lo estaban programando, por lo que no esperaba que existiera esa confusión. 😕
