### ISSUE TITLE
Duda del formato de las direcciones en la Tarea 2

### ISSUE THREAD

**Issue by dalliende** [IIC2343/syllabus#139]
Hola Mundo!
Quisiera saber cual es el formato de las direcciones en el Assembler, por ejemplo si nos dicen MOV A,(10) la dirección esta en binario o en base 10?. Osea para el código final el address es 000000001010 o 000000000010.

Saludos

**Comment by Hernan4444** [comment]
@dalliende en el pdf de Assembler, pagina 3 están los formatos de los literales.

Saludos

**Comment by dalliende** [comment]
Pero, las direcciones pueden tener el mismo formato que los literales?.

**Comment by Hernan4444** [comment]
Al final las direcciones tambien son literales
