### ISSUE TITLE
Problemas con bits (?)

### ISSUE THREAD

**Issue by narierao** [IIC2343/Syllabus#14]
Hola! en la tarea me sale que al sumar 33 bits me dan los segundos en negativo:

![image](https://user-images.githubusercontent.com/20784195/78700795-eabe6400-78d3-11ea-92ce-12fa843bc9ed.png)

Y lo estoy haciendo mediante la suma de potencias de 2. (así represento los bits para saber en cuánto tiempo ocurre el problema).

**Comment by narierao** [comment]
Me sirve como ejemplo para los programas que tendrán problemas al tener 32 bits? kjaskjsajaskkjas

**Comment by jmwielandt** [comment]
Estás usando long unsigned int para los segundos?

**Comment by narierao** [comment]
sip

![image](https://user-images.githubusercontent.com/20784195/78706276-cf0b8b80-78dc-11ea-8631-550329d3c5ed.png)

Y luego de eso le sumo pontencias de dos

**Comment by narierao** [comment]
Aún no me funciona, se lo puedo mandar a alguien? creo que tengo un error que es netamente conceptual :/

**Comment by BSamilla** [comment]
@narierao tu código funciona bastante bien. No es ningún error conceptual.

Ten ojo con como estas casteando los valores, y recuerda que la cantidad de dígitos del formato que les damos es el *mínimo* numero de dígitos que puede tener cada unidad de tiempo.

**Comment by narierao** [comment]
Perdón, pero no entendí casi nada de lo que me dices T.T Podrías hacer alguna "traducción" para poder terminar mi código? 

Muchas gracias!

**Comment by jmwielandt** [comment]
Hola, creo que tu problema es porque estás usando ints en vez de long unsigned ints cuando haces `(int) segundos` más abajo en tu código. Ese casteo (poner el `(int)`) no es necesario de hecho porque en C, a diferencia de python, dividir enteros hace que siempre te den números enteros.

Cuéntanos si te funciona! :D

**Comment by narierao** [comment]
Seco! ahí me pasó un test case más. Me queda solo uno que me sale respuesta incorrecta. Será error del código?

**Comment by jmwielandt** [comment]
@narierao creo que con lo que comenté ya fue suficiente hint ^^u
Deberías poder lograrlo ahora.
