### ISSUE TITLE
Testeo placa

### ISSUE THREAD

**Issue by francisca1** [IIC2343/syllabus#14]
Testie la placa con las instrucciones del archivo tutorial de instalación , con el archivo .bit del semestre pasado, al seleccionar program device me pide seleccionar un archivo .bit y aparte un "debug probes file" y si solo cargo el archivo .bit me sale esto en la consola.
![imagen](https://user-images.githubusercontent.com/26394880/38457810-9dc3ba90-3a6b-11e8-85fa-9cc0792aa24c.png)
¿ Que debería hacer ?

**Comment by Hernan4444** [comment]
@francisca1 eso solo es un warning. Cuando cargaste solo el .bit, ¿tu placa comenzó a hacer otra cosa? y lo otro, ¿puedes mandar el .bit que ocupaste?

Saudos ✌️

**Comment by francisca1** [comment]
ese es el archivo .bit, por github no se puede enviar.

2018-04-07 16:09 GMT-03:00 Hernan Valdivieso <notifications@github.com>:

**Comment by francisca1** [comment]
La placa solo muestra los leds en 0 .

**Comment by FranLucchini** [comment]
Y si apretan los botones como en la tarea, sigue sin hacer algo?

**Comment by FranLucchini** [comment]
@francisca1, al final lo pudieron probar?
