### ISSUE TITLE
[Control] Materia

### ISSUE THREAD

**Issue by aeperalta** [IIC2343/syllabus#14]
Hola! 

No fui a la última clase, por lo que no sé dónde quedaron... ¿hasta qué materia entra en el control? Y lo otro, ¿es posible que suban una solución a la ayudantía 2 antes de mañana?

Saludos.

**Comment by Arcoirisky** [comment]
Hola! Entra toda la materia vista hasta el lunes, eso incluye Programar en Assembly. Además, el profesor confirmó que no preguntaría aritmética de números binarios.

Te sugiero hacer las ayudantías con sus ejercicios propuestos además de los nuevos que subimos ayer para que estudiaran :D ¡No olvides repasar las clases también!

Y en general las soluciones de las ayudantías se suben los domingos :DD Ánimo y suerte!
