### ISSUE TITLE
Duda Tarea: Floats

### ISSUE THREAD

**Issue by ceosorio** [IIC2343/Syllabus#14]
Hola!

En la tarea una pregunta es con **floats**, mi duda es si para obtener la información de éstos hay alguna forma de hacerlo sin uso de punteros, que no sea a "fuerza bruta". No pregunto por la forma, solo si existe alguna.

**Comment by Allmoz** [comment]
Hola,

Efectivamente el compilador de C no te va a permitir el uso de operadores bitwise sobre un float directamente, porque no hay ni una buena razon para hacerlo, aparte de la académica. Para procesar floats existe hardware especializado , FPU, separado de la ALU. En C++ podrías usar "operator overloading" en una clase contenedora para definir los operadores.

PD: Para el resto, si bien hay que usar punteros para re-interpretar el tipo, esa parte está en los anexos del enunciado de la tarea.

**Comment by ceosorio** [comment]
Ahi lo vi, muchas gracias!

**Comment by Allmoz** [comment]
Reparado los anexos del enunciado, ahora si está el uso de puntero para la re-interpretación de float a  unsigned int.

**Comment by aeperalta** [comment]
@Allmoz Hola! No entiendo lo que hace esta línea
`unsigned int bits = *((unsigned int*) (&f));`
¿Cómo funciona esa re-interpretación?  ¿Qué representa?

**Comment by Allmoz** [comment]
Hola,

Si lees con palabras  "unsigned int bits = *((unsigned int*) (&f));" es parecido a:

Considera la dirección a memoria del punto flotante llamado "f" como una dirección a memoria de un entero sin signo. Luego recupera el valor del entero sin signo almacenado en dicha dirección y  guárdala en  la memoria en la dirección del entero  sin signo llamado "bits". 

Por lo que los bits del float "f" quedan almacenados en el unsigned int "bits" sin ser modificados.


Por otro lado, uniendo tu pregunta a lo que vimos el martes y hoy:

Si copiamos una variable como normalmente lo hacemos:

float f2 = f; // es semejante a;
    MOV A,(f)
    MOV (f2),A

Ahora si descomponemos  en 3 partes la re-interpretación del puntero:

float* p_f = &f; // es semejante a:
    MOV A,f
    MOV (p_f),A

unsigned int* p_bits = (unsigned int *) p_f; // es semejante a
    MOV A,(p_f)
    MOV (p_bits),A

ungined int bits = *p_bits; // es semejante a:
   MOV B,(p_bits)
   MOV A,(B)
   MOV (bits),A


Más técnico es saber que  &f hace referencia al puntero de f, &f  para el compilador es del tipo  (float*) porque es el puntero a un float,  el cual que se puede convertir a un puntero de un entero sin signo (unsigned int *)  al cual finalmente se puede desreferenciar usando el operador * para recuperar el valor correspondiente.

más sobre punteros en https://es.wikipedia.org/wiki/Puntero_(informática)
más sobre el operador * https://es.wikipedia.org/wiki/Operador_de_desreferencia
