### ISSUE TITLE
[T3-Placa] Conectar Placa

### ISSUE THREAD

**Issue by Tito0906** [IIC2343/syllabus#140]
Hola, trato de conectar la placa y al parecer no se termina nunca de conectar o al menos no se hace efectiva la conexión. Para conectar la placa lo que hago es conectarla al computador, prenderla y en vivado, apreto auto-conect. Por favor decirme si me falta hacer algo o que puedo hacer para usarla, muchas gracias.

**Comment by Arcoirisky** [comment]
¿Te aparece algún error? Porque si efectivamente existe un problema debería aparecerte un error en la "consola" de Vivado

**Comment by Tito0906** [comment]
No, como que se conecta un segundo y después desaparece. Además cuando trato de conectarlo denuevo con auto-connect nunca logra conectar.

**Comment by frvalenzuela** [comment]
Hola @Tito0906 ! 

Puedes indicar el número de tu placa ? También intentas cornectarla otro puerto? Y por último. Que sistema operativo estás usándolo ? 

Saludos !

**Comment by Tito0906** [comment]
Lo traté de conectar a todos los puertos del computador. Estoy usando windows 10. Sobre el número de placa no sé como verlo (es la primera vez que uso placa) pero si veo que en la parte de atras hay un código de barra con "D736090". Como dije no sé si a eso te refieres al número de placa.

**Comment by Arcoirisky** [comment]
¿No será el número que está en la caja?

**Comment by Tito0906** [comment]
Creí que ese era sólo el numero de grupo, perdón. El numero es 1.

**Comment by frvalenzuela** [comment]
Hola @Tito0906 ! 

Intentaron conectarlo en el computador de tu compañer@ de grupo? En cualquier caso recomiendo fuertemente rellenar el formulario para una junta presencial que se encuentra en el README del syllabus. 

Saludos !
