### ISSUE TITLE
Tarea 3 | Pregunta 1.3 | Orden de bloques FIFO

### ISSUE THREAD

**Issue by isiguelfand** [IIC2343/Syllabus#141]
Hola!
Hay algún orden para imprimir los dos bloques distintos dentro de cada conjunto ? Entiendo como se tienen que reemplazar, pero no en que orden entregárselos a la función print_cache.

**Comment by ceosorio** [comment]
Hola @isiguelfand!

La función recibe los bloques en orden 0,1,2,3. Para el caso de la tarea, esto corresponde a los dos bloques del primer conjunto (es decir, 0 y 1) y luego los dos bloques del segundo conjunto (2 y 3). 

Con respecto al orden de los bloques _dentro_ del conjunto, dichos bloques tienen un orden fijo que debe ser consistente. Esto hace sentido cuando piensas en los reemplazos donde referirse al primer bloque del conjunto 0 es distinto a hablar del segundo bloque. Es decir, el bloque que le pases a la función como bloque n° 1, siempre debe mantenerse.

Si no me quedó muy claro puedes seguir preguntando por aqui :3

Éxito en la tarea! :sparkles:
