### ISSUE TITLE
DATA Y CODE

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2343/syllabus#141]
Hola, en la tarea en la parte del assembler, si no consideramos las lineas en blanco ni los comentarios, ¿siempre se parte con DATA? ¿o puede no estar o haber algún label o algo antes?
Gracias!

**Comment by Hernan4444** [comment]
@FranciscoLarach siempre se partirá con DATA y en los archivos assembly solo habrán comentarios, sección DATA y sección CODE.
Saludos

**Comment by FranciscoLarach** [comment]
Buenísimo, gracias
