### ISSUE TITLE
[T3 -Programada] Consulta SP

### ISSUE THREAD

**Issue by seba608** [IIC2343/syllabus#141]
Hola,

En la issue #124 ya preguntaron esto pero sigo con la duda. Según lo que yo interpreto del enunciado, para el opcode 0o0042 las operaciones son Memory[SP] = Ax ; SP = SP - 1 y uno debería hacerlas en ese orden, sin embargo en la issue citada se menciona que eso es al revés y primero debería aplicar  SP = SP - 1 y luego acceder a la memoria. La misma duda aplica para la instrucción CALL (opcode 0o0050).

Saludos!

**Comment by Arcoirisky** [comment]
Lo que hace el orden ``` Memory[SP] = Ax ; SP = SP - 1``` es primero guardar en memoria y luego mover el SP mientras que si lo das vuelta, practicamente haces lo mismo pero empiezas con moverte.

Al fin y al cabo no importa tanto el orden si se mantiene constante y coherente con su creación, ya que nuestro SP desde el inicio apunta a la ultima dirección de memoria, entonces guarda ahí y se mueve. Nunca debería de sobrescribir ningún valor que hubiera gardado él mismo porque siempre se va moviendo.

De la forma que dices, primero se mueve y luego se guarda, entonces tu sp debería partir de una dirección conveniente en caso de que dejara "espacios vacios". 

Todo depende de como tu arquitectura maneje los datos que entran y salen de memoria. En este caso elegimos este.

**Comment by seba608** [comment]
Tenía entendido lo mismo, pero en la issue #124 no lo describen igual y de hecho en el ejemplo del enunciado el SP parte con el valor 0o0000 y según tu respuesta debería ser en la dirección 4095 (memoria de tamaño 2 elevado a 12). Además, si no me equivoco, la dirección 4095 no se puede pasar a octal si usamos complemento.

En 12 bits el número positivo más grande sería 0111 1111 1111, que si no me equivoco es (2 elevado a 11) menos 1.

**Comment by seba608** [comment]
@Arcoirisky Necesito saber si estoy entendiendo algo mal

**Comment by Arcoirisky** [comment]
Cuando son direcciones, siempre son positivos o: No importa el complemento o la forma en la que estás representando los números O:

Eso del complemento es solo para poder operar en el mundo de los Enteros aka solo en la ALU existen los negativos y positibos. Fuera de esta todo es "positivo", porque sino pasaría lo que dices O: y tendrías posiciones negativas D:

pd: Gracias por llamar mi atención xD

**Comment by seba608** [comment]
@Arcoirisky Entiendo que las direcciones solo son positivas pero en el enunciado de la tarea nos piden que usemos el complemento de la base octal y no se mencionaba que eso contaba solo para la ALU.

Y en cuanto a la otra duda, en el primer comentario mencionas que el SP parte apuntando a la última posición, pero en el ejemplo del enunciado parte en el 0o0000, ¿cómo será finalmente? creo que de eso también depende de si accedo a memoria y luego muevo el SP o si es al revés en las instrucciones como PUSH.

**Comment by Arcoirisky** [comment]
No se mencionaba porque debería de ser algo que debieron de darse cuenta por ustedes mismos. Incluso por la confusión de que varios no se habían dado cuenta antes, se dijo en otras issues que minimo debía funcionar con la suma y la resta.

Y sobre lo segundo, la isa dice que deben ejecutar esas 3 instrucciones, el orden lo ven ustedes pero el resultado final debe ser lo que la instrucción dice que hace.

**Comment by seba608** [comment]
Pero tú mencionas que el sp parte en la última dirección de memoria y en el enunciado el ejemplo parte en 0. Independiente de que se puede implementar de distintas formas, no sé si por poner que el sp parte apuntando a la última dirección tendré el output de la simulación malo

**Comment by Arcoirisky** [comment]
Yo lo decía en plan, un ejemplo de cómo funcionaría según lo que me decían (en este caso, guardar y luego mover). 

Si sabes con certeza de que SP empieza en 0o0000 entonces tendrás que ejecutar las instrucciones de forma que la instrucción general funcione. Si no puedes conseguir que el resultado final sea el mismo, seguramente estará malo.

**Comment by frvalenzuela** [comment]
Hola @seba608 !

Que parte en 0, en la posición 4095 o en la mitad de la memoria es algo arbitrario. Generalmente se pone la posición 4095 para no interferir con el programa que generalmente ocupará las primeras direcciones de memoria para ejecutar lo que tenga que ejecutar. Si tu SP parte mirando al final o al principio no debería afectar el funcionamiento general de cualquier programa (a menos que quieras acceder a una dirección que sea cambiada por el SP, que puedes estar tranquilo no se probará con ningún programa que haga algo así). 

Espero que esto calme tu inquietud y resuelva tu duda.

Saludos!

**Comment by seba608** [comment]
Hola @frvalenzuela 

Muchas gracias por la respuesta. Entiendo perfecto que no interferirá en el desarrollo de mi programa, pero simplemente me surgió la inquietud porque en clases siempre se veía que partía apuntando al final  y no al principio. Por su puesto que se puede implementar de las dos formas pero supongo que la gracia es que para la tarea sigamos una convención. Cuando nos muestran ejemplos en el enunciado de la tarea, al menos yo supongo que mi programa debe arrojar lo mismo para que no haya problemas cuando revisen.

En todo caso, para el problema de la simulación usarán un input y entendiendo que se puede implementar de distintas formas, para hacer un POP si implemento mi programa de cierta forma necesitaría el orden de opcodes 0o0044 y 0o0045 y si lo implemento de otra forma necesitaría que el orden de opcodes sea 0o0045 y 0o0044 y uno a priori no sabe cuál usarán. En cualquier caso, no me complicaré más y dejaré especificado en el README lo que interpreté yo.

Saludos!

**Comment by Arcoirisky** [comment]
Pero eso solo pasa cuando la posición inicial del SP depende, y aquí sabes que empieza de 0o0000. 

Quizás no estoy viendo tu confusión, ya que si empiezas desde esa premisa debes tener el mismo resultado que el resto.

**Comment by seba608** [comment]
Quizás te entendí mal, pero en este comentario:

"Al fin y al cabo no importa tanto el orden si se mantiene constante y coherente con su creación, ya que nuestro SP desde el inicio apunta a la ultima dirección de memoria, entonces guarda ahí y se mueve. Nunca debería de sobrescribir ningún valor que hubiera gardado él mismo porque siempre se va moviendo."

Entendí que el SP partía en la última dirección. En fin, parte en 0.

Gracias!
