### ISSUE TITLE
Funcionamiento Disassembler

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2343/syllabus#142]
Cuál es el objetivo del Disassembler al final? Simplemente remplazar los "lit" y "dir" con el valor correspondiente entregado por el archivo .txt
Que hacemos con los registros A y B, tienen alguna influencia en el archivo resultado.txt ?

No se si estoy entendiendo bien el enunciado :(

**Comment by Hernan4444** [comment]
@joseluishaddad un Disassembler recibe dos input, una tabla de "traducción" que conecta código binario con código Assembly y un archivo .txt con código en binario que facilmente podría ponerse en la rom para ver que hace. 
El objetivo del Disassembler es interpretar el código en binario y gracias a la tabla de "traducción", escribir un código en Assembly para poder entender que hace (supongo que a nadie le gusta leer en binario). 

Al final el Assembler lleva de assembly a binario y el disassembler lleva de binario a assembly.

Ojalá se entienda mejor.

Saludos

**Comment by mrafaeli** [comment]
el archivo CSV con los opcodes lo tenemos que hacer nosotros?
