### ISSUE TITLE
Materia C4

### ISSUE THREAD

**Issue by Okhan97** [IIC2343/syllabus#142]
Hola!

¿Pueden dar alguna recomendacion sobre que estudiar de las clases para el control de Miercoles?

**Comment by Arcoirisky** [comment]
Hasta ahora en clases han estado viendo una materia similar a lo que han estado haciendo en sus tareas O: 

Buscar en la isa los opcodes de instrucciones, tomar estos opcodes y generar señales que ejecuten sus instrucciones según el diagrama de un computador. Incluso pueden y se espera, que sean capaces de ver las instrucciones que puede ejecutar una microarquitectura solo con su diagrama ó crear sus propias instrucciones (especificando las señales que involucran)

Si han hecho la tarea a conciencia y entendido lo que está pasando podrían ser capaces de ir más allá a lo que les he mencionado y responder ante situaciones que se hace en la realidad :D 

Alguna duda sobre alguna materia o situación en particular pueden hacerla sin miedo con un ```[C04]``` en el título :D para poder diferenciarles de las issues sobre la tarea.

**Comment by Arcoirisky** [comment]
Tambien recuerden los tipos de direccionamiento, los ejemplos subidos en la hoja resumen por su ayudante de catedra favorito, las arquitecturas vistas en clases (IA-32), etc.

#Suerte

**Comment by cdlepe** [comment]
En relación a esto, a que apuntes debiéramos darles más énfasis en el estudio??
