### ISSUE TITLE
Tarea 3 | Pregunta 1.1 | Duda con aclaración de stalling

### ISSUE THREAD

**Issue by tomasmetroy** [IIC2343/Syllabus#142]
Hola! Me quedó una duda con respecto a la aclaración que hicieron con respecto al _stalling_ en la pregunta de _hazards_ de datos. Esta dice:

**"En la pregunta de _Pipeline_ I, si se tiene que hacer _stalling_ deben indicarlo anteponiendo una "s" a la _forwarding unit_ a usar, quedando "sfw1" o "sfu2"."**

Viendo los apuntes del curso se ve que en estos casos actúa una _data hazard unit_, pero no se menciona cómo influyen las _fowarding units_ para solucionar esto. Podrían explicar a qué se refiere la aclaración?

Muchas gracias!

**Comment by jmwielandt** [comment]
Hola,

La data hazard manda la señal de no incrementar el program counter. Al ciclo siguiente actúa una forwarding unit. Te recomiendo que sigas los cables.

Saludos!
