### ISSUE TITLE
Tarea 3 | Pregunta 1.3 | Duda Caché

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2343/Syllabus#143]
Hola,
Estoy confundida con cuantas lineas tiene la caché. En el enunciado nos dan las características, pero cuando dice: "conjuntos de 2 bloques cada uno" y después dice "bloques de 4 palabras" me confunde. Por que si los bloques tienen 4 palabras no sería 4-way asociative? :(

**Comment by ceosorio** [comment]
Hola @kelseyfranken!

Cuando uno habla de _n-way associative_, estamos hablando de una caché cuyos conjuntos contienen **n bloques** por cada conjunto. Por lo tanto, el n-way es independiente de la cantidad de palabras por bloque. 
A modo de ejemplo:
- Una caché de 3 conjuntos con **4 bloques cada uno** y 3 palabras por bloque <-- Es 4-way associative.
- Una caché de 2 conjuntos de **4 bloques cada uno** y 4 palabras por bloque <-- También es 4-way associative.

Ojalá con eso haya aclarado tu duda :3

Ánimo! :sparkles:

**Comment by kelseyfranken** [comment]
Gracias! Para confirmar: dentro de un conjunto tenemos que elegir entre 2 bloques y dentro de esos 2 bloques elegimos entre 4 direcciones de memoria?  🤔

**Comment by ceosorio** [comment]
Dentro de un conjunto tienes dos bloques y debes elegir uno de esos bloques, como dices. 
Con respecto a las direcciones de memoria (y asumiendo que estás refiriéndote a los reemplazos), como menciono en la issue #128 , tú no guardas (o reemplazas) una sola dirección de memoria en la caché, si no que guardas el bloque completo (osea guardas y reemplazas de a 4 direcciones a la vez). 

Te recomiendo leer esa issue, donde explico en más detalles como funciona :)

Éxito en la tarea :sparkles:
