### ISSUE TITLE
Aviso  T03-Placa + Entrega + Décimas

### ISSUE THREAD

**Issue by FelipeCampbell** [IIC2343/syllabus#143]
Hola :). No entendí el último punto del último aviso (punto: Un problema una solución).

**Comment by Arcoirisky** [comment]
Antes de intentar explicarte todo de nuevo xD ¿Qué no te quedó claro?

**Comment by FelipeCampbell** [comment]
En ese punto decía:
La idea de las tareas es que aprendan y en este caso, el error de que no pudieran --> probar.
No entiendo cuál es la solución al problema de no haber podido probar

**Comment by Arcoirisky** [comment]
SIDING ME CORTÓ EL ANUNCIO :sob: 
Ahora mismo lo intento rescribir

**Comment by FelipeCampbell** [comment]
Jaja dale (:

**Comment by Arcoirisky** [comment]
Esta era básicamente el anuncio parte 2 :crying_cat_face: 

2) Un Problema, una solución. La revancha

La idea de las tareas es que aprendan y en este caso, el error de que no pudieran **probar**  sus componentes fue totalmente nuestro :( 

Estamos más cerca que nunca de encontrar una solución que no modifique su tarea. Y si lo hace, que sea en lo mínimo para que puedan probar el funcionamiento de sus instrucciones. Tengan en cuenta que en menos de 3 días se ha tenido que resolver su tarea de cero, con todos los problemas de sincronización que ustedes no tienen que preocuparse (⌣̩̩́_⌣̩̩̀) Manden fuerzas (/ಥ_ಥ)/

¿Eso significa que todo este tiempo que estuve intentando entender el por qué no funciona fue en vano? ┻━┻ ︵ヽ(`□´)ﾉ︵﻿ ┻━┻

¡NO :D! Sabemos y nos hemos dado cuenta por las issues que se han esforzado, por lo tanto todo ese tiempo gastado ¡será recomensado! ¿cómo? ¡con décimas!

Existen varias instrucciones que la microarquitectura entregada en el enunciado (el diagrama) no soporta. En su readme, **de forma totalmente opcional**, deben de escribir la instrucción no soportada más la razón **fundamentando** con el mismo diagrama.

Por ejemplo, digamos que no es posible ejecutar la instrucción ```Mov Ax, Lit``` (algo totalmente falso pero ilustrativo) entonces en mi README.md escribiría:

```
La instrucción **MOV Ax, Lit** no es soportada por la microarquitectura original porque el registro Ax solo recibe como entrada lo que sale de la ALU y el Literal solo puede llegar al MuxB, quién no tiene un selector con los bits necesarios para permitir que entre el Literal a la ALU como para que logre llegar al registro Ax y almacenarlo.
```

Si la instrucción mencionada y el fundamento es correcto entonces se llevan 2 décimas **por instrucción* extra *directamente sobre su nota** en esta tarea. Además de que les ayudará a estudiar para el Control 04 que se viene el miercoles :warning: 

Este "beneficio" está abierto para todos en el curso. No solo los que están realizando la versión de Placa. 

Agradecer a la Jessica del Pasado por avisparse y escribir como primer punto que la entrega oficial de la tarea es el Miercoles y no hoy, nunca es suficiente. Pero en principio, esto es lo que se perdieron por culpa del siding.

Lamentamos mucho todos los inconvenientes que pudimos causarles pero esperamos que esta solución sea del agrado de todos. De más está decir que, a penas consigamos una solución al soporte de las instrucciones, les subiremos los archivos + el nuevo diagrama para que puedan compararlo con el original y se den una idea de los cambios. Pero pueden hacerlo sin la necesidad de este uwu)/

¡Mucha suerte con todo lo que queda! Ya nos estamos quedando sin semestre  (⌣́_⌣̀)\(˘⌣˘ )

¡Cualquier duda pregunten! Incluso si es de materia, pueden escribir en el título ```[C04]``` y así se separan de las normales. Aún si creen que la pregunta puede ser básica o de una materia que ya se a visto ¡pregunten igual! Con lo que nos gusta hablar de la materia :heart_eyes:

**Comment by dfvasquez** [comment]
Todavía tenemos +24hrs después de la entrega de la tarea para escribir el README?

**Comment by Arcoirisky** [comment]
@dfvasquez
Sip~ recuerden ser claros y que esta vez se descuenta si no existe xD
