### ISSUE TITLE
Registro

### ISSUE THREAD

**Issue by SebaCardenas** [IIC2343/syllabus#143]
Para un registro, la implementación de la senal Load se puede hacer mediante una compuerta lógica AND con el clock? o hay que replicar algo parecido al registro que fue entregado en la Entrega1 ? o si se puede usar esa misma implementación?

Saludos!

**Comment by Rudyjb24** [comment]
Es decir esta estructura que ocuparon en los registros que nos dieron en la primera entrega:

reg_prosses : process (clock)           -- Proceso sensible a clock.

debemos replicarlo para cualquier componenete sensible al clock o debemos hacerlo unicamente con compuertas logicas.

**Comment by Hernan4444** [comment]
@SebaCardenas @RickyUC el load debe ser manejado con lo visto en clases. Nosotros no hemos enseñado process por lo mismo (no es necesario). Como hint puedo decir que el load se relaciona con las señales de control.

Saludos
