### ISSUE TITLE
Notas I1

### ISSUE THREAD

**Issue by Okhan97** [IIC2343/syllabus#144]
Hola, me gustaria saber si las notas de la i1 estarán antes del 29 de septiembre, de no ser así se podria intentar que asi fuera ? Lo digo pensando en la fecha maxima para botar ramos

**Comment by Hernan4444** [comment]
@Okhan97 este repositorio es para dudas del proyecto o tareas. Tu pregunta tienes que mandarsela al jefe de catedra o al profesor.

Saludos!!
