### ISSUE TITLE
Tarea 3 | Pregunta 1.3 | FIFO

### ISSUE THREAD

**Issue by pbyoma** [IIC2343/Syllabus#144]
Hola, 
En la pregunta de caché piden utilizar la política de reemplazo FIFO, es decir, el primero en entrar es el primero en salir.  Cuando ocurre esto la nueva linea debe ocupar si o si la segunda posicion del bloque a que se está insertando y la que estaba en el segundo pasa al primero o ocupa la posicion del bloque sacado. 

Explicandolo con el ejemplo del enunciado: 
[6, [0, 1, 2, 3, None, None, None, None, 12, 13, 14, 15, 4, 5, 6, 7], "H"]
y se quiere insertar una palabra al segundo bloque, lo que se saca ahora es 12, 13, 14, 15, por lo que deberia quedar:
1. [x, [0, 1, 2, 3, None, None, None, None, 16, 17, 18, 19, 4, 5, 6, 7], "H"]
2. [x, [0, 1, 2, 3, None, None, None, None,  4, 5, 6, 7,16, 17, 18, 19], "H"]
Cual es la opcion del output esperado?

**Comment by ceosorio** [comment]
Hola @pbyoma!

Estoy un poco confundida con respecto a tu duda. El reemplazo se hace sólo en caso de que la dirección no se encuentre en la caché, por lo que dependerá del valor de ese **x**. De la misma forma con ese valor sabremos qué conjunto debemos revisar en caso de tener que hacer el reemplazo.

Podrías asignar un valor a **x** y hacer el ejemplo con respecto a ese valor? De esa forma podré ver mejor qué parte es la que te produce dudas :)

Quedo atenta! :sparkles:

**Comment by pbyoma** [comment]
1. [18, [0, 1, 2, 3, None, None, None, None, 16, 17, 18, 19, 4, 5, 6, 7], "H"]
2. [18, [0, 1, 2, 3, None, None, None, None, 4, 5, 6, 7,16, 17, 18, 19], "H"]

Mi pregunta mas que nada va por el lado de FIFO y cual de las way ocupar especificamente dentro del bloque que le corresponde. Es decir, lo que estaba en way2 pasa al al way1 o simplemente se inserte en way del que acabas de sacar. Es por un tema del output que esperan, siento que ambas serian correctas

**Comment by ceosorio** [comment]
Gracías por dar mejor el ejemplo :)

Cuando uno usa FIFO, tú reemplazas sólo el bloque más "antiguo", pero el segundo bloque del conjunto no se mueve de lugar. En ese caso, el output correcto sería el **1.**
Sin embargo, ten en cuenta que los bloques pertenecen a un conjunto específico, por lo que para este ejemplo técnicamente, no sería necesario el reemplazo ya que el bloque [16,17,18,19] pertenece al conjunto 0, no al 1.

De todas maneras, si por ejemplo hacemos el ejercicio con la dirección 21, ahí si deberemos reemplazar el bloque más antiguo del segundo conjunto (en este ejemplo asumiremos que es el [12,13,14,15]), por el bloque [20,21,22,23]. y la caché nos quedaría así:

[0, 1, 2, 3, None, None, None, None, 20,21,22,23, 4, 5, 6, 7]

espero que esto haya aclarado tu duda :3

Ánimo! :sparkles:

**Comment by pbyoma** [comment]
Perfecto!! muchas gracias :)
