### ISSUE TITLE
Interpretación de (dir) en Resultados [Disassembler]

### ISSUE THREAD

**Issue by egromero** [IIC2343/syllabus#145]
Hola,

Para la parte de disassembler, como interpreto en el archivo resultados.txt las direcciones? osea, entiendo que el dir en un computador básico es un literal de 16 bits, pero cuando tengo que escribirlo en resultados, lo pongo como un int?
Me surgió la duda porque en los ejemplos de assembler, las direcciones siempre son definidas en data, y como data lo tenemos que dejar vacío... No se si me explico bien :(

Graciassss

**Comment by Hernan4444** [comment]
@egromero en ese caso, las direcciones serán números (`int`) por lo tanto quedaría algo de la forma `MOV A,(3)`. ojalá haya respondido tu duda :(  Sino pediría que reformules la pregunta 😅 

Saludos ✌️

**Comment by egromero** [comment]
Sii graciass !!
