### ISSUE TITLE
Tarea 3 | Pregunta 1.1 | no hay hazards de control

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2343/Syllabus#146]
Hola, que no hayan hazards de control significa que los test que correrán para la pregunta 1.1 nunca tendran jumps o que no debemos tratar estos hazards que se producen?

De antemano, muchas gracias.

**Comment by mariana-ortega** [comment]
O que habrán jumps, pero no generarán hazards de control?
Podemos asumir que no hay jumps?

**Comment by jmwielandt** [comment]
Hay jumps pero deben ignorar esos hazards, es como si la predicción siempre hubiera salido bien y no se necesitara hacer flush nunca.
