### ISSUE TITLE
¿T06?

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#146]
No encuentro la T06 ¿Ya la subieron? 
Pd: No estoy apurando ni nada D: Pensé que me había perdido un correo o algo. Entré en panico sola ;---;

**Comment by jheysen** [comment]
Estamos trabajando en los últimos detalles, pero estén seguros que tendrán 2 semanas para hacerla

**Comment by Arcoirisky** [comment]
Entonces ¡Ánimo! :DD
