### ISSUE TITLE
[C4] Material de Estudio

### ISSUE THREAD

**Issue by tacorrea** [IIC2343/syllabus#146]
Una pregunta, ¿qué material de estudio sirve para el control 4?
De los apuntes, ¿qué capítulo entra? y de las clases, ¿qué clase es?
Cualquier otra fuente de ejercicios o materia, bienvenido.
Saludos

**Comment by Arcoirisky** [comment]
Clase, la última subida 
Apuntes, diría que los que hablan del x86
Material, Daniel está trabajabando en eso pero lo que tuvieron que hacer para la tarea + su bonus les también sirve 🤔

**Comment by Panckx** [comment]
Hola! Me sumo a la respuesta de @Arcoirisky, estoy terminando algunos ejercicios para subirlos con respuesta que creo que servirán para estudiar para el control. Es importante saber x86 (es decir, IA-32), lo que han estado viendo en su tarea y lo que se vio en las clases de la semana pasada (todo lo que sea teoría sobre ISAs, tipos de direccionamiento en x86, etc) que no necesariamente es conocimiento práctico pero es igual de relevante. Ánimo en el estudio!

**Comment by seba608** [comment]
Hola! La clase de hoy no entra entonces?

**Comment by Jiparavich** [comment]
Sumandome a la pregunta anterior, entonces Core I7 no entra?

**Comment by Panckx** [comment]
Hola! Core i7 si entra, ya que lo vieron la semana pasada! Lo importante de Core i7 es entender sus conceptos como el tamaño de cada elemento en memoria, el tamaño de sus palabras, su _endianness_, etc. Con respecto a la pregunta anterior, la clase de ayer no entra, excepto los conceptos que hayan repasado que si se hayan visto la semana pasada. Saludos!

**Comment by Jiruiz2** [comment]
Entonces vendrían siendo las diapos de 09. ISA de las clases solamente?

**Comment by Arcoirisky** [comment]
Sip
