### ISSUE TITLE
Tarea 3 | Pregunta 3 | Cómo tratar el STDIN?

### ISSUE THREAD

**Issue by javierzagal** [IIC2343/Syllabus#147]
- Hola, sé cómo resolver la pregunta pero no sé nada de STDIN y no entendí lo de CMD para probar los códigos, espero me puedan ayudar:
Al tratar el STDIN hay que poner en el codigo algo tipo "archivo = input()", pero, éste input lo debo tratar de igual manera a que estuviese abriendo un archivo con open("nombre.txt", "r") (usando for para diferenciar las lineas) o como si fuese un gran string con saltos de linea ("\n"). Gracias de antemano

**Comment by ceosorio** [comment]
Hola @javierzagal!

Te recomiendo leer la issue #123 , donde explicamos una forma de obtener los datos :)
En el caso de la issue, es como si hicieras input() **n** veces (osea obtienes n lineas de input) y esas las vas guardando en una lista. Esto se hace porque si te das cuenta, la función `parse` debe recibir una lista de strings.

Quedo atenta por si aun te quedan dudas :3

Ánimo! :sparkles:
