### ISSUE TITLE
[Tarea 3][Programada]Duda obvia para alumnos responsables

### ISSUE THREAD

**Issue by Jaluco** [IIC2343/syllabus#147]
En assembler cuando se habla de literales pueden ser tambien variables, no?

Por ejemplo:
ADD Ax, x
x 3

y en la "traduccion" a opcodes en la linea despues del opcode de ADD vendría la direccion de memoria de x?

**Comment by Arcoirisky** [comment]
Sip. 
Toma “literales” como “argumentos”, creo que sería más claro verlo de esa forma 🤔

**Comment by Jaluco** [comment]
Muchas Gracias :D @Arcoirisky

**Comment by elramirezv123** [comment]
Solo por si acaso, creo que esta issue tiende a confundir 🤯, porque en #93 dijeron que para 'referenciar' a una variable debería estar entre corchetes 🤔

**Comment by Arcoirisky** [comment]
Si pero en principio no estamos viendo eso, sino lo que significa hablar de literal.

Lo de los []/()/LoQueQuieras es porque se agregaron, dando a entender que son necesarios para el direccionamiento. 

Si no los tiene, entonces se asume que funciona y se escribe a un ladito que se está considerando de esa forma (para la tarea y todo programa que tenga una forma estándar de direccionamiento indirecto, no pueden hacer eso porque aparecen los problemas mencionados en la issue)

**Comment by Jaluco** [comment]
Ah pero mi pregunta era sobre eso tambien, entonces en mi ejemplo debi poner
ADD Ax, [x]?

**Comment by Jaluco** [comment]
yo se que en mov interesa mucho el tema de las direcciones, pero cualquier referencia a variables debe ser con []?

**Comment by Arcoirisky** [comment]
En el contexto de la tarea (y pensando que quieres referenciar el valor guardado en X) sip. Debiste agregarlos u0u

**Comment by Jaluco** [comment]
okay, gracias por la aclaración

**Comment by Jaluco** [comment]
Y en el contexto de dissasembler, como se cuando el literal es una referencia a una direccion o un valor?

**Comment by Arcoirisky** [comment]
Por el Opcode, por eso existen opcodes que trabajan con literales y otros con Dir

**Comment by Jaluco** [comment]
Pero en los opcodes que tenemos no existe la posibilidad de un ADD Ax, [x] como mi ejemplo :o

**Comment by Jaluco** [comment]
Las dir nomas entonces se refieren a las variables? Pero antes dijieron que un literal podia ser una variable tambien

**Comment by Arcoirisky** [comment]
Nonono
A ver

Mov Ax, [x] es una instrucción (Opcode)
x Es una variable 

x= 5 sigue siendo una variable pero esta te dice que la dirección de memoria a la que apunta x guarda un 5

**Comment by Arcoirisky** [comment]
Las variables no son más que direcciones de memoria. Si haces 

Mov Ax, x 

x, a pesar de ser variable se toma como literal. Pero, si haces 

Mov Ax, [x] 

Se toma como una dirección de memoria que guarda un literal. 

Ya si quieres ir más allá, puedes guardar una variable dentro de otra pero, eso es ir más allá de lo que pedimos.

**Comment by Jaluco** [comment]
Comprendo, me quedo con que Lit significa un valor en todos los casos (De la ISA)
