### ISSUE TITLE
discrepancia entre diagrama y registroCU

### ISSUE THREAD

**Issue by rjdelrio** [IIC2343/syllabus#148]
hola hay algo que no logro entender en el diagrama nuevo sale esto:
![imagen](https://user-images.githubusercontent.com/26306472/57672063-7d7f5180-75e4-11e9-9d64-2692318b1bfd.png)
donde sale que hay 5 entradas y salidas en total sin embargo en el codigo de registroCU salen y entran 6 señales:

```
entity RegisterCU is
    Port ( clock    : in  std_logic;                        -- Se?al del clock (reducido).
           datain   : in  std_logic_vector (11 downto 0);   -- Se?ales de entrada de datos.
           dataout  : out std_logic_vector (11 downto 0);
           lit : out std_logic_vector (11 downto 0);
           selAddSec      : out std_logic;
           stalling      : out std_logic);  -- Se?ales de salida de datos.
end RegisterCU;
```

**Comment by frvalenzuela** [comment]
Hola Raúl ! 

La señal selAddSec debe ser ignorada y conectada a una señal sin interacción. Fue usada para probar cosas que ustedes no deben preocuparse. Dataout es lo conectado a control unit y lit es el cable verde. Si tienes alguna otra duda favor hacerla llegar. 

Saludos !
