### ISSUE TITLE
Tarea 3 | Pregunta 1.2 | Duda acerca de pc ejemplo3

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2343/Syllabus#149]
Hola, tengo una duda acerca de lo siguiente

en el ejemplo 3 el programa solo tiene 22 instrucciones es decir existe hasta pc21
el tema es que las dos ultimas lineas es lo siguiente:
0049|0009   JEQ 21     [0000|001C]
0050|0021   JMP 21     [0000|001C]

en el cual en jeq 21 se pierden 3 instrucciones ya que carga 0010,0011,0012 y se da cuenta que debe saltar pero cuando ejecuta la siguiente instruccion que es jmp21 y en donde finaliza el programa en si , al hacer el if,id,ex de jmp21 estaria cargando 0022,0023,0024 que serian las intrucciones que vienen en el program counter pero como no existe no las carga y no hay instrucciones perdidas perdidos pero si un hazard(?)

de antemano, muchas gracias.

**Comment by ceosorio** [comment]
Hola @nicoparraguez!

Para el caso de la tarea, no consideres a los jumps **incondicionales** como hazards (asume que no se hace ejecución especulativa). 
Lo que sucede es que el emulador termina la ejecución cuando detecta un loop cerrado, por eso JMP es la última instrucción.

Saludos! :sparkles:
