### ISSUE TITLE
definición de datos T06

### ISSUE THREAD

**Issue by Bipavez** [IIC2343/syllabus#149]
¡Hola!
No estoy entendiendo muy bien como es que la máquina  interpreta cuando se define un dato y cómo leer el código assembly.
En el ejemplo de la tarea tenemos este segmento:
```assembly
MOV (var1), A
var1 0
```
que resulta en:
```
00101001
11001000
00000000
```
¿Cuando yo muevo el dato del registro a var1 cómo se donde está var1?
¿Cuando yo digo `var1 0`, estoy registrando el valor 0 en la memoria?
¿El resultado correspondiente a `var1 0` es solo el `00000000`? Si es así ¿Cómo se cual es la dirección? o ¿Las instrucciones tienen que estar contiguas para funcionar?
¿Tengo que inicializar `var1` o puedo simplemente asignarle una posición en la memoria tomando en cuenta la cantidad de líneas de código que tengo?

**Comment by jheysen** [comment]
Hola, primero cuidado que la máquina lo único que conoce es el binario, el assembly es problema del assembler.
Recuerda que en este caso var1 es sólo un label para referirse a esa dirección de memoria, es tarea del assembler resolver cuál es, aunque en este caso eso está dado por el enunciado.
El resto de las preguntas creo que las puedes resolver dado lo anterior.

**Comment by fdduarte** [comment]
Hola!
Aprovecho de colgarme de esta issue ya que tengo una duda puntual relacionada con esto.
No me calza la ubicación de `var1`.
Lo que tengo entendido es que tras utilizar un label, la próxima línea seria la ubicación de este label en la memoria, por lo tanto, si `var1` esta en la línea 9 (como en el ejemplo) la palabra posterior a la utilización del label seria `00001001`.  ¿Porque en el ejemplo dan `11001000` como ubicación de `var1`?

**Comment by jheysen** [comment]
Ya corregí el enunciado
