### ISSUE TITLE
Ejemplos Código IA-32

### ISSUE THREAD

**Issue by Panckx** [IIC2343/syllabus#149]
Hola a todos!

Acabo de subir un archivo a [este link](https://github.com/IIC2343/syllabus/blob/master/Ayudant%C3%ADas/Ejercicios%20Resueltos/x86_examples.pdf) que contiene un pequeño repaso de la arquitectura ISA IA-32 (mejor conocida como x86) desde un punto de vista práctico (son ejemplos de código). Tienen todo lo necesario para entender cómo programar en dicha ISA, partiendo desde cero. También ayuda si tratan de traspasar todo lo que aprendieron programando en MIPS!

Además, al principio hay una suerte de "recordatorio" que es más bien una reflexión sobre algunas diferencias entre MIPS y x86 para facilitar el proceso de aprendizaje mediante la comparación con algo que ustedes ya conocen!

Al final del documento hay un ejemplo de una subrutina recursiva! Ese ejemplo incluye no solo la subrutina, sino también el código llamándola, por lo que, de entender ese ejercicio, podrían considerar que tienen un entendimiento bastante profundo de x86.

Espero que les sirvan los ejercicios resueltos, recuerden que esas resoluciones **solamente son algunas de las posibles soluciones**, pero deberían servir para guiarse al comienzo. Cualquier duda, por supuesto, es merecedora de una issue y estaremos muy felices de responderla!

Finalmente, dado que, en mi opinión, ese mini compilado de ejercicios tiene todo lo necesario para partir desde cero y entender todos los conceptos, si quieren practicar más, los insto a inventar sus propios programas! Si tienen dudas con alguno de sus programas inventados, pueden escribir una issue diciendo qué están intentando hacer, el código que llevan y qué creen que les falta, y, de igual forma, responderemos muy felices!

Eso, ojalá que les sirva!
Buenas noches!

**Comment by Jiparavich** [comment]
Hola Daniel! Una duda respecto al ejercicios Recursivo, en las lineas 19 y 22 cuando estamos "recuperando" los parametros, no debería ser bp + 4 Y bp + 6 dado que los parámetros estan "mas arriba" en el stack.
Lo anterior lo menciono por este ejemplo que sale en los apuntes.


Ejemplo apuntes:
![image](https://user-images.githubusercontent.com/30678179/57720771-8a398f00-7650-11e9-9b5d-21139ac6f81d.png)

**Comment by Panckx** [comment]
Hola! Tienes toda la razón! Lo lamento, lo corregiré de inmediato, muchas gracias y felicitaciones por comprender bien la materia!

**Comment by brayanmoreno** [comment]
Hola Daniel, quisiera saber si en el control de mañana nos darán una guía con el set de instrucciones de x86 o es necesario saberlas todas.

**Comment by dfvasquez** [comment]
Muchas gracias por el material, queda mucho más claro! 😄

**Comment by Arcoirisky** [comment]
@brayanmoreno es bueno que sepas cuales son y cómo funcionan :D

**Comment by Panckx** [comment]
@brayanmoreno les entregaremos las instrucciones que no son clásicas (clásicas = add, inc, etc). Nuestra idea es que sepan utilizar la ISA y no que se la tengan que aprender de memoria, por lo que, aparte de las clásicas, las entregaremos. De igual forma, te recomiendo, al igual que @Arcoirisky, que sepas usar todas las que están en los ejemplos resueltos!
