### ISSUE TITLE
Assembler duda sintaxis txt

### ISSUE THREAD

**Issue by lefischer** [IIC2343/syllabus#149]
Hola, 
 en el ejemplo puesto para la entrega dos en el pdf sobre el assembler salen labels que tienen una linea vacia despues, como se interpreta eso?

Es valido algo como esto:
label1:
label2:
sin lineas entre ambos

saludos

**Comment by Hernan4444** [comment]
@lefischer lo anterior es totalmente valido puesto que al final los labels son solo una ayuda para que el humano entienda el código, son un indicador de que cualquier salto que sea hacia ese label, se haga hacia la posicion del primer comando en asembly que se encuentre debajo del label.
Por ejemplo:
```
MOV A,4
label2:
label1:
MOV A,2
JMP label1
JMP label2
```
Lo anterior es lo mismo que
```
MOV A,4
MOV A,2
JMP 1
JMP 1
```
Ojalá el ejemplo te dé una intuicion de como hay que abordar este en assembly.
Saludos ✌️

**Comment by lefischer** [comment]
@Hernan4444  entonces etsa correcto que en el assembler que tengamos hecho en dicho caso ambos labels indique un salto a la misma linea, ademas en caso de tener 

end:
nada despues,

simplemente indica que se salta a la siguiente linea de la rom, la cual  seria una sin acción cuya direccion es dir_ultima_instruccion + 1

**Comment by Hernan4444** [comment]
@lefischer estás en lo correcto 👍 
Saludos

**Comment by lefischer** [comment]
@Hernan4444  gracias

**Comment by JoseRomeroi** [comment]
Hola, respecto a la sintaxis del .txt:

1) Todas las lineas en que se definen variables van a tener un "//" ?
2) Pueden haber 2 lineas en blanco seguidas?
3) Todas las variables se van a llamar v1, v2 , ......... , vn ? o tendran otros nombres?

salu2

**Comment by Hernan4444** [comment]
@JoseRomeroi sobre tus dudas:
1.  No es necesario
2.  Si pueden haber, e incluso pueden haber más si se buscaba separar códigos en el assembly
3. Las variables pueden tener cualquier nombre permitido para una variable en python (guion bajo, letras, numeros)

Salud3
