### ISSUE TITLE
Duda Ejercicios Propuestos Control Nº1

### ISSUE THREAD

**Issue by Unknomads** [IIC2343/syllabus#15]
Hola!

¿Como hago MOVi si la instrucción no esta en la ISA del documento?

Saludos.

**Comment by Panckx** [comment]
Hola! Como esa instrucción no está en la ISA, no puedes usarla para hacer programas! Debes idear otra forma de lograr lo que quieres utilizando solamente los comandos entregados por dicha ISA. Saludos!

**Comment by Unknomads** [comment]
Gracias.

Suponte puedo hacer lb $s1, 0(9)?

**Comment by Panckx** [comment]
No podrías hacer eso, ya que, según la arquitectura MIPS, _lb_ tiene una sintaxis de la forma `lb Lit($sn)`, donde _$sn_ es el registro _n_, **NO** un literal.

**Comment by Unknomads** [comment]
Gracias!!

**Comment by Unknomads** [comment]
Tengo otra duda ya que me confundí con lo que hicimos en la ayudantía.

Según la ISA del documento de ejercicios propuestos no podemos hacer addi $s3, $s3, 1 cierto?

**Comment by Arcoirisky** [comment]
¿Por qué no? o: El primer argumento es donde se guardará el resultado de la operación que nos de, en este caso, la ALU y es esta última toma lo que hay en el registro $s3 para sumarle 1 pero, esto no significa que sepa donde guardarlo. Sobrescribir un registro de esa forma es totalmente válido :D

**Comment by Unknomads** [comment]
Perfecto!! Gracias!
