### ISSUE TITLE
Tarea 1 - Problema MOV Intérprete

### ISSUE THREAD

**Issue by nivek0o0** [IIC2343/syllabus#15]
Hola, estoy teniendo problemas con la instrucciones
```
MOV A, 0
MOV B, 0
MOV A, 1
MOV B, 1
```
Por alguna extraña razón, que no logré encontrar revisando el código del intérprete, se guarda en los registros los valores 10 y 9 al intentar setear alguno de esos literales.

La única solución que encontré es especificar la base del literal: `MOV A, 0d`

Publico esto para que otros no tengan este mismo problema.
Saludos!

**Comment by MainScientist** [comment]
Hola Kevin, al probar el interprete con el siguiente código:
```
DATA:
CODE:
MOV A, 0
MOV B, 0
//PRT A
//PRT B
MOV A, 1
MOV B, 1
//PRT A
//PRT B
```
Me imprimió `0 0 1 1`. ¿Podrías publicar algun código (que no revele mucho de tu tarea) en donde se produzca este error?

**Comment by BSamilla** [comment]
Hola! 

También tengo problemas con el interprete, aunque no sabría decir cual es, lanza un error al abrir el texto. Sin embargo en el Emulador de windows funciona correctamente ¿Que puedo hacer?

**Comment by MainScientist** [comment]
Puedes hacer una issue con un código que no revele tu tarea en donde pase el problema para poder ver qué hacer y cómo solucionarlo :)

**Comment by BSamilla** [comment]
Es que no se que o cual es el problema, sale eso en la consola apenas abro el texto.....

![captura](https://user-images.githubusercontent.com/37226243/38474578-da3065f8-3b76-11e8-8182-42e8d984545b.PNG)

**Comment by BSamilla** [comment]
Es que no se que o cual es el problema, sale esto en la consola apenas abro el texto ....

![captura1](https://user-images.githubusercontent.com/37226243/38474605-5205c1ae-3b77-11e8-9144-5432d80d3bb1.PNG)

**Comment by MainScientist** [comment]
Envíame el código por email a fipezoa@uc.cl

**Comment by asimonv** [comment]
Hola, el MOV no me está funcionando cuando hago MOV A, (var) en todos los casos. De hecho nunca modifiqué (var) y cambió el valor que le asigné al principio en //HEAD de las otras variables. Qué hago? :-/

**Comment by asimonv** [comment]
@Hernan4444 @FranLucchini ?

**Comment by MainScientist** [comment]
Mandame el codigo a mi mal fipezoa@uc.cl Estás usando la ultima versión?

**Comment by asimonv** [comment]
Sí, estoy usando la última! Te mandaré un mail.
