### ISSUE TITLE
Outputs P5 floats

### ISSUE THREAD

**Issue by bpardobravo** [IIC2343/Syllabus#15]
Hola, deberíamos ser capaces de dar outputs especiales en la P5? Por ejemplo output inf o -inf? Hice el código y funcionaba para todos los casos menos 4, después al incluir ...ciertos casos borde... sigo con 2 sin resolver.
 Aprovecho de preguntar, pueden pasarnos números no normalizados? En ese caso el antecesor de cualquier no normalizado positivo es 0?

**Comment by jmwielandt** [comment]
Hola,
+inf y -inf son outputs válidos, pero no inputs válidos
aunque si haces el algoritmo de encontrar el antecesor y el sucesor bien se calculan solos y luego se imprimen solos correctamente.

Mucho ánimo! :D

**Comment by bpardobravo** [comment]
Mmmm creo que mi código falla por algo que no entiendo de C, por ejemplo en este caso:
```
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
int main() {
float f;
f=0x5fffffff;
printf("%f\n",f);
    
}
```
El resultado debiese ser 36893485948395847680, pero el print sale 1610612736.000000.
Es un número que sale de la calculadora que nos pasaron, así que estoy seguro que es lograble con IEEE754 32 bits.
(Nota, si hago f = 36893485948395847680,  el output pasa a ser 18446741874686296064.000000, un 3er distinto valor)

**Comment by jmwielandt** [comment]
Hola, 0x5fffffff vale 1610612735 en decimal.
Estás confundido con el cómo funcionan las asignaciones de variables con los punto flotantes.

Si yo hago
```c
float x = 5;
```
x va a valer 5 ya que el computador va a tomar el 5 que le estás dando, va a conseguir el patrón de bits que se usan para representar el 5 como float y eso es lo que va a guardar en memoria.

En tu caso, lo que estás intentando es hacer que el patrón de bits que se guarden en tu variable f se corresponda por la representación en binario de el 1610612735, pero el compilador lo que hace es encontrar cómo se representa el 1610612735  como float y te guarda ese número en la memoria. En ese sentido es igual que python, tú le dices 5.0 esperando que se guarde un 5.0, no un 7.00649232162e-45 que es lo que se guardaría si copiara los bits.

![image](https://user-images.githubusercontent.com/37153467/79027792-9d542800-7b5b-11ea-8f8f-eeb4fea7f0db.png)

![image](https://user-images.githubusercontent.com/37153467/79027870-ef954900-7b5b-11ea-8ad7-ae0cc83ad77b.png)

En el material de C que les mandé tienen un código de ejemplo en el que hago operaciones bitwise con un float. Lo que tienes que hacer es pasar lo que está guardado a una variable que se interprete como entero y luego realizar las operaciones lógicas o aritméticas y finalmente hacer el proceso inverso y devolverlo a una variable de punto flotante.

Espero haber resuelto tu duda, dime si no es el caso ;)

**Comment by bpardobravo** [comment]
Entonces lo que no entendí era la calculadora. Pensé que hexadecimal representation era la representación hexadecimal del número, no otra cosa. Es la representación de los binarios de IEEE745, pero en hexadecimal entonces?

**Comment by jmwielandt** [comment]
Sí, es la representación en hexa de la cadena de bits que se guardan.

![image](https://user-images.githubusercontent.com/37153467/79028943-37b66a80-7b60-11ea-9baf-1553512140b1.png)

Sorpresa :o
Resulta que el 1610612735 tiene un exponente tan grande que no le dan los bits en la mantisa para representarlo y lo aproxima a 1610612736. El número inmediatamente menor es el 1610612608 y de esto va un poco la pregunta 5 de la tarea. Me temo que de aquí no puedo decir mucho más.

**Comment by bpardobravo** [comment]
Ya, última pregunta que hago para no estirar mucho esto, me confundí en lo que quería preguntar varias veces, ahora sí:
Si yo genero, usando las casillas de la calculadora, lo siguiente:
![image](https://user-images.githubusercontent.com/48322933/79030528-67b53c00-7b67-11ea-8596-76bc356d1123.png)
Y tomo ese número y lo meto acá:
```
int main()
{
float f;
    f=108086391056891904;
    printf("%f\n",f);
}
```
entonces printea 108086391056891904.000000 (el mismo número).
Por otro lado, si uso las casillas de la calculadora para generar esto:
![image](https://user-images.githubusercontent.com/48322933/79030636-fde96200-7b67-11ea-9fea-593abe09f08d.png)
Y tomo ese número y lo meto acá:
```
int main()
{
float f;
    f=14167099448608935641088;
    printf("%f\n",f);
}
```
entonces printea 0.000000.
Este sí que es el comportamiento que no entiendo

**Comment by jmwielandt** [comment]
Lo acabo de probar en local y me tira esto:

![image](https://user-images.githubusercontent.com/37153467/79030914-73096700-7b69-11ea-87ef-f0bee15fa9e9.png)

Pero si a ese número le pongo un .0 al terminar, funciona bien. Es decir:

```C
#include<stdio.h>

int main()
{
    float f;
    f = 14167099448608935641088.0;
    printf("%f\n",f);
}
```

En varias oportunidades he mencionado al "compilador de C", más adelante se mencionará un poco más de qué es un compilador (en nuestro caso, un assembler), pero de momento te puedo comentar que un compilador es un programa que toma un código fuente y lo transforma en un código máquina que tu computador pueda ejecutar. Bueno, lo que está pasando es que al poner el número como 14167099448608935641088, primero lo toma como una constante entera que debe transformar a punto flotante y al hacer eso te hace overflow ya que el número 14167099448608935641088 requiere de 5 bytes para representarlo, y un entero normal usa solo 4 bytes (que equivale a los 32 bits). En cambio si le pones el .0 al final el compilador de C lo va a intentar llevar directamente de un string a un float y, como float, sí cabe en los 32 bits.

Cosa que busqué y me dio la pista: https://stackoverflow.com/questions/19715782/c-integer-constant-is-too-large-for-its-type

**Comment by bpardobravo** [comment]
Y cómo puedo capturar un stdin tan grande como 14167099448608935641088 como float? Dado que scanf ("%f" ...) no funciona? Tengo la sensación de que los 2 testcase que me faltan son eso, y después de mucho google no doy con la respuesta. Hay alguna manera de agregar un .000 al stdin antes de que se cometa el overflow y el cambio a 0?
