### ISSUE TITLE
Duda Tarea 5.3.1

### ISSUE THREAD

**Issue by Tngarrido** [IIC2343/Syllabus#15]
![image](https://user-images.githubusercontent.com/42189869/63318254-dea17a00-c2e3-11e9-84ee-9f1d62eae728.png)
Hola, he estado arto tiempo intentando entender este problema, he buscado información como [aquí](https://support.microsoft.com/es-cl/help/164015/understanding-tcp-ip-addressing-and-subnetting-basics), logre trasformar en binario y representar cada uno de los 4 bytes en decimal de la IP y la masacara binaria, pero no comprendo los ouputs de los ejemplos y como llegan a la dirección de la subred, nose si alguien puede explicarme de mejor forma el problema, gracias de antemano.

**Comment by jmwielandt** [comment]
Hola!

No te puedo decir cómo calcular la dirección de la subred, pero sí te recomiendo que calcules esta antes de cambiar el formato al de las direcciones IP. De lo que dices, entiendo que ya puedes realizar esa conversión correctamente. :smile:

Saludos~

**Comment by Tngarrido** [comment]
Hola! @jmwielandt 

Pero a que clase (A, B, C) corresponde las direcciones IP que nos entregan, ya que en lo que he leído, por cada clase existe una cantidad especifica de bits en la mascara que  pertenecen a la red y  otra cantidad que representa un host, pero esta cantidad depende de la clase, o  ¿no influye ?.

**Comment by jmwielandt** [comment]
Hola!

A ninguna clase en particular, son random. Las máscaras cumplen con ser máscaras (si te ayuda, busca la notación de barra) y las ip, son completamente aleatorias.

Saludos~

**Comment by Nacho111** [comment]
Que tiene que ver saber como se relacionan la IP y la máscara de subred en el protocolo IPv4 con la tarea?
En la misma tarea da como motivación el siguiente texto: 

> En esta tarea practicarán el uso de distintos tipos de datos, operaciones bitwise y formas de almacenar datos. Esto con el objetivo de que se familiaricen con los contenidos del curso y su aplicación a distintos escenarios, usando el lenguaje de programación C

No veo la justificación de hacernos perder el tiempo buscando este tipo de información. Por lo menos deberían adjuntar alguna fuente con el información mínima necesaria para resolver el problema.

**Comment by Arcoirisky** [comment]
Estimado @Nacho111,

El foro de preguntas no es un medio de reclamos, para ese tipo de comentarios sugiero enviar un mail al profesor con copia al ayudante jefe para que se pueda ver el caso.

Sobre su pregunta, las tareas están para que practiquen en el contexto de una aplicación real de la materia que se ve en clases.
