### ISSUE TITLE
Error XOR ISA Tarea 6

### ISSUE THREAD

**Issue by LuisFros** [IIC2343/syllabus#150]
![image](https://user-images.githubusercontent.com/21247721/46261743-4c776400-c4ce-11e8-8594-dac0aec20b34.png)
Los operandos del **XOR** en la linea que esta marcada en amarillo, deberia ser **A,B** o no? Porque **A XOR A** es siempre 0 y los operandos para la operacion **A=A XOR B** no estan.

**Comment by jheysen** [comment]
Gracias por el aviso, si, es un typpo

**Comment by jheysen** [comment]
Ya se subió el enunciado corregido
