### ISSUE TITLE
Hazard de datos: MuxDin

### ISSUE THREAD

**Issue by csolguin** [IIC2343/Syllabus#150]
Hola! 😄
En la pagina 16 de los apuntes de Paralelismo nivel de instruccion, aparece lo siguiente:

- Si MEM/WB.LoadA == 1, EX/MEM.MemDin == A, EX/MEM.W == 1 corresponde hacer
forwarding del RegIn de la etapa WB a la entrada de memoria.

- Si MEM/WB.LoadB == 1, EX/MEM.MemDin == B, EX/MEM.W == 1 corresponde hacer
forwarding del RegIn de la etapa WB a la entrada de memoria.

```diff

¿No deberian ser  
+  EX/MEM.MuxDin
en vez de 
- EX/MEM.MemDin ?
```
Sino es asi, entonces ¿por qué?

**Comment by Allmoz** [comment]
Lo que te interesa es saber que registro se seleccionó  en el MuxDin, y esa información está en MemIn. MuxDin tiene el valor del dato seleccionado, no su origen.
