### ISSUE TITLE
Duda Operación INC A

### ISSUE THREAD

**Issue by dalliende** [IIC2343/syllabus#150]
Hola, tengo una duda de como realizar esta operacion. Debido a que esto es lo mismo que sumar el registro en A con un 1, este uno debiese venir del MUX de 4 entradas que esta conectado con el registro B, pero ya tenemos definidas 4 entrada ( El literal, la salida de la Ram, El registro B y el "0"). Mi duda es, debemos crear un MUX para B con 5 entradas?, si no debemos hacer eso, que debemos hacer?. Saludos.

**Comment by Hernan4444** [comment]
@dalliende te acabas de dar la respuesta en las primeras dos lineas, no te puedo decir directamente que es lo que tienes que hacer puesto que una de las tareas es que logres entender como funciona cada comando y como se puede llevar a cabo con los componentes que ya tienes.

Saludos

**Comment by camiolguin** [comment]
mmmm no se puede hacer con lo componentes que tenemos, puesto que necesitaríamos guardar el valor del registro a en el registro b y luego realizar la suma. Las soluciones que yo tenia pensado, todas implicaban cambiar algun componente de como lo tienen descrito en la entrega, por ejemplo agregarle al reg b una senal para aumentar en 1 su valor o agregarle el 1 al mux b.

**Comment by camiolguin** [comment]
no importa ya lo solucionamos
