### ISSUE TITLE
Tarea 3 | Pregunta 1.2 | posible error en test_ejemplo_t3

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2343/Syllabus#150]
hola, tengo una duda existencial :(

yo calculo el max pc que existe en el txt que en este caso seria 0028 en n = 0013.
Entonces cuando estoy en esta linea:
0013|0028   JMP 10     [000A|0006]
0014|0010   MOV (0),A  [000A|0006]
en la instruccion 0013 cuando esta haciendo el jmp 10 pasa por 4 ciclos como de pipeline hasta darse cuenta que debe saltar y como la siguiente instruccion es pc = 0010 si habria perdida de instrucciones que por ser pc= 0028 serian las pc= 0029, 0030, 0031 pero como calcule que el max del programa es pc= 0028 no tendria que instrucciones que poner y no habrian instrucciones perdidas pero si hazard.
El tema es que en la linea final dice jump 29 y nunca se nombra pc= 0029 por lo tanto podria existir  pc=0030 hasta pc= 9999 sin que se le llame en la ejecucion del programa pero si generaria instrucciones perdidas en 0028.

Por lo que no hay forma de determinar a ciencia cierta cuantas instrucciones en total tiene el programa dado que se da solo su ejecución por lo que si se puede decir hay hazards de control pero no se puede estimar cuantas instrucciones se pierde si pc >= 0025 por que a ciencia cierta solo sabemos por la ejecucion que existe hasta el pc = 0028.

La pregunta es entonces que hacemos , asumimos que el pc tiene hasta indice el max de la ejecucion o como saber cuantas lineas tiene pc para asi poder contar instrucciones perdidas si hay hazards. 

De antemano,muchas gracias.

**Comment by jmwielandt** [comment]
> El tema es que en la línea final dice jump 29 y nunca se nombra pc= 0029 por lo tanto podría existir pc=0030 hasta pc= 9999 sin que se le llame en la ejecución del programa pero si generaría instrucciones perdidas en 0028.

Ahhhh!!!!!! Ya vi el código. La dirección 29 es donde está la label `end` al final del programa. El emulador aparte de por loop cerrado termina si llega al final de las instrucciones de la ROM. No consideres las instrucciones que después vendrían porque no las hay. Además, recuerda que les regalamos el supuesto de que los jumps incondicionales no generan hazards de control.
