### ISSUE TITLE
[Tarea 3- Programada] Input de disassembler 

### ISSUE THREAD

**Issue by Jaluco** [IIC2343/syllabus#150]
Hola una pregunta, de que forma será el input del dissasembler?
Porque yo tenia entendido que sería como el output del assembler, pero en el archivo de ejemplo aparecen numeros enteros

**Comment by Arcoirisky** [comment]
Es como dices, puedes comprobarlo mirando otras issues sobre el tema. Quien manda es el enunciado :D

**Comment by Jaluco** [comment]
ahhh yaya me asuste jajaja nada peor que terminar y que no corra con el ejemplo

**Comment by Arcoirisky** [comment]
Te entiendo completamente 😂💕
