### ISSUE TITLE
Tarea 3 | Pregunta 1.2 | Posible error ejemplo2.txt

### ISSUE THREAD

**Issue by Cadagan** [IIC2343/Syllabus#151]
En enunciado se menciona que "_El contador de hazards aumenta siempre que haya un salto condicional (es decir, la ejecución especulativa siempre se equivoca)._"

Sin embargo, en el txt del ejemplo2.txt, me encontré con un **caso en que no se equivoca** y no se ejecuta el salto condicional
( . . . )
0061|0020   JEQ 29     [0002|0005]
0062|0021   MOV A,(7)  [0007|0005]
0063|0022   ADD A,(B)  [000C|0005]
0064|0023   MOV (7),A  [000C|0005]
( . . . )

¿Esta malo? ¿o quizás hubo un error de enunciado y no siempre ocurre que se ejecutan los JUMP's condicionales?

**Comment by jmwielandt** [comment]
Hola,

La ejecución que les pasamos no van las instrucciones que fueron borradas al hacer flush:

```
0019|0015   JLT 22     [000A|0006]
-  aquí debería aparecer una instrucción, pero se borró al hacer flush y no sale
-  aquí debería aparecer una instrucción, pero se borró al hacer flush y no sale
-  aquí debería aparecer una instrucción, pero se borró al hacer flush y no sale
0020|0016   SUB A,B    [0004|0006]
0021|0017   MOV (0),A  [0004|0006]
0022|0018   MOV A,(2)  [0000|0006]
0023|0019   ADD A,1    [0001|0006]
```

![image](https://user-images.githubusercontent.com/37153467/85433940-3a1b4480-b553-11ea-9873-11cf8e288a11.png)
