### ISSUE TITLE
[T03 - Placa] Literales en el RegisterCU

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2343/syllabus#151]
Hola,
Ahora con el cambio al diagrama los literales y dir's saldrían siempre del  RegisterCU y solo se usarán valores de memoria cuando se especifique Memory[algo], es lo pregunto por el tema de los literales que entrega la CU como output

**Comment by frvalenzuela** [comment]
Hola @Jiruiz2 !

Supongo que te refieres a los literales que entrega RegisterCU. Si ese fuese el caso, tu lógica estaría correcta.

Saludos!

**Comment by Jiruiz2** [comment]
![image](https://user-images.githubusercontent.com/26437497/57732122-566b6300-766a-11e9-907a-20311a2ec941.png)
Me refiero a estos casos por ejemplo, si no es así, quería preguntar cuales literales serían los que entregaría el RegisterCU. Tengo la duda, ya que el MUX B recibe valores de la Memory y del RegisterCU y no se cual usar

**Comment by frvalenzuela** [comment]
Hola @Jiruiz2 !

En el caso del opcode 66, la memoria queda mas claro decir PC = Memory[SP]. (como se actualiza sp sería sp+lit, pero realmente sale el address es SP).

Los opcodes 63 y 64 basta con seleccionar el SP en el mux A y el literal del RegisterCU.

Espero que eso haya quedado más claro.

Saludos!

**Comment by Jiruiz2** [comment]
Entiendo, pero solo para confirmar
![image](https://user-images.githubusercontent.com/26437497/57733654-02627d80-766e-11e9-940d-59d43610e85d.png)
En el caso de la 004 el literal también sería del RegCU cierto?

**Comment by frvalenzuela** [comment]
Hola @Jiruiz2 !

Así es! 

Saludos!

**Comment by brayanmoreno** [comment]
Solo para confirmar, si yo en el muxaddress escojo el valor dado por el PC obtendría como salida en memoria el mismo valor guardado como literal en el RegCU.

**Comment by frvalenzuela** [comment]
Hola @brayanmoreno !

Si, estas en lo correcto!

Saludos!

**Comment by brayanmoreno** [comment]
@frvalenzuela muchas gracias, pero ahora viendo el diagrama me surgió otra duda con respecto a la ejecución del opcode 66, donde tu mencionas que primero se actualizaría el valor del SP con la salida de la ALU (para este caso sería SP + LIT) y luego en el mux address se debería escoger la entrada del SP que estaría actualizado a SP + LIT, pero esto es considerando que la ALU se ejecuta primero. Yo pensaba que primero se ejecuta el mux address entonces para realizar la ejecución daba el valor del SP al BP y este se suma al LIT en el adder/sub para luego ser escogida esta salida en el mux address y finalmente actualizaba el valor del SP con la ALU. Entonces mi duda es que se ejecuta primero la ALU o el mux address.

**Comment by frvalenzuela** [comment]
Hola @brayanmoreno !

Lo que mencionas no es posible en los tres ciclos de ejecución. Para que el valor del SP se lo de al BP se requiere de tres ciclos, y luego hacer la suma literal son otros tres ciclos.

Por lo que se debe ejecutar la ALU para cambiar el valor del SP y este mismo sea la dirección que recibe addres para que luego BP sea actualizado con lo que sale de memoria.

Espero que se entienda, si no hacerlo saber.

Saludos!

**Comment by vbarreradg** [comment]
Hola! Entonces cuando en los operandos sale Dir, ¿este va a provenir siempre del Register CU?, y así ¿MuxB va a elegir como entrada a la memoria solo cuando haya una instrucción del tipo Memory[x] = Ax/Bx?
Lo otro, ¿cuál es la diferencia de los operandos Dir y [Dir]? no entiendo bien eso.

**Comment by Arcoirisky** [comment]
Te puedo responder lo último uwu
Ya se ha hablado en varias Issues (mínimo 3) así que si no te queda claro con esto, puedes buscarlas para complementar. 

Básicamente, imagina un Dir que apunta a la dirección 0o0055 y que esa dirección guarda el valor de 0o0003 ¿ok? 

Entonces, si yo hago:

Mov Ax, Dir 

Lo que realmente está pasando es:

Mov Ax, 0o0055 === Ax = 0o0055

Por otro lado, si hago:

Mov Ax, [Dir] 

Lo que hago es tomar el calor almacenado en esa dirección de memoria. Ergo:

Mov Ax, [Dir] === Mov Ax, [0o0055] === Mov Ax, 0o0003 === Ax = 0o0003
