### ISSUE TITLE
3 ciclos

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#151]
![image](https://user-images.githubusercontent.com/24725124/46263347-615ef200-c4e4-11e8-82af-a8619fb000d6.png)

![image](https://user-images.githubusercontent.com/24725124/46263352-7045a480-c4e4-11e8-9681-6a1da963fc99.png)

Dado la arquitectura, y pensando que son tres ciclos. No entiendo como el computador sabe que operación realizar si en el segundo ciclo el literal estaría sobreescribiendo lo que está en el control unit. Es decir, que la intrucción que va a tener el CU va a ser "literalemente" el literal. Se entiende?

**Comment by Geeermy** [comment]
**Cito el enunciado.**

![ups](https://user-images.githubusercontent.com/5559611/46263918-4a240280-c4ec-11e8-918f-e59dca72c614.png)

**Comment by movaldivia** [comment]
Si toda la razón, gracias!
