### ISSUE TITLE
Tarea 3 | Pregunta 1.1 | Funcionamiento de un ADD A,(v1)

### ISSUE THREAD

**Issue by fncabrera** [IIC2343/Syllabus#152]
Hola,

Esta duda en realidad es de materia general de pipelining. 
Se que para un MOV A,(v1) el funcionamiento es como se muestra a continuación (diapo 33 clase pipelining): 
![image](https://user-images.githubusercontent.com/30879712/85369161-930abe80-b4fa-11ea-981d-2faa9f7e4a2c.png)

Sin embargo, para un ADD A,(v1) no me queda claro, debido a que cuando este en la ALU, esta aún no conocerá el valor de v1 a sumar (solo su dir), y una vez que llega a MEM y lo conoce, ¿como es que lo suma con A? 

Agradecería mucho la aclaración,
pd. Creen que será posible subir outputs de ejemplos? en verdad ayudaría mucho a estar seguro de lo programado y la detección de errores considerando la cantidad de casos en los que hay que ponerse.

Saludos! :)

**Comment by jmwielandt** [comment]
Hola,

Con el cambio de ISA esta instrucción ya no corre.
Saludos!
