### ISSUE TITLE
¿Label, Opcode o Literal? [T06-Programación]

### ISSUE THREAD

**Issue by Bipavez** [IIC2343/syllabus#152]
Hola!
Escribiré bien ya que en la issue #149  no pude explicar mi duda, pero tampoco había entendido el enuciado bien.
En el enuciado nos dicen que la declaración de labels es en cualquier parte del código, y que su puntero va a ser la posición después de todas las palabras que le anteceden (en el código _Assembly_). El problema se me produce en el _Disassembler_, en donde no tengo información previa acerca del código _Assembly_ y sus variables. Pongamonos en el siguiente supuesto de código:
```assembly
var1 0
MOV A, B
MOV A, 5
MOV B, 3
ADD A, B
```
Aquí, el puntero sería 0, en #149 era 9. En nuestro _Assembler_ esto resultaría en (asumiendo que ocupo 00000000 como el Lit cualquiera de la memoria):
```
00000000
00000000
00000000
00000010
00000101
00000011
00000011
00000100
00000000
11111111
.......
```
¿Cómo debería el _Disassembler_ actuar?¿Tiene que estar dentro de nuestras suposiciones?¿Eso no daría una evaluación más compleja?
Si quiero podría leer primero la cantidad de líneas para checkear la paridad del mensaje antes del mensaje `NOP`, pero fácilmente podría en mi código ejemplo declarar una cantidad par de labels.
Podría leer jerárquicamente el código, de arriba hacia abajo, a ver que pasa; en este caso el código saliente del _Disassembler_:
```assembly
MOV A, B
;ERROR, la palabra después de "MOV A, B" no es 00000000
```
Pudiera aún asumir que la palabra después de una instrucción que no necesite literales sea basura, en este caso el output sería:
```assembly
MOV A, B
MOV A, B
ADD B, A
MOV B, 4
;ERROR no hay palabra después de la instrucción que sea distinta a 11111111
```
El tema es que podría asumir que ustedes no nos van a dar ejemplos con errores, en cual caso podría rebuscar un código que me genere el código consistente si encuentro una inconsistencia.**Pero necesito restricciones no especificadas en el enuciado**. Pero no puedo, porque estas restricciones pasan sobre lo dicho en el enuciado. 
Asumiendo que _podemos_ aplicar las restricciones.
¿Es este el análisis que esperan de nosotros en la _parte 4_? Si es así ¿Cómo evaluamos nuestro progreso hacia la completitud de la tarea?¿fe en que nuestras suposiciones están correctas?
Mi mayor problema es el del título, no se como diferenciar entre las palabras. El que el puntero de los labels pueda ser menor o igual a los opcodes.  No encuentro nigún patrón para crear mi código. Quizás solo me falta darle más vueltas a la tarea, si es el caso, mil disculpas por preguntar bueno, lo que nos estan preguntando.
Gracias de antemano

**Comment by Geeermy** [comment]
Todo lo que mencionas es el proceso por el que **queremos** que pasen para esta tarea. Piensa lo siguiente: El _Disassembler_... ¿conoce el código original? ¿O solo actúa en base al archivo binario recibido? La pregunta 4 también está por algo.

**No** pueden asumir que no les pasaremos códigos con errores, en el enunciado decimos explícitamente que si no conocen un _opcode_ tienen que escribir un mensaje de error, eso es todo lo que necesitan. Puedes asumir que no te vamos a dar algo que no siga la convención establecida y cosas de ese estilo, pero nada más. **No necesitas más restricciones de las especificadas en el enunciado**.

Lo que quizás te está complicando es que estás pensando en que todo tiene que funcionar de manera perfecta y manejando todas las excepciones entre todas las partes de la tarea. No es así. La diseñamos de esta forma para que vean lo que pasa. Entonces, en lo que respecta a la simulación, preocúpate de realizar todo en base a los 3 ciclos que planteamos en la introducción y, con respecto al _Disassembler_, de ir haciendo la traducción pensando en lo que hicieron en el _Assembler_.

Lo siento si sueno algo "críptico", pero esto es parte de lo que queremos que piensen en la tarea, profundizar más sería empezar a darles la solución.

¡Ánimo! 😄

**Comment by Bipavez** [comment]
Muchiisimas Gracias!
