### ISSUE TITLE
[T03 PLACA] 5ta Entrada MUX Adress

### ISSUE THREAD

**Issue by DaToMC9** [IIC2343/syllabus#152]
Reconectando todos los componentes con respecto al diagrama nuevo, nos encontramos con la siguente duda:
La 5ta entrada al mux adress (imagen 1), parece no venir de ningún lado, ya que al seguirla (imagen 2) resulta que también es entrada del Register Bx, es decir no es el out de ningún componente, 
¿Qué podemos hacer en este caso? 😕  
![image](https://user-images.githubusercontent.com/37244943/57739261-dac8e080-7680-11e9-8ccf-b6afc90159f8.png)
![image](https://user-images.githubusercontent.com/37244943/57739285-fb913600-7680-11e9-803d-a0ae470e800d.png)

**Comment by frvalenzuela** [comment]
Hola @DaToMC9 !

Debería ser la salida del Registro B, se podría ocupar para una instrucción de direccionamiento por registro. Finalmente no incluimos ese tipo de instrucciones en la ISA de la tarea, así que no deben preocuparse mucho por esa señal.

Saludos!
