### ISSUE TITLE
Formato entrega tarea 3 y 4

### ISSUE THREAD

**Issue by nmaturana97** [IIC2343/syllabus#153]
Hola, para la tarea 3 subi mi tarea en la carpeta solucion. Me dijieron que suba una issue para recordarles esta situacion y que arreglara eso para la tarea 4. Ya deje el archivo de la tarea 4 en el directorio principal de la rama master. Igualmente añadi la situacion al readme de dicha tarea. Gracias.

**Comment by jheysen** [comment]
En los repos de tus tareas...
