### ISSUE TITLE
[T3-Placa] Conectar Placa

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2343/syllabus#153]
Estoy tratando de conectar la placa y no me aparece el basys 3 en la conexión. ¿Cómo podría arreglarlo? El cable está bueno, el problema probablemente tenga que ver con vivado

**Comment by frvalenzuela** [comment]
Hola Juan!

Que sistema operativo tienes?

Saludos!

**Comment by jgespinosa10** [comment]
Windows 10

**Comment by frvalenzuela** [comment]
Hola Juan!

¿Que te aparece cuando intentas hacer Auto-connect?

Saludos!

**Comment by jgespinosa10** [comment]
![image](https://user-images.githubusercontent.com/30691527/57740131-3ea0d880-7684-11e9-958b-8c62d01c183d.png)

Esto es lo que me aparece

**Comment by jgespinosa10** [comment]
Es como si no leyera el basys 3, no lo reconoce. Pero me aparece conectado en devices de windows

**Comment by frvalenzuela** [comment]
Hola Juan!

Lo único que se me puede ocurrir es que la instalación de los controladores no fue la correcta. Intenta desintalarlos e instalarlos como se menciona en este [link](https://www.xilinx.com/support/documentation/sw_manuals/xilinx2018_3/ug973-vivado-release-notes-install-license.pdf)  (página 36)

Si no se soluciona solo recomendaría volver a instalar Vivado.

Saludos!
