### ISSUE TITLE
Tarea 3 | Pregunta 1 | Preocupación sobre pregunta

### ISSUE THREAD

**Issue by cacosandon** [IIC2343/Syllabus#153]
Hola!

Tengo muchas dudas y preocupaciones con respecto a la pregunta 1 (1.1 y 1,2). Se entiende completamente que el cuerpo docente esté colapsado (tod@s lo estamos), pero al menos en mi caso no he podido desarrollar bien la tarea por la cantidad de casos que existen en los outputs.

Entiendo también que no exista un código pauta que resuelva estas preguntas (si existiera sería fácil generar tests), por lo que al mismo tiempo creo que no se ha tomado conciencia sobre la cantidad de situaciones y variables que lo incluyen (claramente existen muchos casos diferentes en donde se efectúan los hazards).

Obviamente sería buena solución aumentar el plazo de la tarea (no para l@s estudiantes, si no que para que haya tiempo de generar tests), pero al menos para mi caso ya no puedo dedicarle más tiempo a esta tarea en la semana.

Lamentablemente esto afecta en el aprendizaje más que en la nota de mi tarea, dado que la única forma de saber en un futuro si lo que aprendí estaba bien o mal será con la nota, y no creo que me de el tiempo de revisar una pauta completamente distinta (si es que lo es) para detectar qué estaba bien o qué estaba mal entre tanto caso.

Eso, la verdad es que no sé si exista una solución para esto o si realmente están de acuerdo conmigo, pero creo que esta era la mejor forma de expresarlo.

Saludos!

**Comment by Cadagan** [comment]
Sumándome a las palabras de @cacosandon , siento que he aprendido mucho en clases, que entiendo muy bien pipeline y que hasta incluso he repasado varias veces los contenidos para hacer la tarea, sin embargo, siento que hay tantas interpretaciones distintas a las instrucciones que hay, tanto en el enunciado como en la totalidad de la issues, que pase lo que pase no podré optar a un buen resultado, a pesar de haberme esforzado mucho.
Me da pena no poder demostrar todo lo que he aprendido, espero podamos llegar a una buena solución para este problema. 😔

**Comment by jmwielandt** [comment]
Discutiremos las opciones de dar más plazo, pero de momento les puedo comentar cómo modelar el problema para que les salga más fácil el análisis de casos.

> Tomemos una instrucción arbitraria. Esta instrucción requiere leer ciertos valores (memoria, registros, etc) y escribir otros (memoria, registros, etc). Entonces para cada instrucción podemos tener ciertas "dependencias" (cosas de las que depende para poder trabajar) y valores en los que escribe.
>
> Si hacen una función que recibe una instrucción y retorna estos datos en un diccionario, luego sólo les queda cruzar la información de la instrucción que estén mirando con las dos anteriores (por la profundidad del pipeline) para poder detectar los hazards (les recomiendo partir por la inmediatamente anterior y luego, de ser necesario, ir a la que estaba antes de esa).
>
> Con eso + la información del tipo de dependencia, determinar qué forwarding unit es. Piensen que la dependencia se da cuando escribí un valor que no he alcanzado a escribir luego, ese es el que tengo que traer a donde lo necesito. También sigan los cables y miren las señales del diagrama para poder ver bien en qué casos actúa cada una.

### En todo caso, si están cortos de tiempo les recomiendo ir directo a la de Pipeline II que es significativamente más corta y sencilla que la de Pipeline I, al menos para lo que es la tarea con nota.

Para la pregunta 3 de caché, sólo necesitan mirar los MOVs que usen memoria (tanto lectura como escritura).

**Comment by cacosandon** [comment]
Hola @jmwielandt 

Intenté hacer la pipeline II porque se veía más fácil, pero hasta ahora sigo sin poder hacerla porque no sé qué piden.

Issue #136
![image](https://user-images.githubusercontent.com/30879716/85427762-37682180-b54a-11ea-9daa-eb6f7b262421.png)

Issue #134
![image](https://user-images.githubusercontent.com/30879716/85427859-5797e080-b54a-11ea-82ff-8cdb4b033661.png)

Siento que se contradicen ambas respuestas, donde no necesariamente se pierden 3 instrucciones si siempre se equivoca..

**Comment by jmwielandt** [comment]
Si predigo mal el salto, ¿cuántas instrucciones perdí?

**Comment by clementeross** [comment]
Yo estoy de acuerdo con @cacosandon. Hay casos en que una mala predicción puede ocasionar perder menos de 3 instrucciones.

A modo de ejemplo, supongamos que el programa tiene 29 instrucciones (el PC de la última instrucción será 28).
Supongamos el programa tiene la instrucción JEQ 28 y asume el salto. Como siempre se equivoca, el programa no salta, y por lo tanto perdería solo una instrucción: la que tiene PC = 28, que corresponde a la última.

Estoy bien?

**Comment by jmwielandt** [comment]
🤔 🤔 🤔 🤔 🤔 🤔

Si predices que saltas al 28 igual tienes que esperar los 3 ciclos antes de asegurarte de que terminó el programa y en ese caso podemos tomar esos ciclos perdidos como NOPs (que son instrucciones al fin y al cabo), y eso seguiría siendo perder 3 instrucciones. Entiendo por donde vas pero no te sobrecompliques las cosas.

**Comment by clementeross** [comment]
Ok perfecto! Muchas gracias!
