### ISSUE TITLE
[T3- Programada] Valor pc con RET, simulador

### ISSUE THREAD

**Issue by Jj1martinez** [IIC2343/syllabus#154]
Hola, me surgió una duda con respecto al ejemplo de la tarea. Cuando corro el simulador con ese código, al llegar al RET debería ir a buscar el valor Memory[SP] pero como aquí no hay un CALL para llamar a la función por lo queno poseo ningún valor para asignarle a pc. En un caso como este, donde no haya nada guardado en el stack, que se debe hacer con respecto a pc y las proximas lineas del simulador? 
Debo dejar los valores como quedaron y que el pc continúe hasta el límite de memoria?

**Comment by tomasrivera** [comment]
Hola, sin importar el contexto en que se ejecuta la instrucción, se espera que esta realice lo que esta debe hacer. 

Es importante notar que el _stack_ está contenido en la memoria principal y por lo tanto siempre existirán valores para cualquier posición del `SP`.

Que lo anterior tenga sentido, va a depender del contexto, y de lo que se busca. Pero ten en cuenta que si un eventual programador se equivoca en el "código" el comportamiento debe verse reflejado en la simulación.

**Comment by Jj1martinez** [comment]
Pero en el ejemplo, ese RET estaría erréneo?
