### ISSUE TITLE
Sintaxis para saltos T06- Programación

### ISSUE THREAD

**Issue by felipesilvadv** [IIC2343/syllabus#154]
Hola! tengo una duda respecto a los labels que se usarán demarcar los saltos dentro del código assembly y como se diferenciarán de los label de variables, tengo que determinarlo yo o será de la forma que vimos en clases, o sea usando un ":" después del nombre del label?

Algo así me refiero

```assembly
salto1: MOV A,var1 
ADD A,B
CMP A,2
JEQ salto1
var1 0
```

**Comment by FranLucchini** [comment]
Sí, van a ser labels _inline_.

**Comment by jheysen** [comment]
Serán como los vistos en clase.

**Comment by felipesilvadv** [comment]
Okey! muchas gracias !!

**Comment by felipesilvadv** [comment]
Me surgió otra duda, en el mismo ejemplo que di, que literal debiese considerar para la primera línea (el que irá en la segunda línea del output en la parte 1), el del label de salto o la posición del label var1?
(Se que en ese ejemplo específico coinciden y debería poner literal 0, mi duda va para el caso que no coincidan)

**Comment by Bipavez** [comment]
Me sumo con otra pregunta, para la transformación a palabras cómo deberíamos proseguir?
Un ejemplo:
```assembly
main : MOV A, (var1)
MOV B, (var2)
ADD A, B
JMP main
var1 0
var2 1
```
Se traduciría en:
```
00000000 -- Valor de main???
00100111 -- Opcode MOV A, (dir)
00001001 -- Puntero de var1
00101000 -- Opcode MOV B, (dir)
00001010 -- Puntero de var2
00000100 -- Opcode ADD A, B
00000000 -- Basura
00011110 -- Opcode de JMP dir
00000000 -- Puntero de main
00000000 -- Valor de var1
00000001 -- Valor de var2
```
Sería así?

**Comment by Geeermy** [comment]
@Bipavez El valor de ```main``` de la primera línea de tu traducción es innecesario. Basta con que el literal de la instrucción de salto tenga el puntero correspondiente (que corresponde a la posición de la primera instrucción indicada por el _label_, en este caso ```main```). 🌝

**Comment by acrojas2** [comment]
@Geeermy no entendí tu explicación a la duda de @Bipavez , puedes explayarte un poco mas? En particular no entiendo que debe aparecer en la linea 1 de su ejemplo. Tampoco entiendo a qué te refieres con que el literal de la instrucción de salto tenga el puntero correspondiente, dónde y cómo se refleja eso en el archivo de salida?.
 No entiendo lo del literal, lo que yo entendia era que con JMP se salta a la direccion correspondiente, pero en este caso el _label_ representa esa dirección en memoria, pero cómo sé cual es esa dirección en memoria.
Saludosc confusos 😕 !

**Comment by Geeermy** [comment]
@acrojas2 En el ejemplo, se corre todo para arriba una posición, ya que los _labels_ de salto **no guardan un literal en la memoria principal.**

Por otra parte, el literal que utilizan las instrucciones de salto a determinado _label_ hace referencia a la primera instrucción proveniente de este. Es decir, el literal será igual al número de la **línea** del _opcode_ correspondiente a la primera instrucción asociada al _label_ referenciado. Por ejemplo, en el caso del ejemplo dado por @Bipavez se tiene esto:

```
00100111 -- Opcode MOV A, (dir)
00001001 -- Puntero de var1
00101000 -- Opcode MOV B, (dir)
00001010 -- Puntero de var2
00000100 -- Opcode ADD A, B
00000000 -- Basura
00011110 -- Opcode de JMP dir
00000000 -- Puntero de main
00000000 -- Valor de var1
00000001 -- Valor de var2
```

Puntero de _main_ = 0 dado que en esa línea de la memoria se ubica el _opcode_ de la primera instrucción bajo el _label_. Ahora, si tuviéramos esto:
```
MOV A, (var1)
main: MOV B, (var2)
ADD A, B
JMP main
var1 0
var2 1
```

Entonces, tu memoria se va a ver así:

```
00100111 -- Opcode MOV A, (dir)
00001001 -- Puntero de var1
00101000 -- Opcode MOV B, (dir)
00001010 -- Puntero de var2
00000100 -- Opcode ADD A, B
00000000 -- Basura
00011110 -- Opcode de JMP dir
00000010 -- Puntero de main
00000000 -- Valor de var1
00000001 -- Valor de var2
```

Ahora, puntero de _main_ = 2 dado que esa es la posición del _opcode_ de la primera instrucción perteneciente al _label_ (ojo que es 2 porque asumimos que se parte de la posición 0).

Finalmente, para conocer el valor de los punteros, tendrías que encontrar una forma de _parsear_ el código para determinarlo. No te puedo dar una solución porque es parte de lo que ustedes tienen que hacer, pero entendiendo lo que dije deberías pillar la forma.

¡Ánimo! 😃

**Comment by jheysen** [comment]
Se corrió en 1

**Comment by Geeermy** [comment]
Lo siento, toda la razón. Hice _copy-paste_ directo y no me di cuenta de ese detalle. Lo dejé corregido para no causar dudas. 😀

**Comment by acrojas2** [comment]
@Geeermy creo que tengo dudas serias:

- No entiendo cuando se pone un literal seguido de una instrucción, siempre? 

- Que pasa en el caso que haya un MOV A,B sin antes haber hecho MOV A, Lit(o (dir), ...) y MOV B,Lit(o (dir), ...)?

- Porque en la linea que sigue a ADD hay que poner basura? pasa lo mismo con SUB? con que operaciones más pasa eso? 
No entiendo la lógica la verdad.
Saludos más confusos que los de ayer...

**Comment by Geeermy** [comment]
* En nuestro caso, siempre, ya que toda instrucción **debe** estar acompañada por un literal tal como lo vimos en clases con el computador básico, sin importar si la instrucción hace uso de este o no.

* Puedes asumir que los registros parten en cero. Entonces, si haces MOV A,B inicialmente tendrás entonces que: A = B = 0.

* Porque estas instrucciones no hacen uso del literal. Da lo mismo el valor que pongas, aunque se propague por la máquina este **no debiese** afectar el resultado de la instrucción. Si lo hace, es porque algo está mal implementado.

* No, porque se apunta **a la primera instrucción que pertenece a _main_** y no a _main_ per se. _main_ es solo un _label_ de referencia para decir desde dónde parte una sección de código, no ocupa espacio en la memoria porque no serviría de nada tenerlo, te basta con conocer la ubicación de la primera instrucción que está bajo él.

**Comment by acrojas2** [comment]
@Geeermy  + DUDAS que me han surgido:

- Para el caso de Mov A, (B) que se pone como literal en la linea siguiente?
- Misma pregunta para INC(B)
- Misma pregunta para NOP
- En las instrucciones AND, XOR,...,OR tampoco se hace uso del literal igual que en ADD y SUB? Quizas mi duda tiene mas que ver con cómo me doy cuenta que se usa el literal.
- Se puede asumir que las variables y labels a las que hacen alusion las instrucciones siempre están en alguna parte del archivo?

**Comment by Geeermy** [comment]
@acrojas2 Para los primeros cuatro puntos, la respuesta es la misma: el literal puede valer lo que sea (generalmente 0), ya que no se utiliza en ninguna de las instrucciones. El literal lo usas explícitamente cuando la instrucción usa "Lit" o cuando usa una dirección (ya sea variable de memoria o instrucción de salto). 

Con respecto al último punto: sí, puedes asumirlo. :-)
