### ISSUE TITLE
Variables assembler

### ISSUE THREAD

**Issue by NotSimple** [IIC2343/syllabus#154]
Hola,
si tenemos el siguiente codigo assembly:
```
DATA:
v1 5
CODE:
MOV A, (v1) // esto es operacion MOV A,dir    dir = valor de Mem[0]?
MOV A, v1 //  esto es operacion MOV A,lit       lit = valor 5?
```
Esta bien?
Gracias!

**Comment by Hernan4444** [comment]
@NotSimple es ese caso A primero toma el valor de 5 y luego toma el valor de 0. Imagina que v1 es el indice en una lista de array y tu lista es la ram,
En el primer caso estás haciendo ` A = RAM[v1] = Ram[0] = 5`.
En el segundo caso estás haciendo `A = v1 = 0`.

Ojala se entienda ahora la diferencia ✌️ 
Saludos!
