### ISSUE TITLE
Tarea 3 | Pregunta 3 | Clarificación FIFO

### ISSUE THREAD

**Issue by acpopper** [IIC2343/Syllabus#155]
Hola!
Solo queria una pequeña aclaracion. 
Entonces el reemplazo es por FIFO pero independiente en cada conjunto?
Es decir, cada uno de los 2 conjuntos tendrá dos bloques, cada uno con sus 4 direcciones, y al reemplazar, por ejemplo, en el conjunto 1, se reemplaza entonces el bloque mas antiguo?
Gracias de antemano!

**Comment by ceosorio** [comment]
Hola @acpopper!

Exacto! :smile:  Si aun tienes dudas, te recomiendo revisar la issue #144 donde hay un ejemplo, o volver a preguntar por acá :3

Ánimo! :sparkles:
