### ISSUE TITLE
Bonus Disassembler

### ISSUE THREAD

**Issue by lootarola** [IIC2343/syllabus#155]
Para el Bonus del disassembler debo guardar las variables en Datos solo si se ejecuta la operación MOV? O también debo guardar los resultados de las operaciones?

**Comment by Hernan4444** [comment]
@lootarola podrías dar un ejemplo a qué te refieres?? Me suena a que no debes guardar las operaciones pero preferiría saber bien a qué te refieres.

Quedo atento a tu comentario.

**Comment by lootarola** [comment]
Si en el archivo se me indica la operación ADD por ejemplo ¿Debiese escribir en datos una var_x = 'resultado de la operación' o solo escribo variables en datos si se ejecuta exclusivamente la operación MOV?

**Comment by Hernan4444** [comment]
@lootarola un caso así no va a ocurrir 👍. En el enunciado se especificó que el patron solo involucra `MOV A ; Lit, MOV (i),A con i desde 0 hasta el número de variables.` Por lo tanto, si vez una operación es que ya se terminó la sección de DATA.

Ps: No olvides la aclaración del `MOV A,0` que hicimos en la página 5, te puede ayudar a guiarte.
Saludos
