### ISSUE TITLE
Pregunta 9.a III | Código para controlar el funcionamiento de la impresora

### ISSUE THREAD

**Issue by viantirreau** [IIC2343/Syllabus#156]
Hola!

Podemos programar esta parte en código Python-like, donde se usen funciones para cada operación (y tal vez aprovechar el valor de retorno para las operaciones _fetch_)?

Gracias desde ya!

**Comment by jmwielandt** [comment]
Hola, hazlo más parecido a C, lo más bajo nivel posible en un lenguaje de alto nivel.

**Comment by viantirreau** [comment]
Bacán, muchas gracias!
