### ISSUE TITLE
registro CU no me esta pasando ningun input

### ISSUE THREAD

**Issue by rjdelrio** [IIC2343/syllabus#156]
yo creo que me debo estar equivocando en un tontera pero he estado intentando hacer cruzar bites por el registro CU y no he podido, entonces me puse a ver el código de registroCU y me di cuenta que la variable cargar jamas se le da un valor desde ningún input, podría ser esto un problema ? 

```
entity RegisterCU is
    Port ( clock    : in  std_logic;                        -- Se?al del clock (reducido).
           datain   : in  std_logic_vector (11 downto 0);   -- Se?ales de entrada de datos.
           dataout  : out std_logic_vector (11 downto 0);
           lit : out std_logic_vector (11 downto 0);
           selAddSec      : out std_logic;
           
           stalling      : out std_logic);  -- Se?ales de salida de datos.
           
end RegisterCU;


architecture Behavioral of RegisterCU is

signal reg : std_logic_vector(11 downto 0) := (others => '0'); -- Se?ales del registro. Parten en 0.
signal lit_signal : std_logic_vector(11 downto 0) := (others => '0'); 
signal cargar : std_logic_vector(1 downto 0);
signal mux : std_logic;
signal opcode_signal : std_logic_vector(11 downto 0) := (others => '0');
signal ceros  : std_logic_vector(11 downto 0) := (others => '0');
signal opcode_mux : std_logic_vector(1 downto 0) := (others => '0'); 
signal stop : std_logic := '1';


begin

reg_prosses : process (clock)           -- Proceso sensible a clock.
        begin
          if (rising_edge(clock)) then  -- Condici?n de flanco de subida de clock.
            if (cargar = "00") then
                cargar <= "01";
                stop <= '0';
                mux <= '1';
            elsif (cargar = "01") then
                opcode_signal <= datain;
                cargar <= "10";
                stop <= '1';
                mux <= '1';
            elsif (cargar = "10") then
                lit_signal <= datain;
                cargar <= "00";
                mux <= '1';
                stop <= '0';
            end if;
          else
                -- necesario para poder simular 
          end if;
        end process;

with cargar select
    dataout <=    ceros when "10",
                opcode_signal when "00",
                ceros when "01",
                ceros when others ;

selAddSec <= mux;
stalling <= stop;
lit <= lit_signal;   
end Behavioral;
```

**Comment by frvalenzuela** [comment]
Hola @rjdelrio !

No, no es un problema. Por defecto las señales serán cero cuando son definidas (en el caso de carga será “00” inicialmente), por lo que en process por cada flanco de subida irá cambiado su valor. 

¿A que te refieres con cruzar bytes ? Debería entregarle los inputs correspondientes y con ello darte el output adecuado. 

Si queda alguna duda favor hacerla 

Saludos !

**Comment by Arcoirisky** [comment]
Te puedo jurar, con la mano en el corazón, que el RegCU está perfecto (el nuevo que subió Felipe, del antiguo dudaría 👀)

Cargar si funciona y de hecho, no pusiste la declaración de inputs, outputs O: (al menos en lo que me muestras) quizás solo no estás dando el input en el orden en que va asignando sus bits.

**Comment by rjdelrio** [comment]
hola :D @frvalenzuela 
lo que pasa es que cuando lo simulo me sale que la variable cargar nunca toma valor, por eso te preguntaba nomas, pero si tu dices que por defecto deveria ser "00" te creo, hay alguna manera de decirle explícitamente al programa que esa variable por defecto sera "00"?

**Comment by frvalenzuela** [comment]
Hola @rjdelrio ! 

Si es por simular podrías intentar en la declaración de la señal terminarla con `0) := (others => '0');` 
(Como se ven en todas las otras señales). 

Ojalá te sea de ayuda. 

Saludos. !

**Comment by rjdelrio** [comment]
BUENISIMA ahora si funciono :D

**Comment by frvalenzuela** [comment]
Hola @rjdelrio

Por favor no cerrar las issues. Alguien más podría ayudarle. 

Saludos !

**Comment by frvalenzuela** [comment]
Hola @rjdelrio

Por favor no cerrar las issues. Alguien más podría ayudarle. 

Saludos !
