### ISSUE TITLE
Memoria principal: Datos e instrucciones

### ISSUE THREAD

**Issue by paula-ds** [IIC2343/syllabus#157]
Hola, tenemos 2 dudas sobre la tarea 6 parte práctica:

1. De la memoria principal salen instrucciones y datos, y de alguna forma debemos diferenciar entre estos dos. Hasta el momento no se nos ocurre algo apropiado para solucionarlo, hay algo especial que se deba considerar para hacer esta parte?

2. Debemos asumir que solo habrá un programa en memoria?

Gracias de antemano

**Comment by Geeermy** [comment]
Sobre 1, piensa que siempre se tendrá el par _opcode_-literal, eso debería ayudarte a encontrar un mecanismo que funcione asumiendo eso. Te recomiendo revisar de todas formas la parte programación, algunos de los elementos expuestos ahí te podrían guiar aún más.

Obviamente, no ahondaré en _cómo_ hacerlo, dado que es parte de la evaluación.

¡Mucho éxito!
