### ISSUE TITLE
Archivo . bit T03 [Placa]

### ISSUE THREAD

**Issue by miortiz1** [IIC2343/syllabus#157]
En la tarea dice que debe haber en el  repositorio solo el Readme, el archivo.bit el computador vonTwelve y su carpeta sources?
Sin embrgo, nose me ha creado ningun archivo.bit, ¿que deberia hacer?

**Comment by frvalenzuela** [comment]
Hola @miortiz1 !

Debería haberse creado cuando aplicas Generate Bitstream

Saludos!

**Comment by miortiz1** [comment]
Deberia llamarse bays3.bit? lo encontre, pero estaba dentro de una de las carpetas que no hay que subir

**Comment by tomasrivera** [comment]
Está en runs_1/impl_1 o algo por el estilo

**Comment by tomasrivera** [comment]
Tienes que copiarlo junto con tus _sources_ y subirlo

**Comment by frvalenzuela** [comment]
Hola @miortiz1 !

Ese mismo ! lo puedes copiar y pegar para que quede en el mismo directorio del README

Saludos!

**Comment by miortiz1** [comment]
Okay, gracias!

**Comment by DanielCarrascoFalcon** [comment]
El enunciado dice que hay que subir la carpeta basic_computer.srcs y el archivo basic_computer.xpr
Supongo que deberían ser los archivos VonTwelve.xpr y la carpeta sources del mismo, cierto?
(Es solo para corroborar)

**Comment by frvalenzuela** [comment]
Hola @DanielCarrascoFalcon !

Así es !

Saludos!

**Comment by DanielCarrascoFalcon** [comment]
Ok!
Gracias!

**Comment by sipoblete** [comment]
el archivo.bit con que instrucciones se debe compilar?? Porque si bien entiendo, este archivo cambia segun las instrucciones que se den en main memory

**Comment by frvalenzuela** [comment]
Hola @sipoblete! 

Intenta varias sin algún orden. 

El .bit es para saber que si código compilo alguna vez. 

Saludos !
