### ISSUE TITLE
[T3-Placa] With/select con múltiples condiciones

### ISSUE THREAD

**Issue by atbusch** [IIC2343/syllabus#158]
Hola, por ahora en mi CU estoy manejando todas las instrucciones con un with select que recibe el opcode y entrega todas las señales, pero me di cuenta de que haciéndolo así no estoy considerando que se cumplan las condiciones para los jumps. Esto lo podría arreglar fácilmente haciendo por ejemplo 
`[señal JE] when ([opcode] and [z=1]);`
pero he estado buscando y no pude encontrar si esto es posible, saben si se puede?

**Comment by frvalenzuela** [comment]
Hola @atbusch  ! 

La parte de los jumps tiene distintas formas de solución y es parte de lo que deben saber al hacer una control unit. Se puede hacer con `with/select`. Piénsenlo bien!

Saludos!
