### ISSUE TITLE
[T6 Práctica] Manejo opcodes sin literales

### ISSUE THREAD

**Issue by malopez16** [IIC2343/syllabus#158]
Hola! bajo el supuesto de que tenemos opcodes que no requieren un literal para funcionar, cómo asumimos que se nos entregara el input de la parte practica? (considerando que debe funcionar siempre en tres ciclos) 
gracias!

**Comment by malopez16** [comment]
Presioné enter sin querer. Ya edité el contenido de la issue con mi duda :)

**Comment by jheysen** [comment]
Siguiendo el estándar igual nomás
