### ISSUE TITLE
Duda Labels

### ISSUE THREAD

**Issue by lootarola** [IIC2343/syllabus#158]
¿Mi Assembler debe ejecutar el código de las labels sólo si son llamados por un Jump? ¿O debe ser ejecutado de todas formas con el debido orden?

Ejemplo:
MOV A, 12
MOV B, 13
label1:
MOV A, 15
MOV B, 15

Instrucciones traducidas por el ASSEMBLER:

bin(12)(opcode MOV A, Lit)
bin(13)(opcode MOV B, Lit)
bin(15)(opcode MOV A, Lit)
bin(15)(opcode MOV B, Lit)

O debe ser 

bin(12)(opcode MOV A, Lit)
bin(13)(opcode MOV B, Lit)

**Comment by FranLucchini** [comment]
El Assembler no ejecuta el código, solo lo transforma a lenguaje de máquina. Pero si tu pregunta es si debe incluir lo que viene después de label1, la respeusta es que incluso si no la llama un jump, deben estar esas líneas en el resultado final.

Es importante recordar que el label no genera una sección de código, si no que guarda una referencia a una línea de él cosa de que los jumps puedan ir a esa instrucción. Por eso debe ser como el primer ejemplo que mostraste.

```
bin(12)(opcode MOV A, Lit)
bin(13)(opcode MOV B, Lit)
bin(15)(opcode MOV A, Lit)
bin(15)(opcode MOV B, Lit)
```
