### ISSUE TITLE
[T06][Programado] Dudas varias

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#159]
Hola, quiero ver si entendí bien el enunciado y ver de qué cosas no tengo que preocuparme.

1. Por lo que entiendo, el assembler (& co.) que estamos haciendo es para la arquitectura von neuman, con su isa respectiva (adaptada), no? Lo digo por lo del little endian.
2. En la intro sale que cada instrucción toma 3 ciclos, pero en el ejemplo de la simulación me da la impresión que t cambia en 1 por cada instrucción.
3. Lo de la protección de la unidad de control a literales consiste en que no los interprete como instrucciones, no? ¿Y que el programa no escriba en posiciones usadas por las instrucciones?
4. Por "El archivo de entrada siempre tendrá un formato válido y correspondiente al establecido en este enunciado." ¿puedo asumir que incluye el respeto a las mayúsculas para las instrucciones, un espacio entre una instrucción y sus parámetros y no habrá más que una coma (y nada de espacios) entre los parámetros?
5. En los labels para los saltos, si son varias instrucciones, ¿van a poner tabs/múltiples espacios?
6. **duda importante**, en clases vimos que para von neuman se ponen las variables solo en la parte inferior del assembly pero en el enunciado sale que pueden estar en cualquier lugar. Pensando en el disassembler, ¿las variables también podrán estar en cualquier posición dentro del binario o respetarán lo visto en clases?

Creo que eso es todo, por ahora.
Gracias~

**Comment by jheysen** [comment]
1. No debería importarte el tema del endianess
2. Si, cambia en cada instrucción, es t de tiempo
4. Si bien para algo está el readme, nunca es malo tomar un poco de precauciones.
5. Explícate
6. Lee la parte D.

**Comment by jmwielandt** [comment]
4. Me refiero a que no voy a tener una instrucción `mov a,  b` (puse dos espacios entre la coma y la "b") en vez de `MOV A,B`, por ejemplo. Lo mismo si puedo asumir que los nombres de las variables `var1`o `perro55341243` no tendrán mayúsculas. Tampoco una variable que incluya palabras reservadas, etc.
5. por parte D te refieres al 4? (las preguntas)

**Comment by acrojas2** [comment]
Ya que esta issue es de dudas varias haré mis preguntas acá: 

- Alguien me puede explicar a qué se refiere esta parte del enunciado (ojalá con un ejemplo):
<img width="514" alt="captura de pantalla 2018-10-05 a la s 00 55 32" src="https://user-images.githubusercontent.com/26121354/46515393-f3932d00-c839-11e8-9772-d77b5e6369ae.png">

- el nombre de las variables siempre seguirá la convención _var{n}_

- cuando hay un salto, cómo debe lucir el output (esa parte del archivo de output)?

**Comment by Geeermy** [comment]
@jmwielandt No, no pondremos espacios de esa forma, seguiremos un formato lo más simple posible en ese sentido ya que no forma parte de lo que queremos evaluar. No veo por qué no podrían tener mayúsculas las variables... pero lo que sí no tendrán serán palabras reservadas (no definiremos una variable como "mov", por ejemplo). En lo que respecta al punto 5 (tabs en saltos), ¿podrías dar un ejemplo? Nuevamente, buscamos que sigan una estructura definida y simple, no nos interesa añadir complejidad en ese sentido. Por último, aludiendo al punto 6, pueden salir en cualquier parte, ya que lo estamos explicitando. Leer la parte 4 de preguntas (y responderlas) te dará a entender por qué dejamos  que las variables aparezcan en cualquier parte, buscamos que analicen eso (no ahondaré más por motivos pedagógicos).

@acrojas2 Con respecto al primer punto, te lo contesté en la otra _issue_ (#154). El nombre de las variables no sigue una convención predeterminada, simplemente no posee palabras clave de otras instrucciones (por ej. mov) ni utiliza símbolos que den paso a ambigüedades (por ejemplo, ":", lo que podría hacer pensar que es un _label_ cuando no lo es). Con respecto al _output_, nuevamente, ver #154.

¡Que estén bien! 😄

**Comment by jmwielandt** [comment]
@Geeermy lo de los labels con subrutinas me refiero a algo como
```
MOV A,5
MOV B,8
main: ADD A,B
    ADD B,4
    SUB B,A
MOV (A),B
```
Y replanteo mi pregunta respecto al dissassembler: **¿esperan que el disassembler genere un resultado correcto?**, o, dado el análisis que realicemos, ¿aceptarán que el resultado no sea el correcto?

**Comment by jheysen** [comment]
José, esperamos que el dissassembler haga lo que el enunciado dice que tiene que hacer.
