### ISSUE TITLE
Duda instancia recorrecion del lunes 8

### ISSUE THREAD

**Issue by rsommer1** [IIC2343/syllabus#159]
Que ocurre con el plazo de recorreccion de la segunda entrega? se corre hasta el martes ? o se recolectan los archivos de los repositorios?

**Comment by Hernan4444** [comment]
El plazo de recorrección es desde el lunes 23:59 hasta 2 semanas más a las 23:59. Como el lunes era 25, entonces este lunes 8 de octubre se acaba el plazo, es decir, hasta el lunes 8 - 23:59 tienes para mandar un mail a los ayudantes e indicar que quieres que vuelvan a descargar su repositorio. 

La ultima vez que descargamos los repos fue el martes a las 00:00, si saben que mejoraron algo, manden un mail para que lo mejorado suba su puntaje. 

Saludos ✌️
