### ISSUE TITLE
Entrega 4 | Tabla de verdad Decoder OUT

### ISSUE THREAD

**Issue by fjlopez7** [IIC2343/Syllabus#159]
Todavía no entiendo correctamente la lógica del decoder. Será posible mostrar más ejemplos o parte de la tabla de verdad de esta componente?

**Comment by frvalenzuela** [comment]
Hola @fjlopez7 !!

Disculpa la tardanza en la respuesta primeramente. En segundo lugar, la lógica detras del Decoder es solo un direccionamiento de una señal de carga según la salida dle Mux B. Si por ejemplo tengo que lo que salga del MUX B es 0 entonces la señal de carga del registro display se activará, si la señal del MUX B es 1 entonces la señal de carga del registro led se activará, en otro caso, no se activa ninguna señal de carga.

Aquí va la tabla de verdad.

| ENTRADA | ENTRADA  | SALIDA   | SALIDA   |
|---------|----------|----------|----------|
| MUXB    | LOAD_OUT | LOAD_DIS | LOAD_LED |
| 0       | 1        | 1        | 0        |
| 1       | 1        | 0        | 1        |
| *       | *        | 0        | 0        |

Cualquier duda, comentar.

Saludos!

**Comment by dvogaz** [comment]
Debido a que se toma a mux_b en vez de a reg_b, cuáles tienen que ser los valores del selector de este mux? ya que a priori no sabemos hacia donde tenemos que enviarlo.
