### ISSUE TITLE
 [T3-Placa] Placa no corre código

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2343/syllabus#159]
Hola, tuva muchos problemas conectando la placa, al final tuve que descargar Vivado en linux y ahora la placa me tira este error al conectar y no funciona ningún de los programa y tampoco se muestra nada en display.

![Captura de pantalla de 2019-05-15 14-17-30](https://user-images.githubusercontent.com/30691527/57804640-28992380-7729-11e9-8931-875861dcb5e3.png)

**Comment by frvalenzuela** [comment]
Hola @jgespinosa10 !

No veo ningún error aparente, si no se muestra nada en los display puede ser porque algo no esta bien conectado o la control unit no esta mandando bien las señales.

Saludos!
