### ISSUE TITLE
Y2K38 pregunta escrita 2

### ISSUE THREAD

**Issue by Tito0906** [IIC2343/Syllabus#16]
Holaa! La pregunta pide que mencionemos un caso donde el problema Y2K38 haya generado un error, pero no me queda claro que parte del problema debe haber generado un error. 
No se si me están pidiendo:

- ¿Un caso donde la representación del tiempo en 32 bits con signo haya causado problemas (sea o no el caso específico del año 2038)?

- ¿Un caso específico del año 2038, dejando de lado cualquier problema donde se hayan ocupado 32 bits con signo si no está relacionado con el año 2038?

Agradezco de antemano la respuesta.

**Comment by ceosorio** [comment]
Hola @Tito0906 !

Te recomiendo mirar la issue #10, donde preguntaron por esto por esto mismo en los comentarios. Avisanos si aun quedas con dudas.

Saludos y éxito en la tarea! 😄

**Comment by Tito0906** [comment]
Buenisima! Muchas gracias!!
