### ISSUE TITLE
Problema con el ADD

### ISSUE THREAD

**Issue by hagarces** [IIC2343/syllabus#16]
en mi código utilizo
MOV B, palindromo
ADD B, 0 
MOV A, (B)
y por alguna razón el 0 altera el resultado, alguien sabe cual es la explicación? ;__;

**Comment by nivek0o0** [comment]
Hola, si intentas con 0d en vez de solo 0, ¿funciona bien?

**Comment by Hernan4444** [comment]
@hagarces lo que pasa es que `ADD B,0`  hace B = A + lit y puede ser que antes A tenga otro valor. Por eso altera el resultado.

La recomendación es usar los comandos que están en los apuntes de Hans (capitulo 5.5), pero hay otros comandos que existen que son parte del proyecto, pero que no esperábamos que ocuparan en esta tarea,

Por si acaso te dejo el link al [archivo](https://github.com/IIC2343/syllabus-2017-2/blob/master/Assembler/IIC2343%20-%20Assembler.pdf)

Saludos ✌️

**Comment by hagarces** [comment]
Funcionó! muchas gracias
