### ISSUE TITLE
[Ejercicios Propuestos] Cantidad de registros disponibles 

### ISSUE THREAD

**Issue by Bizama** [IIC2343/syllabus#16]
Hola! 

Tenia una duda con el primer ejercicio (que te piden guardar los siguientes n números en los espacios de memoria a partir de un número K) sobre cuántos registros podemos usar, consideramos 4 como en la ayudantía o los que queramos? 

Saludos!

**Comment by Arcoirisky** [comment]
Consideren 4 registros a menos que se indique lo contrario :D

**Comment by Bizama** [comment]
Muchas gracias!

**Comment by Arcoirisky** [comment]
@Bizama Actualicé la respuesta, perdona por el error :'c
