### ISSUE TITLE
Como compilar Vivado

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2343/Syllabus#16]
Hice todo lo del Tutorial___Vivado___Crear_proyecto, pero no sé como correr lo que hice en la placa?

**Comment by jjaguillon** [comment]
Para enviar a la placa:

- Debes presionar la opción: Generate Bitstream. Esto generará un archivo `.bit`

- Luego debes abrir el: Hardware Manager y autoconectar la placa

- Finalmente, debes presionar la opción program hardware, y seleccionar el archivo `.bit` generado en el primer paso

**Comment by Ignacioislae** [comment]
Me funciono! Gracias!!

**Comment by frvalenzuela** [comment]
Hola @Ignacioislae !

Por favor no cerrar las issues, porque tu duda podría ser útil a otra persona! También agregar que se subió un tutorial más ilustrativo para compilar a la carpeta Tutoriales por si alguien no logro entender las instrucciones expuestas más arriba por Juan.

Saludos!

**Comment by Ignacioislae** [comment]
Dale, perdón por no saber jeje

**Comment by Snorlax8** [comment]
Hola! Seguía el tutorial de cómo compilar Vivado, pero no logro pasar del auto connect:

![image](https://user-images.githubusercontent.com/14048037/63643571-225c0100-c6a1-11e9-8cbd-12853308efd3.png)

Me muestra "Connecting to hw_server" eternamente y nunca se desbloquea la opción de Program Device. ¿Alguna idea de qué puede ser?

Muchas gracias!

**Comment by Snorlax8** [comment]
Hola de nuevo! Lamentablemente después de un rato volví al mismo problema anterior (no logro nunca hacer la conexión y, por lo tanto, no puedo hacer Program Device) y ahora sí que no sé qué puede ser, porque la placa está conectada y con el Jumper 1 cómo corresponde. ¿Alguna idea? Lo único más que puedo mencionar es que la placa que me dieron es ultra mañosa para conectarse, hay que mantener el cable USB presionado constantemente para que se logre mantener encendida.

![image](https://user-images.githubusercontent.com/14048037/63644227-d9607880-c6b1-11e9-9883-0f955e8458cc.png)

**Comment by fedetaladriz** [comment]
Hola @Snorlax8 ! 

Lo pudiste solucionar? Estoy con el mismo problema ahora.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @fedetaladriz ! 

Descargaste los controladores necesarios para la conexion a la placa ? 

Quedó atento a tu respuesta. 

Saludos !

**Comment by Snorlax8** [comment]
Hola @fedetaladriz! 

En mi caso, el puerto de la placa estaba con problemas. Después de un par de cambios de cable micro usb (con el que me entregaron, la placa no encendía y con otro que probé, encendía pero Vivado no la reconocía) logré que el programa reconociese a la placa, dejando el cable en una posición media extraña.

Saludos!

**Comment by fedetaladriz** [comment]
Hola @frvalenzuela ! Si, descargué los controladores. Hice todos los tutoriales al pie de la letra :/ Corrí los comandos nuevamente y me tiró que ya estaban correctamente instalados. 
@Snorlax8 no recuerdas que numero de placa te tocó? Quizas tengo esa misma.

**Comment by Snorlax8** [comment]
Hola!

Mil disculpas la demora. Si mal no recuerdo, trabajé con la placa número 10.

Saludos!
