### ISSUE TITLE
Literal, ¿contiguo o abajo?

### ISSUE THREAD

**Issue by Vicentevialpaul** [IIC2343/syllabus#160]
Hola! tengo una duda respecto al enunciado, en la primer parte se nos dice que el literal está en la palabra contigua al opcode:
![captura de pantalla 2018-10-05 a la s 13 55 43](https://user-images.githubusercontent.com/30669451/46548635-05121e80-c8a6-11e8-9b91-232d121925ca.png)
Y luego en la parte de programación nos dicen que el literal de un opcode va en la posición de memoria siguiente:
![captura de pantalla 2018-10-05 a la s 13 55 13](https://user-images.githubusercontent.com/30669451/46548654-13603a80-c8a6-11e8-8214-da4f5001bf22.png)

Luego, ¿como vendría dado el literal  y el opcode? ¿los 2 en la misma palabra ó primero el opcode en una palabra y luego el literal en la próxima palabra?

Muchas gracias!

**Comment by Geeermy** [comment]
¡Hola!

Debes notar que la memoria principal hace uso de palabras de 8 bits. Como tanto el _opcode_ como los literales ocupan 8 bits, no es posible que se ubiquen ambos en una misma palabra. Si ves más _issues_, podrás notar que hay varios ejemplos donde se muestra la estructura (incluso en el mismo enunciado se deja un ejemplo de la versión binaria de un código).

¡Éxito!

**Comment by Vicentevialpaul** [comment]
Muchas gracias!!
