### ISSUE TITLE
Entrega 4 | Señales de control instrucciones OUT 

### ISSUE THREAD

**Issue by nbnavarro** [IIC2343/Syllabus#160]
Hola!

Para las entregas anteriores podíamos usar la tabla de señales de control que estaba en los apuntes oficiales, pero lamentablemente no aparecen las instrucciones OUT que debemos realizar en esta entrega. 
¿Es posible que nos den la información de todas las señales de control para las 4 nuevas instrucciones OUT? Siento que ayudaría mucho a entender con claridad qué hace cada instrucción. 

Muchas gracias de antemano

**Comment by frvalenzuela** [comment]
Hola @nbnavarro !

Parte del trabajo que se espera es que puedan deducir que señales son las necesarias de activar para ejecutar dichas instrucciones. Recomiendo revisar #159 

Saludos!
