### ISSUE TITLE
[T03 Placa] SelAddSec RegisterCU

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2343/syllabus#160]
Hola,

En el registerCU hay una salida llama selAddSec pero no entiendo ni como calcularla ni a donde se conecta, ya que en el diagrama no la encuentro, por lo que quería preguntar que es.
Saludos
![image](https://user-images.githubusercontent.com/26437497/57805958-1bc9ff00-772c-11e9-988b-133bd333f867.png)

**Comment by frvalenzuela** [comment]
Hola @Jiruiz2 !

Algo que no deben ocupar, conéctenla a una señal que no haga nada.

Saludos!
