### ISSUE TITLE
Mux In entrega 3

### ISSUE THREAD

**Issue by Mapuentes** [IIC2343/syllabus#161]
No me queda muy claro lo del mux In, de donde sale el literal ni para que sirve, ni el sw. Gracias

**Comment by Mapuentes** [comment]
y que se refiere en el puerto con (*) con input "nada"

**Comment by FranLucchini** [comment]
Saludos,

El Mux IN recibe el literal desde el literal de la ROM, ya que la instrucción asociada es IN Reg, Lit. El puerto con (*) se refiere a que en esos puertos no entra nada, lo importante es que el selector del MuxIN es el literal completo, pero sólo usan el 0 y el 1 y de 2 a FFFF están desocupados.

**Comment by dalliende** [comment]
Sigo sin entender, como mostramos que input estamos dando con los botones?. Y el literal que entra al muxin se utiliza solo para escojer el puerto?.

Saludos

**Comment by FranLucchini** [comment]
El output del MuxIN va hacia el MuxA. Entonces, para mostrarlo, deben usar el selector de los botones para el MuxIN y el selector de la entrada que sobraba del MuxA. El resto lo deben pensar ustedes.

Sobre la segunda pregunta, el literal es como mencionas, se utiliza para escoger el puerto.

**Comment by frvalenzuela** [comment]
En caso de que la instrucción del programa 7 del ejemplo que esta en documento de la entrega 3; 
`IN A,2 // Nada a A`
¿Se podría considerar esta instrucción equivalente a un NOP? ¿O en A se guarda cero?

Mi problema es que "Nada" es ambiguo, no se si se refiere a solo ceros  o algún valor desconocido.

**Comment by FranLucchini** [comment]
No pueden considerar que es un NOP, lo más correcto sería que se guardaran ceros.
