### ISSUE TITLE
PLACA T03

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#161]
Hola , me pueden ayudar con esto, no entiendo q pasa! llevo mucho rato y no puedo gracias

![image](https://user-images.githubusercontent.com/20804346/57817472-87709400-774d-11e9-9c0f-bd50ba59b7dd.png)

**Comment by frvalenzuela** [comment]
Hola Nicolas ! 

A que conectaste selAddSec ? 


Saludos !

**Comment by NicolasAguirre** [comment]
@frvalenzuela a un '0' (que lo declare antes), pero lo elimine y recien me compilo (no se si sirve)

**Comment by NicolasAguirre** [comment]
@frvalenzuela nop, no me compila me tira otro error jjajajaja

**Comment by NicolasAguirre** [comment]
![image](https://user-images.githubusercontent.com/20804346/57818836-c73a7a00-7753-11e9-8f74-9bb1f9b6c35c.png)

**Comment by frvalenzuela** [comment]
Hola Nicolas ! 

Conecta una señal definida en la parte de las signals! SelAddSec es un output por lo que debe ser conectado a una señal. Dicha señal no debería ser utilizada para nada más. 

Saludos !

**Comment by NicolasAguirre** [comment]
@frvalenzuela ya lo hice e igual no funcionaba! por otro lado borrandolo me funciona ahora! (no se si dejarlo asi no mas, para probar algo ajjaj)

**Comment by frvalenzuela** [comment]
Hola Nicolas !

Me parecería extraño que no te funcionara al conectarle una señal sin interacción. Recomiendo igual revisar que todo este bien  conectado. 

Saludos !

**Comment by NicolasAguirre** [comment]
@frvalenzuela yaa, muchas gracias! voy a intentarlo!
