### ISSUE TITLE
Direccionamiento var1 0

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2343/syllabus#161]
Hola, qué tal? 
Tengo una duda con respecto a la "var1 0". ¿Esta indica que en la dirección var1 está el valor 0 o me equivoco? y si es así, en qué posición de la memoria iría guardada? ¿a continuación del opcode "00101001" - es decir en la posición 00000111- o en otro segmento especializado para "datos" - dividir las posibles 256 palabras entre 128 para opcode y 128 para datos-? 
![43124958_248390675860596_5277598849173553152_n](https://user-images.githubusercontent.com/26261777/46550674-1c540a80-c8ac-11e8-82a6-55ee10ea925c.png)

**Comment by Geeermy** [comment]
Hola, **en el mismo enunciado y en la misma página del código que mandaste** hay un ejemplo de cómo se vería el código en binario. Te darás cuenta que se pone justo después del _opcode_ y literal de la última instrucción del ejemplo. Si hubieran más instrucciones abajo, quedaría entre medio simplemente haciendo uso de una única palabra en la memoria principal.

**Comment by nfbalbontin** [comment]
Ohh... verdad, es que me estaba fiando del otro ejemplo. Gracias!
