### ISSUE TITLE
Entrega 4 | Conexión Registros y displays

### ISSUE THREAD

**Issue by nbnavarro** [IIC2343/Syllabus#161]
Hola!

En las entregas pasadas existía una conexión directa entre los registros y los displays, esa conexión debe deshacerse para esta entrega, cierto?
Tengo la duda, porque me imagino que ahora los displays A, B, C y D deben estar solo conectados al Reg Dis

Gracias de antemano

**Comment by frvalenzuela** [comment]
Hola @nbnavarro !

Como dices anteriormente, la conexión de los display es a este nuevo registro Dis, no hay conexión directa con los registros A y B a ningún dispositivo de output.

Saludos!
