### ISSUE TITLE
Entrega 4 | Mapeo RegistroLeds-Leds

### ISSUE THREAD

**Issue by cjones27** [IIC2343/Syllabus#162]
Hola!

En la entrega, cómo se conecta el cable de salida de leds a los leds de la Basys? Mi pregunta va a que el cable es un vector de 16 bits pero en la placa solo tenemos 15 leds y por lo tanto nos falta una led para conectar el bit faltante del vector. Por lo que sé no se pueden poner más leds en el archivo Basys3.xdc.

Gracias de antemano

**Comment by frvalenzuela** [comment]
Hola @cjones27 !

Para ocupar las 16 leds en el archivo `.xdc` se debe tener lo siguiente:

```
## LEDs
set_property PACKAGE_PIN U16 [get_ports {led[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
```

Aunque debo recalcar que para la sintesis y simulación el archivo `.xdc` no es considerado, por lo que puedes obviarlo si lo estiman conveniente.

Saludos!

**Comment by quememo** [comment]
Probé eso y me arroja un error, en el archivo sale ledn en vez de led[15]
```
set_property PACKAGE_PIN L1 [get_ports {ledn}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ledn}]
```

**Comment by frvalenzuela** [comment]
Hola @quememo !

Cambia el valor de n por 15 y no debería arrojar error.

Saludos!

**Comment by quememo** [comment]
Lo probaste? A mi no me funciona

**Comment by frvalenzuela** [comment]
Hola @quememo !

Si, aunque no fui lo suficientemente preciso, el cambio de esas dos líneas debería ser así:

```
set_property PACKAGE_PIN L1 [get_ports {led[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
```

Si todavía persiste el error favor comentar.

Saludos!

**Comment by cjones27** [comment]
@frvalenzuela me acuerdo haber cambiado a principio de semestre ese n por 15 y no se podía porque esos representan leds físicos de la placa y el led 15 no existe físicamente en la placa, por lo que entendí del primer taller. Esos archivos .xdc son específicos para cada placa y creo que no se pueden modificar.

**Comment by frvalenzuela** [comment]
Hola @cjones27 !

Los constrains son un conjunto de comandos que ejecuta Vivado en el Tcl Console, y la placa cuenta con 15 leds así que no tendría problema. Si hay un error, puede darse en como modificar el n, haciendo referencia a la posición 15.  Puedo asegurar que esa parte en el archvio de constrains es correcta.

Saludos!

**Comment by cjones27** [comment]
Buenisimo! Funciono. Gracias!
