### ISSUE TITLE
no me deja instanciar un componente

### ISSUE THREAD

**Issue by rjdelrio** [IIC2343/syllabus#162]
tengo que instaciar el pc completo en la basys3 pero por alguna razon me dice que no es un subprograma:
![image](https://user-images.githubusercontent.com/26306472/57819076-c8b87200-7754-11e9-9ba7-b551cfbd898d.png)
 aqui esta la otra parte del componente:
![image](https://user-images.githubusercontent.com/26306472/57819136-1339ee80-7755-11e9-9eb3-b9f6df0f79e5.png)

**Comment by frvalenzuela** [comment]
Hola @rjdelrio ! 

Puede ser que ocupas componentes que se ocupan en ambas entidades de la misma manera. Intenta evitar eso. 

Saludos !

**Comment by rjdelrio** [comment]
buenisima eso funciono bien :D
