### ISSUE TITLE
Botones input entrega 3

### ISSUE THREAD

**Issue by jisilvamc** [IIC2343/syllabus#162]
Hola, me queda la duda de como funciona el tema de IN con los botones... ¿la idea es que cuando aparezca una instrucción así tomemos los valores de los botones y los usemos como un literal de 5 bits? En ese caso, ¿habría que mantener los botones apretados hasta que llegue esa instrucción, para que cuando llegue esté listo el input? ¿Los otros 11 bits serían 0s?
Gracias de antemano

**Comment by FranLucchini** [comment]
Hola, 
Es como tú lo mencionas. Si sabes que viene un IN que quiere guardar el valore de los botones, debes mantenerlo apretado hasta que se guarde. También, como mencionaste, los valores de los botones son sólo 5, por lo que debes rellenar con 0s en las otras posiciones.

**Comment by jisilvamc** [comment]
Perfecto, muchas gracias.
¿Podemos asumir entonces que sólo va a haber un input con botones por programa? Para no tener problemas con la velocidad del clock

**Comment by FranLucchini** [comment]
No pueden asumir eso, pero no se preocupen, que no es parte de su trabajo manejar eso. Al corregir, los ayudantes nos encargamos :smile:

**Comment by dalliende** [comment]
todavia tengo una duda del uso de los botones, cuando cuando llegue la instruccion IN, se ven los botones que esten apretados y se genera un binario, es decir si el boton 0 y el 3 estan apretados, el input seria (01001)2 o es como en la entrega uno donde si mantenemos apretado un boton aumenta/dismunuye un registro (en este caso que no es ni el A ni B) y cuando se ocupa IN, se entrega el numero de ese registro?. 

Saludos

**Comment by FranLucchini** [comment]
Es la primera opción que describiste, ahora los botones son elementos de input binario.
