### ISSUE TITLE
Instrucciones Assembler T03

### ISSUE THREAD

**Issue by mcorreaiz** [IIC2343/syllabus#163]
Podrian entregarnos una tabla de todas las instrucciones que interpreta el assembler que nos entregaron? Gracias

**Comment by Hernan4444** [comment]
@mcorreaiz el assembler interpreta todas las instrucciones contenidas en el archivo de [Assembler.pdf](https://github.com/IIC2343/syllabus/blob/master/Assembler/IIC2343%20-%20Assembler.pdf) excepto por `OUT` e `IN`

Saludos ✌️
