### ISSUE TITLE
Entrega 4 | Orden de los botones

### ISSUE THREAD

**Issue by stmorales** [IIC2343/Syllabus#163]
Hola!!

Aún no me queda claro cual es el posicionamiento en bits de los botones. Cuál es el orden en los bits correspondiente a cada boton?? 

Bits = Izquierdo | Arriba | Derecha | Abajo | Central ??

Gracias!

**Comment by frvalenzuela** [comment]
Hola @stmorales !

El orden de los botones es el siguiente:
posición 0 central, posición 1 arriba, posición 2 izquierda, posición 3 derecha y posición 4 abajo.

En formato de señal para la simulación sería:
```
btn <= "00001"; -- press central button
btn <= "00010"; -- press up button
btn <= "00100"; -- press left button
btn <= "01000"; -- press right button
btn <= "10000"; -- press down button
```

Si queda alguna duda favor confirmar.

Saludos!

**Comment by stmorales** [comment]
Gracias Felipe!
Clarísimo

Slds
