### ISSUE TITLE
Disassembler/Assembler Parte Programada

### ISSUE THREAD

**Issue by acrojas2** [IIC2343/syllabus#163]
Dudas varias:

- El archivo de input del disassembler es como el archivo de salida del assembler en la parte 1?

- En operaciones que usan (Dir), el literal que va abajo es el valor de la variable o no?, lo que no entiendo es porqué en el ejemplo del enunciado ponen que es la ubicación de la variable.
-La idea del disassembler es general un archivo como el de entrada de la parte1 de programación?

Saludos.

**Comment by jheysen** [comment]
Sobre tus dudas del dissassembler, lee las preguntas de la parte 4.
En operaciones que usan dirección, en general tu siempre quieres la
dirección para hacer las cosas.

**Comment by acrojas2** [comment]
@jheysen acerca de las operaciones que usan direccion, lo que no me queda claro es porqué el valor de la variable es la ubicación de ella en memoria.

**Comment by jheysen** [comment]
Recuerda que el valor de la variable es algo que vas a tener recién en tiempo de ejecución, luego, para referirte a su valor en un instante dado siempre vas a necesitar ir a verla a su dirección de memoria asignada.
