### ISSUE TITLE
Input Parte 2

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2343/syllabus#164]
En la parte 2 de la tarea (y en el bonus) nos piden revisar si existen ciclos en una matriz. 

La matriz que nos piden revisar bajo que input la obtenemos? Tenemos que leer un txt? O bien se declara a mano dentro del programa?

**Comment by Hernan4444** [comment]
@Rudyjb24 lo declaramos a mano en el programa. En el enunciado se pusieron precisamente como estará el código al inicio para obtener el input. Tambien subimos de la parte 2 para que vean como serán los archivos.

Saludos ✌️

**Comment by Rudyjb24** [comment]
Perfecto.

En la misma ide para la parte en C declaran el arreglo asi: 

int* matriz = [0, 0, 0, 0, 0, 1, 0, 1, 0];
Pero esto me tira error "Expected Expresion". Y aprovechando el vuelo. 
Como accedo un elemento del array? con matriz[i]?

**Comment by Hernan4444** [comment]
Si, nos equivocamos y debe ser:
```C
int* matriz = {0, 0, 0, 0, 0, 1, 0, 1, 0};
```

> Como accedo un elemento del array? con matriz[i]?

Eso es algo que debes investigar tu, por algo es bonus.

Saludos ✌️

**Comment by Rudyjb24** [comment]
Eso me tira una warning: "excess elements in scalar initializer"

**Comment by Hernan4444** [comment]
Puedes probar con:
```C
int matriz[] = {0, 0, 0, 0, 0, 1, 0, 1, 0};
```
Le cambie el asterisco por un parentesis, por si acaso ambas formas sirven para representar un puntero a una lista de `int`

Avisame si ahí te funciona.

**Comment by Rudyjb24** [comment]
Puedo declarar el arreglo de otra manera? (Esque encontre otra declaracion que funciona).

**Comment by Rudyjb24** [comment]
Si esa es la forma que me funciono.

**Comment by Hernan4444** [comment]
@Rudyjb24 puedes indicarnos como quieres declarar la lista?

**Comment by Rudyjb24** [comment]
Habia encontrado  esta forma int matriz[] = {0, 0, 0, 0, 0, 1, 0, 1, 0}; la que ya nos indicaron que sirve. Gracias!

**Comment by lefischer** [comment]
entonces se declararan como matriz[] = {0,.......}?

**Comment by Hernan4444** [comment]
así es
Saludos ✌️
