### ISSUE TITLE
Entrega 4 | Duda con nuevas instrucciones

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2343/Syllabus#164]
Hola, tengo dudas acerca de las 4 nuevas instrucciones que soporta el computador básico ya que no entiendo muy bien que realizan por que ya tenemos programado todo el hardware pedido.

Esto claramente no es una petición que digan que señales de control unit se activa si no que si se puede explicar que hacen en el computador y al final que reg dis o reg led se utiliza :(

**Comment by frvalenzuela** [comment]
Hola @nicoparraguez !

Las instucciones de OUT cargan lo que esta en el registro A en alguno de los otros dos registros, Dis y Led. Cual de los dos, se determina por la señal de salida del MUX B, que indica al componente Decoder donde pasar la señal de carga. Para más información al respecto recomiendo revisar la issue #159

Si queda alguna dudo, no dudes en comentar.

Saludos!
