### ISSUE TITLE
Entrega 4 | Formato de Subrutinas

### ISSUE THREAD

**Issue by mora4** [IIC2343/Syllabus#165]
Hola, 

El enunciado dice que tenemos que subir los codigos de las subrutinas. Estos codigos tienen que incluir las instrucciones necesarias para recibir parametros (interaccion con botones y switches)? O es suficiente el codigo "puro" que solo implementa una funcion con los parametros cargados en la DATA?

Gracias!

**Comment by frvalenzuela** [comment]
Hola @mora4 !

Tienen que incluir las instrucciones necesarias para ecibir parametros, dado que el recibir parametros es parte del manejo de la subrutina.

Saludos!
