### ISSUE TITLE
Loops Infinitos Simulacion

### ISSUE THREAD

**Issue by LuisFros** [IIC2343/syllabus#165]
Debemos manejar el caso que exista un loop infinito?

**Comment by jheysen** [comment]
Tienen que ejecutar el código tal cual viene. No veo en qué impacta que se
meta a un loop infinito.

**Comment by LuisFros** [comment]
Entiendo,
Mi duda es porque si existiera un loop infinito y no realizo un manejo sobre ese caso, el archivo de resultados de la simulacion nunca se escribe. La unica manera de que puedo entregar algun resultado seria deteniendo el loop infinito.
![image](https://user-images.githubusercontent.com/21247721/46583275-78449d80-ca2a-11e8-9da9-fa0646d822b2.png)

**Comment by LuisFros** [comment]
Ok, gracias!
