### ISSUE TITLE
Duda de comportamiento del SP.

### ISSUE THREAD

**Issue by dalliende** [IIC2343/syllabus#166]
Tengo una duda, en el enunciado de la entrega nos dicen que al hacer POP/PUSH/CALL/RET el SP, disminuye y aumenta en 2, si con la memoria que tenemos nos basta disminuir/aumentar en tan solo 1 el SP, debemos igual disminuirlo en 2(como en la arquitrectura x86) , o queda a nuestro criterio si queremos disminuir 1.

Saludos

**Comment by Hernan4444** [comment]
@dalliende debería reducirse en 1, me podrías indicar en que parte dice que es 2? (Para tenerlo en cuenta el próximo semestre).

Saludos ✌️

**Comment by dalliende** [comment]
![image](https://user-images.githubusercontent.com/11409081/31801939-b2e8ab80-b521-11e7-8c9e-cff1c436c7ec.png)

No se si es verdad, pero pense que el -- (del SP) significaba que se decrementaba en dos unidades porque salian dos -, si no es asi, era porque no sabia la notación ajaja . saludos

**Comment by Hernan4444** [comment]
@dalliende Minuto computín: 
El  `SP--` se traduce a `SP = SP - 1` (`--` es como restaré uno y guardalo), al igual que `SP++` es sumar 1 y guardar. En otros lenguajes (Como `C`  💟) se ocupa eso.
Saludos ✌️
