### ISSUE TITLE
Tarea 4 - NWA

### ISSUE THREAD

**Issue by danustilovsky** [IIC2343/syllabus#166]
Hola, cuando la cache es NWA existe alguna convencion respecto a que segmento debe ir cada palabra cuando es traida por primera vez o podemos dejarlo como random.

Gracias

**Comment by frvalenzuela** [comment]
Hola @danustilovsky !

Cuando la cache es N-way se tiene la convención de a que conjunto debe ser enviado, el cual se comporta como mapeo directo revisando la cantidad de bits necesaria (en 2-way necesito un bit, en 4-way necesito dos bits y así). Luego que definimos el conjunto, dentro de ese mismo conjunto asignamos al primer bloque disponible, de no haber ninguno aplicamos el reemplazo según la política que este definida. 

Para más información recomiendo revisar los apuntes. Y si tu duda persiste no olvides hacerlo saber para poder solucionarla de mejor manera.

Saludos!

**Comment by atbusch** [comment]
@frvalenzuela no me queda claro cuantos bits usamos al convertir las direcciones de memoria de los programas a binario para ponerlas en los sets. En los apuntes lo hacen con 5 bits pero igual depende de que tan grande pueda llegar a ser la dirección.

Gracias

**Comment by frvalenzuela** [comment]
Hola @atbusch !

La cantidad de bits te la dará el tamaño de la memoria. Si tienes una memoria de 16 bytes, necesitas 4 bytes para poder representar la dirección.
En los apuntes sale 5 bits solo para evitar la confusión con números negativos por complemento 2 (lo que no se da, no deben preocuparse de ello en la tarea puesto que todas las direcciones son naturales).

Espero que responda tu duda. 

Saludos!

**Comment by pgarnham** [comment]
@frvalenzuela Pero si no me equivoco la cantidad de bits depende de (tamaño cache)/N, y no directamente si es 2WA o 4WA o no? Me refiero a que es más importante la cantidad de secciones, que la cantidad de bloques por seccion.

**Comment by pgarnham** [comment]
Y otra pregunta. El bit que se usa para elegir la palabra dentro del bloque es aparte de los bits para elegir la seccion? Es decir, los bits en total son el "tag" + "la seccion" + "el bloque" ?

**Comment by frvalenzuela** [comment]
Hola @pgarnham !

Toda la razón, error mío ahí lo edite @danustilovsky , @atbusch  !

Respecto a la segunda pregunta a que te refieres con sección y con bloque? Notar que bloque se ocupa para un grupo de palabras en memoria, línea un grupo de palabras en cache. Pero sección no se a que te refieres particularmente.

Quedo atento para responder tu segundo duda.

Saludos!

**Comment by pgarnham** [comment]
@frvalenzuela Muchas gracias!

 Me refiero al grupo de lineas de la caché según la division que genera el NWayA

**Comment by frvalenzuela** [comment]
Hola @pgarnham !

En N-way los bits están distribuidos así : "tag" + "conjunto" + "offset"

Donde conjunto es el número de conjunto. 
**Ejemplo:** 
Si una cache tiene 4 conjuntos, y cada línea de la cache tiene dos palabras entonces requerimos dos bits que indique el número de conjunto, un bit de offset (porque solo hay dos palabras en cada línea) y el resto de bits sería el tag. Así una dirección como 111111111111011, se dividirá como 111111111111 para tag, 01 que indica que va en el conjunto uno y el offset 1 (me salto muchos detalles solo para que quede bien representado la subdivisión de cada componente).

Espero que con esto quede claro.

Saludos!!

**Comment by danyestay** [comment]
@frvalenzuela Me surgió una pequeña duda y aprovecho de colgarme del ejemplo que acabas de dar. Por el principio de localidad espacial correspondería también agregar justo arriba (ubicacion 0 dado el offset 0), en el mismo conjunto y bloque, la dirección 111111111111010?

**Comment by frvalenzuela** [comment]
Hola @danyestay !

Sip así es !

Saludos!

**Comment by danyestay** [comment]
@frvalenzuela gracias!
