### ISSUE TITLE
Numeros negativos [Programacion]

### ISSUE THREAD

**Issue by LuisFros** [IIC2343/syllabus#166]
Tenemos que manejar numeros negativos?

**Comment by jheysen** [comment]
Para literales y cosas así? Si

**Comment by LuisFros** [comment]
Entonces el ejemplo (programa3.txt) que nos dieron para la tarea en el syllabus,
![image](https://user-images.githubusercontent.com/21247721/46586210-77733200-ca51-11e8-840e-2f09eac4bba2.png)
No podriamos trabajar con 255 en 8-bits signed, el rango es (-127,128)

**Comment by LuisFros** [comment]
Perdon por seguir insistiendo,pero antes me dijiste que teniamos que manejar numero negativos entonces estamos obligados a que sea todo sea ***signed**. Por lo tanto, no podemos tener numeros en base decimal afuera del rango (-128,127) y el valor 255 no puede existir en esta tarea. Estoy en lo correcto?

**Comment by jheysen** [comment]
La única limitante real que tienes es que son números de 8 bits, piensa un poco qué pasa si sumas 255 + 255 con una ALU de 8 bits, tomalos unsigned.
Para efectos de la tarea acá por completitud en un assembler tendrías que soportar negativos con complemento a 2, ya que es el computador básico. Si el número es positivo y todavía te dan los 8 bits, no deberías tener problema tampoco.

**Comment by Geeermy** [comment]
¡Hola @LuisFros ! Para seguir este tema si tienes dudas, por favor refiérete a esta _issue_: #173 😁
