### ISSUE TITLE
Tarea 4 - Tabla de Paginas

### ISSUE THREAD

**Issue by MrEarle** [IIC2343/syllabus#167]
Para usar la tabla de paginas (como se especifica en el Anexo de los apuntes de [Multiprogramacion](https://github.com/IIC2343/syllabus/blob/master/Apuntes/10%20-%20Multiprogramaci%C3%B3n.pdf)), es necesario tenerlo en la memoria principal.

Para la tarea, no me queda claro donde guardar las tablas de paginas, y se me ocurren 2 posibilidades:

1. Las tablas de paginas van junto a los datos del programa, por lo que, del tamaño que nos dan para la memoria principal, hay que reservar una fracción para las tablas de páginas.
2. El tamaño de memoria dado corresponde al espacio reservado para la ejecucion del programa, y las tablas de paginas se guardan aparte.

Como sería?

**Comment by tomasrivera** [comment]
Hola, como en la tarea les estamos pidiendo simular los accesos a memoria pueden asumir que tienen todo el espacio que quieran para las tablas de páginas. Sería la opción 2 que propones :smile:

**Comment by danustilovsky** [comment]
Hola, con respecto a lo anterior, se puede asumir que la memoria fisica, siempre tendra una sola pagina como en el enunciado (aunque de tamaño variable) para poder simplemente concentrarse en los accesos a memoria y no tener que implementar las tablas de pagina, dado que los accesos a memoria vienen dados en el archivo json y habria que crear tablas de pagina que tuvieran sentido con lo que se nos entrega y no se podrian generar tablas de pagina de forma "libre".
Gracias

**Comment by frvalenzuela** [comment]
Hola @danustilovsky !

No se puede asumir eso. Las tablas de página se van creando a medida que se usan. Recordar también que no solo nos importan los accesos de memoria en multiprogramación, también nos importan los marcos de memoria. Recomiendo fuertemente revisar los apuntes para una información más detallada.

Saludos!

**Comment by danustilovsky** [comment]
Pero @frvalenzuela que deberiamos hacer en el caso del ejemplo del enunciado en el cual se tiene una sola pagina con 16 palabras, por lo que al procesar el acceso a memoria del programa 2 cuando intenta ingresar al espacio 60, este en binario es "00111100"  por lo que "0" es el numero de pagina, pero "0111100" es el offset que claramente es mayor a la cantidad de palabras disponibles por lo que como se traspasa eso a la tabla de magina?

Gracias

**Comment by frvalenzuela** [comment]
Hola @danustilovsky !

Te recomiendo revisar #172  !

Saludos!

**Comment by fenahurtado** [comment]
Hola, no me queda muy claro... Leer y escribir en la tabla de memoria cuenta para el tiempo de acceso a la memoria?
