### ISSUE TITLE
Entrega 4 | Problema señal C SUB

### ISSUE THREAD

**Issue by felipearellanom** [IIC2343/Syllabus#167]
Me he encontrado con que el metodo de definir el Carry (C) para la resta (SUB) dado en la entrega 1 es incorrecto, se define como que si la resta es a-b entonces hay carry cuando a>=b pero en el caso que a=-1 y b=0 el modelo de resta enseñado en clase resulta en carry a pesar de que a<b pero por lo menos con este ejemplo no.
¿Que deberia hacer?

**Comment by frvalenzuela** [comment]
Hola @felipearellanom !

En proyecto, tanto para referirnos a literales, como a direcciones de memoria y datos almacenados, asumimos que serán valores naturales, lo que también pueden asumir en esta entrega.

Todos los inputs que se probarán serán números mayores a cero, por lo que no se compliquen con los casos negativos.

Saludos!
