### ISSUE TITLE
ciclos

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#167]
![image](https://user-images.githubusercontent.com/24725124/46583671-dbd1c980-ca30-11e8-8ab5-968e31ab821e.png)

Hola no me quedan claro los tres ciclos.
Por ejemplo, si quiero hacer Mov A, Lit en el primer ciclo podría guardar el opcode y ya directamente en el segundo guardar Lit en el registro A, por lo que no se necesita un tercer ciclo.

 Además como en la mainMemory siempre es opcode, literal tendríamos que poner un "pause" a la lectura o no?

¿No se será que con tres ciclos se refieren a tres subidas donde la tercera es la primera de la siguiente?

**Comment by jheysen** [comment]
Es para estandarizar y que se enreden menos. La idea es clock 1 leen
opcode, clock 2 leen literal, clock 3 ejecutan.

**Comment by movaldivia** [comment]
@jheysen osea para el ejemplo `Mov A, Literal` en el segundo clock no debería estar el literal en el `registro a` cierto?

**Comment by jheysen** [comment]
En una implementación estricta no
