### ISSUE TITLE
Dudas T03 Parte 1

### ISSUE THREAD

**Issue by mcorreaiz** [IIC2343/syllabus#167]
No se puede acceder al registro SP? El assembler me tira error al hacer operaciones del tipo MOV A,(SP).
Podemos asumir que todos los elementos del arreglo son distintos?

**Comment by dalliende** [comment]
Creo que MOV A,(SP) seria el equivalente a POP A.

**Comment by Hernan4444** [comment]
Tal como dice dalliende, MOV A,(SP) es equivalente a POP A. Recuerden revisar el pdf de Assembler, ahí se especifica todas las instrucciones soportadas y que hacen.

**Comment by mcorreaiz** [comment]
Si se que es equivalente, era un ejemplo no mas. Un ejemplo mejor seria 
MOV A, SP
DEC A
MOV B,A
MOV A, (B)
para acceder a los parametros de una funcion. Pero ya veo que SP no esta disponible en esta arquitectura asi que buscare un metodo alternativo. Gracias igual

**Comment by FranLucchini** [comment]
Asumir que cuáles elementos son distintos? Me puedes especificar si estás pensando en la parte 1 o 2 de la tarea?

**Comment by mcorreaiz** [comment]
En la parte 1, los elementos de la lista. Testearan con listas con elementos repetidos?

**Comment by Hernan4444** [comment]
@mcorreaiz no puedes hacer ese supuesto. Si fuera una lista de elementos no repetidos, hubieramos dicho conjunto o set (ambos no aceptan repetidos).

Saludos ✌️
