### ISSUE TITLE
Tarea 4 - Hit Rate

### ISSUE THREAD

**Issue by MrEarle** [IIC2343/syllabus#168]
No me queda muy claro un par de cosas sobre cuando se cuenta un hit. Me estoy basando en el anexo de los apuntes de [Multiprogramacion](https://github.com/IIC2343/syllabus/blob/master/Apuntes/10%20-%20Multiprogramaci%C3%B3n.pdf), y cuando se encuentra la página en la TLB y no en la caché, se trae el bloque apropiado de memoria y se copia a la caché. Luego se vuelve a buscar en la caché (donde si o si va a estar).

Mi pregunta es, esto cuenta como un miss y despues un hit? O solo cuenta como un miss?

El problema con lo primero es que si cuenta como miss y despues hit, entonces el hit rate va a ser siempre mayor o igual a 0.5

**Comment by Arcoirisky** [comment]
Hola!

Por lo mismo que dices, solo cuenta como Miss :D Porque inicialmente no lo tenía, solo que se da una vuelta de comprobación para que el flujo se mantenga y no tener que agregar más cosas al computador.

**Comment by MrEarle** [comment]
Perfecto, y como es en el caso de un miss al buscar la página en la TLB?

En los apuntes dice:

> En caso de que la TLB no tenga la entrada, ocurre una excepcion denominada TLB miss exception [...] hay dos posibilidades: si la entrada esta marcada como que esta en memoria, o si esta marcada como que esta en disco:
> 1) Si esta marcada que esta en memoria, el SO copia la entrada a la TLB, y se repite el acceso a esta, esta vez ocurriendo un hit.
> 2) Si esta marcada que esta en disco. [...] Una vez completado esto se repite el acceso a la TLB y ahora habra un hit.

Segun la descripcion, se da a entender que cuando hay un TLB Miss, habrá un TLB Hit si o si antes de que se termine la ejecucion de esa linea.

Ese hit tampoco se cuenta?

**Comment by frvalenzuela** [comment]
Hola @MrEarle !

Lo que da entender el apunte es que cuando es que tu tienes un TLB Miss, por lo que necesitas ir a buscar la página ya sea a memoria o a disco, y una vez que tu la buscas y la pones en la TLB puedes acceder a ella, a eso se refiere con que sea un hit. En analogía, podrías tener una cache normal, cuando tu accedes a una dirección primero lo traes de memoria, lo escribes en la cache y tendrías ahora el acceso a dicha dirección en la cache (un hit), pero para la estadística eso será un Miss, puesto que no estaba en la cache. De forma similar ocurre en la TLB.

Así que or lo dicho anteriormente, ese "hit" no cuenta en la estadística para el hit rate. Ojo también que luego de copiar la entrada en la TLB podrás acceder a la dirección física la cual si puede esta en la cache, recordar que en la cache hay direcciones físicas no páginas.

Espero que haya quedado más claro, si no fuese así no dudes en volver a consultar.

Saludos!

**Comment by faamigo** [comment]
Hola!
Entonces por cada línea ejecutada habrá una de estas opciones o me equivoco?
Miss de ambas
hit de ambas
miss tlb hit cache
hit tlb miss cache

Gracias!

**Comment by frvalenzuela** [comment]
Hola Felipe!

Si, esas son las opciones.

Saludos!

**Comment by MrEarle** [comment]
Muchas gracias!
