### ISSUE TITLE
input bonus

### ISSUE THREAD

**Issue by lefischer** [IIC2343/syllabus#168]
Hola,

Pueden explicar como va a ser el input del bonus, puesto que la con la definición de matriz del enunciado tira error

main.c:3:17: error: expected expression before '[' token
int* matriz = [0, 0, 0, 0, 0, 1, 0, 1, 0];

no debería ser int* matriz[9] = {0, 0, 0, 0, 0, 1, 0, 1, 0}; ? (de esta forma tampoco es totalmente correcto)

en input lo van a pegar en el main o debe ser ingresado?

**Comment by Hernan4444** [comment]
#164 
Saludos ✌️

**Comment by lefischer** [comment]
gracias

**Comment by Rudyjb24** [comment]
Una vez recibido el input, podemos trasladar la información a otra estructura de datos que consideremos mas adecuada?

**Comment by Hernan4444** [comment]
@Rudyjb24 si puedes 👍 mientras que el input sea como lo indicamos y el output igual, lo que pasa entremedio puede ser lo que quieras **menos** importar una librería que haga la pega por tí.

Saludos ✌️
