### ISSUE TITLE
[Tarea 6 Programacion] uso de labels

### ISSUE THREAD

**Issue by nmaturana97** [IIC2343/syllabus#168]
Hola, quería saber si en los saltos pueden haber algunos con labels y otros sin ellas. Me explico:

Puede existir esto?
JMP 5 -> salto a la posicion de memoria 5
JMP etiq1 -> salto a la posicion de memoria donde esta etiq1

Tambien quería saber si para el codigo disassembler, al reconocer un salto debemos volver a establecer etiquetas, es decir, si encuentro un JMP (en opcode) en la posicion 6 y el literal siguiente es 2, debo añadir JMP etiq1 y a la instruccion a la cual refiere el salto agregarle "etiq1:"?

**Comment by Geeermy** [comment]
¡Hola!

1. Muy buena pregunta. No, no les pasaremos algo así en **código Assembly**.

2. No, no es necesario. No obstante, si lo dejas así, te va a pasar lo que mencionas en el punto anterior, pero eso no está mal ya que no hay forma de recuperar los _labels_ originales dado que no se guardan _strings_. Si quieres, **puedes tomar el supuesto de que sí se puede existir un código así** y eso te permitiría probar los programas con saltos reconstruidos con tu -Disassembler_, pero como _input_ no les pondremos algo así.

¡Que estés bien! 😄

**Comment by nmaturana97** [comment]
Muchas Gracias!

**Comment by tomasrivera** [comment]
Hola, con relación a lo mismo, ¿aplica para las instrucciones de memoria y direccionamiento?

Por ejemplo, el código puede tener instrucciones del tipo:

`MOV (7),A`

O se restringirá a usar _labels_ para el direccionamiento?
