### ISSUE TITLE
Entrega 4 | Instrucción POP en dos ciclos

### ISSUE THREAD

**Issue by diegoheg** [IIC2343/Syllabus#168]
Hola, con nuestro grupo nos surgió la duda de si es necesario implementar una instrucción para aumentar el SP antes de hacer el POP, ya que como lo manejamos hacemos que el POP realice el incremento del SP, pero con los resultados de la entrega 3 nos dimos cuenta de que no lo hace correctamente (probablemente lo hace luego de obtener el valor), es por esto que queríamos saber si con las instrucciones de la tabla tenemos lo necesario o es necesario crear una instrucción exclusivamente para aumentar el SP

**Comment by frvalenzuela** [comment]
Hola @diegoheg !

Si es necesario dos instrucción recomiendo revisar la issue #95 donde se explica con mayor profundidad.

Saludos!
