### ISSUE TITLE
Problema Emulador

### ISSUE THREAD

**Issue by SebaCardenas** [IIC2343/syllabus#169]
Estoy haciendo una función en assembly, donde en los regitros tengo REG A = FFFF y REG B = 0000 pero cuando llego a hacer un 
CMP A, B
JLT OTRAF 

no se realiza el jump. es problema del emulador?

**Comment by Hernan4444** [comment]
@SebaCardenas `JLT` salta solo si la última comparación es negativa y `CMP` hace A-B, eso no da negativo.
Saludos ✌️

**Comment by SebaCardenas** [comment]
Pero queda como resultado FFFF y eso debería ser negativo, tomando que FFFF es -1

**Comment by Hernan4444** [comment]
@SebaCardenas no estamos trabajando con números negativos 😅 

Saludos ✌️

**Comment by SebaCardenas** [comment]
Eso explica muchas cosas, gracias!
