### ISSUE TITLE
Tamaño bloques caché

### ISSUE THREAD

**Issue by FernandoDeDiego** [IIC2343/syllabus#169]
Hola!
No me queda claro cuál es el tamaño de cada bloque de la caché. Debemos asumir que cada bloque tiene un dato, de un byte?
Saludos.

**Comment by Arcoirisky** [comment]
Hola!
Serán de 2 bytes, es decir que guardarán dos datos. De la misma forma que el control 3 :D

**Comment by MrEarle** [comment]
El tamaño de un bloque no debiera ser el mismo tamaño que el de un marco fisico de la memoria o de una pagnia de la memoria virtual?

**Comment by frvalenzuela** [comment]
Hola @MrEarle ! 

No necesariamente. El tamaño de la cache generalmente almacenara menos direcciones que un marco físico. 

Saludos !

**Comment by MrEarle** [comment]
@frvalenzuela 

Por lo que entiendo, la TLB traduce una dirección virtual en una dirección fisica:
(Para el caso de paginas/marcos de 4 palabras)
1. Toma la dirección virtual (por ejemplo 7) y la traduce a la pagina correspondiente (en este caso, la pagina 1)
2. Busca en sus líneas si contiene la página 1, si la contiene, la traduce al marco físico en que se encuentra la página (digamos que es el marco 2, conteniendo las direcciones fisicas 8-11, donde la direccion virtual 7 se encuentra en la direccion fisica 11).
3. El computador usa ese marco físico para ver si el dato que requiere está en la caché. Este seria el marco 2 de direccion fisica 8.
4. La caché busca si tiene un bloque de dirección fisica 8 y lo encuentra, pero si el tamaño de los bloques es 2, entonces este bloque contiene los datos en las direcciones virtuales 4 y 5, por lo que realmente no encontró el dato.

Yo creo que mi confusión está en el paso 3 o 4, porque, para encontrar el dato de la direccion virtual 7 habria que decirle a la caché que busque el bloque de dirección 10 (8 + 2) que corresponde a la mitad del marco físico 8. Es así como realmente funciona?

**Comment by frvalenzuela** [comment]
Hola @MrEarle !

Primero, la TLB no es quién se encarga de tener dicha traducción, se encarga la tabla de página. Dentro de la TLB esta la información de la tabla de página, por lo que primero revisas si esta en la TLB, y en caso de no estar revisas en la tabla de página.

En el paso dos que mencionas, una vez obtenida la dirección física no es necesario recurrir nuevamente al marco (pues lo utilizaste para calcular la dirección) Por lo que en el tercer punto revisas la dirección 11 esta en cache, no la dirección ocho. 

Finalmente que guarde la mitad de un marco físico en cache no es ningún problema, puesto que para la caché solo hay direcciones fisicas.

Si algo no quedo claro hacerlo saber.

Saludos!

**Comment by Jiparavich** [comment]
@frvalenzuela @Arcoirisky 
Entonces, podemos asumir (al igual que el control) que la cache va a guardar la dirección "que fui a buscar" y la contigua ( dirección + 1)?

**Comment by frvalenzuela** [comment]
Hola @Jiparavich !

Sip! aunque no necesariamente direccion +1, puede ser también direccion -1 !

Saludos!

**Comment by Jiruiz2** [comment]
Sobre lo que dijiste que puede también almacenar la -1, queda a nuestro criterio como lo hacemos o hay alguna manera de decidir?

**Comment by Jiparavich** [comment]
> Sobre lo que dijiste que puede también almacenar la -1, queda a nuestro criterio como lo hacemos o hay alguna manera de decidir?

Tienes que ver el ultimo bit.
Si es 0, guardas el siguientes (+1).
Si es 1, guardas el anterior(-1)
Con ultimo bit me refiero al 1 de "00001"
