### ISSUE TITLE
Solicitud para extender plazo tarea 6

### ISSUE THREAD

**Issue by paula-ds** [IIC2343/syllabus#169]
Hola! ¿existe la posibilidad de extender el plazo para esta tarea? varios lo agradeceríamos :/

**Comment by jheysen** [comment]
Contando que se entrega el jueves?

**Comment by jheysen** [comment]
Les dimos un día más

**Comment by Arcoirisky** [comment]
Durante este fin de semana dejarán que seamos elfos libres o subirán tarea? O’:

**Comment by norman123123** [comment]
Pero podemos entregarla el viernes en la tarde? Hoy hay interrogación de Ingeniería de Software y la tarea es larguísima igual! PORFAVOR!

**Comment by dagalloso** [comment]
Se los agradeceríamos mucho!!

**Comment by faberrios** [comment]
Si por favor!! Seria maravimagico!!

**Comment by jheysen** [comment]
No es posible, por la devolución de las placas.

**Comment by dmolina2** [comment]
Porfavor! Estamos varios en la misma situación!!!

**Comment by jheysen** [comment]
Se ha enviado un aviso al respecto
