### ISSUE TITLE
Entrega 4 | MuxIn para multiples inputs en simulación

### ISSUE THREAD

**Issue by diegoheg** [IIC2343/Syllabus#169]
Hola, tengo la duda de si a priori hay que modificar en algo el componente muxIn con respecto a la entrega 3, debido a que en esta entrega el input es confirmado mediante botones ¿Es necesario agregar otro selector adentro del muxIn que tome el valor de los botones o eso debe ser trabajo de la simulación?

**Comment by frvalenzuela** [comment]
Hola @diegoheg ! 

No es necesario, puesto que el MUX IN trabaja con el literal para seleccionar el puerto, y el puerto de los botones ya está definido en la entrega 3, por lo que con pasar el literal correspondiente bastaría. 

Saludos !
