### ISSUE TITLE
FLAG_Z y FLAG_N entrega 1

### ISSUE THREAD

**Issue by ChaparoD** [IIC2343/Syllabus#17]
con respecto al flag Z, podemos declar flag Z de la siguiente forma

flag_z = "1"when A == B ; (podemos usar la función predefinida "== " en el caso de que sea una resta)

y con respecto al flag N , 

flag n = "1" WHEN A < B ; ( usar la función predefinida "< " y sea resta también la operación que estamos ejecutando)

**Comment by frvalenzuela** [comment]
Hola @ChaparoD !

Para ambas preguntas, la respuesta es un no. La idea es que usando circuitos lógicos ustedes puedan obtener la equivalencia el resultado de esos operadores matemáticos.

Saludos!
