### ISSUE TITLE
Problema modulo Debouncer

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2343/syllabus#17]
Hola!

Tenemos un problema a la hora de usar los botones para incrementar / decrementar el valor de los inputs, ya que no cambia en uno en uno, si no que de a saltos aleatorios. Estamos usando los d_btn, pero al parecer si está tomando en cuenta el tiempo que está el botón apretado.

Alguien más tiene el mismo problema o se debe a un error nuestro?

**Comment by fdominguezclaro** [comment]
Después de leer las issues de año pasado nos dimos cuenta que había que poner el clock en 10 o 11.

Gracias de todas formas!

**Comment by Hernan4444** [comment]
justo eso iba a decir, jejeje 
Saludos ✌️
