### ISSUE TITLE
Pauta Control 3

### ISSUE THREAD

**Issue by danustilovsky** [IIC2343/syllabus#170]
Hola, existe la posibilidad de que suban la pauta del control 3 ya que podria ayudar a resolver dudas de la tarea 4.

Gracias,

**Comment by Arcoirisky** [comment]
La subo enseguida!

**Comment by danustilovsky** [comment]
Muchas Gracias!!

**Comment by Arcoirisky** [comment]
Ya está arriba :D

**Comment by Felipehanckes** [comment]
Hola!

Viendo la respuesta del control, hay algunas cosas que no me quedaron claras.

1. No me queda claro cuando se borra la memoria TLB y si hay una para cada memoria virtual o una para todo el sistema? 
2. Al ser LIFO la politica de la TLB, no deberia quedarse siempre el que primero ingresa? ya que al ser secuencial, si le quiero meter 2 entradas de paginas, al sacar una y meter otra, esa que meti pasaria a ser la "last in", por lo que no debería salir de inmediato par que entre la otra?

Saludos!

**Comment by Panckx** [comment]
Hola, @Felipehanckes! En respuesta a tus preguntas,

1. Todo el sistema tiene una sola TLB, y ésta se borra en cada cambio de contexto, ya que los datos de la TLB para el programa 1 van a tener poco que ver con los del programa 2. Tendrá esto un impacto en el desempeño de un computador si la TLB no se alcanza a llenar antes del cambio de contexto? 🤔

2. Esto no ocurre, ya que la política es una política de reemplazo, por lo que primero se llena la TLB y luego, al querer escribir en ella, se elige el último espacio usado. De ahí para adelante, siempre se cambiará ese espacio! Qué te dice eso de la eficiencia de una TLB con ese tipo de política de reemplazo?

Espero que te sirvan las respuestas!
