### ISSUE TITLE
Entrega 4 | Duda simulaciones

### ISSUE THREAD

**Issue by vaperez5** [IIC2343/Syllabus#170]
Hola, tengo dudas de como ingresar los inputs en mi simulación siguiendo el orden especifico del enunciado. Mi duda surge puesto que en el taller 4 se dice que para esta entrega es mucho más sencillo simular y que no tenemos que ir viendo lo que pasa ciclo por ciclo, sino que basta con entregar los parámetros y que se ejecute el programa, para posteriormente mostrar el resultado final. Por lo que, en este caso, se podría ingresar todos los inputs a utilizar al comienzo del programa y guardarlos como variables para posteriormente usarlos en su ejecución, o eso no respetaría el orden del enunciado? Muchas gracias!

**Comment by frvalenzuela** [comment]
Hola @vaperez5 ! 

Puedes almacenar los inputs en memoria si lo consideran más sencillo para sus Algortimos. Sin embargo,  debe poder recibir los inputs por el archivo de simulación, y no ejecutarse por defecto solo con lo que esté en la DATA. Debe poder ser interactivo con la simulación, si se cambie el input, se pueda cambiar el resultado. 

Respecto al orden, el ingreso de input tiene un orden específico, si se sigue ese orden debería estar bien. Como por ejemplo que después de pasar un parámetro se apreté el botón central. Por lo demás no veo problema en cómo piensan sus solución.

Saludos !
