### ISSUE TITLE
Operación INC(B)

### ISSUE THREAD

**Issue by vixolo** [IIC2343/syllabus#170]
Esta instrucción debiese "incrementar Mem[B] en una unidad". Para hacer esto, primero hay que leer qué hay en Mem[B], y luego sumarle uno y escribirlo en Mem[B]. Al menos tomaría dos ciclos ya que primero hay que tener la señal de control "write" de la memoria apagada (para obtener el valor), y luego hay que activarla para guardar el valor incrementado. Para implementar esto, evaluamos usar un registro como repositorio auxiliar del valor de Mem[B+1], y luego escribir el valor. El problema es que cambiaríamos el valor que estaba almacenado en este registro.

Por otro lado, podríamos hacer PUSH B antes de hacer esto, y luego con POP B recuperar el valor, pero nos suena extraño que esta instrucción tenga una implementación tan compleja.

¿Nos podrían orientar un poco con esto?

Muchas gracias,
Vicente.

**Comment by Hernan4444** [comment]
![image](https://user-images.githubusercontent.com/15641721/31850951-a908b120-b632-11e7-8853-209840c63e3f.png)

@vixolo esta instrucción no necesita de dos ciclos, como puedes ver en el diagrama, la **MUX S** puede recibir lo que tiene el registro B y ese dato mandarlo como dirección a la RAM, de este modo el **dataout** de la RAM será **MEM[B]** el cual llegará al **MUX B**. (Hasta aquí logramos obtener MEM[B] sin sobreescribir nada)

Además podemos hacer que de la **MUX A** salga un 1 y que la **ALU** esté en modo suma. De este modo haces que la **MUX B** tenga **MEM[B]** y la **MUX A** tenga 1. Cuando sumes obtendras como resultado de la **ALU** lo que necesitas (MEM[B] + 1). Este resultado puede ir de inmediato al **MUX DATAIN** y  no olvidemos que de la **MUX S** venía el valor de B. Por lo tanto, la RAM está apuntando a **MEM[B]** y de datain tiene **MEM[B] + 1** solo es necesario que esta instrucción haga que la señal **W** de la RAM sea 1 y lograrás que todo se realice en un ciclo.

En resumen:
1. MUX S recibe B
1. MUX B recibe dataout de B
1- MUX A recibe un 1
1. ALU suma
1. MUX DATAIN recibe resultado ALU
1 RAM está en modo escritura

Como podrás notar, en ningún momento pusimos un **LOAD** de los registros en 1, por lo tanto no se perdió nada 😃 

Ojalá haya quedado más claro la instrucción.
Saludos ✌️

**Comment by vixolo** [comment]
Muchas gracias Hernán! Ahí me quedó muchísimo más claro. La única pequeña duda que me podría quedar es que creo que para que lo que tu describes funcione, la señal **W** de la RAM debe estar en 0 anteriormente y eso no es necesariamente cierto, o sí?

Podría darse un código con las siguientes dos lineas una tras la otra y no estaríamos obteniendo el valor **MEM[B]** al comienzo?

MOV (B), Lit  -------------  (Aquí la señal **W** queda en 1)
INC (B)

**Comment by Hernan4444** [comment]
@vixolo no es necesario que esté en 0 anteriormente. Todo el sistema del clock está hecho para que los cambios se realicen cuando hay una subida de este (clock). Esto en simples palabras te permite hacer esas dos lineas seguidas con W en 1 en cada una de ellas sin ningún problema. Te recomiendo mejor que lo pruebes tu mismo y te darás cuenta que no pasa nada extraño 😃 

Saludos ✌️
