### ISSUE TITLE
[Tarea 6 programación] Definición variables

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#170]
Hola! En la última ayudantía vimos que tomáramos el código como opcode, literal, opcode, literal, etc aunque hubiera una definición de una variable entremedio. Es decir, hacer como que nunca se definen variables. O más bien se refería a que si un opcode utiliza una variable, entonces se va a la "linea" de la variable para encontrarla y luego se debe omitir esa linea siguiendo la idea de opcode, literal? 
Si no me explico mi pregunta es: debemos hacer como que no existen las definiciones de variables? o debemos darnos cuenta cuando se define una variable para saltarnos esa linea?

Gracias!!

**Comment by FranLucchini** [comment]
Hola, me puedes especificar un poco más a qué parte de la tarea te refieres si al assembler o al disassembler?

**Comment by Bipavez** [comment]
Hola!
A raíz de esta pregunta me surgió otra:
¿Que hacemos cuando hay una instrucción de direccionamiento indirecto, pero apunta a una label declarada **antes** de la línea que estamos leyendo?
Podría decir directamente, bueno, esta línea es dato en memoria, pero eso rompería la paridad y mi instrucción de la que derivé la posición va a ser literal en vez de opcode. Si el label está declarado abajo no hay problema. 
La pregunta se refiere al ***disassembler***.
Gracias!

**Comment by miguelramirezv** [comment]
En la primera parte-1 Assembler @FranLucchini

**Comment by FranLucchini** [comment]
@miguelramirezv si entendí correctamente, tu duda tiene que ver con qué hacer si aparece una variable en la lectura del programa en el caso del assembler. El caso que me describes, de que se debe leer los pares opcode + literal, la idea es que el assembler sea capaz de obtener los casos en que ocurre una variable y reemplazarlos por la dirección que le corresponde. O sea, si tenemos el siguiente código:

```
MOV (var1), A
var1 10
(...)     ; más instrucciones
```
Tu assembler debe ser capáz de definir la posición de memoria en que irá `var1` y modificar las apariciones de ella, ya sean antes o después de que aparezca:
```
00100111 -- opcode MOV (var1),A
00000010 -- Literal, dirección de var 1
00001010 -- var1 en memoria
(...)    -- siguientes instrucciones
```

Dado esto, no me queda claro cómo tu duda tiene relación con el assembler: 

> Si no me explico mi pregunta es: debemos hacer como que no existen las definiciones de variables? o debemos darnos cuenta cuando se define una variable para saltarnos esa linea?

Ahora, cuando el disassembler trata de de leer este código, debe tratar de interpretarlo lo mejor posible con la información que tiene disponible. Las concecuencias de esto se relacionan con las preguntas que les planteamos en el enunciado.
