### ISSUE TITLE
Entrega 4 | Que hacer cuando el programa termina

### ISSUE THREAD

**Issue by felipearellanom** [IIC2343/Syllabus#171]
Cuando el programa termina el enunciado dice que hay que prender todos los led para señalarlo.
¿Esto significa que vuelve a empezar y se puede decidir de nuevo entre programa 1 y programa2?

**Comment by frvalenzuela** [comment]
Hola @felipearellanom !

Para esta entrega no es necesario un loop para volver a iniciar. Para volver a elegir otro programa se deberá volver a correr la simulación con otro input. 

Saludos !
