### ISSUE TITLE
[C03] DUDA TLB

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#171]
Hola!
Por que la TLB la van "reiniciando"  de vez en cuando? Al ser LIFO en el caso del control el (0,0) de pagina|marco no se debería mantener hasta el final? Espero que se entienda mi duda.

**Comment by Arcoirisky** [comment]
¿Te refieres a los cambios de contexto? Xq esos te invalida todo lo que tienes en tus Cachés

**Comment by auirarrazaval** [comment]
Hola @chocopiano!

La TLB no es nada mas que una *caché* de la tabla de páginas de el proceso actual, que se usa para disminuir lo más posible los accesos a disco por parte de la CPU durante la ejecución de el proceso (recuerda que las tablas de página se encuentran en el disco). 
Por eso mismo, el contenido de la TLB durante cada cambio de contexto debe ser invalidado, ya que las relaciones presentes en ella al hacer cambio de contexto corresponden a mapeos de las páginas de el proceso saliente, y esas relaciones no tienen nada que ver con las relaciones del nuevo proceso (a no ser que sea un caso muy extraño)

En el caso que pones tu, (0, 0) correspondería a una relación (página P1, marco) , en otras palabras: la página 0 de la **memoria virtual del proceso 1** mappea al marco 0 de la **memoria física** (disco). Pero al hacer cambio de contexto, estamos trabajando con la **memoria virtual del proceso 2**, y en esa memoria virtual, el mapeo de su página 0  no necesariamente es al marco 0: puede ser 0, 1, 2 o 3, lo que es determinado segun el algoritmo de reemplazo utilizado.

Espero que se haya entendido,
Saludos!

**Comment by chocopiano** [comment]
Muchas gracias!
