### ISSUE TITLE
Problema RET

### ISSUE THREAD

**Issue by SebaCardenas** [IIC2343/syllabus#171]
RET no está volviendo a PC +1 intenté con el caso base del factorial, pero vuelve al inicio del programa y no a la instrucción que debe. Cuando cambie el RET por un JMP se salia del loop. Es problema del emulador?

**Comment by Hernan4444** [comment]
@SebaCardenas debe haber un error de tu código, ese emulador lo llevamo usando desde antes que yo tomara el semestre y al menos mis tareas las hice con pura recursión por lo que el RET debe estar bueno. Talvez un condicional malo o no llegas a la instruccion que crees que llegaste.

Saludos ✌️
