### ISSUE TITLE
Duda tarea 3 primer algoritmo

### ISSUE THREAD

**Issue by sebawarrior** [IIC2343/syllabus#172]
Hola, quería preguntar si el resultado del factorial del K-máximo y el K-minimo en assembly debe estar en herxadecimal, o bien basta con que sea un numero normal (en base 10). Pregunto esto pues no sé como sería meter letras en las variables del Assembly en caso de que deba devolverlo como hexadecimal. Gracias.

**Comment by Hernan4444** [comment]
@sebawarrior el resultado es en hexadecimal pero el mismo emulador se encarga de pasarlo a hexadecimal. Solo tienen que buscar el mínimo o máximo y dejarlo en la variable que corresponde. El emulador hará el resto, no hay de que preocuparse.

saludos ✌️

**Comment by sebawarrior** [comment]
Ya perfecto! osea con el obtener el factorial de kmaximo y kminimo estamos. Gracias!
