### ISSUE TITLE
[TAREA 4] - Páginas Virtuales

### ISSUE THREAD

**Issue by RobinCuevas** [IIC2343/syllabus#172]
Hola!
Una consulta, como puedo saber cuantas páginas virtuales existen en el programa? Puedo asumir que todos los números dentro de la secuencia de un programa son de 8 bits, por ende tendría siempre 2^3 páginas virtuales?

Dentro de lo mismo, para los números dentro de la secuencia de un programa, cuántos bits se consideran para el numero de página virtual y cuantos bits para el offset?

**Comment by chocopiano** [comment]
Complementando a la pregunta, yo tambien estoy mega ultra perdido. Como puedo saber la cantidad de paginas virtuales que habrán? Como puedo saber en cuantos bits debo escribir cada numero de la secuencia? y de la pregunta anterior cuantos bits son para el indice de pagina y cuantos son para indicar el offset? No lo logre entender de los apuntes viendo el ejemplo de la página 7. Gracias!

**Comment by chocopiano** [comment]
Para responder todo lo anterior, creo que solo es necesario saber el tamaño de la memoria virtual. Donde está?

**Comment by frvalenzuela** [comment]
Hola @chocopiano y @RobinCuevas !

El tamaño de la memoria virtual, para caso de la tarea, siempre será el doble de la memoria física. Con eso se puede calcular la cantidad de páginas.

Respondiendo a la duda de los bits, el número de bits que indica el número de página virtual será igual al logaritmo en base dos de la división de el tamaño de la memoria virtual divido en el tamaño de tabla de página. Respecto al offset sería la cantidad de bit totales de la dirección menos la cantidad de bits de número de página. 

Saludos!

**Comment by fperezm12** [comment]
El tamaño de tabla de página se refiere a la cantidad de marcos posibles?

**Comment by leolivares** [comment]
@frvalenzuela Hola! Me queda una duda. La cantidad de bits totales esta determinada por el tamaño de la memoria virtual o siempre será 8?

**Comment by Taeval** [comment]
Es correcto decir que si por ejemplo la memoria virtual es de 32 bytes y una página tiene un tamaño de 16 bytes, entonces una tabla de páginas tendrá 2 entradas? (32/16 = 2)

**Comment by Dyoma3** [comment]
@frvalenzuela como la cantidad de paginas virtuales es el doble de la memoria fisica: en el ejemplo del enunciado Tamano: 16 y TamanoPaginas: 16 por lo que habran 2 paginas virtuales para cada programa, con un total de 32 direcciones. Sin embargo, en las secuencias hay numeros mayores a 31. Podemos asumir que eso esta mal y que deberian ser a lo mas hasta el 31?

**Comment by frvalenzuela** [comment]
Hola @Dyoma3 ! 

El ejemplo del enunciado es solo un ejemplo de formato. Recomiendo revisar los test subidos al syllabus.

Saludos !

**Comment by chocopiano** [comment]
@frvalenzuela me sumo a las preguntas anteriores.... como puedo saber en cuantos bits debo escribir las direcciones virtuales, ya que gracias a eso puedo sacar los indices de paginas y el offset. Gracias

**Comment by frvalenzuela** [comment]
Hola @leolivares !

La cantidad de bits totales estará definido por el tamaño de la memoria virtual.

Saludos!

**Comment by Dyoma3** [comment]
@chocopiano lo que yo hago es multiplicar la cantidad de paginas virtuales por el tamaño de pagina. Por ejemplo, si los programas usan 4 paginas y el tamaño de cada una es 16, tengo 64 direcciones posibles. Necesito entonces 6 bits, de los cuales los primeros 2 bits se usan para indicar la pagina y los otros 4 el offset. Supongo que esta bien.

**Comment by Taeval** [comment]
Es como dice @Dyoma3  creo. Solo que la memoria virtual es siempre el doble que la memoria física. Así puedes saber la cantidad de bytes que hay en memoria virtual y por ende la cantidad de bits que necesitas para escribir las direcciones (por ejemplo, si tienes una memoria física de 128 bytes, hay 256 bytes de memoria virtual disponibles. Entonces necesitas 8 bits para escribir las direcciones porque 2**8 = 256 .)

**Comment by fperezm12** [comment]
Como puedo saber a que marco físico se mapea cada página?

**Comment by Taeval** [comment]
La memoria física es Fully Associative así que supongo que se puede usar cualquier marco vacío. (O reemplazar según LIFO/FIFO).

**Comment by fperezm12** [comment]
Lo que me refiero es que por ejemplo en los apuntes una página va de 2-3-4 y otra de 5-6-7.  Asumo que empiezan desde el marco 0?

**Comment by frvalenzuela** [comment]
Hola @Taeval !

Atendiendo a la primera duda:

Calculo de cantidad de páginas para un programa: Tamaño_mem_virtual / Tamaño_pagina
Tamaño de tabla de página por programa es un parámetro dado por el .json

Atendiendo a la segunda duda:

Si es correcto!

Saludos!

**Comment by frvalenzuela** [comment]
Hola @chocopiano !

El número de bits de la direcciones virtuales te lo dirá el logaritmo en base dos de el tamaño de la memoria virtual.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @Dyoma3 !

Es como dice @Taeval 

Saludos!

**Comment by Taeval** [comment]
En qué parte del .json está el parámetro del tamaño de la tabla de páginas? Los programas solo tienen nombre y secuencia.

**Comment by frvalenzuela** [comment]
Hola @Taeval !

Perdón error de tipeo y lei mal jaja, me refería al tamaño de página. La cantidad de filas de la tabla de página de cada programa será igual a la cantidad de páginas posibles en la memoria virtual.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @fperezm12 !

Todas podrían partir con cualquier número realmente (por eso la x representada en alguna fila de los apuntes), lo que importa es que todas tengan un bit de validez y un bit de disco en cero al inicio. Y cuando se vayan validando el valor sea el correspondiente de la página al marco asociado.

Saludos!

**Comment by Dyoma3** [comment]
@frvalenzuela pero si lo que dijo @Taeval es complementario a lo mio.

**Comment by Taeval** [comment]
Muchas gracias por las respuestas @frvalenzuela ! @Dyoma3 , si es complementario. En todo caso eso lo saqué de los apuntes de multiprogramación.

**Comment by frvalenzuela** [comment]
Hola @Dyoma3 !

Ambas respuestas están correctas, solo que mencione lo de @Taeval porque responde de una manera más directa el como sacar la cantidad de bits de las direcciones virtuales. Lo que dijiste esta bien para sacar el offset y cantidad de bits de página, pero si la pregunta es solo la cantidad de bits de la dirección virtual entonces solo saber el tamaño de la memoria virtual es requerido. (Nuevamente, no es que lo que dijiste esta mal, solo lo recalco en caso de alguna confusión).

Perdón si se me entendió de otra manera.

Saludos!

**Comment by fperezm12** [comment]
@frvalenzuela Estuve probando y me da que casi todos van a la pagina 0. Esta correcto?

**Comment by Sforrego** [comment]
> Hola @fperezm12 !
> 
> Todas podrían partir con cualquier número realmente (por eso la x representada en alguna fila de los apuntes), lo que importa es que todas tengan un bit de validez y un bit de disco en cero al inicio. Y cuando se vayan validando el valor sea el correspondiente de la página al marco asociado.
> 
> Saludos!

me queda la duda, si yo le asigno el marco fisico que quiero a las paginas virtuales

por ejemplo si el programa 1 accede a las paginas virtuales 5, 8, 17 y el programa 2 al 1, 6, 13

tabla programa 1
pag     marco
5         0
8         1
17       2

tabla programa 1
pag     marco
5         3
8         4
17       5

entonces sirve de algo realmente el bit de validez/disco?
porque si no hago que dos paginas virtuales apunten a un mismo marco nunca voy a tener que usar el disco.

**Comment by frvalenzuela** [comment]
Hola @Sforrego !

El problema estará cuando todos los marcos tengan asociado un página. Ahí es cuando necesitarás mandarla a disco.

Saludos!

**Comment by Sforrego** [comment]
Gracias @frvalenzuela !
Para estar seguro entonces, si mi memoria fisica es de 128 bytes, tengo 128 marcos para asignar, cuando asigne el marco #129 voy a tener que pasar el que se repita a disco.

**Comment by frvalenzuela** [comment]
Hola @fperezm12 !

SI las direcciones virtuales están dentro del rango del tamaño de la página entonces es normal que te de la misma página. Por ejemplo, si en el test1, el tamaño de página es 32, si todas las direcciones son menores a 32, pues todas esas direcciones están en la misma página. 

Espero que eso resuelva la duda.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @Sforrego !

Solo mencionar que el ejemplo que planteas cada marco es de un solo byte, y que no puedes asignar más marcos de los disponibles, así que efectivamente un marco se ira a disco.

Saludos!

**Comment by Jaluco** [comment]
> Hola @Taeval !
> 
> Perdón error de tipeo y lei mal jaja, me refería al tamaño de página. La cantidad de filas de la tabla de página de cada programa será igual a la cantidad de páginas posibles en la memoria virtual.
> 
> Saludos!

Podrian explicar mejor esto? De donde sacamos el tamaño de pagina?
