### ISSUE TITLE
Caché | Ejercicio propuesto en clases

### ISSUE THREAD

**Issue by GbPoblete** [IIC2343/Syllabus#172]
Hola! Estaba estudiando para el examen y en las clases hay un ejercicio que propuso el profesor. Llevo mucho rato intentado obtener la respuesta pero no lo logro. Alguien sabe por qué es 11?

Problema: Supongamos una cache con 64 líneas, en cada línea tiene 16 bytes. ¿Cuál es el índice de la línea correspondiente a la dirección de memoria 1200?

Respuesta 11.

Agradezco la respuesta de antemano!

**Comment by ceosorio** [comment]
Hola @GbPoblete!

Teniendo en cuenta que te dan una caché de 64 lineas, de 16 palabras cada una, podemos saber que:

* 4 bits serán para indicar la posición de la dirección _dentro_ de la linea.
* 6 bits serán para indicar el índice de linea (porque son 64 lineas en total)

Como te piden la dirección 1200 = 10010110000

|tag|linea|posición|
|-|-|-|
|1|001011|0000|

Entonces tu línea será la 001011 = 11 en decimal.

Espero haber aclarado tu duda :)
Ánimo en el estudio! ✨

**Comment by GbPoblete** [comment]
Sii, muchísimas gracias!!
