### ISSUE TITLE
[Tarea 6 programación] Orden del código en el Assembler Parte 1

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#172]
Hola! Si archivo txt que nos entregan está de la siguiente forma:

var1 255
MOV B,(var2)
SUB A,1
var2 0
CMP A,B

Podemos entregar los opcodes con la definición de las variables al final? O sea en este orden:

MOV B,(var2)
SUB A,1
CMP A,B
var1 255
var2 0

O debe ser en el orden original?

Gracias!!

**Comment by Arcoirisky** [comment]
Me uno a la pregunta diciendo Sí, para el dissassembler O:!

**Comment by jheysen** [comment]
Deben _intentar_ entregarlos en el orden original.
Como se especifica en el enunciado, una de las _gracias_ de la ISA es que las variables pueden estar en medio de todo.
