### ISSUE TITLE
[T04] NWA Cache

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#173]
Hola nuevamente
Cuando se me dice que la cache es 2wa por ejemplo con un tamaño de 4, existiria solo un conjunto o me equivoco? al ser 2wa me dice que habra 2 bloques por conjunto y como cada bloque es de 2 palabras se me da a entender que así sera (1 conjunto->2 bloques->4 ubicaciones). De no ser así, alguien me puede explicar como funcionaría? Gracias!

**Comment by chocopiano** [comment]
Me había confundido, ahora entendí que el tamaño te indica la cantidad de bloques

**Comment by frvalenzuela** [comment]
Hola @chocopiano !

Me alegro que se haya entendido, solo para quienes no hayan entendido mencionar que como son conjuntos de líneas (la terminología bloque se refiere a la memoria física) 2-way significará que habrá dos conjuntos de líneas. Si el tamaño es de 4 palabras, y cada línea tiene dos palabras habrá dos líneas, por lo que como son dos conjuntos y tenemos dos líneas de cache, cada una representará su propio conjunto.

Saludos!

**Comment by FernandoDeDiego** [comment]
@frvalenzuela no sé si entendí muy bien ese punto.
En el material sale que una caché es 2-way si tiene dos líneas por conjunto. Para el caso de una caché de 4 palabras, si es 2-way y hay dos palabras por línea, bajo esa definición no debería ser un solo conjunto que contiene ambas líneas?
saludos!!

**Comment by frvalenzuela** [comment]
Hola Fernando !

Toda la razón, disculpa mi error. El número de conjunto se saca como número de líneas divido en N, donde N es el parámetro de N-way. En este caso como es 2-way, y hay dos líneas de cache solo hay un conjunto de ambas líneas como mencionaste. 

Edito mi mensaje anterior y pido disculpas por cualquier confusión ocasionada.

Saludos!

**Comment by chocopiano** [comment]
En conclusión cuando se me dice por ejemplo que el tamaño es 4, siginifca que habran en total 4 bloques, es decir 8 palabras o que habra en total 4 palabras nomas ya sea para 2wa y fa. Gracias

**Comment by frvalenzuela** [comment]
Hola @chocopiano !

El tamaño 4 significa 4 bytes o 4 palabras no confundir.

Saludos!

**Comment by chocopiano** [comment]
muchas gracias!

**Comment by chocopiano** [comment]
@frvalenzuela en los apuntes de cache en la parte del 2wa hay 8 lineas y sin embargo solo 2 conjuntos pero con lo que dices deberian ser 4 conjuntos. Fue un error o algo estoy entendiendo mal?

**Comment by frvalenzuela** [comment]
Hola @chocopiano !

En el ejemplo de los apuntes hay 4 líneas (en los apuntes aparece como bloque) , cada línea tiene 2 palabras, por lo que es una cache de un tamaño de 8 palabras, con líneas de 2 palabras. Como hay 4 líneas y es 2-way, se requiere entonces de dos conjuntos.

Saludos!

**Comment by chocopiano** [comment]
Toda la razon, fue una confusión mia entre linea y palabra. Gracias!
