### ISSUE TITLE
Consulta largo de bits Opcode

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2343/syllabus#173]
Hola! Tengo la duda si es que podemos agregarle más bits a nuestro Opcode, que actualmente es de 17 bits, a por ejemplo 20 bits.

Saludos!

**Comment by Hernan4444** [comment]
@BenjaPrograma ¿porque quieres tantos?

**Comment by BenjaPrograma** [comment]
ocupamos 13 la entrega pasada, y ahora queremos usar 6, 1 para cada señal, sabemos que no es óptimo, pero se nos hace más facil de implementar.

**Comment by Hernan4444** [comment]
No se puede, para empezar estás reduciendo la cantidad de literales y eso hará que los test no logren funcionar. Por otro lado los opcode no son para enviar las señales. De eso se encarga la Control Unit.

Saludos ✌️
