### ISSUE TITLE
[TAREA 6 - IMPORTANTE] Manejo de números negativos

### ISSUE THREAD

**Issue by Geeermy** [IIC2343/syllabus#173]
¡Hola a todas y a todos!

Con respecto a la tarea 6, hay una acotación que debemos hacer que concierne a la parte de programación dado que no todos lo han tenido en consideración. Como sabrán, los computadores hacen uso de valores negativos, y la arquitectura de esta tarea no es la excepción. Es decir, podemos encontrar instrucciones del tipo:

MOV A,-3

Por ello, les pedimos que tengan las siguientes consideraciones:

1) Si ya terminaron su _Assembler_ sin considerar esto, asegúrense de terminar el resto de sus partes antes de volver a ello, ya que es un detalle que se puede incorporar al final.

2) Lo que se espera que hagan es que trabajen con complemento a 2 al momento de escribir estos literales dentro de la memoria, algo que hemos visto desde el principio del curso.

3) ¿Entonces el _Disassembler_ considera números negativos según complemento a 2? => Decisión de ustedes que debe ser expuesta en el **README**, recuerden que también existen direcciones como literales, lo que puede influir en su decisión.

4) ¿Y si recibo números mayores a 127? => Decisión de ustedes también, aún lo pueden seguir representando con 8 bits, así que se pueden almacenar directamente y le dejan ese problema al _Disassembler_.

Esperamos que estos puntos los ayuden a aclarar este detalle y que lo puedan incorporar dentro de sus tareas, si aún no lo hacen.

**Comment by acrojas2** [comment]
Hola!
En el punto 4. Mencionas que le dejo el problema al disassembler con el tema de los numeros negativos. De ser así, puedo considerar negativos en el assembler siempre y cuando no sean direcciones de memoria y en el disassembler considerar que solo existen positivos para todo tipo de instrucción? o se debe hacer la distincion entre intrucciones?
Saludos 😕

**Comment by Geeermy** [comment]
@acrojas2 Sí, es válido ya que no explicitamos una forma de manejo fija (y ya lo habíamos conversado por correo 👀).

**Comment by naquiroz** [comment]
@Geeermy  puedo suponer que las direcciones de memoria con numeros negativos se organizan de la siguiente forma?

Primera memoria (00000000) .... Ultima Memoria(11111111)
```
127,126,125, ..., 1, 0,  -1, -2 ..., -128 
```
Así, en mi assembler podría permitir direcciones negativas de memoria.

**Comment by Geeermy** [comment]
Nosotros no les vamos a pasar direcciones negativas.

NUNCA les vamos a pasar algo así:

```
MOV B,-5
MOV A,(B)
```

Y si tu _Disassembler_ llegase a generar algo así:

```
MOV A,(-1)
```

Puedes analizar ese resultado en la pregunta 4, pero no tiene por qué ser _parseado_ en tu _Assembler_. Por lo tanto, no hagas ese supuesto ya que, según mi percepción, complejizaría de sobremanera tu implementación y los _tests_ que soporta.

**Comment by naquiroz** [comment]
Hice un edit!

**Comment by naquiroz** [comment]
Basandome en el édit. Si permito eso Y números del 0-255, es problema?

**Comment by Geeermy** [comment]
Trata de no editar, ya que es más difícil seguir el hilo.

Insisto, no es necesario que hagas eso, pero debería funcionar. Aunque también esperaría que funcione con algo del estilo:

```
MOV A,(255)
```

Por ejemplo. ¿Lo permites? (punto 4 de esta _issue_).

**Comment by naquiroz** [comment]
@Geeermy , si lo permite. Saludos!
