### ISSUE TITLE
Examen | Pregunta 1-a | Duda Alu

### ISSUE THREAD

**Issue by arbiocanpion** [IIC2343/Syllabus#174]
Hola! 
En el enunciado de la pregunta 1-a dice "No puedes utilizar la ALU ni modificarla." ¿A que se refiere con ello?, a que no puedo modificar la ALU, ¿Pero la puedo utilizar mas de una vez para las subrutinas?.

**Comment by jmwielandt** [comment]
La ALU se tiene que seguir usando para los procesos normales del computador básico, pero para implementar la operación `MUL A,B` no puedes usarla. Tienes que agregar los componentes que necesites aparte.

**Comment by vaperez5** [comment]
Osea, para que quede más claro, básicamente seria que no puedo modificarla, pero si puedo continuar usándola como siempre la hemos usado?

**Comment by jmwielandt** [comment]
@vaperez5 no puede participar en el cálculo de la operación `MUL A,B` para calcular el resultado.

**Comment by vaperez5** [comment]
Me perdí jajaja podrías explicarlo nuevamente porfa? Sin alu entonces donde se efectuarían las operaciones?

**Comment by jmwielandt** [comment]
Puedes agregar otra ALU distinta, u otro componente que estimes necesario.
