### ISSUE TITLE
Duda general TLB

### ISSUE THREAD

**Issue by Dyoma3** [IIC2343/syllabus#174]
Hola, queria saber si estoy enteniendo bien la materia, por lo que explicare lo que entiendo:

![image](https://user-images.githubusercontent.com/17127676/58492680-66da0e00-813f-11e9-8c7c-92b0b81f8174.png)

Para que un programa acceda a una dirección de memoria en específico, primero la MMU busca la entrada de la tabla de la página (del programa actual) en la TLB. Si no está, va a la memoria con las tablas de páginas y la mete a la TLB. 

Luego de tener la entrada de la página, si la entrada indica que la página esta en el disco, se hace un swap out y swap in para meterle en la memoria principal (no sé si se aprovecha también de meter a la caché). Luego de esto,  va a haber un miss o hit dependiendo de si metí el dato a la caché en el paso anterior o solo a la memoria principal.

Finalmente, se entrega el dato a la CPU.

**Comment by auirarrazaval** [comment]
Hola! 

Esto puede servir de ayuda para el como se debe hacer la tarea:
Cuando se quiere acceder a una direccion de memoria específica para cada programa, lo que se hace es:

1. Buscar si la entrada correspondiente está en la TLB o no (con vit válido, obviamente), si está, entonces es un TLB hit, si no, es un TLB miss (ahí ya tenemos una estadística).

2. 
    a. Si estaba en la TLB, entonces tenemos la dirección del marco físico donde se encuentra el dato (o si está en el *swap file* o no)

    b. Si no está, debemos accceder a la tabla de páginas (primer acceso a disco) para encontrar la dirección del marco físico correspondiente.  (Si tampoco está ahi, entonces es un page fault)

3.
    a. En caso de que el marco no estaba en el *swap file*, entonces está todo bien.

    b. Si el marco estaba en el swap file, se hace un *swap in* de este al disco y se actualiza este valor tanto en la tabla de páginas como en la TLB (y se hace *swap out* de otro marco, determinado por la política de reemplazo utilizada). Notar que hacer swap in implica leer la swap file y escribir en la memoria física

(Hasta acá es lo que hace la MMU -> traducción de direcciones)

4. Ya teniendo la dirección del marco físico correspondiente, se busca en la *caché* de la memoria física

5. 
    a. Si está en la *caché* (*caché hit*) estamos listos (tenemos el valor, eso no es necesario para la tarea)
    b. Si no está, se debe ir a buscar a la memoria física en el marco especificado (*caché miss*) y agregarlo a la *caché* (Segundo acceso a disco, si es que no hubo *swapping*)

Estoy atento por si queda alguna duda!
Saludos.

**Comment by Dyoma3** [comment]
@auirarrazaval quede con dudas. Tu te refieres al swap file en este caso de las entradas de las tablas de páginas. Sin embargo, en #167 se dice que las tablas se almacenan aparte y que hay que suponer que se tiene todo el espacio que queramos para esto. Esto implicaría que no sería necesario guardar la info de las tablas en el disco por falta de espacio (no habría swap file). El swap file que indican los apuntes son los de las páginas que no alcanzan en la memoria principal.

**Comment by MrEarle** [comment]
Entonces, respecto a la tarea, que no exista una entrada en la tabla de paginas se considera un page fault?
Y obtener/escribir un registro de la tabla de paginas tambien cuenta como una lectura/escritura para las estadisticas de la tarea?

**Comment by auirarrazaval** [comment]
@Dyoma3 Los *swap* son de los marcos a los que apuntan las entradas de la tabla de páginas, los que ocurren dado que la memoria virtual total por lo general es mas grande que la física, por lo que ocurre que la memoria física está ocupada, pero la direccion virtual para ese proceso esta "libre" (esa es la gracia de la virtualización - ver ultimas diapositivas de la clase de Memoria). Y ojo que lo que es "infinito" es el espacio disponible para almacenar todas las tablas de paginas, pero cada tabla de pagina en sí si tiene un tamaño finito.

@MrEarle Respecto a lo primero, un page fault es cuando la entrada de la tabla de páginas es inválida, o bien está en disco (básicamente cualquier cosa que lleve a que hay que entrar a disco igual). 
Y respecto a lo segundo, si, de hecho, esa es una de las gracias de la tarea, ya que los tiempos de lectura de la TLB son mucho menores que los tiempos de lectura de la tabla de páginas (lo mismo para escritura)

**Comment by Dyoma3** [comment]
@auirarrazaval entiendo que los swap son de los marcos (me referia a que no son de las tablas que indican el mapeo de estos) y que las tablas de las páginas sí tienen tamaño finito (por esto es relevante el tamaño de la TLB). Pero según lo que leí en Multiprogramación, las tablas de las páginas se almacenan en la memoria principal y la TLB se usa para crear acceso más rápido, por lo que un miss en el TLB solo implica que se va a buscar el dato en la memoria principal. Ese dato contiene la info del mapeo del marco, además de decir si es válido o está en el disco (en base a esta info hay page fault, swap in/out).

**Comment by auirarrazaval** [comment]
@auirarrazaval Si bien las tablas de página están en la memoria principal, estan en un lugar distinto que lo que nosotros llamamos "memoria física" en este caso. Es ese espacio el que estamos designando como infinito. 
Creo que quizás nos estamos refiriendo a lo mismo, pero para ponerlo de otra forma y asegurarme:
Cuando un programa pide una dirección, ésta viene  de la forma ```bits_dirección_virtual | bits_offset```, y se necesita una relación direccion virtual -> direccion "real". De eso es lo que se encarga la MMU, la que en teoría podría tener solo las tablas de páginas, y en ese caso lo que se haría sería acceder a ella para cada solicitud de dirección (si no se encuentra, es page fault y se le asigna un marco físico a esa página virtual). La (El técnicamente) TLB corresponde a un *buffer o caché* de la tabla de páginas, por lo que si no hay una a entrada con la direccion solicitada en la TLB, igualmente se debe ir a buscar a la tabla de páginas para encontrar al marco físico que corresponde.
Luego, recién teniendo la dirección del marco físico correspondiente puedo ir a buscar el dato a la memoria principal, usando la dirección física = ```dirección_marco_fisico | offset``` , dónde el offset es igual en la dirección virtual y en el marco, ya que solo corresponde a la linea que se busca dentro de la tabla/marco (que son del mismo tamaño).
Recíen con la dirección física final, puedo ver si el dato esta presente en la caché de la memoria principal (nada que ver con la TLB). En caso de que no esté en esa caché, ahi recién voy a buscar el dato a la memoria principal.

En resumen:
+ **Best case scenario:** (Hay dos accesos a memoria física)
1. Busco en TLB si hay una entrada para la dirección virtual correspondiente, no está
2. Busco lo mismo en tabla de páginas, tampoco está -> Page Fault -> Asigno un marco físico a esa página virtual (O la traigo de swap file si ese es el caso)
3. Teniendo ahora una dirección física para la dirección virtual, busco en la caché de la memoria principal si hay un dato cuya entrada sea la dirección del marco físico + offset, no está
4. Voy a buscar el dato directamente a la memoria principal

+ **Best Case Scenario** (No hay accesos a memoria principal)
1. Voy a buscar la dirección virtual a la TLB -> Si está -> Tengo la dirección del marco físico
2. Voy a buscar a la caché de la memoria principal si hay una entrada con la dirección física (direccion del marco obtenido de la TLB + offset) -> Si está -> Estoy listo, tengo mi dato

No sé donde me referí a que el swap se hacía de las entradas a la TLB, avisame para editarlo y dejarlo lo más claro posible para que ayude al resto!

**Comment by Dyoma3** [comment]
@auirarrazaval buena gracias lo que escribiste es lo que pensaba

**Comment by danustilovsky** [comment]
@auirarrazaval Hola! me surgio una duda, cual es la diferencia entre que una direccion virtual no tenga asociada un marco fisico o que esta este en el disco?
Ademas, en que caso se puede dar en que una direccion virtual no se encuentre en la tabla de pagina? O esto seria lo mismo a que lo que pregunte en la primera pregunta?

Gracias!!

**Comment by auirarrazaval** [comment]
@danustilovsky
:warning: Hay que tener cuidado con la distinción de los terminos dirección virtual y número de página. ⚠️ 

Algunas consideraciones al respecto:
+ Un número de página se podría decir que siempre está en la tabla de páginas (ya que ésta representa todo el espacio de memoria virtual), pero no necesariamente tiene asignado un marco (primer tipo de page fault). 
+ Supongamos que ya se ha accedido a la página en algun momento previo al acceso actual, entonces en ese momento previo ya se le asignó un marco, pero puede haber ocurrido que a ese marco se le haya hecho swap out para hacer otra asignación. En ese caso, se podría decir que la página tiene asignado un marco pero que se encuentra en el swap file, y hay que traerlo de vuelta a la memoria física para acceder a el (segundo tipo de page fault y swap in). (nota: Cuando se trae de vuelta ese marco desde la swap file a la memoria física, no necesariamente ocupará la misma dirección que antes, sino que la nueva dirección la determina el algoritmo de reemplazo de la memoria física)

**Comment by danustilovsky** [comment]
@auirarrazaval Gracias!

Me surgio otra duda, un mismo programa puede tener mas de una direccion virtual que se mapee a una misma pagina y al mismo tiempo, o solo puede haber una direccion virtual por pagina en un momento dado?

**Comment by auirarrazaval** [comment]
@danustilovsky si, de hecho eso es lo que ocurre siempre. Las páginas (para direcciones virtuales), y marcos (para direcciones físicas) correponden a bloques de datos. Esos bloques tienen múltiples lineas, y al momento de sacar el offset, estoy viendo que numero de linea dentro del bloque tiene el dato en específico. Por ejemplo: si los bloques son de 4 lineas (el offset es de 2 bits), tendré 4 direcciones virtuales que mapeen al bloque uno (todas las direcciones virtuales que correspondan a la página que está mapeada). Pongamosnos en el siguiente caso:
+  memoria virtual de 4 páginas
+ memoria física de 2 marcos 
+ 4 lineas/entradas x marco/página
+ estamos en el programa 1 y despues de un tiempo se le asignó a la página 2 del programa, el marco nro 1 de la memoria física, 
en la tabla de páginas de ese programa tendría algo así:

```
Página            |      Marco
0                 |          x
1                 |          x
2                 |          1
3                 |          x
...
```
Luego: 
+ El offset serán 2 bits (porque hay 4 entradas por marco).
+ La direccion virtual tendrá 4 bits (2 para la página, mas 2 del offset).
+ La direccion física tendrá 3 bits (1 Para el numero de marco, 2 por el offset). 
Si se solicita la dirección virtual 10 (bin: 1010), nro pag: 10 (2), offset: 10 (2), pero el nro de pag 2 está mapeado al marco 1, por lo que la dirección física será 110 (6). Ahora tomemos el ejemplo de la direccion virtual 9 (bin: 1001). Nro pag: 10 (2, igual que antes, pero es otra dirección), offset: 01 (1), marco asignado: 1 (1). Dirección fisica será 110. Mapeado nuevamente al marco 1 (1).

En este caso, tuvimos dos accesos a direcciones distintos que accedian a la misma página, pero tenían distino offset. El primer acceso iba a la linea 10 del marco, y el segundo a la linea 01, pero ambos apuntaban al mismo marco
