### ISSUE TITLE
Parte Práctica

### ISSUE THREAD

**Issue by Cschavez** [IIC2343/syllabus#174]
Hola! 
No sabemos discernir de dónde sale el bus destacado en la imagen. Sale de la unidad de control?
![image](https://user-images.githubusercontent.com/37157327/46689353-0d37ca00-cbd6-11e8-995a-a19356a71e7a.png)

Muchas gracias!

**Comment by jheysen** [comment]
Recuerda que es una guía y no lo que tienen que hacer. Creo que esa línea está de más ya que vendría de la RAM

**Comment by Geeermy** [comment]
Tal como dice @amartinezsilberstein, esa conexión es para que el literal pueda pasar por el Mux B. Antes provenía de la ROM, como ahora las memorias están unificadas es necesario que el cable salga de la memoria principal (por eso se bifurca antes de llegar a la Unidad de Control).
