### ISSUE TITLE
Entrega Parte Programacion

### ISSUE THREAD

**Issue by LuisFros** [IIC2343/syllabus#175]
![image](https://user-images.githubusercontent.com/21247721/46757568-f1e5c100-cca0-11e8-94a5-6dc389546235.png)
Ademas de los _scripts_ de Python, estoy utilizando un archivo JSON para la realizar la Tarea. Puedo usarlo y que sea parte de los archivos que entrego?

**Comment by BSamilla** [comment]
Si, puedes subir archivos complementarios para el correcto funcionamiento de tus scripts.

Asegúrate de mencionarlo en tu Readme, y mantener lo mas ordenado posible tu repositorio, ya que de esta forma es mas fácil para los ayudantes comprender y corregir tu tarea.

Saludos!

**Comment by LuisFros** [comment]
Ok, Gracias!

**Comment by mvcavieres** [comment]
Hola, escribo mi duda aquí porque tiene que ver con la formalidad de la entrega, como se menciona arriba en el enunciado dice: 

> El formato de entrega serán los scripts en Python 3.5 o 3.6 correspondientes, de nombre von_neumann_assembler.py, von_neumann_simulator.py y von_neumann_dissassembler.py

Sin embargo disasselmbler, se escribe la primera "s" con una sola "s", entonces mi duda era el archivo del disassembler lo dejamos con el nombre: "von_neumann_di**ss**assembler.py" con dos "s" en la primera s o "von_neumann_di**s**assembler.py" con una "s"?.

**Comment by jheysen** [comment]
Como estamos muy encima para arreglar el typpo, sigan como sale en el enunciado.
