### ISSUE TITLE
Paginación Apuntes

### ISSUE THREAD

**Issue by FernandoDeDiego** [IIC2343/syllabus#175]
Hola!
El ejemplo de los apuntes en que se obtiene la ubicación física de la dirección virtual 70 del programa 2 dividiendo los bits de la dirección 70 para determinar el marco físico, corresponde al procedimiento en una memoria directly mapped?
Para el caso de una memoria fully associative sería distinto?
Saludos.

**Comment by frvalenzuela** [comment]
Hola Fernando!

Esa división se hace para revisar la página asociada a que marco, en la tabla de página, no tiene que ver con cache. Divide los bits para indicar que página y en la tabla de página se ve que marco va asociada a esa página y luego se cambia para saber la dirección real.

Lo que ocupa políticas de acceso es la TLB que es una cache de la tabla de página.

Espero que eso aclare tu duda.

Saludos!!

**Comment by FernandoDeDiego** [comment]
Gracias, había confundido conceptos!
