### ISSUE TITLE
nodo raíz T3 Parte 2

### ISSUE THREAD

**Issue by cjgazali** [IIC2343/syllabus#175]
¿Podemos asumir que el nodo 1 siempre es nodo raíz?
Si no, tenemos que probar partiendo desde todos los nodos en teoría.

**Comment by Hernan4444** [comment]
@cjgazali en un grafo no existe nodo raíz, eso es para árboles. Debes probar partir desde todos los nodos para buscar algún ciclo.

Saludos ✌️

**Comment by cjgazali** [comment]
Hecho.
