### ISSUE TITLE
Tarea 4 - Invalidar tlb cuenta como escritura?

### ISSUE THREAD

**Issue by MrEarle** [IIC2343/syllabus#176]
Cuando hay un cambio de contexto, se deben invalidar todas las líneas de la tlb.

Para efectos de las estadisticas de la tarea, invalidar cuenta como escritura (cambiar el bit de validez para cada linea)?. Y si cuenta, es solo una escritura en total? O como una escritura por linea?

Edit: Similar a eso, en el caso de la memoria. Si ya conté la lectura por hacer el swap out y la escritura por el swap in, cambiar el bit que indica si está en disco o no cuenta como una escritura adicional? Y la misma duda al actualizar el bit de "prioridad" (para hacer LFU o LRU) en la cache y tlb.

**Comment by auirarrazaval** [comment]
@MrEarle 
Pueden considerar que todo cambio de metadata (valid bit, priority, etc) en las entradas de ambas caché son atómicos (no requieren tiempo)
Sobre la memoria: como dice el enunciado, el manejo de writes es *Write-Back*, por lo que en la memoria se actualizarán las entradas en 2 casos: 

1. Cuando se reemplace/invalida una entrada en la caché correpondiente se debe actualizar en memoria para mantener consistencia
2. Durante un cambio de contexto se actualiza el contenido de la tabla de páginas con el de la TLB donde corresponde (se podría incluir en el punto 1, ya que ahi igual se invalidan todas las entradas)
