### ISSUE TITLE
Comando Assembly

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2343/syllabus#176]
Me llego una duda sobre lo que tiene que hacer los siguientes comandos:

ADD A,B     (Guarda en A, A+B, no modifica B)
ADD B,A     (Guarda en B, A+B, no modifica A)
ADD A,lit   (Guarda en A, A+lit, no modifica B)
ADD A,(dir) (Guarda en A, A+(dir), no modifica B)
ADD A,(B)   (Guarda en A, A+(B), no modifica B)
ADD (Dir)   ??
ADD B, lit  (Guarda en B, B+lit, no modifica A)
ADD B, (dir)  (Guarda en B, B+(lit), no modifica A)

Esta bien esto? Y que hace el comando que me falta?

**Comment by Hernan4444** [comment]
@Rudyjb24 te recomiendo revisar el pdf de Assembler.pdf, ahí está explicado mejor las intrucciones.
Adjunto pantallazo:
![image](https://user-images.githubusercontent.com/15641721/31946289-d4bc57e6-b8a7-11e7-8509-7a3e208d100b.png)

Op debes cambiarlo por ADD para ver como funciona ADD.

Saludos ✌️
