### ISSUE TITLE
[T6 Práctica] Modificacion del diagrama figura 1

### ISSUE THREAD

**Issue by Jaluco** [IIC2343/syllabus#176]
Podemos modificar la figura1 para que el Mux A pueda recibir el dataout?

**Comment by BSamilla** [comment]
Como dice el enunciado, la figura 1 es solo una posible solucion.

Pueden hacer todos los cambios que estimen convenientes para implementar la máquina siempre que cumpla con las caracteristicas de Von Neumann y las instrucciones/restricciones dadas por enunciado.

Recuerda que toda la informacion sobre la implementacíon que usaron la pueden detallar en el Readme.

Saludos!
