### ISSUE TITLE
DUDA T4

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#177]
Cuando hago un swap in, el swap in es a la memoria fisica principal, pero tmb a la cache o esperar a que haga un miss y dpes agregarla

**Comment by auirarrazaval** [comment]
Al hacer swap in ocurren las siguientes cosas:
1. Se lleva un bloque se la memoria ppal al swap file (determinado por el protocolo de reemplazo) 
2. Se cambia en las entradas de la tabla de pagina y TLB el bit de disco
3. Se invalida toda linea de la caché que apunte a una dirección fisica del marco que ya fue reemplazado (consistencia) 
4. Se trae el bloque que estaba en swap file y se escribe en el marco del bloque sacado anteriormente 
5. Se va a la memoria fisica en búsqueda de la dirección inicial, y se actualiza su caché 
6. Se actualiza la entrada en la tabla de paginas
7. Se actualiza la entrada en la TLB

Espero que eso responda a tu pregunta!
Saludos

**Comment by fenahurtado** [comment]
Hola @auirarrazaval, tengo una duda... Antes de invalidar las lineas de la cache que apunten a la direccion del marco fisico que se va a sacar, no se escriben en el mismo marco? Para mantener la consistencia?

**Comment by auirarrazaval** [comment]
@fenahurtado Si, se me olvidó esa pequeña acotación: Dado que es *Write-Back*, cuando se invalida la linea debe esribirse en el marco correspondiente (ojo que eso no ocurre solo en swapping)
