### ISSUE TITLE
Problemas con el repositorio

### ISSUE THREAD

**Issue by tamaralues** [IIC2343/syllabus#177]
Hola, 
Es que en mi grupo somos 3 personas y cuando quiero unirme al repositorio sale que esta lleno.

**Comment by tamaralues** [comment]
Hola! soy el grupo 16 gracias!

**Comment by FranLucchini** [comment]
Ya deberías tener acceso. Me dices si te llegó :smile:

**Comment by tamaralues** [comment]
si gracias!
