### ISSUE TITLE
Problema cargando los tests

### ISSUE THREAD

**Issue by fperezm12** [IIC2343/syllabus#178]
Tengo un problema cargando los test.json. Solo puedo carga el test2.
El error que tengo es este: raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 34 column 5 (char 668)
Puede ser que esten mal escritos?

**Comment by auirarrazaval** [comment]
Hola! Acabo de actualizar los archivos, haz pull y avisa si ahora te funciona!

**Comment by fperezm12** [comment]
Ahora funcionan todos menos el 1 y el 7. Al 1 le falta una coma en programas y al 7 le sobra una

**Comment by auirarrazaval** [comment]
Me di cuenta cuando los subí denuevo jaja, ahora estan todos bien

**Comment by fperezm12** [comment]
ahi si funciona todo perfect
