### ISSUE TITLE
Resultados tests entrega 3

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2343/syllabus#178]
Holaa,
Durante la corrección de la entrega 3 dijeron que iban a subir los resultados de todos los tests para que pudieramos trabajar para recorrejir. Los busqué pero me parece que no los han subido, lo van a hacer?
Graciaas

**Comment by FranLucchini** [comment]
Voy a subirlos ahora, se nos pasó.

**Comment by FranLucchini** [comment]
Ya, están en la carpeta tests en la entrega 3 :)
