### ISSUE TITLE
T4 - LIFO en Memoria

### ISSUE THREAD

**Issue by MrEarle** [IIC2343/syllabus#179]
No me queda muy claro cómo funcionaría LIFO en la memoria principal.

Con "Last In First Out" entiendo un comportamiento que no me hace mucho sentido:

- Al insertar una página a la memoria, en primera instancia se insertaría en el marco 0.
- Como se insertó en el marco 0, este fue el último en entrar (Last In), por lo que la próxima vez se insertará en el marco 0 (First Out)
- Siguiendo el patrón, sólo se insertarán datos al marco de memoria 0, por lo que la mayoría de la memoria no hubiera sido usada nunca y el computador sería muuuuy ineficiente

O me equivoco?

**Comment by Taeval** [comment]
Según yo si la memoria está llena, es decir, todos sus marcos están en uso, cuando tengas que poner otra, tienes que hacer primero un swap out para despejar un marco. La página que tienes que sacar es de acuerdo a la política de reemplazo LIFO que debería ser la que más recientemente se puso en la memoria, en algún marco. Esta la sacas (swap out) y la dejas en disco y traes (swap in) la que necesitas. Como la memoria es Fully Associative, las páginas pueden usar cualquier marco disponible. 

Esto según yo, puede que me equivoque.

**Comment by MrEarle** [comment]
Si, segun yo estás bien, pero igual, al final va a terminar sacando el mismo marco cada vez (ya que el ultimo que entró va a ser el primero en salir), y en ningun caso se sacará un marco sin insertar otro en ese mismo espacio (por lo que entiendo del scope de la tarea).

**Comment by Arcoirisky** [comment]
No realmente, según la política de reemplazo es que vas eligiendo cual mandar al disco para darle espacio al dato que entra 🤔

**Comment by Taeval** [comment]
Aaaah creo que capté lo que dice @MrEarle . Si la memoria física se llena (todos sus marcos ocupados) cuando necesite entrar una nueva página, se reemplaza la que se puso más recientemente en algún marco (LIFO). Pero como es LIFO, la que acaba de entrar sería la que entró más recientemente y por lo tanto, cuando tenga que entrar una nueva página, se reemplazará esta. Entonces el marco que contiene cada una de estas páginas es el que siempre se va actualizando, mientras que los marcos que fueron ocupados antes de que se llenara la memoria quedarían intactos.

**Comment by Arcoirisky** [comment]
Míralo como tiempos. El último en entrar es el primero en salir, cada vez que se ejecuta una acción es un +1 en el clock. Lo que dices está bien pero siento que te jugará un poco en contra no actualizar los tiempos de todas formas.

**Comment by MrEarle** [comment]
Pero eso sería LRU, no LIFO.

**Comment by Taeval** [comment]
Puede que sea intencionalmente ineficiente para efecto de las estadísticas.

**Comment by Arcoirisky** [comment]
O puede que realmente las cosas se hagan según estos métodos ya que siempre se busca el mejor hit rate 🤔

**Comment by MrEarle** [comment]
Por eso pregunto... Este método da un pésimo hit rate, y hace sentido por lo que hemos explicado. Por lo mismo pregunto si lo que estamos asumiendo está en lo correcto, o estamos viéndolo mal y generando malos hit rates cómo consecuencia

**Comment by Arcoirisky** [comment]
No es cosa de asumir algo o no. Las politicas están bien definidas y si dan un pésimo hit rate en algún caso, puedes argumentarlo bien para la parte teorica :D

**Comment by Dyoma3** [comment]
@MrEarle segun yo esta bien lo que dices, aunque sea raro. No se actualizaria nunca el orden y se sacaria siempre el mismo.
