### ISSUE TITLE
Ayudantía 2 - Ejercicio C

### ISSUE THREAD

**Issue by leolivares** [IIC2343/syllabus#18]
Hola! Me surgió una duda con este ejercicio.
Según lo que entiendo por enunciado el P0 es el primer número par que debemos considerar en la suma, y los demás se obtendrían sumando 2 cada vez. Sin embargo en la solución subida,  lo consideran como la posición del primer número par.
Estoy entendiendo mal y debo considerar que los números pares se encuentran guardados?

**Comment by Panckx** [comment]
Ups! Error mío, olvidé cambiar el enunciado de la pregunta! Lo que respondí con la solución fue cómo sumar los N números desde P<sub>0</sub> y olvidé actualizar el enunciado! Ya está actualizado en cualquier caso. Gracias y disculpa! :heart:

**Comment by chocopiano** [comment]
en esta misma pregunta en la línea 8, no deberia ser mov $s3,$s2?

**Comment by Panckx** [comment]
Por qué dices lo del mov? Lo que está haciendo la línea de código que está puesta es ir a buscar el valor almacenado en $s1 a memoria y almacenándolo en $s3 para después poder sumárselo a $s4

**Comment by chocopiano** [comment]
es que segun yo $s3 deberia ser igual a $s1 y lo que se esta haciendo en esa linea es decir que $s3 es igual al valor Mermoria[$s1]. Ejemplo si s1 es 14, queremos decir que s3 tambien va a ser igual a 14 pero lo que se esta haciendo es decir que s3 es igual a Memoria[14]. Jajajaja espero se entienda mi punto

**Comment by Panckx** [comment]
Exacto, el ejercicio dice que tienes que sumar todos los valores en memoria desde el valor ubicado en S<sub>0</sub>, por lo que cada vez que quieras sumar un número nuevo tienes que ir a memoria, rescatar el número y después sumarlo

**Comment by chocopiano** [comment]
Perfecto, había entendido mal el enunciado. Gracias!
