### ISSUE TITLE
Fecha de entrega 1 de Proyecto

### ISSUE THREAD

**Issue by nivek0o0** [IIC2343/syllabus#18]
Hola, dado que coincide con la tarea 1, ¿será posible posponer la primera entrega del proyecto hasta el domingo?
Así podemos focalizar nuestros esfuerzos en cada actividad por separado, junto con la posibilidad de que los grupos se reúnan con calma el fin de semana a terminar una buena entrega.

**Comment by MainScientist** [comment]
Ver el último anuncio de proyecto en el siding! :)
