### ISSUE TITLE
Problemas con Submit  (RGB to CMYK)

### ISSUE THREAD

**Issue by narierao** [IIC2343/Syllabus#18]
Hola ! en el código del RGB a CMYK me pasa que el código me aprueba el test case 0 en el editor

![image](https://user-images.githubusercontent.com/20784195/79032064-83254480-7b71-11ea-9d00-1707a01291ba.png)

Pero al hacerle Submit code me lo rechaza x'c 

![image](https://user-images.githubusercontent.com/20784195/79032072-9df7b900-7b71-11ea-8a46-4f2530b1b8cd.png)

No sé si pasará algo similar con el #testcase8. ayura <3

**Comment by ceosorio** [comment]
Hola @narierao!

Puedes estar sucediéndote lo mismo que expliqué en la issue #11. Si no es el caso, avisame por esta misma issue y ahí puedo seguir ayudándote :)

Saludos y éxito en la tarea ✨

**Comment by narierao** [comment]
Hola! efectivamente, está pasando los sample. Podrían darme algún indicio de qué podría estar fallando en mi código? Tengo la sensación de que pueden ser casos súper particulares x.x

**Comment by narierao** [comment]
Así es, pasó los Sample. Gracias!

**Comment by ceosorio** [comment]
Por favor, no cierres las issues, alguien más podría tener dudas de esto mismo y así pueden comentar aquí :) Nosotros las iremos cerrando en la medida que sea oportuno.

Lograste ver lo que evitaba que pasaras esos 2 test, o aun tienes alguna duda?
