### ISSUE TITLE
T4 - Esquema búsqueda

### ISSUE THREAD

**Issue by fenahurtado** [IIC2343/syllabus#180]
Hice un diagrama para ordenar mi tarea... esta bien el proceso que hago? 
![Untitled Diagram(2)](https://user-images.githubusercontent.com/30677749/58599992-8a40ae00-8250-11e9-8430-9084f06ace5c.png)

**Comment by Arcoirisky** [comment]
No podemos responderte eso D: Es parte de la tarea y materia que queremos evaluar. 

Lo siento :(
