### ISSUE TITLE
Duda libreria tarea 4

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2343/syllabus#180]
Podemos ocupar la función log de la librería math para calcular la potencia de dos de las distintas memorias?

**Comment by Hernan4444** [comment]
@frvalenzuela si puedes.

Saludos ✌️

**Comment by fvandeputte** [comment]
Se puede usar la librería time para la politica de escritura LRU y FIFO?

**Comment by Hernan4444** [comment]
@fvandeputte no puedes, preferimos que consideres que casa acceso de la lista es 1 tiempo.
