### ISSUE TITLE
No entendi write miss

### ISSUE THREAD

**Issue by glbello** [IIC2343/syllabus#181]
Saludos, quedé con la duda sobre el write miss en el enunciado de la tarea 4: 
```
write-miss se define como la cantidad de escrituras realizadas en la
memoria principal dividida por la cantidad de escrituras totales.
```
¿No se supone que cuando escribe, siempre escribe el dato en la memoria principal?, no comprendí muy bien la definición aunque sea super clara.

**Comment by Hernan4444** [comment]
@glbello no siempre se escribe en la memoria principal, hay una política de escritura que justamente escribe en la caché y solo cuando el bloque va a ser reemplazado, escriba en la memoria principal.
Es por esa razon que puede ser que `write-miss` no sea 1.0 siempre

¿Quedó mas claro?
Saludos ✌️

**Comment by glbello** [comment]
a ver si entendí bien, se supone que  por ejemplo en la función de correspondencia de directly mapped si dos bloques están mapeados a un mismo bloque caché, el hecho de que se estén sobreescribiendo ya es una escritura, ahora bien, ¿cuándo sucedería en ese caso la escritura en la memoria principal?

**Comment by Hernan4444** [comment]
la escritura ocurrirá cuando un bloque que ya estaba en la caché va a ser sobreescrito. Si te llegó una acceso de 1w  y luego te llega uno de 5 que justo coincide con el mismo bloque que 1, entonces el 1w debe mandarse a la memoria principal y ahí se genera una escritura de memoria. Si es que llegó 1w y jamás llego otro acceso que involucre el bloque de 1, entonces nunca hubo escritura de memoria.

**Comment by glbello** [comment]
Entonces (corroborando que entendí bien... again) cuando me llega un xW, con x cualquier numero natural más el cero, si sucede que en un bloque de memoria caché estaba sin usar en la que será mapeado este valor, ¿entonces realizo una escritura solo en caché si es que estaba sin usar?, ¿entonces ahí no es necesario que escriba en memoria principal?, ¿eso implica que no hubo write-miss?, ¿solo hay write-miss entonces cuando el bloque de memoria caché no está disponible?. 

Agradesco las respuesta anteriores.

**Comment by Hernan4444** [comment]
> Entonces (corroborando que entendí bien... again) cuando me llega un xW, con x cualquier numero natural más el cero, si sucede que en un bloque de memoria caché estaba sin usar en la que será mapeado este valor, ¿entonces realizo una escritura solo en caché si es que estaba sin usar?, ¿entonces ahí no es necesario que escriba en memoria principal?, ¿eso implica que no hubo write-miss?

Presisamente, eso no es write-miss.

> ¿solo hay write-miss cuando el bloque de memoria caché al que fue mapeado el valor no está disponible?.

Esta parte no te la entendí bien. Si el valor que será mapeado a la caché no está disponible y en el proceso en donde la memoria principal trae ese bloque, reempleza algo que ya estaba "w", ahí si hay write-miss


Imagina que tenemos `esta caché [1-2 , 3-4]` . Tiene 2 bloques de 2 lineas cada bloque y tiene en este momento las memorias 1, 2, 3 y 4. 

Ahora quiero 5w. Este valor no está y ocupa el primer bloque, así que pido a la memoria principal ese bloque reemplazando el 1-2. `La caché queda [5w-6, 3-4]`

Ahora quiero 1w. Este valor no está y ocupa el primer bloque, así que pido a la memoria principal ese bloque reemplazando 5w-6. Como el 5 estaba con "w" y se va a perder, lo mando a la memoria principal y **ocurre el primer write-miss**.  `La caché queda [1w-2, 3-4]`

**Comment by glbello** [comment]
> Ahora quiero 1w. Este valor no está y ocupa el primer bloque, así que pido a la memoria principal ese bloque reemplazando 5w-6. Como el 5 estaba con "w" y se va a perder, lo mando a la memoria principal y ocurre el primer write-miss. La caché queda [1w-2, 3-4] 
> 

Ah perfecto con eso comprendí la idea, muchísimas gracias @Hernan4444

**Comment by vabesa** [comment]
@Hernan4444 Perdona lo latero, se que lo explicaste super bien pero quiero saber si entendi bien ya que dependo de esta tarea jaja
Si es que un acceso de escritura efectivamente escribe se produce un miss(de la cache), dado que tiene que "avanzar" un nivel mas que el de la cache y no disminuye el write-miss(1 instruccion de escritura, 1 escritura efectiva). Pero si un acceso de escritura no escribe en la memoria, sino que solo lo guarda en la cache,este disminuiria el write-miss(suma 1 instruccion de escrita pero no suma escritura efectiva) y este producirá el miss(de la cache) solamente cuando efectivamente se escriba en la memoria(Cuando se reemplace el bloque o se necesite llamar a la memoria, siendo relevante para la tarea solo el primero), aumentando el write-miss tambien(suma escritura efectiva pero no instruccion de escritua). 
Esta bien eso?

**Comment by Hernan4444** [comment]
está perfect 👍 
Saludos ✌️

**Comment by vabesa** [comment]
@Hernan4444 Tengo otra pregunta, si es que hago una instrucción de escritura, por ejemplo 7W, deberia ir a la cache a buscar tambien las memorias que estan "cerca" de esta, por ejemplo en el caso de una memoria de lineas de 2 palabras, tendria que ir a bucar la memoria 6? O solo se cambiaria la posicion 1 de la linea y no la 0?

**Comment by FranLucchini** [comment]
Sí, deben hacerlo. Cuando se pide una linea, buscan todas las lineas de ese bloque.
