### ISSUE TITLE
Error en Test 4 - Tarea 4

### ISSUE THREAD

**Issue by DaToMC9** [IIC2343/syllabus#181]
La política de reemplazo de la caché en el test 4 sale que es NWA 😕

**Comment by Arcoirisky** [comment]
¿Y por qué estaría mal? 🤔

**Comment by Arcoirisky** [comment]
Ya lo noté, dame 5’

**Comment by Arcoirisky** [comment]
Listop, gracias por avisar :D

**Comment by MrEarle** [comment]
Ahora, para la caché se tiene `N = 4` y `Tamaño = 4`, pero si cada bloque es de 2 _bytes_, entonces no caben 4 bloques en toda la caché (porque 4 bloques usarían 8 bytes y la caché es de 4 bytes).

En ese caso no podría caber ningún conjunto de tamaño 4 (N=4) en la caché

**Comment by frvalenzuela** [comment]
Hola @MrEarle !

Toda la razón, ahí el tamaño fue cambiado a 8. Gracias por decirnos.

Saludos!
