### ISSUE TITLE
T6 & contenidos - operaciones lógicas

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#181]
Hola, quería saber qué debe hacer el simulador con las operaciones lógicas con números de varios bits.
Por ejemplo, para python `3 and 4` es 4. `1 or 2` es 1, `0 and -7` es 0, `0 or -7` es -7, `not 5` es 0 (false), etc.

¿Pero qué comportamiento le damos? ¿O queda 100% a nuestro criterio?

Y en la vida real (pregunta de contenido), ¿qué hace x86 (por ejemplo)?

**Comment by jheysen** [comment]
Son bitwise
