### ISSUE TITLE
Levantar error variable indefinida?

### ISSUE THREAD

**Issue by naquiroz** [IIC2343/syllabus#182]
Puedo levantar un error si el codigo assembly hace uso de una variable aún no definida?

Ejemplo
```assembly
MOV A,var1

var1 0
```
Levantaría un error, mientras que

```assembly
var1 0
MOV A,var1
```

No lo haría

**Comment by jheysen** [comment]
Nop

**Comment by acrojas2** [comment]
@jheysen  se asume que viene correcto?
