### ISSUE TITLE
metodo LRU cuenta como lectura?

### ISSUE THREAD

**Issue by Dyoma3** [IIC2343/syllabus#182]
Para mi LRU, cada vez que uso una direccion, tengo que actualizar los valores correspondientes a las posiciones. Para esto, tengo que leer denuevo las lineas para ver que valores actualizar. Esto lo cuento como tiempo de lectura? porque puede variar dependiendo de como implemento el algoritmo.

Ademas, para encontrar el least recently used, yo asocio las las lineas a su orden y para eso tengo que encontrar la que tiene el 0 (la lru). Esto tambien se cuenta como tiempo de lectura?

Estoy confundido con respecto a cuando hay q considerar el tiempo de escritura, ya que creo que creo que en unas partes depende de como uno lo programe. Supongo que primero uno tiene que buscar si hay un bloque libre y para eso si o si tiene que considerarse como lectura, pero de ahi en adelante depende de como se implemente el algoritmo de reemplazo.

Gracias de antemano.

**Comment by auirarrazaval** [comment]
Duplicate of #176
