### ISSUE TITLE
T6 - Práctico. 8 Leds menos significativos 

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2343/syllabus#183]
Hola, qué tal? 
En la parte que aparece que hay que conectar los 8 leds menos significativos a la salida de la RAM, al hacerlo en VIVADO y luego generar el archivo Beatstream, me arroja el siguiente error: 
![captura_error](https://user-images.githubusercontent.com/26261777/46846368-e7691b80-cdb5-11e8-9731-6b5ee632e361.PNG)
Eso es, cambiando la salida de "led" de (3 downto 0) a (7 downto 0) - que supongo que es la forma en que uno pasa a considerar 8 leds en vez de 4-. 
Luego de eso obviamente tengo cada led asociado a cada bit de salida de la RAM. 
Si no hago el cambio, y solo asocio los 4 bits menos significativos, el Beatstream se genera sin problemas. ¿De alguna forma hay que ampliar los 4 bits para que pasen a ser 8? o el "led" se debe configurar en otra parte de tal forma que admita 8 bits en vez de 4? 
Saludos :)

**Comment by frvalenzuela** [comment]
Yo lo arregle dirigiéndome al archivo Basys3.xdc en la carpeta basic_computer.srcs/constrs_1/new
y en el archivo debajo de las lineas de #LEDS  saque todos los '#' de los set, para así activar todos los LEDS y me dejo de ocurrir ese error, eso me resulto a mi por lo menos

**Comment by nfbalbontin** [comment]
Ahí me funcionó! Muchas gracias Felipe :)
