### ISSUE TITLE
Dudas largo de lineas Tarea 4

### ISSUE THREAD

**Issue by vabesa** [IIC2343/syllabus#183]
Tengo unas dudas con respecto al largo de las lineas en la tarea 4.
-Primero ¿podemos asumir que siempre serán múltiplo de 2?, de no ser así como hacemos las aproximaciones correspondientes?
-Si es que el largo no es 2, ¿Como se hace para tomar los demás espacios de memoria que se deben llevar?, Por ejemplo si el largo de la linea es 4, si se accede a la memoria 13, habría que tomar la 12,13,14,15 o la 10,11,12,13?. En el primer caso, que pasaría si se tiene una memoria de 16 palabras accede a la memoria 15, dado que no se podría tomar la 15,16,17 y 18, ya que las ultimas 2 no existen. Lo  mismo para el segundo caso si es que se accede a la memoria 1, dado que no se puede tomar -2,-1,0 y 1. 
Espero que se entienda lo que pregunte, y gracias anticipadas por su tiempo.

**Comment by Hernan4444** [comment]
@vabesa puedes asumir que son multiplos de 2 y cuando este número es más grande, tienes que analizar cual es el "paquete de líneas" adecuado para ese bloque. 

Por ejemplo si tenemos 4 y llamo a la memoria 5, como son 4 líneas por bloque, el primero si o si tendrá del 0 al 3 (0,1,2,3) y por ello, el "paquete de líneas" que contiene al 5 son del 4 al 7 (4,5,6,7). En base a lo anterior, es facil encontrar un algorítmo adecuado.

Saludos ✌️
