### ISSUE TITLE
Control 5

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2343/syllabus#183]
¿Cuales serán los contenidos el control 5? - Pueden subir ejercicios tipos por favor.

Gracias

**Comment by frvalenzuela** [comment]
Hola @ignacioaraya1995 ! 

Los contenidos será todo referido a paralelismo a nivel de instrucción (cómo está escrito en los apuntes). En clase está como pipelining. 

Con esto entraría todo lo que sea pipeline y todos los hazards. 

Saludos !!

**Comment by mramirez7** [comment]
Pueden subir ejercicios?

**Comment by frvalenzuela** [comment]
Hola @mramirez7 !

Disculpa la tardanza de la respuesta, pero si fueron subidos.

Saludos!
