### ISSUE TITLE
Duda horario i proyecto

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2343/syllabus#184]
Hola! A que hora es la interrogación del proyecto? En horario de ayudantia o a las 18:30?

Saludos

**Comment by IriSalazar** [comment]
En el pdf decía que era en el horario de la I3. Así que supongo que a las 18:30

**Comment by Hernan4444** [comment]
@BenjaPrograma precisamente es en horario de I3, es decir, a las 18:30.

Saludos ✌️
