### ISSUE TITLE
Funcionamiento Basic Computer

### ISSUE THREAD

**Issue by gebalassa** [IIC2343/syllabus#184]
Saludos.

Después de varios intentos sigo sin comprender a cabalidad el funcionamiento del Basic Computer, así como para modificarlo e implementar los cambios en los que hemos estado trabajando.

¿Existe alguna guía o truco para entenderlo con mayor facilidad? ¿O sólo queda revisar las partes una por una e ir viendo cómo se conectan?

Al construir el diagrama mediante Vivado se obtiene un resultado cuyo desorden y complejidad lo vuelven inutilizable. Adicionalmente, al aplicar el bitstream que se nos entrega a la placa se produce un comportamiento extremadamente extraño e inexpicable.

Deseaba, entonces, saber si existe alguna forma de abarcar las modificaciones a Basic Computer (o Basic Computer de por sí) para evitar hacer trabajo redundante debido a la ausencia de una explicación concreta.

Siento que este fenómeno ha sido una constante a lo largo de las tareas y que es necesario que los enunciados sean más explícitos respecto al material de ayuda entregado y los requisitos que se buscan.

Gracias,
Gabriel.-

**Comment by FranLucchini** [comment]
Hola,

No hay un truco para entenderlo con mayor facilidad, en cierto momento hay que sentarse y pensar en qué el lo que está pasando. Si no están seguros de cómo hacerlo o cómo partir, yo espero que nos contacten.

Igualmente, lo que se genera al hacer el .bit no es muy importante, dado que la idea es modificar la arquitectura.

La ausencia de guía es intencional, ya que es el desafío de la tarea lograr armar el circuito pedido con sus propias habilidades.
