### ISSUE TITLE
Ejemplo está mal?

### ISSUE THREAD

**Issue by naquiroz** [IIC2343/syllabus#185]
Hola! Estaba pensando en el ejemplo que se entrega en el enunciado (que está en el syllabus), y creo que está mal, o yo estoy entendiendo mal. Si vemos el ejemplo,

```assembly
; Se carga A = 3 , B = 5 y luego se guarda en la direccion de var1 el valor A + B .
MOV A ,3
MOV B ,5
ADD A , B
MOV ( var1 ) , A
; Note que ya no es necesario el segmento DATA , por lo que los
; labels de datos puede estar en cualquier linea del codigo .
; Mucho ojo con esto !!!!!
var1 0
```

El resultado es 
```binary
00000010 --- Opcode MOV A, L i t
00000011 --- Literal 3
00000011 --- Opcode MOV B, L i t
00000101 --- Literal 5
00000100 --- Opcode ADD A, B
00000000 --- Literal 0
00101001 --- Opcode MOV (Dir) ,A
00001000 --- Literal 0, ubicacion de var1
00000000 --- var1
11111111 --- Termino programa
11111111 --- Termino programa
```

Pero la ISA dice que
```Assembly
MOV (Dir),A ;=> Mem[Dir] = A
```
Entonces si yo hago

```Assembly
MOV (3),A ; Mem[3] = A
```
Pero en el ejemplo no están tomando el valor de `var1`, sino que están haciendo 

```assembly
Mem[8] = A ; 00001000 = 8 Porque Mem[8] = var1= 0
```

Podrían comentarme para entendir si soy yo el que lo está entiendo mal, o el ejemplo está mal? Dado que cambia harto la forma de resolverlo.

**Comment by jheysen** [comment]
Es la sintaxis para decirle que escriba en esa dirección solamente, no veo el problema con la tabla.

**Comment by naquiroz** [comment]
Que si sigo la tabla, no tiene sentido con el ejemplo con números.

Si yo hago
```assembly
MOV (3),A
```
Entonces, eso es Mem[3] = A? O acaso eso no se puede?

**Comment by jheysen** [comment]
Cuidado, de dónde estás sacando ese 3?

**Comment by naquiroz** [comment]
Es solo un literal, en #168 se dijo que podíamos hacer eso si queríamos extender la funcionalidad al dis assmbler

**Comment by BSamilla** [comment]
@naquiroz 
Creo que tu problema es que estas confundiendo literales con direcciones de memoria.
(Supongamos que esos números son las direcciones de memoria (Deberían ser binarios pero así vale para la explicación)) 

0  - 00000010 --- Opcode MOV A, L i t
1  - 00000011 --- Literal 3
2  - 00000011 --- Opcode MOV B, L i t
3  - 00000101 --- Literal 5
4  - 00000100 --- Opcode ADD A, B
5  - 00000000 --- Literal 0
6  - 00101001 --- Opcode MOV (Dir) ,A
7  - 00001000 --- Literal 0, ubicacion de var1
8  - 00000000 --- var1
9  - 11111111 --- Termino programa
10 - 11111111 --- Termino programa

Lo que tu quieres es guardar el valor de A + B en la variable var1 que para el caso del ejemplo es la dirección 8, por eso es que el literal de la operación es 00001000 (8 :P).
Ahora bien la operación que tu dices MOV (3),A  si se puede PERO sobre-escribiría una de las instrucciones del programa y si llegara a realizarse un salto que hiciera que se leyera esa linea tendrías un gran problema, así que ten cuidado con eso.

Vale decir que solo para el ejemplo la dirección es 8 podría ser cualquiera de las 2**8 de la memoria  y ese es el valor que debes entregar como literal a las operaciones con (dir).

Saludos!
Mucho éxito!
