### ISSUE TITLE
T4 - Asignar paginas virtuales

### ISSUE THREAD

**Issue by danustilovsky** [IIC2343/syllabus#185]
Hola, se puede asumir que en la ejecucion de los programas no habran mas de un acceso a memoria que corresponda a una misma pagina virtual? De ser asi solo habria que preocuparse de asignar los marcos segun los criterios del archivo json?

Gracias,

**Comment by auirarrazaval** [comment]
Hola!

No, no se puede asumir eso. Tu programa debe obtener el numero de página de cada dirección virtual, y ese numero de página buscarlo en la TLB o Tabla de Páginas correspondiente.  Lo que suguieres tu sería asignar un marco por dirección virtual, lo que es erroneo. 
Saludos!

**Comment by danustilovsky** [comment]
Hola @auirarrazaval!

Si entiendo que hay que transformar el numero del acceso (direccion virtual) al numero de de pagina, me referia a que en un mismo programa podria darse que dos accesos diferentes al hacer la transformacion para obtener el numero de pagina virtual entreguen una misma pagina y por ende tener que hacer un cambio en una misma pagina de una direccion virtual a otra?

**Comment by auirarrazaval** [comment]
No entiendo a que te refieres con:

> hacer un cambio en una misma pagina de una direccion virtual a otra

Pero un programa si puede acceder a la misma página con distintas direcciones. En ese caso, para el segundo acceso, la pagina ya tendría un marco físico asignado en la tabla de páginas por lo que no sería necesario asignarle un nuevo marco. Además, en el caso de que sean accesos consecutivos o de que no se haya sacado la entrada de la TLB, ni siquiera sería necesario ir a la tabla de páginas de nuevo
