### ISSUE TITLE
Archivos de prueba tarea 4

### ISSUE THREAD

**Issue by Javierdr** [IIC2343/syllabus#185]
¿Existe la posibilidad de que suban algunos archivos de prueba para testear la tarea 4?
Saludos y gracias de antemano

**Comment by jpgonzalez4** [comment]
Me sumo a la petición de @Javierdr 👍

**Comment by Hernan4444** [comment]
Estamos trabjando en test que se subirán mañana en la tarde/noche.
Por el momento les recomiendo probar con el test de la prueba
> [1, 16, 20, 20, 7, 0, 7, 24, 22, 0, 2, 25, 31, 26]

Y comparar entre ustedes, como cambia el hit rate según las características de la caché. Pueden usar esta misma issue para comparar sus __hit-rate__.

Saludos ✌️
