### ISSUE TITLE
[T04] - Empate en LRU

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2343/syllabus#186]
Hola,

Que técnica debo usar para desempatar en el caso de que dos o más bloques hayan tenido una misma cantidad de accesos?

Sumando a esta pregunta, el acceso que genera que el bloque sea traido a, por ejemplo, la TLB, cuenta para este criterio?

**Comment by frvalenzuela** [comment]
Hola @Jiruiz2 !

Revisar #194 

Saludos!
