### ISSUE TITLE
PC al MuxDataIn. Esta bien?

### ISSUE THREAD

**Issue by norman123123** [IIC2343/syllabus#186]
Según el dibujo que nos dan en el enunciado, hay una conexión entre el PC y el MUX DataIn , que va a la RAM.
No entiendo por qué, siendo que debería guardarse solo el valor del PC+1, no del PC. 
El valor del PC debería entrar solo al MuxAddress. 
Esta bien esto?

Saludos

**Comment by Geeermy** [comment]
¡Hola!

Eso da lo mismo. En la práctica no es necesario y tampoco les pedimos que hagan el mismo diagrama, puedes prescindir de esa conexión y debiese funcionar.

¡Que estés bien!
