### ISSUE TITLE
Duda memoria principal y librería tarea 4

### ISSUE THREAD

**Issue by jisilvamc** [IIC2343/syllabus#186]
Hola, un par de dudas:
Primero, no nos queda muy claro qué se supone que hay en la memoria principal al partir... ¿en teoría es necesario hacer una llena de 0s? ¿O no hacemos reemplazos reales y sólo guardamos los datos sobre si hubiera sido un miss o no? Es decir, ¿hacemos el cambio real del dato o sólo cambiamos el tag que está en la caché?
¿Se puede usar la librería operator, en particular attrgetter?

Gracias de antemano

**Comment by Hernan4444** [comment]
En esta tarea no buscamos ver que pasa con la memoria principal. Solo analizar la caché y para ello, con solo ver los tag debería bastar.

Y si puedes usar operator.
