### ISSUE TITLE
[T04] - Cantidad de lineas TLB

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2343/syllabus#187]
Hola,

Quería saber si las líneas son la cantidad de bloques que almacena la TLB o a que se refieren.

**Comment by auirarrazaval** [comment]
Hola!
La TLB (y la Tabla de Páginas) no almacena ningun bloque.  Cuantas lineas tiene una TLB se refiere a cuantas relaciones ```Numero de Pagina -> Numero de Marco``` puede almacenar ~~(**spoiler~:** La puedes imaginar como un diccionario en python)~~
