### ISSUE TITLE
[T06] Problema condiciones de salto

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#187]
Hola, 
No me di cuenta hasta ahora, pero creo que hay un error con las condiciones de salto que nos dieron en el enunciado.
![imagen](https://user-images.githubusercontent.com/37153467/46898974-6b79dc80-ce64-11e8-9dd3-7c8bd8de1ebf.png)
Por ejemplo, para el JGE (jump si es mayor o igual) no tendría que saltar si n = 0 or z = 0, en lugar de solo n=0? Lo mismo pasa con otras instrucciones, como el JLT, por ejemplo.
Pregunto por saber si implemento lo que se supone deben hacer estas instrucciones o si me ciño a la isa entregada.

**Comment by BSamilla** [comment]
Hola!

Podrías implementarlo de esa forma, PERO no es necesario ya que basta con n = 0, esto ultimo ocurre cuando la resta A - B NO es negativa, vale decir si fue positiva o 0.

Saludos!

**Comment by jmwielandt** [comment]
Ohhh! Cierto! Muchas gracias jaja
