### ISSUE TITLE
Tarea 4 - Preguntas

### ISSUE THREAD

**Issue by MrEarle** [IIC2343/syllabus#188]
En la parte de preguntas de la tarea 4 se pide:

> Con el enunciado, se les entregaron 6 archivos de prueba, los cuales corresponden a los mismos 3 conjuntos de programas, ejecutados con distintos parametros. Para cada programa debe especicar que conjunto de parametros es mejor, y por que (ProTip: Use los resultados de su simulacion para respaldar sus argumentos).

Cuales son estos archivos de prueba? Porque los 7 tests entregados tienen todos distintos conjuntos de programas. O debemos cambiar estos tests nosotros para obtener los resultados?

**Comment by frvalenzuela** [comment]
Hola @MrEarle !

Deben cambiarlos ustedes.

Saludos!
