### ISSUE TITLE
Secuencia xW Tarea 4

### ISSUE THREAD

**Issue by nachojarasaez** [IIC2343/syllabus#188]
Hola no entiendo muy bien que indica el W que acompaña al numero en la secuencia. Quiere decir que lo escribo directo en la memoria principal independiente de la forma que escribo los datos?. Cual es la diferencia con el que no lo lleva? 
Gracias

**Comment by Hernan4444** [comment]
@nachojarasaez, el W quiere decir que esta lectura de la memoria involucra tambien una escritura, lo cual implica que según la política de escritura, este dato será escrito o no en la memoria principal. Finalmente escribir en memoria principal o no, puede cambiar el write-miss.

Los que no tienen W significa que son solo lecturas.

Saludos ✌️
