### ISSUE TITLE
Tarea 4 - tiempos

### ISSUE THREAD

**Issue by cristobalilabaca** [IIC2343/syllabus#189]
Tengo un par de dudas con los tiempos que tenemos que medir en la tarea:
1. el tiempo que se demoran los swaps como lo calculamos? No se nos da en ninguna parte el tiempo de acceso a disco, por lo que no se como calcular el tiempo que demoran estas acciones.
2. El tiempo de lectura de la cache y TLB es solo uno? Esto a pesar de que la lectura termine en un miss?

**Comment by Sforrego** [comment]
me sumo a la duda,
si es un miss debo escribirlo y luego volver a leerlo, seria en ese caso 
tiempo de escritura + 2tiempo de lectura?

**Comment by auirarrazaval** [comment]
#194

**Comment by auirarrazaval** [comment]
Duplicate of #194
