### ISSUE TITLE
Cuales son los statesment process y los Case?

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2343/Syllabus#19]
Cuales son los statemenst process y los Case? Que creo que hice la tarea con statements process, pero no estoy seguro, ademas cuales son los Case, no quiero pasar a usarlos sin saber :c

**Comment by jjaguillon** [comment]
Estimado, le dejo un par de ejemplos de *Statement Process* y *Case*. 

## Recordar que estos statements están totalmente prohibidos para la entrega


Ejemplo de *process*:
```
BEGIN
	PROCESS
	BEGIN
	...
	x <= `1`; 		
	IF x=`1` THEN
		action_1;
	ELSE
		action_2;
	END IF
	...
	END PROCESS;
```

Ejemplo de *case*:

```
case SEL is
  when "01" =>   Z <= A;
  when "10" =>   Z <= B;
  when others => Z <= 'X';
end case;
```

**Comment by Ignacioislae** [comment]
Vale muchas gracias!! , y puedo hacer el trabajo con el comando:         
signal cable: std_logic;  
y sin los with/select?

**Comment by jjaguillon** [comment]
El uso de signals y with/select **siempre ha estado permitido**. 

Pasa a ser tu decisión usarlos o no.

Saludos
