### ISSUE TITLE
Dudas con outliers RGB -> CMYK 

### ISSUE THREAD

**Issue by narierao** [IIC2343/Syllabus#19]
Hola, Quería saber cómo manejo el caso de que (k = 255 - max) me diera 255 (es decir, max = 0).

Saludos!

**Comment by ceosorio** [comment]
Hola @narierao!

En el caso que `max = 0`, significaría que `R, G, B` son todos igual a `0`. Piensa a qué color correspondería, y luego ve qué pasaría entonces al convertirlo a CMYK.

Éxito en la tarea! ✨

**Comment by narierao** [comment]
Gracias! ya solucioné ese caso, pero aún así me falla uno, seguiré pensando.

Gracias!
