### ISSUE TITLE
Punto de partida ejercicio teorico tarea

### ISSUE THREAD

**Issue by miortiz1** [IIC2343/syllabus#19]
Si una compuerta necesitan 2 inputs para funcionar de donde saca los primeros 2 inputs para comenzar el ciclo en el ejemplo de la tarea?

**Comment by jmwielandt** [comment]
Te recomiendo que leas bien el enunciado. Las preguntas que hacemos deberían orientar tu respuesta. 
También puedes añadir imagenes, esquemas y demás para complementar tu explicación.

**Comment by ariel-m-s** [comment]
Hola @miortiz1! Me gustaría complementar la respuesta de @jmwielandt.

En primer lugar, me parece que tu pregunta es **súper interesante**. Este es (en parte) el análisis que estamos buscando de parte de ustedes. Basándome en tu respuesta puedo inferir que vas bien encaminado.

Para ayudarte un poco con la resolución del ejercicio, te voy a pedir que pienses en todos los posibles estados en los que podría encontrarse un cable dentro un circuito lógico binario. Estos son dos: **cero y uno**. Básicamente, el cable puede tener corriente o no tenerla; **no existe otra opción**. Es decir, que un cable (ya sea _input_ o _output_ de una compuerta) siempre contendrá un valor lógico-binario **válido**, que puede **cambiar** dependiendo de la naturaleza propia del circuito.

Para responder correctamente a las preguntas planteadas en el ejercicio es necesario abstraerse de la idea de un circuito lineal, en el que los cables van tomando valores a medida que reciben el _output_ de una compuerta anterior. En el caso de un circuito con ciclos, el concepto de **anterioridad** no es fácilmente distinguible o, en algunos casos, no existe.

Ánimo!
