### ISSUE TITLE
Interprete y assembly

### ISSUE THREAD

**Issue by IriSalazar** [IIC2343/syllabus#19]
Hola! Podrían explicar un poquito como leer lo que sale en el Assembler que subieron cuando corremos el código?
Y trato de abrir el interprete (ambos archivos) pero no me funciona. Como que abre la ventana y se cierra. Como hago para usarlo? 

Saludos!

**Comment by IriSalazar** [comment]
ok lo del assembler no, ya lo entendi. pero si lo del interprete por favor? :)

**Comment by MainScientist** [comment]
Ambos interpretes funcionan de distinta manera. El primero `interpreter.zip` intentará abrir una ventana en donde elijas el archivo .txt que quieras ejecutar, el cual debe contener el código de tu assembler.
El segundo `main-interpreter.zip` busca el archivo `main.txt` en la misma carpeta en donde está el `.zip` y lo ejecuta.

**Comment by IriSalazar** [comment]
Gracias!!
