### ISSUE TITLE
[Tarea 4][Tamaño del Dato]

### ISSUE THREAD

**Issue by dfvasquez** [IIC2343/syllabus#190]
Hola!

Me surgió una duda en la tarea. ¿De qué tamaño deben ser los datos que tenemos que manejar (en bits)? Pregunto esto para poder calcular el tag y que sea del mismo tamaño.  

Por ejemplo, en el test7 hay accesos al dato 7 y al dato 1005, lo que me entrega tamaños de bits bastante alejados. 🤔 ¿Sería una buena solución representarlos con el valor máximo? En este caso, ¿10 bits? 

Gracias!

**Comment by frvalenzuela** [comment]
Hola @dfvasquez !

El número de bits máximo por dirección virtual te lo dirá el tamaño de la memoria virtual (que en esta tarea se definió como el doble de la memoria física) y la cantidad de bits máximo por dirección física te lo dirá el tamaño de la memoria física especificado en el .json

Saludos!

**Comment by dfvasquez** [comment]
Creo que ya entendí una parte!

Muchas gracias @frvalenzuela. Ahora que tengo ese valor máximo, ¿cómo sé cuántos bits son los significativos y cuánto es el offset? ¿Siempre son 3? 😕 🆘

**Comment by frvalenzuela** [comment]
Hola @dfvasquez !

Recomiendo revisar #172 ! Allí se explica la cantidad de bits en direcciones virtuales.

Si todavía no queda claro, favor hacerlo saber y lo respondo con gusto.

Saludos!

**Comment by dfvasquez** [comment]
Hola @frvalenzuela lo entendí justo después de redactar tu preguna y lo confirmé leyendo esa issue! 😅 .

Muchas graciaaaaaaaaaaaas!
