### ISSUE TITLE
Creación repositorio práctico

### ISSUE THREAD

**Issue by julioag** [IIC2343/syllabus#190]
Estoy tratando de crear el repositorio para la tarea 7 pero al ir al link y inscribir mi grupo (12) , me aparece un error porque el nombre del grupo ya esta ocupado, pero no aparece ninguno con ese nombre en la lista de los repositorios para unirse.

**Comment by FranLucchini** [comment]
Qué extraño, voy a revisarlo y les aviso.

**Comment by julioag** [comment]
Si pude entrar.

Gracias.
