### ISSUE TITLE
[duda con la escritura en memoria]

### ISSUE THREAD

**Issue by roy350** [IIC2343/syllabus#190]
Hola!, disculpen pero me queda la duda de que si nos dan la politica de escritura whrite-through, solo se deben escribir en el momento que se ingresa a la cache, en memoria solo los numeros que tengan una W o también los demás? espero que se entienda la duda. Muchas gracias de antemano! :)

**Comment by Hernan4444** [comment]
@roy350 las escrituras solo se dan con la W, sin importar la política de escritura, 

Respondí tu duda?

**Comment by roy350** [comment]
y tambien me queda la duda de que al momento de darse una escritura, se aplican los mismos criterios de sustitucion y correspondencia que nos dan para usarlas en la cache verdad?

**Comment by Hernan4444** [comment]
se aplican exactamente igual, la única diferencia que si una escritura se efectúa en la memoria principal (no caché) debido al tipo de política de escritura o a una sustitución,  el write-miss aumenta.

**Comment by JaimeGo** [comment]
Con WT el write-miss puede ser sólo 1 o 0?
