### ISSUE TITLE
Duda con Write-Miss

### ISSUE THREAD

**Issue by kenzoak** [IIC2343/syllabus#191]
Si tengo que guardar en memoria principal un dato, este cuenta como un solo write-miss, o es uno por cada dato continguo almacenado en la linea del cache? 
Por ejemplo, si cada linea del cache tiene 4 palabras, y tenemos que escribir en la memoria principal un dato almacenado en esta caché, sería write-miss +4 ó write-miss +1? 
Muchas gracias

**Comment by Hernan4444** [comment]
sería write-miss +1, porque tiene que hacer la acción de escribir una vez en memoria para un bloque de datos. 

Saludos ✌️
