### ISSUE TITLE
[Tarea 4] - Page Fault y TLB

### ISSUE THREAD

**Issue by vramos1** [IIC2343/syllabus#191]
Cuando ocurre un page fault en el acceso a la TLB y la tabla de paginas, hay que cambiar la memoria física. Esto hará que quizá algunas entradas en la cache queden obsoletas. En este caso invalidamos toda la cache, o solo los datos que hacen referencia al marco físico a reemplazar??. Si es así eso cuenta cómo lectura/escritura en la caché??
También me gustaría saber que si la TLB posee 2 lineas, si cada linea es para una sola relación MarcoVirtual-MarcoFisico, o cada linea posee 2 datos como en la caché. 
Muchas Gracias

**Comment by frvalenzuela** [comment]
Hola @vramos1 !

Recomiendo revisar #194 ! Y respecto a cada línea tendrá una sola relación.

Saludos!
