### ISSUE TITLE
[Tarea 7][Práctico] Dudas variadas muchas (auxilio)

### ISSUE THREAD

**Issue by beayancan** [IIC2343/syllabus#192]
Hola, tengo bastantes dudas (y confusión) respecto de la tarea. No entiendo las lineas generales de lo que hay que seguir (Si pudiesen darnos pasos a seguir sería genial ❤️ )

1.- ¿Cada leds se refiere a un output o son un output en general  (arreglo de 16 bits)?
2.- Cuando se refiere IN A, 3, ¿se refiere a entregarle el valor que se ubica en el puerto 3 (en este caso un led) o al valor literal?
3.- ¿Cada uno de los switch es un input, o bien son un input como un conjunto (un input de 16 bits)? ¿solo se usa como input? ¿lo mismo para los botones?
4.- Conceptual: En los apuntes se señala que el adress decoder recibe la información de la CPU, ¿esto se refiere a la RAM, ROM o a otra cosa?
5.- En el port, ¿el data bus se refiere a lo que sale de la rom?
6.- En memory mapped, ¿El adress decorder recibe los 32 bits que entrega la rom? ¿es necesario agregarle según hacia donde va?
7.- Con lo que posee el computador basico 2, ¿están ya implementadas los jumps, subrutinas y demases, etc, etc, etc?
8.- De la ISA actual, los opcodes (que no se refieren a I/O) debemos implementarlos de igual forma, o bien, ya están implementados y funcionando correctamente y solo debemos implementar el paso de la información (si es que hay que hacer eso, honestamente no sé 😞) que van a tener los I/O.
😢😭 🙏

**Comment by jheysen** [comment]
1. Cada led es un output
2. Se refiere a que entregue a lo que esté por Port IO en el puerto 3
3. Si, cada switch es un input
4. Piensa en qué tiene que hacer tu address decoder
5. Al bus por donde transitan los datos
6. Por qué la ROM?
7. Tienes que revisar
8. Tienes que ver qué está y qué no
