### ISSUE TITLE
Tablas de pagina

### ISSUE THREAD

**Issue by miortiz1** [IIC2343/syllabus#192]
Hola, estaba leyendo los contenidos y despues de muchas vueltas, aun no logro entender donde y como se guardan las tablas de paginas. Tampoco entiendo si se guardaran en la memoria fisica y tengo cuatro programas, deberia dejar un espacio para las tablas y desues el resto del espacio sobrante dividirlo en 4 marcos d paginas?

**Comment by frvalenzuela** [comment]
Hola @miortiz1 !

Recomiendo revisar #167 !

Si todavía no queda claro hacerlo saber.

Saludos!
