### ISSUE TITLE
duda con el reemplazo en cache

### ISSUE THREAD

**Issue by roy350** [IIC2343/syllabus#192]
Disculpen me queda la duda de, si por ejemplo en un bloque de 2 palabras tengo [1,2W] y el siguiente numero a revisar es un 2, este si se reemplaza verdad? se debe considerar como si fueran 2 numeros distintos cierto? muchas gracias!

**Comment by Hernan4444** [comment]
Eso no se considera un reemplazo,  saludos :v:

**Comment by roy350** [comment]
osea en teoria, solo debo fijarme en el numero en si, y si son iguales es un hit y no hay reemplazo? indepentiende que tengan o no W?

**Comment by Hernan4444** [comment]
@roy350 precisamente, el W solo te influirá a efectos del write-miss, pero el hit o miss de una caché es solo por el hecho de encontrar o no la dirección de memoria en la caché.

Saludos ✌️

**Comment by roy350** [comment]
ohhh muchas gracias!! :D
