### ISSUE TITLE
Pautas evaluaciones

### ISSUE THREAD

**Issue by cjgazali** [IIC2343/syllabus#193]
Sería buenísimo tener pautas para aprender de errores y prepararse para el examen.

¿Será posible que suban una pauta al menos para la i2?

Con por favor y gracias :smiley:.

**Comment by Hernan4444** [comment]
@cjgazali este medio es para proyecto y tareas. Cualquier tema de cátedra, mandar mail a Jurgen.
Saludos ✌️
