### ISSUE TITLE
Duda swaps in

### ISSUE THREAD

**Issue by FernandoDeDiego** [IIC2343/syllabus#193]
Hola!
Tengo una duda con respecto a la memoria física y swaps in. Cuando comienza la ejecución de los programas, la memoria está vacía? Y de ser así, cada vez que traigo un dato, aunque no haya habido page fault, corresponde a un swap in?
Saludos

**Comment by auirarrazaval** [comment]
Hola! 

No, swap in es solo cuando se lleva un marco de disco a memoria física, en un principio solo se asignan marcos vacíos a páginas, no se trae nada de disco

**Comment by FernandoDeDiego** [comment]
Perfecto, entonces el número de swaps in es igual al número de swaps out? Y la asignación en base a qué se hace? Gracias por las respuestas.

**Comment by auirarrazaval** [comment]
No, no son iguales, revisa en qué casos ocurre swap in y en cualea swap out, te darás cuenta que uno ocurre mas veces qie el otro.
La asignacion en un principio es segun que marco esta libre, despues segun la política de reemplazo especificada en el archivo input

**Comment by VicenteMelin** [comment]
Hola! me surgieron algunas dudas leyendo esta issue. 
En un inicio la memoria física parte vacía, por lo que cuando el primer programa quiere acceder a la primera dirección no va a encontrar en la TLB el marco e iría a la tabla de paginas en el disco a buscar la entrada(cierto?). En este caso la tabla de paginas aun no ha asignado a las paginas virtuales a ningún marco por lo que se asigna a la pagina que busco el primer marco disponible(que va a estar disponible siempre en el inicio), esto también cuenta como page fault? o cuenta solo cuando la memoria fisica esta llena y despues debo hacer los swaps?
Otra duda @auirarrazaval, en el segundo comentario dijiste "swap in es solo cuando se lleva un marco de disco a memoria física", con esto te referías a cuando se lleva específicamente desde el swap file cierto? Ya que en un inicio el marco se lleva a la TLB desde la tabla de paginas(que también esta en el disco) después de que es asignado
Gracias!

**Comment by Jiparavich** [comment]
Me sumo a la pregunta de arriba

**Comment by auirarrazaval** [comment]
@VicenteMelin 

> En un inicio la memoria física parte vacía, por lo que cuando el primer programa quiere acceder a la primera dirección no va a encontrar en la TLB el marco e iría a la tabla de paginas en el disco a buscar la entrada(cierto?)

Si

> En este caso la tabla de paginas aun no ha asignado a las paginas virtuales a ningún marco por lo que se asigna a la pagina que busco el primer marco disponible(que va a estar disponible siempre en el inicio), esto también cuenta como page fault? o cuenta solo cuando la memoria fisica esta llena y despues debo hacer los swaps?

Si, tambien es un page fault

> Otra duda @auirarrazaval, en el segundo comentario dijiste "swap in es solo cuando se lleva un marco de disco a memoria física", con esto te referías a cuando se lleva específicamente desde el swap file cierto? Ya que en un inicio el marco se lleva a la TLB desde la tabla de paginas(que también esta en el disco) después de que es asignado

Si, con disco me refiero a la Swap File (Pero cuidado con que la tlb almacena direcciones, no marcos completos. Quizas te confundiste al escribirlo, pero nunca esta demás recordar ese detalle 😅)
