### ISSUE TITLE
Duda algoritmo de substitución dentro LFU

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2343/syllabus#194]
En los apuntes sobre LFU dice que 

> ' ...en caso de haber dos bloques empatados en menor cantidad de accesos, se ocuparía otro algoritmo para desempatar, generalmente FIFO....'

Podemos ocupar LRU como algoritmo para desempata? O se tomará como regla FIFO??

**Comment by Hernan4444** [comment]
Se considera fifo
Saludos :v:

**Comment by frvalenzuela** [comment]
Gracias :D!
