### ISSUE TITLE
[Tarea 4] IMPORTANTE - Aclaración de Dudas

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2343/syllabus#194]
### (Por favor leer todo)
Hola!

Para condensar algunas de las dudas que han surgido en muchas issues y la ayudantía, les pido por favor que lean esta issue compelta para poder ser lo mas transparente posible con todos los miembros del curso:

1. Nos disculpamos por no dejar en claro cuanto es el tiempo/velocidad de lectura y escritura para el disco. Como entendemos que es muy tarde para andar cambiando el enunciado completamente, se dejará como convencion que dichos tiempos coresponden a **10 veces los tiempos especificados para la Memoria Física** en el archivo de input.

2. El tamaño de la memoria virtual de cada programa será igual al doble del tamaño de la memoria física total

3. Tengan en consideración que ~~tanto las tablas de páginas como~~ el swap file se encuentran en disco (Por lo que además se puede asumir que tienen infinita capacidad 😮)
Las tablas de página se especifican en la issue #167

4. En caso de empate de algun algoritmo de reemplazo, se usa criterio FIFO para desempatar.
 
5. Cualquier escritura en alguna **caché** (solo cachés) que implique solamente un cambio de bit de metadata (valid bit, dirty bit, etc...) puede ser considerado una escritura atómica (se demora 0s). Esto incluye la invalidación de TLB durante el cambio de contexto y los datos que usen para determinar FIFO, LRU, etc...

6. TL,DR: A lo más se lee y escribe una vez en cada componente por cada dirección que se desea acceder.
Al momento de actualizar un valor en algun componente, no se requiere buscar ese valor nuevamente en dicho componente para usarlo durante la misma "solicitud". Por ejemplo: Si busco un marco en la TLB y no está, luego hago todo el proceso correspondiente para encontrar su marco asignado. Luego actualizo aquella entrada en la TLB, no es necesario que lea la TLB denuevo para tener el marco encontrado (solo durante la misma solicitud de dirección, si despues otra solicitud apunta a la misma página, si se debe buscar).

7. Lo que se les está pidiendo es simular los accesos a memoria, no obtener los datos en dichos accesos, por lo que no se compliquen con eso al momento de modelar su programa.

8. Cuando se hace swap out de un marco en memoria física, es lógico invalidar todas las entradas de la caché que apunten a direcciones dentro de ese marco, ya que cuando ingrese el nuevo marco, en caso de no invalidar, habría inconsistencia en los datos. (Repito: SOLO LAS LINEAS QUE APUNTABAN AL MARCO SACADO)

9. Al usar un protocolo tipo *Write-Back*, cada vez que se invalide una entrada en la caché de la memoria física, se debe actualizar la entrada correspondiente en la memoria misma para mantener consistencia (cada entrada actualizada corresponde a una escritura). Obviamente en el caso de los swap outs esto debe ocurrir antes de sacar el marco.

10. Esto es mas un tip que creo que si lo empiezan a aplicar y lo entienden, se les va a aclarar un poco ese ámbito de la tarea: No es lo mismo hablar de una **página** que se un **marco**. Página corresponde a el bloque de datos en la memoria VIRTUAL, Marco es el bloque de datos en la memoria física. Es importante entender esta diferencia para evitar confusiones del estilo: "Cual es la diferencia entre marco virtual y el marco físico" y similares (No existen los "marcos virtuales"). 

Perdón por el largo, pero creo que era necesario incluir todos esos puntos.

Saludos y suerte con la tarea!, aún queda mucho tiempo 😄. Cualquier duda que tengan aquí estamos.

**Comment by chocopiano** [comment]
para el punto 4 es posible que sea random tambien? Yo lo hize trabajando de esa forma y y tenia pensando especificarlo en el readme.

**Comment by auirarrazaval** [comment]
@chocopiano
Lamentablemente, y como se especificó en el aviso de siding, la tarea se corregirá con los criterios expuestos anteriormente.

**Comment by chocopiano** [comment]
Entiendo pero esta tarea se subio hace más de una semana y me tuve que organizar con mis tiempos, lamentablemente la otra semana estoy muy lleno de cosas y tuve que partir con esta tarea con anticipación. Siento que se debería tomar en cuenta lo que digo, porque me perjudica totalmente que 3 diás antes de la entrega avisen esto. Esta bien, hay tiempo pero son días que yo los tenia planificado para otras cosas. De no poder tomarse en cuenta lo que digo, me gustaría pedir más tiempo ya que al final tendre que hacer cosas nuevamente y por ende fue tiempo perdido. Espero que me entienda, saludos.

**Comment by sipoblete** [comment]
opino los mismo!

**Comment by RobinCuevas** [comment]
En mi caso pasa lo mismo, comencé con la tarea hace bastantes días atrás y siguen habiendo aclaraciones que al menos para mi terminan siendo modificaciones o cosas que agregar que requieren tiempo.
Es importante aclarar que sólo busco que tengan un poco de empatía considerando estas aclaraciones a pocos días de la entrega.

**Comment by MrEarle** [comment]
@auirarrazaval no que las tablas de páginas estaban en memoria (una memoria aparte con infinita capacidad)? Porque eso cambiaría los tiempos de memoria, ya que leer o escribir en las tablas de páginas no contaría para la estadística MT

**Comment by rjdelrio** [comment]
> 
> 
> Entiendo pero esta tarea se subio hace más de una semana y me tuve que organizar con mis tiempos, lamentablemente la otra semana estoy muy lleno de cosas y tuve que partir con esta tarea con anticipación. Siento que se debería tomar en cuenta lo que digo, porque me perjudica totalmente que 3 días antes de la entrega avisen esto. Esta bien, hay tiempo pero son días que yo los tenia planificado para otras cosas. De no poder tomarse en cuenta lo que digo, me gustaría pedir más tiempo ya que al final tendre que hacer cosas nuevamente y por ende fue tiempo perdido. Espero que me entienda, saludos.

opino lo mismo no lo encuntro justo para nada.

**Comment by Taeval** [comment]
Opino lo mismo que @chocopiano . No puede ser que más de una semana después de que se haya subido la tarea se agreguen nuevos criterios para la corrección.

**Comment by Arcoirisky** [comment]
Hola~

Primero que todo, el criterio que se agregó sólo fue la politica de reemplazo y debido a esto si está considerado darles un par de días más (en vez del **martes** que se entregue el **jueves** a la misma hora). 

El resto son consultas que se han repetido demasiado y se decidió integrarlas en una sola issue para que todo quede aclarado. Además, es materia pasada :c No son supuestos ni requerimientos nuevos, es la materia :c ó detalles que les serán utiles a quienes estén perdidos :c 

Entendemos que es fin de semestre y todos estamos colapsados :c Por eso el no darles más tiempo sería ridículo. La idea es que entiendan los contenidos y puedan aplicarlos de la mejor forma posible, no solo buscar una nota :two_hearts:

**Comment by Dyoma3** [comment]
@Arcoirisky yo creo que la solucion de entregarla el jueves va a servir de poco. Yo, como muchos otros, tenemos muchas cosas para la otra semana. Eso de FIFO en vez de random no creo que sea algo de entender conceptos. 
Ademas, con respecto a la siguiente aclaracion : 'Por ejemplo: Si busco un marco en la TLB y no está, luego hago todo el proceso correspondiente para encontrar su marco asignado. Luego actualizo aquella entrada en la TLB, no es necesario que lea la TLB denuevo para tener el marco encontrado (solo durante la misma solicitud de dirección, si despues otra solicitud apunta a la misma página, si se debe buscar).' 

En apuntes sale : 
    'b) En caso de que la TLB no tenga la entrada, ocurre una excepcion denominada TLB miss exception la cual entrega el control al sistema operativo para que este vaya a buscar a la
tabla de paginas del proceso actual la entrada, y la copie a la TLB. Cuando el sistema operativo
vaya a buscar la entrada, hay dos posibilidades: si la entrada esta marcada como que esta en
memoria, o si esta marcada como que esta en disco:
1) Si esta marcada que esta en memoria, el SO copia la entrada a la TLB, y se repite el acceso
a esta, esta vez ocurriendo un hit.'

Es decir, se hace un acceso nuevo.

**Comment by Arcoirisky** [comment]
@Dyoma3  Basicamente se refieren a lo mismo solo que algunos consideraban que existía un miss-hit a la vez, produciendo un incremento nulo en la estadística. Pero realmente lo que cuenta para las estadísticas es un miss, a pesar de que sea un hit el que permita continuar con la operación. 

Es solo la respuesta a una duda recurrente que hemos notado en el curso o:

Y se pide FIFO en vez de Random porque las estadisticas serán variables en los outputs de los tests.

**Comment by pgarnham** [comment]
@auirarrazaval @frvalenzuela  @Arcoirisky  En la Issue #167 se menciona que las tablas de página quedaban en memoria principal, pero sin tener que preocuparse del espacio requerido. Algo así como una memoria principal aparte para las tablas de paginas. No en disco, como se dice más arriba. 

Esto fue hace 6 días.  Yo ya estructuré la tarea de esta forma, y por mucho que den más tiempo, hay más ramos. No se puede reestructurar una semana llena de cosas así como así. Espero que se pueda considerar como correcta la estructura mencionada.

**Comment by Dyoma3** [comment]
@Arcoirisky y podria ser el de menor indice? yo creo que seria para muchos mas facil que implementar FIFO. Por ejemplo, si estoy usando LFU y esta empatado el bloque 0 con el 1, reemplazar el 0. Alguien mas lo hizo asi o le acomoda mas?

**Comment by Arcoirisky** [comment]
@Dyoma3 Eso sería crear un nuevo protocolo de reemplazo. En lo personal, nadie debería de haberlo hecho de esa forma sin antes parar a preguntarlo por una issue.

@pgarnham, tienes razón. La posición de la tabla de página sigue la issue #167 :sweat_smile: deja que corrijo la issue :D

**Comment by Jiparavich** [comment]
@Arcoirisky 
Hola!, finalmente cual seré el nuevo plazo de entrega (si es que hay)?

Slds

**Comment by ignacioaraya1995** [comment]
Ojalá sea el **Viernes** como último plazo, mucha gente tiene prueba el Jueves!

**Comment by Jiparavich** [comment]
@Arcoirisky 
No entiendo bien cuando mencionas "Basicamente se refieren a lo mismo solo que algunos consideraban que existía un miss-hit a la vez, produciendo un incremento nulo en la estadística. Pero realmente lo que cuenta para las estadísticas es un miss, a pesar de que sea un hit el que permita continuar con la operación."

Si no me equivoco, no hay un incremento "nulo" en las estadísticas, ya que estamos contando por separado los hits, los miss y los numeros de accessos. Y según los apuntes, sería un miss, seguido de un hit...
Entonces, según sus "aclaraciones", no contamos el segundo hit??

**Comment by Jiparavich** [comment]
> @Arcoirisky
> No entiendo bien cuando mencionas "Basicamente se refieren a lo mismo solo que algunos consideraban que existía un miss-hit a la vez, produciendo un incremento nulo en la estadística. Pero realmente lo que cuenta para las estadísticas es un miss, a pesar de que sea un hit el que permita continuar con la operación."
> 
> Si no me equivoco, no hay un incremento "nulo" en las estadísticas, ya que estamos contando por separado los hits, los miss y los numeros de accessos. Y según los apuntes, sería un miss, seguido de un hit...
> Entonces, según sus "aclaraciones", no contamos el segundo hit??

??????

**Comment by tomasrivera** [comment]
@Jiparavich para evitar confusión, esta estadística es super simple. Si la dirección/página está en la _caché/TLB_ es un _hit_, en caso contrario es un _miss_.

**Comment by Jiparavich** [comment]
Ok
