### ISSUE TITLE
Mapeo NWA cache

### ISSUE THREAD

**Issue by Taeval** [IIC2343/syllabus#195]
Tengo dudas sobre cuales son los bits de una dirección de la memoria física que tengo que usar ara determinar el set de la cache al que le corresponde. ¿Cuántos son? ¿Son los más significativos o los menos significativos?

**Comment by frvalenzuela** [comment]
Hola @Taeval !

Recomiendo revisar #166 !

Si quedan dudas favor avisar.

Saludos!
