### ISSUE TITLE
escritura en memoria

### ISSUE THREAD

**Issue by roy350** [IIC2343/syllabus#195]
Hola tengo la duda de que si me toca escribir en memoria un 2W por ejemplo, si la palabra por bloques son 2 por ejemplo debo tambien escribir 3W en memoria?

**Comment by Hernan4444** [comment]
@roy350 no, si se solicita el 2W y los bloques son de 2 líneas, entonces la caché traerá la memoria 2 y 3, pero solo la 2 quedará marcado como que fue escrito.

Saludos ✌️

**Comment by roy350** [comment]
Otra duda referida a lo mismo, si por ejemplo tenemos un bloque con 4 palabras, por ejemplo [0W,1W,2,3W], teniendo write back como escritura, y si se va a reemplzar este bloque se debe escribir en memoria el 0,1 y 3?

**Comment by Hernan4444** [comment]
@roy350 creo que esta issue responde tu duda #192

**Comment by roy350** [comment]
Creo que no me entendiste bien la duda :(, por que la otra pregunta era si era lo mismo un numero con o sin W. Acá me refiero a que si un bloque tiene mas de un numero con W, si estos se deben escribir o no en memoria al momento de reemplazar

**Comment by Hernan4444** [comment]
aaa ya, si un bloque tiene más de un W, igual se considera como 1 write. porque la caché escribirá todo el bloque como un paquete en la RAM.

Saludos ✌️

**Comment by berrazuriz1** [comment]
si ya lo hice de la otra forma lo puedo dejar asi y explicitar en el readme?

**Comment by Hernan4444** [comment]
@berrazuriz1 no, una caché no funciona así y hace unos días también preguntaron eso. Si lo dejas así es demasiado probable que algunos test no den resultado correcto y esta tarea solo evalúa output, no hay readme ni revisión de código.

Saludos ✌️

**Comment by Hernan4444** [comment]
**pero** considerando el tiempo, eso es 100% apelable en la recorrección (lo corrigen después y se sube la nota), Pero para la primera corrección que es automatizada, no se considera bueno para poder corregir lo más rápido posible eso.

**Comment by berrazuriz1** [comment]
Ya lo cambie, gracias igual
