### ISSUE TITLE
Posibilidad de mas informacion de los test

### ISSUE THREAD

**Issue by roy350** [IIC2343/syllabus#196]
Hola! queria saber si existe la posibilidad de los test que dieron respuestas, dar mas informacion como hit realizados, writes realizados, accesos totales y escrituras totales, seria de gran ayuda! muchas gracias de antemano!

**Comment by vabesa** [comment]
@Hernan4444 Si porfavor! Ademas puede ser que el test 3 este malo? A mi me da que tiene 6 escrituras efectivas, por lo tanto el miss write debiese ser 6/7 o no?

**Comment by roy350** [comment]
Te esta pasando el mismo error que a mi!, resulta que debes considerar por bloques, no por cuantos elementos con W se escriben en memoria, me explico creo que un bloque te quedaba del estilo [0W,1,2W,3W] y eso se tenia que guardar en memoria, eso cuenta como un miss, independiente que sean 3 valores, solo se escribe una vez en memoria, debes fijarte solo en cuantos bloques escribes y no cuantos elementos escribes :) asi que si es asi seria 2/7 por que se escribe otro bloque mas, eso!

**Comment by vabesa** [comment]
@roy350 Muchas gracias! Ahora me funciono perfect!
