### ISSUE TITLE
[Tarea 4] Numero de pagina y offset

### ISSUE THREAD

**Issue by jnpoblete** [IIC2343/syllabus#196]
Hola, tengo una duda con los apuntes. En ellos aparece lo siguiente:

...Al ser el espacio de direccionamiento de 8 bits (2**8 = 256 palabras en memoria), la dirección de 8 bits se dividirá en los 3 bits más significativos para indicar el número de página (2**3 = 8 páginas), y los 5 bits restantes para indicar el offset (2**5 = 32 palabras por página).
Para determinar la ubicación fı́sica de la dirección virtual 70 del programa 2, por ejemplo, se debe realizar los siguientes pasos:
Primero es necesario obtener la dirección en binario: 70 = 01000110. ....

El problema surge al replicar esto con el test 7 de la tarea, donde la secuencia específica un 1005 para un memoria física de 512 . Según los apuntes sería 2**9 el espacio de direccionamiento (lo cual es correcto 512=2**9) pero para representar el 1005 necesito 10 bits (1005=1111101101). Entonces los apuntes están mal? . Se debería representar el 70 con 9 bits y no con 8?

**Comment by frvalenzuela** [comment]
Hola @jnpoblete !

Los apuntes están bien, solo se asume en ese ejemplo que la memoria física y la memoria virtual del mismo tamaño (se asume implícitamente). Para el caso de la tarea, la memoria virtual es el doble que la memoria física por lo que tenemos 10 bits efectivamente para direccionar.

Espero que eso aclare la confusión.

Saludos!
