### ISSUE TITLE
Diagrama Teórico

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2343/syllabus#197]
Hola, qué tal? 
Para el Diagrama que se solicita, el nivel de especificidad debe ser de este estilo: 
<img width="457" alt="captura de pantalla 2018-10-23 a la s 17 19 33" src="https://user-images.githubusercontent.com/26261777/47388157-d8546880-d6e7-11e8-962f-b2ddc566077f.png">
O este? 
<img width="676" alt="captura de pantalla 2018-10-23 a la s 17 20 08" src="https://user-images.githubusercontent.com/26261777/47388179-e7d3b180-d6e7-11e8-82be-850bece1f2f7.png">

**Comment by nfbalbontin** [comment]
si :)

**Comment by Geeermy** [comment]
@nfbalbontin Sería lo segundo, dado que explícitamente les pedimos un diagrama de la interacción de la CPU y memoria con los dispositivos I/O del contexto descrito.

Algo del estilo del primer diagrama es solicitado en la última parte. 😁

**Comment by vjmoreno** [comment]
@Geeermy tengo una duda respecto al segundo diagrama. Por qué el South Bridge no se conecta a la memoria del computador?

**Comment by Geeermy** [comment]
@vjmoreno Sí lo hace, solo que lo hace **a través del _North Bridge_ (ver apuntes).

Ahora... solo por si acaso: en lo que les planteamos nunca hacemos mención de estos componentes (_North Bridge_, _South Bridge_). No tienen que ponerlos.
