### ISSUE TITLE
Invalidacion cache caso NWA

### ISSUE THREAD

**Issue by Dyoma3** [IIC2343/syllabus#197]
Para invalidar los datos de la cache con NWA, hay dos casos:
CASO 1: Cuando el tamaño de pagina es mas grande al tamaño de conjunto (numero de bloques por conjunto * 2). En este caso, una pagina podria tener sus datos en distintos conjuntos de bloques, por lo que tendria que revisarlos todos para la invalidacion (tiempo de lectura).
CASO 2: En caso contrario, entonces si podria saber a priori en que conjunto se deberian encontrar todos los datos de la pagina y no seria necesario buscar en todos los conjuntos.

Mi duda es que, para el segundo caso, si lo hago de la forma 'inteligente' y no busco en todos los conjuntos mi tiempo de lectura seria menor. Sin embargo, no se como un computador podria saber eso (yo que estoy programando puedo saberlo facilmente). Yo creo que se asume que las paginas son mayores a los conjuntos en la construccion de un computador. Puedo asumir esto? y si no, entonces se hace el algoritmo 'inteligente' para ahorrarse tiempo de lectura ?

**Comment by frvalenzuela** [comment]
Hola @Dyoma3 !

Estoy un poco confundido, porque hablas de NWA y páginas? La TLB solo tiene full asociative como función de correspondencia. NWA se ocupa solo en la cache, la cual solo se preocupa de direcciones fisicas. Las tablas de página no se guardarán en la memoria física como se dijo en #167.

Espero que eso resuelva tu duda.

Saludos!

**Comment by Dyoma3** [comment]
Estoy hablando de NWA de la cache. No me refiero a las tablas de pagina, sino a los mismos datos del programa, que en la memoria principal se guardan por marcos (tamaño de las paginas).  Lo que pasa es que cuando invalido un marco con un tamaño menor a un set de la cache, entonces podria saber en que set se encuentra el marco

**Comment by frvalenzuela** [comment]
Hola @Dyoma3 !

Por favor no cierres las issue, porque podría que alguien más tenga la duda.

Saludos!

**Comment by Dyoma3** [comment]
@frvalenzuela creo que lo explique mal. No me refiero a las tablas de pagina ni nada relacionado con tlb. Me refiero a que, si los tamaños de los marcos en la memoria fisica (segun el parametro tamaño pagina) son menores al tamaño de un set o conjunto en una cache de NWA, entonces todos los bits que determinan el conjunto al que estan mapeados en la cache seran iguales para un mismo marco.

**Comment by frvalenzuela** [comment]
Hola @Dyoma3 !

Pero si tienes una memoria lo suficientemente grande, aún si los marcos fuesen de dos palabras, significará que necesitarás muchos bits para representar el número de marcos. Sigo sin entender muy bien tu duda, pero espero que lo dicho ayude a orientarte, de no se así favor decirlo.

Saludos!

**Comment by Dyoma3** [comment]
![image](https://user-images.githubusercontent.com/17127676/58989138-4bab7600-87b1-11e9-962a-0043e64ff161.png)

En este caso, los marcos (determinado por TamanoPagina) tienen 2 bloques. La cache es 4WA. Por lo tanto, todas las direcciones de un marco en especifico se guardaran en el mismo set de la cache (el bit que indica el set es el mismo). 
En el caso que haga un swap out, tengo que buscar en la cache los bloques correspondientes a invalidar. Para hacer esto, tengo que ir uno por uno leyendo los bloques de todos los sets (supongo que cuenta como tiempo de lectura, esto tambien es una duda) y cambio la validez si corresponde a una direccion del marco hizo swap out (esto especificaron que era un cambio atomico que no contaba como escritura). 
Mi duda es que, en este ejemplo que estoy mostrando, ya podria saber a priori en cual set podria estar cualquier bloque que se debe invalidar, por lo que no seria necesario buscar por toda la cache y se ahorarria tiempo de lectura. Considero esto o busco simplemente en toda la cache de todas formas?
