### ISSUE TITLE
Caso sin escritura

### ISSUE THREAD

**Issue by Javierdr** [IIC2343/syllabus#197]
Como el `write-miss = escrituras realizadas en memoria / escrituras totales` que pasa si no se realiza ninguna escritura me quedaria: `0/0`. ¿Que debería entregar en ese caso? 
Saludos.

**Comment by Hernan4444** [comment]
@Javierdr retornen 0 por favor. Aunque considerando el poco tiempo, si es que ocurre `ZeroDivisionError`, también lo tendré que aceptar.

Saludos ✌️
