### ISSUE TITLE
memoria principal y tablas de pagina

### ISSUE THREAD

**Issue by rjdelrio** [IIC2343/syllabus#198]
hola la verdad aun no entiendo, se supone que las tablas de paginas ahora están en el disco según la aclaración dada hace un 1 día atrás, entonces quería saber la memoria principal siempre tendrá por lo menos el espacio mínimo para poder tener 1 tabla de paginas de un programa o no?

**Comment by frvalenzuela** [comment]
Hola @rjdelrio !

Finalmente se decidió dejar todo como fue establecido en la #167 ! Recomiendo revisarla.

Saludos!
