### ISSUE TITLE
Tabla de Estados y Comandos 

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2343/syllabus#198]
Hola, qué tal? 
Una tabla de estados y comandos se refiere un poco a esto? 
<img width="298" alt="captura de pantalla 2018-10-23 a la s 18 57 04" src="https://user-images.githubusercontent.com/26261777/47393331-8b778e80-d6f5-11e8-9824-38941b8f6d7f.png">
En la que los sucesos son acciones que van ocurriendo a lo largo de la ejecución. 
O esto? 
<img width="553" alt="captura de pantalla 2018-10-23 a la s 19 14 03" src="https://user-images.githubusercontent.com/26261777/47394051-d7c3ce00-d6f7-11e8-9061-eddc34f46bd8.png">

**Comment by Geeermy** [comment]
¡Hola!

Lo segundo, tal como se vio en ayudantía. :eyes:

**Comment by movaldivia** [comment]
@Geeermy 
![image](https://user-images.githubusercontent.com/24725124/47512607-ee326c80-d852-11e8-9bec-9dbce5fb084b.png)

Ahí (pregunta donde se pide los comandos) se pide además las direcciones a qué se refiere? Es lo mismo que la ubicación, podemos poner "registro estado"?
