### ISSUE TITLE
[T04] POSIBLES TIEMPOS

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#199]
TLB:
1)Si esta en TLB es tlb_tiempo_lectura
2)Si no esta en tlb pero si en memoria fisica es tlb_tiempo_lectura+tlb_tiempo_escritura
3)Si no esta en tlb pero hay solo swap out es:tlb_tiempo_lectura+tlb_tiempo_escritura+MF_tiempo_escritura x10
4)Si no esta en tlb pero si en disco por lo que hay swap out y swap in seria: tlb_tiempo_lectura+tlb_tiempo_escritura+MF_tiempo_escritura x10+MF_tiempo_lectura x10

CACHE
1)Si esta en Cache es cache_tiempo_lectura
2) Si no esta en cache pero si en memoria fisica es cache_tiempo_lectura+cache_tiempo_escritura

Eso es lo que tengo entendido pero creo que esta super malo, porque en que momento usaría los tiempos de memoria fisica (no los multiplicados por 10)....Ojala me puedan corregir y explicar las situaciones que m faltan para añadir los otros tiempos...Gracias!

**Comment by brayanmoreno** [comment]
yo también tengo esa duda, pero así es como lo veo yo:

**MMU:**

- dirección marco está en TLB = TLB_lectura
- dirección marco NO está en TLB = TLB_lectura
  - validez = 1, disco = 0 += Disco_lectura + TLB_escritura
  - validez = 0, disco = 0 (page fault) += Disco_lectura
    - MF NO llena (asignar marco) += MF_lectura + TLB_escritura
    - MF llena (swap out y asignar marco) += MF_lectuta + Disco_escritura + TLB_escritura
  - validez = 1, disco = 1 (page fault, swap out, swap in y asignar marco) += Disco_lectura + MF_lectura + Disco_escritura + MF_escritura + TLB_escritura

**Caché:**

- Caché hit = Cache_lectura
- Caché miss = Cache_lectura + Disco_lectura + Cache_escritura

**Comment by auirarrazaval** [comment]
@chocopiano Siento que quizás estas confundiendo TLB con tabla de páginas, puede ser, por que en ningun momento mecionas los tiempos relacionados a asignar un marco en la tabla de páginas? 
Donde entra en juego el tiempo de la memoria física (sin el x10) es cuando se escribe en esta. Por ejemplo: Cuando se hace swap in: se lee el disco (MF_readx10), y luego se escribe en la memoria física (MF_write), en ese caso se usa el tiempo sin el x10

**Comment by chocopiano** [comment]
Entonces lo que dice @brayanmoreno esta correcto o no? Muchas gracias!

**Comment by auirarrazaval** [comment]
@chocopiano Si entendí bien, a @bryanmoreno le faltaría la escritura de la entrada en la tabla de paginas. Y revisando tu pregunta original, en los tiempos de la caché, cuando no esta en la cache te faltaría MF_tiempo lectura para ir a buscar el valor

**Comment by chocopiano** [comment]
Para los tiempos de swap sería [tiempo en leer en tabla de pagina+tiempo en escribir en disco] (Swap out) y [tiempo de leer en disco+tiempo de escribir en MF](Swap in) o me equivoco sobre como calcular estos tiempos?

**Comment by auirarrazaval** [comment]
Faltaría leer lo que se va a escribir en disco para el swap out

**Comment by chocopiano** [comment]
Espero que esta sea la vencida, usando lo @brayanmoreno, estaría bien esto:
MMU:

dirección marco está en TLB = TLB_lectura

dirección marco NO está en TLB = TLB_lectura:
            1. validez = 1, disco = 0 += MF_lectura + TLB_escritura
            2. validez = 0, disco = 0 (page fault) += Disco_lectura
                        - MF NO llena (asignar marco) += MF_lectura + TLB_escritura + MF_escritura
                        - MF llena (swap out y asignar marco) += MF_lectura + Disco_escritura + 
                           TLB_escritura+MF_escritura

              3. validez = 1, disco = 1 (page fault, swap out, swap in y asignar marco) += Disco_lectura + 
                     MF_lectura + Disco_escritura + MF_escritura + TLB_escritura

Caché:

Caché hit = Cache_lectura
Caché miss = Cache_lectura + Disco_lectura + Cache_escritura

Swap out: Disco_lectura+Disco_escritura+MF_lectura
Swap in: Disco_Lectura+MF_escritura+Mf_lectura
####################

**Comment by frvalenzuela** [comment]
Hola @brayanmoreno !

Para poder responder mejor, necesito saber específicamente, ¿cuál es la duda? Entre tanta explicación no me deja de quedar claro.

Saludos!

**Comment by chocopiano** [comment]
1) Si tengo 2 programas, y en el "1" ocurre un page fault y se provoca un swap out en el "2", todos los tiempos que hay involucrados en esta iteración se le suman a los tiempos del programa "1" o algunos corresponde al tiempo del programa "2" (el tiempo de hacer swap out en este caso, se debe  agregar al programa "1" o "2").

2) No me queda bien como funcionan los tiempos, y por lo estudiado y lo dicho por mi compañero de arriba llegue a la conclusión que los tiempos de cada caso que puede ocurrir en la simulación son como los escribi en el comentario anterior. ¿Quería saber, estoy en lo correcto con aquello o hay alguno que este malo? De ser así por favor corrijanme. Gracias!

**Comment by Felipehanckes** [comment]
Hola!

Todavía no me queda claro cuales son los tiempos de escritura y lectura de la tabla de paginas, estan bien explicados los de la TLB, Caché, Memoria fisica y swap, pero no encuentro los de las Tablas de paginas :cry: :face_with_head_bandage: 

Saludos!

**Comment by FernandoDeDiego** [comment]
Hola,
Es posible que los mensajes anteriores estén incorrectos, ya que se estaba considerando que las tablas de páginas estaban en disco? Ahora que estamos seguros que están en memoria física, deberíamos cambiar los tiempos de disco señalados arriba con tiempo de memoria física?
Saludos

**Comment by Jiparavich** [comment]
Hola, sumándome a los comentarios de arriba.

No entiendo bien como calcular los tiempos, porque tiempo "total utilzado" puede ser englobar muchas cosas...

**Comment by chocopiano** [comment]
@FernandoDeDiego  según tu como serían los nuevos tiempos? Si no te da lata podrías escribir los tiempos con los cuales hay discrepancias con los míos. LLevo varios días tratando de poder resolverlo y solo me estoy confundiendo más.

**Comment by FernandoDeDiego** [comment]
@chocopiano, yo también estoy bastante confundido. Pero creo que en la segunda issue que pusiste tiempos, en el punto 2 (cuando hay page fault), deberia ser MF_Lectura en lugar de Disco_lectura, dado que estás buscando la entrada en la tabla de páginas y esta última está en la memoria física. Sobre el resto, tampoco estoy seguro, de hecho he tratado de guiarme con esta issue.

**Comment by Dyoma3** [comment]
@chocopiano @FernandoDeDiego para los tiempos de lectura, consideran que estos estan dados para lineas, bloques y paginas? (tlb, cache y MF respectivamente).
Por ejemplo, si busco algo en la TLB y lo encuentro en la segunda linea, yo lo agrego 2 veces el tiempo de lectura (lei dos lineas)

**Comment by chocopiano** [comment]
@Dyoma3  no no, es solomanete un 1 tiempo de lectura, jamas lo vei por linea, sino que general

**Comment by chocopiano** [comment]
dirección marco está en TLB = TLB_lectura
dirección marco NO está en TLB :
a) validez = 1, disco = 0 TLB_lectura +MF_lectura + TLB_escritura
b) validez = 0, disco = 0 (page fault) 2 ocpiones:
1) Memoria llena (Page fault): TLB_lectura+MF_lectura++MD_escritura+MF_escritura+TLB_escritura
2)MF NO llena (asignar marco) TLB_lectura+MF_lectura + TLB_escritura + MF_escritura
c) validez = 1, disco = 1 (page fault, swap out, swap in y asignar marco) TLB_lectura+MF_lectura +Disco_lectura + Disco_escritura + MF_escritura + TLB_escritura

Caché:

Caché hit = Cache_lectura
Caché miss = Cache_lectura + Disco_lectura + Cache_escritura

Finlamente yo creo que asi usare los tiempos, no se me ocurre otra forma

**Comment by Dyoma3** [comment]
@chocopiano tengo duda en Caché miss = Cache_lectura + Disco_lectura + Cache_escritura

no deberia ser MF_lectura?

**Comment by chocopiano** [comment]
Tambien me hace sentido, dejemolo con MF_lectura.... los otros como encuentras que estan?

**Comment by Dyoma3** [comment]
ya buena, en todo caso en apuntes sale "En caso de que la cache no tenga la palabra, o sea que haya un miss, el controlador de cache debe ir a buscarla a memoria principal,"
lo demas segun yo esta bien, lo voy a hacer asi

**Comment by RobinCuevas** [comment]
Sí, yo igual lo haré considerando esos tiempos!

**Comment by chocopiano** [comment]
Si tengo 2 programas, y en el "1" ocurre un page fault y se provoca un swap out en el "2", para las estadisticas se considera el PF para el programa "1" pero el swap out lo consideran para el "2" o no? Siguiendo con el mismo ejemplo, el tiempo en este caso seria:
 TLB_lectura+MF_lectura+MD_escritura+MF_escritura+TLB_escritura
Este tiempo sería para el programa 1, o habria que sumar alguno de esos termino al programa 2? Y de ser esto ultimo cuales serian??? Que opinan @RobinCuevas @Dyoma3 @FernandoDeDiego @Felipehanckes

**Comment by Jiparavich** [comment]
> Si tengo 2 programas, y en el "1" ocurre un page fault y se provoca un swap out en el "2", para las estadisticas se considera el PF para el programa "1" pero el swap out lo consideran para el "2" o no? Siguiendo con el mismo ejemplo, el tiempo en este caso seria:
> TLB_lectura+MF_lectura+MD_escritura+MF_escritura+TLB_escritura
> Este tiempo sería para el programa 1, o habria que sumar alguno de esos termino al programa 2? Y de ser esto ultimo cuales serian??? Que opinan @RobinCuevas @Dyoma3 @FernandoDeDiego @Felipehanckes

Según yo, se le suma todo al programa "que esta corriendo"

**Comment by NicolasAguirre** [comment]
@chocopiano yo lo dejare tal como lo hiciste tu. Creo que eso NO esta explicado, asi que lo dejare a la lógica.

**Comment by Dyoma3** [comment]
@chocopiano lo voy a hacer como tu dijiste

**Comment by Felipehanckes** [comment]
> Si tengo 2 programas, y en el "1" ocurre un page fault y se provoca un swap out en el "2", para las estadisticas se considera el PF para el programa "1" pero el swap out lo consideran para el "2" o no? Siguiendo con el mismo ejemplo, el tiempo en este caso seria:
> TLB_lectura+MF_lectura+MD_escritura+MF_escritura+TLB_escritura
> Este tiempo sería para el programa 1, o habria que sumar alguno de esos termino al programa 2? Y de ser esto ultimo cuales serian??? Que opinan @RobinCuevas @Dyoma3 @FernandoDeDiego @Felipehanckes

Yo tambien asumi que el tiempo se le suma al que esta corriendo, porque es en sus ciclos donde pasa todo esto, el sistema Operativo ya esta trabajando sobre el.

**Comment by Jiruiz2** [comment]
> -dirección marco está en TLB = TLB_lectura
> -dirección marco NO está en TLB :
> a) validez = 1, disco = 0 TLB_lectura +MF_lectura + TLB_escritura
> b) validez = 0, disco = 0 (page fault) 2 ocpiones:
> 
> 1. Memoria llena (Page fault): TLB_lectura+MF_lectura++MD_escritura+MF_escritura+TLB_escritura
> 2. MF NO llena (asignar marco) TLB_lectura+MF_lectura + TLB_escritura + MF_escritura
> 
> c) validez = 1, disco = 1 (page fault, swap out, swap in y asignar marco) TLB_lectura+MF_lectura +Disco_lectura + Disco_escritura + MF_escritura + TLB_escritura
> 
> Caché:
> 
> Caché hit = Cache_lectura
> Caché miss = Cache_lectura + Disco_lectura + Cache_escritura
> 
> Finlamente yo creo que asi usare los tiempos, no se me ocurre otra forma

Holaa,

Te quería preguntar a que te refieres con MD, a la memoria del disco?

**Comment by chocopiano** [comment]
si Memoria del disco, que es 10 veces la memoria fisica!

**Comment by dedarritchon** [comment]
> 1. Memoria llena (Page fault):

Ojo que en esta issue: https://github.com/IIC2343/syllabus/issues/193#issuecomment-498001726
dijeron que el page fault no es solo cuando no quedan marcos disponibles. Osea cuando aun quedan marcos disponibles pero no se ha asignado en la tabla de paginas tambien es page fault

**Comment by chocopiano** [comment]
@dedarritchon en los apuntes sale esto:
"El problema ocurre si ahora uno de los programas quiere acceder a otra p ́agina, por ejemplo el programa 1 a la p ́agina 4. En este momento, la memoria f ́ısica est ́a ocupada completamente; es decir, al momento de ir a asociar un marco a la p ́agina 4 del programa 1, el sistema operativo se encuentra con que no hay marcos f ́ısicos disponibles. Esta situaci ́on se conoce como una falta de p ́agina o page fault"
Según page fault es solo cuando no quedan marcos disponibles

**Comment by dedarritchon** [comment]
mmm bueno lo que puse arriba lo escribio un ayudante asique espero que alguno nos diga cuando efectivamente ocurre un pagefault

**Comment by auirarrazaval** [comment]
@dedarritchon Si bien ahora no puedo revisar por que estoy sin mi computador, en la el power de memeoria que esta en el syllabus se define un page fault como un "miss" en la tabla de páginas (Era por la diapo 49 o 50) :eyes:

**Comment by javierabao** [comment]
> -dirección marco está en TLB = TLB_lectura
> -dirección marco NO está en TLB :
> a) validez = 1, disco = 0 TLB_lectura +MF_lectura + TLB_escritura
> b) validez = 0, disco = 0 (page fault) 2 ocpiones:
> 
> 1. Memoria llena (Page fault): TLB_lectura+MF_lectura++MD_escritura+MF_escritura+TLB_escritura
> 2. MF NO llena (asignar marco) TLB_lectura+MF_lectura + TLB_escritura + MF_escritura
> 
> c) validez = 1, disco = 1 (page fault, swap out, swap in y asignar marco) TLB_lectura+MF_lectura +Disco_lectura + Disco_escritura + MF_escritura + TLB_escritura
> 
> Caché:
> 
> Caché hit = Cache_lectura
> Caché miss = Cache_lectura + Disco_lectura + Cache_escritura
> 
> Finlamente yo creo que asi usare los tiempos, no se me ocurre otra forma

Para el caso No TLB -> Validez 0 -> Disco 0 -> Memoria llena ¿se puede escribir en el disco sin haberlo leído antes? ¿Basta con saber por la tabla de páginas que la página no estaba en disco, y después solo escribir al hacer swap out de otra página? Me hace ruido que en todos los otros componentes siempre se lea antes de escribir.

**Comment by Arcoirisky** [comment]
@javieraBao ¿Podrías ser un poco más precisa? Tiene sentido que siempre se lea antes de escribir porque lo primero que se hace es buscar si existe el dato que necesitas, ya si no está empiezas a editar todo lo necesario con tal de que lo tengas pero en principio, los procesos de un computador no tienen tantos casos considerados.

Siempre trabajan de la misma forma y a veces terminan generando estos “ciclos” miss-hit que confundían a muchos desde el principio. Se ahorran en inteligencia y por ende en componentes. Es decir, se ahorran en dinerillo y complejidad.

No estoy segura si logré responder tu pregunta, si no es así, por favor dímelo :D

**Comment by javierabao** [comment]
@Arcoirisky mi caso es específicamente cuando hay solo SWAP OUT, sin hacer SWAP IN. En la tabla de páginas va a aparecer que esa página no se encuentra ni en memoria física ni en disco, por lo que habría que escribir en disco el marco físico que se sacó para poder meter a otro. Pero antes de sacar ese marco físico, ¿se lee el disco? ¿o solo se escribe?
Hice ese diagrama, mi pregunta es si el camino 
ACCESO TLB -> Hit = no -> ACCESO TP -> Validez = no -> M.F. llena = sí -> SWAP/OUT ESCRITURA MEM FÍSICA
tiene bien considerado sus tiempos, que son las nubes dibujadas jajaja.
Los tiempos serían: tiempo lectura TLB, tiempo lectura MEM FÍSICA, tiempo escritura disco, tiempoe scritura mem. física, tiempo escritura caché y tiempo escritura TLB.

![diagrama_simulacion](https://user-images.githubusercontent.com/37162768/59114794-f76dd680-8915-11e9-9961-f3a37a2db93f.png)

**Comment by javierabao** [comment]
Ahora que lo pienso también pasa cuando se escribe en caché después de un page fault, cualquiera de los dos tipos (cuando no se encuentra ni en disco ni en mem física, o cuando se encuentra en disco pero no en mem física). ¿Hay que leer la caché antes de escribirla? Perdón si estoy muy enrededa, me ha costado demasiado entender esto.

**Comment by Felipehanckes** [comment]
Hola @javierabao , Según entiendo yo, para efectos de como nos dieron los parametros y especificaciones hasta ahora, sería de la siguiente forma ese camino:

- Tienes que leer TLB, como no esta ahi el marco, vas a ver tu tabla de pagina y te dice validez 0, disco 0.
- Luego vas a leer la memoria para encontrarlo. (este no es x10, porque solo en swap es x10 ,según entiendo por las issues)
- Encontces lo quieres escribir en memoria física y te das cuenta que esta llena.
- Tienes que hacer un swap out. (tiempo x10)
- Luego escribes en la memoria principal. (tiempo sin x10)
- luego escribes a TLB.

Para la cache es parecido, pero funcionaría asi:

-Esta en cache: tiempo leer cache nomas.

si no esta en cache:
- Tienes que leer cache y ver que no esta.
-Ir a buscarlo a memora (sin x10 porque como es write back, siempre lee y escribe luego de que ya esta en RAM)
- Luego que lo tienes, escribir en la cache el dato que obtuviste.

Ojalá esto te ayude!

**Comment by Jaluco** [comment]
Hay alguna conclusión de esta duda? entre tanta explicacion salí más perdido de lo que entre :(

**Comment by chocopiano** [comment]
Yo al menos ya puse los tiempos como el diagrama que puse arriba, a un día de la entrega ya no voy a cambiarlo jajajaja

**Comment by Minjor** [comment]
No entiendo nada

**Comment by Jaluco** [comment]
> No entiendo nada, lo hice como @chocopiano pero no queda claro si eso está bien

Nadie entiende, casate con una forma y espera lo mejor

**Comment by Jj1martinez** [comment]
Siempre que los marcos estén todos usados haremos un disco_read() para ver si tenemos que hacer un swap in ?
La lectura de disco se la agregamos a tiempo_mem_fisica?

**Comment by Jj1martinez** [comment]
La escritura y lectura de disco se suma al tiempo_memoria_fisica? o hay que crear una estadística aparte del enunciado?

**Comment by Jaluco** [comment]
> La escritura y lectura de disco se suma al tiempo_memoria_fisica? o hay que crear una estadística aparte del enunciado?

la escritura y lectura en disco son alfinal los tiempos de swap

**Comment by Jj1martinez** [comment]
Pero  aquí por ejemplo, 
Cache miss =Cache_lectura + Disco_lectura + Cache_escritura

ese disco lectura también hay que sumárselo al tiempo de swaps?

**Comment by Jaluco** [comment]
ese Cache miss deberia decir Cache_lectura+mem_fisica_lectura+cache_escritura. Porque a disco solo vas con los page faults

**Comment by Jj1martinez** [comment]
Vale gracias!!
