### ISSUE TITLE
Par de dudas

### ISSUE THREAD

**Issue by Javierdr** [IIC2343/syllabus#199]
Hola tengo dos preguntas:
1) Puedo usar la libreria math
2) En el enunciado dice que el programa se debe ejecutar por consola mediante el siguiente comando:  `$ python tarea.py nombre archivo.txt` pero si hago esto mi programa no funciona, en cambio si hago: `$ python3 tarea.py nombre archivo.txt` mi programa funciona. ¿Debo arreglar esto o no?
Saludos

**Comment by Hernan4444** [comment]
Hola,
1) Si puedes
2) No es necesario, con python3 también se acepta.

Saludos ✌️
