### ISSUE TITLE
Librerias Permitidas / No Permitidas

### ISSUE THREAD

**Issue by jjaguillon** [IIC2343/syllabus#2]
Estimados ayudantes.

Existen limitaciones en el uso de librerías de Python 3.6.X para los ejercicios de programación de la tarea. Sería bueno aclarar eso.

Muchas gracias de antemano

EDIT: Lo siento, acabo de leer la parte de Aspectos Formales. Para los que tenían la duda, sale en el documento. Saludos

**Comment by frvalenzuela** [comment]
Aprovecho esta issue para recordar a todos que es de gran importancia que lean los Aspectos Formales, pues contempla información que será usada para la corrección de sus tareas a lo largo del semestre, re-corrección, dudas sobre la tareas, etc.

Dejo el [link](https://github.com/IIC2343/syllabus/blob/master/Aspectos_Formales_IIC2343.pdf) disponible para que quién no lo haya encontrado todavía, (todo como siempre esta en el syllabus pero se los facilito de todas formas :D )

**Comment by sfga** [comment]
Hola,

   necesito utilizar la librería _json_. ¿Hay algún problema con usarla?

**Comment by frvalenzuela** [comment]
No hay ningún problema en ocupar la librería _json_

Saludos!

**Comment by vijuarez** [comment]
Hola, necesito usar dos librerias:

* `argparse`, para poder manejar los argumentos del programa de forma más ordenada.
*`re`, para un detalle al momento de leer los circuitos.


Muchas gracias.

**Comment by auirarrazaval** [comment]
Hola @vijuarez, si bien ambos módulos puedes usarlos ya que son built-in en python, el primero no es necesario, ya que si lees el documento de Aspectos Formales para las tareas, ahi les decimos como manejar los argumentos por consola.

Saludos!
