### ISSUE TITLE
Tarea 1: Cómo Programar en assembly

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2343/syllabus#2]
Leí el enunciado y entiendo que la tarea se debe hacer en assembly, pero como se hace para programar y testear en assembly?

De antemano, gracias!

**Comment by Hernan4444** [comment]
Hola,
 Voy a explicar todo el procedimiento. Para empezar, ustedes programarán en un lenguaje de bajo nivel llamado Assembly. Tal como en pythom existe comandos como `if`, `for`, etc. En Assembly tambien tiene su catalogo de comandos que pueden revisar en los apuntes de Hans que están en el [Syllabus/Material: capítulo 5.5](https://github.com/IIC2343/syllabus/blob/master/Material/Apuntes%20de%20Hans/5.5%20-%20Arquitectura%20Computador%20B%C3%A1sico.pdf) **Hoja 7 en adelante**.

En clases vieron los saltos condicionales, incondicionales y subrutinas. Mediante dicha formas se espera que redacten una serie de instrucciones capaces de calculo lo esperado. 

A modo de ejemplo, si les pedimos un código que obtenga la sumatoria de una lista, podemos usar el siguiente código (aquí hacemos saltos condicional e incondicional):
```Assembly
DATA:
//HEAD
fin 10 		// largo del arreglo
indice 0
suma 0
arreglo     	1
		2
		3
		4
		5
		4
		5
		2
		1
		1
//HEAD
CODE:

for:
    MOV A, (indice) 	// Obtenemos posición en la que estamos
    MOV B, (fin)      	// Obtenemos el largo de la lista
    CMP A,B		// Comparamos A y B.
    JGE end		// Si A >= B entonces ya terminamos de recorrer y saltamos a "end"
    MOV A, arreglo	// Obtenemos la posición de memoria donde empieza la lista
    ADD A, (indice)	// Nos desplazamos según el indice  (Posición arreglo + indice)
    INC (indice)	// Aumentamos el indice en 1 para el siguiente recorrido
    MOV B, A		// Movemos en B la posición del número que queremos obtener
    MOV A, (B)		// Movemos en A el valor almacenado en la lista
    ADD A, (suma)	// Hacemos que A = A + SUMA
    MOV (suma),A	// Guardamos A en memoria
JMP for 		// Saltamos de nuevo al for

end:
    MOV A,(suma)	// Movemos a A el valor final de la suma
    //PRT A
```
Con este código obtenemos la suma de todo el array. La idea es que hagan lo mismo para la tarea.  Dejé este código subido en la carpeta de la T01. Por cierto, los tabs y espacios no influyen en el código, solo los puse por algo de orden.

## ¿Como testear?

En el [Syllabus/Herramientas](https://github.com/IIC2343/syllabus/tree/master/Herramientas) hay dos interpretes (ambos funcionan en windows).

El primero:  Assembler IIC2343.exe es el interprete oficial. Este permite cargar un .txt con el código en assembly (tal como está escrito arriba) y simula cada línea.

El segundo: interpreter.zip es un interprete en fase beta. Ese se ocupa haciendo `python interpreter.zip` y se abrirá una ventana para seleccionar el archivo, simulará y hará un print de los registro o de algún dato en memoria. Los comandos para este interprete están en el pdf de la T01.

## ADVERTENCIA ⚠️ 
Cuando hacemos `MOV A, algo` (sin paréntesis) es lo mismo que `MOV A,lit`. Solo cuando ponemos paréntesis, se considera DIR, lo entenderán cuando vean la lista de comandos.

**HINT**: Recorrer un _string_ es igual que recorrer la lista 👀.

Espero haber respondido tu duda.
Éxito en la tarea ✌️

**Comment by MainScientist** [comment]
Un poco para complementar lo que dijo @Hernan4444 respecto de los intérpretes:
El interprete `Assembler IIC2343.exe` es un intérprete que solo funciona en windows mediante una interfaz gráfica, es decir, pueden ver mientras su programa se ejecuta en vivo los valores de los registros, la ram y el stack. Esto sirve para depurar su programa y ver más en detalle la ejecución de su programa.
El interprete `interpreter.zip` funciona para todas las plataformas que tengan instalado python (Python 3). Este no muestra valores en tiempo real sino que recibe comentarios especiales (`//PRT A`). Estos comentarios no corresponden a instrucciones de assembly, sino que fueron hechas para que el éste intérprete las reconozca sin afectar la ejecución de su programa en otros intérpretes. La idea de este programa es poder hacer print mediante consola usando assembly.

Finalmente quiero destacar que los comentarios `//HEAD` son también comentarios especiales. Estos comentarios no son usados por el intérprete, pero serán usados por el programa que corrige las tareas. Esto quiere decir que todas las variables dentro de head serán sacadas y utilizadas para la corrección, por lo que las variables especiales que ustedes usen deben declararlas fuera de estos comentarios.

Por ejemplo:
```
DATA:
//HEAD
fin 10 		// largo del arreglo
indice 0
suma 0
arreglo     	1
		2
		3
		4
		5
		4
		5
		2
		1
		1
//HEAD
mi_variable 1
otra_variable 2
arreglo_auxiliar 0
		0
		0
		0
CODE:
```

Mucha suerte con sus tareas!

**Comment by KnowYourselves** [comment]
Muchas Gracias a ambos!

**Comment by ValentinaAlvarezG** [comment]
Hola! no entiendo bien como abrir el interpreter.zip

**Comment by ValentinaAlvarezG** [comment]
Graaaaaacias!!!!! ❤️
