### ISSUE TITLE
Tarea 1

### ISSUE THREAD

**Issue by santi95** [IIC2343/Syllabus#2]
Hola! Cuando subirán la Tarea 1?

Saludos y gracias!

**Comment by Arcoirisky** [comment]
Hola~
Las fechas están en el Readme del curso. El archivo de texto grande que hay a penas entrando al [Syllabus](https://github.com/IIC2343/Syllabus) :D

**Comment by santi95** [comment]
Perdón! Creí que la fecha de entrega era el 14.
Gracias!

**Comment by santi95** [comment]
Perdón! Creí que la fecha de entrega era el 14.
Gracias!
