### ISSUE TITLE
Digito verificador 

### ISSUE THREAD

**Issue by narierao** [IIC2343/Syllabus#20]
Hola! he estado ene rato probando mi código en este problema usando esta página [https://generarut.cl/] (para probar los que terminan en k y 0) y me funciona correctamente inluso de los rut son de bajo 10 millones (rut de abuelos).  Algún indicio de qué podría ser? T.T solo quiero terminar esta tarea xc

**Comment by ceosorio** [comment]
Hola @narierao!

No sé si entendí bien la pregunta, podrías explicarla de nuevo?
Quedo atenta! 😄

**Comment by narierao** [comment]
Es que me falla un caso, pero incluso programé el código para cualquier n (largo del rut), podrías ingresar literalmente un rut de 100 cifras jkakjaskjas y sigue el patrón. No sé si me pueden dar una pista de qué estoy pasando por alto.

Gracias!

**Comment by ceosorio** [comment]
En ese caso te recomiendo revisar si funciona para cualquier rut dentro del rango que les damos.
Me cuentas como te va ✨
