### ISSUE TITLE
Argumentos que recibe el programa

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#20]
Suponemos que cuando ingresamos los input, estos estaran escritos bien para no tener problemas como que no se encuentra el json, etc. Gracias

**Comment by tomasrivera** [comment]
Puedes suponer que tendrán el formato correcto.
Saludos

**Comment by frvalenzuela** [comment]
Hola ! 

Por favor no cierres issues, porque la duda podría servir a otras personas. Gracias ! 

Saludos :D!
