### ISSUE TITLE
[Tarea 4] bit de validez TLB

### ISSUE THREAD

**Issue by dedarritchon** [IIC2343/syllabus#200]
No me queda clara la utilidad del bit de validez de la TLB, podrían dar un ejemplo de su uso? (diferencia entre cambiar el bit de validez y borrar la entrada completa) Saludos

**Comment by frvalenzuela** [comment]
Hola @dedarritchon !

Primero notar que el bit de validez viene de la tabla de página más que de la TLB por si misma (pues esta última es una cache especializada). Siguiendo con lo demás, borrar la entrada completa es costoso en tiempo pues significaría escribir en dicha línea un valor nulo (además que se tendría que definir conjunto de bits que represente dicho valor nulo), por lo que sale más conveniente ocupar un solo bit que nos indique que su contenido esta siendo ocupado.

Ejemplo:
Digamos que tengo lo siguiente en una tabla de página muy simple
Pag|Marco
0     | 1
Y digamos que el sistema operativo dice que esa asociación dejará de ser válida (digamos que es porque se va hacer un reinicio de todos sus programas). El borrar la asociación digamos que sea poner que el marco sea -1 (nuestro valor nulo)
Pag|Marco
0     | -1
Esto significaría ir donde esta guardada la tabla de página y sobrescribir el valor solo para indicar que no es válida la asociación, y luego cuando yo quiera saber que no hay asociación válida en esa dirección voy a tener que leer dicha línea. Ambas acciones tienen un costo de tiempo muy alto, algo que se acorta enormemente con el bit de válidez. En el mismo ejemplo tendría.
Pag|Marco|validez
0     | 1       |1
Ahora si el sistema operativo dice que no es válido no debo sobrescribir toda la dirección solo debo cambiar un solo bit, lo que es menos costoso en tiempo.
Pag|Marco|validez
0     | 1       |0

Espero que con eso haya quedado más claro. 

Saludos!

**Comment by Dyoma3** [comment]
@frvalenzuela cuando tengo tanto la cache (o tlb) llena pero algunos datos tienen validez 0 (son invalidos), entonces considero como es espacio libre? Tengo la duda de si se considera asi o se tiene que usar la politica de reemplazo, lo que no me hace mucho sentido ya que los datos con validez 0 no sirven y podrian ser considerados como espacios vacios.
Gracias de antemano.

**Comment by Arcoirisky** [comment]
Si tienes un dato con bit de validez cero, sí se considera como un espacio libre y no necesitas usar una política de reemplazo ya que no estás reemplazando nada. 

bit de validez cero son espacios con basura que no nos importa perder ni tomar en cuenta :D
