### ISSUE TITLE
T7 teórica - tamaño de una imagen

### ISSUE THREAD

**Issue by malopez16** [IIC2343/syllabus#200]
Hola! En la tarea se indica que el tamaño del buffer del HDD es suficiente para una imágen, pero el tamaño de ese buffer es el mismo que el tamaño de cada buffer de cada color. Asumimos que cada frame es del tamaño de buffer del HDD para sus 3 colores? Esto implicaría por lo tanto que los buffer de cada color no se usarían en su totalidad. ¿O no estoy entendiendo?

*Edit: Creo que ya entendí, mi confusión se debía a un problema de vocabulario: Frame = Imágen.

Gracias!

**Comment by malopez16** [comment]
Duda actualizada. De nuevo hice missclick en publicar -.-

**Comment by Geeermy** [comment]
Exacto. Los _buffers_ de _Germoji_ son capaces de contener 3 _frames_ simultáneamente (dado que están los canales separados), mientras que el _buffer_ del HDD solo soporta un frame máximo (y sigue un orden específico, que debe ser armado por tu programa en base a los _buffers_ del I/O).
