### ISSUE TITLE
[Tarea 4] cache NWA con N = 1

### ISSUE THREAD

**Issue by dedarritchon** [IIC2343/syllabus#201]
Los test 2 y 6 tienen cache con función de correspondencia NWA y N = 1. No sé si sea un error pero como en el enunciado dice que en caso de que sea NWA será un múltiplo de 2 me pareció raro.

**Comment by frvalenzuela** [comment]
Hola @dedarritchon !

Fueron hechos precisamente para que se dieran cuenta de dicha equivalencia. Felicidades por encontrarla!

Saludos!

**Comment by Taeval** [comment]
Entonces es un error o está bien? Porque el enunciado dice que es 1 si no es NWA.

**Comment by Arcoirisky** [comment]
@Taeval Está bien

**Comment by dedarritchon** [comment]
> Hola @dedarritchon !
> 
> Fueron hechos precisamente para que se dieran cuenta de dicha equivalencia. Felicidades por encontrarla!
> 
> Saludos!

Solo para confirmar, cuando una cache NWA tiene 1 solo conjunto es equivalente a FA (eso pasa en el test 4). 
En los test 2 y 6, N=1, pero tienen 4 conjuntos de 1 linea cada uno entonces no serían equivalentes a FA.

**Comment by Arcoirisky** [comment]
@dedarritchon lo que sucede con NWA es que decir que es N=1 es que solo tienes un set, por lo tanto, sería toda la caché. Luego, sabes que cada ser trabaja FA. Así es como terminan siendo equivalentes.

**Comment by dedarritchon** [comment]
mmm en los apuntes sale: Si se tienen 4 bloques por conjunto, se denominará 4-way associative; 2 bloques por conjunto, 2-way associative y así. osea el N es la cantidad de bloques por conjunto

**Comment by VicenteMelin** [comment]
![image](https://user-images.githubusercontent.com/37168631/58930994-dc3f7300-872b-11e9-9f2e-b9b19ac3ecda.png)
 según los apuntes y este pantallazo de las clases tener N= 1 seria direct-mapped, pero el enunciado dice que no consideraran este caso.
Aparte: el N va a ser potencia de dos cierto? sino el numero de conjuntos podria no ser entero

**Comment by frvalenzuela** [comment]
Hola @dedarritchon !

Como bien dice@VicenteMelin ! Es direct map! Me confundí completamente con el número de conjuntos, lo lamento.
En cualquier caso, el enunciado no dice que no se puede considerar direct map, dice que puede el parámetro N puede ser múltiplo de dos o el valor uno.

Así que sip, N siempre será potencia de dos.

Saludos!

**Comment by dedarritchon** [comment]
Entonces esto: https://github.com/IIC2343/syllabus/issues/201#issuecomment-498932319 esta bien?

**Comment by frvalenzuela** [comment]
Hola @desarritchon ! 

Si ! 

Saludos !

**Comment by DanielCarrascoFalcon** [comment]
Entonces si es N=1 lo tomamos como FA? hay que considerar una equivalencia o nos olvidamos no más??

**Comment by Arcoirisky** [comment]
@DanielCarrascoFalcon Olvídenlo no más 😅 entre tanto FA nos confundimos al responder.
