### ISSUE TITLE
Duda Test 3

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2343/syllabus#201]
Estimados, puede ser que en el test 3 el _write-miss rate_ sea `0.428571` en lugar de `0.28571`.
Me está dando ese resultado y encuentro demasiado sospechosa la similitud.

Gracias

**Comment by Hernan4444** [comment]
@joseluishaddad, ese test está correcto, e incluso a más alumnos les dió lo mismo #196 

Saludos ✌️

**Comment by joseluishaddad** [comment]
Entonces solo fue una coincidencia :/ jajaja Gracias
