### ISSUE TITLE
Problema Write Miss Urgente

### ISSUE THREAD

**Issue by JaimeGo** [IIC2343/syllabus#202]
Hola! Llevo horas en esto. No me calza el resultado del miss rate del test 2. La secuencia es esta:

SEC=0W,1,2,3W,4,5,6,7,8,9,8,7W,6,5,4,3,2,1,0,1,3,2,4,6,4,2

Y se ocupa WB, 2W y LRU

La caché tiene espacio para 8 palabras.

Primero coloca en caché los números del 0 al 7. Luego al llegar a 8 se debe reemplazar [0,1] por [8,9] y como es WB:

escrituras realizadas en la memoria principal +=1

Luego al llegar a 1, no está en la caché porque se reemplazó antes. Por tanto de nuevo:

escrituras realizadas en la memoria principal +=1

Además es obvio que hay 3 escrituras totales.

Por tanto el miss rate debería ser:

escrituras realizadas en la memoria principal/escrituras totales=2/3=0.66

Pero en resultados aparece 0.33

Me podrían explicar por qué??? Llevo muchas horas...

**Comment by joaquincastillo** [comment]
"  Luego al llegar a 8 se debe reemplazar [0,1] por [8,9] y como es WB:
escrituras realizadas en la memoria principal +=1 ".  Aquí si hay escritura en memoria principal porque el 0 tiene una instrucción de escritura (el W).

"Luego al llegar a 1, no está en la caché porque se reemplazó antes. Por tanto de nuevo:
escrituras realizadas en la memoria principal +=1 ". Aquí no hay escritura en memoria principal, dado que ninguno de los datos del bloque (8 y 9) tienen el W.

**Comment by JaimeGo** [comment]
Muchas gracias, eso era
