### ISSUE TITLE
Corrección Tarea 5

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2343/syllabus#203]
Hola,

En las notas de la Tarea 5 Práctica no obtuvimos todo el puntaje en la columna de "Código", sin embargo no había ningun comentario en la planilla por lo que no sabemos que fue lo que hicimos mal. ¿Habría alguna forma de saberlo?

PD: somos el grupo 13

**Comment by jheysen** [comment]
Te sugiero enviar este tema por recorrección
