### ISSUE TITLE
[Tarea 4][Sugerencia] - Entrega Final

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#203]
Hola, quería preguntar al final para cuando será la entrega de la tarea. Leyendo las issues anteriores no sé para cuando quedó al final. Sería super importante saber, debido a que tengo que organizar todo de nuevo y supongo que los demás del curso también. 

Sin caso de ofender, ni nada es segunda vez que tengo que perder bastante tiempo tratando de entender porque no funciona mi programa (por problemas de enunciado que faltan datos o bien el programa esta malo) y en este caso me costó demasiado entender el enunciado (no creo que esta tarea de para un enunciado tan pequeño). Me ha costado mucho poder organizar, debido a que estoy en mi último semestre y el tiempo que dispongo es super chico (los otros ramos son ultra demandantes). 

Yo sé que ustedes están al tanto de esto y que han tenido la MEJOR disposición a responder todo tipo de dudas ya sea por wpp, telegram, git, hangouts, pero es primera vez que me pasa. Lo único que pido es más rigurosidad, ya que al final los perjudica a ustedes, pero los más perjudicados somos todos los alumnos.

**Comment by chocopiano** [comment]
Sumando a lo anterior, me gustaría saber como será el criterio de correción. Esto es debido a que uno puede tener bastante claro la materia pero puede tener errores en el codigo porque a mi parecer no esta fácil de programar. Al final siento que se evalua más la parte 'programada' que de conocimiento. Dejar en claro que esto no es una queja, sino más bien, hacer saber una preocupación que a más de alguno creo que le debe estar pasando. Saludos!

**Comment by njgarrido** [comment]
Por otro lado, creo que los tiempos de ejecución no se entienden al 100% y van a haber muchos resultados diferentes. Sería bastante util si pudieran poner los resultados de uno de los ejemplos para probar si lo estamos haciendo bien o mal este calculo.

**Comment by Jiparavich** [comment]
Me sumo al comentario de @njgarrido , dada la discrepancia entre los apuntes y lo que dicen ustedes, sería bueno que suban outputs de ejemplo de los test para finalmente "ajustar" nuestro programa a los criterios de ustedes.
Muchas Gracias!

**Comment by Arcoirisky** [comment]
Hola~

Recibimos sus sugerencias con agrado pero tengo el deber de recordar las reglas del foro #1, punto 4. Si tienen alguna sugerencia como estas es mejor enviarlas por mail al ayudante jefe con copia al profesor. Así tendremos un registro de las opiniones y podremos revisarlas para llegar a una solución que pueda satisfacer a la mayoría :D 

Saludos~
