### ISSUE TITLE
duda write-miss

### ISSUE THREAD

**Issue by smargozzini** [IIC2343/syllabus#203]
Si mi secuencia termina y en la cache quedaron palabras que no se escribieron a la memoria principal porque nunca las tuve que sacar, esas quedaran en el cache sin influir en el write-miss o debo hacer algo con eso como pasar todas las que no se escribieron a la memoria principal sumando una escritura mas?

**Comment by Hernan4444** [comment]
@smargozzini quedan en la caché sin influir en el write miss.

Saludos ✌️
