### ISSUE TITLE
[T7] Duda enunciado parte teórica 

### ISSUE THREAD

**Issue by malopez16** [IIC2343/syllabus#205]
Hola! me pareció raro que aquí: 

![image](https://user-images.githubusercontent.com/26126519/47514921-e6c19200-d857-11e8-96cf-3d1b930d53a7.png)
Se pida que se escriba una **Imagen** en el HDD. No será un emoji completo? (una imágen es sólo 1 frame, y tal vez no querían referirse a eso, sino a mandar la cantidad de frames totales del emoji).
Gracias!

**Comment by Geeermy** [comment]
¡Hola!

Exacto... fue un error de tipeo. 😢

Daré un aviso pronto con el tema para que no haya problemas.

¡Muchas gracias por dar cuenta de esto!

**Comment by malopez16** [comment]
de nada, gracias a ti!
