### ISSUE TITLE
Tarea 4 - Informe

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2343/syllabus#205]
Hola, en el informe hablan de que los 3 archivos de prueba son los mismos tres conjuntos de programas. ¿A que se refiere eso?

**Comment by auirarrazaval** [comment]
Duplicate of #194

**Comment by Arcoirisky** [comment]
En la issue #206 se habla de esos 3 archivos y se espera que ustedes cambien los parámetros pedidos según sea conveniente y prueben :D 

Saludos~

**Comment by Arcoirisky** [comment]
Mentira! 
Me equivoqué al referenciar!

**Comment by Arcoirisky** [comment]
Los 3 test son el 1, 2 y el 5

**Comment by jgespinosa10** [comment]
Hola, sigo sin entender. Debemos para los programas 1, 2 y 5 cambiar sus parámetros e intentar de analizar como afectan en el desempeño del programa?

**Comment by ignacioaraya1995** [comment]
No entiendo

**Comment by Arcoirisky** [comment]
@jgespinosa10 si
