### ISSUE TITLE
[T04] DUDA ACLARACIONES PUNTO 8

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#206]
"Cuando se hace swap out de un marco en memoria física, es lógico invalidar todas las entradas de la caché que apunten a direcciones dentro de ese marco, ya que cuando ingrese el nuevo marco, en caso de no invalidar, habría inconsistencia en los datos. (Repito: SOLO LAS LINEAS QUE APUNTABAN AL MARCO SACADO)"

Lo anterior se refiere a que cuando ocurra un swap out debo sacar dicha página de la TLB y además sacar de la cache la direccion fisica que resultaba de los valores que elimine de la TLB o no?? Gracias!

**Comment by auirarrazaval** [comment]
Ese punto se refiere a la caché de la memoria física, no la TLB
