### ISSUE TITLE
ISR

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#207]
Hola! 
En el enunciado sale esto: 
![image](https://user-images.githubusercontent.com/24725124/47522013-dff04a80-d86a-11e8-9aef-05ec07388889.png)

No entiendo la utilidad de la parte `ISRXY:` si al final accedemos a todos los dispositivos por `map` o por `puerto`, es decir, no utilizamos direcciones del dispositivo (Germoji).

Osea tendremos que escribir todo en la parte `program:`, o me equivoco?

**Comment by jheysen** [comment]
Te equivocas...

**Comment by movaldivia** [comment]
@jheysen  Osea dentro de ISRXY puedo utilizar MOV AX 38, que según enunciado corresponde a la primera palabra del buffer rojo de germoji?

**Comment by jheysen** [comment]
Si

**Comment by movaldivia** [comment]
@jheysen vale gracias!

**Comment by eiherrera** [comment]
Hola! Para el caso del registro que almacena el contador de frames por enviar, como también para el buffer al que se le cargan dichos frames, ¿tenemos que actualizar sus contadores y datos a mano en el ISR, o basta con definir un comando del tipo `cargar buffer` o `actualizar contador` en la tabla de comandos, al cual podemos llamar en el código y obviar las operaciones que ocurren por debajo?

**Comment by jheysen** [comment]
Preguntate, ¿Quién está encargado de hacer ese trabajo?

**Comment by eiherrera** [comment]
Me lo he cuestionado pero no estoy seguro, por eso pregunto por aquí.

**Comment by jheysen** [comment]
Qué programas tienes que hacer en la tarea, creo que esa pregunta te va a conducir a la respuesta
