### ISSUE TITLE
Tarea 4 Duda tiempo lectura busqueda TLB

### ISSUE THREAD

**Issue by cmp831** [IIC2343/syllabus#207]
Hola, para buscar en la tabla TLB, el tiempo de lectura que debemos calcular, corresponde a la  suma del tiempo de lectura de la cantidad de lineas recoridas, o al tiempo de lectura que nos entregan como parámetro?

**Comment by auirarrazaval** [comment]
Se considera el tiempo de lectura entregado como parámetro, independiente de si se leen 1 o 100 lineas (lo mismo para escritura)
