### ISSUE TITLE
Ayudantía 6 robot

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#208]
Hola!
Este es el código del ejercicio del robot
![image](https://user-images.githubusercontent.com/24725124/47523211-df0ce800-d86d-11e8-8a40-701430564ce6.png)

El enunciado dice que el robot debería avanzar infinitamente, y aquí siento que me faltan dos cosas un "loop" al inicio para avanzar infinitamente y algún salto para ir a `avanzar` o me equivoco?

**Comment by Geeermy** [comment]
Fíjate que el robot **interrumpe** cada vez que termina un comando. Por eso es infinito, el robot se encarga de que así sea.

**Comment by Geeermy** [comment]
@movaldivia El programa no termina ahí. Como no hay un salto, el ```PC``` aumenta en una unidad y ejecutas lo que viene después. En este caso... ```IRET```. :grin:

**Comment by movaldivia** [comment]
@Geeermy  aaaaaaaaaaaaaaaaaaaa, ahora entendí jajajajajaja. Por un momento se me había olvidado el `PC`. Gracias !
