### ISSUE TITLE
Notas T03

### ISSUE THREAD

**Issue by iqacevedo** [IIC2343/syllabus#208]
Hola,

Ya saben aprox cuando estarán las notas de la tarea 03? 

Saludos!

**Comment by Hernan4444** [comment]
@iqacevedo estamos trabajando lo más rápido en tener todas las notas (Entrega 3, Tarea 3 y Tarea 4 al tiro).
El lunes 27 en la noche tendremos si o si la T03.

Saludos ✌️

**Comment by iqacevedo** [comment]
Gracias @Hernan4444. Eres la luz al final del camino ❤️
