### ISSUE TITLE
Accesos de Memoria - Control 3

### ISSUE THREAD

**Issue by rafafdz** [IIC2343/syllabus#208]
Hola! Revisando la pauta del control 3, me encontré con que en la pregunta de **Memoria Virtual**, los accesos a memoria de los programas se trataban como si representaran un **numero de página virtual** en vez d una dirección de memoria virtual.

Me di cuenta de esto porque en la tablas de paginas de la solución se guarda un mapeo de esas direcciones a los marcos de memoria física, cuando en realidad se tendría que haber mapeado la página correspondiente a cada dirección (En el ejercicio todas las direccion corresponderían con la página virtual 0) con los marcos. 

Esto es un error o hay algo que no estoy entendien bien? 
Gracias!

**Comment by Arcoirisky** [comment]
En el control te estamos dando las páginas virtuales, no tienen que hacerle ninguna transformación para obtenerla. Es por eso que es tan directo O:
