### ISSUE TITLE
Devolución Placas

### ISSUE THREAD

**Issue by lefischer** [IIC2343/syllabus#209]
Hola,

Como y cuando se realizara  la devolución de las placas?

gracias

**Comment by Hernan4444** [comment]
@lefischer las devoluciones se tenían planeadas para el 29, pero puedes agendar antes conmigo para entregarla en otra fecha (manda mail).
Saludos ✌️

**Comment by lefischer** [comment]
@Hernan4444 

El 29 tengo examen, va a ver un horario especifico o sera durante el día?

**Comment by Hernan4444** [comment]
mandaremos un aviso cuando tengamos bien definidos los horarios
