### ISSUE TITLE
[TAREA 4] Problema pregunta 1 informe

### ISSUE THREAD

**Issue by Taeval** [IIC2343/syllabus#209]
En la pregunta 1 para el informe de la tarea, se menciona que se subieron 6 archivos con 3 conjuntos de programas ejecutados con parámetros distintos, pero se subieron 7 y no se repiten programas. 
¿Cómo respondemos la pregunta si nos pide analizar cual configuración usada para cada conjunto es mejor?

**Comment by Arcoirisky** [comment]
Hola~

En la issue #206 se especifican estos 3 archivos. Les subimos 7 para que probaran su tarea :c 
y realmente esperamos que ustedes cambien los parámetros como lo estimen conveniente.

**Comment by Arcoirisky** [comment]
Los 3 test son el 1, 2 y el 5

**Comment by ignacioaraya1995** [comment]
No entiendo la respuesta.

**Comment by dedarritchon** [comment]
Podrían decir lo que se espera que hagamos? Por ejemplo, cuáles son los parámetros que deberíamos variar? Porque las distintas combinaciones posibles de **politicas de reemplazo**, **funciones de correspondencia**, **N**, y **tamaños** son demasiadas.  Solo variando las **políticas de reemplazo** y **funciones de correspondencia** son 16 configuraciones para cada programa: 48 tests

**Comment by auirarrazaval** [comment]
Hola! Deben hacer un análisis de como cambian los tests mencionados al cambiar ciertas políticas, no tienen por que hacer los 48 tests, sino que con dos o tres variables por cada uno está bien. La idea es que los cambios que hagan tengan como consecuencia un cambio en el output, y deben der capaces de explicar el por qué de ese cambio.
Saludos!
