### ISSUE TITLE
Duda enunciado parte teórica: DMA y acceso a disco.

### ISSUE THREAD

**Issue by lucasmarinb** [IIC2343/syllabus#209]
En el enunciado se dice que la DMA hace la transferencia del dispositivo al **disco**, sin embargo, esto sería contradictorio con la definición de DMA de los apuntes, que sería facilitar la trasferencia a memoria.
Por otro lado, por enunciado, el HDD requiere de un formato especial de los datos cuando se trata de una imagen, lo que obligaría de alguna forma a usar la memoria principal como intermediaria de la transferencia.
¿Correspondería esto a un error de enunciado?

**Comment by jheysen** [comment]
No
