### ISSUE TITLE
Cambio de respuesta en Google Form

### ISSUE THREAD

**Issue by bpardobravo** [IIC2343/Syllabus#21]
Hola, envié mis respuestas vía el google form, pero ahora quiero cambiar una respuesta que me di cuenta que le faltaba algo.
Tengo que llenar todo el form de nuevo o enviar solamente la pregunta cambiada?

**Comment by jmwielandt** [comment]
Hola, puedes mandar solamente la pregunta. Lo demás no se borra.
Saludos!
