### ISSUE TITLE
Operaciones interprete

### ISSUE THREAD

**Issue by asimonv** [IIC2343/syllabus#21]
Qué operaciones están permitidas en el intérprete? En el ejemplo que subieron, está `INC (indice)`, pero no está en la tabla del 5.5.

**Comment by FranLucchini** [comment]
Es el archivo adjunto aparece esa instrucción. Voy a suburlo al syllabus.
[IIC2343 - Assembler.pdf](https://github.com/IIC2343/syllabus/files/1895604/IIC2343.-.Assembler.pdf)

**Comment by asimonv** [comment]
Sorry! El DEC A no está funcionando por si acaso, tuve que hacer SUB A, 1.

**Comment by fdominguezclaro** [comment]
Es confirmado que DEC A no funciona?

**Comment by asimonv** [comment]
Sí, acabo de confirmarlo de nuevo. Hice esto:
`MOV A, 5
    //PRT A
    DEC A
    //PRT A`

Y tiró:
`5
5
`
