### ISSUE TITLE
Duda input/output 

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#21]
Para la equivalencia de circuitos nos entregaran el json asi:
{
  "circuit":[
    {"from": "or1", "to": "and1"},
    {"from": "or2", "to": "and1"},
    {"from": "and1", "to": "output1"},
    {"from": "input2", "to": "or1"},
    {"from": "input1", "to": "or2"},
    {"from": "not2", "to": "or2"},
    {"from": "input1", "to": "not1"},
     {"from": "input2", "to": "not2"},
     {"from": "not1", "to": "or1"}
  ]
}

y para el output de este circuito tiene que quedar:

{
  "circuit":[
    {"from": "input1, "to": "nor1."},
...
  ]
}

Mi duda es que no se como tiene que se el output e input. En el ejemplo simulacion se entiende perfect, pero en este tengo dudas!! No se si va con circuit o sin! muchas gracias

**Comment by Arcoirisky** [comment]
Tiene que quedar con circuit xD 

Los .Json son diccionarios con llaves que contienen listas de diccionarios. Es el formato con el que podrás y debes manejar los .json 

Espero haber respondido tu pregunta :)
