### ISSUE TITLE
Python 3.5

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#21]
¿Cómo se descarga/instala python 3.5 en windows 10 (x64)? 😢 

https://www.python.org/downloads/release/python-356/

**Comment by BSamilla** [comment]
Hola @jmwielandt 

Debes ir a https://www.python.org e ingresar a Downloads -> Windows.
Te aparecerá un listado con todas las versiones.
Buscas la que quieres y la descargas.

Personalmente yo descargo la x86 - 64 executable installer, pero puedes usar la que mejor te convenga.

Saludos!

**Comment by jmwielandt** [comment]
Gracias
No encontraba los ejecutables de la 3.5 😅

**Comment by jheysen** [comment]
Lo otro es usar una distribución de Python que te ayude para este y otros ramos, como Anaconda.
https://docs.anaconda.com/anaconda/faq#how-do-i-get-the-latest-anaconda-with-python-3-5

(Lo mejor a mi juicio es hacer el Virtualenv como dicen ellos)
