### ISSUE TITLE
[Tarea 4] Ubicación Original de los Datos

### ISSUE THREAD

**Issue by pgarnham** [IIC2343/syllabus#210]
¿Donde están los datos guardados inicialmente? Porque el primer acceso va a ser un miss en TLB, luego va a ser un miss en la caché, y tampoco va a estar en la Memoria Física. Entonces lo que me queda es el disco (?)
Creo que entiendo el flujo y funcionamiento, pero el inicio me confunde.

**Comment by frvalenzuela** [comment]
Hola @pgarnham !

¿Por qué no estará en la memoria? La direcciones siempre estarán en la memoria, lo que este dentro de dicha dirección es otra cosa, y podría haber cualquier valor realmente (lo que tampoco es relevante para el enfoque de esta tarea). Así que luego del miss en caché lo que se que este en la dirección física será agregado a la cache según la función de correspondencia que tenga definida.

Saludos!

**Comment by pgarnham** [comment]
@frvalenzuela  Yaaa perfecto!! muchisimas gracias!!!

**Comment by leolivares** [comment]
@frvalenzuela Hola! No me quedó claro. Si mi memoria principal tiene cierto tamaño, inicialmente estaría vacía. Luego, con la primera dirección virtual, asignaría un marco de los disponibles, procedería a la cache y luego directamente al marco (ya que en ninguno estaría el dato inicialmente). No debería entonces buscarlo en disco?

**Comment by frvalenzuela** [comment]
Hola @leolivares !
Si tu memoria tiene un cierto tamaño, ¿por qué debería estar vacía?, ¿qué le impide que dentro tenga guardado datos en sus direcciones?
Aún en el caso de estar vacía, lo único que significaría es que en las direcciones de la memoria física cada dato tiene un valor igual a cero, y si el programa accede alguna de esas direcciones no tiene porque ir a buscar a disco en dicho caso.

Saludos!

**Comment by Sforrego** [comment]
@frvalenzuela disculpa pero me entro la duda, si siempre vamos a buscar los valores a la memoria fisica independiente de lo que haya(que es lo que tiene sentido), cuando aplicamos la politica de reemplazo de la memoria fisica? es relevante esa informacion?
