### ISSUE TITLE
Puertos

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#210]
![image](https://user-images.githubusercontent.com/24725124/47528437-95c39500-d87b-11e8-8df9-cfa45d1aaf08.png)

No entiendo porque el HDD tiene un registro de dirección base, un registro de tamaño copia, si ya tenemos esa información en el DMA. Es necesario escribir la información en ambos dispositivos?
Si es así, porque?

**Comment by movaldivia** [comment]
Además para que el DMA tenga cierto control se necesita el registro de estado, y si bien en el enunciado sale que se puede agregar todos los estados y comandos necesarios, luego no sabría como acceder a el (No está en la tabla). Podría asumir que está el registro de estado en el puerto 5?

**Comment by jheysen** [comment]
En qué espacio de direcciones se mueve el HDD?

**Comment by movaldivia** [comment]
@jheysen aaaaa claro se mueve al buffer y del buffer al hdd.
Y respecto a la otra pregunta? (Podría asumir que está el registro de estado DMA en el puerto 5?)
