### ISSUE TITLE
Registros DMA

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#211]
Hola!

Según mi interpretación de esto:
![image](https://user-images.githubusercontent.com/24725124/47530274-81ce6200-d880-11e8-85f1-db91d205fa4e.png)
Habría que modificar los valores de los registros del DMA desde afuera osea no en el ISR. Pero todos los ejemplos que he visto, incluso en el problema anterior donde hay que realizar el ISR de Germoji estos registros se modifican adentro del ISR.
Entonces, está bien modificar estos registros desde afura del ISR, o asumo que funcionan "automáticamente"?

**Comment by jheysen** [comment]
Dice eso explícitamente
