### ISSUE TITLE
[Tarea 4] Consulta escritura en memoria

### ISSUE THREAD

**Issue by seba608** [IIC2343/syllabus#211]
Hola!

No estoy seguro si es que esto ha sido preguntado antes. Según entiendo, si tengo datos en la caché y se accede a ellos en modo lectura, una vez que saco ese dato de la caché no debo escribirlo en memoria física porque su valor nunca cambió. En cambio, cuando el acceso a la cache ha sido para escribir en ese dato y lo quiero sacar, si debo escribir en memoria principal su nuevo valor una vez que lo saque de caché. ¿Cómo puedo saber cuando los accesos a una dirección de la caché modificaron efectivamente el dato para saber si tengo que escribir ese dato en memoria física una vez que lo saque de la caché?

Gracias!

**Comment by Jiparavich** [comment]
x2

**Comment by ignacioaraya1995** [comment]
x3
