### ISSUE TITLE
Cantidad total de frames Germoji

### ISSUE THREAD

**Issue by lucasmarinb** [IIC2343/syllabus#212]
En la descripción del Germoji nos dicen que tiene un registro que lleva la cuenta del total de frames. Sin embargo en las tablas no aparece como memmory mapped ni como port i/o. ¿Podemos suponer que tenemos acceso a este registro?

**Comment by jheysen** [comment]
Dale vueltas a lo que dice sobre ese registro

**Comment by norman123123** [comment]
No entiendo bien, sale que el registro tiene la cantida total de frames a enviar, pero que se actualiza luego de que se haya hecho un envío. Como funciona eso? 
Además cómo se accede al valor de este registro?

**Comment by Geeermy** [comment]
Pueden asumir que tienen acceso, o bien reservar una dirección dentro de la ISR que contenga ese valor y llenarlo ustedes mismos, cualquier método que sea razonable está bien.

Con respecto a la actualización, pueden asumir lo que quieran que sea consistente con su programa. Por ejemplo, si asumen que este valor es actualizado por _Germoji_, está OK, pero tendrán que estar pendientes de cuál es ese valor. Si asumen que solo les da los _frames_ de los _emojis_ y ustedes lo deben actualizar en la ISR, también está OK, pero deberán preocuparse de actualizarlo constantemente y con consistencia, para no tener un valor negativo de _frames_, por ejemplo.

Por último, pueden asumir que el acceso a esa dirección es directo a partir del número en el que esté reservada. Por ejemplo, si lo reservé en la dirección 3110:

```
MOV AL,[0x0C26]
```
Basta con eso para acceder.

Este punto es bien flexible dado que no está explicitado en el enunciado. Juéguensela con supuestos, aquí hay muchas soluciones posibles, no piensen que hay una única implementación correcta.

¡Éxito!
