### ISSUE TITLE
Valores en LEDs - Practica

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2343/syllabus#213]
Hola!

Para la parte de Memory Mapped, el valor registrado en un LED puede ser solo 0 o 1 cierto? en otras palabras, en la RAM si tengo que en la address 11111110 (que si no me equivoco seria el led0), tengo el valor 00000010 (que seria 2) ahi prendo el led igual? Prendo el led si hay cualquier valor distinto de 0? O estoy entendiendo todo mal?

Muchas gracias

**Comment by Geeermy** [comment]
¡Hola! Dos cosas:

1) La _address_ del ```led0``` va a varias ya que es _programable_, como se explicó en ayudantía. Es decir, si yo ejecuto:

```
MOV A,15
MOV B,0
MOV (192),A
MOV (193),B
MOV (15),B
```
Ahí lo que digo es que el dispositivo que será mapeado en la dirección 15 (haciendo uso de la primera dirección reservada del _address decoder_, igual a 192) será ```led0``` (dado que en la dirección 193 almacené el puerto 0, correspondiente al ```led0```). Esta es la forma de determinar cuándo cambiar el valor de un _led_ específico.

2) Sí, solo puede ser 0 o 1. Qué hacer si recibes un valor distinto. Puede ser lo que dices, aunque quizás es más fácil quedarte solo con un bit de lo que recibiste. Sea cual sea tu decisión, déjalo en tu README/reporte.

¡Éxito!

**Comment by auirarrazaval** [comment]
Tengo un par de preguntas al respecto:
1. Cuando dices 
> Ahí lo que digo es que el dispositivo que será mapeado en la dirección 15

te refieres a puerto 15 del _address decoder_?

2. Estoy confundido un poco con como funciona el Address decoder. Termina siendo algo asi como otra memoria?  cuando recibe una direccion entre 192 y 255, exactamente que hace despues? En los apuntes no lo encuentro

3. Para _Port I/O_, si recibo `IN A, (4)`, seria un comando invalido o no? ya que los ports reservados para _Port I/O_ son del 32 al 40. Y como puedo saber a que dispositivo/direccion de memoria me estoy dirigiendo si lo que recibo es un port, y no un address

Muchas Gracias! (Por la hora además)

**Comment by Geeermy** [comment]
1) No. Recuerda que estamos trabajando con un _address decoder_ **programable**, es decir, **soy yo el que decide cuál es la dirección a la que estará _mapeado_ un dispositivo**.

Entonces, cuando hago:

```
MOV A,15
MOV (192),A
```

Estoy diciendo "el primer dispositivo estará _mapeado_ a la dirección 15".

Luego al hacer:

```
MOV B,0
MOV (193),B
```

Estoy diciendo "el primer dispositivo será el de puerto 0, que corresponde a ```led0```".

Por lo tanto, al hacer:

```
MOV B,1
MOV (15),B
```

Lo que digo es: "haz que la dirección 15 contenga un 1". No obstante el _address decoder_ lo verá y dirá "ah, pero esta dirección la tengo reservada para un dispositivo, en particular el de puerto 0, así que le enviaré este valor a él". ¿Qué pasará? Si todo está bien, ```led0``` tendrá un valor igual a 1 y se prenderá.

2) No es otra memoria, pero podría tener elementos de memoria contenidos en él (como registros, por ejemplo). Al final lo que te estamos diciendo es que esas direcciones están también _mapeadas_ a memoria. El _address decoder_, al ver ese rango, sabrá que se están refiriendo a **contenido que le pertenece a él**, por lo que hará algo al respecto. Esto se liga con lo que dije de los elementos de memoria, puedes decir, por ejemplo, que dichas direcciones están asociadas a componentes internos del _address decoder_ (...registros), lo que te puede facilitar bastante el trabajo de reservar posteriormente direcciones de memoria a ciertos dispositivos.

3) Sí. Puedes asumir que no haremos eso, pero si quieres controlarlo, simplemente haz que ```A``` no cambie su valor. En esta instrucción siempre te pasaremos puertos y no direcciones, no te preocupes por eso.

¡De nada! 😁
