### ISSUE TITLE
[Tarea 4] Tiempo utilizado en swaps

### ISSUE THREAD

**Issue by atbusch** [IIC2343/syllabus#213]
Hola, tengo una duda en la estadistica de tiempo utilizado en swaps, porque ocurren muchas cosas en estos y no se si hay que considerar las lecturas y escrituras en disco solamente o las lecturas y escrituras en las otras componentes tambien, aunque ya esten contadas en las otras estadisticas de tiempo.

Gracias!

**Comment by seba608** [comment]
+1
