### ISSUE TITLE
Repositorios Publicos Tarea 8

### ISSUE THREAD

**Issue by LuisFros** [IIC2343/syllabus#214]
Parece que los repositorios generados por el link son publicos

**Comment by Geeermy** [comment]
¡Toda la razón!

Gracias por el aviso. Ya se corrigió eso en el enlace, ahora mismo arreglaré los repositorios creados.

**Comment by Geeermy** [comment]
Parece estar todo en orden, si alguien nota algo extraño, por favor avisar en esta misma _issue_.

¡Muchísimas gracias!
