### ISSUE TITLE
[Tarea 4] Write-Back

### ISSUE THREAD

**Issue by brayanmoreno** [IIC2343/syllabus#215]
tengo problemas para entender como implementar esto en la simulación, ya que considere los siguientes casos como ocurrencia de esto:

- ocurre un swap out, por lo cual se debe leer la cache y escribir en memoria los datos actualizados antes que se pierda el marco para finalmente invalidar las líneas de la cache que apuntaban al marco.

- una línea de cache debe ser reemplazada (se decide por la política de reemplazo), pero antes de esto sería necesario leer la memoria y escribir en está para mantener el marco referente a la línea actualizado.

no se si esto es correcto o interprete algo mal.

**Comment by Arcoirisky** [comment]
¿Cual es tu duda? Específicamente 😅 Porque no podemos decirte si estás pensando bien o mal algo que estamos evaluando.
