### ISSUE TITLE
[Tarea8] Algoritmo de remplazo memoria física

### ISSUE THREAD

**Issue by tomasrivera** [IIC2343/syllabus#215]
Hola, qué algoritmo de remplazo se usa para cuando se llena la memoria física?
Saludos

**Comment by jheysen** [comment]
LRU, y actualizaremos el enunciado.

Gracias por el aviso.

**Comment by jmwielandt** [comment]
@jheysen 
LRU con o sin normalizar?
O queda a nuestro ~~des~~criterio?

**Comment by jheysen** [comment]
El básico digamos, absoluto

**Comment by jmwielandt** [comment]
Me refería al LFU de la caché, perdón.

**Comment by Geeermy** [comment]
@jmwielandt Asume sin normalizar, mágicamente tenemos un contador infinito así que eso no es problema.
