### ISSUE TITLE
informe pregunta 1 

### ISSUE THREAD

**Issue by rjdelrio** [IIC2343/syllabus#216]
en caso de que nuestro programa aun no tengo la capacidad de poder mostrarnos un resultado seguro, podemos argumentar nuestra respuesta con materia de clases y algunos cálculos hechos a mano?

**Comment by Jaluco** [comment]
+1, no tengo ninguna seguridad de estar haciendo lo que se espera que hagamos, entonces mi informe dependerá mas de materia que observacion

**Comment by jmwielandt** [comment]
Hola!

No hay ningún problema con ello.

Saludos!
