### ISSUE TITLE
[T8] Duda Tabla de Página

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2343/syllabus#216]
Entiendo el hecho que las tablas de páginas no estén en memoria. Pero existe alguna estandarización que debamos seguir para la hacer las tablas de página? Mi duda principalmente esta en si el como se diseño las tablas de página afecte en algo las estadistas finales que entregue el programa. O solo importa que cada tabla de página no tenga el mis par, página virtual y dirección física, y cualquier tipo de diseño que cumpla esa restricción no afecta a las estadisticas.

**Comment by jheysen** [comment]
A priori no te tendría que afectar, pero recuerda que en cátedra y en ayudantía se vio el esquema donde para encontrar una entrada a la dirección base de la tabla de páginas le sumas el número de página que quieres encontrar, y lo que está en esa dirección corresponde a la primera dirección de esa página.
