### ISSUE TITLE
[T05] Pregunta 5.1, qué significan los bits de flags?

### ISSUE THREAD

**Issue by fgbruna** [IIC2343/syllabus#217]
Tengo una idea pero no estoy tan seguro, por lo que me gustaría corroborar(si es posible).
Cuando mencionan que se usan 4 bits para **_flags_** se refieren a que, a los bits para codificar la relación **página -> marco** en una tabla, se le agregan 4 bits para validez, disco, etc ?

**Comment by Arcoirisky** [comment]
Los bits de flags son bits que se agregan a la entrada de la tabla de páginas :D

**Comment by Arcoirisky** [comment]
o Metadata, como prefieras uwu

**Comment by fgbruna** [comment]
Gracias!
