### ISSUE TITLE
Tarea 5 - Bits por entrada

### ISSUE THREAD

**Issue by RobinCuevas** [IIC2343/syllabus#219]
Hola!
Alguien puede explicarme que son los bits por entrada, para la pregunta 5? 

Gracias de antemano!

**Comment by jmwielandt** [comment]
Hola!

- **Bits por entrada:** = la cantidad de bits que ocupa tu "dato" + los 4 bits que usamos para flags
- **Bits de página:** el número de bits que necesitas para direccionar a todas tus páginas
- **Bits de marco:** el número de bits que necesitas para direccionar a todos tus marcos físicos

**OJO:** los bits de flags se quedan únicamente en la TLB!
No es necesario que ajusten ningún tamaño para que sea múltiplo de 1 byte.

Saludos!

**Comment by seba608** [comment]
Hola @jmwielandt,

Dos consultas,

1) En la explicación de bits por entrada, con "dato" te refieres a offset?
2) Quizás estoy entendiendo algo mal pero puede ser que la línea 4 de la tabla esté mala?

Saludos!

**Comment by Arcoirisky** [comment]
Hola~ 

Sobre la segunda pregunta, la respuesta es no. La tabla no está mala :0 

Y respondiendo la primera, también es no. Con la información que tienen más la materia deberían poder completar la tabla.

**Comment by seba608** [comment]
@Arcoirisky Gracias!

**Comment by miortiz1** [comment]
Hola, llevo ya rato dandole vueltas y de verdad no logro entender a que se refieren con bits de entrada si no es el offset, de lo que entiendo de los apuntes si es que no fuera el offset, y fuese la cantidad de bits que necesito para direccionar cada entrada , no deberian ser los bits de dir virtual + 4 siempre?

**Comment by Arcoirisky** [comment]
@miortiz1 ¡Hola! Básicamente, corresponde a los bits que contiene cada entrada de la **tabla de páginas**. Piensa que esta tabla es utilizada para hacer las traducciones de direcciones virtuales a direcciones físicas y, por otra parte, los bits de _offset_ ya los posees porque son los mismos de tu dirección virtual de entrada. Entonces, ¿qué bits debería contener, además de las _flags_? **Pista:** Lo que te falta para poder construir tu dirección física, dado que ya tienes el _offset_. :)

**Comment by miortiz1** [comment]
😊 muchas gracias!

**Comment by MrEarle** [comment]
No se si estoy entendiendo mal, pero si necesito `n` bits para direccionar todas las páginas, entonces necesito por lo menos `n+4` bits para cada entrada en la tabla de páginas (o no?)

Mi problema está que en 2 de las lineas de la tabla de esta pregunta, el numero de bits para direccionar a todas las páginas es igual al numero de bits de la entrada de la tabla de páginas, por lo que no hay espacio para los bits de flag o del marco...

Estoy entendiendo mal?

**Comment by vaetchegaray** [comment]
Hola, en la línea 2 de la tabla de la pregunta 5 una dirección física de 26 bits, que no es un múltiplo de 2, entonces no debería ser 16 bits?
