### ISSUE TITLE
[Tarea 8] Duda sobre cache 

### ISSUE THREAD

**Issue by nmaturana97** [IIC2343/syllabus#219]
Hola, 
¿Se debe utilizar el concepto de localidad espacial en la tarea? y en el caso de ser afirmativo, ¿cual es la cantidad de bloques de la cache y cual es la cantidad de palabras por cada bloque?

**Comment by Geeermy** [comment]
¡Hola! Por el solo hecho de utilizar una caché, estás usando el principio de localidad espacial.

Con los parámetros que les damos en el enunciado, puedes determinar la cantidad de palabras por LÍNEA (bloque es en la memoria principal y línea es en la caché, como vimos en ayudantía). Les damos la cantidad de líneas en la caché y el tamaño total de esta... con eso ya pueden calcularlo.

Si sigues teniendo dudas, te recomiendo revisar la solución de la ayudantía 7, ahí hay varios ejercicios donde se hace el paso a paso de los cálculos que necesitan manejar en lo que respecta a caché.

¡Éxito!

**Comment by nmaturana97** [comment]
y asumimos que las palabras son de 1 byte?

**Comment by Geeermy** [comment]
1) Sí, palabras de 1 byte.

2) Por como lo vimos en ayudantía, es en base al _offset_. Si te piden la dirección 5, guardas 4-5-6-7 (5 es la palabra de _offset_ igual a 01 en ese caso). Si te piden la dirección 4, también guardas 4-5-6-7 (4 es la palabra de _offset_ igual a 00). Por último, si te pidieran la dirección 3, guardarías 0-1-2-3 (en cuyo caso 3 es la palabra de _offset- 11). ¿Se entiende? Siempre es en base al _offset_, el que depende del número de palabras por línea.
