### ISSUE TITLE
Como conectar ALU para simulación

### ISSUE THREAD

**Issue by tomasjelvez** [IIC2343/Syllabus#22]
Con mi grupo tenemos la ALU lista, pero no sabemos como instanciar esta entidad en Basys3 para conectarla y tampoco como instanciar la entidad registro. 
Habiamos pensado en conectar la ALU al display a través del registro, haciendo dos señales para cada mitad del dataout del registro, y que esas señales sean los input de la ALU y que el resultado que entrega la ALU este conectado al datain del registro a través de otra señal y así dependiendo del boton central se muestre el resultado. Agradeceria si me pudieran confirmar si estamos bien o no.

**Comment by frvalenzuela** [comment]
Hola @tomasjelvez !

Sobre como instanciar la entidad registro recomiendo ver las grabaciones del taller del viernes 3 de Abril donde lo vimos en detalle.

Respecto a su modelación tienen que considerar que al conectarlo al datain perderán el valor de los operadores, lo que no es lo esperado. 

Recomiendo ver las grabaciones del último taller que también se dan dudas al respecto que quizás pueda orientar a un mejor modelo de resolución a su problema.

Cualquier duda quedo atento. 

Saludos!

**Comment by maormeno** [comment]
Gracias por la respuesta, logramos conectar todo y nos funciona bastante bien; pero tenemos otro problema: cuando presionamos el boton btn(0), tenemos un "with select" que hace que se muestre el display correspondiente al registro del resultado (ocupando los 16 bits del display); al mismo tiempo, ese es el boton que envia la senal para que el load del registro del resultado (el cual actualiza el dataout con el datain, el cual a su vez recibio el resultado desde la ALU). Al parecer toma mas tiempo la actualizacion del dataout que el cambio de los display, por lo que muestra 00000000 por como 15 nanosegundos (esperando el proximo flanco) antes de actualizar al valor correcto del resultado de la ALU. Hay alguna forma de arreglar esto? O tal vez no es tan malo y se toma como que sigue funcionando bien?

Ojala se entienda la pregunta,
Gracias!

**Comment by frvalenzuela** [comment]
Hola @maormeno !

Comentaste muy a fondo el desarrollo de la entrega que otros de tus compañeros podría utilizar, lo que podría ser considerado copia. Favor tener más cuidado para la próxima. 

Responderé tu duda por correo electrónico.

Saludos!
