### ISSUE TITLE
[T01] duda posible caso not

### ISSUE THREAD

**Issue by pfarellano** [IIC2343/syllabus#22]
Hola !

Puede pasar que nos den un json así??

circuit:{from:input1 , to:not1}, {from:not1 , to:output1}

En ese caso como tendría que ser el json del resultado? (porque nand recibe 2 inputs)

Gracias !!

**Comment by ariel-m-s** [comment]
Hola @pfarellano!

1. Sí, ese es un circuito válido. Puede ser usado como test.

2. No te puedo decir cómo sería el ```JSON``` porque responder a eso es tu trabajo. Te confirmo que, efectivamente, los NAND reciben dos _inputs_. Sin embargo, dos circuitos **equivalentes** deben tener la misma cantidad de _inputs_ y _outputs_, estos no pueden ser modificadios. Tienes que descubrir la manera de incluir esto como requisito de tu programa.

Saludos.

**Comment by pfarellano** [comment]
sisi, obvio, pero a lo que me refiero es que cuando dibujamos los circuitos en clases, podemos hacer que por ejemplo una compuerta X reciba dos buses de un mismo input A 
pero cómo tendría que poner eso en palabras ? porque pasaría que solo quedaría un diccionario con X como "to" en el circuito. 

se entiende ?? jajaja

gracias !

**Comment by jmwielandt** [comment]
```JSON
[{"from": "input1", "to": "puertamisteriosa1"},
{"from": "input1", "to": "puertamisteriosa1"},
{"from": "puertamisteriosa1", "to": "output1"}
]
```

**Comment by ariel-m-s** [comment]
Mmm... la verdad es que no entendí bien lo que quisiste decir 😢. Si quieres te explicas de nuevo. También podrías hacer una nueva _issue_ (por una cosa de orden) preguntando algo como “¿Puedo hacer XXX en la tarea 1?” O “¿Es XXX un circuito válido?”.

**Comment by pfarellano** [comment]
esa era mi pregunta !! lo que hizo @jmwielandt 
no cachaba si se pueden repetir dos diccionarios iguales en el circuito , se puede ?

**Comment by ariel-m-s** [comment]
Sí! Se puede. Fíjate que es una “lista”, entonces no hay problema con repetir elementos.

**Comment by jmwielandt** [comment]
En una lista puedes tener repetidos y JSON no llora.
Prueba 
```python
import json

print(json.dumps([1, 2, 2, 3]))
```

**Comment by pfarellano** [comment]
Bacaaan !!! mil gracias a los dos !!! @ariel-m-s  @jmwielandt !
