### ISSUE TITLE
Instalacion Vivado

### ISSUE THREAD

**Issue by BSamilla** [IIC2343/syllabus#22]
Me pueden decir cual es el link en concreto para descargar el programa, seguí el link que está en el tutorial, pero no veo por ninguna parte la descripción "Vivado WebPACK (Free)".

Entré a algunas de las opciones disponibles, pero piden datos muy raros que no se mencionan en el tutorial por lo que supongo que no es el correcto.

Gracias!

**Comment by FranLucchini** [comment]
Hola, me puedes mostrar una foto de las opciones que te aparecen?

**Comment by BSamilla** [comment]
Esas son:
![captura](https://user-images.githubusercontent.com/37226243/38670948-8c131cec-3e20-11e8-90a3-b4da43cb16ab.PNG)
![captura1](https://user-images.githubusercontent.com/37226243/38670949-8c39e1e2-3e20-11e8-8399-44e7843c4475.PNG)
![captura2](https://user-images.githubusercontent.com/37226243/38670950-8c5c56a0-3e20-11e8-8e8b-eb21e0c9d121.PNG)

Pero cuando selecciono alguna me lleva a inicio de sesion, y luego a completar datos de compañia, y no se si esta bien, en caso de estarlo como completo esa zona?

**Comment by Hernan4444** [comment]
Hola, de la primera imagen, tienes que escoger una de esas dos (Windows o Linux), te va a pedir datos de compañía, pero tu los completas con los datos de la U (yo lo hice así y me funcionó). En compañia pones: Pontifice Universidad Catolica de Chile y en primary markey poner  High Performance Computing, los otros espacios ya son intuitivos de que poner.
