### ISSUE TITLE
[T05] Dudas en pregunta 1.c y 1.d

### ISSUE THREAD

**Issue by Regenschrim** [IIC2343/syllabus#220]
En cuanto a la pregunta 1.c: ¿al decir que una instrucción no utiliza una etapa del pipeline hace referencia a que pasa por ella sin hacer nada? Por ejemplo, al realizar una instruccion A = A + B, la etapa de MEM no realizaría nada ya que no se accede a memoria, por lo que en la etapa de WB se guarda el valor en A. ¿A esto se refiere?

En la pregunta 1.d dice que 
>... involucra la colision de dos etapas que requieren la lectura de datos desde un registro?
no se si lo entendí mal, pero ¿hace referencia a que dos instrucciones quieran especificamente solo leer un registro determinado al mismo tiempo (en dos etapas distintas)? ¿o no es necesariamente solo lectura y puede ser que se lee para luego ser modificado?

Gracias de antemano!

**Comment by Arcoirisky** [comment]
Dado que es la pregunta, no te puedo responder por motivos obvios :/

**Comment by Regenschrim** [comment]
Pucha, entiendo, ¿pero algun tipo de orientación es posible? Es que siento que puedo perder puntaje por una pregunta que es sencilla y no es por no saber, si no porque no interpretar bien la pregunta :/ Si no se puede, entiendo y responderé como entendí la pregunta y pondré una aclaración para que la vean a la hora de corregir. Gracias igual!

**Comment by MrEarle** [comment]
Yo tambien encuentro confuso el enunciado de esas 2 preguntas. Seria buenisimo si pueden aclararlo!

**Comment by daleal** [comment]
Hola! Para la pregunta 1.c, que una instrucción no utilice una etapa del pipeline quiere decir, efectivamente, que pasa por esa etapa sin realizar ninguna operación (i.e. sin realizar cómputos o alterar el estado).
Por otro lado, para la pregunta 1.d, considera que la pregunta solamente menciona lectura de datos para orientar tu respuesta (qué problema se podría dar?). Por lástima, más allá de eso no podemos responderte, ya que involucraría entregar gran parte del análisis esperado. Ojalá que con eso queden aclaradas ambas dudas!

**Comment by Regenschrim** [comment]
Con eso es suficiente, gracias!
