### ISSUE TITLE
[Tarea 5] Pregunta 3.b

### ISSUE THREAD

**Issue by Taeval** [IIC2343/syllabus#221]
No entiendo la pregunta. ¿Qué es una operación CISC completa?

**Comment by Arcoirisky** [comment]
Que es 100% CISC. No sabría como explicarlo de otra forma. Una operación que sigue la idea de CISC en todo momento.

**Comment by daleal** [comment]
Hola! Para complementar un poco, ejecutar una operación CISC **completa** es ejecutarla de inicio a fin sin alterar la forma en que los cómputos son llevados a cabo! Ojalá te sirva!

**Comment by rjdelrio** [comment]
a mi aun no me queda clara la pregunta: es conveniente implementar un procesador cisc con unidades que resuelven la operación cisc completa?, las instrucciones son cisc o risc (o oisc) entonces como aplica la pregunta a este concepto?

**Comment by Arcoirisky** [comment]
Para entender la pregunta, primero necesitas entender qué significan los conceptos que se preguntan (por eso la parte a) una vez con eso claro entiendes el fin de la pregunta.

**Comment by rjdelrio** [comment]
es que mi pregunta se resumen en que si en esta parte falta un "o" o no:
Dado su conocimiento sobre pipeline y arquitecturas, ?es conveniente implementar
un procesador CISC con unidades que resuelven la operacion CISC completa? "o" ?Es
mejor construir un computador RISC que emule la arquitectura CISC de alguna forma?
Justique.
