### ISSUE TITLE
[Tarea 8] Números de páginas iguales

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#221]
se supone que en la TLB o en la tabla de páginas, buscamos en alguna de sus "n" páginas la que corresponde  según la entrada virtual y con ella tomar el marco (y realizar las operaciones correspondientes para obtener la dirección física) pero, en casos como buscar direcciones virtuales como el 1 y el 2, ambas (y varios otros casos más) tienen número de página "00000" (Para el ejemplo de la tarea, programa 1) ¿cómo saber que cuál de los dos estamos tomando?

**Comment by Geeermy** [comment]
Recuerda que tu dirección virtual se separa en ```bits_página + bits_offset``` y la física en ```bits_marco + bits_offset```. Al hacer la traducción, si bien las direcciones virtuales 1 y 2 te traducirán al mismo marco físico al tener la misma página (dentro de un mismo proceso, claro está), el _offset_ **será distinto**, por lo que la dirección física resultante sí o sí será distinta. Ojo que independiente de esto, si la página ya está asignada en ambos casos te va a dar un _hit_, al igual como lo vimos en ayudantía con la _caché_ cuando accedíamos a dos palabras pertenecientes a una misma línea.

Espero que se entienda. 😁

**Comment by Arcoirisky** [comment]
gracias!! <3
