### ISSUE TITLE
[T8] Duda filas repetidas en tablas de páginas distintas

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2343/syllabus#222]
En el caso hipotético que tengamos más programas que marcos físicos, eso ¿no significaría repetición en las filas de algunas tablas de páginas distintas? En caso de serlo ¿Existe alguna forma de evitar dicha repetición?

**Comment by jheysen** [comment]
Solo una tabla de paginas puede tener el marco en válido al mismo tiempo

**Comment by Geeermy** [comment]
Exacto. Complementando lo que dice Jurgen, recuerda que cuando se acaban los marcos físicos (_i.e._ todos han sido asignados) comienza el proceso de _swapping_. De esa forma, podrían haber "marcos físicos repetidos", pero uno de ellos tendrá un bit de metadata que indicará que el marco de ese proceso **está en disco** y no en la memoria física.

**Comment by frvalenzuela** [comment]
Lamento mi insistencia pero sigue quedándome una duda. 

Si por ejemplo tuviese 4 marcos y 5 programas, en el caso de que programa 1 acceda a dir virtual 0, luego cambió de contexto  programa 2 acceda a dir virtual 0, cambio de contexto programa 3 accede a dir virtual 0,   Cambio de contexto programa 4 accede a dir virtual 0, cambio de contexto programa 5 accede a dir virtual 0. Si la fila que mapea la página 0 con el marco físico correspondiente se repete con algún programa y el programa 5, ocurrirá lo que dice Germy. Pero si se repitiese dicha fila entre el programa 1 y el programa 2, para dicho momento la memoria no estaría llena, no habría swap y dos programas distintos ocuparían el mismo marco traduciendo las mismas direcciones físicas, lo que tenia entendido que se debía evitar. 

O acaso estoy obviando algo importante ?

**Comment by Geeermy** [comment]
Estás obviando algo súper importante. ¿Por qué asumes que ocupan el mismo marco? Si bien todos acceden a la misma página virtual, tú siempre les asignarás un marco físico distinto...

**El siguiente ejemplo es asumiendo que no se ha asignado ningún marco:**

* Proceso 1 accede a dirección virtual 0 -> Asignamos marco físico 0
* Proceso 2 accede a dirección virtual 0 -> Asignamos marco físico 1
* Proceso 3 accede a dirección virtual 0 -> Asignamos marco físico 2
* Proceso 4 accede a dirección virtual 0 -> Asignamos marco físico 3
* Proceso 5 accede a dirección virtual 0 -> Asignamos marco físico 0 (por LRU el que haya sido accedido hace más tiempo).

Por lo tanto, es imposible que pase lo que planteas.

**Comment by frvalenzuela** [comment]
Pero para eso yo debería haber tenido de antes en las tablas de páginas lo siguiente:

Tabla P1
Pag virtual | marco 
0                 |0
1                 |1
.
.
Tabla P2
Pag virtual | marco 
0                 |1
1                 |2
.
.
Tabla P3
Pag virtual | marco 
0                 |2
1                 |3
.
.
.
Tabla P4
Pag virtual | marco 
0                 |3
1                 |4
.
.
Tabla P5
Pag virtual | marco 
0                 |0
1                 |1
.
.

En dicho caso, la repetición se daría que la tabla entre la primera tabla de página y la tabla de página de numero igual al numeros de marcos +1. Pero si yo hubiese hecho las tablas de páginas de otra forma tal que la tabla 1 y la tabla 3 sean la que se repitiese entonces ocurriría. 

O es que acaso debemos crear la tablas de página on-the-fly según espacio libre y politica de reemplazo? No debería estar diseñadas antes de comenzar las asignaciones? O debemos agregar alguna restricción al momento de crear las tablas de páginas de cada programa?

**Comment by Geeermy** [comment]
Felipe, las tablas de página son estructuras donde **todas** las entradas son inválidas al comenzar la ejecución de la simulación. Vas ingresando números de marco a medida que los vas asignando, **nunca** partes con una estructura con asignaciones ya realizadas. Además, al igual que con la _caché_, tienes bits de _metadata_ que te indican las características de la entrada. Tienes un bit de validez que te indica si la entrada es válida o no (al principio, **todas las entradas de todas las tablas son inválidas porque ningún marco físico ha sido asignado**, se marcan como válidas una vez que se hace la asignación). Además, hay un bit de disco que te indica si el marco físico está almacenado en disco o no. Si llega un proceso que llega a pedir un marco físico **ya asignado**, este primero se almacenará en disco, la entrada de la tabla de páginas del proceso que estaba haciendo uso de él **activará el bit de disco** y, finalmente, se hará la asignación correspondiente. De esta forma, se evita que dos procesos accedan a un mismo marco físico.

Con respecto al espacio, cada tabla tiene el mismo tamaño, que es igual a _número entradas * ancho entrada_, en este caso _número entradas_ es el número de páginas por proceso y _ancho entrada_ son los bits de marco físico + los bits de _metadata_. No necesitas más espacio que eso por proceso.

Finalmente, no entiendo en tu ejemplo por qué a todos los procesos les asignas la página 1... todos tuvieron acceso **solo a la página 0, no asignas nunca, en ningún caso, la página 1 según la secuencia que estamos viendo de ejemplo**. Y aunque tu ejemplo "se viera así", los bits de _metadata_ indicarían que solo uno de los marcos repetidos está en la memoria física, mientras que el otro está en el disco. Así funciona la paginación.

Te recomiendo que revises bien los apuntes y clases antes de seguir con la tarea (incluso los ejercicios de la ayudantía si es necesario), ya que es primordial que entiendas cómo funciona para poder programar lo solicitado.

**Comment by frvalenzuela** [comment]
Pero según los mismos apuntes "..Esto quiere decir que **se deben tener almacenadas entradas para todas las posibles páginas, aunque estas no estén utilizadas.** Para diferenciar las páginas que están correctamente mapeadas a un marco físico de las que no, se agrega a la tabla de páginas un bit de validez el cual cuando tiene el valor 1 indica que esa entrada es válida, y cuando tiene el valor 0 indica que no lo es..." Por lo que me parece raro que vaya ingresando los números de marco a la tabla a medida que se vaya leyendo.

A menos que con asignación se refiera a que se cambie el bit de validez, en dicho caso y mi pregunta prevalece, por que si tiene lo siguiente con el mismo ejemplo (suponiendo 8 paginas virtuales, 4 marcos y cinco programas) :

Tabla P1
Pag virtual | marco | validez | disco
0           |  0    |   1     |   1
1           |  1    |   0     |   0
2           |  2    |   0     |   0
3           |  3    |   0     |   0
4           |  0    |   0     |   0
5           |  1    |   0     |   0
6           |  2    |   0     |   0
7           |  3    |   0     |   0


Tabla P2
Pag virtual | marco | validez | disco
0           |  1    |   1     |   0
1           |  2    |   0     |   0
2           |  3    |   0     |   0
3           |  0    |   0     |   0
4           |  1    |   0     |   0
5           |  2    |   0     |   0
6           |  3    |   0     |   0
7           |  0    |   0     |   0


Tabla P3
Pag virtual | marco | validez | disco
0           |  2    |   1     |   0
1           |  3    |   0     |   0
2           |  0    |   0     |   0
3           |  1    |   0     |   0
4           |  2    |   0     |   0
5           |  3    |   0     |   0
6           |  0    |   0     |   0
7           |  1    |   0     |   0

Tabla P4
Pag virtual | marco | validez | disco
0           |  3    |   1     |   0
1           |  0    |   0     |   0
2           |  1    |   0     |   0
3           |  2    |   0     |   0
4           |  3    |   0     |   0
5           |  0    |   0     |   0
6           |  1    |   0     |   0
7           |  2    |   0     |   0

Tabla P5
Pag virtual | marco | validez | disco
0           |  0    |   1     |   0
1           |  1    |   0     |   0
2           |  2    |   0     |   0
3           |  3    |   0     |   0
4           |  0    |   0     |   0
5           |  1    |   0     |   0
6           |  2    |   0     |   0
7           |  3    |   0     |   0

Esto sería lo que creo que terminaría con el ejemplo dado por Germy. Pero mi duda va a que iniciando el otra forma de distrubución de tabla de páginas como la siguiente:

Tabla P1
Pag virtual | marco | validez | disco
0           |  0    |   0     |   0
1           |  1    |   0     |   0
2           |  2    |   0     |   0
3           |  3    |   0     |   0
4           |  0    |   0     |   0
5           |  1    |   0     |   0
6           |  2    |   0     |   0
7           |  3    |   0     |   0


Tabla P2
Pag virtual | marco | validez | disco
0           |  1    |   0     |   0
1           |  2    |   0     |   0
2           |  3    |   0     |   0
3           |  0    |   0     |   0
4           |  1    |   0     |   0
5           |  2    |   0     |   0
6           |  3    |   0     |   0
7           |  0    |   0     |   0

Tabla P3
Pag virtual | marco | validez | disco
0           |  0    |   0     |   0
1           |  1    |   0     |   0
2           |  2    |   0     |   0
3           |  3    |   0     |   0
4           |  0    |   0     |   0
5           |  1    |   0     |   0
6           |  2    |   0     |   0
7           |  3    |   0     |   0


Tabla P4
Pag virtual | marco | validez | disco
0           |  3    |   0     |   0
1           |  0    |   0     |   0
2           |  1    |   0     |   0
3           |  2    |   0     |   0
4           |  3    |   0     |   0
5           |  0    |   0     |   0
6           |  1    |   0     |   0
7           |  2    |   0     |   0

Tabla P5
Pag virtual | marco | validez | disco
0           |  2    |   0     |   0
1           |  3    |   0     |   0
2           |  0    |   0     |   0
3           |  1    |   0     |   0
4           |  2    |   0     |   0
5           |  3    |   0     |   0
6           |  0    |   0     |   0
7           |  1    |   0     |   0

Aquí la tabla 3 y la tabla 1 serían la misma ( a diferencia de lo anterior donde la tabla 5 era idéntica a la tabla 1) Y yo siguiera nuevamente el mismo procedimiento, osea "asigno" (suponiendo que es solo cambiar el bit de signo) marco físico cero por el llamado de la dirección cero del proceso 1:

Tabla P1
Pag virtual | marco | validez | disco
0           |  0    |   1     |   0
1           |  1    |   0     |   0
2           |  2    |   0     |   0
3           |  3    |   0     |   0
4           |  0    |   0     |   0
5           |  1    |   0     |   0
6           |  2    |   0     |   0
7           |  3    |   0     |   0


Tabla P2
Pag virtual | marco | validez | disco
0           |  1    |   0     |   0
1           |  2    |   0     |   0
2           |  3    |   0     |   0
3           |  0    |   0     |   0
4           |  1    |   0     |   0
5           |  2    |   0     |   0
6           |  3    |   0     |   0
7           |  0    |   0     |   0

Tabla P3
Pag virtual | marco | validez | disco
0           |  0    |   0     |   0
1           |  1    |   0     |   0
2           |  2    |   0     |   0
3           |  3    |   0     |   0
4           |  0    |   0     |   0
5           |  1    |   0     |   0
6           |  2    |   0     |   0
7           |  3    |   0     |   0


Tabla P4
Pag virtual | marco | validez | disco
0           |  3    |   0     |   0
1           |  0    |   0     |   0
2           |  1    |   0     |   0
3           |  2    |   0     |   0
4           |  3    |   0     |   0
5           |  0    |   0     |   0
6           |  1    |   0     |   0
7           |  2    |   0     |   0

Tabla P5
Pag virtual | marco | validez | disco
0           |  2    |   0     |   0
1           |  3    |   0     |   0
2           |  0    |   0     |   0
3           |  1    |   0     |   0
4           |  2    |   0     |   0
5           |  3    |   0     |   0
6           |  0    |   0     |   0
7           |  1    |   0     |   0

Luego repito lo mismo para el proceso 2, quien queda "asignado" el marco fisico 1:

Tabla P1
Pag virtual | marco | validez | disco
0           |  0    |   1     |   0
1           |  1    |   0     |   0
2           |  2    |   0     |   0
3           |  3    |   0     |   0
4           |  0    |   0     |   0
5           |  1    |   0     |   0
6           |  2    |   0     |   0
7           |  3    |   0     |   0


Tabla P2
Pag virtual | marco | validez | disco
0           |  1    |   1     |   0
1           |  2    |   0     |   0
2           |  3    |   0     |   0
3           |  0    |   0     |   0
4           |  1    |   0     |   0
5           |  2    |   0     |   0
6           |  3    |   0     |   0
7           |  0    |   0     |   0

Tabla P3
Pag virtual | marco | validez | disco
0           |  0    |   0     |   0
1           |  1    |   0     |   0
2           |  2    |   0     |   0
3           |  3    |   0     |   0
4           |  0    |   0     |   0
5           |  1    |   0     |   0
6           |  2    |   0     |   0
7           |  3    |   0     |   0


Tabla P4
Pag virtual | marco | validez | disco
0           |  3    |   0     |   0
1           |  0    |   0     |   0
2           |  1    |   0     |   0
3           |  2    |   0     |   0
4           |  3    |   0     |   0
5           |  0    |   0     |   0
6           |  1    |   0     |   0
7           |  2    |   0     |   0

Tabla P5
Pag virtual | marco | validez | disco
0           |  2    |   0     |   0
1           |  3    |   0     |   0
2           |  0    |   0     |   0
3           |  1    |   0     |   0
4           |  2    |   0     |   0
5           |  3    |   0     |   0
6           |  0    |   0     |   0
7           |  1    |   0     |   0

Pero ahora como la tabla de página 3 es como la 5 del caso anterior, debería hacer un swap sin que la memoria este llena quedando:

Tabla P1
Pag virtual | marco | validez | disco
0           |  0    |   1     |   1
1           |  1    |   0     |   0
2           |  2    |   0     |   0
3           |  3    |   0     |   0
4           |  0    |   0     |   0
5           |  1    |   0     |   0
6           |  2    |   0     |   0
7           |  3    |   0     |   0


Tabla P2
Pag virtual | marco | validez | disco
0           |  1    |   1     |   0
1           |  2    |   0     |   0
2           |  3    |   0     |   0
3           |  0    |   0     |   0
4           |  1    |   0     |   0
5           |  2    |   0     |   0
6           |  3    |   0     |   0
7           |  0    |   0     |   0

Tabla P3
Pag virtual | marco | validez | disco
0           |  0    |   1     |   0
1           |  1    |   0     |   0
2           |  2    |   0     |   0
3           |  3    |   0     |   0
4           |  0    |   0     |   0
5           |  1    |   0     |   0
6           |  2    |   0     |   0
7           |  3    |   0     |   0


Tabla P4
Pag virtual | marco | validez | disco
0           |  3    |   0     |   0
1           |  0    |   0     |   0
2           |  1    |   0     |   0
3           |  2    |   0     |   0
4           |  3    |   0     |   0
5           |  0    |   0     |   0
6           |  1    |   0     |   0
7           |  2    |   0     |   0

Tabla P5
Pag virtual | marco | validez | disco
0           |  2    |   0     |   0
1           |  3    |   0     |   0
2           |  0    |   0     |   0
3           |  1    |   0     |   0
4           |  2    |   0     |   0
5           |  3    |   0     |   0
6           |  0    |   0     |   0
7           |  1    |   0     |   0

Lo cual no me hace sentido, debido que el swap debería ocurrir cuando existe un page fault, osea cuando se hayan ocupado todos los marcos.

Leí los apuntes, las clases pero sigue sin quedarme claro el hecho de distintos tipos de tablas de páginas y posibles resultados distintos como este. Estoy confundido, perdon.

**Comment by Geeermy** [comment]
Felipe, lo primero que dijiste es **exactamente lo que acabo de explicar**. Por eso **siempre tenemos un espacio para cada tabla de páginas en cada proceso**, como lo indiqué antes. Voy **asignando** marcos físicos a medida que cada proceso **va necesitando utilizar dichos espacios en memoria**, y al asignarlos, modifico la entrada correspondiente en la tabla de páginas con el valor del marco físico para indicar que **la página correspondiente a la entrada modificada tiene asignado el marco físico que acabo de escribir**. Antes de eso, el contenido es **solo basura**, no me dice nada.

Viendo tus ejemplos: Sí, el primer caso está bien, tal como lo expliqué. Ahora, por lo que veo... el problema es que estás **asumiendo que cada página tiene un marco físico predeterminado y yo simplemente cambio el bit de validez**. Eso **NO FUNCIONA ASÍ**, las tablas siempre parten con información basura, pero yo asigno **el primer marco físico que tenga disponible**.  En tu ejemplo, es **falso** que a P3 le asignaré el marco físico 0, le asignaré el marco físico 2 dado que **es el siguiente que tengo disponible, nunca asignaré marcos que ya estén asignados.** Al final yo solo parto con el espacio asignado para todas las entradas de las tablas de página, pero **su contenido es basura**, yo voy sobreescribiendo **tanto el bit de validez como el marco físico contenido**, no es que yo asigne por "cierta distribución" un marco físico a una página de forma definitiva, lo hago en tiempo de ejecución.

Espero que con esto último ya te quede claro el proceso.

**Comment by frvalenzuela** [comment]
Ahora todo me quedo perfectamente claro muchas gracias @Geeermy y @jheysen, perdón lo reiterativo pero ahora si todo me quedo perfectamente claro. Nuevamente muchas gracias !!
