### ISSUE TITLE
[Control 6] Ayudantía 12 y Ejercicios

### ISSUE THREAD

**Issue by mericci** [IIC2343/syllabus#222]
Hola! podrían subir la solución de la ayudantía 12 para estudiar para el control, y de ser posible si es que se pueden subir ejercicios resueltos como se ha hecho para controles anteriores.

Muchas gracias!

**Comment by Arcoirisky** [comment]
La solución de la ayudantia 12 está subida 🤔

**Comment by Arcoirisky** [comment]
Y más que ejercicios, lo que necesitan para el control es entender bien la materia.

**Comment by daleal** [comment]
La ayudantía estará subida a la brevedad! Disculpen la demora :heart:

**Comment by mericci** [comment]
Buenisimo! muchas gracias!
