### ISSUE TITLE
Tarea 5 P6 - Direcciones Compartidas

### ISSUE THREAD

**Issue by MrEarle** [IIC2343/syllabus#223]
Hola, en la pregunta 6 de la tarea dice:

> Los datos que el proceso P2 almacena en estas ultimas direcciones (de la 4500 hasta la 5000) son compartidos por el proceso P3 (tanto para lectura como para escritura), el que accede a ellos
a traves de las direcciones virtuales 2452 a la 2952.

Cuál es el protocolo en caso de que el proceso P2 traiga a memoria sus direcciones 4500-5000 y luego el proceso P3 los requiera en sus direcciones 2452-2953 (siendo que siguien en memoria, pero traidos por el P2)?

No encontré en los apuntes una descripción de algún caso similar, y lo que encontré en internet menciona 2 posibilidades:

1. Se toman como 2 accesos independientes, por lo que cada proceso trae los datos de esas direcciones a memoria, y quedan repetidos en ella. Cada tabla apunta al marco donde se trajo el dato.

2. De alguna manera el proceso P3 sabe cuando P2 trae esos datos a memoria, por lo que tambien lo registra en su tabla de páginas.

Me inclino por la primera opción que encontré, pero me gustaría confirmar

**Comment by Arcoirisky** [comment]
realmente, como la memoria es **compartida**, sería como el punto dos.

En la tarea puedes dejar una tabla comparativa o lo que prefieras para que ejemplifique mejor lo que tienes en mente.

**Comment by Arcoirisky** [comment]
No confundir con que las direcciones de ambos programas apunten a la misma dirección en la tabla de página. Sino que hay algo que deben de darse cuenta que sucede entre P2 y P3. Y eso eso parte de la pregunta askjds

¡Ánimo!
