### ISSUE TITLE
[T08] Ayuda Para Iniciar

### ISSUE THREAD

**Issue by Dunkan1** [IIC2343/syllabus#223]
estoy algo perdido, entiendo como funciona la multiprogramacion y como funciona la cache, lo que no se es donde entra la cache en la tarea, es decir no entiendo como funcionan ambas en conjunto.

Agradezco desde ya por cualquier respuesta, Saludos

**Comment by Dunkan1** [comment]
Entonces una vez que traduzco con la tabla de direccion virtual a fisica esa direccion fisica la uso como acceso a la cache (arreglando el offset) y si tengo un miss en la cache al copiar el bloque lo considero como swap in y out cierto?

**Comment by Geeermy** [comment]
Bien hasta el final... en _caché_ no hay _swap in/out_, simplemente después de un _miss_ copias el bloque de la memoria principal correspondiente a la línea de la _caché_ que corresponda según la función de correspondencia, nada más. El _swapping_ es solo relativo a los marcos físicos. Si es necesario, revisa el ejercicio de la ayudantía 7 donde se ve cómo se llena la _caché_ según una secuencia de accesos, eso es lo que buscamos.

**Comment by Geeermy** [comment]
**Como lo vimos en clases y en ayudantía**... dos casos:

* Quiero asignarle un marco físico a una página, pero ya no quedan marcos disponibles, lo que implica que debo hacer un _swap out_ del marco físico que corresponda según la función de reemplazo (LRU). Al hacerlo, el marco físico que almacené queda disponible ahora para ser asignado a la página que lo solicita.

* Quiero acceder a un marco físico que está en disco (porque le hice _swap out_ anteriormente). Hago _swap out_ de otro marco físico según la función de reemplazo (LRU), y luego hago _swap in_ del marco original almacenado en disco y lo guardo en el que acabo de desocupar.

Te recomiendo encarecidamente ver los apuntes, clases y ayudantías 7-8 para que tengas claro el funcionamiento de la paginación y _caché_, dado que no les estamos pidiendo algo distinto en la tarea.
