### ISSUE TITLE
Control 6 - Contenidos

### ISSUE THREAD

**Issue by danustilovsky** [IIC2343/syllabus#224]
Hola, cuales son las clases que seran preguntadas en el control 6?

Gracias

**Comment by NicolasAguirre** [comment]
@danustilovsky Pregunte hace 5 dias y aun no me responden...

**Comment by jmwielandt** [comment]
@NicolasAguirre 
@danustilovsky 

Hola!
Sentimos mucho no haber respondido antes.
**Para el control 6 entra coherencia de caché e I/O, la materia vista en las últimas clases.**

Las notas de los controles están en proceso.
No podemos subir las notas por partes ya que se hacen en paralelo, entonces puede que algunas preguntas 1 estén antes que otras, etc.

Saludos y ánimo!

**Comment by vaetchegaray** [comment]
@jmwielandt  Estas seguro que entra I/O? 
Yadran dijo que no entraba lo que vimos las últimas 2 clases.

**Comment by Jaluco** [comment]
bueno mejor estudiar todo parece

**Comment by jmwielandt** [comment]
Hola,
Esa es la información que manejamos. Estamos en proceso de confirmar pero sí, recomiendo que estudien ambos temas.

Saludos.

**Comment by jmwielandt** [comment]
**FE DE ERRATA: entran ambos temas (I/O y coherencia).**
Saludos.
