### ISSUE TITLE
Existe una palabra por linea en la TLB

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#224]
El supuesto `Existe una palabra por linea en la TLB` significa que no habrá `Unicación de palabra`?
![image](https://user-images.githubusercontent.com/24725124/47973000-50c00f80-e080-11e8-8981-e950983d0d37.png)

Y que diferencia habría con este supuesto: `Cada palabra de la TLB es una entrada de pagina`.

**Comment by Geeermy** [comment]
1) Exacto, ya que solo hay una.

2) Que al final el contenido principal de la TLB es el marco físico que se le asigna a una página. Por comodidad, puedes ver la TLB así:

```
          ---TLB---
n_entrada | página | marco |
----------------------------
        0 |     12 |     0 |
        1 |      7 |     2 |
        2 |      0 |     3 |
...
```

Es decir, en cada entrada ver la página y el marco que tiene asignado (que debe ser consistente con la asignación que hallas en la tabla de páginas del proceso).

Espero se entienda. :grin:

**Comment by movaldivia** [comment]
@Geeermy 

1. Osea nuestro índice bloque sería el n_entrada?
2. Con la página y el marco se puede determinar la dirección fisica, pero aún así no estaríamos usando `tag`, ni guardando el `dato` que sería la dirección fisica. Se puede hacer como lo pusiste o fue una simplificación?

**Comment by Geeermy** [comment]
1) Claro, pero es solo un índice, es como hablar de la posición de un arreglo, no te dice nada del contenido... tienes que revisarlo.

2) En este caso puedes considerar que el ```dato``` es el **marco físico** y el ```tag``` el **número de página**, ya que con ellos en conjunto puedes: (1) ver si tu página está en la TLB y (2) hacer la traducción haciendo uso del número de marco físico. Entonces sí, puedes hacerlo como lo puse. :octocat:

**Comment by movaldivia** [comment]
@Geeermy yaaaa, me quedó muy claro. Gracias denuevo !
