### ISSUE TITLE
[T08] Marcos físicos para páginas

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#225]
Hola! No entiendo muy bien una cosa: Cuántos marcos físicos se tienen disponibles? Es el tamaño total de la memoria física partido en el tamaño de las páginas?

Gracias!!

**Comment by Geeermy** [comment]
Exacto :-) otra forma de calcularlo sería obteniendo los bits de marco físico, lo que es igual a:

```
bits marco físico = bits dirección física - bits offset
marcos físicos = 2^(bits marco físico)
```

Esto debiese ser consistente con el cálculo que das de ejemplo.

Espero que se entienda. :sheep:

**Comment by Geeermy** [comment]
**PD: La división que propones está bien, dado que nuestros marcos físicos deben tener la misma dimensionalidad de las páginas virtuales.**

**Comment by nlvargas** [comment]
@Geeermy ¿A qué te refieres con "dimensionalidad"?

**Comment by Geeermy** [comment]
@nlvargas Tamaño. 😁
