### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#225]
Hola, tengo algunas dudas de la tarea (ya he buscado en diferentes enciclopedias, web, etc):

1c: No entiendo a que se refiere una aceleración del pipeline 
2. Lo que no cacho es por que no se pueden usar los NOPS (como el computador) y porque se necesitan (como hacer por software las cosas) 
5.3 Alguna pista que pueda ayudar?? 
6. Si o si es necesario ese dato que P3 comparte con P2 (porque segun yo como que se puede omitir eso y solo estaria molestadno y podria entrar el proceso 3 y hacer un swap si se requiere no mas).

Muchas gracias

**Comment by Arcoirisky** [comment]
1) Un pipeline normal puede influir en el tiempo de ejecución de un programa, un Pipeline “más rápido” podría reducir ese tiempo. El cómo es la pregunta. 

2) Porque es lo que se está evaluando. Los Nops pueden resultar más caros de lo que crees. 

3) Nop

4) La pregunta es la que es y deben contestarla 😅 No modificarla según una posible conveniencia. Y sip, es necesario porque lo dice la pregunta. 

Sin contar que no necesariamente “estaría molestando”. Recuerda los tiempos que te puedes ahorrar evitando swaps al disco. 

Creo que respondí a tus preguntas, saludos~

**Comment by seba608** [comment]
@Arcoirisky En la 5.3 puedo asumir que las matrices a las que se refieren son vectores? Si no es así, a qué se refieren con el producto punto entre matrices? según tengo entendido el producto punto (al menos el clásico) es una operación entre vectores.

**Comment by frvalenzuela** [comment]
Hola @seba608 !
Se refiere al producto punto entre las filas y columnas de ambas matrices para lograr lo que uno esperaría de una multiplicación entre matrices. A eso nos referimos con el producto punto entre matrices. 
Saludos!

**Comment by seba608** [comment]
@frvalenzuela Muchas gracias!

**Comment by seba608** [comment]
@frvalenzuela Me surgió otra duda. Solo para estar seguro, se quiere maximizar el hit rate de la caché o de la TLB?

**Comment by dedarritchon** [comment]
Sobre la pregunta 2: la Stalling Unit es lo mismo que la Data Hazard Unit de las clases? y podrían explicar a que apunta la diferencia entre procesadores reales y computador básico?

**Comment by Arcoirisky** [comment]
@dedarritchon Tu segunda pregunta no se contestará, es parte de la pregunta.

Y la Hazard Unit abarca mucho más que el Stalling Unit. Puedes revisar los apuntes si necesitas ver la diferencia entre ellas.
