### ISSUE TITLE
El orden de ejecucion de los programas esta dado por el numero del programa

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#226]
Si el primer programa hace yield, el segundo también y el tercero también, se sigue con el cuarto o me devuelvo al primero continuando con el segundo?

**Comment by Geeermy** [comment]
Se sigue con el cuarto, en caso de existir. Si no hay más, vuelves al primero y así sigues sucesivamente.

**Comment by movaldivia** [comment]
Ya, gracias !!
