### ISSUE TITLE
Kb

### ISSUE THREAD

**Issue by miortiz1** [IIC2343/syllabus#226]
Duda corta, un KB son 2^10 bits o 2^13? Para la pregunta 5?

**Comment by Arcoirisky** [comment]
2^10!

**Comment by miortiz1** [comment]
Entonces son kilo-bits y no kilo-bytes? O también estoy confundido con eso?🙃

**Comment by jmwielandt** [comment]
Hola!
1 Byte = 8 bits
1 KB = 1024 Bytes = 2^10 Bytes
1 MB = 1024 KB = 2^20 Bytes
Etc.

B -> Byte
b -> bit

**Comment by Arcoirisky** [comment]
2^10 es 1Kb (kilo-byte) :O 
2^13 = 8192 mientras que 2^10 es 1024. 
2^9 es 512 y 2^11 es 2048

Puedes seguir esa lógica y si no quedas conforme, puedes ver este [link](https://es.wikipedia.org/wiki/Kilobyte)
