### ISSUE TITLE
Indice bloque N-Way associative

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#227]
Hola!

¿Cual es la utilidad del índice bloque en los N-Way associative?
Creo que ninguna, pero puede que se me este escapando un detalle

**Comment by jheysen** [comment]
Piensa en qué necesitas para hacer el n-way...

**Comment by Geeermy** [comment]
Para complementar, al final del día el índice de bloque te interesa en _directly mapped_ porque a partir de la dirección obtienes el segmento que determina a qué línea mapear según el índice de bloque. En _fully associative_ y en _N-way associative_ se pone en los diagramas como referencia solamente.

**Comment by movaldivia** [comment]
@jheysen y @Geeermy , gracias!
