### ISSUE TITLE
Estadísticas Swap in, Swap Out, Page Valid, Page Disk

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2343/syllabus#228]
Hola!

No me queda muy claro del enunciado que es lo que son estas estadísticas:
- *Swap In, Swap Out*: ¿Son la cantidad de swaps que se hacen durante la ejecución de cada programa, o se cuentan para cada programa la cantidad de swaps que se realizan de marcos físicos asociados a páginas de ese programa?
- *Page Valid*: ¿Es la cantidad de veces que nos encontramos con una página válida en un marco de la memoria física durante la ejecución de un programa o la cantidad de páginas válidas que quedan de cada programa al finalizar la ejecución completa?
- *Page Disk*:  Al igual que la pregunta anterior, es la cantidad de veces que nos encontramos con una página en disco durante la ejecución de un programa, o la cantidad de páginas en disco que quedan al final de la ejecución.

Muchas Gracias

**Comment by Geeermy** [comment]
* **Como se indica en el enunciado**, es el _swap in_ y _swap out_ por programa.

* No, es la **cantidad de páginas válidas** que queda según la tabla de páginas **de cada programa** al final de la ejecución.

* No, es la **cantidad de páginas en disco** que queda según la tabla de páginas **de cada programa** al final de la ejecución.

En resumen, todas las estadísticas son **por programa** y no globales. Por último, recuerda que **cada programa tiene su propia tabla de páginas**, por lo que tienen sentido las estadísticas pedidas.

**Comment by pdesolminihac** [comment]
Gracias! 
Me quedo claro lo de las 2 últimas.

Lo que preguntaba acerca de los swaps va más a cuando se cuenta que un swap es de un programa en específico.
¿Un swap corresponde a un programa si ocurrio durante la ejecución de ese programa?

**Comment by Geeermy** [comment]
Ah, ahora entiendo, muy buena pregunta.

Al hacer _swap out_, le sumas esa estadística **al programa que haya sido dueño del marco** (que también puede ser el programa mismo que está en ejecución, nada lo impide). Esto es muy importante porque significa que no puedes perder la referencia del programa dueño del marco (esto ya estaba implicado por tener que cambiar el bit de disco del programa correspondiente al hacer _swap out_, pero refuerza más el hecho de que tengan que hacerlo). Por otra parte, al hacer _swap in_ siempre se lo sumas al proceso en ejecución (puesto que él es el que está recuperando un marco físico almacenado en disco).

¿Se entiende? 😁

**Comment by miguelramirezv** [comment]
Me sumo a la pregunta. Yo entendí esto último sobre el número de swap in como la cantidad de swap in que experimentan las páginas de un programa. Lo mismo para los swap out, aunque no necesariamente los swap out de un programa ocurrirán exclusivamente cuando este programa se esté ejecutando. Estoy bien?

Aprovecho de preguntar para asegurarme que una vez que una página se valida, esta nunca se invalida después (a diferencia de las lineas de las cachés)?

Gracias!!

**Comment by Geeermy** [comment]
@miguelramirezv Justo contesté jeje, puedes ver la respuesta arriba, debería contestar tu pregunta (sí, estás bien). :)

Con la pregunta adicional que realizas, claro, nunca se "invalidaría" (a lo más podría activar su bit de disco para indicar que el marco físico fue transferido ya no está en la memoria física).

**Comment by Geeermy** [comment]
@Arcoirisky Total. 👀

**Comment by mvcavieres** [comment]
Hola, no me queda muy claro sobre la cantidad de páginas válidas si se calcula después de haber terminado el programa en especifico, o después de que termine de ejecutar todos los programas?.

**Comment by tomasrivera** [comment]
Hola, si una página queda en el disco luego de la ejecución de todos los programas, se considera como una página válida para la estadística final?

**Comment by Geeermy** [comment]
No, por eso se pide la cantidad de páginas válidas (_page valid_) y la cantidad de páginas en disco (_page disk_).

**Comment by tomasrivera** [comment]
Ya, entonces sólo para estar seguro, el Validez de esta tabla no se refiere a que sea una página válida?
![capture](https://user-images.githubusercontent.com/26392989/48157129-99104500-e2ad-11e8-8e02-b57027422f89.PNG)

**Comment by Geeermy** [comment]
Claro, sería la combinación **Validez = 1, Disco = 0** la que consideramos como página válida.
