### ISSUE TITLE
[T8] Tests

### ISSUE THREAD

**Issue by leylayunis** [IIC2343/syllabus#229]
Hola, subirán algún test de ejemplo para verificar los resultados obtenidos? :pray:

**Comment by Geeermy** [comment]
¡Hola!

Lamentablemente no nos encontramos con tiempo para crear los _tests_. 😢

No obstante, les damos la opción de que utilicen **esta misma _issue_** para que publiquen sus propios _tests_ y los resultados obtenidos, de forma que puedan comparar entre ustedes. Podrían partir, por ejemplo, con un _test_ equivalente al del enunciado.

¡Mucho ánimo!
