### ISSUE TITLE
[TAREA 5] MISD

### ISSUE THREAD

**Issue by Okhan97** [IIC2343/syllabus#229]
Hola,

En la pregunta 4a) nos piden que demos ejemplos de cada una de las arquitecturas, en el tip que nos dan nos dicen que es dificil encontrar ejemplos de MISD y que deberiamos elongar su definicion para que calce con ejemplos reales. Sin embargo no logro entender a que se refieren con "elongar", no me parece que le falte a nada a la definicion segun la taxonomia del Flynn y en internet leyendo varios foros casi todos dicen que esa arquitectura realmente no existe.

¿Algún cosejo o ayuda para encontrar aplicaciones de esta arquitectura?

PD: Según wikipedia lo unico parecido a una aplicacion son "Arreglos sistolicos", pero tampoco entiendo muy bien que son esos, ¿va por ahí la cosa?

**Comment by daleal** [comment]
Hola! Cuando les pedimos que "elonguen" la definición de MISD, lo que esperamos es que alteren lo menos posible esa definición para poder clasificar computadores existentes dentro de ella. Un arreglo sistólico puede calzar dentro de la categoría MISD si se altera levemente la forma en que en estricto rigor se define la clasificación MISD. Ojalá te sirva!
