### ISSUE TITLE
vars arrays interprete

### ISSUE THREAD

**Issue by asimonv** [IIC2343/syllabus#23]
Hola, cómo puedo tener dos variables de arrays en el espacio de otras variables? Podría declarar un array de largo A debajo de otro de tamaño B, pero sería harcodeado.  Lo que quiero es poder tener las direcciones en que comienza cada variable, pero al parecer estaría sobreescribiendo la que está más abajo al moverme en el primer array.

**Comment by asimonv** [comment]
Pero a priori no sé de cuánto es el array como para declararlo a mano. Lo
que puedo hacer es declarar la variable y calcular el largo para iterar
después sobre ese largo, pero si declaro otra variable abajo, se va a
sobrescribir porque el intérprete la declara en la dirección contigua. En
resumen, necesito poder darle un largo a una variable para un array sin
declararlo a mano. Algo así:

arr //  arreglo que necesito darle tamaño (y moviendome con la variable
largo) sin declararlo a mano como la variable matriz.
var // pero como está abajo de arr, se va a sobrescribir al modificar arr.
Podría declararla arriba, pero y si necesito otro array? Igual uno tiene
que quedar encima del otro.

**Comment by Hernan4444** [comment]
@asimonv no se puede lo que quieres, solo es posible declarar un array de largo indefinido, el cual dejas como última variable, pero tener dos ya no es posible con el computador básico que estamos trabajando.
Saludos ✌️

**Comment by asimonv** [comment]
OK, gracias @Hernan4444 !
