### ISSUE TITLE
Ejercicio teórico tarea

### ISSUE THREAD

**Issue by FernandoDeDiego** [IIC2343/syllabus#23]
Hola!
Para responder el ejercicio teórico la idea es que utilicemos conceptos sólo vistos en clases, o pueden ser complementados con otras fuentes externas (libros, internet, etc)?
Saludos!

**Comment by frvalenzuela** [comment]
Hola Fernando!

La idea es que ustedes analicen un problema con lo que ya saben según visto en clases y ayudantías. Pero mientras hagas buena referencia a lo que ocupes no hay problema de apoyarte en fuentes externas. 

Saludos!

**Comment by FernandoDeDiego** [comment]
Ok, muchas gracias!
