### ISSUE TITLE
Error en testcase de prueba (Floats)

### ISSUE THREAD

**Issue by dlcartagena** [IIC2343/Syllabus#23]
Hola, hay un testcase en que están dados vueltas los resultados:

<img width="1218" alt="Captura de Pantalla 2020-04-14 a la(s) 05 37 51" src="https://user-images.githubusercontent.com/37153544/79210115-5774b980-7e12-11ea-9564-2efdc17ce9d2.png">

Lo comparé con esta página: 
https://www.h-schmidt.net/FloatConverter/IEEE754.html

Saludos!

**Comment by jmwielandt** [comment]
Hola,

Recuerda que en el enunciado pedimos imprimir primero el antecesor y luego el sucesor, y -500.000030518 es menor que -500, por lo que es su antecesor, no su sucesor.

Saludos y mucho éxito!
