### ISSUE TITLE
[Tarea 5] Paralelismo Simultaneo

### ISSUE THREAD

**Issue by vijuarez** [IIC2343/syllabus#230]
Hola!

>¿Es posible tener simultaneamente paralelismo del tipo SISD y SIMD? Si su respuesta es negativa, justifiquela, y si es positiva, indique detalladamente un caso en que esto se de.

No me queda claro a que se refieren con tener paralelismo simultaneo de dos tipos en la pregunta 4-c. No se muy bien como explicar lo que me confunde sin decir mi respuesta, pero es algo asi:

Se refieren a que un solo procesador se pueda clasificar de ambas formas, o que un mismo sistema (entiendase, un computador) este ocupando distintos procesadores de forma paralela que se puedan clasificar asi?

Gracias!

**Comment by Arcoirisky** [comment]
La definición de SISM y SIMD debería de poder aclarar tu duda o al menos guiarte a tu respuesta. Porque por lo que dices siento que estás alejándote del foco de la pregunta. 

Mándame un mail si quieres y podemos verlo bn xD

**Comment by vijuarez** [comment]
Aún no me queda claro, así que voy a escribirte.

Gracias!!
