### ISSUE TITLE
[T8] Duda sobre memoria virtual

### ISSUE THREAD

**Issue by fdduarte** [IIC2343/syllabus#230]
Hola,
En el enunciado nos dan una capacidad para la memoria virtual. Mi pregunta es: **¿en qué casos esta se llena?** Lo que tenía pensado era que si nos dan muchas direcciones, donde cada instrucción es de una palabra, esta se podría llenar...
Y en el caso que se llene la memoria virtual, **¿qué se debe hacer?**
Muchas gracias de antemano

**Comment by Geeermy** [comment]
La memoria virtual no se llena, es la memoria física la que lo hace. Al final puedes usar todas las páginas para todos los procesos, pero no te vas a salir de ese rango ya que **las direcciones virtuales que te daremos no superarán las dimensiones que te damos**. Es decir, si mi memoria virtual es de 256 byte, por ejemplo, tengo 256 direcciones virtuales y nada más, no te daremos un acceso a una dirección que sea mayor a 255, así que nunca tendrán problemas en ese sentido. El único problema sería si se llenara el _swap file_, dado que ya no se podría hacer _swapping_ y todo el proceso se caería... pero estamos asumiendo que dicho archivo es infinito, así que eso no es tema.

**Comment by Geeermy** [comment]
**Nota:** Aunque se usen todas las páginas de todos los procesos, asumiendo que la memoria física es menor a la memoria virtual **nunca serán todas válidas en un mismo instante** dado que estarás limitado por la cantidad de marcos físicos existente. Podrás asignar todas a un marco físico, pero algunas de ellas lo tendrán almacenado en el _swap file_ definitivamente.

**Comment by fdduarte** [comment]
¡Buenísimo!
Entiendo bien lo del swap en el caso de que se llene la memoria física, tenia dudas de que pasaba si nos daban un programa muy largo que no cupiera ni en la memoria virtual, teniendo que hacer swaps de la memoria virtual al hdd o cosas por el estilo. Pero ya que esto no puede pasar me despreocupo.
Muchas gracias por la rápida respuesta.
