### ISSUE TITLE
[Tarea 5] Dudas pregunta 6

### ISSUE THREAD

**Issue by fperezm12** [IIC2343/syllabus#231]
Para la preguntas de la 6 las tablas de página que se piden son las finales (cuando terminan todos los procesos), después de cada cambio de contexto o de alguna otra forma? Lo mismo para la pregunta 6.1

**Comment by Arcoirisky** [comment]
Hola~ 

Son para cuando terminan todos los procesos :D (6.2)

Para la 6.1 ¿Por qué lo mismo para esta pregunta? O: En esta sería al terminar de ejecutar cada programa **y** el detallar más en lo que sucede antes y después de la ejecución P3.

**Comment by fperezm12** [comment]
Era la misma pregunta porque los marcos van cambiando las páginas que tienen en los distintos cambios de contexto. gracias
