### ISSUE TITLE
Asignación de marcos físicos

### ISSUE THREAD

**Issue by nlvargas** [IIC2343/syllabus#231]
Hola, 

¿En qué momento se le asigna un marco físico a un página?
Para el ejemplo de la tarea existen 512 / 32 = 16 marcos físicos y entre todos los programas tienen más direcciones que marcos físicos posibles. En base a esto, ¿debo asignar los marcos físicos a las páginas al iniciar la ejecución de todos los programas? ¿O cuando leo una instrucción reviso si tiene un marco físico asignado en su tabla de página y de no ser así le asigno uno si es posible (sino realizaría un swap out)?

**Comment by jheysen** [comment]
Se encuentra en las clases y los apuntes la respuesta
