### ISSUE TITLE
[T08] TLB y Memoria física LRU

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#232]
Hola! Tengo dos dudas con respecto a uso de estas memoria:

1.- En el caso de usar una página que se encuentra en la TLB, entonces debo actualizar la última vez del uso de ella en la TLB. Mi duda es: tengo que además actualizar la última vez de uso en la memoria física? Es decir si en tiempo 1 creo la pagina 2 y su marco en memoria y la agrego a la cache, en el tiempo 5 la vuelvo a buscar y se encuentra en la TLB. Entonces la última vez usada de la página 2 en la memoria física es en el tiempo 1 o 5?

2.- Si la respuesta anterior es NO (entonces 1 en el ejemplo), entonces tengo otra pregunta. Si se le hace swap out a una página en memoria que además se encuentra en la caché, entonces se debe invalidar el bit de validez de la página en memoria?

Gracias!!

**Comment by Geeermy** [comment]
1. Sí, dado que al tener que hacer _swap_ tienes que escoger el marco físico a reemplazar mediante LRU. Por lo tanto, el marco físico también debe tener el tiempo del último acceso.

2. Piensa que de todas formas, si una dirección de la _caché_ se invalidara por _swapping_, cuando vuelvas a acceder a ella no lo harás a partir de la misma dirección física (harás uso de otro marco físico al hacer el _swap in_ para recuperar el marco del disco... la probabilidad de que reemplaces exactamente el mismo que tenías antes es prácticamente 0).

😁

**Comment by miguelramirezv** [comment]
Gracias!! Aprovecho de hacerte otra. Cuando se busca una página que aún no se ha creado (inválida), entonces se considera que ocurre un page fault y un swap in? O solo page fault? O ninguna de las anteriores?

**Comment by Geeermy** [comment]
Solo _page fault_. Para que haya un _swap in_ involucrado tiene que haber existido un _swap out_ del marco físico al que busca acceder.

Ojo que al iniciar el programa los marcos físicos disponibles simplemente se asignan, no hay _swapping_ de por medio hasta que se ocupan todos y es necesario empezar a cargar todo en disco. Es importante que tengan eso en cuenta para las estadísticas. :grin:

**Comment by miguelramirezv** [comment]
Gracias de nuevo! Lo único que no me quedó muy claro es que pasa si "creo" (valido) una nueva página y los marcos están todos ocupados. Entonces ahí debo hacer swap out de un marco, pero no swap in de una página del disco debido a que esta la acabo de "crear". Entonces considero como que no se hace swap in, aunque haya habido swap out?

**Comment by Geeermy** [comment]
Exactamente, que es lo que está explicado en esta _issue_: #223

**Comment by pdesolminihac** [comment]
@Geeermy 
¿Page fault ocurre solo cuando la memoria fisica está llena?
¿O también ocurre si es que la pagina que estoy buscando no esta en memoria fisica ni en el disco aun que la memoria fisica no este llena?

Por ejemplo el primer acceso del primer programa, ¿Se considera como page fault?

**Comment by Geeermy** [comment]
En los dos casos que planteas se considera _page fault_. La diferencia será que cuando la memoria física esté llena habrá _swapping_ de por medio, lo que implicará que aumente el contador de _swap out_ y, si corresponde, _swap in_. Por lo tanto sí, el primer acceso del primer programa será _page fault_ definitivamente, pero no tendrá _swapping_, asignarás el primer marco disponible directamente.

**Comment by Geeermy** [comment]
Quizás le falta actualización a los apuntes en ese sentido, pero _page fault_ hace más bien referencia al caso en el que una página no está _mapeada_ a un marco físico. Atenderé a mi querida Wikipedia:

> _A page fault (sometimes called #PF, PF or hard fault) is a type of exception raised by computer hardware when a running program accesses a memory page that is not currently mapped by the memory management unit (MMU) into the virtual address space of a process._

No es que se contradiga con los apuntes en todo caso, dado que de todas formas la definición que pusiste es **un caso** donde se da el _page fault_. El tema es que, como dije en #234, no profundizaron en el **inicio de la ejecución**, donde ningún marco físico ha sido asignado a una página.

**Comment by tomasrivera** [comment]
Porque sólo sale que es un _page fault_ en ese caso. Tiene mucho más sentido con lo que sale en Wikipedia de todas maneras. :smile:

**Comment by Geeermy** [comment]
Si lo tomas de esa forma, tampoco se consideraría _page fault_ el hecho de que un marco físico haya sido almacenado en disco, y sabemos que no es así. De todas formas, estoy de acuerdo en que debiese tener una definición más clara y generalizada, se tendrá en consideración para actualizarlo y no generar este tipo de confusiones en el futuro.

Muchas gracias por la acotación. 😁
