### ISSUE TITLE
[Tarea 3] Arreglar

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2343/syllabus#233]
Hola,

Quería consultar si van a arreglar el problema que tuvieron al corregir la Tarea 3.

**Comment by Arcoirisky** [comment]
Sip, estamos en eso.

**Comment by seba608** [comment]
@Arcoirisky Qué problemas están considerando? Yo he encontrado un par y es para ver si es necesario hacerlos saber. Sería bueno que den más información al respecto.

**Comment by jmwielandt** [comment]
@seba608 Acabamos de subir los tests corregidos y actualizamos el readme de los tests. Si hay algún problema con ellos, agradeceríamos muchísimo que nos lo digan lo antes posible.

Gracias! :D

**Comment by jmwielandt** [comment]
Ya vimos el CMP del prostack.txt (estaba como `CMP A, 4` en vez de `CMP Ax, 4`).
Mañana lo vamos a actualizar acá.

**Comment by seba608** [comment]
Hola!

Tengo una duda con la simulación. En el ejemplo del enunciado tanto el SP como el BP parten en la posición 0o0000. Además, yo pregunté por eso mismo en la issue #141 y me confirmaron que partían en esa posición, sin embargo en los archivos de salida con los que se revisarán ambos parten en la dirección 0o7777. No sé bien cual es la política de revisión pero lógicamente mi fila no será igual a la esperada.

Saludos!

**Comment by seba608** [comment]
@jmwielandt Disculpa si es que ya lo habías visto pero se me olvidó etiquetarte

**Comment by jmwielandt** [comment]
Gracias por recordarlo,
Decidimos ignorar ambas columnas para la corrección de la simulación. El único requisito es que los números sean en octal.

**Comment by seba608** [comment]
@jmwielandt Hola tengo unas dudas:

- Puede ser que en el archivo simulador/dirs.txt esté mala la primera columna? Dice que el PC apunta siempre a 0

- Hay algún problema si mis archivos son csv? En el enunciado decía que el archivo de output tenía que ser un csv. 

- Al final van a subir algo para automatizar el probar mi código?

Saludos!

**Comment by seba608** [comment]
Además, creo que los archivos de salida del simulador no tienen las filas correspondientes a las instrucciones RET que se agregaron a los tests

**Comment by jmwielandt** [comment]
Hola, 

- Voy a subir la última versión de los tests que utilizamos, con los errores corregidos (igual si los revisan sería muy bueno).
- ¿A qué te refieres con lo de "csv"? En formato, los valores deben estar separados por comas, si es por la extensión, en principio debieras respetar el nombre que entregamos como parámetro.
- Decisiones ejecutivas determinaron que, dado que aún queda la instancia de recorrección final y el kit de corrección contiene un assembler, este no será subido :( 
>(Pero pueden hacer ustedes un script de powershell o bash que corra todos los tests y luego un archivo .py que compruebe si las líneas son correctas o no, si quieren nos preguntan aquí y les damos algunos indicadores de cómo funciona).
- Efectivamente, decidimos ignorar esa fila, ya que el stack a ese punto está vacío, por lo que no tienen a dónde volver.
