### ISSUE TITLE
NUM_PROG

### ISSUE THREAD

**Issue by mvcavieres** [IIC2343/syllabus#233]
Hola, no me queda muy claro la utilidad del input NUM_PROG. En el enunciado dice que es el número de programas a ejecutar, entonces si por ejemplo tengo 5 programas en PROG y NUM_PROG = 4, solo debo ejecutar los 4 primeros programas de PROG?

**Comment by Geeermy** [comment]
Es una redundancia que quedó en el enunciado, siempre debe coincidir NUM_PROG con el número de listas que viene de _input_. De todas formas, es mejor determinarlo a partir del parámetro en vez de deducirlo del número de listas.

**Comment by mvcavieres** [comment]
Entonces, se puede suponer que NUM_PROG siempre va a coincidir con el numero de programas en PROG?.
Otra duda: Van a subir testcase para probar la tarea y ver si vamos bien?

**Comment by Geeermy** [comment]
1. Sí.
2. Ver #229
