### ISSUE TITLE
Contenido de Multiprogramación, Anexo  [Tarea 8] 

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2343/syllabus#234]
Hola, qué tal? 
En el contenido de los apuntes de multiprogramación, al final nos dan un "Anexo" que es un hint bastante grande, pero aún así, ¿puede ser que hay un error? Se anuncia lo siguiente: 
<img width="1142" alt="captura de pantalla 2018-11-07 a la s 12 52 52" src="https://user-images.githubusercontent.com/26261777/48142818-470af780-e28c-11e8-8790-e677f98f56f5.png">
Sale que existen dos casos cuando el SO va a buscar la entrada, que esté en memoria o esté en disco. ¿No deberían haber tres? Que esté en memoria, esté en disco o que no esté asociada a ningún marco por lo que se tiene que generar el mapeo. 
Corríjanme si me equivoco.

**Comment by Geeermy** [comment]
Es cierto, probablemente eso no lo escribieron pensando en el estado inicial que se plantea en la tarea, que es justamente que no hay ningún marco físico asignado.

Ahora, ojo ahí que hay algo que puede causar confusión: Cuando menciona que se "repite el acceso, ahora ocurriendo un _hit_", ustedes **no deben considerar eso como un _hit_ en la estadística**, solo se considera _hit_ cuando ubicas de inmediato la página en la TLB, no en otro caso.

Espero haber dejado más claro el panorama.
