### ISSUE TITLE
Operación completa pregunta 3

### ISSUE THREAD

**Issue by miortiz1** [IIC2343/syllabus#234]
A que se refieren con "un procesador CISC con unidades que resulevan la operación CISC completa"? No son así todos los CISC, o un CISC puede tener varias unidades para una misma operación (MUL por ejemplo)?

**Comment by frvalenzuela** [comment]
Hola @miortiz1 ! 

Espero que hayas respondido tu duda, dejaré la issue abierta con mi respuesta por si alguien más está con la misma pregunta. 
Respuesta:
Puede darse el caso que una operación CISC sea un conjunto de operaciones RISC. En el caso de MUL podrías tener varias instrucciones que ejecutarán una multiplicación, sin la utilización de una unidad de hardware especializada que multiplique.

Saludos !

**Comment by frvalenzuela** [comment]
Hola @miortiz1 ! 

Espero que hayas respondido tu duda, dejaré la issue abierta con mi respuesta por si alguien más está con la misma pregunta. 
Respuesta:
Puede darse el caso que una operación CISC sea un conjunto de operaciones RISC. En el caso de MUL podrías tener varias instrucciones que ejecutarán una multiplicación, sin la utilización de una unidad de hardware especializada que multiplique.

Saludos !
