### ISSUE TITLE
[T05] Duda pregunta 2

### ISSUE THREAD

**Issue by Regenschrim** [IIC2343/syllabus#235]
Para la pregunta 2, ¿queremos solamente agregar la stalling unit o queremos agregar tambien las forward units? Es que no me hace sentido insertar solo la stalling unit, porque al fin y al cabo usamos los stall para poder esperar valores que obtendremos con un forward.

**Comment by Arcoirisky** [comment]
Al menos solo te estamos preguntando por la stalling unit, si quieres agregar más, puedes hacerlo o: Pero estarías trabajando de más.

**Comment by Regenschrim** [comment]
Yap, es que sí, sentía que iba a gastarme como 5 hojas implementando todo solo para poder poner la stalling unit al final. ¿Ignoro la implementación de las demás cosas o las nombro de forma general? Igual siento que es necesario mencionar las demás componentes para ver como interactuan con la stalling unit.

**Comment by Arcoirisky** [comment]
Sigue tu corazón~

**Comment by Regenschrim** [comment]
Ya jaja
