### ISSUE TITLE
[Tarea 9] Plazo entrega

### ISSUE THREAD

**Issue by nmaturana97** [IIC2343/syllabus#236]
Hola, antes de que ya no haya tiempo para hacer la pregunta:
¿Existe la posibilidad de que la entrega sea el viernes 16, en vez del miércoles 14?
Como comprenderan, todos los ramos empiezan a bombardear con lo que falta, por lo que, por lo menos yo, tengo muchas cosas para esa semana.
¿Podría caber la posibilidad de que suban la tarea 10 cuando esta programada, aun sin finalizar la entrega de la tarea 9?
Quedo atento

**Comment by jheysen** [comment]
Lo consideraremos durante el fin de semana

**Comment by acrojas2** [comment]
Hola:
Apoyo la petición de que publiquen para cuando está programada la tarea 10, serviría para organizar la distribución del tiempo del final del semestre.
Saludos.

**Comment by augustoas** [comment]
Hay alguna opción al final de correr el plazo de entrega para la tarea 9? Apoyo la petición 100%

**Comment by JorgeBdelaT** [comment]
Alguna noticia?

**Comment by llloyola** [comment]
Apoyo completamente la moción, pues el final de semestre me está bombardeando de entregas y tareas, además de las pruebas :(

**Comment by norman123123** [comment]
Porfavor! Hay prueba de bases de datos el miércoles  tambien 😔

**Comment by Jaluco** [comment]
tengo el puro miercoles para hacerla, help, no quiero pasar mas de largo :(

**Comment by jheysen** [comment]
Decidimos darles hasta el viernes, pero la T10 va a salir el miércoles igual.

**Comment by beayancan** [comment]
@jheysen ¿El viernes hasta qué hora?

**Comment by Geeermy** [comment]
23:59.
