### ISSUE TITLE
[T09] Fowarding Units

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#237]
Hola! Tenía una duda de contenido que me acuerdo que se comentó en clases pero se me olvidó. Por qué hay dos Fowarding Unit? Es porque la 2 es exclusiva para cuando se escribe en memoria y la primera para cuando se utiliza el registro modificado en la ALU?

Gracias!!

**Comment by jheysen** [comment]
Lo puedes revisar en los apuntes, pero si, una se preocupa de los registros y la otra del Din
