### ISSUE TITLE
Tarea 5 - Pregunta 4.b

### ISSUE THREAD

**Issue by danustilovsky** [IIC2343/syllabus#237]
La pregunta 4 b) dice

> ¿Qué tipo de operaciones son las que más beneficio sacan del paralelismo SIMD? Complemente las diferencias con ejemplos para cada uno de los casos.

A que se refiere con complemente las diferencias con ejemplos para cada uno de los casos? Dado que preguntas que tipo de operaciones son las que mas beneficio y por lo tanto entiendo que se debe entregar la con mayor beneficio y no varias.

Gracias

**Comment by Arcoirisky** [comment]
Y el xq son con más beneficios, dar ejemplos que dejen claro el xq son mejores que otras instrucciones. Comparar, etc.

**Comment by Jaluco** [comment]
Sigo sin entender la pregunta, cada uno de los tipos en que son mejores compararlo con el resto de las arquitecturas? No tenemos que hacer eso en la a)?
