### ISSUE TITLE
[T09] Dudas supuestos válidos

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#238]
Hola, estoy avanzando en la tarea y no me quiero arriesgar o dar la lata de tener que recorregir después.

1. todo el código estará bueno, sin espacios de más o entre las comas, las mayúsculas estarán bien, etc?
2. (Dir) es una label, nunca un número?
3. Lit es un número positivo o negativo, pero nunca "--2"?
4. en la sección data la sintaxis será "nombre valor", con un espacio de separación siempre y el valor un entero?
5. los errores y cosas se disparan en tiempo de ejecución y no antes?

Creo que es eso _por ahora_.
Gracias~

**Comment by Arcoirisky** [comment]
6. ¿Debemos manejar complemento de 2?

**Comment by jmwielandt** [comment]
@Geeermy ¿cómo vamos a saber si las predicciones fueron erróneas o no sin manejar los valores de los registros? 😰 

O siempre no salto, hago flush y luego ejecuto con normalidad no saltando y sin flush?

![imagen](https://user-images.githubusercontent.com/37153467/48306432-299d8e00-e517-11e8-9d9c-8b06b2176c05.png)

**Comment by Geeermy** [comment]
Toda la razón, perdón, se me fue ese detalle. 😓

**_UPDATE_: Sí, deben manejar los valores de los registros, pero no es necesario que los manejen en binario, pueden trabajarlos como enteros en Python de forma directa para operar más rápido.**

**Comment by Geeermy** [comment]
@jmwielandt Ojo eso sí, recuerda que **siempre decides no saltar.** Los resultados del ejemplo es lo que debería darles, para que tengas eso de referencia al probar tu programa.

**Comment by Arcoirisky** [comment]
@Geeermy Según yo si vamos a tener que manejar en binario ya que tenemos operaciones AND, NOT, XOR de literales, los SHL, SHR que me terminan modificando los valores de los registros con los que trabajo.

**Comment by jmwielandt** [comment]
@Arcoirisky y aquí es cuando amas a python aún más: https://wiki.python.org/moin/BitwiseOperators

**Comment by Geeermy** [comment]
Ya edité de nuevo mi respuesta. :'(

@Arcoirisky Toda la razón, pero de todas formas el enlace que comparte @jmwielandt es buenísimo, lo recomiendo de hecho jeje.

**Comment by Arcoirisky** [comment]
@jmwielandt gracias por mostrarme que la perfección existe ;w;

**Comment by pdesolminihac** [comment]
Una pregunta @jmwielandt, respecto al NOT en los bitwise operators, no es exactamente lo mismo que aplicar complemento a 2 o sí?

**Comment by Arcoirisky** [comment]
Lo que hace ese ~ es literalmente hacer not a cada bite del numero. Lo que sería complemento de 1 PEEERO nosotros vimos en clases como pasar de complemento de uno a complemento de dooossss

**Comment by augustoas** [comment]
Hola ! Con respecto al punto 4**.en la sección data la sintaxis será "nombre valor", con un espacio de separación siempre y el valor un entero?** En los archivos de ejemplo están separados por 3 espacios, se sigue ese formato? o solo un espacio de separación? Gracias !

**Comment by Geeermy** [comment]
@augustoas Yes, fue un error del _copy paste_... así que sí, solo un espacio de separación.

**Comment by miguelramirezv** [comment]
Hola! Para el caso de que ocurra un Flushing para la 3era instrucción cuya acción será Flushing ins1;ins2;ins3, si esta instrucción además necesita hacer un tipo de forwarding para ejecutarse, entonces se debe agregar también?

Por ejemplo:

MOV A,3
ADD A,2
ADD A,B

cómo se imprimirían las acciones de ADD A,B si ocurre flushing en ese momento?

**Comment by Geeermy** [comment]
**Muy buena pregunta**. Sí se imprimen, dado que el _forwarding_ sigue ocurriendo. Una forma válida de hacerlo es la siguiente:

```
MOV A,3 | NONE
ADD A,2 | FORWARDING - MOV A,3 - FORWARDING UNIT 1
ADD A,B | FORWARDING - ADD A,2 - FORWARDING UNIT 1 | FLUSHING - MOV A,3; ADD A,2; ADD A,B
```

Esto se condice con lo expuesto aquí: #246.

Ahora, en la práctica el segundo _forwarding_ **no ocurre**, dado que este **no se alcanza a detectar** ya que la tercera instrucción recién estará en la etapa `IF` cuando te des cuenta de que es necesario hacer _flush_. Por lo tanto, también se acepta (y de hecho, es más correcto):

```
MOV A,3 | NONE
ADD A,2 | FORWARDING - MOV A,3 - FORWARDING UNIT 1
ADD A,B | FLUSHING - MOV A,3; ADD A,2; ADD A,B
```

Al no estar explicitado en el enunciado, pueden manejarlo como les acomode más. Ahora, **la siguiente opción no se aceptará:**

```
MOV A,3 | NONE
ADD A,2 | NONE
ADD A,B | FLUSHING - MOV A,3; ADD A,2; ADD A,B
```

Porque esto ni siquiera se condice con el ejemplo plasmado en el enunciado, donde de todas formas hay un _forwarding_ en instrucciones donde se hace _flush_.

Espero que esto aclare el panorama. 🤓

**Comment by Geeermy** [comment]
Depende del supuesto que hagan. Si sigues la primera forma que puse, sí. En otro caso, no. Simplemente sean consistentes con las decisiones que tomen. La cantidad de _forwardings_ que se vea impresa en las acciones debería coincidir con la que se imprime de las estadísticas.

**Comment by LuisFros** [comment]
@Geeermy Agregando a lo que dije en #254   y sobre tu comentario 

- "Porque esto ni siquiera se condice con el ejemplo plasmado en el enunciado, donde de todas formas hay un forwarding en instrucciones donde se hace flush."

No me queda claro porque ocurre de todas formas el fowarding, es porque la instruccion si llega a ejecutarse?

**Comment by Geeermy** [comment]
@LuisFros Porque la primera instrucción, `MOV A,5` (en tu caso) llega a la etapa `EX`, y como la instrucción`ADD A,B` llega a la etapa `ID`, a través de las señales almacenadas en los registros intermedios `EX/MEM` e `ID/EX` **determinas** que necesitas hacer _forwarding_. Revisa la página 12 de los apuntes y notarás que efectivamente se alcanza a detectar. 😁

**Comment by LuisFros** [comment]
Gracias!! Me quedo muy claro

**Comment by Arcoirisky** [comment]
@amartinezsilberstein ¿y el problema es? 🤔🤔🤔
