### ISSUE TITLE
[TAREA 6] Plazo tarea 6

### ISSUE THREAD

**Issue by Taeval** [IIC2343/syllabus#239]
En el enunciado de la tarea se menciona que el 28 es la fecha límite para la tarea 6, pero en el aviso por mail de la publicación de la tarea se menciona que la fecha límite es el 2. ¿Hasta cuándo hay plazo? ¿Podría quedar para el 2 para tener el fin de semana para hacerla, ya que muchos tenemos exámenes durante la próxima semana? 😟

**Comment by Jaluco** [comment]
+1, si no aparecia este issue me hubiese echado la tarea y por extension el ramo.

**Comment by Conjo1** [comment]
En el cuestionario de ingcursos dice hasta el 2 de julio. Quizás se les pasó en el enunciado

**Comment by Arcoirisky** [comment]
Sip, se nos pasó en el enunciado skndksnd Es hasta el 2 😅

**Comment by shantifabri** [comment]
Hasta que hora es el plazo?

**Comment by frvalenzuela** [comment]
Hola @shantifabri !

Como fue dicho en un anuncio y en cuestionario del siding, es hasta las 23:59 del martes 2 de julio (mañana).

Saludos!
