### ISSUE TITLE
Ejemplo está mal? v.t9

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#239]
Hola, en el output de ejemplo, cuando se hace la suposición del "no salto" después del "JMP start" viene:

MOV A,0
ADD A,B
MOV B,3

pero, en el código se nos entrega:

JMP start
MOV A,**5**
ADD A,B
MOV B,3

Ese 0 debería ser un 5? (En los apuntes está igual)
Sino no sabría de dónde vino ese 0 si se supone que continuó por donde iba.

**Comment by Geeermy** [comment]
Error de tipeo... asuman que en el _output_ y enunciado siempre es 5. Lo actualizaré en un par de horas cuando tenga acceso al computador. :)

Gracias por el aviso.
