### ISSUE TITLE
Proyecto: Duda informe

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2343/syllabus#24]
Hola!

Tengo una duda respecto al punto 1 del informe. Cuando nos piden explicar el comportamiento de los componentes creados, debemos explicar también los "subcomponentes"? Es decir, tengo que explicar mi Half Adder, Full Adder y Adder 16 bits? O sólo este último?

Y también, en que se diferencia la explicación de ese componente respecto al punto 2 y 3 del informe?

Gracias!!

**Comment by Hernan4444** [comment]
@fdominguezclaro en el primer punto, se espera que explican que entra en el componente y que sale, sin detallar en lo que ocurre adentro para transformar lo que entra en lo que sale. Cada componente se entiende como cada archivo .vhl que creaste.

En los otros dos puntos, se espera una descripción de lo que entra, que pasa adentro y lo que sale. Aquí debe haber un mayor detalle de como está implementado (usaron process, hicieron tantos half adders, aprendieron y usaron `for`, etc).

Espero haber respondido tus dudas.
Saludos ✌️

**Comment by fdominguezclaro** [comment]
Si perfecto! Gracias!!
