### ISSUE TITLE
[TAREA 1] En cuanto a argumentos por línea de comando.

### ISSUE THREAD

**Issue by Taeval** [IIC2343/syllabus#24]
En el enunciado se menciona que los scripts se ejecutarán desde consola y que por ejemplo para el circuito equivalente nand/nor, se deben recibir 3 argumentos por línea de comando (como aparece en la imagen). Estoy tratando de hacer esto y logro que: en una línea se ejecuta el programa y en las 3 líneas siguientes ingreso los argumentos uno por uno. ¿Cómo puedo ingresarlos en la misma? (No se si esto es parte de la tarea y tenemos que averiguarlos nosotros mismos)

![image](https://user-images.githubusercontent.com/37159657/55195257-b83f3e80-518a-11e9-8d97-e068f0fafe1a.png)

**Comment by Arcoirisky** [comment]
Estás haciendo input por casualidad?
Estoy segura que en aspectos formales está tu respuesta.
Hint: No Es con input

**Comment by Taeval** [comment]
Dónde está lo de aspectos fromales? No lo encontré😓
Muchas gracias!

**Comment by Taeval** [comment]
Ok, ya lo encontré.
