### ISSUE TITLE
T02 Programación y cantidad de nands

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#24]
Hola!! 
tengo la duda de que si causaría, o no, confusión entregando un output con _s_ cantidad de nands.
Más que nada quería saber si es posible entregar en el output compuertas con nombres tipo "X" para luego describir su funcionamiento interno. Al menos a mi, me suena más claro un output de esa forma que con muchos nand{s}. ¿Es legal hacer esta agrupación o la idea es que sea cada compuerta por separado?

**Comment by jheysen** [comment]
Por favor elabora la idea

**Comment by Arcoirisky** [comment]
A ver... Lo que entiendo por output, tal como lo dice el enunciado, es algo del tipo:
```
{
"circuito":[
                {"from":"input1","to":"nand1"},
                {"from":"input2","to":"nand1"},
                {"from":"nand1","to":"nand2"},
                ....
                {"from":"nand291239","to":"out5"},
                ]
}
```
El último número fue una exageración pero se entiende xD 

A lo que me refería con "agrupar" era decir algo como: 
{
"circuito":[
                {"from":"input1","to":"nand_xor_1"},
                {"from":"input2","to":"nand_and_2"},
                {"from":"nand1","to":"nand2"},
                ....
                {"from":"nand_and5","to":"out5"},
                ]
}
```
y luego decir que el nand_xor se compone "de tal y tal manera" con nans O:

**Comment by jheysen** [comment]
Debido a la forma en que vamos a comprobar las tareas después, debe quedar de la primera forma que señalas.
