### ISSUE TITLE
Detalles en formato output

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#240]
¿Es demasiado, terriblemente, HORRIBLEMENTE necesario imprimir las variables como llegaron? En plan:
```
MOV B,(n) | NONE
MOV A,(i) | NONE

```
¿No puedo reemplazarlos por los valores que tiene el data?
```
MOV B,(2) | NONE
MOV A,(0) | NONE
```
No es de flojera, solo no quiero más guerra y, chamullando un poco, así no se pierde información del data en el output(?) 👀 👀 👀 👀  xDD

**Comment by Geeermy** [comment]
Jajajaja, lo siento, pero la idea es que se impriman como llegaron. Piensa, además, que dentro del paréntesis no debiese ir el valor de memoria, sino que el valor de la dirección (si no, imagínate que ```Mem[n] = Mem[i]```, ¿cómo los diferencio?).

Podrías imprimir con la dirección de memoria que le corresponda a esos _labels_ en vez del _label_ mismo... pero lo veo como un paso adicional innecesario.

¡Ánimo! 😅
