### ISSUE TITLE
[T09] Bonus - código con nops

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#241]
Hola, 
Si en el bonus nos pasan un código con nops y no son necesarios, los puedo/tengo que eliminar?

Ejemplo:
```
MOV B,5
MOV A,3
NOP
INC B
```
Ese nop puede ser eliminado perfectamente, pero no sé si esperan que lo eliminemos o si podemos hacerlo para tener el bonus 🤔 
Gracias~

**Comment by Geeermy** [comment]
Hmmm... la verdad, es prácticamente un caso trivial ese, por lo que no creo que sume en la corrección.

El enfoque del bonus es que **reordenen** las instrucciones para evitar perder ciclos. Lo que más esperamos es que encuentren una forma -dentro de lo posible- de evitar por sobre todo _stallings_, ya que esos son los que manejándolos directamente ahorran ciclos.
