### ISSUE TITLE
[Tarea 9] MOV[dir],A

### ISSUE THREAD

**Issue by Nicolasvegam** [IIC2343/syllabus#242]
Con respecto a esta instrucción, que tamaño de memoria debemos utilizar?

**Comment by Geeermy** [comment]
Puedes asumir que es de 8 bits la dirección, al igual que los registros.

**Nota: Los corchetes son de ```Assembly x86```, aquí estamos usando paréntesis, tal como lo indica la ISA del enunciado.**
