### ISSUE TITLE
[Notas] Recorrección T02

### ISSUE THREAD

**Issue by fenahurtado** [IIC2343/syllabus#242]
Hola, me gustaría saber cuando van a subir las notas de las recorrecciones de la tarea 2.

**Comment by Arcoirisky** [comment]
Resuelta y agregar T3 + ctrl 5

**Comment by atbusch** [comment]
@Arcoirisky está recorregida se supone? Porque yo la mandé a recorregir y no me ha cambiado nada

**Comment by frvalenzuela** [comment]
Hola @atbusch ! 


Supones bien, si tienes un problema particular favor mandar un correo electrónico a la ayudante jefe.

Saludos !
