### ISSUE TITLE
[T09][Contenidos] Flecha vertical, ¿dependencia? && ¿Dobles dependencias?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#243]
Hola, 
No se me ocurrió el caso antes, pero si tengo el siguiente fragmento de código:

```
...
MOV A,5
MOV B,5
NOP
NOP
JEQ label1
...
```
Donde estaré intentando leer el registro B (para calcular el salto) al mismo tiempo que escribo en él (`MOV B,5`), ¿hay dependencia o no la hay?
Lo que se me ocurre es que si el tiempo que tarda en escribir en el registro B y luego escribir en el registro id/ex es menor al clock hay dependencia, porque en ese caso entraría en la ALU el valor anterior de B y no el nuevo, pero si el clock es mayor no habría.
¿Cómo lo tomo? ¿O queda a nuestro ~~des~~criterio?

Es muy similar a si elimináramos el `NOP` de la cuarta línea y tuviéramos una dependencia con B (FU2) y una posible dependencia con A (lo que pregunto).

Ah, y otra cosa, si tengo este fragmento de código:
```
MOV A,5
MOV B,6
ADD A,B
```
Tendría una dependencia en la línea 3 con las dos anteriores (necesito ambas FU), ¿cuál es el formato para imprimir eso?
(Todos los casos del enunciado son con una única dependencia)

**Comment by jmwielandt** [comment]
@jheysen 
Gracias.
¿Y sobre el formato para cuando tengo dos dependencias y necesito ambas FUs?
```INSTRUCTION | ACTION1 | ACTION2```
puede ser, o quizás quieren que usemos `;` u otro separador 🤔

**Comment by Geeermy** [comment]
@jmwielandt ¿En qué caso ocurre eso, o es solo hipotético?

**Comment by Geeermy** [comment]
@jmwielandt Sí, es un supuesto razonable, así que puedes mantener ese formato.
