### ISSUE TITLE
Temario Examen

### ISSUE THREAD

**Issue by Sforrego** [IIC2343/syllabus#244]
Podrian subir un temario punto por punto de lo que entra en el examen? 

Gracias!

**Comment by Arcoirisky** [comment]
Una subdivisión de los temas podría ser: 

* Representación de datos
* Lógica Booleana y Circuitos digitales
* Operaciones aritméticas y lógicas
* Programabilidad 
* Control de flujo
* Subrutinas
* Lenguaje de máquina y assembly
* Microarquitectura
* Arquitectura del set de instrucciones (ISA)
* Ejemplos de arquitecturas
* Dispositivos de entrada/salida (I/O)
* Comunicación entre CPU, memoria y dispositivos I/O
* Jerarquía de memoria
* Multiprogramación
* Paralelismo
* Coherencia en una memoria caché
* Y más~

También lo pueden ver según las clases y los apuntes. Pero básicamente sigue siendo toda la materia 😅
