### ISSUE TITLE
Duración Examen

### ISSUE THREAD

**Issue by rafafdz** [IIC2343/syllabus#245]
Hola! Cuanto tiempo se dará para el examen? Tengo otro exámen en el segundo módulo del jueves.

**Comment by frvalenzuela** [comment]
Hola @rafafdz !

El examen dura 2 horas y media. Si tienes un problema con otro examen, manda un correo al profesor con copia a la ayudante jefe explicando tu situación. Si tu otro examen es de ingeniería no deberias tener problema de tope de examen.

Saludos!
