### ISSUE TITLE
[T09] Test

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#245]
Hola! Podríamos hacer como para la tarea pasada dejar una issue para subir tests para ir probando?

**Comment by miguelramirezv** [comment]
Este es un test que estoy probando pero sigo intentando obtener bien el resultado, por si alguien quiere probar:

;Segmento de datos.
DATA:
n   8
h   2
i   0
r   -2
;Segmento de codigo.
CODE:
MOV B,(h)
MOV A,(r)
ADD A,B
start:
ADD A,B
SHL A,A
end:
INC B
MOV A,(B)
MOV A,5
JEQ start
MOV A,B
ADD A,B
MOV (r),A
XOR A,7
MOV B,3
MOV A,B
JNE end
OR B,A

**Comment by miguelramirezv** [comment]
Este es un test que estoy probando:

PROGRAMA:

;Segmento de datos.
DATA:
n 8
h 2
i 0
r -2
;Segmento de codigo.
CODE:
MOV B,(h)
MOV A,(r)
ADD A,B
ADD B,2
start:
ADD A,B
SHL A,A
end:
INC B
MOV A,(B)
MOV A,5
JEQ start
MOV A,B
ADD A,B
MOV (r),A
XOR A,7
MOV B,3
MOV A,B
JNE end
OR B,A

STATS:

==== ACTIONS ====
MOV B,(h) | NONE
MOV A,(r) | NONE
NOP | STALLING
ADD A,B | FOWARDING - MOV A,(r) - FOWARDING UNIT 1
ADD B,2 | NONE
ADD A,B | FOWARDING - ADD B,2 - FOWARDING UNIT 1 | FOWARDING - ADD A,B - FOWARDING UNIT 1
SHL A,A | FOWARDING - ADD A,B - FOWARDING UNIT 1
INC B | NONE
MOV A,(B) | FOWARDING - INC B - FOWARDING UNIT 1
MOV A,5 | NONE
JEQ start | FOWARDING - MOV A,5 - FOWARDING UNIT 1
MOV A,B | NONE
ADD A,B | FOWARDING - MOV A,B - FOWARDING UNIT 1
MOV (r),A | FLUSHING - MOV A,B; ADD A,B; MOV (r),A
ADD A,B | NONE
SHL A,A | FOWARDING - ADD A,B - FOWARDING UNIT 1
INC B | NONE
MOV A,(B) | FOWARDING - INC B - FOWARDING UNIT 1
MOV A,5 | NONE
JEQ start | FOWARDING - MOV A,5 - FOWARDING UNIT 1
MOV A,B | NONE
ADD A,B | FOWARDING - MOV A,B - FOWARDING UNIT 1
MOV (r),A | FOWARDING - ADD A,B - FOWARDING UNIT 1 | FOWARDING - ADD A,B - FOWARDING UNIT 2
XOR A,7 | FOWARDING - ADD A,B - FOWARDING UNIT 1
MOV B,3 | NONE
MOV A,B | FOWARDING - MOV B,3 - FOWARDING UNIT 1
JNE end | FOWARDING - MOV A,B - FOWARDING UNIT 1 | FOWARDING - MOV B,3 - FOWARDING UNIT 1
OR B,A | FOWARDING - MOV A,B - FOWARDING UNIT 1
==== STATS ====
cycles: 32
fowarding unit 1: 17
fowarding unit 2: 1
stalling: 1
flushing: 1

**Comment by haarenas** [comment]
Ojo que la instrucción ADD B,Lit (ADD B,2) no aparece en la isa que nos entregan.

**Comment by Geeermy** [comment]
Súper importante lo que dice @haarenas, recomiendo que modifiquen los _tests_ acorde a eso.

**Comment by cristobalilabaca** [comment]
no entiendo como se podría evaluar la instrucción MOV A,(B), ya que en este punto B vale 3 pero en ningún momento se ejecuto una la instrucción MOV (3), algo. Que valor tendría Mem[3] en este caso?

**Comment by Geeermy** [comment]
@miguelramirezv Correctísimo. Ahora, no probaremos casos donde B salga del rango ya que se escapa del foco de la tarea, así que siéntanse libres de manejarlos como quieran e indicarlo en el README (aunque el manejo con los 0's me parece lo mejor).
