### ISSUE TITLE
Examend - Pruebas semestres anteriores

### ISSUE THREAD

**Issue by danustilovsky** [IIC2343/syllabus#247]
Hola, existe la posibilidad que suban las pautas de los examenes o pruebas anteriores para practicar? o en efecto el link a los repositorios de semestres anteriores donde se encuentren.

Gracias!!

**Comment by Arcoirisky** [comment]
Hola,

Existe mucho material de semestres anteriores en el Siding, pueden empezar buscando por ahí.
