### ISSUE TITLE
Instrucciones

### ISSUE THREAD

**Issue by miortiz1** [IIC2343/syllabus#248]
Hola, estaba revisando la materia y no logro entender bien la deferencia entre el sp y el bp, me pasa lo mismo con las instricciones jal y jr

**Comment by frvalenzuela** [comment]
Hola @miortiz1 !

Respondiendo tu primera pregunta;el  Stack Pointer(SP), es un registro que almacenado la dirección donde se encuentra apuntando el tope del Stack. En computador básico nosotros ocupamos el fondo de la instrucciones de memoria como un apilador de datos, sin embargo si queremos utilizar alguno de los datos que guardamos en este apilador, necesitamos una referencia de donde quedo el último dato apilado, es por eso que nosotros ocupamos el registro mencionado anteriormente. 

Este apilador es altamente ocupado para el manejo de subrutinas, donde podemos guardar los valores de los registros antes del llamado de una función, guardar la dirección de retorno y hacer operaciones sin preocuparnos de alterar los valores de los registros antes de la misma. Ahora bien, ¿qué sucede cuando tenemos una subrutina  hace llamadas recursivas? Pues sencillo, se va almacenado datos uno sobre otro, almacenando los valores en el mismo apilador. No obstante, si mi función tuviese variables locales además de operaciones a ocupar, necesitaría tener muy presente en que lugar de mi apilador fueron almacenados, ya que solo tengo el tope del stack referenciado con el stack pointer. 

Yo en principio no se donde esta datos que fueron ingresados en el stack iteraciones atrás sin información previa del código. Para resolver esta problemática es que nosotros ocupamos un registro adicional para el manejo de la subrutinas, el Base Pointer, que al igual que el SP me indicará una posición del apilador, pero a diferencia de este último, BP me indicará donde comienza a ejecutarse una subrutina, y con el apoyo de protocolos como stdcall, yo tendré control de donde están mis variables locales, donde estará la dirección de retorno de mi función, y en definitiva, voy a tener más conocimiento de mis datos ubicados en mi apilador, que solo ocupando el SP.

Espero que esto resuelva tu primera duda!

Saludos!

**Comment by frvalenzuela** [comment]
Para tu segunda pregunta te recomiendo revisar esta explicación hecha por daniel #34 !

Si te queda alguna otra duda o sigue sin estar claro estaremos atentos!

Saludos!
