### ISSUE TITLE
[T09] Duda Fowarding

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#248]
Hola! Tenía una duda de contenidos. Si es que se tiene el siguiente caso:

1. ADD A,B
2. OR B,A
3. ADD A,7

En el punto 2 ocurre Fowarding de A del punto 1, dado esto no tiene que ocurrir en el punto 3 Fowarding de A nuevamente del punto 1, o sí? Ocurre algún Fowarding en el punto 3?

De antemano, muchas gracias!

**Comment by Geeermy** [comment]
¡Hola!

En este caso, ocurre _forwarding_ de 1 a 2 y de 1 a 3. ¿Por qué? Por dos cosas:

1) La instrucción 2 necesita tener actualizado el valor del registro `A` para poder tener el valor correcto de `B`.
2) La instrucción 3 necesita tener actualizado el valor del registro `A` para poder actualizar correctamente su valor.

Ahora, la diferencia radica en la naturaleza del _hazard_ y la forma de hacer el _forwarding_. Estas situaciones están detalladas en la página 12 de los apuntes, pero básicamente es esto según tu ejemplo:

1) En este caso, hay un _hazard_ dado que la instrucción anterior modifica el registro utilizado en la instrucción actual. Por lo tanto, se hace _forwarding_ del valor almacenado en el registro `EX/MEM` al `Mux FwA` para que la operación de la ALU sea correcta.

2) En este caso, hay un _hazard_ dado que la instrucción previa a la anterior (o "anterior anterior") modifica el registro utilizado en la instrucción actual. Por lo tanto, se hace _forwarding_ del valor almacenado en el registro `MEM/WB` al `Mux FwA` para que la operación de la ALU sea correcta.

En este caso en particular, se hacen necesarios estos _forwardings_ dado que no se detectará un _hazard_ entre las instrucciones 2 y 3 (fíjate que la instrucción 2 no modifica el valor de `A`, así que no le interesa).

¿Se entiende lo que expliqué? Si tienes dudas, sigue profundizando por favor.

**Comment by miguelramirezv** [comment]
Sí entendí perfecto! Gracias!! 😄
