### ISSUE TITLE
Notas Control 6

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#249]
Hola, podrían subir los puntajes q llevan del control 6 (así lo hicieron con edd el año pasado) e iban subiendo las notas a medida q las tenian. Seria Epico.
GRAAACIAS

**Comment by Arcoirisky** [comment]
Estimado, para evitar casos de ansiedad se ha decidido no realizar liberación parcial de las notas del (control/tarea/etc) si no hasta que se haya terminado de corregir hasta el último alumno y se revisen preliminarmente las notas.

**Comment by NicolasAguirre** [comment]
@Arcoirisky jajajaj yaa muchas gracias! ojala las tengan pa hoy :==O
