### ISSUE TITLE
[Tarea 1] Duda con el main.py

### ISSUE THREAD

**Issue by Kullak** [IIC2343/syllabus#25]
Por lo que entendí del enunciado nos piden crear un archivo principal main.py que puede llamar a logic_translator.py y circuit_simulator.py. Sin embargo, en el ejemplo que aparece en el enunciado no se llama a un archivo main.py, sino directamente a logic_translator.py.
![Captura de pantalla (241)](https://user-images.githubusercontent.com/48307972/55239248-0731b600-5215-11e9-9c01-f312efdea241.png)
Mi duda es si es que al final es necesario tener un archivo main.py o podemos desde la terminal llamar directamente a logic_translator.py y a circuit_simulator.py.

**Comment by frvalenzuela** [comment]
Hola!

Respecto a tu duda, main.py es solo un ejemplo, debes llamar a la terminal como se muestra en la imagen.

Saludos!
