### ISSUE TITLE
Seleccionar operación en Entrega 1

### ISSUE THREAD

**Issue by mariana-ortega** [IIC2343/Syllabus#25]
Hola!

Tengo una pregunta sobre el sel de la figura 5 del enunciado (tabla de verdad de la ALU).
![image](https://user-images.githubusercontent.com/30672931/79455608-24b9f500-7fbb-11ea-8586-68527876bcca.png)

Ahí hay una convención que se espera para ese sel que selecciona cada operación?
Por ejemplo, todos los grupos debemos tener que '00' es suma mientras '11' es resta ? O podríamos asignarlos como queramos, por ejemplo ''10' será suma y '01' resta ?

Estoy pensando en si corregirán las entregas con un archivo de simulación que ya tenga definido los sel para la ALU.

Saludos,
Mariana

**Comment by frvalenzuela** [comment]
Hola @mariana-ortega !

El sel asignado de sería ideal que siguieran el mismo descrito en clases. De cualquier forma no hay restricción en ese lado, y sería bueno que esta en el informe. El archivo de simulación se ajustará a un sel dado.

Saludos!
