### ISSUE TITLE
[Tarea 02] Pregunta Programacion.

### ISSUE THREAD

**Issue by acrojas2** [IIC2343/syllabus#25]
Hola: 
Tengo varias dudas:

1. ¿Siempre son la misma cantidad de inputs? En el código de ejemplo muestran que existen solo dos, pero no se explicita la cantidad de inputs que se pueden recibir.
 
2. ¿Tienen test para probar el código?

3. ¿Los input son de la forma "input<numero_binaro>" ? Por ejemplo: "input0101", "input0011010010101"
Saludos! 😄

**Comment by FranLucchini** [comment]
Hola:
1.  En la descripción del componente del enunciado se explicita que siempre recibe 2 vectores, no más ni menos.
2.  Por como se describe el comportamiento, se ingresan manualemente los valores usando los switches, por lo que lo puedes probar ingresando los vectores más simples que se te ocurran, como [0, 0, 1] y [0, 0, 1], lo que debería dar como resultado 1 en los displays.
3. No entiendo esta duda, dado que los valores del input se ingresan usando los switches de la placa, por lo que se trabajan siempre como valores binarios.

**Comment by acrojas2** [comment]
Hola @FranLucchini ! me equivoque de título, era Pregunta Programación no Practico, por eso no entiendes mi duda en el punto 3. Cambiaré el título 😄

**Comment by Geeermy** [comment]
¡Hola!

Ahora contesto en base a la parte de programación:

1. No, puede variar. Por eso se sigue la convención "_input{i}_".

2. Ver #29.

3. No. De hecho, en el ejemplo basta con ver que se utiliza "_input1_" e "_input2_".

¡Mucho éxito! 🙌
