### ISSUE TITLE
[Tarea 09] Duda de acceso a memoria

### ISSUE THREAD

**Issue by GabrielLyonB** [IIC2343/syllabus#250]
En el ejemplo de la tarea se define lo siguiente:
```text
DATA:
n   2
i   0
CODE:
MOV B,(n)
MOV A,(i)
```
Y luego se ejecuta: `B=MEM[n]` y `A=MEM[i]`, sin embargo, lo que me hace sentido del ejemplo es que los valores para cada uno son: `A=0` y `B=2`, de este modo la segunda vez que se ejecuta `JNE start` la condición no se cumple por lo tanto continua ejecutando el resto del código.
Entonces, no entiendo cómo se están definiendo los valores de memoria, ¿DATA estaría definiendo que la posición **2** de la memoria toma valor **2**, y asimismo con **i**? 
Estoy un poco perdido con esto, muchas gracias.

**Comment by Geeermy** [comment]
Claro, está bien lo que dices con respecto a `B = Mem[n] = 2` y `A = Mem[i] = 0`, pero fíjate que antes de ejecutar `JNE start`, haces `ADD A,1`, por lo tanto, en el fondo pasa esto (sin _pipeline_):

```
A = 0, B = 2
A += 1
¿A = B? No, saltamos.
A += 1
¿A = B? Sí, no saltamos.
-Ejecución de las instrucciones que están debajo de JNE start
```

Quizás lo que te confunde es que la instrucción es _jump not equal_. En este caso, cuando accedes por primera vez tienes `A = 1, B = 2`. Al no ser iguales, **saltas**. Luego, cuando incrementa `A` nuevamente, tienes `A = 2, B = 2`. Al ser iguales, **no saltas** y sigues ejecutando el resto.

Si te confunde que en la primera pasada por el salto se ejecute lo de abajo, entonces te falta estudiar la sección de predicción de salto: como estamos con _pipeline_, luego de tres ciclos de haber comenzado la ejecución de la instrucción **yo determino si correspondía o no hacer el salto**, dado que en la etapa `MEM` se encuentra la unidad de salto. Si correspondía y no lo hice (como es el caso del ejemplo), se hace _flush_ de las tres instrucciones anteriores y se carga la instrucción que correspondía según el salto. En la página 18 de los apuntes de paralelismo simple se profundiza este caso.

¡Ánimo!

**Comment by GabrielLyonB** [comment]
Creo que me expliqué mal. Entiendo lo del salto, lo que no entiendo es el acceso a memoria y la definición de esta. Según lo que me dices: `B = Mem[n] = 2` y `A = Mem[i] = 0`, pero en qué posición están en memoria las posiciones `n` e `i`. Si miro la memoria como un diccionario tengo algo así:
```python
# ¿Cuáles son estas posiciones?
memory = {'n': 2, 'i': 0}
```
No sé si se entiende mejor. Porque si no tengo esos valores, cómo accedo a modificar la memoria después (en caso de haber alguna instrucción que modifique en memoria).

**Comment by Geeermy** [comment]
Ah. **Como se menciona aquí: #238,** siempre se hará uso de _labels_ a lo largo del código. No es necesario que modeles una memoria como un arreglo con posiciones y que `n,i` se asocien directamente a estas, con un diccionario como lo indicas es más que suficiente. Luego, para escribir en esas direcciones, simplemente lo haces con estas instrucciones:

```
MOV (n),A/B
MOV (i),A/B
```

**Consejo:** No se compliquen tratando de modelar el problema lo mejor posible, sean prácticos (como lo haces tú con el uso del diccionario).

**Comment by GabrielLyonB** [comment]
Perfecto, lo mantengo con el diccionario entonces. Muchas gracias.

**Comment by Arcoirisky** [comment]
Según lo que le entendí e hice tu diccionario memory esta bien! Así es como se llama el data. 

Onda, hacer memory[n] te da 2. No es memory[2].

**Comment by malopez16** [comment]
@Geeermy y para el caso de MOV A, (B)? debido a que el valor en registro B será numérico, entonces tendríamos que poder manejar eso, en cuyo caso ese dict no sería suficiente, _creo._

**Comment by Geeermy** [comment]
Puedes hacer que el valor de la llave del diccionario no sea simplemente el valor del contenido de la dirección de memoria... ahí manéjalo como más te acomode (por razones obvias, no puedo dar ideas).

**Comment by malopez16** [comment]
gracias! entiendo. Sólo quería comprobar que no estaba entendiendo mal :)

**Comment by sfga** [comment]
@Geeermy, ¿me podrías confirmar la siguiente situación?

MOV (n),B asignar el valor del registro B en la dirección 'n' de la memoria

Opción 1:
MOV B,(n) asignar el valor de 'n' al registro B

Opción 2:
MOV B,(n) asignar al registro B el valor existente en la dirección 'n' de la memoria

En mi opinión, la opción 2 la encuentro válida (se usa la nomenclatura de direccionamiento), pero, por los comentarios anteriores, la opción 1 sería la correcta (i.e a considerar) para la tarea, ¿cierto?

**Comment by Geeermy** [comment]
Los dos casos que mencionas son lo mismo. Al final `n` lo puedes considerar como el "nombre" de tu dirección, digamos. Entonces, si `n` fuera la única variable definida, ocuparía la dirección 0 y decir `Mem[n]` sería lo mismo que decir `Mem[0]`. Al final del día, al igual que con los saltos, `n` no es más que el _label_ de una dirección específica (en este ejemplo, la dirección 0).
