### ISSUE TITLE
Control 6

### ISSUE THREAD

**Issue by shantifabri** [IIC2343/syllabus#250]
Hola, iran a tener para hoy las notas del control 6?
Se agradecería mucho :)

**Comment by Taeval** [comment]
Por favooor!

**Comment by Arcoirisky** [comment]
Estimados, lamento que el plazo establecido todavía no se cumple y, recordando que los ayudantes son alumnos con exámenes, no se puede exigir que tengan las evaluaciones antes de tiempo. De todos modos están haciendo todo su esfuerzo para tenerlos lo antes posible pero lamentablemente no será hoy.
