### ISSUE TITLE
Dia Correccion

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#251]
Hola, para el día de la correción podrian poner como horarios para alumnos (en un form) tal vez, para que la gente q vaya no espere mucho tiempo que yo creo q es lo q va a pasar

Gracais

**Comment by Arcoirisky** [comment]
Lo pensamos pero si nos llegamos a alargar con alguno termina siendo lo mismo o hasta peor ya que existiría una promesa de tiempo :T

**Comment by NicolasAguirre** [comment]
@Arcoirisky piensenlo de nuevo :O es q yo creo q van a ir todos y algunos van a esperar muuuuuucho tiempo. Gracias, taria bacan q lo hicieran de alguna optima

**Comment by Arcoirisky** [comment]
Vamos a evaluar tu sugerencia y cuando tengamos todas las notas, vamos a ver que sucede :)

**Comment by NicolasAguirre** [comment]
@Arcoirisky muchas graacias!!
