### ISSUE TITLE
[Tarea 6][Pregunta 1] Señales de control

### ISSUE THREAD

**Issue by danyestay** [IIC2343/syllabus#252]
Hola! No estoy seguro si entiendo muy bien a qué se refieren cuando nos piden "_Identicar las señales de control necesarias para el correcto funcionamiento del computador básico_". ¿Es referirse a las señales que ya están explicadas abajo del diagrama, junto a las que solo están dibujadas en este?

**Comment by Arcoirisky** [comment]
Es identificar las del diagrama y darles un valor en específico para cada una de las instrucciones. (Las de abajo del diagrama son partes del diagrama)

**Comment by danyestay** [comment]
@Arcoirisky Perfecto, pero eso de darles un valor específico iría en la tabla de verdad que piden o no?

**Comment by Arcoirisky** [comment]
Exacto!

**Comment by danyestay** [comment]
@Arcoirisky Gracias!
