### ISSUE TITLE
Recorreccion T4

### ISSUE THREAD

**Issue by Dyoma3** [IIC2343/syllabus#253]
queria saber si puedo hacer una recorreccion presencial de la T4. Le dedique mucho tiempo, revise como 2 dias que me entregara resultados correctos, y tuve 0 puntos. Estuve tambien pendiente a las issues y a lo que otros hacian asique encuentro muy raro esto.

**Comment by Arcoirisky** [comment]
Hola~

Te recuerdo que por las reglas del foro #1 

> El foro no es un medio de reclamos 😞 Cualquier mensaje de este tipo debe ser enviado directamente al coordinador del curso.

**Comment by Dyoma3** [comment]
Estaba preguntando si hay posibilidad de recorreccion presencial

**Comment by Arcoirisky** [comment]
Si puedes,  solo debes pedirlo por el medio formal, que es el formulario de re-corrección.
