### ISSUE TITLE
Duda archivo de ejemplo

### ISSUE THREAD

**Issue by LuisFros** [IIC2343/syllabus#254]
No me queda claro porque ocurre un fowarding 1 en la linea marcada: 
![image](https://user-images.githubusercontent.com/21247721/48588469-0e1af480-e916-11e8-8abe-2480cf0d0b3b.png)
Instruccion previa: MOV A,0
Instruccion actual: ADD A,B
Segun los apuntes, el fowarding ocurre cuando la instruccion previa escribe en el registro lo cual se cumple para este caso y ademas que la instruccion actual utiliza un registro en la ALU (tambien se cumple).

Pero en este ejemplo, las instrucciones [ MOV A,0 ; ADD A,B ;MOV B,3 ] no deberian ejecutarse por el flushing de el salto condicional. Entonces si MOV A,0 no se ejecuta , nunca se va a escribir en en el registro A y ademas no hay un resultado de "AluResult" como lo indica los apuntes para hacer el fowarding.

**Comment by Geeermy** [comment]
¡Hola! Por favor, ver #238.
