### ISSUE TITLE
[Tarea 6][Pregunta 1] R[i] en ISA

### ISSUE THREAD

**Issue by danyestay** [IIC2343/syllabus#254]
Hola! No sé si lo estoy interpretando bien, pero al decir _R[i]_ me estoy refiriendo a uno de los _i_ registros _(i = 0, ..., 3)_ que posee el _Registrer file_? Si fuese así, entonces por ejemplo en la instrucción _MOV A_ estaría almacenando en mi registro elegido por la señal _Da_, el valor de salida _A_, el cual corresponde a un valor del registro escogido mediante _Aa_?

**Comment by Arcoirisky** [comment]
Exactamente es eso!!
Guardas en el registro i lo que hay en el registro j con i,j entre 0 y 3

**Comment by danyestay** [comment]
Buena gracias!
