### ISSUE TITLE
[Tarea 3] Recorrección

### ISSUE THREAD

**Issue by tgarcia5** [IIC2343/syllabus#255]
Hola, quería saber si para recorregir la tarea 3. ¿Hay que hacerlo mandando el form o hay que ir a la última instancia presencial que dieron?.

**Comment by Arcoirisky** [comment]
Mejor manda primero por el form para que lo veamos antes O: 
En una de esas te salvas de venir ese día :D 

Intenta ser detallado y corregir tu código en caso de ser necesario :D

**Comment by emontecinos** [comment]
Hola @Arcoirisky yo mande un form sencillo para la recorrección y mi 1,6 bajo a 1,0 
Tenía un poco del bonus, entonces no cacho que pasó

**Comment by jmwielandt** [comment]
@emontecinos sí me acuerdo de eso 🤔 

Las issues no son lugar para este tipo de dudas, por favor, manda mail a @Arcoirisky con copia al profesor.

Saludos!

**Comment by emontecinos** [comment]
dale, gracias!
