### ISSUE TITLE
[Tarea 6][Pregunta 2] Operaciones en ISA

### ISSUE THREAD

**Issue by danyestay** [IIC2343/syllabus#256]
Hola! En las instrucciones que debemos agregar ocuparon distinta notación? Mi pregunta va a si es que _RD, SA, SB_, es lo mismo que _Da, Aa, Bb_, en ese orden respectivo

**Comment by Arcoirisky** [comment]
Sip, ya se actualizó el enunciado con esos cambios!
Gracias~

**Comment by danyestay** [comment]
Gracias!

**Comment by jjaguillon** [comment]
Sobre este mismo tema. La operación LDI, el literal es la dirección de una memoria, o es lo que se cargaría en el registro(?).

Es decir,

R[Da] = Lit

o

R[Da] = M[Lit]

**Comment by Arcoirisky** [comment]
@jjaguillon, es la segunda opción :D como en el enunciado c:
