### ISSUE TITLE
[Tarea 6] Pregunta 4

### ISSUE THREAD

**Issue by mericci** [IIC2343/syllabus#257]
¿Como se dice que el robot gira a la derecha en 45°, asumimos que el robot puede moverse en diagonal? ¿o debemos hacer que el robot se mueva dos veces hacia la derecha para poder avanzar sobre un solo eje?

**Comment by Arcoirisky** [comment]
Al estar en una grilla con paredes, estas te estorbarían. Ya que no eres un punto. Que el robot se mueva dos veces hacia la derecha para poder avanzar es la respuesta :D

**Comment by mericci** [comment]
Muchas gracias!
