### ISSUE TITLE
Tarea 6 Dudas Generales

### ISSUE THREAD

**Issue by FernandoDeDiego** [IIC2343/syllabus#258]
Hola!
Tengo un par de dudas con respecto a la entrega de la tarea 6. El cuestionario de siding permite una sola subida? y, está publicado el link para crear repositorios? (para subir el archivo .zip). No lo pude encontrar :/
Saludos!

**Comment by Arcoirisky** [comment]
la entrega es 100% Siding como se anunció junto a la tarea, y sip. El cuestionario permite una única subida.

**Comment by FernandoDeDiego** [comment]
Fue mencionado que la entrega era única?

**Comment by Arcoirisky** [comment]
nop, porque no cambié la configuración. Ahora pueden actualizar sus respuestas.
