### ISSUE TITLE
[T02 Programación] Duda sobre input de argumentos

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2343/syllabus#26]
> ...debe tener como nombre logic translator.py y debe tomar dos argumentos:...

¿Estos dos argumentos se deberá entregar por línea de comandos el nombre de las rutas de los archivos, o esperan que se ejecute el archivo y se entreguen en formato de input ?

**Comment by rfenzo** [comment]
Por la línea de comandos

**Comment by frvalenzuela** [comment]
okey, gracias!
