### ISSUE TITLE
Entrega 1

### ISSUE THREAD

**Issue by IriSalazar** [IIC2343/syllabus#26]
Duda, no entiendo como hay que subir las cosas. Proyecto base y Entrega son carpetas paralelas? heeeeeelp

**Comment by CheloRiveros** [comment]
Por lo que entedí yo, ahora mismo deberían haber dos carpetas, una llamada Entregas, con E1 dentro de ella que tenga el informe y el .bit, y otra del Proyecto Base

**Comment by Hernan4444** [comment]
Así es, recuerden que el proyecyo base debe tener los nuevos archivos que crearon con los componentes.

Saludos ✌️
