### ISSUE TITLE
[Tarea 6] Pregunta 5 - Simultaneidad

### ISSUE THREAD

**Issue by javierabao** [IIC2343/syllabus#260]
Hola!
En la pregunta 5, cuando hablan de que se ejecutan muchos procesos de forma simultánea, ¿se refieren a que son 100% concurrentes, o que se produce scheduling entre procesos? ¿Sería un sistema multiprocesador o de un procesador?

Gracias!

**Comment by Arcoirisky** [comment]
Siempre se produce scheduling entre los procesos a menos que tengas varios núcleos O: ahí si podrías ejecutar procesos de forma independiente en paralelo.

**Comment by javierabao** [comment]
Por eso, para la pregunta 5 tenemos 1 o varios núcleos?

**Comment by pfarellano** [comment]
tengo la misma duda, y si son varios núcleos asumimos que comparten o no la memoria ?

**Comment by jmwielandt** [comment]
Tienen un solo núcleo, como en un IIComputador2343 promedio.

Saludos.
