### ISSUE TITLE
Fin de semestre!

### ISSUE THREAD

**Issue by daleal** [IIC2343/syllabus#261]
# Fin de semestre!

Hola a todos! Han pasado casi 4 meses y ya estamos a punto de terminar! Ha sido un semestre interesante y lleno de aprendizajes, pero antes de despedirnos, hay un par de cosas que aclarar para poder cerrar bien el semestre! Aquí van:

## Controles 6

Los controles 6 están subidos! Los pueden ir a retirar el día miércoles desde las 14:00 horas al buzón de tareas como es habitual. Las recorrecciones serán explicadas en su propio apartado.

## ¿Cómo lo hago para recorregir?

Al final del semestre habrá una **recorrectón** presencial para algunas de las evaluaciones del semestre. Lo que se puede recorregir es:

- Examen
- Todas las tareas
- Control 6

Las reglas para recorregir son las siguientes:

- Cada uno puede recorregir su examen.
- Cada uno puede recorregir un máximo de 2 tareas.
- Cada uno puede recorregir su control 6.
- Para recorregir algo, **deben** inscribir la recorrección en [este excel](https://docs.google.com/spreadsheets/d/15pJTfC1NwORrOdIOb_t4usQmwp_xdg2Ex-GyNLGHcQg/edit?usp=sharing). Éste estará abierto hasta el jueves. En el mismo excel están las instrucciones detalladas sobre lo que deben hacer.

La recorrectón presencial será llevada a cabo el día viernes de 10:00 a 14:00 horas en sala por definir, donde estarán los ayudantes del curso para llevar a cabo las recorrecciones.

## Última nota

Bueno, ya casi nos despedimos! Solamente queda formalizar las notas y está todo listo! De parte de todo el cuerpo de ayudantes, quiero expresar nuestros agradecimientos a todos aquellos que participaron de las instancias que existieron para aprender sobre el ramo y a aquellos que nos ayudaron a mejorar a lo largo del semestre! Esperamos que hayan aprendido de nosotros tanto como nosotros lo hicimos de ustedes. Nos vemos el viernes!

**Comment by mericci** [comment]
Será hasta las 13:00 o las 14:00? en el excel aparece disponiblidad hasta las 14:00 y en la issue dice 13:00

**Comment by daleal** [comment]
Hola! Disculpa, fue un typo :sweat_smile: efectivamente es hasta las 14:00, editaré la issue de inmediato. Muchas gracias!
