### ISSUE TITLE
[Tarea 4] Feedback

### ISSUE THREAD

**Issue by Jj1martinez** [IIC2343/syllabus#262]
Hola, quería saber dónde podría ver el feedback de mi tarea 4. No me aparece nada en el excel
Saludos

**Comment by auirarrazaval** [comment]
Hola! 
Les subimos los tests usados y resultados que obtuvimos nosotros al [Syllabus](https://github.com/IIC2343/syllabus/tree/master/Tareas/T04/Archivos_T04), si es que la tarea no corrió puedes probar con eso el por que de cada caso.

Saludos!

**Comment by Jj1martinez** [comment]
El problema que tengo es que si corre con esos test y tengo outputs parecidos pero mi nota es un 1. Entonces quiero saber como evaluaron los outputs para saber como recorregir.

**Comment by auirarrazaval** [comment]
Tu programa generaba los archivos de output en el formato correspondiente? (nombre de archivos, sin espacios, etc...)? Porque se hizo un script que si no seguían al pie de la letra lo estipulado en el enunciado, tiraría error y nota 1. 
Se consideró un rango de aceptación para cada valor del output, por si esa es tu preocupación.
Puedes mandar un screenshot de tu output si quieres para ver que esté todo bien.

**Comment by Jj1martinez** [comment]
Seguí el estipulado por el enunciado, el cual incluía Caché Hit rate pero en los outs de ustedes no aparecen. Aquí adjunto las imagenes del test1
![Captura de Pantalla 2019-07-02 a la(s) 12 57 54](https://user-images.githubusercontent.com/37161666/60531549-369b0780-9cc9-11e9-9581-120a6e1c3fc6.png)
![Captura de Pantalla 2019-07-02 a la(s) 12 57 20](https://user-images.githubusercontent.com/37161666/60531550-37339e00-9cc9-11e9-9416-9e90a6c6e445.png)

**Comment by tomasrivera** [comment]
Revisa como recibes/usas los argumentos del programa.
Saludos

**Comment by Jj1martinez** [comment]
En el terminal :
python3 simulator.py test1.json out.csv
 y dentro del archivo es así:
![Captura de Pantalla 2019-07-02 a la(s) 13 07 58](https://user-images.githubusercontent.com/37161666/60532083-7adad780-9cca-11e9-82c1-a7ab232f23cc.png)

**Comment by tomasrivera** [comment]
Dos cosas, el `/` no es el separador de todos los sistemas operativos y `test` ya incluye el `cwd`, ahí está tu problema.
Que esté o no en el README, no cambia nada porque no cumple con lo pedido en el enunciado.

**Comment by Jj1martinez** [comment]
Entiendo que debía ser absolutos, ahí cometí el error. En el enunciado sale que había que tener especial cuidado pero no que no se corregirá la tarea lo cual es algo extremo.

**Comment by auirarrazaval** [comment]
Se corrigió, y no corrió. Puedes cambiarlo y recorregir sin problemas 😄.

**Comment by Jj1martinez** [comment]
Existiría la posibilidad de recorregir 3 tareas? De qué podría depender eso?

**Comment by auirarrazaval** [comment]
@Jj1martinez Vimos tu solicitud, recuerda subir el código arreglado a tu repo 👀.
Dependerá de la cantidad de solicitudes para las tareas de aquí al jueves

**Comment by Jj1martinez** [comment]
Dale gracias!
