### ISSUE TITLE
[Recorrecciónes Finales] 

### ISSUE THREAD

**Issue by daniellyonvald** [IIC2343/syllabus#264]
Hola, ¿En qué sala serán las recorrecciones mañanas? 
¿Si es que no alcanzan a subir las notas del examen, T05 y T06 se hará igual la recorreción mañana?

Saludos!

**Comment by daleal** [comment]
Hola! La recorrección se llevará a cabo mañana sí o sí! De todas maneras, las notas estarán subidas antes de la recorrección ~~cueste lo que cueste~~. En cuanto a la sala, mañana se enviará un anuncio con su ubicación.
Nos vemos mañana!

**Comment by daniellyonvald** [comment]
Gracias, animo!
