### ISSUE TITLE
Duda I2

### ISSUE THREAD

**Issue by AntoniaChristensen** [IIC2343/Syllabus#27]
Hola! Vi que en el mail que mandaron sale que la materia de la I2 incluye representación de punto flotante (IEEE754 de 32 bits), circuitos secuenciales y la arquitectura del computador básico. Esto incluye la parte de **subrutinas o funciones** que vimos en clases?

Muchas gracias de antemano!!

**Comment by jmwielandt** [comment]
Hola, no incluye subrutinas!

Saludos!

**Comment by jrrosas** [comment]
Hola! Aparte de la ayudantía 2, ¿dónde puedo encontrar más ejercicios para estudiar?

**Comment by jmwielandt** [comment]
Hola, acabamos de subir un compilado de ejercicios de pruebas pasadas que tratan de la materia que entra para esta I.

Saludos~

**Comment by GbPoblete** [comment]
Hola! solo para dejarlo explícito y facilitar el estudio, serían los capítulos 1.5, 3, 4 y 6 de los apuntes oficiales?.

Muchas gracias de antemano!!

**Comment by jmwielandt** [comment]
@GbPoblete son los 1.5, 3, 4 y parte del 5 hasta saltos (incluyendo saltos).
Ten ojo con el cap. 3 ya que llaman "flip flop D" a los latches D.
