### ISSUE TITLE
Sobre los PPT

### ISSUE THREAD

**Issue by fabarros** [IIC2343/syllabus#27]
Holaa, quería saber si es posible que se suban los PPT después de cada clase, ya que actualmente se suben con un delay de una semana y me gustaría poder estudiar los contenidos de la clase anterior antes de cada clase. 
Gracias!

**Comment by Arcoirisky** [comment]
Hola! 

Hacemos lo posible por subirlos cuanto antes pero a veces hay que modificarlos un poco y esperar los cambios u-u)
