### ISSUE TITLE
Tarea 1 - Desafío 5.1

### ISSUE THREAD

**Issue by Snorlax8** [IIC2343/Syllabus#27]
Hola!
Tengo un problema con los caracteres que hay que mostrar. Según veo, uno de los caracteres que hay que quitar del string original entregado es el espacio (caracter 32). El problema que tengo es que, haciendo eso, hay un test que me falla.

Aquí se puede ver que eliminando los espacios llegué al output correcto:
![WhatsApp Image 2019-08-28 at 14 49 06](https://user-images.githubusercontent.com/14048037/63887110-11b1d080-c9aa-11e9-89f4-6ac26e1f879b.jpeg)

Sin embargo, en este test se rechaza mi código por no aceptar el espacio justo antes del \W:
![WhatsApp Image 2019-08-28 at 14 49 39](https://user-images.githubusercontent.com/14048037/63887174-3017cc00-c9aa-11e9-82bf-82d8985c035e.jpeg)

Cabe destacar que me fijé que efectivamente en ambos casos es el mismo caracter (32) el que forma el espacio.

¿Alguna idea?

Muchas gracias!

**Comment by jmwielandt** [comment]
Hola!

<details>
<summary>Descubierto, el misterio!</summary>
<br/>

![image](http://vamosajugar.net/archivo/PMMCielo/images/mm2%20cielo-07085.png)

</details>

Es un tab. Hackerrank lo reemplaza por 4 espacios cuando muestra los ejemplos.

![image](https://user-images.githubusercontent.com/37153467/63901904-ac270980-c9d4-11e9-928f-ecc60dba9891.png)

Saludos~

**Comment by Snorlax8** [comment]
Ahhh, eso lo explica! Muchas gracias 🎈.
