### ISSUE TITLE
Repositorio T1

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2343/syllabus#27]
Hola! me acabo de dar cuenta de que no me ha llegado la invitación de repositorio para entregar tarea :c

**Comment by Hernan4444** [comment]
@ValentinaAlvarezG según github ya aceptaste la invitación, puedes revisar en https://github.com/IIC2343 y escribir T01, ahí debería aparecer tu repo.

Saludos ✌️

**Comment by ValentinaAlvarezG** [comment]
Gracias!!! 😄

**Comment by hagarces** [comment]
A mi tampoco le ha llegado la invitación :c y no me sale nada

**Comment by Hernan4444** [comment]
@hagarces lo mismo que Valentina, github ya nos dice que aceptaste la invitación y tu repo ya está creado. Revisa en la página que señalé y escribe T01

Saludos ✌️

**Comment by hagarces** [comment]
Eso hago pero no me sale nada ;___;

**Comment by Hernan4444** [comment]
@hagarces te saqué y volví a invitar. Revisa tu mail.
Saludos ✌️

**Comment by hagarces** [comment]
ahora si! muchas gracias

**Comment by rjgalvez** [comment]
Hola, a mi no me aparece tampoco mi repositorio! ayuda porfa :(
