### ISSUE TITLE
T02 inputs y outputs

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#27]
en los jsons que nos den los inputs{k} siempre tendrán su output{s} correspondiente donde k=s?
Es decir, el input1 siempre será al final output1 y así con todas las entradas y salidas? O:

**Comment by Geeermy** [comment]
¡Hola!
No necesariamente. Pensemos en un circuito tan simple como A OR B. Este tendría el siguiente JSON:

```
{ "circuit": [
  {"from": "input1", "to": "or1"},
  {"from": "input2", "to": "or1"},
  {"from": "or1", "to": "out1"}
  ]
}
```

En el caso anterior, si bien teníamos dos _inputs_, terminamos con un solo _output_. En resumen, dependerá de la estructura del circuito. 👀 
¡Mucho éxito! 😄

**Comment by Arcoirisky** [comment]
Comprendo O:! Muchas gracias :DD
