### ISSUE TITLE
Entrega 1B - Uso "When"

### ISSUE THREAD

**Issue by eitandv** [IIC2343/Syllabus#28]
Hola!
Quería saber si, bajo el "with # select", podemos ocupar el comando "when" de vivado. Buscando en Internet me di cuenta que este es muy común a la hora de implementar un muxer y quería estar seguro de poder ocuparlo antes de hacerlo.

**Comment by jjaguillon** [comment]
Hola!

Si, el comando `when` esta permitido sólo para el uso en bloques `with/select`. Por ejemplo:

```
with a select b <=
	"1000" when "00",
	"0100" when "01",
	"0010" when "10",
	"0001" when "11",
        signal when others;
```

Cualquier otro caso de uso del  `when` está prohibido.

**Comment by eitandv** [comment]
Oka, Gracias!!

**Comment by jjaguillon** [comment]
@eitandv Por favor, no cerrar Issues. Puede que sus compañeros les sea útil que la Issue quede abierta y más visible.

Gracias de antemano

**Comment by tomcan127** [comment]
Hola
Hay algfuna forma de representar el uso de bloques `with/select` en el diseño circuital?

**Comment by frvalenzuela** [comment]
Hola @tomcan127 !

Te recomiendo revisar la siguiente issue #18 , que puede que resuelva tu duda.

De no ser así, favor hacerlo saber.

Saludos!

**Comment by jjaguillon** [comment]
Hola.

Para representar el bloque `with/select` puedes dibujar un Multiplexor Selector en tu diagrama de circuito, si es a lo que te refieres.

![MUX_example](https://user-images.githubusercontent.com/20802209/64080689-066de600-ccc5-11e9-8cb1-2459e693dddb.jpg)

**Comment by tomcan127** [comment]
Muchas gracias a ambos! @jjaguillon @frvalenzuela
