### ISSUE TITLE
Aplazo T1

### ISSUE THREAD

**Issue by asimonv** [IIC2343/syllabus#28]
Holaa! Pueden aplazar la T01 para mañana a las 12:00PM?? La 2da parte estaba considerablemente difícil.

**Comment by AlainLotissier** [comment]
La App se cae cuando intento probar mi código.. Por último tiempo para poder probarlo.. :)

**Comment by Hernan4444** [comment]
Hola, 
No se dará más tiempo.

Lo que si pueden tener en cuenta es que las tareas se rigen bajo las mismas reglas de metodología de proyecto. Se corregirá el commit más cercano a la fecha de entrega. Si una persona quiere corregir una versión que supere esta fecha, deberá indicarlo con un mail o en un issue del repositorio aceptando el descuento por atraso (5 décimas por hora o fracción).

Por últimp, la App corre el mismo interprete que ustedes disponen y ya se mencionó que ese era beta, que la voz final la tiene el Assemble.exe el cual disponen desde un inicio. 

Saludos ✌️
