### ISSUE TITLE
Entrega 2: Instrucciones Assembly

### ISSUE THREAD

**Issue by nbnavarro** [IIC2343/Syllabus#28]
Hola,

Estoy algo perdido con la construcción del assembly, entiendo que si recibo algo como `MOV A, B` lo puedo transformar a alguna instrucción en binario. Sin embargo, mi problema es cómo traspasar las partes del código que dicen, por ejemplo, `start`, `error`, `CODE: ` o incluso `DATA:` 
¿Hay alguna recomendación para trabajar eso?

Muchas gracias de antemano!

**Comment by MatLop1** [comment]
Hola, 

Respondiendo a tu pregunta, para realizar bien el assembler su programa debe ser capaz de identificar las partes del código assembly y elaborar un traspaso especifico de este a la ROM. Esto quiere decir que al leer el código, su programa debe ser capaz de insertar las partes de DATA, CODE, etc. consistentemente para el uso de estos en la CPU.

Ejemplo de lectura de assembly:  Su programa identifica DATA en el código y empieza a guardar todos los datos en memoria RAM (códigos de guardado de la RAM en la ROM), guardando en el programa las direcciones de memoria usadas (ustedes deciden en que dirección de la RAM guardarla) para poder usarla si se requiere después en el código. Luego identifica CODE y empieza a transformar sus instrucciones a sus respectivos opcode con literales (códigos de instrucciones en la ROM).

Espero que te ayude!
