### ISSUE TITLE
Materia Control 2

### ISSUE THREAD

**Issue by Felipehanckes** [IIC2343/syllabus#28]
Hola! 

Quería saber que materia entrará especificamente en el control 2 y si estos son acumulativos o especificos, es decir, nos preguntaran algo que ya evaluaron en el control1?

Saludos!

**Comment by Arcoirisky** [comment]
Hola~

Los controles buscan evaluar la materia vista en las clases, tareas y ayudantías que hay entre cada control. Pero, no significa que no necesiten saber/entender lo que se ha visto en evaluaciones anteriores. La materia en sí es muy acumulativa, así que si quedan con algún tema colgando pueden preguntar con total confianza :D

En este caso existen tres temas principales que han visto en clases usando tanto el computador básico como MIPS:
1) Arquitectura y modificaciones según necesidad de instrucciones.
2) Ejecución de instrucciones al nivel de palabras de control (Opcode-Literal)
3) Subrutinas

**Comment by Arcoirisky** [comment]
Hola! he agregado la ultima clase que vieron en el contenido que entra a petición del profesor :D
