### ISSUE TITLE
Archivos a entregar proyecto 1B

### ISSUE THREAD

**Issue by naviera** [IIC2343/Syllabus#29]
Hola, no me quedó claro el formato de entrega, por lo que entiendo piden una carpeta en el repo que contenga el .srcs, el .xpr, y el Basys3.xdc, y afuera de esa carpeta que esté el .bit, es eso correcto?
Saludos.

**Comment by jjaguillon** [comment]
Hola!

Si, imagina que tu proyecto se llama "MiProyecto", debes entregar los siguiente:

- MiProyecto.srcs (y todos los archivos contenidos)
- MiProyecto.xpr
- MiProyecto.bit
- Basys3.xdc

**Comment by naviera** [comment]
Perdona, entonces esas 4 cosas tienen que ir "sueltas" en el repo? La "carpeta con su proyecto de
Vivado" a la que se refieren en el enunciado entonces sería la .srcs?

**Comment by jjaguillon** [comment]
Si. Puede entregar una carpeta que separe lo de Vivado o no.

Se revisará que esté lo antes mencionado, independiente que esté en la carpeta raíz del repositorio o no
