### ISSUE TITLE
Ayuda T02 - Parte Programada 

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#29]
# Hola! 😃
En esta _issue_ les voy a comentar un poco lo que se espera que hagan en la tarea 2 los que les tocó la parte programada, además de anunciarles que ya subí los archivos de ejemplo que prometimos en el enunciado.

## Arquitectura de 8 bits
Lo primero es lo primero, a diferencia de los que tienen la parte de placa, en la parte programada utilizaremos una arquitectura de 8 bits, lo que significa que los valores que manejaremos irán desde 0x00 hasta 0xFF. En muchos casos, como los valores de los registros, estos sí tienen sentido que se _interpreten_ como números negativos, cuando corresponda. Sin embargo, pregúntense si para acceder a posiciones de la memoria de instrucciones o para manipular el _program counter_ esto tiene sentido. Esperamos que su programa responda correctamente a casos como estos.

Sobre el _program counter_ y el término del programa. Es cierto que, como mencionamos en el enunciado, si encuentran cuatro bytes consecutivos cuyo valor sea 0xFF, entonces es un indicador de que el programa ha terminado, pero, si el valor del _program counter_ es 0xFF y **debe avanzar**, entonces eso **también** implica que el programa ha terminado. Lo que no debe pasar es que tome el valor 0x100 o 0x00.

Por lo mismo, los tamaños de ambas memorias solo admiten 256 bytes de almacenamiento. Si un programa al compilarse acaba ocupando un espacio mayor, queda a su criterio el cómo lo manejan, pero no deben pasarse. La memoria de datos también se ve restringida a ese tamaño máximo.

## ISA y opcodes
Deben tener mucho cuidado de no confundirse de ISA, ya que no es la misma para la parte programada y la parte placa. Esto es simplemente porque una ISA más pequeña ya sirve para evaluar los contenidos que queremos.

Quizás alguien se pregunta por qué no usamos la arquitectura MIPS para esta tarea en general, y la respuesta corta es que es simplemente demasiado grande.

Los opcodes aparecen en hexadecimal y no en binario por la misma razón que se prefiere esta base en general, frente al binario: es mucho más fácil distinguir `0x2E` de `0x54` que `0b101110` de `0b110110` (y se usa hexadecimal y no decimal porque la transformación de binario a hexa y vice versa es directa, a diferencia de con la base 10).

## Instrucciones sin literal
Si una instrucción no tiene un literal, deben colocar el byte 0xFF como literal. Pueden reflexionar ¿por qué 0xFF y no 0x00? Ambas opciones son legítimas y se usan, pero que lo mediten un tiempo no les hará ningún mal. Es una simple sutileza, en nuestro caso.

## Archivos de ejemplo
En la carpeta `Tareas/T02/Ejemplos/` encontrarán cinco archivos:
- `ejemplo_binario.s`
- `ejemplo_codigo.s`
- `ejemplo_precompilado1.s`
- `ejemplo_precompilado2.s`
- `ejemplo_simulacion.txt`

El archivo `ejemplo_codigo.s` es un código de ejemplo, así serán los archivos que recibirá su assembler. Es importante que tengan en cuenta que **puede o no contener indentación, vía espacios o tabulaciones (`\t`)**.

Los archivos `ejemplo_precompilado1.s` y `ejemplo_precompilado2.s` están para mostrar un poco el proceso de compilación. En el primero vemos cómo se reemplazó la sección `DATA` por código que carga en memoria las variables a utilizar, luego aparece el `JMP` a `MAIN` y luego están los distintos bloques de código. Todos los nombres de labels y variables fueron reemplazados por sus direcciones de memoria correspondientes. Las direcciones de memoria de las labels siempre son números pares, ya que en `PC = 0` tenemos una instrucción y en `PC = 1` tenemos el literal que la acompaña (algo que deben considerar al calcular las direcciones de salto). En el segundo coloqué las transformaciones de cada línea a `opcode - literal`.

El archivo `ejemplo_binario.s` muestra cómo debe ser el archivo que retorne su assembler. El disassembler debe realizar el proceso inverso.

Finalmente, el archivo `ejemplo_simulacion.txt` lo subo para que puedan contar los caracteres más fácil.

## Consejos
Además de lo típico, de que modelen su programa antes de programar e inicien con tiempo, les comento:
- Pueden usar la librería `re` para usar expresiones regulares si lo prefieren, aunque no es nada indispensable.
- No es necesario que simulen la microarquitectura completa del computador básico.
- Para el formato de los textos, pueden usar str.format o f-strings, que son dos implementaciones de lo mismo.

#### Mucho éxito~ 💪, no duden preguntar vía issues si tienen alguna duda 🎵🕺.

**Comment by jmwielandt** [comment]
## Sobre representación de números enteros

En base 10 con notación del lenguaje natural, anteponemos el signo `menos` (`-`) para indicar que un número es negativo, en este caso es un poco lo mismo, pero se combina con el complemento a 2 de la siguiente forma:

Si el número en hexadecimal está entre `0b10000000` y `0b11111111`, incluyendo ambos extremos, entonces cuando tenga sentido deberá ser interpretado como número negativo y ser representado como su contraparte positiva, anteponiendo un signo `menos` (`-`), mientras que cuando no tenga sentido, deberá ser interpretado y denotado como un número positivo.

**Comment by Sforrego** [comment]
"Las direcciones de memoria de las labels siempre son números pares, ya que en PC = 0 tenemos una instrucción y en PC = 1 tenemos el literal que la acompaña (algo que deben considerar al calcular las direcciones de salto)."

Estoy un poco complicado con esto
usando el ejemplo dado:

0x26: INC B         0x2E 0xFF
    MOV (0x03),B    0x2A 0x03
    MOV A,0         0x02 0x00
    MOV (0x05),A    0x29 0x05
    MOV A,(0x04)    0x27 0x04
    JMP 0x60        0x1E 0x60
0x32: INC B         0x2E 0xFF
    MOV (0x03),B    0x2A 0x03
    MOV B,(0x05)    0x28 0x05
    INC B           0x2E 0xFF
    MOV A,1         0x02 0x01
    MOV (B),A       0x2D 0xFF
    MOV A,(0x04)    0x27 0x04
    MOV B,(0x03)    0x28 0x03
    JMP 0x60        0x1E 0x60
0x44: INC B         0x2E 0xFF

avanza en 6 de 26 a 32 con 6 comandos entre ambos, pero en  avanza 12 de 32 a 44 con solo 9 comandos entre estos, porque ocurre esto?

**Comment by jmwielandt** [comment]
Recuerda que `0xYY` es notación **hexadecimal**, donde `0x9 + 0x1 = 0xA`

En el segundo caso que comentas, entre paréntesis pongo las direcciones de cada _byte_.
![image](https://user-images.githubusercontent.com/37153467/55991521-7200d980-5c78-11e9-8676-9532b9f2a2b9.png)

**Comment by Sforrego** [comment]
jajajaj oops cierto cierto!
como coincidio que ninguno terminara en A->F se me olvido que estaba en hex

**Comment by Sforrego** [comment]
Gracias!

**Comment by Sforrego** [comment]
Seria demasiado hermoso si pudieran subrir uno o dos ejemplos mas para probar nuestros programas (sin necesidad de los precompilados).

**Comment by Arcoirisky** [comment]
@Sforrego Abre otra issue pidiendo los ejemplos O: 
Es más fácil y cómodo para todos tener varias Issues con distintas preguntas/peticiones que todas en un mismo hilo :D

**Comment by danyestay** [comment]
"El archivo ejemplo_codigo.s es un código de ejemplo, así serán los archivos que recibirá su assembler. Es importante que tengan en cuenta que **puede o no contener indentación, vía espacios o tabulaciones (\t)**. 

Estoy un poco confundido ¿A qué se refieren específicamente al decir sin ningún tipo de indentación? ¿Podrían dar un pequeño ejemplo?

**Comment by jmwielandt** [comment]
```assembly
LABEL1:
mov A,3 ;sin indentación

LABEL2:
    mov B,4 ;con indentación

LABEL3:
	add A,B ;indentando con un tab (\t)
```
En gran parte de los lenguajes de programación, las indentaciones son completamente opcionales pero una muy buena práctica ya que hace el código más legible.

**Comment by danyestay** [comment]
@jmwielandt perfecto! había entendido algo nada que ver jajaj gracias!
