### ISSUE TITLE
Entrega 2: Diseño de Opcodes

### ISSUE THREAD

**Issue by cjones27** [IIC2343/Syllabus#29]
Hola! 

Esperando que se encuentren bien, en nuestro grupo nos surgió la duda de como hacer opcodes eficientes. Esto debido a que en el taller se sugirió fuertemente hacer opcodes eficientes en esta entrega para evitar tener que rehacerlos en la próxima. También nos dijeron que hacer opcodes iterativos (es decir, del 0 hasta la operacion n) tampoco es tan bueno. Entonces la pregunta es cómo debe ser este diseño para que cumpla con los requerimientos? Hay algunas reglas, lógica o guidelines que podamos seguir? Y cuál es el objetivo del opcode también? Que sea legible por nosotros o que sea eficiente para el computador (o ambas)?

Gracias!

**Comment by frvalenzuela** [comment]
Hola @cjones27 !!

Son varias preguntas así que intentare responder todas en distintos puntos.

> cómo debe ser este diseño para que cumpla con los requerimientos? 

El único requerimiento que tiene que cumplir esta entrega es que envíe las señales correspondientes según las características de la instrucción. Dejando eso en claro, lo que viene a continuación *es recomendado*, no obligatorio, y **no es requisito aprenderlo o aplicarlo de la misma forma**:

Ahora bien, si queremos trabajar un opcode eficiente, que sea escalable **a futuro**, existen podemos visualizar tres opciones: 
- Cada bit de la palabra de control sea una señal (si quieren buscarlo en internet o en literatura lo pueden encontrar como **hardwired**)
- Agrupar conjuntos de bits con una semántica que luego se traduce en la propagación de señales (si quieren buscarlo en internet o en literatura lo pueden encontrar como **microcode**)
- Una opción híbrida entre ambas.

### Ejemplo
Digamos que nuestra palabra de control tiene 9 bits `"000000000"`, y queremos diseñar una palabra de control para **MOV A,B**.
**Primero preguntarnos: ¿qué queremos con esta instrucción?**
Lo que queremos con esta instrucción es almacenar lo que se encuentra en el registro B en A. 
 **Segundo preguntarnos: ¿qué señales están involucrada?**
Las señal de carga de A (para almacenar lo que esta en B), la señal de ambos selectores MUXA y MUXB (para darles los parametros 0 y B a la ALU) y finalmente la señal de operación de la ALU (para indicar que sume 0 y B, retorne B y esta sea lo que entre en el registro A para ser guardado).
 **Tercero transcribir la instrucción a nuestro opcode**

**DIseño Hardwired**
Si nosotros escogemos una configuración hardwired, entonces cada bit significará una señal
`"A B SA SB    ALU  `
`"0 0  00  00    000 "`
Aquí los bits dos bits menos significativos significaran los enableA y enableB y los menos significativos el selector de la ALU. **Pro:** Es fácil de implementar. **Contra:** Ocupo todos los bits, por lo que en instrucciones que ocupen más componentes **necesitaré más bits**.

**Diseño Microcode**
Si nosotros escogemos una configuración microcode, entonces cada bit significará tendrá una semántica: R significará que registro elijo, si es 0 es el registro A, 1 es el registro B. la señal SG significará selector general, donde 00 significa que el MUXA eligirá cero y MUXB elegirá  MUXB B. La ALU sigue de la misma forma que hardwired.
`"R SG ALU  `
`"0 00   000  000 "`
**Pro:** Tenemos más bits para futuras instrucciones. **Contra:** Requiere de más selectores y compuertas lógicas que modelen la semántica esperada, y la semántica dada puede no ser lo suficientemente general, como en el ejemplo (¿qué pasa si queremos implementar la instrucción MOV (Dir), A? **Respuesta**: necesitamos ocupar más bits y complejidad asociada.).

**Diseño Híbrido**
Para un diseño híbrido podemos tener la forma de manejar los registros de hardwired y la forma de trabajar los selectores será microcode quedando:
`"A B SG ALU  `
`"0 0  00  000  00 "`
**Pro:** Tenemos más bits para futuras instrucciones y no es tan complejo como microcode. **Contra:** Añade más complejidad que hardwired y no obtenemos una máxima optimalidad de bits.

Me alargue mucho en esta respuesta así que responderé en otro comentario las otras preguntas, pero espero que esto sirva un poco más para guiarlos en como diseñar una palabra de control.

Si algo del ejemplo o la explicación no se entiende no dudes en consultarme.

Saludos!

**Comment by frvalenzuela** [comment]
Respondiendo a las otras preguntas:

>  cuál es el objetivo del opcode también?

El objetivo es que el computador tenga una referencia a la instrucción a ejecutar, y esta pueda ser leída por la control unit para ejecutar las señales correspondientes a lo que debería hacer la instrucción.

Si queda alguna duda no dudes en consultarme.

Saludos!

**Comment by frvalenzuela** [comment]
Respondiendo a la última pregunta:

> Que sea legible por nosotros o que sea eficiente para el computador (o ambas)?

Nosotros no nos preocupamos por temas de eficiencia a nivel de opcodes. Todas las instrucciones deben tomar un ciclo de reloj, así que su tiempo será el mismo. Si para una instrucciones hay que pasar el opcode por compuertas lógicas, selectores y demás dentro de la control unit no hay mayor complicación. Así que si a eso te refieres con eficiencia no te preocupes realmente. Lo más importante es que funcione, si a eso quieren añadir legibilidad no debería haber problema.

Espero haber entendido bien tu pregunta, si no es así házmelo saber.

Saludos!

**Comment by quememo** [comment]
Por qué no querría usar opcodes iterativos (es decir, del 0 hasta la operacion n)?

**Comment by frvalenzuela** [comment]
Hola @quememo !

Porque eso significaría hacer un selector por cada instrucción, lo que no escala nada bien, y es propenso a muchos errores, y genera un nivel de complejidad en el circuito muy grande. La detección de errores se vuelve muy dificil, y para próximas entregas puede significar un mayor problema.

Saludos!
