### ISSUE TITLE
[T02 Programación] Tests

### ISSUE THREAD

**Issue by cilopez** [IIC2343/syllabus#29]
Existe alguna posibilidad de que nos suban test para probar nuestros programas, para así estar seguros de que estamos haciendolo bien en varios casos

**Comment by Geeermy** [comment]
¡Hola!

Uno de los objetivos de la tarea de programación es que ustedes sean capaces de elaborar sus propios _tests_ para comprobar que el funcionamiento de su programa es el correcto.

Probablemente subamos algunos de todas formas, pero cerca de la entrega. Por lo mismo, esperamos que **no dependan de estos** para que avancen con su tarea a buen ritmo.

¡Que estés muy bien! 😄
