### ISSUE TITLE
T06 HELP Nota cambiada D':

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#290]
Por casualidad ¿no hay un pequeño error en la hoja de cálculos correspondiente la T06?
Que se me ha cambiado la nota y estoy con un poquitito de pánico :'D
Era un 6,2 y ahora es un 2,2 ;---; En la sheet se ve que tengo un puntaje alto pero aún así tengo un 2,2 ;---; 

No sabía dónde más acudir pensando que hoy, lunes, se cierra el curso~
así que abro esta issue de emergancia ;--; Perdón si molesto ;---;

**Comment by Geeermy** [comment]
Ya te contesté el correo. 😅

**Comment by Arcoirisky** [comment]
esto fue en medio del pánico xD igual lov para todos <3
