### ISSUE TITLE
T01: Parte simulación: Número de rutas (argumentos) que recibe el programa

### ISSUE THREAD

**Issue by sfga** [IIC2343/syllabus#3]
Hola,

   En el enunciado (página 3) ponen lo siguiente: 

> el archivo a ejecutar debe recibir tres argumentos por línea de comando: el _path_ del archivo que describe el circuito, el _path_ del archivo que contiene los inputs y el _path_ del archivo que en el que se escribirá el resultado (en ese orden).

Sin embargo, en el ejemplo (página siguiente) colocan el contenido de los input y el circuito en un mismo archivo json:
![imagen](https://user-images.githubusercontent.com/20782942/54480402-ca25f680-4806-11e9-87d3-d3d912e95369.png)

Lo que haría pensar que se recibe una sola ruta con el archivo json que contiene la información del circuito y los inputs y no dos archivos json separados, como dice el enunciado.

¿Pueden confirmar la cantidad de archivos con las que debe trabajar el programa?

**Comment by jmwielandt** [comment]
Hola!
Efectivamente fue un __typo__, lo corregiremos pronto y resubiremos el enunciado en el syllabus.

Deberán recibir **dos** argumentos, el archivo de entrada y el de salida, tal como muestra la imagen.
