### ISSUE TITLE
[Programa]

### ISSUE THREAD

**Issue by daniellyonvald** [IIC2343/Syllabus#3]
Hola, 
No me quedo claro cómo ponderan las Interrogaciones y el Examen para la nota de Evaluaciones Escritas en el programa. 
Gracias

**Comment by jmwielandt** [comment]
Hola!
El examen vale lo mismo que una interrogación. El cálculo de la nota de Evaluaciones Escritas es el siguiente:

- Caso 1: no existen inasistencias y el examen es mayor que alguna de las dos interrogaciones: 
```
EE = (I1 + I2  - min(I1 + I2) + 2 * Ex) / 3
```

- Caso 2: no existen inasistencias y el examen es menor que ambas interrogaciones: 
```
EE = (I1 + I2 + Ex) / 3
```

- Caso 3: solamente existe una inasistencia **justificada** a una interrogación: la nota del examen reemplaza la interrogación a la que faltaste. Supongamos que es la I1, entonces:
```
EE = (Ex + I2 + Ex) / 3
```

- Caso 4: solamente existe una inasistencia a una interrogación, pero no está justificada, tienes un 1 en esa evaluación, el examen no la reemplaza y la nota de evaluaciones escritas se calcula:
```
EE = (I1 + I2 + Ex) / 3
```

- Caso 5: solamente existe una inasistencia **justificada** al examen (y fuiste a las interrogaciones), quedas con nota P y deberá ser actualizada a principios del primer semestre de 2020.

- Caso 6: existen a lo menos dos inasistencias a evaluaciones escritas (interrogaciones y/o examen): reprobación inmediata del curso. Sean estas justificadas o no.

Saludos!
