### ISSUE TITLE
Manejo de strings

### ISSUE THREAD

**Issue by BSamilla** [IIC2343/syllabus#3]
Hola!
Quería consultar por los comandos para trabajar con strings y como usarlos, por ejemplo como acceder a cada letra de la palabra.
Y saber también si es posible hacer CMP entre las letras o si existe un comando similar.

Saludos

**Comment by MainScientist** [comment]
Assembly es un lenguaje de muy bajo nivel (justo antes de trabajar en lenguaje de máquinas), por lo que es importante que comprendas que este lenguaje no posee manejo de strings.

Este es un lenguaje para trabajar directamente con la arquitectura del computador casi sin ningún tipo de abstracción, por lo que para entender bien como trabajar con strings debes tener en cuenta lo siguiente:

```
DATA:
mi_string "hola"
largo 4
CODE:
MOV A, (mi_string)
```

Primero, los strings son representados en tu computador como un arreglo de caracteres, y como el computador solo sabe trabajar con números, se creó una convención que a cada carácter (letra) le asigna un número. En este caso, nuestros interpretes representan los caracteres en formato [ASCII](https://www.asciitable.com/) (que es el formato más comúnmente usado para representar caracteres en forma numérica). Por lo que un string no es más que un arreglo de números en la memoria.

Segundo, en el código que te mostré al hacer `mi_string "hola"` le estamos diciendo al assembler que guarde en la variable `mi_string`, la posición al **primer carácter** del arreglo. Por lo que tu memoria y variables se verían así:
```
mi_string ---> 68 ('h')
               6F ('o')
               6C ('l')
               61 ('a')
largo -------> 4
```
Por lo que al hacer `MOV A, (mi_string)` estás escribiendo en el registro A el valor del carácter al que apunta `mi_string`. Es decir, estás escribiendo 68 en el registro A.

Tercero, debido a lo anterior, para acceder a un carácter que no sea el primero solo debes sumar, es decir, tienes `mi_string` cuyo valor apunta a la dirección del primer carácter. Si quieres obtener la dirección del segundo carácter debes sumarle 1 a `mi_string`.
```
MOV B, mi_string      // notar que al no usar paréntesis nos referimos a la dirección
                      // y no al valor que está en esa dirección
INC B                 // Le sumamos uno al valor de B
MOV A, (B)            // Con esto estamos diciendo que se escriba en A el valor que se 
                      // encuentra en la dirección a la que apunta B
```
Finalmente, como ves esto es un manejo a muy bajo nivel en donde todo se maneja de forma numérica, es por eso que es importante que a la hora de definir un arreglo tengas en alguna parte mencionado el largo de éste, ya que este valor no se almacena ni se define en ninguna parte, por lo tanto es necesario dejarlo explícito para que tú puedas en tu programa saber en qué dirección termina tu arreglo. Esto puede ser implementado de varias formas, en nuestro caso, optamos por usar una variable para que nos indique el largo de nuestro string, pero otra posible solución es usar un marcador especial para mencionar el fin del string. Como ves en la tabla, el carácter con valor `0` es el carácter `NULL`. Algunos lenguajes utilizan éste carácter para marcar el termino del string (es decir, en memoria `hola` se guardaría como `68 6F 6C 61 00` (los strings en C funcionan de esta forma).

Espero que con esto entiendas mejor cómo enfrentar la tarea.

**Comment by BSamilla** [comment]
Vale!
Te entendí perfectamente.
Gracias.

**Comment by Hernan4444** [comment]
Dejemos las issues abiertas un tiempo para que otros vean las respuestas 😄. Nosotros la cerramos después 👍.

**Comment by FranLucchini** [comment]
Todavía tienes esta duda? Voy a responder lo mejor que pueda:
No, que no tenga paréntesis significa que trae el la dirección de la variable. Por ejemplo, si `mi_string` se guardó en la dirección de memoria 2, ejecutar `MOV B, mi_string` va a guardar 2 en el registro B.

**Comment by IriSalazar** [comment]
Gracias!!
