### ISSUE TITLE
Parte Asignada T02

### ISSUE THREAD

**Issue by rafafdz** [IIC2343/syllabus#30]
Hola! Si no me llegó un mail diciéndome que se me asignó un compañero, debo asumir que se me tocó la parte programada? 
O tengo que esperar a que me llegue un mail que me lo diga explícitamente? 

Gracias!

**Comment by jmwielandt** [comment]
En el README del syllabus, está el link al excel donde están las asignaciones de tareas.

[https://docs.google.com/spreadsheets/d/1NtsaQ8NPKCwHGjVcmWh1gYNo54VxO2iLMI_BHWXwNpI/edit#gid=0](link)

**Comment by fabarros** [comment]
Hola, en el mail que nos enviaron dice lo siguiente: 
> Esta tarea es la primera donde se encontrarán con dos secciones. Una requiere trabajo de placa con un compañero asignado, mientras la otra seguirá siendo individual y programada.

Sin embargo por lo que veo en el Excel, no es que todos tengamos que hacer la mitad de la parte de placa y toda la parte programada, sino que algunos tendrán que hacer la parte programada y otros la parte de placa, correcto? Le creemos al excel o al mail? Si le tengo que creer al mail, cómo sé con quién me tocó?
Gracias.

**Comment by jmwielandt** [comment]
Hola!
El mail no fue lo suficientemente claro con eso, lo sentimos.
Efectivamente, la mitad de ustedes estará con la parte programada y la otra mitad con la parte de placa, es decir, manda el excel.
