### ISSUE TITLE
Error al correr simulación: "correct 'read/write/execute' permissions"

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2343/Syllabus#30]
Hola!

Estaba haciendo el tutorial para crear simulaciones y en la parte de correrla, me tira el siguiente error: 

![image](https://user-images.githubusercontent.com/26395403/64137073-ee30c080-cdc3-11e9-989b-3c7c7ffcad1e.png)

El proyecto lo tengo en mi escritorio por lo que creo que tengo los permisos necesarios. Busqué en internet y no encontré nada que me sirviera. Alguna sugerencia? 

Gracias!

**Comment by frvalenzuela** [comment]
Hola @federaladriz ! 

Me puedes decir en qué sistema operativo estás ejecutando Vivado ?

Saludos !

**Comment by fedetaladriz** [comment]
@frvalenzuela  Estoy corriendo ubuntu en una maquina virtual en mac

**Comment by frvalenzuela** [comment]
Hola!

Comento que la solución fue importar  instalar el extended pack de virtual box.

Saludos!
