### ISSUE TITLE
Uso de if/else en Entrega 2

### ISSUE THREAD

**Issue by bvallejo1** [IIC2343/Syllabus#30]
Hola, estoy haciendo los componentes de Pc y Status, y  en el taller dice que los hagamos según el componente Reg que nos entregaron, el cual usa los statements if/else cuando en el enunciado dice que están prohibidos.

Es válido usar los statements process en estos 2 componentes? o debemos encontrar alguna forma de hacerlos sin estos?

Gracias.

**Comment by frvalenzuela** [comment]
Hola @bvallejo1 !

Efectivamente, el componente Reg ocupa _process_. Sin embargo, esta **prohibido** que ustedes ocupen ese comando y ese tipo de condicionales. Para hacer esas entidades debería bastar usar el componente Reg como una (o varias) instancias, y el uso de señales para generar el comportamiento esperado.

Si queda alguna no dudes en consultar.

Saludos!
