### ISSUE TITLE
Como representar numeros negativos en hexadecimal

### ISSUE THREAD

**Issue by MrEarle** [IIC2343/syllabus#32]
En el enunciado de la parte programada dice 

> Todos los valores numericos seran enteros con signo.

Como esperan que representemos estos numeros? Complemento de 2 o simplemente poner un - (menos) al frente?

En la imágen de la parte de simulación muestra los números con un - al frente, pero eso cambia la forma de traducir entre assembly y hexadecimal.

![image](https://user-images.githubusercontent.com/30664457/55758386-9e241c80-5a24-11e9-8330-6c3ace8662df.png)

**Comment by jmwielandt** [comment]
Hola!
Te comento:
En el binario, con complemento a 2
En el código, con signo o sin según corresponda.
En el reporte, con signo o sin según corresponda.

Por ejemplo, si estás saltando a la dirección 0xF1, entonces el signo no tiene mucho sentido, dado que no tienes direcciones de memoria negativas. Pero si estas haciendo 
`ADD A,0xF1`, sí tiene sentido que 0xF1 sea considerado como un número negativo, se escriba con el signo -.

**Comment by MrEarle** [comment]
Pero si hago `ADD A,0xF1`, y lo estoy considerando "signed", entonces no
hay que poner el "-", ya que el código hexadecimal toma en cuenta si es
negativo o no (cómo en complemento de 2). En cambio, si lo tomo como
unsigned, pero debería ser negativo, el comando debería quedar `ADD
A,-0xF1`.

Por eso mi pregunta. No solo en el reporte, sino que también al traducir el
assembly a hexadecimal (con el assembler), los escribo con complemento de
dos (0xF1 es negativo y 0x01 es positivo) o con un "-" (0xF1 es positivo y
-0xF1 es negativo)?

**Comment by jmwielandt** [comment]
0xF1 considerado como signed es -0x0F

Entonces,
`ADD A,0xF1` debe ser transformado en `ADD A,-0x0F` (en hex) o `ADD A,-15` (en decimal).

Para el output de la simulación, entonces
`JMP 0xF1` tiene opcode `0x1E` y literal `0xF1`, mientras que `ADD A,0xF1` tiene como opcode `0x06` y literal `-0x15`.
El - 0xF1 no existe, pues el computador de la parte programada es de _8 bits_.

**Comment by MrEarle** [comment]
Ahi me quedo claro, gracias!

**Comment by jmwielandt** [comment]
@MrEarle exactamente eso, es para que el reporte sea más fácil de leer~
