### ISSUE TITLE
Duda sobre Sa1

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2343/Syllabus#32]
Hola, no estoy entendiendo que instruccion del assembler esta asociada a obtener el valor 1 en el Mux A, ya que agregamos la señal Sa1 para poder obtener un 1 en el Mux A y en ninguna parte aparece la instruccion asociada a ese 1

**Comment by frvalenzuela** [comment]
Hola @lfuenzalida2 ! 

Para la instrucción INC B es útil. 

Saludos !

**Comment by lfuenzalida2** [comment]
Gracias!
