### ISSUE TITLE
Pregunta 2 Teórica

### ISSUE THREAD

**Issue by augustoas** [IIC2343/syllabus#32]
Hola ! 
En la pregunta 2.b:  Al comparar números enteros se asume que los bits a comparar tienen bit de signo ?
Gracias !

**Comment by Geeermy** [comment]
¡Hola!

Por favor, hayas resuelto tu duda o no, **no cierres las _issues_** ya que las respuestas a las preguntas que hacen pueden ser de utilidad para más alumnos.

Respondiendo tu pregunta: Al estar trabajando con la representación entera, si seguimos los pasos del complemento a 2 para obtener el inverso aditivo de un número, podemos ver que el bit de signo surge de forma natural.

TL;DR: Sí.

¡Mucho éxito! 😀
