### ISSUE TITLE
SUB no funciona correctamente

### ISSUE THREAD

**Issue by gebalassa** [IIC2343/syllabus#32]
¡Hola! Estaba aprendiendo a usar Assembly cuando noté un detalle donde desconozco si el que se equivoca soy yo o el programa.

```
DATA:
var1 4

CODE:
MOV B, (var1)
SUB B, 4
```

El `SUB B,` me debiese tirar '0' en el registro B pero me tira 'FFFC'.

--------
Luego, con el código:
```
DATA:
var1 5
var2 4

CODE:
MOV A,(var1)
MOV B,(var2)
SUB B,4
```
me tira '1', cuando me debiese tirar '0'.

**Comment by MainScientist** [comment]
Si miras los apuntes la isntrucción `SUB B, lit` no está soportada, sin embargo, en el assembler si está. La instrucción hace `B = A - lit`. Como puedes notar, la arquitectura del computador básico no permite que sea de otra forma.

**Comment by MainScientist** [comment]
El caso `SUB A, lit` se encuentra en los apuntes del curso.

**Comment by gebalassa** [comment]
Oka thx.
