### ISSUE TITLE
[Vivado] Wavedata error en Ubuntu con Parallels en Mac

### ISSUE THREAD

**Issue by fhohlberg** [IIC2343/Syllabus#32]
![Captura de pantalla 2019-09-04 a la(s) 16 31 28](https://user-images.githubusercontent.com/42193204/64289056-826c6600-cf31-11e9-8cdb-d27bd5e43c5e.png)
Hola! Tratando de compilar en Vivado siguiendo las instrucciones del documento "Tutorial___Compilar_en_Vivado.pdf" me aparece un error de Wavedata.. lo mismo me pasa al tratar de simular. Estoy usando Ubuntu con Parallels en Mac.. ¿Cómo puedo arreglar esto?

#30

**Comment by frvalenzuela** [comment]
Hola @fhohlberg !

Puedes mandarme una captura de /home de Ubuntu con mostrando las carpetas y archivos ocultos por favor?

Saludos!

**Comment by fhohlberg** [comment]
![Captura de pantalla 2019-09-05 a la(s) 10 58 17](https://user-images.githubusercontent.com/42193204/64353678-2571be00-cfcc-11e9-8fa8-d0bf2c4b9056.png)

**Comment by frvalenzuela** [comment]
Hola @fhohlberg !

Prueba eliminando la protección de la carpeta .Xilinx (ese candando de la carpeta)

Saludos!
