### ISSUE TITLE
Formato circuitos de tamaño n

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#33]
Hola, con lógica proposicional podemos usar expresiones de largo variable (con los equivalentes para la conjunción y disyunción de la sumatoria), pero, ¿cómo debo expresar esto en forma de circuitos?
[Parte teórica]

**Comment by Geeermy** [comment]
¡Hola!

Perdón la demora. Recuerda que puedes definir entradas y salidas de largo _n_ (o "buses" de _n_ bits) con respecto a las compuertas. Por ejemplo, puedes revisar las operaciones lógicas _bitwise_ en las _slides_ de la clase de operaciones aritméticas y lógicas, que son un claro ejemplo de esto y que permite escalar a circuitos de "mayor largo".

Espero que tu duda haya ido por ese lado. Si no, sigue comentando aquí sin problemas. 👌 

¡Mucho éxito! 😁

**Comment by Geeermy** [comment]
1. En ese caso, puedes definir una secuencia de compuertas AND "interconectadas" de forma que la salida final sea el resultado que buscas (_i.e._ que conectes todas las compuertas de forma que la última obtenga el resultado de aplicar la operación lógica sobre un conjunto de valores). Si diseñas eso puedes después generalizarlo en un nuevo componente y utilizarlo donde sea, pero tiene que estar bien construido y detallado. Obviamente no puedo entrar en más detalles porque sería empezar a desarrollar la tarea. 😅

2. Te confirmo porque lo estamos evaluando, pero por ahora piensa en cómo hacerlo con compuertas, ya que no es necesario usar relés.

¡Ánimo! 😁
