### ISSUE TITLE
Dudas sobre ROM y Control Unit

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2343/Syllabus#33]
Hola, tengo un par de dudas sobre la entrega 2, especificamente que hace la ROM y la Control Unit, las preguntas son:

1)  La ROM debe entregar como DataOut un vector de largo 33 en donde los 16 bits mas significativos son el literal y los bits restantes (17 bits) son el Opcode para la Control Unit? Porque nosotros entendimos que el DataOut contenía el Literal (16 bits), un Opcode de 6 bits (ya que caben todas las instrucciones que necesitamos) y ademas 11 señales de control (y magicamente esto calza perfectamente con los numeros)

2)  La DATA de los programas que debemos ejecutar se entregan directamente desde la ROM? o deben pasar por la Control Unit para que esta sea enviada a la RAM?

**Comment by frvalenzuela** [comment]
Hola @lfuenzalida2 !

1) Si, los 17 bits restantes son de Opcode. El opcode lo diseñan ustedes (más información revisar la issue #29 . El patron de cantidad señales y tamaño de opcode visto en clases es coincidencia, pues en próximas entregas el número de señales aumenta.

2) Las variables de la parte DATA deben ser agregadas a la RAM por instrucción desde la ROM. Para más información recomiendo cargar un programa en el emulador con DATA y ver como se ejecuta.

Saludos!
