### ISSUE TITLE
Entrega 1C - Uso de modulos 

### ISSUE THREAD

**Issue by lucasalamos** [IIC2343/Syllabus#33]
Hola. Con respecto a los modulos entregados, solo nos debemos preocupar de conectar la entrada de la placa clk con la entrada clk del modulo? o tambien debemos preocuparnos de darle los correctos input a los modulos?

**Comment by CristobalHV** [comment]
Hola @lucasalamos !

Debes preocuparte de conectar todas las entradas necesarias para que tu entrega funcione. En el caso de la entrada clk que mencionas, en el enunciado de la tarea se explica que esta es la entrada del clock, necesaria para que el Display de la placa funcione correctamente.

Disculpa la tardanza y éxito con la entrega :)
