### ISSUE TITLE
Operacion de CMP

### ISSUE THREAD

**Issue by MrEarle** [IIC2343/syllabus#33]
Hola,

En la ISA de la parte programada se muestra la operacion de CMP, pero no donde se guarda.

La operacion `CMP A,B` hace `A=A-B`, y `CMP A,Lit` hace `A=A-Lit`? O acaso los resultados no se guardan?

**Comment by Arcoirisky** [comment]
Hola, estás en lo correcto. No se guardan.

CMP es una instrucción para comparar. Si A y B son binarios iguales entonces su resta es 0’b 

Se usan más que nada para los JMP (Así comprueban las condiciones de salto) No todo es tan mágico y automático como antes u-u

**Comment by jmwielandt** [comment]
Complementando la respuesta de Jessica, puedes ver en los apuntes del curso, el pdf de saltos y subrutinas, en el punto 3 explica todo lo necesario para entender el funcionamiento de los saltos y su implementación para la tarea. Lo interesante de todo es que no necesitas una instrucción CMP para poder condicionar un salto, dado que el registro Status que guarda los valores Z, N, C y V, para cada operación que pase por la ALU :not-maigc:
