### ISSUE TITLE
[Entrega 1C] Uso de módulos extra

### ISSUE THREAD

**Issue by vjaguilera** [IIC2343/Syllabus#34]
Hola! Me podrían explicar como podemos hacer uso de los módulos extras que nos proporcionaron? Estoy muy perdido en como importar o como llamar a la entidades entregándoles valores y que estas nos retornen otros valores, y específicamente como hacer funcionar el display de 7 segmentos :( Por favor!

Muchas gracias.

**Comment by frvalenzuela** [comment]
Hola @vjaguilera !

Hoy en la tarde se subirá un tutorial que explicará el como llamar a otras entidades. Cuando sea subido te informaré por este medio.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @vjaguilera !

Lamentando la demorá, pero ya está arriba el tutorial que describe lo visto en la última ayudantía del lunes pasado.

Saludos!

**Comment by vjaguilera** [comment]
@frvalenzuela muchas gracias por el aviso!
