### ISSUE TITLE
[T02 Programación] Sobre el circuito

### ISSUE THREAD

**Issue by acrojas2** [IIC2343/syllabus#34]
Hola tengo las siguientes dudas:

1. Supongamos que en el circuito de ejemplo que aparece en el enunciado el resultado del  "xor1" es decir "out1" y el resultado del "and1" pasan a una siguiente compuerta y supongamos que es "exor"(da igual cual, lo que me interesa es saber como vendra en el archivo de input) en el json se agregaria esto?: {"from":"out1", "to": "exor1"}, {"from":"out2", "to": "exor1"}, {"from":"exor1", "to": "out3"} o los "out{i}" pasan a ser "input{j}".

2. Puedo asumir que el archivo de input siempre tendrá un circuito que tenga sentido? ,es decir, nunca va a pasar que una compuerta va a recibir más de 2 input para el caso de "and", "or", "exor" y las compuertas  "not"  nunca recibirán mas de un "input".

Saludos!

**Comment by nivek0o0** [comment]
Hola,
1. ninguna de las dos. En el json se agregaría `{"from":"xor1", "to": "exor1"}, {"from":"and1", "to": "exor1"}, {"from":"exor1", "to": "out1"}`. Puedes pensar que cada uno de estos diccionarios representa un cable del circuito, los que fluyen entre entidades (compuertas, entradas o salidas).

2. Sí.
