### ISSUE TITLE
Explicación Recursion Factorial

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#34]
Viendo las diapositivas, no me queda claro como es la vuelta (hacia atrás) de la funcion factorial.

int factorial(int n):
   if n < 1:
      return 1
   else:
      return n*factorial(n–1)

Dada la naturaleza recursiva de la función, ahora también es necesario guardar en el stack los valores de los registros $a0 y $ra, para poder restaurarlos al volver a la llamada anterior:
factorial:
   addi  $sp, $sp, –8
   sw    $ra, 4($sp)
   sw    $a0, 0($sp)
 Luego, comparamos n con 1, y vamos al label L1 si n ≥ 1: slti $t0, $a0, 1
   beq   $t0, $zero, L1
Si n < 1, factorial devuelve 1, a través del registro $v0:
   addi  $v0, $zero, 1
   addi  $sp, $sp, 8
   jr    $ra
Si n ≥ 1, n es decrementado y factorial es llamado recursivamente:
L1:
   addi  $a0, $a0, –1
   jal   factorial
 De ahí, empezamos a “salir” de (esta llamada de) la función:
   lw    $a0, 0($sp)
   lw    $ra, 4($sp)
   addi  $sp, $sp, 8
... ponemos en $v0 el producto de $a0 y $v0: mul $v0, $a0, $v0
... y finalmente, factorial salta nuevamente a la dirección de retorno:
jr $ra

Si me pueden ayudar con esto porfavor! gracias! (Esto es lo que sale en los apuntes de clases)

**Comment by NicolasAguirre** [comment]
mistery :
--
beq $a0, $zero, final addi $sp , $sp , −8
sw $ra, 0($sp) sw $a0 , 4($sp)
addi $a0 , $a0 , −1 jal mistery
lw $ra, 0($sp) lw $a0, 4($sp)
addi $sp, $sp, 8 mul $v0 , $v0 , $a0
jr $ra final :
li $v0,1 jr $ra

Vinedo la ayudantia cache q estaba el mismo ejercios, sin embargo no cacho cuando termina!! si me podrian ayudar seria genial, gracias!

**Comment by MrEarle** [comment]
Si te fijas, la seccion `final` corresponde al caso base (cuando `$a0 == 0` entonces `return 1`).

Luego, en el final de la seccion `mystery` se empieza a salir de los llamados recursivos, hasta que, en el llamado original, se vuelve al codigo principal (medianta el `jr $ra`)

**Comment by Panckx** [comment]
Hola! Partamos por ver la explicación línea por línea del código:

```mips
mistery:
    beq  $a0, $zero, final  # Si el primer parámetro de la subrutina es == 0, ir al final
    addi $sp, $sp, -8       # Guardar espacio en el stack para la subrutina (2 registros)
    sw   $ra, 4($sp)        # Guardar dirección de la llamada anterior
    sw   $a0, 0($sp)        # Guardar el valor del primer parámetro de la subrutina
    addi $a0, $a0, -1       # Restarle 1 al primer parámetro de la subrutina
    jal  mistery            # Llamada recursiva (así es baby)
    lw   $a0, 0($sp)        # Cargar el valor del primer parámetro de esta llamada de la subrutina
    lw   $ra, 4($sp)        # Cargar el valor de la dirección de la llamada anterior a la actual
    addi $sp, $sp, 8        # Devolver espacio en el stack usado por la subrutina
    mul  $v0, $v0, $a0      # Multiplicar v0 por el valor del primer parámetro
    jr   $ra                # Volver
final:
    li   $v0, 1             # v0 = 1
    jr   $ra                # Volver
```

Para comprender la manera en que el código funciona, hay que comprender primero cómo funciona el llamado recursivo de subrutinas. Imaginemos que se llama una vez a `mistery` y que ésta se llama recursivamente a sí misma solamente 1 vez. Básicamente, en la línea que dice `jal mistery` se comenzará a ejecutar una instancia nueva de la misma subrutina. Una vez que la segunda instancia de la subrutina acabe (por ahora imaginemos que mágicamente acaba), la primera subrutina continuará ejecutándose desde la línea siguiente a `jal mistery`, es decir, desde `lw   $a0, 0($sp)`. después de ésto se ejecutarán algunos comandos para finalmente llegar a la línea `jr   $ra` de la subrutina `mistery`, que terminará la instancia de la función. Una vez comprendida la forma en que termina una subrutina que se llama recursivamente una sola vez, estás listo para comprender la subrutina de manera general.

Pongámonos en el caso de que se quiera calcular el factorial de cero. El registro `$a0` contendrá el valor cero. La primera línea de `mistery` determinará que `$a0 == $zero` y hará **un salto** hacia el label `final`. Ésto es **muy** importante, ya que cuando uno utiliza el comando `jal`, automáticamente se almacena en el registro `$ra` la posición siguiente a la última llamada a `jal`. Dado que la última vez que se usó `jal` fue para llamar a la subrutina `mistery`, cualquier `jr $ra` hará que se ejecute la línea siguiente a la línea en que se llamó la subrutina. Por lo mismo, hacer un salto hacia el label en vez de llamarlo como subrutina permite que la línea `jr $ra` termine con la subrutina `mistery` y se vuelva al código principal.

Ahora, imaginemos que `$a0` vale 1. No se hará un _branching_ condicional debido a que `1 != 0` y se guardará el valor de `$ra` en el _stack_ y también el valor de `a0`, debido a que **ahora si** vamos a llamar una subrutina con `jal` y no queremos perder la referencia de dónde tenemos que volver cuando todas las subrutinas se acaben! Una vez llamada la segunda subrutina, ocurrirá todo lo que discutimos en el párrafo anterior, excepto que esta vez, `jr $ra` apuntará hacia la línea siguiente de la primera subrutina en que se llamó a la segunda (porque ahí fue nuesta última llamada a `jal`). Una vez llegado aquí, se cargará el valor anterior de `$ra` y de `a0` desde el stack para poder multiplicar el resultado de la subrutina recursivamente llamada por el valor de `a0` de ésta subrutina y para poder recordar dónde debemos devolvernos al hacer `jr`. Por último, se ejecutará `jr $ra`, que nos devolverá al código principal donde originalmente se llamó a la subrutina.

Para un `$a0` cualquiera >= 1 se cumple lo mismo! El caso base es cuando `$a0` es 0, y el resto de los casos son todos parecidos!

Espero que haya quedado un poco más claro el funcionamiento de esta subrutina en particular. En cualquier otro caso estamos aquí para seguir aclarando tus dudas!

**Comment by NicolasAguirre** [comment]
@MrEarle perdon por no responder, pero gracias por la respuesta! @Panckx graacias!! lo entendi dpes (para el ctrl), pero muchas grcias por la respueta asi se  me aclara mucho más!
