### ISSUE TITLE
Tabla Operación/Control Unit

### ISSUE THREAD

**Issue by nbnavarro** [IIC2343/Syllabus#34]
Hola, 

Para la entrega 2 hay alguna tabla donde estén los cables que deben estar en 0 o 1 dependiendo de cada operación? o es un análisis que debemos hacer nosotros? (o no sé si estoy muy perdido y es algo innecesario la verdad)
Tengo la duda porque siento que son muchas operaciones y estaríamos mucho rato en eso.

Gracias de antemano

**Comment by frvalenzuela** [comment]
Hola @nbnavarro !

Hay una gran tabla de señales en los apuntes, específicamente en el capítulo 5.5 que les ayuda con ese trabajo.

Cualquier duda no dudes en consultar

Saludos!
