### ISSUE TITLE
Entrega 2: INC A

### ISSUE THREAD

**Issue by cjones27** [IIC2343/Syllabus#35]
Hola! 

Una pregunta, en el enunciado sale hacer un `INC(A)`, que significa incrementar el valor del registro A en 1. Hacer el `INC(B)` resulta facil porque tenemos el valor 1 en el mux de A, sin embargo en este caso no lo tenemos. Para poder hacer esto nuestro assembler tendría que hacer el trabajo de dividir la acción en varias sub acciones o hacer que el literal se transforme automaticamente en 1. Un problema parecido ocurre con el `DEC(A)`.

Es esto correcto? Cómo deberiámos tratar estos casos?

**Comment by frvalenzuela** [comment]
Hola @cjones27 !

Este es un claro ejemplo de agregar instrucciones al computador básico. Siempre hay dos opciones para este tipo de casos, traducirla en una o más instrucciones que cumplan el objetivo de la instrucción (en caso de ser más de una instrucción esto tardaría más ciclos) o modificar el computador básico para que soporte la instrucción (como el cambiar el mux de B para que si tenga el 1).
En el caso de proyecto no deben cambiar la arquitectura del computador básico, y tu aproximación de usar un literal 1 es bastante acertada.

Si queda alguna duda no dudes en consultar.

Saludos!
