### ISSUE TITLE
[Tarea 2] Parte teorica

### ISSUE THREAD

**Issue by haarenas** [IIC2343/syllabus#35]
Es posible utilzar mapas de Karnaugh para la parte teorica? (no se si se ve en el curso)

Saludos

**Comment by Geeermy** [comment]
¡Hola!

Si bien no es parte de los contenidos del curso, sí puedes hacer uso de ellos. No obstante, **debes explicar en qué consisten y mostrar el proceso en el desarrollo de la tarea.**

¡Éxito! 🐵

**Comment by haarenas** [comment]
Perfecto, muchas gracias.
