### ISSUE TITLE
Entrega 1C- Diferencia entre datos en simulación y placa.

### ISSUE THREAD

**Issue by rnahum00** [IIC2343/Syllabus#35]
Al probar el programa en la simulación y en la placa se encienden leds distintos con los mismos inputs. En la placa se enciende un led(y reemplaza el valor de otro led) que en la simulacion aparece como "U" o no inicializado para cualquier valor(ya que es un led que no se usa nunca).
Al comienzo habia dejado este led comentado ya que no lo usaba pero aun asi se encendia, por lo que intente descomentarlo y asignarle un valor pero aun asi no funciona.

**Comment by frvalenzuela** [comment]
Hola @rnahum00 !

Podrías dar un ejemplo de tu situación para entender mejor el problema? quede algo confudido con tu explicación.

De cualquier forma, recomendaría mucho revisar las conexiones que describes, puede que sea un problema de que conectaras alguna señal de forma de que de un comportamiento que no se espera.

Quedo atento a tu respuesta.

Saludos!
