### ISSUE TITLE
[Tarea 2] Duda formato de inputs

### ISSUE THREAD

**Issue by CmPoblete** [IIC2343/syllabus#36]
Hola, como nos van a hacer el formato del json cuando el mismo input entra a las dos terminales de entrada de una puerta? será así: {from: input1 to: or1} o lo mostrarán duplicado: [{from: input1 to: or1}, {from: input 1 to: or1}]?
y también si van a haber circuitos mas complejos como que de un or entre a un xor?

**Comment by Geeermy** [comment]
¡Hola!

Se debe ver duplicado, será más fácil verlo de esa forma.

¡Éxito! 🦁

**Comment by jheysen** [comment]
Sobre la última parte de la pregunta, tu programa debe soportar circuitos arbitrarios dentro de las restricciones indicadas.
Saludos.
