### ISSUE TITLE
Errores comunes, qué evitar y qué usar en el Control 2

### ISSUE THREAD

**Issue by daleal** [IIC2343/syllabus#36]
# Errores comunes, qué evitar y qué usar en el Control 2

Hola a todos! Disculpen la hora! Después de revisar los controles 1 y algunas dudas que me hicieron algunos compañeros, compilé una lista con los errores típicos que encontré y con uno que otro tip que podría resultarles útil. Voy a tocar 3 temas: guardado de palabras y bytes en memoria (el más recurrente del control 1), entrega de argumentos y retorno de valores en una subrutina, y guardado de registros S y stack. Empecemos!

## Guardado de palabras y bytes en memoria

Cada palabra está compuesta de 4 bytes (o sea, 32 bits). Como sabemos, la memoria en MIPS está indexada según bytes. Esto quiere decir que Mem[0] es el primer byte de la memoria, Mem[1] es el segundo y así. Pero resulta que la mayoría de las veces se quiere guardar **una palabra** en memoria y terminan sobreescribiendo las anteriores! Como las palabras son de 4 bytes, deben desfasarse de a 4 y no de a 1. Veamos un ejemplo de cómo guardar algunas palabras en la memoria!

Supongamos que tenemos que A<sub>3</sub>, A<sub>2</sub>, A<sub>1</sub>, A<sub>0</sub>, B<sub>3</sub>, B<sub>2</sub>, B<sub>1</sub>, B<sub>0</sub> representan un byte de información cada uno. Esto quiere decir que:

**A<sub>3</sub>A<sub>2</sub>A<sub>1</sub>A<sub>0</sub>** es una palabra

**B<sub>3</sub>B<sub>2</sub>B<sub>1</sub>B<sub>0</sub>** es una palabra

Por último, supongamos que el registro `$s0` vale 0, el registro `$s1` tiene almacenada la palabra **A<sub>3</sub>A<sub>2</sub>A<sub>1</sub>A<sub>0</sub>**, el registro `$s2` tiene almacenada la palabra **B<sub>3</sub>B<sub>2</sub>B<sub>1</sub>B<sub>0</sub>**, el registro `$s3` tiene almacenada la palabra **A<sub>1</sub>A<sub>0</sub>B<sub>1</sub>B<sub>0</sub>** y el registro `$s4` tiene almacenada la palabra **000B<sub>0</sub>** (cada 0 siendo un byte de ceros).

Tenemos nuestra memoria vacía y la vamos llenando. La secuencia será la siguiente:

![mem_0](https://user-images.githubusercontent.com/37158127/55851550-1bd05100-5b27-11e9-8576-6f5ea553793e.jpg)

```mips
sw $s1, 0($s0)
```

![mem_1](https://user-images.githubusercontent.com/37158127/55851582-46220e80-5b27-11e9-8376-73db8a383a49.jpg)

```mips
sw $s1, 0($s0)
sw $s2, 4($s0)
```

![mem_2](https://user-images.githubusercontent.com/37158127/55851586-47533b80-5b27-11e9-9fd5-9fd58b93ed30.jpg)

```mips
sw $s1, 0($s0)
sw $s2, 4($s0)
sb $s4, 8($s0)
```

![mem_3](https://user-images.githubusercontent.com/37158127/55851591-491cff00-5b27-11e9-9b0d-f6ce378bf925.jpg)

Si se fijan, solamente ocupamos 1 byte de la memoria! Finalmente:

```mips
sw $s1, 0($s0)
sw $s2, 4($s0)
sb $s4, 8($s0)
sw $s3, 9($s0)
```

![mem_4](https://user-images.githubusercontent.com/37158127/55851594-4a4e2c00-5b27-11e9-91fb-eec2f13dad0d.jpg)

## Entrega de argumentos y retorno de valores en una subrutina

Para entregar parámetros a una subrutina, utilizamos los registros `$a0`, `$a1`, `$a2`, `$a3`. Para retornar valores de una subrutina, utilizamos los registros `$v0`, `$v1`. Por ejemplo, si quisiéramos transcribir el siguiente script de Python a MIPS:

```python
def suma(a, b):
    return a + b

final = suma(3, 7) # final = 10
```

EL código de MIPS sería:

```mips
suma:
    add $v0, $a0, $a1
    jr $ra

addi $a0, $zero, 3   # a0 = 3
addi $a1, $zero, 7   # a1 = 7
jal  suma            # v0 = a0 + a1 = 10
add  $t0, $zero, $v0 # t0 = v0 = 10
```

## Guardado de registros s y stack

Supongamos que tenemos el siguiente código en Python:

```python
def suma_inter(a, b):
    c = a + b
    return c

c = 143
final = suma_inter(3, 7) # final = 10, c = 143
```

Si se fijan bien, a pesar de que usamos el valor de `c` en la función, éste mantuvo su valor externo. Qué pasaría si hacemos lo mismo en MIPS?

```mips
suma_intermedia:
    add $s0, $a0, $a1   # Cambia el valor de s0
    add $v0, $s0, $zero

addi $s0, $zero, 143 # s0 = 143
addi $a0, $zero, 3   # a0 = 3
addi $a1, $zero, 7   # a1 = 7
jal  suma_intermedia # v0 = 10
add  $t0, $zero, $v0 # t0 = v0 = 10; s0 = 10!
```

`s0` cambió de valor dentro de la subrutina pero antes de terminarla no volvió a su valor original! Es por esto que utilizamos el _stack_ para almacenar los valores de los registros `s` que modificamos en la subrutina.

Como los registros almacenan 32 bits (una palabra completa), necesitamos 4 espacios en la memoria para almacenar cada registro que usemos. Como el _stack_ se usa de abajo hacia arriba, lo que hacemos es que tenemos un **Stack Poiner** o **SP** que apunta a la dirección de más abajo desocupada y, para almacenar espacio para una subrutina, realmente lo que hacemos es cambiar la posición del **Stack Pointer** a una posición de más arriba en la memoria para guardar los valores de los registros hacia abajo. Un ejemplo!

Imaginemos que el **SP** se encuentra en la dirección 255 (última en una memoria de 1 byte de espacio para indexación).

```mips
suma_intermedia:
    addi $sp, $sp, -8    # Cambiamos el valor de sp de 255 a 247
    sw   $s0, 4($sp)     # Guardar s0 en Mem[247 + 4] y los 3 espacios siguientes
    sw   $s1, 0($sp)     # Guardar s1 en Mem[247 + 0] y los 3 espacios siguientes
    add  $s0, $a0, $a1   # s0 = a0 + a1
    add  $s1, $a2, $a3   # s1 = a2 + a3
    sub  $v0, $s0, $s1   # v0 = s0 - s1
    lw   $s1, 0($sp)     # Cargar el valor de s1 de fuera de la subrutina
    lw   $s0, 4($sp)     # Cargar el valor de s0 de fuera de la subrutina
    addi $sp, $sp, 8     # Devolver el Stack Pointer a 255

addi $s0, $zero, 143 # s0 = 143
addi $a0, $zero, 3   # a0 = 3
addi $a1, $zero, 7   # a1 = 7
addi $a2, $zero, 1   # a2 = 1
addi $a3, $zero, 4   # a3 = 4
jal  suma_intermedia # v0 = 10 - 5 = 5
add  $t0, $zero, $v0 # t0 = v0 = 5; s0 = 143!
```

En esta subrutina se guardaron los valores de s0 y s1 antes de cambiarlos y antes de terminarse la subrutina se volvieron a cambiar! Ésto nos permite tener una suerte de _namespace_ que se acaba junto con la subrutina.

## Conclusión

Espero que esta issue les sirva, incluso si no la alcanzan a ver antes del control debido a la hora, para aprender sobre cómo operar con subrutinas y utilizando la memoria, específicamente el stack, en MIPS. Mucho éxito mañana a los que siguen estudiando a esta hora, a los que ya se durmieron (me gustaría pensar que para recargar fuerzas) y a los que no alcancen a leer esto antes del control! Les tengo mucha fé y creo que les va a ir muy bien! :heart:

**Comment by fgbruna** [comment]
@Panckx me queda perfectamente claro el que tengamos que guardar los valores de los registros $s en el stack antes de hacer cualquier cosa con ellos en las subrutinas.Mi duda es:
Por qué siempre guardas solo $s0 y $s1?, a priori no deberías guardarlos todos?
Gracias de antemano!

**Comment by Panckx** [comment]
Lo que pasa es que todas las subrutinas que he mostrado en que se alteran registros s, se alteran solamente s0 y s1, pero debes guardar todos ls registros s que altered dentro de la subrutina. No tiene sentido guardarlos todos cada vez porque no vas a cambiar su valor, entonces solo te haría perder memoria.

**Comment by fgbruna** [comment]
Entiendo, gracias!

**Comment by jmwielandt** [comment]
[Lista de registros existentes en MIPS](http://wikitronica.labc.usb.ve/index.php/Registros_del_camino_de_datos_del_Mips)
Les dejo esto, para que lo tengan presente por si no lo han visto antes. Perdón lo tarde, pero es importante. En el control 1 encontré varios que usaban registros inexistentes, como `$s20`.
