### ISSUE TITLE
Entrega 1C - Resultado displays restantes

### ISSUE THREAD

**Issue by csolguin** [IIC2343/Syllabus#36]
Estimado,
Si bien en el enunciado aparece que "... resultado en base decimal debe quedar representado en los dos display de 7-segmentos.", ¿Es posible que los displays restantes queden en "0" y no "apagados"?
De antemano muchas gracias.

**Comment by frvalenzuela** [comment]
Hola @csolguin !

Si, no hay problema con lo que mencionas.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @csolguin !

Favor no cerrar las issues, pueden servir a otra persona. Por la misma razón edite el titulo de la issue.

Saludos!
