### ISSUE TITLE
Duda instrucciones Assembly

### ISSUE THREAD

**Issue by stmorales** [IIC2343/Syllabus#36]
Hola! 

Las instrucciones en Assembly me dejaron un poco confundido. Esto es porque en este caso, tenemos la DATA que es a = E5h, b = B3h y bits = 0b. Luego en el code, nos dicen MOV A, ( a), por lo que he entendido de las clases y se las instrucciones, A se refiere al registro donde guardaremos el segundo valor y (a) es este segundo valor que se encuentra en la posición E5h de nuestra RAM. Por lo tanto la operación sería la siguiente:

RegA = Mem[E5h]

Sin embargo, en los comentarios de esta operación dice que la operación es RegA =  5. Por lo que me hace deducir que la data se guarda en la posición del valor de esta.

Pero luego paso a la siguiente instrucción, y encuentro que me dicen AND A, ( 1d ), y en los comentarios dice que se corresponde a Reg A = RegA & b. 

Me confunde súper harto las distintas maneras con las que ponen las instrucciones, por lo que les agradecería mucho qué se debe hacer en cada caso.

![image](https://user-images.githubusercontent.com/42178490/80703589-0cfd6900-8ab1-11ea-8bfd-b2e95468fdef.png)

**Comment by frvalenzuela** [comment]
Hola @stmorales !

Cuando se escribe la función MOV A, (Dir), nosotros traemos al registro A lo que se encuentra en la dirección Dir, donde Dir es una dirección de memoria, de la forma:

RegA = Mem[Dir]

Por tanto, cuando nosotros hacemos MOV, (a), nosotros traemos al registro A lo que se encuentra en la dirreción a (donde 'a' es una dirección de memoria. Por tanto quedaría de la forma:

RegA = Mem[a] = E5 

Ahora bien, en este código de ejemplo se tiene que se pasa una dirección física (el valor 1 en decimal) donde estará guardado 'b'. Esto es suponiendo que tu guardas en orden la sección DATA en la RAM. Guardando primero 'a' en la dirección 0, luego 'b' en la dirección 1 y 'bits' en la dirección 2. De ahí que al hacer:

AND A, ( 1d) , se este guardando en A la operación A & Mem[1] = A & b

Ocupando el emulador disponible en la carpeta de tarea2 podemos ver como quedaría la ROM un nivel de assembly básico:
![image](https://user-images.githubusercontent.com/20147482/80725068-9c664480-8ad0-11ea-9b9c-93ae93c68058.png)

Donde lo rojo sería las instrucciones para guardarlo en DATA. Recomiendo mucho ocupar este emulador en los ejemplos para un mayor entendimiento de lo que ocurre.

Espero que con esta explicación quede todo mucho más claro, si no fue así no dudes en consultar nuevamente y con gusto responderemos :smiley: 

Saludos!

**Comment by stmorales** [comment]
Muchas gracias Felipe,

Entonces solo para confirmar si entendí. Cuando hago la definción de mi DATA en assembly, lo que estoy haciendo es asignándole a una cierta dirección de memoria el valor que me dice y sólo se utilizarán estas variables entre parentesis. Por lo que nunca tendré una instrucción donde Lit = varX.

Es correcto??

**Comment by frvalenzuela** [comment]
Hola @stmorales !

Efectivamente, para esta entrega solo deberían esperar que las variables este entre parentesís. En la entrega 3, hay algunos ejemplos donde cuando el literal es una variable se refiere al puntero de la dirección. Pero no tienen que preocuparse por eso en los test, así que no se preocupen. Pueden asumir que toda referencia a DATA será entre paréntesis.

Saludos!

**Comment by stmorales** [comment]
Muchas gracias!

**Comment by fabarros** [comment]
Hola! 
Nuestro programa debe captar la diferencia entre hexagecimal, decimal y binario? Si leemos E5 debemos ser capacer de pasarlo a binario para realizar la operación?

**Comment by frvalenzuela** [comment]
Hola @fabarros !

No es necesario que capten esa diferencia para esta versión del curso. Todos los valores de los test evaluados (que ya se encuentran subidos) están en decimal.

Saludos!
