### ISSUE TITLE
Tutorial 2

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#37]
Cual es el proyecto base que debemos poner? o se refiere al computador primigenio? Graciass

**Comment by Arcoirisky** [comment]
Hola! Es el computador primigenio que está en la carpeta VIvado :D

**Comment by frvalenzuela** [comment]
Complementado lo dicho por @Arcoirisky. Lo importante para abrir el archivo de extensión .xpr

Espero que te sea ayuda saludos !
