### ISSUE TITLE
Dataout ROM en casos de saltos

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2343/Syllabus#37]
Hola, cuando uno tiene un salto como por ejemplo el `end: `en la siguiente imagen, como es que puedo obtener el address de `end:` para colocarlo en el Dataout de la ROM?
![image](https://user-images.githubusercontent.com/42476356/80766185-d2c4b380-8b12-11ea-86de-de8229d42196.png)

**Comment by frvalenzuela** [comment]
Hola @lfuenzalida2  !

Para obtener ese label la ROM debe darlo como literal, y dicho literal debe corresponder a una dirección de memoria de la ROM donde se encuentre la instrucción correspondiente. Un ejemplo en el emulador del computador básico (modificado levemente porque la instrucción DEC A es parte del proyecto y no una instrucción soportada por el emulador) queda así:
![image](https://user-images.githubusercontent.com/20147482/80779082-92782c00-8b38-11ea-970e-318d18cd86e9.png)

Como se ve el salto se hace en la dirección 9, que estará en el literal, y en la dirección 9 es donde esta la instrucción después del label `end`.

Si no queda algo claro no dudes en consultarme.

Saludos!

**Comment by lfuenzalida2** [comment]
ahh ya entendi, mi problema era de como se define el address que se usa en el jump osea ese 9 de donde salía, pero con el ejemplo queda mas claro, muchas gracias!

**Comment by fncabrera** [comment]
Hola @frvalenzuela , 
Me quedo una duda con respecto al end:

Tenía entendido que cuando uno llega a un end, simplemente es para limitar hasta donde llega esa función y el código sigue con lo que venga después del end. Sin embargo, me confundí con el ejemplo del Programa4, donde siento que quedaría en un loop infinito cuando se ejecute el JMP end, ¿cuando termina el programa ahí?

![Capture](https://user-images.githubusercontent.com/30879712/80931638-3eb05180-8d89-11ea-87dc-736e4aabe5b2.JPG)

Gracias!

**Comment by frvalenzuela** [comment]
Hola @fncabrera !

Efectivamente, queda en un loop infinito y nunca termina. Cuando ocurre eso los registros no cambian su estado, por lo para nosotros es más fácil de ver el resultado en la placa cuando queda en ese loop infinito. en la simulación tampoco es tanto problema, puesto que simulamos por un periodo corto de tiempo.

Así técnicamente ese programa no termina nunca, pero como los registros no cambian, pensando en que esto estuviese en una placa, el programa prácticamente termino.

Si queda alguna duda no dudes en comentar.

Saludos!
