### ISSUE TITLE
OPCODE PLACA TAREA 2

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#38]
Hay un opcode que se repite que es del add con el sub, que se hace con respecto a eso?

**Comment by Arcoirisky** [comment]
Oh Noo! Ya se está trabajando en arreglarlo!

Pero en principio el único cambio es que a la luna del error se mueve un cero a la izquierda y de ahí se siguen sumando 1 para que ya no se topen :)

**Comment by frvalenzuela** [comment]
Hola !!

Ya esta arreglado los opcodes de la parte de placa, ahora no deben haber problemas. Ocupen el entregado último actualizado y disculpen las molestias.
