### ISSUE TITLE
Entrega 2: TestSimulacionX

### ISSUE THREAD

**Issue by jrrosas** [IIC2343/Syllabus#38]
Ya probamos el test 1 y tenemos dudas con el resto de la parte de simulación, ¿hay que crear los 5 tests restantes o los van a subir?, ya que no sabemos como probar los otros ejemplos. ¡GRACIAS!

**Comment by frvalenzuela** [comment]
Hola @jrrosas !

Los test con los que evaluaremos serán subidos entre hoy y mañana.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @jrrosas !

Están subidos !

Saludos!

**Comment by frvalenzuela** [comment]
**Aclaración:**

- El TestSimulacion2 y TestSimulacion5 han sido actualizados, más información en la siguiente issue #46 

Saludos
