### ISSUE TITLE
Donde ver notas proyecto

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2343/Syllabus#38]
Hola, 
donde veo mi nota en el proyecto? Soy del grupo 1A y no encuentro donde es que se ve

**Comment by jjaguillon** [comment]
Estimado

En el repositorio creado para la entrega, es decir, el repositorio **proyecto-entrega-1a-"tugithub"**,esta el feedback, en la sección Issues.

Saludos

**Comment by Ignacioislae** [comment]
Lo encontré. Gracias!!
