### ISSUE TITLE
Output unidad de control, dudas específicas

### ISSUE THREAD

**Issue by acpopper** [IIC2343/Syllabus#39]
Hola!
Con mi grupo nos preguntábamos dos cosas:
1. Para casos como, por ejemplo, ADD (Dir), donde no se guardan datos en los registros A o B, como podemos poner eso como señales de la unidad de control? (Sería Enable A=0 y Enable B=0 en la tabla de opcode?)
PD. En caso de que ambos enables sean 0, cómo podríamos poner eso para el opcode diseño microcode? (el R)

2. Algo similar pero para el caso de las instrucciones jump. Cómo sería la tabla de opcodes (outputs de unidad de control) para esas instrucciones (JMP, JEQ, etc)? No entendemos como serían, considerando que no se sobreescriben los registros A y B, y cómo incluir las condiciones del status (ej. Z=1).

Muchas gracias de antemano!

**Comment by frvalenzuela** [comment]
Hola @acpopper !

Respondo a cada punto:

1. Efectivamente, sería Enable A= 0 y Enable B= 0, mientras que W sería igual 1. En caso de microcode podríamos tener una señal que reciba `R and not(W)`, por lo que cuando la señal W este activa las señales de los registros no lo estarán.

2. Esto tiene tres preguntas así que las que responderé ambas por separado:

> Cómo sería la tabla de opcodes (outputs de unidad de control) para esas instrucciones (JMP, JEQ, etc)?

La tabla de opcode esta en el capitulo 5.5 de los apuntes del curso disponibles en el syllabus, pero especificamente de las instrucciones de salto son lo siguientes:
![image](https://user-images.githubusercontent.com/20147482/80892596-47c1f580-8c99-11ea-8337-d780d5566412.png)
![image](https://user-images.githubusercontent.com/20147482/80892617-632d0080-8c99-11ea-9e30-ac71d2f1a24f.png)

> No entendemos como serían, considerando que no se sobreescriben los registros A y B

No todas las instrucciones deben sobrescribir los registro A y B, por ejemplo la instrucción CMP tampoco carga nada a los registros. En este caso, su función no es actualizar los registros A y B, si no más bien es actualizar el registro PC. (de ahí que la señal de loadPC sea 1).

>  cómo incluir las condiciones del status (ej. Z=1).

Una forma de incluir dichas condiciones serían con lo más aproximado que nosotros tenemos a un condicional en circuitos digitales, un selector, ahí puedes incluir las señales provenientes del Status y dar como resultado la señal de carga para el PC.

Si queda alguna duda no dudes en comentar.

Saludos!

**Comment by acpopper** [comment]
Muchas gracias!
