### ISSUE TITLE
Multiplicacion [practico]

### ISSUE THREAD

**Issue by NicolasCourt** [IIC2343/syllabus#39]
Para la parte practica cuando se multilican 2 numeros, esta multiplicacion debe ser implementada del estilo 0010x0110 o 2x6?

**Comment by FranLucchini** [comment]
Todo lo que se trabaja en la parte práctica se basa en números binarios; de hecho, para ingresar los vectores se usan los switches, que devuelven un arreglo de valores binarios.

Es importante notar que deben hacer un multiplicador con circuitos y no usar la operación algebraica.
