### ISSUE TITLE
[Entrega 1D] - Uso de IF

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2343/Syllabus#39]
Hola!, ¿se puede usar IF?

**Comment by jjaguillon** [comment]
Si, puede usarlo solo en los process de diseño secuencial

**Comment by VicenteVicente** [comment]
Con eso te refieres a que sería legal, por ejemplo:
`if n=7 and button_pushed then n=0`

**Comment by jjaguillon** [comment]
El if iría dentro de un statement process, para que sea diseño secuencial, debe utilizar un `rising_edge()` dentro de su if.

Por ejemplo:

```
process(signal)
    begin
        if(rising_edge(signal)) then
            ...
            ...
        end if;
end process;
```

**Comment by VicenteVicente** [comment]
Dale! gracias

**Comment by Cfvalenzuelar** [comment]
Hola! Se pueden ocupar más if dentro del que va acompañado de rising_edge()? saludos

**Comment by jjaguillon** [comment]
@Cfvalenzuelar si.

El requisito de diseño secuencial es que exista el bloque mostrado en el comentario anterior, el uso de if dentro de ese bloque es libre.

```
process(signal)
    begin
        if(rising_edge(signal)) then
            \\aquí el uso de if es libre
            ...
        end if;
end process;
```

**Comment by kmhaller** [comment]
Hola,
Me pasa que si meto un elsif, sale error subrayado en rojo, asi que traté lo mismo pero separandolo en dos if en dos process diferentes, como el mostrado arriba.
Ahora, si hago la simulacion generando un test bench, el problema es que dice que la señal que recibe el rising_edge no esta declarada. Además solo parece leer el primero process.
Espero que me puedan ayudar con eso, me quede pegado ahi. 
Saludos

**Comment by frvalenzuela** [comment]
Hola @kmhaller !

Cuando te aparece un error subrayado en rojo, puedes acercar el cursor para ver el error en especifico. Respecto a la simulación, la señal de clock debe ser entregado como un input más, por lo que debes simular el comportamiento del reloj también en la señalización de los inputs.

Espero que te ayude,

Saludos!
