### ISSUE TITLE
[T01 Simulación] Cantidad de inputs compuertas AND y OR

### ISSUE THREAD

**Issue by fgbruna** [IIC2343/syllabus#4]
Es posible que se reciban _**n**_ inputs para una de estas compuertas o siempre serán binarias?

**Comment by frvalenzuela** [comment]
Hola Franco !

Los inputs de compuertas AND y OR  **siempre** recibirán dos inputs.

Saludos! :D

**Comment by fgbruna** [comment]
Gracias @frvalenzuela !

**Comment by ariel-m-s** [comment]
Hola @fgbruna!

Lo que dice @frvalenzuela  es válido para todas las compuertas binarias (```AND```, ```OR``` y ```XOR```): reciben exactamente **dos** _inputs_. Por otra parte, la compuerta ```NOT``` recibe exactamente **un** _input_.

Happy Pythoning 🐍
