### ISSUE TITLE
Programa del curso/evaluaciones

### ISSUE THREAD

**Issue by sebacruzd** [IIC2343/syllabus#4]
Hola, 

He buscado y no encuentro ninguna especificación sobre las notas del ramo, es decir ies, tareas y proyecto. Sé que el profesor lo dijo la primera clase pero no lo anoté.
Podrían subir algún documento que lo especifique o decirme por acá?

Gracias!

**Comment by Hernan4444** [comment]
@sebacruzd el ayudante jefe se pronunciará durante la próxima semana para dejar claro el tema de evaluaciones.

**Comment by sebacruzd** [comment]
Gracias!

**Comment by jheysen** [comment]
Se ha subido el PPT introductorio y se ha enviado un aviso por SIDING con las ponderaciones del ramo.

**Comment by sebacruzd** [comment]
Muchas gracias!
