### ISSUE TITLE
Vivado problema

### ISSUE THREAD

**Issue by Tngarrido** [IIC2343/Syllabus#4]
Hola, Al momento de instalar el programa, me  aparece aquella ventana para ingresar mi cuenta de usuario y poder descargar los archivos pertinentes, pero cada vez que presiono login, esta ventana me vuelve aparecer inmediatamente, es decir no se accede con el inicio de la instalación (no me arroja error de usuario o contraseña simplemente vuelve aparecer la mini ventana), siendo que realice el tutorial_0 paso a paso. ayuda, adjunto imagen y gracias de antemano.
![image](https://user-images.githubusercontent.com/42189869/62828089-b7440200-bbab-11e9-9521-a1702173c467.png)

**Comment by frvalenzuela** [comment]
Hola @Tngarrido  ! 

Primero diría que te asegures que tú usuario y contraseña sea el correcto al ingresar. Puedes verificar esto iniciando sesión en el sitio web de Xilinx. 

Una vez que te asegures de que tú usuario y contraseña estén correctos, intenta seguir nuevamente los pasos el tutorial nuevamente. 

Si lo anterior sigue sin funcionar recomendaría verificar que la fecha y hora definida en tu computador sea la correcta como especifica en este [URL](https://www.xilinx.com/support/answers/68849.html)

Si aún realizado todo lo anterior sigue fallando, la última alternativa sería cambiar tu contraseña desde el sitio web.

Si nada funciona por favor hacerlo saber, estaremos atento.

Saludos!

**Comment by Tngarrido** [comment]
Me funciono cambiar fecha y hora al momento de validar mi cuenta, pero ahora al momento de comenzar la instalación me aparece lo siguiente: 
![image](https://user-images.githubusercontent.com/42189869/62837299-f7eb5c00-bc3b-11e9-99c5-da08836cdfc2.png)
luego de apretar "yes" o "no" la instalación se detiene, [aca](https://forums.xilinx.com/t5/Installation-and-Licensing/Error-Downloading-files/td-p/860327) describen el mismo error pero entregan la misma solución de cambiar la fecha y hora a la correspondiente, también he intentado hacer el proceso todo de nuevo (descargando todo de nuevo con la fecha y hora correcta) pero llego a lo mismo :(

**Comment by Arcoirisky** [comment]
Tienes activado el antivirus/firewall de Windows?

**Comment by Tngarrido** [comment]
hola, creo que si, recomiendas desactivarlo ?

**Comment by Arcoirisky** [comment]
Inténtalo, a veces lesean con descargas totalmente legales y seguras.

**Comment by Tngarrido** [comment]
Sigue pasando lo mismo :/

**Comment by Arcoirisky** [comment]
Tienes conexión ethernet o wifi? ¿Alguna vez tuviste problemas descargando inventor por casualidad? Me trinca que puede ser el mismo problema de conexión débil

**Comment by frvalenzuela** [comment]
Hola @Tngarrido !

Otra posible solución podría ser eliminando el directorio con todos los archivos en donde el instalador quizás creo algunos archivos cuando tenías mal la fecha y hora. (El directorio es el que tu seleccionaste al momento de empezar la instalación). Ojalá te sirva este o el consejo dado por @Arcoirisky . De no ser así favor hacerlo saber.

Saludos!

**Comment by Tngarrido** [comment]
Tengo conexión wifi, lo curioso es que no sale nada al respecto de una conexión débil. Borre los directorios creado anteriormente, eh incluso se crea uno nuevo pero sigue apareciendo la ventanilla de si quiero borrar el contenido existente, que luego, independiente de lo que respondo, se detiene la instalación y la interfaz desaparece.

**Comment by frvalenzuela** [comment]
Hola @Tngarrido !

Te recomendaría probar iniciando el instalador el otro directorio. Mi hipótesis es que el instalador Vivado dejo algunos archivos de cache con el set de hora erróneos y no los puede modificar, y que quizás esos archivos están en el directorio donde lo estas instalando (asumiendo que no lo haz cambiado). 

Otra opción que se me ocurre es que quizás no tengas el espacio suficiente para instalar Vivado, por lo que también te pregunto si acaso tienes el espacio disponible.

Si no es ninguna de las anteriores, veo como otra opción descargar el instalador más pesado de 19 GB e intentar con ese (estoy descargando ese en este momento para ver como es su funcionamiento y ayudarte con dicha alternativa).

Estoy atento a tus comentarios.

Saludos!

**Comment by Tngarrido** [comment]
@frvalenzuela este fue el directorio que usé para la descarga (por defecto en tutorial), el cual borre y luego se creo nuevamente en el proceso, pero no me funcionó:
![image](https://user-images.githubusercontent.com/42189869/62841424-ddce6f80-bc75-11e9-97b5-9fd7ee38b50d.png)
tengo bastante memoria disponible, como información adicional, tengo una partición del disco duro con ubuntu (no sé si eso influye en algo).
![image](https://user-images.githubusercontent.com/42189869/62841339-01dd8100-bc75-11e9-9bd2-b2685333f592.png)

**Comment by frvalenzuela** [comment]
Hola @Tngarrido !

Me refería al directorio donde descargaste el instalador (tipicamente en la carpeta Descargas), puede que allí este algún archivo de inicio del instalador interpreta mal (esa es mi hipótesis).

Por el momento recomiendo descargar la versión de 19 GB del instalador para ver si de esta forma el error no aparece (refiriéndome a este en especifico) :
![image](https://user-images.githubusercontent.com/20147482/62841514-02771700-bc77-11e9-85c2-e22be68f8ebd.png)

**Comment by Tngarrido** [comment]
@frvalenzuela, lo primero no funcionó así que me encuentro descargando el instalador de 19 GB. Como se demorará bastante en descargar, al momento de ejecutarlo, ¿ prefieres que lo haga en un directorio distinto a "descargas" ?(al igual que antes) y que hago con el otro instalador, ¿ lo borro ? o ¿ no afecta en nada ?

**Comment by frvalenzuela** [comment]
Hola @Tngarrido !

Si lo anterior no funcionó entonces la carpeta Descargas no debe ser el problema. El otro instalador no debería afectar en nada.

Saludos!

**Comment by Tngarrido** [comment]
acabo de probar nuevamente con el primer instalador y me funciono, creo que siempre fue el problema de la hora, ya que cuando la cambie me fije en la hora de mi celular, el cual ya se había adelantado una hora. lo importante es que esta corriendo la instalación, gracias.

**Comment by frvalenzuela** [comment]
Hola @Tngarrido !

Perfecto! Me alegro que te haya funcionado!

Saludos!
