### ISSUE TITLE
[T1] Pregunta 2b

### ISSUE THREAD

**Issue by haarenas** [IIC2343/syllabus#4]
La modificacion que piden en dicha pregunta debe mantener la consistencia algebraica?, ¿existe alguna otra restriccion a la modificacion que se debe hacer?

**Comment by nmaturana97** [comment]
Entonces no es necesario que se mantenga la consistencia algebraica?

**Comment by malopez16** [comment]
@nmaturana97  https://github.com/IIC2343/syllabus/issues/4#issuecomment-414022458 ...?
