### ISSUE TITLE
[T2 - Programada] [Dudas]

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#40]
Hola! La verdad es que he estado leyendo la tarea y no he logrado captar una parte del assembler.
<img width="944" alt="Captura de pantalla 2019-04-13 a la(s) 14 57 29" src="https://user-images.githubusercontent.com/20804346/56084146-dd73b400-5dfc-11e9-8618-0b3d417e396c.png">

Mi duda es como puedo pasar el data hacia la primera parte de las instrucciones. Porque luego vienen los labels (esa parte creo que la entiendo). Por ejemplo fk_2 representarlo, etc. 

Muchas Gracias, espero que se entienda mi duda

**Comment by jmwielandt** [comment]
Ten en cuenta que el valor inicial de las variables puede ser guardado como literal en la memoria de instrucciones.
Por otro lado, para la dirección que ocupe, se guardan secuencialmente en la memoria de datos según la convención que estamos usando en la tarea.

**Comment by NicolasAguirre** [comment]
@jmwielandt buena, perfect! me quedo clarisimo muchas gracias! A todo esto, yo tengo q representar una memoria ?? (o se puede hacer de otra manera (no se si hay otra forma envdad jajaja))

**Comment by jmwielandt** [comment]
Si bien es libre, la verdad es que las tres partes, el assembler, simulador y disassembler están muy relacionadas.
Mientras las posiciones de ambas memorias y sus valores concuerden, todo bien.

**Comment by NicolasAguirre** [comment]
@jmwielandt perfect! gracias!

**Comment by NicolasAguirre** [comment]
@jmwielandt tengo una ultima duda:
cuando hago el dissembler le tengo q entregar un archivo como el precompilado 2 y devolver ejemplo_codigo.s ??
y para la simulacion q archivo debe recibir este?? 
Gracais

**Comment by Arcoirisky** [comment]
@NicolasAguirre

Los archivos precompilados que les dio José no son más que ejemplos visuales/material didáctico para ustedes. No tienen que crearlos ni hacer uso de ellos en la tarea.

El disassembler debe de recibir es un archivo tipo ejemplo_binario.s pero versión txt, tal como dice el enunciado, y lo que retornará será un archivo txt en assembly como el ejemplo_codigo.s (la entrada del Assembler).

Recuerda que la notación de José solo es de comodidad y que la arquitectura con la que trabajan es 8bit, no 16.

Aparte de esto, lo que recibe la simulación, también descrito en el enunciado, un archivo binario compilado (es decir un txt con el formato del enunciado) y que retorne otro txt con los resultados de la simulación.

**Comment by NicolasAguirre** [comment]
@Arcoirisky sip, entiendo perfect! muchas gracias!

**Comment by mramirez7** [comment]
Hola, tengo una duda de los labels en la parte de código, en base a qué se le asigna el valor a la etiqueta? No entiendo por qué al label CASO1 se le asigna el 0x26 y a CHECK el 0x60, por ejemplo

**Comment by jmwielandt** [comment]
@mramirez7 en base a la posición donde se guarda la primera instrucción que viene luego del label

**Comment by Jiruiz2** [comment]
Hola,

Me sumo a la duda anterior, ya que solo se estarían guardando 5 variables en memoria, entonces no entiendo por qué el label vendría siendo 0x26 que vendría siendo 38. Después todo sigue la correlación pero no entiendo este salto inicial

**Comment by jmwielandt** [comment]
La sección data se convierte en 19 líneas de código
Y cada línea de código es 1 opcode y 1 literal
19 * 2 = 38
