### ISSUE TITLE
Contenido en displays

### ISSUE THREAD

**Issue by cacosandon** [IIC2343/Syllabus#40]
Hola!

Vi que para evaluar si nuestro resultado estaba bien, debíamos usar las display. Esto se evaluará?

Cómo se usan estos display? Es el output de la ALU?

Gracias!

**Comment by frvalenzuela** [comment]
Hola @cacosandon !

Parte de la evaluación de su entrega es en base a test, Estos test toman en cuenta la señales `displayA`, `displayB`, `displayC`y `displayD`.

 Finalmente, cito el enunciado de la entrega en la sección de requerimientos:

> ... Para esto basta con mostrar el valor del display al final de la simulaci´on que deber´a mostrar los 8 bits menos significativos de cada registro (disA y disB ser´an el registro A, disC y disD ser´an el registroB. Los 4 bits menos significativos de cada registro son mostrados en disB y disD). 

Si esta parte del enunciado no es clara favor comentar e intentaré explicarlo de otra forma.

Saludos!
