### ISSUE TITLE
Nota Tarea 01

### ISSUE THREAD

**Issue by emontecinos** [IIC2343/Syllabus#40]
¿Donde puedo ver un feedback de mi nota de la tarea?
Comento porque hice todos los desafios y estoy lejos del 7

![image](https://user-images.githubusercontent.com/26130693/64747689-1c11b580-d4e6-11e9-8d8f-fb57da08922e.png)

En la imagen aparezco como rank 1

**Comment by jmwielandt** [comment]
Hola!

Estamos revisando lo que pasó. Probablemente haya sido en el traspaso al SIDING.

Les estaremos informando.
Saludos.

**Comment by Snorlax8** [comment]
No eres el único, me pasó lo mismo!

**Comment by chamox** [comment]
Hola, me pasó lo mismo, tengo un 1 y tenía todos los testcases bien...

**Comment by franciscaguerra** [comment]
Yo también tengo un 1 y si bien no tenía todos los test buenos, me faltaron muy pocos!

**Comment by jgparot** [comment]
Me pasó lo mismo!

**Comment by Arcoirisky** [comment]
Buenas, 

Las issues no es lugar para estos problemas, sugiero mandar un mail al ayudante jefe de las tareas con copia al ayudante jefe para ver cada caso de forma particular.

Saludos

**Comment by emontecinos** [comment]
![image](https://user-images.githubusercontent.com/26130693/64748852-f1c1f700-d4e9-11e9-8c0a-ee659c3dae94.png)

En el enunciado de la tarea aparece que cualquier duda con aspectos administrativos (como las notas) se tratata a través de una issue.
Como ya están informados, sigue siendo necesario el mail?

**Comment by Arcoirisky** [comment]
Sip, sigue siendo necesario el mail.

**Comment by emontecinos** [comment]
La corrigieron

**Comment by Allmoz** [comment]
Efectivamente un problema con el traspaso a Siding. Lamento el susto.

Saludos!
