### ISSUE TITLE
Uso de Módulos Lógicos en Tarea Teórica

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2343/syllabus#41]
Para la Pregunta 2 de la parte Teórica, ¿Podemos utilizar módulos lógicos que ya hemos implementado en clases pero para buses de n-bits? (Por ejemplo, ALU de N bits)

**Comment by FranLucchini** [comment]
Puedes usarlos, pero es importante que con lo que aprendiste en clases sepas cómo tomar elementos de tamaño fijo y generalizarlos para N. Si no estás segurdo de cómo hacer eso para la ALU, puedes preguntarnos.

**Comment by fgbruna** [comment]
@FranLucchini , no estoy seguro si es el lugar adecuado, pero a mi no me queda del todo claro como generalizar un circuito a buses de largo arbitrario.Es posible que compartan una idea inicial de como abordar ese tipo de ejercicios?
Gracias de antemano!

**Comment by FranLucchini** [comment]
En clases deberían haber conversado sobre cómo  combinar full adders para hacer sumadores de más de 1 bit. Un ejemplo de esto está en los apuntes de clases (Apuntes/1 - Fundamentos/02 - Operaciones Aritmeticas y Logicas.pdf). Esta técnica se puede generalizar para N bits.

Para un restador, como se puede hacer a partir de un sumador, ya tienes el restador de N bits.

Para las operaciones lógicas, como se aplican bit a bit, son fácilmente extensibles a N bits.
