### ISSUE TITLE
Error 'set property'

### ISSUE THREAD

**Issue by tanavarrete** [IIC2343/Syllabus#41]
Hola,  al descomentar las lineas del archivo Basys3.xdc me sale el siguiente error:

> [Common 17-55] 'set_property' expects at least one object. ["C:/Users/ricardo.admin/Tarea1/Tarea1.srcs/constrs_1/new/Tarea1.xdc":82]

he estado buscando y no he logrado encontrar por qué sale. Al tratar de crear el Bitstream me sale el siguiente error, que supongo que es debido al primero,

> [DRC NSTD-1] Unspecified I/O Standard: 5 out of 6 logical ports use I/O standard (IOSTANDARD) value 'DEFAULT', instead of a user assigned specific value. This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all I/O standards. This design will fail to generate a bitstream unless all logical ports have a user specified I/O standard value defined. To allow bitstream creation with unspecified I/O standard values (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks NSTD-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run. Problem ports: salida[3:0], and up.

Que estoy haciendo mal?
saludos.

**Comment by tanavarrete** [comment]
Ya subí la entrega parcial, pude hacer que se me borraran casi todas los errores cuando hago Synthesis, pero todavía me quedó uno. 
Muchas gracias!.

**Comment by frvalenzuela** [comment]
Hola @tanavarrete !

En tu entrega parcial faltan entidades dentro de la carpeta `.scr` necesarias para poder ver los problemas asociados a la descripción de tu código. Para poder revisar bien el error que puede estar acomplejandote necesitamos que tu entrega tenga todos las sources necesarias para entender cual podría ser el problema.

Saludos!

**Comment by tanavarrete** [comment]
Perdón, es que estuve tratando de partir de cero de nuevo y se me quedaron en otra carpeta esos archivos, ahora si volví a subirlos.
Saludos!

**Comment by frvalenzuela** [comment]
Hola @tanavarrete !

Revisando el último componente, se puede notar una dependencia circular en el circuito combinacional lo que no esta permitido, debido a que en vivado todo lo que escribas fuera de un process stament será un circuito combinacional, el cual por definición sus depende de estados previos, imposibilitando cualquier dependencia circular.

Mi recomendación es que las señales que están siendo  utilizadas para almacenamiento de datos para otros propósitos, porque eso genera rápidamente dicha dependencia.

Saludos!

**Comment by tanavarrete** [comment]
Hola, 
no entendí bien la recomendación. Las señales que use para almacenamiento de datos solo las use para un componente?

**Comment by tanavarrete** [comment]
le saqué el último componente y corrí la syntesis y me sigue saliendo el error:

> [Vivado 12-584] No ports matched 'btn[0]'. ["C:/Users/ricardo.admin/Desktop/proyecto-entrega-1d-tanavarrete/entrega_1d/entrega_1d.srcs/constrs_1/new/entrega_1d.xdc":110]

**Comment by frvalenzuela** [comment]
Hola @tanavarrete !

Al sacar el último componente no le entregas ninguna señal al botón, porque el componente que sacaste era que daba la señal de activación a los botones.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @tanavarrete !

Mi recomendación es que las señales ocupadas para almacenamiento de datos, solo tenga esa función. Y que las funciones combinacionales sean señales distintas y que no dependan entre si.

Saludos!
