### ISSUE TITLE
T2 Programada discrepancia Opcode

### ISSUE THREAD

**Issue by cmp831** [IIC2343/syllabus#41]
Hola, en el ejemplo subido de la parte programada, se ocupó el Opcode de `JNE` para `JEQ` dentro de `MAIN` (Línea 62, 65 del archivo `ejemplo_precompilado2.s`). Es un error o estoy muy perdido?

**Comment by jmwielandt** [comment]
Ya está arreglado.
Muchas gracias 😄 
Lo escribí a mano así que normal que algo así se me pase ^^U

**Comment by cmp831** [comment]
Gracias!

**Comment by Jiparavich** [comment]
Hola, creo que hay un error, dado que los siguientes archivos no calzan... 
Cual esta bueno? ejemplo_binario o ejemplo_precompilado?
![image](https://user-images.githubusercontent.com/30678179/56100848-c233a200-5eeb-11e9-8b8d-262584462527.png)

**Comment by jmwielandt** [comment]
Oh, olvidé arreglar los opcodes del binario
De momento confíen en el precompilado, el martes durante el día subiré el binario arreglado~
Gracias!

**Comment by vramos1** [comment]
Los opcodes de las instrucciones finales (jumps) están repetidos. Como deberían ser?

**Comment by Arcoirisky** [comment]
¿Estás segura/o de tener el enunciado actualizado? Compáralo con el que hay en el Syllabus.

**Comment by vramos1** [comment]
Fijese en la primera instruccion de JMP con la ultima de SHL. Es el mismo opcode. Felipe Valenzuela me dijo que lo obvie y que siga sumando de a 1 desde que parte el error

**Comment by jmwielandt** [comment]
@vramos1 te refieres a la parte placa o la parte programada?
esta issue es de la parte de programación, haz una issue aparte para las dudas de la isa de la parte de placa.
