### ISSUE TITLE
Duda DATA to RAM

### ISSUE THREAD

**Issue by stmorales** [IIC2343/Syllabus#41]
Hola!

Con mi grupo tenemos una pregunta. Cuando nos dan variables en el apartado DATA de los programas Assembly, estos datos cómo los debemos guardar? Manualmente o agregando la instrucción equivalente a MOV (dir),Lit. Siendo dir = el número de la variable y Lit el valor asociado?

Por ejemplo:

DATA:

var1 10
var2 5

Implicaría que tenemos que agregar las instrucciones equivalente a  MOV (0d),10d y MOV (1d),5d a nuestra ROM??

Muchas gracias

**Comment by frvalenzuela** [comment]
Hola @stmorales !

Como se mostró en el ejemplo #36 se recomienda seguir la forma que hace el emulador, que es primero hacer MOV B, Lit y luego MOV (Dir), B. Dado que la instrucción MOV (dir), Lit en un solo ciclo no esta soportada en la arquitectura. Por lo que como no esta soportada en un solo ciclo, en tu ROM habría las dos instrucciones antes nombradas  para ejecutar lo que tu mencionas como`MOV (dir),Lit` .

Si aún quedan dudas no dudes en comentar, y con gusto será respondida.

Saludos!
