### ISSUE TITLE
Emulador T02.

### ISSUE THREAD

**Issue by nhorellana** [IIC2343/Syllabus#42]
Hola! Este emulador funciona solamente en Windows? O en Linux podría funcionar también?

**Comment by jmwielandt** [comment]
Hola!

@frvalenzuela probó correr el emulador con wine en ubuntu y funcionó bien. Solo tiene como requisito `.net framework 4.6`. En Windows 10 viene y en Windows 7 hay que instalarlo.

En principio Wine también funciona en mac pero nadie del equipo tiene como para probarlo. Sobre cómo usarlo, se indicará en esta misma issue los pasos a seguir.

Saludos~

**Comment by Marialuisaclaro** [comment]
Por favor suban los pasos a seguir!!

**Comment by Arcoirisky** [comment]
@Marialuisclaro se subirán a penas se pueda, tranquilidad respecto al tema.

Recordar que los ayudantes también son alumnos y que hoy a sido día de prueba en muchos ramos :/

**Comment by frvalenzuela** [comment]
Hola @nhorellana !

Los pasos a seguir para ocuparlo en Linux son los siguientes:

**Primer Paso :** Primero se ejecutará el siguiente comando para que wine sepa que el computador es de 64 bits (no es necesario si el computador que ocupen es de 32 bits).

`sudo dpkg --add-architecture i386` 

**Segundo Paso :** Segundo añadiremos el repositorio que contiene wineHQ que es una versión de wine bastante estable para ejecutar archivos ejecutables para Windows en otros sistemas operativos como Linux.

`sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ artful main'`

**Tercer Paso :** Instalar winehq.

`sudo apt-get install --install-recommends winehq-stable`

Para asegurarnos que se haya instalado bien hacemos la prueba con `wine --version`. Que debería mostrar algo similar a `wine-3.0.3 (Ubuntu 3.0.3-2)`

**Cuarto Paso : ** Instalar winetricks. Esta herramienta es una paquete adicional que nos permitirá instalar el framework .net 4.6

`sudo apt-get install winetricks`

**Quinto Paso : ** Instalar el framework con el siguiente comando:

`winetricks dotnet46`

Luego de ejecutar esto se abrirá una ventana de Microsoft .NET, aceptar los terminos de condiciones y dar a continuar/instalar. 

**NOTA: ** El comando primero instalará .net 4.0 y luego instalará 4.5 por lo que si bien dirá que en algún momento que el proceso termino, mientras la terminal siga ejecutandose no cerrarla y las ventanas que aparezcan **NO CANCELARLAS**. Solo dar a continuar hasta que la terminal deje de ejecutar. Es normal que aparezcan errores durante este proceso en la terminal, solo ignorarlos, los siguientes pasos deberían solucionarlo.

**Sexto Paso : ** Ejecutar el emulador. Suponiendo que la terminal esta abierta en la misma ruta donde se encuentre el emulador ejecutar:

`wine emuIIC2343.exe`

Luego aparecerá ventanas como la siguiente:

![image](https://user-images.githubusercontent.com/20147482/64904761-be779780-d6a4-11e9-8ba0-74b593f5d5ec.png)

Esperar hasta lo siguiente, dar a instalar:

![image](https://user-images.githubusercontent.com/20147482/64904766-d8b17580-d6a4-11e9-8d6b-cd308e4eb267.png)

Aparecerá esta ventana, dar a instalar:
![image](https://user-images.githubusercontent.com/20147482/64904788-380f8580-d6a5-11e9-8909-7aac9ffb7268.png)

Finalmente la ventana anterior debería volver a aparecer, se repite el paso anterior, esperar unos segundos y debería estar el emulador listo para usarse.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @Marialuisaclaro !

### COMO UTILIZAR EL EMULADOR

**Primer Paso:** Abrir un archivo, Alertas y Recargar un archivo.

![image](https://user-images.githubusercontent.com/20147482/64904816-ce43ab80-d6a5-11e9-999d-473e296b6529.png)
Apretar el botón abrir y buscar con .txt con un programa escrito con el assembly del computador básico. Para este ejemplo ocuparé el siguiente códido:

```
DATA:
a 0
CODE
MOV A,1
ADD A,1
MOV B,A
MOV A,(a)
MOV (a),B
PUSH B
PUSH B
POP B
POP B
```

Notar que falta dos puntos después de la línea `CODE`, debería ser `CODE:`. Por lo que luego de seleccionar el .txt que tiene este archivo se mostrará una alerta como la siguiente:

![image](https://user-images.githubusercontent.com/20147482/64904890-05668c80-d6a7-11e9-94eb-44f72bb45261.png)

Aquí se mostrará alertas generales sobre lo que sucede en el programa. Ahora si modificamos el archivo .txt y guardamos cambios podemos **Recargar** con el botón mostrado a continuación:

![image](https://user-images.githubusercontent.com/20147482/64904922-73ab4f00-d6a7-11e9-9b10-8dd8812ea100.png)

Una vez recargado, se mostrará un pantalla como la siguiente:
![image](https://user-images.githubusercontent.com/20147482/64904957-c38a1600-d6a7-11e9-99ec-a67eb8556b49.png)

Notar que en la columna izquieda se tiene las variables descritas en DATA, que luego serán cargadas a la RAM. 

**Segundo Paso:** Probar el emulador.
Se presiona el botón Probar del emulador  (marcado en rojo)  el cual comenzará a ejecutar cada instrucción de la columna izquierda (marcada en azul) como se muestra a continuación:

![image](https://user-images.githubusercontent.com/20147482/64905030-bfaac380-d6a8-11e9-8382-a86bc38e625b.png)

**Tercer Paso:** Detener y Recargar.

Mientras el emulador esta ejecutando instrucciones, se puede detener presionando el botón 
Detener como se muestra en la siguiente imagen:
![image](https://user-images.githubusercontent.com/20147482/64905079-57101680-d6a9-11e9-885b-737d266e83b6.png)

**NOTA:** El botón detener no es una **pausa**, eso quiere decir que una vez apretado, si se quiere retomar la ejecución al apretar Probar o Recargar, se reiniciará el programa desde cero.

**COSAS DESTACABLES:** La imagen anterior muestra la secuencia de código anterior en ejecución. Se puede notar que las instrucciones que ya fueron ejecutadas están en _cursiva_. Además se puede notar como se va llenando la RAM, que se puede apreciar en tres columnas principales:

![image](https://user-images.githubusercontent.com/20147482/64905130-e0bfe400-d6a9-11e9-9d31-ddee41df526f.png)

En la columna roja, tenemos la dirección de la RAM correspondiente (siempre las direcciones de memoria dentro del emulador estarán señaladas por corchetes cuadrado). Luego en la columna amarilla tenemos el valor dentro de esa dirección de memoria en base hexadecimal y por último en la columna verde tenemos el mismo valor que la columna amarilla pero en base decimal. 

**Cuarto Paso:** Uso del clock
Para controlar a la frecuencia que va pasando de instrucción a instrucción existe un Clock como muestra la figura:
![image](https://user-images.githubusercontent.com/20147482/64905201-f7b30600-d6aa-11e9-8085-76df21f698bf.png)

Al ser desplazado a la izquierda será más lento, mientras que desplazarlo a la derecha aumentará la velocidad de ejecución. 

**NOTA:** Si se desplaza completamente a la izquierda se consigue una pausa en la ejecución. Mientras que por otro lado si se desplaza completamente a la derecha se ejecutan todas las instrucciones hasta el final. Esto último es muy útil para ver el estado final de la ejecución.

**Quinto Paso:** Revisión de "estadística":

Durante la ejecución y al final de esta se puede visualizar como cambian los distintos registros así también como las direcciones de memoria.

Estadisticas de memoria: Se puede notar la RAM y el stack con sus respectivas direcciones de memoria y lo que hay dentro de ellas:

![image](https://user-images.githubusercontent.com/20147482/64905254-f0d8c300-d6ab-11e9-9391-caaafe07929c.png)

Estadística de código: Se da el número de direcciones ocupadas en la ROM, el número de direcciones ocupadas en la RAM, el número de variables y Code representa el número de instrucciones del apartado CODE.

![image](https://user-images.githubusercontent.com/20147482/64905291-57f67780-d6ac-11e9-991b-9a394dcf5637.png)

Estadísticas de registros: Se muestra el valor del Registro A, B, SP y el Program Counter.
![image](https://user-images.githubusercontent.com/20147482/64905303-82483500-d6ac-11e9-831d-75596e5e9ad2.png)

Espero que con eso quede claro como utilizar el emulador para apoyarse en la realización de su tarea. Si tienen alguna consulta no duden en consultarla por medio de issues. Y aprovecho de disculparme por la tardanza.

Saludos!
