### ISSUE TITLE
Tarea 2[Teórica]

### ISSUE THREAD

**Issue by mvcavieres** [IIC2343/syllabus#42]
Hola, tengo un par de dudas con la tarea teórica:

1. Se debe dibujar solo en la pregunta 2 o también hay que dibujar el verificador y generador de bit de paridad de la pregunta 1?
2. En la pregunta 1b) además de un solo tipo de compuerta, se pueden utilizar 1's y 0's?

3. En la pregunta 2, se debe diseñar el comparador de dos números que se menciona en el enunciado o podemos asumir que existe y construir lo que nos piden en la a), b) y c) en base a este?

**Comment by FranLucchini** [comment]
Hola,

1. Puedes dibujarlo o usar los símbolos lógicos; lo que consideres más claro y entendible.

2. Si te refieres a usarlos de input para la compuerta escogida, no hay problema.

3. El enunciado de la pregunta 2 sólo describe el comportamiento del comparador. El objetivo es diseñarlo.
