### ISSUE TITLE
Tarea 2 Programada ejemplos

### ISSUE THREAD

**Issue by Jiparavich** [IIC2343/syllabus#43]
Hola!

Podrían subir más ejemplos/test ? (Como en la tarea pasada)

De antemano, muchas gracias
Slds

**Comment by tomasrivera** [comment]
Hola, a diferencia de la tarea pasada, creemos que es importante que crees tus propios tests. Esto debido a que complementa lo pedido en la tarea, por lo que permite tener una comprensión más completa de la materia y por lo tanto un mejor aprendizaje.

Eventualmente podríamos subir algunos, pero me gustaría recalcar que parte importante de los aprendizajes que esperamos, es que sean capaces de crear sus propios tests.
