### ISSUE TITLE
Fecha entrega tarea 2

### ISSUE THREAD

**Issue by cotiravanal** [IIC2343/Syllabus#43]
Hola, de parte de muchos compañeros pregunto si es que existe la posibilidad de correr la entrega de la tarea 2 :raised_hands: :pray:

Muchos nos vamos fuera de santiago para la semana del 18 a lugares que no es posible llevar un computador por lo que nisiquiera tenemos opción de avanzar y al final es una semana perdida, dejando muy justo (casi imposible) el tiempo para preparar bien la prueba junto la tarea. 

Porfavooor porfavor porfavor :raised_hands: :raised_hands: :raised_hands:

**Comment by Allmoz** [comment]
El propósito de las tareas es prepararlos en parte para las Ies. Eso es decir bastante.

Saludos.
