### ISSUE TITLE
Flip flop D material I2

### ISSUE THREAD

**Issue by mathiasvaldebenito** [IIC2343/Syllabus#44]
Hola, tengo una duda con el inciso a) de la página 5 del material I2 porque en la solución se ve el mismo flip flop D que está en las slides de clases.

**Comment by jmwielandt** [comment]
Hola,

Nos dimos cuenta de que el diagrama de las slides tiene un error, le falta un NOT para la entrada C. Este es el flip flop D que funciona con flancos de SUBIDA correcto.

![image](https://user-images.githubusercontent.com/37153467/80969265-574f5480-8de7-11ea-9b6d-50f1e45f00af.png)

Eso sí, la tabla de verdad sí era correcta. Muchas muchas muchas gracias!
