### ISSUE TITLE
Duda Displays - Placa

### ISSUE THREAD

**Issue by leolivares** [IIC2343/syllabus#44]
Hola! No me queda claro algo de los displays.
Se espera que para mostrar los valores de los registros se utilicen las señales ya definidas como *dis_a* y *dis_b* (para el caso del registro A, por ejemplo)?
Si es así, me parece que están definidas de 4 bits cada una, y se necesitarían 16 bits para cada registro.
Será que estoy entendiendo algo mal, o debe ser de otra manera?
Gracias!

**Comment by frvalenzuela** [comment]
Hola Leonardo!

Así es, se espera que se muestren en los registros los en dos displays de 4 bits. Por lo tanto **solo podrán visualizar los 8 bits menos significativos**. 

**Ojo** que eso **no** quiere decir que los registros guarden 8 bits, se sigue trabajando en 16 bits como representa el diagrama, pero por limitaciones de la misma placa (no tenemos suficientes displays D:) solo mostraremos los 8 bits más pequeños que serán suficientes para darse una idea de como van cambiando los registros, a lo largo de la ejecución. (Que es el propósito de los displays).

Espero haber aclarado tu duda, si no es así házmelo saber.

Saludos!

**Comment by leolivares** [comment]
@frvalenzuela Gracias me quedó claro!
Me había surgido la duda ya que en el enunciado indicaba que displayA era para los 8 bits más significativos, y displayB para los 8 menos significativos.
Saludos.

**Comment by frvalenzuela** [comment]
@leolivares Toda la razón! Agradezco que lo hayas mencionado y de paso me disculpo y corregí el error en el enunciado.

Disculpen las molestias!
