### ISSUE TITLE
Sistema operativo Vivado

### ISSUE THREAD

**Issue by navarrodiego** [IIC2343/Syllabus#44]
Hola, al parecer las simulaciones en Windows 10 de Vivado no funcionan (el sistema operativo no es compatible).

Lo instalé en Ubuntu 19.04, pero ahora me di cuenta de que tampoco es un sistema operativo compatible (El 18.04 sí es soportado). Alguien más lo ha instalado en Ubuntu 19.04? Han tenido algún problema o saben si voy a tener alguno?

Gracias

**Comment by CristobalHV** [comment]
Hola @navarrodiego

Como ayudante del curso que utiliza Vivado con Windows 10, puedo afirmar que Vivado funciona correctamente en este sistema operativo, simulaciones incluidas.

¿Qué problema estás teniendo exactamente con Vivado al intentar simular? ¿No te deja correr la simulación, Vivado se cae o simular te lanza algún error en específico? Cualquier detalle que puedas darnos al respecto por pequeño que sea será de ayuda para solucionar tu problema.

Saludos :)

**Comment by navarrodiego** [comment]
Para la tarea pasada simular me lanzaba un error en específico, no me acuerdo cuál, pero despues de googlearlo me apareció que podía ser el sistema operativo.

Gracias por la respuesta, si me vuelve a pasar el error lo comento aquí! Por mientras espero que funcione bien
