### ISSUE TITLE
ADC

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2343/Syllabus#45]
Hola! 
Para la tarea 2, primer problema, podemos ocupar ADC? O solo podemos ocupar ADD junto con JCR? 
En general podemos ocupar instrucciones no vistas en el curso hasta ahora?

Gracias

**Comment by Arcoirisky** [comment]
Hola!

No pueden hacerlo :(

La idea es que se manejen solo con el set de instrucciones del computador básico. Específicamente la ISA de los apuntes 5.5, tal como se pide en el enunciado.
