### ISSUE TITLE
Duda entradas MUX

### ISSUE THREAD

**Issue by Jaluco** [IIC2343/syllabus#45]
Hola, en el diagrama de la tarea se ve que a los mux les "entra" un 0 y un 1 de 16-bits, esto significa que cada bit es un 0 o un 1 (si es 0000... 16 veces y 1111... 16 veces)? O literalmente se representan los valores 0 y 1?

**Comment by frvalenzuela** [comment]
Hola Jose! 
Literalmente representan los valores 0 y 1. 
Esto quiere decir que entra 0000000000000000 y 0000000000000001 respectivamente.
Saludos !
