### ISSUE TITLE
[T02 Placa] Output ROM

### ISSUE THREAD

**Issue by mundurragac** [IIC2343/syllabus#46]
Hola, en el enunciado de la tarea dice que el output de ROM es de 33 bits, que se dividen en 2, los 16 menos significativos y los 17 más significativos.
Mi duda es sobre los 16 menos significativos, que 'si van hacia' el registro b se usan los 16 bits, pero 'si van hacia' el PC o la RAM son 12, entonces son los 12 más o menos significativos.

Muchas gracias de antemano.

**Comment by frvalenzuela** [comment]
Hola! 

Van a los 12 bits menos significativos. Lo otro solo por si acaso, los 16 bits menos significativos que salen del output de la ROM van hacia un MUX, no van directamente al registro B.

Espero haber resuelto tu duda mucho éxito!

**Comment by mundurragac** [comment]
Perfecto! Gracias

**Comment by frvalenzuela** [comment]
Hola!

Pido por favor que no cierren las issues, para que así alguien con la misma duda pueda verla. Gracias!
