### ISSUE TITLE
Problema Uso Display - Entrega 1.D

### ISSUE THREAD

**Issue by mvgil** [IIC2343/Syllabus#46]
Hola!
Conecté al display el valor de las monedas, pero no me funciona. Me aparece prendido el display a,b,c, pero el d no hace nada (están todos los segmentos apagados) . Lo raro es que los conecté todos. Tampoco me tira error al generar el bitstream.
Cuando prendo la  placa si me aparecen prendidos los 4 display, pero cuando la programo no. 
Subí mi código al repositorio. 
¿ qué podría ser ?
Muchas gracias!

**Comment by mvgil** [comment]
Al final lo arreglé y me funcionó!

**Comment by frvalenzuela** [comment]
Hola @mvgil !

Me alegra mucho leer eso! Si es posible (osea sin mencionar sobre tu solución) favor de mencionar cual podría haber sido el problema por si alguien se enfrenta a la misma problemática.

Saludos!
