### ISSUE TITLE
Duda Flip Flop D diferencias con material externo

### ISSUE THREAD

**Issue by Cadagan** [IIC2343/Syllabus#47]
Me surgió una duda con el flip flop D de último minuto, ya que en clases comentamos en en el flanco de subida, el output sería igual al input D que le metimos, sin embargo en un video ([este es el link por si lo quieren ver](https://www.youtube.com/watch?v=RP00R9uf004&t=340s)) aparece esta línea de tiempo que dice que el output del flip flop solo toma el valor de D en el FLANCO DE BAJADA del clock: 
![image](https://user-images.githubusercontent.com/30968397/80944215-00ca2200-8db7-11ea-876d-cc03e5ffa750.png)

La verdad es que revise las tablas de verdad de los latch D que usan en el video y son las mismas que las que usamos nosotros en el curso, por lo que no entiendo la diferencia :(
Un saludo y muchas gracias de antemano :)

**Comment by jmwielandt** [comment]
Hola,

Nos dimos cuenta de que el diagrama de las slides tiene un error, le falta un NOT para la entrada C. Este es el flip flop D que funciona con flancos de SUBIDA correcto.

![image](https://user-images.githubusercontent.com/37153467/80969265-574f5480-8de7-11ea-9b6d-50f1e45f00af.png)

Eso sí, la tabla de verdad sí era correcta (si la quieres con flanco de bajada, da vuelta las flechas). Muchas muchas muchas gracias!

**Comment by Cadagan** [comment]
De nada :)
