### ISSUE TITLE
[T02 Programada] Librerias permitidas

### ISSUE THREAD

**Issue by Tito0906** [IIC2343/syllabus#47]
Hola, para la tarea 2 parte programada, ¿existe alguna lista de librerias que podamos ocupar y nos recomienden? o  ¿podemos ocupar la función hex () para transformar numeros decimales a hexadecimales?

**Comment by Arcoirisky** [comment]
Hola! Pueden ocupar toda librería que no necesite instalación y todo build-in de Python **Exepto** eval(☠️) y exec(☠️)
Que puede matar tu computador o el de los ayudantes :D

Aquí algunas de las build-in:
https://docs.python.org/3/library/functions.html

**Comment by Tito0906** [comment]
Ok, muchas gracias¡¡

**Comment by Tito0906** [comment]
Pregunta relacionada a la función hex () . Cuando transformo un numero decimal usando esta función me lo transforma a un hexadecimal con una diferencia entre los que se ven en el enunciado. Por ejemplo, 1 es 0x1 y no 0x01. Esto tiene alguna relevancia?

**Comment by Arcoirisky** [comment]
Mientras tengas en cuenta que el computador es solo de 8bits, no pasa nada. Recuerda el cómo se escriben las bases numéricas y todo será claro uwu)/

**Comment by Tito0906** [comment]
Oka ,muchas gracias :D

**Comment by Sforrego** [comment]
se puede usar bitstring?
