### ISSUE TITLE
Duda I2. 4. Poder de cómputo

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2343/Syllabus#48]
Una consulta, en esta pregunta cuando dice 

> Indica cuales de las siguientes operaciones se pueden hacer en un solo ciclo en el computador básico y cuáles no. Justifica a través del circuito del computador básico. Si no es posible realizar alguna de las instrucciones, indica cómo se debe modificar el computador básico para que sea posible.

¿Se refiere a que si no es posible realizarlas en un ciclo debo modificar el computador para que sea posible hacerlas en 1 ciclo?

**Comment by ceosorio** [comment]
Hola @JoseValencia125!

Exactamente como dices, si alguna instrucción no puede hacerse en 1 ciclo, debes modificar el computador básico para que si lo logre.
Recuerda ser explícito con las señales, los valores de éstas y de las conexiones que hagas en el diagrama.

Ánimo y mucho éxito! ✨

**Comment by JoseValencia125** [comment]
gracias!

**Comment by ceosorio** [comment]
Por favor no cierres la issue, porque a algún compañero le podria servir :)
Nosotros las cerraremos cuando se pertinente.

**Comment by MartinAracena** [comment]
Se pueden hacer componentes dentro de las cajas negras para poder realizar un ciclo o estamos limitados a hacer los nuevos componentes por fuera, sea tanto operaciones logicas And, Or como cosas mas complejas Mux, Adder, etc...

**Comment by ceosorio** [comment]
Hola @MartinAracena,

A cajas negras te refieres a los componentes que ya están dibujados en el diagrama?

**Comment by MartinAracena** [comment]
Si, con eso me refiero a si estamos limitados a poner cosas por fuera, o si dentro de los componentes detallados en el diagrama tambien se pueden poner componentes.

**Comment by ceosorio** [comment]
En ese caso, solo pueden hacer modificaciones por fuera. Es decir, no pueden modificar el funcionamiento de los componentes que ya están en el diagrama.
Recuerda explicar las señales y las conexiones de los componentes que uses :)

Éxito! ✨

**Comment by MartinAracena** [comment]
Y se pueden agregar duplicados de los componentes que ya existen en el diagrama?

**Comment by ceosorio** [comment]
@MartinAracena

Para entender tu pregunta, a duplicado te refieres a la estructura el componente, o a que el duplicado usa la misma señal?

**Comment by MartinAracena** [comment]
Duplicado de la ALU, Data Memory, etc...

**Comment by ceosorio** [comment]
Puedes hacerlo si quieres. Recuerda explicar bien tus conexiones y señales  (y los valores de éstas) 

Ánimo ✨
