### ISSUE TITLE
Problema con auto-connect

### ISSUE THREAD

**Issue by ticastro** [IIC2343/Syllabus#48]
Hola! 
Estoy viendo los tutoriales para compilar en la placa lo hecho en Vivado, y en el paso en el que, luego de hacer el "Generate Bitstream", debemos hacer "auto-connect" para la placa, no sucede nada. No se me conecta a ninguna placa, siendo que esta esta prendida y todo lo demás. Cuál es la solución a esto?

Gracias de antemano

**Comment by frvalenzuela** [comment]
Hola @ticastro !

¿Que sistema operativo estas ocupando ? 

Esto para saber cual podría ser la solución.
Saludos!

**Comment by ticastro** [comment]
Windows 10 !

**Comment by ticastro** [comment]
Hago nuevamente todos los pasos, desde el inicio, creando un nuevo proyecto, y nada. El computador suena cada vez que apago y prendo la placa, por lo que si la reconoce.

**Comment by frvalenzuela** [comment]
Hola @ticastro !

¿De casualidad no tendrás algún antivirus o medida de Firewall activado? La placa en Vivado ocupa un puerto de servidor local, si tu computador bloquea de alguna forma dicho puerto no será posible conectarla a Vivado.

Quedo atento a tu respuesta!

Saludos!

**Comment by ticastro** [comment]
¿Como puedo comprobar eso @frvalenzuela ? No se si es que tendré activada alguna de esas acciones. Se que no genere ninguna de esas por mi cuenta, pero quizás estan por defecto.

**Comment by frvalenzuela** [comment]
Hola @ticastro !

No sabría decirte con certeza pues no posee dicho sistema operativo. La última vez que me tope con un error de este parecido era porque un antivirus no dejaba que se conectara puerto local a la placa. Si no estas ocupando ninguna aplicación o anti virus el problema puede que sea otro, por eso pregunto. Asegura que no exista algún otro programa e intenta nuevamente. 

Quedo atento a tu respuesta.

Saludos!
