### ISSUE TITLE
[Tarea 2] Duda enunciado P.1

### ISSUE THREAD

**Issue by jpjoublan** [IIC2343/syllabus#48]
Tengo una duda respecto al enunciado de la pregunta 1, ya que cuando habla del verificador dice:

> ...se verifica en el receptor si la cantidad de **bits** en el mensaje es par o impar...

Se refiere a que hay que comprobar que el largo de los **bits** sea par o que la cantidad de **1s** lo sea. A priori no me parece lógico que sea la cantidad de bits, ya que en el enunciado dice claramente:

> Una vez transmitido el mensaje, incluido el bit de paridad...

**Comment by FranLucchini** [comment]
Hola,

En el enunciado se indica que se se usa para hacer que la cantidad de 1s del mensaje sea par al inlcuir este nuevo bit, por lo que tiene relación con la cantidad de 1s.
