### ISSUE TITLE
[T2 - PROGRAMADA][DUDA COMPLEMENTO 2]

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#48]
Hola, realizando la simulación me acordé de lo del complemento de 2. Tenia una duda, dado que: 

```

0 -> 0000
1 -> 0001
2 -> 0010
3 -> 0011
4 -> 0100
5 -> 0101
6 -> 0110
7 -> 0111
8 -> 1000
9 -> 1001
A -> 1010
B -> 1011
C -> 1100
D -> 1101
E -> 1110
F -> 1111
```
entonces si:
```
0x <input1> <input2>
```
 si input1 vale 8 o mas, el numero es negativo o no?? (es mas una duda conceptual para asegurar)

o sea si tengo:

```
0xF2 = 0x11110010 (hago complemento 2)
        = 0x00001101
        = 0x00010010 
       = -33
```
Esto esta bien, ya que para la simulación me falta esto y me surgió la duda. Muchas Gracias

**Comment by Arcoirisky** [comment]
Ten en cuenta que esto es lo que significa trabajar con complemento a dos con 4 bits:
```
0 -> 0000
1 -> 0001
2 -> 0010
3 -> 0011
4 -> 0100
5 -> 0101
6 -> 0110
7 -> 0111
-8 -> 1000
-7 -> 1001
-6 -> 1010
-5 -> 1011
-4 -> 1100
-3 -> 1101
-2 -> 1110
-1 -> 1111
```
Con esto deberías tener una idea clara de lo que se termina haciendo :D
