### ISSUE TITLE
I2 p3 - Notación científica en binario.

### ISSUE THREAD

**Issue by gatochico** [IIC2343/Syllabus#49]
Hola!

Todavía no me queda claro a que se refieren en la pregunta de floats con lo siguiente: 

> "Incluye los valores representados en notación científica pero en binario."

gracias de antemano!

**Comment by BSamilla** [comment]
Se refiere a que representes los valores involucrados como números binarios.
Por ejemplo: 4 x 10 ** 5 se escribe (100) x (1010) ** (101)

**Comment by jmwielandt** [comment]
Como añadido a lo que dice @BSamilla, en vez de un diez (10, 0b1010) como base tienes que poner un dos (0b10).

**Comment by jmsilvas** [comment]
Con respecto a esto mismo, es únicamente un requisito de la pregunta expresar los números en notación científica binaria en algún momento. O más bien, nuestra justificación debe basarse en el uso de esta notación? Pregunto porque no creo que sea relevante como lo hagamos siempre que sepamos como escribir ambos números como floats en binario

**Comment by jmwielandt** [comment]
Es requisito que expreses esos números en la notación científica, lo lógico sería que la uses para apoyar tu explicación.

**Comment by lzalaquett** [comment]
Los números tienen que estar representados en notación científica binaria en base 10 o en notación científica binaria en base 2? que es más parecida a IEEE754.
Por ejemplo, 400 tiene que ser:
100 * 1010 ** 10 (4 * 10 ** 2)
ó  1,1001 * 10 ** 1000 (1,5625 * 2 **  8)

**Comment by jmwielandt** [comment]
Notación científica binaria en base 2.
