### ISSUE TITLE
[T02 Programada] Labels de bloques de codigo.

### ISSUE THREAD

**Issue by Sforrego** [IIC2343/syllabus#49]
No se muy bien como identificar a partir del archivo binario el inicio o termino de un bloque de codigo.

siempre van a estar todos los inicios de bloques de codigo mencionados? es decir puedo revisar todas las funciones Jump, Jeq Jne y asi encontrar todos los inicios de bloques? 

gracias :D.

**Comment by jmwielandt** [comment]
Sí, a partir de los jumps debes determinar las ubicaciones de las labels.

**Comment by sipoblete** [comment]
El orden de lo escrito en CODE: siempre sigue el orden de CASOS, LOOP, CHECK, MAIN, END ??
Pudiendo no existir algun LOOP o CHECK claramente.

**Comment by Sforrego** [comment]
Por lo que tengo entendido yo, no. En el enunciado dice que puede haber codigo despues del main, asi que podria ser label1, label2, main, label3, end (creo que el end siempre va al final)

**Comment by jmwielandt** [comment]
@sipoblete las labels usadas tienen ese nombre porque el programa es fibonacci :D
@Sforrego tiene razón. Los labels pueden tener cualquier nombre, los únicos fijos serán main y end.

**Comment by sipoblete** [comment]
Ok, entiendo gracias.

**Comment by cjdelacuadra** [comment]
pero como identificamos la ubicacion de los labels? ya que no calzan,
![Captura de pantalla (21)](https://user-images.githubusercontent.com/37161679/56434828-4a2afa80-62a4-11e9-9668-35a0cadef297.png)
