### ISSUE TITLE
Emulador en Mac

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2343/Syllabus#49]
Hola!
Alguien pudo utilizar el emulador en Mac? Que pueda explicar como hacerlo!

Gracias!

**Comment by jmwielandt** [comment]
Hola!

Como menciono en la issue #42 , nadie del equipo docente tiene mac para probar (asumo que tu pregunta va dirigida a los demás alumnos), pero te dejo link a la página de wine para mac.

https://wiki.winehq.org/MacOS

Saludos y mucha suerte~

**Comment by ninifdr** [comment]
@jmwielandt Hola! Y cuál de todos estos debería bajarme?
![Captura de Pantalla 2019-09-17 a la(s) 00 49 25](https://user-images.githubusercontent.com/42162406/65010075-17357300-d8e5-11e9-87ac-34925a627ee7.png)

**Comment by jmwielandt** [comment]
@Marialuisaclaro no cierres las issues, ya que pueden servir a tus compañeros. Nosotros las cerraremos cuando sea el momento. Y dicho sea de paso, si conseguiste realizar el proceso de ejecutar el emulador con wine en mac, tus compañeros estarían muy agradecidos si compartes los pasos que seguiste 😉 

Hola @ninifdr !

La versión "stable" es la versión que está en producción en este momento, las otras dos son versiones en desarrollo que están ahí por quienes quieran ayudar a testear o simplemente probar las nuevas características. Es bastante común que se haga, la verdad. Intuyo que la "stable" daría menos problemas.

Saludos~ 👍

**Comment by ninifdr** [comment]
@jmwielandt pucha ayer me bajé los tres y ninguno me funcionó jajaja. Gracias igual!

**Comment by Marialuisaclaro** [comment]
Yo también trate con todo y nada me funcionó!

**Comment by ninifdr** [comment]
@jmwielandt Me aparece esto! Sabes qué podría ser?
![Captura de Pantalla 2019-09-17 a la(s) 12 11 44](https://user-images.githubusercontent.com/42162406/65054719-6494fd00-d944-11e9-9da0-6ec9042f1995.png)

**Comment by frvalenzuela** [comment]
Hola @ninifdr ! 

Ese error aparece por la falta del framework .net que ocupa el emulador (el 4.6 para ser específico). En la issue #42 están los pasos a seguir para descargarlo. Ahora bien, desconozco si se servirán esos mismos pasos, pero quizás buscando comandos semejantes puedas lograr instalarlo. 

Saludos !

**Comment by ninifdr** [comment]
Ya, muchas gracias!
