### ISSUE TITLE
formato de entrega

### ISSUE THREAD

**Issue by cjdelacuadra** [IIC2343/syllabus#5]
hola, 
para la entrega debe ser en el formato:
syllabus\tareas\tarea01\respuestas.md
u otro formato?

**Comment by Arcoirisky** [comment]
Al ir al link junto a la fecha de publicación de la tarea se habrá creado un repositorio. Es ahí donde debes de subir tu tarea, incluido el respuestas.md y README.md 

No pueden subir nada al syllabus :D

**Comment by ignacioaraya1995** [comment]
Importa la cantidad de líneas del JSON con la solución, por ejemplo en la solución que se da en el enunciado de la Tarea 1 esta tiene 6 líneas, pero mi código me entrega lo mismo en la misma línea. ¿No hay problemas?

**Comment by Arcoirisky** [comment]
¿puedes explicarte mejor @ignacioaraya1995?

**Comment by jmwielandt** [comment]
@ignacioaraya1995 
Puedes usar 
```python
json.dump(obj_dict, file_object, indent=4)
```

para que retorne el json más bonito en el archivo! :D

**Comment by ignacioaraya1995** [comment]
La solución del ejemplo en el enunciado se dá de la siguiente forma:

> {
>     "not1": 1, 
>     "not2": 0, 
>     "and1": 0, 
>     "output1": 0
> }

Mientras que en mi programa me la entrega así:

> {"not1": 1, "not2": 0, "and1": 0, "output1": 0}

Es el mismo resultado pero mostrado en una línea.

**Comment by Arcoirisky** [comment]
Como dice @jmwielandt puedes hacer eso para que te quede más "bonito". 
Mientras el resultado esté bien no importa como se vea :D

**Comment by ariel-m-s** [comment]
Hola @ignacioaraya1995 !

Por si no se entendió por completo: tanto los espacios como los saltos de línea fuera de los _strings_ **dan absolutamente lo mismo**. Eso es meramente algo de ```E```**s**_TiL_```Ø```.
