### ISSUE TITLE
Download Error Vivado

### ISSUE THREAD

**Issue by ararojas** [IIC2343/Syllabus#5]
Hola!
He tratado de instalar Vivado varias veces, y siempre me aparece el mismo error. Dice:
One or more files failed to download.
Do you want to retry downloading them?
Si pongo que sí, el error vuelve a aparecer.
¿Qué puedo hacer?
Gracias,
Araceli

**Comment by jmwielandt** [comment]
Hola!

¿Estás descargando el webpack, cierto? ¿Puedes adjuntar capturas de pantalla? Y revisa además que tengas espacio suficiente en tu HDD/SSD.

Saludos!

**Comment by Arcoirisky** [comment]
Sin contar tu conexión, si el computador apaga la pantalla/suspende/hiberna, el navegador suele cortar las descargas. 

Intenta descargarlo de nuevo desde la página y no con la opción que te da el navegador de reintentar.

**Comment by ararojas** [comment]
@Arcoirisky  el problema aparece ejecutando el installer, no descargando desde la página, no sé si a eso te referías.
@jmwielandt sí estoy descargando el webpack, y no me funciona agregar capturas de pantalla :(

**Comment by jmwielandt** [comment]
Una vez sacas la captura de pantalla y la copias en el portapapeles, puedes pegarla aquí con Ctrl + V.

![imagen](https://user-images.githubusercontent.com/37153467/62837232-4815ee80-bc3b-11e9-830f-231f49bc6055.png)

![imagen](https://user-images.githubusercontent.com/37153467/62837234-4f3cfc80-bc3b-11e9-83da-470c9ec1c8a6.png)

Si se guarda automáticamente en un archivo, puedes subirla a un host como [imgur](https://imgur.com/).

**Comment by ararojas** [comment]
![error](https://user-images.githubusercontent.com/42160553/62837285-d7bb9d00-bc3b-11e9-8072-a055827b101c.jpg)

Así?

**Comment by jmwielandt** [comment]
<hr />

> ![imagen](https://user-images.githubusercontent.com/37153467/62837314-25380a00-bc3c-11e9-8267-803347a53af4.png)
> Por si te sale más fácil, en Windows existen estas dos herramientas de recorte que te permiten hacer capturas de pantalla sin tener que sacar fotos.

<hr />

Ahora sí, volviendo al tema, ¿cuánto espacio tienes disponible en tu disco/ssd?
Como mencionaron en la issue #4 , quizás tenga que ver con el firewall o antivirus.

Saludos!

**Comment by ararojas** [comment]
Sí sabía lo de los recortes, pero esa foto la había mandado antes por whatsapp preguntando si sabían que pasaba.. jaja
Al final tuve que cancelar la instalación por completo y empezarla denuevo y ahí está funcionando parece.
Gracias!

**Comment by fedetaladriz** [comment]
@ararojas Según el tutorial hay que instalar la versión 2018.3 .... Dará lo mismo?

**Comment by ararojas** [comment]
@fedetaladriz no sé, esa es la versión que me apareció en el lugar donde se suponía que estaba el 2018.3 en el tutorial.. no busqué mas en verdad
