### ISSUE TITLE
Obtener preguntas teóricas desde canvas 

### ISSUE THREAD

**Issue by silvamatias** [IIC2343/Syllabus#5]
Hola! 
Dada la migración tenemos que entregar las respuestas teoricas ahora por un form. Cómo puedo obtener las respuestas que ya había subida para no tener que hacerla toda denuevo?

Muchas gracias!

**Comment by sacorsi** [comment]
Tengo el mismo problema

**Comment by ceosorio** [comment]
Hola @sacorsi y @silvamatias !
Cerramos la tarea en canvas pero ahora debiesen poder ver sus respuestas.
Si aun no pueden, avisen por esta misma issue :)

**Comment by sacorsi** [comment]
@ceosorio ahora puedo ver mi respuesta, gracias!

**Comment by silvamatias** [comment]
Si! muchas gracias
