### ISSUE TITLE
Tarea 1: Espacios en palabras.

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2343/syllabus#5]
En la primera parte, las palabras tendran siempre un espacio entre ellas o podrían tener una cantidad arbitraria de espacios entre medio?

Gracias!

**Comment by FranLucchini** [comment]
Pueden asumir que siempre habrá sólo 1 espacio entre palabras.

Saludos :D

**Comment by KnowYourselves** [comment]
Gracias!
