### ISSUE TITLE
[T2 Programada][Posible error en ejemplos]

### ISSUE THREAD

**Issue by DaToMC9** [IIC2343/syllabus#50]
Hola!, creo que hay un error en los ejemplos entregados, ya que no entiendo por que esa A pasa a ser una B siendo que todas las otras As y Bs se mantienen igual 😕
PD: son los ejemplos ya actualizados 
![image](https://user-images.githubusercontent.com/37244943/56254618-79b4e980-608f-11e9-8e7b-b518dab8bf5f.png)

**Comment by jmwielandt** [comment]
Revisa que tengas los archivos correctos. Lo revisé y está bien.
Lo había corregido antes, de hecho.
(Puedes mirarlo en el propio syllabus y comprobarás que está bien).
