### ISSUE TITLE
Duda i2-4 diagrama lit

### ISSUE THREAD

**Issue by fjlopez7** [IIC2343/Syllabus#50]
En el diagrama se debe pintar la ruta por donde pasa el literal?

**Comment by BSamilla** [comment]
No es necesario que pintes, pero si lo consideras útil para explicar tu implementación puedes hacerlo.
Recuerda ser claro y explicito acerca de las modificaciones que hagas.

**Comment by Seba-F** [comment]
En la pregunta III, en la instrucción CMP 1, (lit).
Esta comparando 1 con el literal que viene en la ROM o con lo que esta almacenado en la RAM en la dirección Mem[lit]

**Comment by jmwielandt** [comment]
Hola, es comparar 1 con lo que está en la dirección de la data memory que apunta lit.

**Comment by MartinAracena** [comment]
Me surgio una duda urgente con esto, en las slides sale que Cmp A, Lit es restar A-Lit...

**Comment by jmwielandt** [comment]
> Me surgio una duda urgente con esto, en las slides sale que Cmp A, Lit es restar A-Lit...
> Y aqui estan diciendo que es A-Mem[Lit]

Porque la instrucción de las slides CMP A,Lit, no CMP A,(Lit).

**Comment by MartinAracena** [comment]
Gracias!
