### ISSUE TITLE
Uso de Display y puertos

### ISSUE THREAD

**Issue by SergioGazali** [IIC2343/Syllabus#50]
Hola!
Estoy teniendo problemas al intentar compilar, la síntesis funciona pero al generar bitstream falla. Uno de los mensajes es que estoy definiendo mal los puertos al parecer: 
_[DRC NSTD-1] Unspecified I/O Standard: 1 out of 13 logical ports use I/O standard (IOSTANDARD) value 'DEFAULT', instead of a user assigned spe_cific _value ... (es largo) ... Problem ports: seg[7]._

Y creo que tal vez entendí mal el uso del modulo para el display: yo descomente clk, y lo use como output, conectandolo al modulo, pero tambien descomente todo en la sección ##7 segment display, definiendolo como output, y a esto le conecté el seg y an que entrega el modulo como salida. 
¿Es necesario descomentar esto para recibir la salida del modulo, o sólo hay que preocuparse de darle al módulo lo que recibe?
Muchas gracias!

**Comment by CristobalHV** [comment]
Hola @SergioGazali 

Te recuerdo que la señal "clk" es el clock, que debe ir como input al display, no como un output.

El error que te da Vivado indica que estás colocándole un valor fijo a una entrada lógica (seg[7]) que debería recibir un I/O (probablemente, el clock).

Te recomiendo leer otra vez el enunciado sobre el uso del Display de la placa.

Saludos!

**Comment by CristobalHV** [comment]
Fe de erratas: 
- La señal "clk" es el clock, que debe ir como input al _controlador_ del display de la placa
- seg[7] es un output (Uno de los leds del display de 7). Te recomiendo revisar si definiste correctamente el bus del modulo principal que lo conecta.

Saludos!
