### ISSUE TITLE
I2 - Poder de Cómputo

### ISSUE THREAD

**Issue by tomasmetroy** [IIC2343/Syllabus#51]
En la pregunta de poder de cómputo se puede asumir que ya se han llevado a cabo algunas instrucciones (e.g asignar valores a registros) o se debe contar un ciclo partiendo desde 0?

Gracias de antemano!

**Comment by jmwielandt** [comment]
Hola,
No importa si ya realizaste alguna instrucción antes (en un ciclo anterior) o si acabo de partir la ejecución.

Saludos!

**Comment by Tito0906** [comment]
Holaa! me confundí un poco con que no importaba ¿cuando dices que no importa cuál opción escojamos, te refieres a que podemos asumir cualquiera de los dos casos (a conveniencia) o a que cualquiera de las situaciones debería dar el mismo resultado?

**Comment by jmwielandt** [comment]
A que cualquiera de las dos situaciones debería dar el mismo resultado.

**Comment by MartinAracena** [comment]
Por que deberia dar el mismo resultado? No es la gracia que si se tienen que poner valores anteriores a los registros y cosas, significa que se esta obligado a hacer 2 operaciones?

**Comment by jmwielandt** [comment]
A lo que yo me refiero es que, si tomamos el caso de la I, da lo mismo si tengo el código:

```asm
MOV A,5
INC (lit) ; esta es nuestra instrucción Mem[lit] += 1
```
o si es 
```asm
ADD A,B
INC (lit) ; esta es nuestra instrucción Mem[lit] += 1
```

La acción de aumentar en 1 la posición de memoria apuntada por lit es invariante a las instrucciones que lo rodeen.

**Comment by MartinAracena** [comment]
Pero si se tuviera MOV A,1 podria usar eso para sumar 1 para el siguiente ciclo.

**Comment by jmwielandt** [comment]
> Pero si se tuviera MOV A,1 podria usar eso para sumar 1 para el siguiente ciclo.

Ah, ya. No puedes apoyarte en instrucciones previas ni futuras para realizar partes de tu instrucción porque eso sería usar varios ciclos.

**Comment by AntoniaChristensen** [comment]
Hola, hay una cosa que no entiendo tan bien de las condiciones que nos dicen para que la instrucción ocurra en un ciclo, en específico donde dice:

>La última cosa que puedes hacer con un dato es escribirlo, luego de eso estás en el siguiente ciclo.

Dado que nosotros usamos flancos de subida para utilizar los componentes conectados al clock, técnicamemente no estaríamos en el siguiente ciclo al escribir un dato? Porque dado el diagrama que aparece en las slides cuando se introducen los clock, dice que partimos con el flanco de subida, por lo que me confunde que "escribir" este dentro del mismo ciclo.

**Comment by bpardobravo** [comment]
Una duda, leer y escribir de/en la data memory cuenta como usarla 2 veces? y por lo tanto no se pueden hacer ambas en el mismo ciclo?

**Comment by jmwielandt** [comment]
> técnicamemente no estaríamos en el siguiente ciclo al escribir un dato? 

@AntoniaChristensen 
Exacto! Mira el ejercicio de la ayudantía donde detallo el funcionamiento del program counter. Para que salga el dato nuevo (la dirección a la que tengo que apuntar de la memoria de instrucciones), lo primero que tengo que hacer es escribir el valor nuevo en el PC. Lo que se da es que en el flanco de subida actualizas el PC con el valor para el nuevo ciclo, al mismo tiempo en que escribes los datos del ciclo anterior en los registros y memoria de datos.

> leer y escribir de/en la data memory cuenta como usarla 2 veces?

@bpardobravo 
Si las direcciones son iguale, y no escribes dos veces, no cuenta como "doble uso". Aunque debes justificar por qué, en este caso.

**Comment by AntoniaChristensen** [comment]
> Lo que se da es que en el flanco de subida actualizas el PC con el valor para el nuevo ciclo, al mismo tiempo en que escribes los datos del ciclo anterior en los registros y memoria de datos.
@jmwielandt Creo que te entendi! Osea como que está desfasado la escritura con el ciclo al cual esa escritura corresponde? A lo que voy es que ese tipo de "desfase" sigue considerándose dentro del mismo ciclo para propósitos de esta pregunta o no?

**Comment by jmwielandt** [comment]
@AntoniaChristensen más que un "desfase", es que el flanco de subida está tanto al final del ciclo T como al inicio del ciclo T + 1.

**Comment by bpardobravo** [comment]
> Si las direcciones son iguale, y no escribes dos veces, no cuenta como "doble uso". Aunque debes justificar por qué, en este caso.

Debo justificar el porqué no cuenta como doble uso o justificar por qué usar la misma dirección? No me quedó claro a cuál de las 2 te refieres

**Comment by tomasmetroy** [comment]
> > técnicamemente no estaríamos en el siguiente ciclo al escribir un dato?
> 
> @AntoniaChristensen
> Exacto! Mira el ejercicio de la ayudantía donde detallo el funcionamiento del program counter. Para que salga el dato nuevo (la dirección a la que tengo que apuntar de la memoria de instrucciones), lo primero que tengo que hacer es escribir el valor nuevo en el PC. Lo que se da es que en el flanco de subida actualizas el PC con el valor para el nuevo ciclo, al mismo tiempo en que escribes los datos del ciclo anterior en los registros y memoria de datos.
> 
> > leer y escribir de/en la data memory cuenta como usarla 2 veces?
> 
> @bpardobravo
> Si las direcciones son iguale, y no escribes dos veces, no cuenta como "doble uso". Aunque debes justificar por qué, en este caso.

**Comment by jmwielandt** [comment]
> > Si las direcciones son iguale, y no escribes dos veces, no cuenta como "doble uso". Aunque debes justificar por qué, en este caso.
> 
> Debo justificar el porqué no cuenta como doble uso o justificar por qué usar la misma dirección? No me quedó claro a cuál de las 2 te refieres

**Comment by tomasmetroy** [comment]
"Si las direcciones son iguale, y no escribes dos veces, no cuenta como "doble uso". Aunque debes justificar por qué, en este caso."

@jmwielandt ¿por qué no contaría como doble uso? Una de las condiciones es "No se está usando algún componente dos (o más) veces para cosas distintas". En este caso sería usar un componente para leer y escribir.

Gracias!

**Comment by jmwielandt** [comment]
> > Si las direcciones son iguale, y no escribes dos veces, no cuenta como "doble uso". Aunque debes justificar por qué, en este caso.
> 
> Debo justificar el porqué no cuenta como doble uso o justificar por qué usar la misma dirección? No me quedó claro a cuál de las 2 te refieres

Ah, no, no necesitas justificarlo, esa es información que te regalamos. Cuando usas la misma dirección de memoria no cuenta como doble uso. Sorry.

> "Si las direcciones son iguale, y no escribes dos veces, no cuenta como "doble uso". Aunque debes justificar por qué, en este caso."
> 
> @jmwielandt ¿por qué no contaría como doble uso? Una de las condiciones es "No se está usando algún componente dos (o más) veces para cosas distintas". En este caso sería usar un componente para leer y escribir.
> 
> Gracias!

Por la misma razón en que la instrucción `ADD A,B` opera en 1 ciclo; LEE A, suma A + B y ESCRIBE el resultado en A.

Más no les puedo decir al respecto, están literalmente a 1 paso.

**Comment by llloyola** [comment]
Hola! En la parte II, ¿A y B son literales o están relacionados con los registros A y B?

**Comment by kelseyfranken** [comment]
Hola!  En el enunciado, donde dice:
> No se está usando algún componente dos (o más) veces para cosas distintas.
Si usamos la ALU una vez para restar 2 literales y otra vez para sumar dos literales, cuenta como cosas distintas?

**Comment by JavierNarvaez** [comment]
Hola! Cuando dice "no se está usando algún componente dos (o más) veces para cosas distintas,
¿por qué eso sería dentro del mismo ciclo si para poder usarlo se requieren 2 señales distintas de la Control Unit? 

Un ejemplo general para no dar una respuesta: si tengo un Mux que depende de una señal 's' que sale de la Control Unit, para usarlo 2 veces para cosas distintas se necesita s=0 y s=1 dentro del mismo ciclo y por el input que recibe Control Unit no pareciera ser posible en un mismo ciclo.

**Comment by mariajesusbraun** [comment]
> Si las direcciones son iguale, y no escribes dos veces, no cuenta como "doble uso". Aunque debes justificar por qué, en este caso.

 @jmwielandt Hola! No entiendo cómo se podría leer y escribir en la memoria en un mismo ciclo, si el valor de la señal W para modo lectura es distinta que para modo escritura, y esta señal viene con la instrucción.

**Comment by Franco1605** [comment]
@jmwielandt entonces, un ciclo sería flanco de subida, línea horizontal, flanco de bajada, línea horizontal y flanco de subida nuevamente ? En otras palabras, en un ciclo, alcanzo a tener dos flancos de subida ?

**Comment by jmwielandt** [comment]
> Hola! En la parte II, ¿A y B son literales o están relacionados con los registros A y B?

Son los registros.

> Hola! En el enunciado, donde dice:
> 
> > No se está usando algún componente dos (o más) veces para cosas distintas.
> 
> Si usamos la ALU una vez para restar 2 literales y otra vez para sumar dos literales, cuenta como cosas distintas?

Sí, cuenta como dos cosas distintas. ¿La ALU puede sumar y restar al mismo tiempo?

> > Si las direcciones son iguale, y no escribes dos veces, no cuenta como "doble uso". Aunque debes justificar por qué, en este caso.
> 
> @jmwielandt Hola! No entiendo cómo se podría leer y escribir en la memoria en un mismo ciclo, si el valor de la señal W para modo lectura es distinta que para modo escritura, y esta señal viene con la instrucción.

Eso ya es duda de materia. No te puedo responder (ahora).

> @jmwielandt entonces, un ciclo sería flanco de subida, línea horizontal, flanco de bajada, línea horizontal y flanco de subida nuevamente ? En otras palabras, en un ciclo, alcanzo a tener dos flancos de subida ?

![flancus](https://user-images.githubusercontent.com/37153467/81079766-f34b8f80-8ebd-11ea-998b-7b9f3be90068.png)

**Comment by MartinAracena** [comment]
Me confunde harto el tema como de que hay dos flancos de subida en un ciclo. Habiamos hablado de que no se podia usar el estado anterior para depender del nuevo estado, por lo tanto si hago ADD A,B y luego INC Lit deberian ser cosas separadas. Lo que entiendo y me confunde de esta issue es que estan hablando como el flanco de subida esta dos veces entonces se usa lo que estaba en el flanco anterior y las instrucciones que le pones al nuevo flanco, pero esto es lo mismo que habiamos hablado de que no se podia depender del flanco anterior, la issue esta confundiendome mas de lo que responde dudas.

**Comment by jmwielandt** [comment]
@MartinAracena en la primera clase de datapath vieron cómo combinando las señales del computador básico que salen de la control unit y el literal que sale de la memoria de instrucciones crear instrucciones. Lo que se pide en el enunciado es determinar si hay alguna forma de combinar estas señales para realizar estas instrucciones o no. Y, si no hay forma, modificar la arquitectura del computador básico para que sí sea posible.

Lo de "en un solo ciclo" es porque hay algunas instrucciones muy especiales que requieren más de un ciclo para completarse, como característica estas instrucciones no avanzan el program counter hasta que están en su último ciclo y esa solución no es válida para esta pregunta.

En esta pregunta no se deberían estar complicando con el tema de los flancos.
