### ISSUE TITLE
Tipo de lenguaje assembly

### ISSUE THREAD

**Issue by ararojas** [IIC2343/Syllabus#51]
Hola!
Quería saber cuál es el nombre de el lenguaje assembly específico que tenemos que usar para la tarea, ya que buscando en internet solo encuentro información de lenguajes assembly más complejos y que nunca tienen solo dos registros.
Si no tiene un nombre, ¿alguien me podría decir donde puedo aprender más de este tipo de asssembly?
Gracias y saludos,
Araceli

**Comment by pgarnham** [comment]
Hola
El Assembly del Computador Básico, cuya arquitectura vemos en clases, no la sacamos realmente de otra parte, sino que esta diseñada para efectos del curso. 
Puedes revisarla en detalle en la sección 5.5 de los apuntes del curso, tal y como se señala en el Enunciado. 
Ánimo con la tarea!

**Comment by ararojas** [comment]
Si, ya me he leído los apuntes y las clases varias veces pero sigo encontrando que hay mucho que falta por explicar, como por ejemplo el manejo de arrays no aparece en ninguna parte, solo hay un ejemplo donde apenas se puede ver. Por eso quería saber si había algo más.

**Comment by pgarnham** [comment]
La lógica detrás de los arreglos se explica en el capítulo “Almacenamiento de Datos”, item 5.3 de los apuntes del curso.
 Si quieres ver algo parecido en cuanto a código, puedes revisar los ejemplos que se hicieron en clases, en el Syllabus del curso.
