### ISSUE TITLE
Producto punto 

### ISSUE THREAD

**Issue by Cschavez** [IIC2343/syllabus#51]
Hola! 
Al hacer el producto punto de los vectores el resultado debiese ser un dígito de 8 bits, pero el enunciado de la parte practica dice que como resultado hay que entregar un bus de 16 bits. Rellenamos con 0 a la izquierda entonces? 

Muchas gracias!

**Comment by FranLucchini** [comment]
Exacto, los bits que sobran se rellenan con ceros.
