### ISSUE TITLE
[T02 Programada] cuando utilizar complemento de 2 y literales

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2343/syllabus#51]
Buenas, que me quedan dudas respecto de cuando utilizar complemento de 2 y unsigned en las variables en la parte de dissasembler.
Si ocurre un 
MOV A,literal
suponemos que el literal es con complemento de 2 o no? Lo mismo para los ADD, SUB, AND, OR, XOR, NOT, etc?
Además, los MOV que contienen parentesis solo tienen variables o pueden tener literales? Podría ser así:
MOV A,(0x1A)
o solo puede ser con variables
MOV A,(var1)

**Comment by jmwielandt** [comment]
Lo del complemento a 2, lo respondo y comento en el primer comentario de la issue #29 .

Lo de las labels... creí que lo había puesto 😖😖😖

## IMPORTANTE: pueden suponer que <u>en el códgo sin compilar</u> todos los saltos y el direccionamiento directo a la memoria de datos, será a través de labels y nombres de variables, nunca a direcciones de memoria explícitas.

**Comment by Jiruiz2** [comment]
Siguiendo la misma pregunta, en los ADD, SUB, etc. se podrían usar variables que tengamos en el data y de ser así cómo sabríamos cuando se trata de literales y cuando de variables.

**Comment by Arcoirisky** [comment]
Como se dijo más arriba, cuando vayas a utilizar un valor ubicado en cierta variable se usará “(var)” sino, es solo el literal.

Se usa la expresión (var) para tomar el valor en ese espacio de memoria. Si solo es var, entonces es la dirección y no el valor guardado.
