### ISSUE TITLE
[Tarea 2] Teórico Pregunta 1a

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#52]
Hola! 

No entiendo muy bien que quiere decir esta pregunta con "¿Cuántos bits con errores es capaz de detectar este esquema?"

Se refiere a:

1. Mensajes de cuantos bits binarios se puede el generador que hicimos
2. Cuantos bits entran en el generador/verificador
3. A cuantos bits se podría extrapolar el circuito hecho, o sea, que tan grande lo podríamos hacer si vamos agrandando el circuito

O a qué se refiere? Gracias!!

**Comment by jheysen** [comment]
A cuántos bits cambiados detecta en un mensaje
