### ISSUE TITLE
I2 - Ruta de acceso a memoria

### ISSUE THREAD

**Issue by cacosandon** [IIC2343/Syllabus#52]
Hola!

Me quedó una duda del Zoom. Se dibujaron algunos registros en paralelo y se especificó que podíamos, por ejemplo, hacer una Data Memory para X bytes y luego generalizar. Sin embargo, en el enunciado se menciona que se debe usar la RAM y no mostrar los registros. 

Entonces, debemos o no mostrar los registros? 

Gracias!

**Comment by jeharcha** [comment]
Hola!!
A mi me surge una duda parecida, relacionada con el nivel de detalle que se le debe dar a la Data Memory.
Entiendo que debo tratar las RAM como una caja negra, pero dentro de ella ¿sólo hay registros o hay más circuitos (que no se podrían decirse en una issue) que hacen algún procesamiento?
Me cuesta definir la frontera para la RAM, para ver que está dentro de ella y no debo agregarlo a mi 
Data Memory, y lo que está fuera de ella y Si debo explicitar en mi Data Memory.

Gracias

**Comment by dlisidoraguelfand** [comment]
A mí tampoco me quedó claro el nivel de detalle que se debe usar.

**Comment by jmwielandt** [comment]
@cacosandon eso lo puse para ejemplificar las entradas de la RAM, no pongan los registros.
@jeharcha dentro de la RAM solo tienes registros, nada más. Ante la duda, cualquier cosa que no se corresponda a los registros déjalo fuera de tu RAM.

**Comment by narierao** [comment]
Hola! las señales también debemos dejarlas fuera de la RAM? o podemos diseñarlas?

Saludos.

**Comment by jmwielandt** [comment]
Las señales van fuera de la RAM.

**Comment by silvamatias** [comment]
Hola! subirán el Zoom? no pude conectarme a esa hora y estoy muy perdido con esta pregunta.
No entiendo bien la abstracción que piden de la RAM cuando dicen:

"Pueden asumir que la RAM es un bloque de registros, sus entradas y sus salidas son las que se corresponden a los propios registros." 

Porque la RAM tiene Data In, Address, W y Data Out (apuntes oficiales) que es básicamente lo que piden que dibujemos. Entonces, lo quieren es que dibujemos los circuitos previos a estos buses de datos y la abstracción que dicen como RAM en realidad son simplemente un conjunto de registros?

**Comment by jmwielandt** [comment]
@silvamatias voy a ver si me da el internet para subirlo, pero lo que pasa es que la RAM es distinto a la memora de instrucciones de los apuntes. La RAM en este caso es una parte de la data memory.

**Comment by stmorales** [comment]
Hola!! Sinceramente encuentro que para hacer esta pregunta necesitamos saber bien cuáles son los verdaderos DataIn y DataOut de una RAM. En ningun minuto se especificó que es lo que necesita una RAM, y en el proyecto toman la RAM como la DataMemory, entonces nos falta la información para poder sacar la solución a esta pregunta. Porque no sabemos hasta qué paso es cuando es la RAM la que hace esto.

**Comment by silvamatias** [comment]
En el apunte "Almacenamiento de datos" describen la RAM (de manera abstracta también) y es idéntica de manera abstracta al Data Memory de los otros apuntes en el computador básico. Creo que una aclaración sobre esto sería bueno porque en el readme hablan de la RAM de forma distinta a la vista en los apuntes

**Comment by silvamatias** [comment]
Además algo que me confunde es que en el enunciado dicen que dibujemos la memoria de datos y luego en el readme hablan de la memoria de instrucciones y @jmwielandt en el comentario anterior también hablas de la memoria de instrucciones. Entonces cual es la que se pide?

**Comment by jmwielandt** [comment]
> Hola!! Sinceramente encuentro que para hacer esta pregunta necesitamos saber bien cuáles son los verdaderos DataIn y DataOut de una RAM. En ningun minuto se especificó que es lo que necesita una RAM, y en el proyecto toman la RAM como la DataMemory, entonces nos falta la información para poder sacar la solución a esta pregunta. Porque no sabemos hasta qué paso es cuando es la RAM la que hace esto.



> En el apunte "Almacenamiento de datos" describen la RAM (de manera abstracta también) y es idéntica de manera abstracta al Data Memory de los otros apuntes en el computador básico. Creo que una aclaración sobre esto sería bueno porque en el readme hablan de la RAM de forma distinta a la vista en los apuntes

Para que les salga más fácil, donde vean que dice "RAM" en la pregunta, reemplácenlo por "Bloque de registros" y ya, es solo una diferencia de lenguaje. Espero que con esto la confusión sea menor. Tienen un bloque de n registros de 1 __byte__ cada uno y al rededor hay distintos circuitos que permiten manejar las distintas entradas de la memoria de datos.

**Comment by jmwielandt** [comment]
> Además algo que me confunde es que en el enunciado dicen que dibujemos la memoria de datos y luego en el readme hablan de la memoria de instrucciones y @jmwielandt en el comentario anterior también hablas de la memoria de instrucciones. Entonces cual es la que se pide?

Fue un error de tipeo, lo que se pide es la memoria de datos. Ya está corregido.

**Comment by silvamatias** [comment]
Gracias!

**Comment by MartinAracena** [comment]
Solo hay una manera de hacer la Data Memory? Porque se me ocurrio una, pero no tengo idea de si es la forma que debiera ser, pero por lo menos en mi mente la logica sigue la linea de los inputs y los outputs.

**Comment by jmwielandt** [comment]
> Solo hay una manera de hacer la Data Memory? Porque se me ocurrio una, pero no tengo idea de si es la forma que debiera ser, pero por lo menos en mi mente la logica sigue la linea de los inputs y los outputs. Por ejemplo en mi caso, estoy muy seguro que es una manera bastante poco optima.

Si funciona y **justificas** bien que es correcto, entonces está bien.

**Comment by jrrosas** [comment]
Los registros son de 1 byte o de n bytes?

**Comment by ceosorio** [comment]
Hola @jrrosas,

Los registros son de 1 byte :)

**Comment by jrrosas** [comment]
Se puede mandar más de una vez la prueba?

**Comment by ceosorio** [comment]
@jrrosas,

Revisa la issue #55 :)
Les pedimos que por favor hagan preguntas con respecto al tema de la issue para mantener ordenadas las dudas. En caso de no encontrar una issue del tema que quieren preguntar, pueden hacer una nueva.

Ánimo! ✨
