### ISSUE TITLE
[T02 Porgramada] Uso de DATA

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2343/syllabus#52]
Hola,
El DATA que tenemos en el código de assembly tiene que ser obtenido de algún lado o nosotros colocamos ahí lo que necesitemos para poder hacer el assembler y disassembler?

**Comment by jmwielandt** [comment]
La sección DATA es parte del programa en ASM, sin compilar.
El assembler debe transformarlo en código, y el disassembler reconstruirlo.
