### ISSUE TITLE
Codigo base parte 1

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2343/Syllabus#52]
Hola!
Al correr el codigo base parte 1, el num_2_2 que es 255 el emulador lo registra en la RAM como -1.
Que se puede hacer para que lo registre correctamente?

Gracias!

**Comment by pgarnham** [comment]
Hola

Recuerda que el computador trabaja en complemento a 2. Entonces, el 255, que en binario es el 11111111 , considerando complemento a 2 en 8 bits, corresponde al -1.
Para más información te recomiendo revisar los apuntes del curso.

**Comment by Marialuisaclaro** [comment]
Si si entiendo que sea -1 en complemento a 2, pero debo trabajarlo como -1? O debo hacer algo para que lo registre como 255?

**Comment by pgarnham** [comment]
Fíjate que el emulador también te debería mostrar un FF, que es un 255 en hexadecimal, es decir, no tienes que hacer nada para cambiarlo. 
Insisto en que los apuntes del curso te pueden ayudar para profundizar en esto.
