### ISSUE TITLE
I2 - Data Memory

### ISSUE THREAD

**Issue by MartinAracena** [IIC2343/Syllabus#53]
Hola, estoy confundido sobre cual debería ser la salida de Data Memory, en clases vimos las cosas que entraban y si se llegaba a escribir en ella o no, supongo que lo que sale es lo que entra en la address, pero hay un caso especial. Cuando se escribe que debería salir, lo que estaba en la dirección antigua o el nuevo valor que esta en la dirección, ya que se escribió sobre ella, que sería data input.

Pregunto porque este caso no lo vimos en clases.

**Comment by jmwielandt** [comment]
> Cuando se escribe que debería salir

Mira la tabla de verdad de los flip flops D, allí encontrarás la respuesta.

**Comment by MartinAracena** [comment]
No me queda claro instantaneamente, ya que si el clock maneja el flip flop D significa se estan cambiando los valores en cada momento. Entonces supongo que la senal Write junto con un AND con el clock son quienes controlan esto, seria asi?

**Comment by MartinAracena** [comment]
El comentario estaba fuera de lo permitido?
