### ISSUE TITLE
Program Device - Target shutdown

### ISSUE THREAD

**Issue by SergioGazali** [IIC2343/Syllabus#53]
Hola!
Al programar la basys 3 tengo un problema, después de poner "program device", y cargar el archivo .bit me muestra el siguiente error:
 [Labtoolstcl 44-513] HW Target shutdown. Closing target: localhost:3121/xilinx_tcf/Digilent/210183736200A
No sé si sea un problema con los cables o la entrada de la placa, porque a veces muestra el error antes, y otras veces se demora más. Pero pareciera que se desconecta o algo así. 

He probado distintos cables, y con el jumper 1 tanto en QSPI (así estaba) como USB. por lo que mis preguntas son:
- en qué posición debería estar el jumper?
- alguna idea de qué estará pasando?
Muchas gracias!

**Comment by frvalenzuela** [comment]
Hola @SergioGazali !

Para programar en la placa el jumper 1 debe estar en JTAG como muestra la siguiente imagen:
![image](https://user-images.githubusercontent.com/20147482/64927369-73fb3580-d7e0-11e9-9834-8464b12ec3fe.png)

Más información en: https://reference.digilentinc.com/basys3/refmanual

Saludos!

**Comment by SergioGazali** [comment]
Muchas gracias! eso no me había quedado claro, sin embargo el comportamiento es el mismo, en el sentido de que todavía me levanta el error de target shutdown, no ha pasado esto a otras personas?

**Comment by frvalenzuela** [comment]
Hola @SergioGazali !

Te aseguraste de que la placa este encendida al conectarla? También necesito preguntar ¿qué sistema operativo estas ocupando? Sobre el registro de personas que le a pasado algo similar, generalmente se solucionaba con revisar que estuvieran bien los controladores, el jumper bien posicionado, un cable en buen estado y la placa encendida.

Quedo atento a tus respuestas.

Saludos!

**Comment by SergioGazali** [comment]
Si, esta prendida la placa. Estoy ocupando ubuntu en virtualbox, intalado en mi mac. Al final a pesar de que tenia el target shutdown alcancé a programar la placa antes de que levante el error, y después ya no era relevante que falle eso porque estaba todo listo. Así que está funcionando! no logré saber bien cuál era el problema pero mientras uno alcance a cargar el programa antes del error, todo anda bien.
Muchas gracias!
