### ISSUE TITLE
[T02 Programada] Redundancia instrucciones en la DATA

### ISSUE THREAD

**Issue by danyestay** [IIC2343/syllabus#53]
Probando mi assembler me di cuenta de que hay una posible redundancia de instrucciones en la data del ejemplo precompilado, específicamente en la línea 11, ya que no sería necesaria debido a la línea 8. 

¿Cómo debemos considerar esa parte? En mi transformación no genero la línea 11, de ahí nace mi duda :/

![image](https://user-images.githubusercontent.com/20783397/56262497-e1c5f880-60ac-11e9-8497-956cc3b82665.png)

**Comment by Arcoirisky** [comment]
Hola~ 
Todas las partes deben funcionar independiente el programa que les demos ,sobretodo el Assembler y Disassembler, ya que estos no son más que “traductores”. 

En tu caso, debes generar la línea “redundante” porque es así como lo quiso el usuario creador del assembly.

**Comment by danyestay** [comment]
Entendido, muchas gracias por la aclaración :)
