### ISSUE TITLE
[Tarea2] Programación

### ISSUE THREAD

**Issue by Nicolasvegam** [IIC2343/syllabus#54]
¿Se puede asumir que en el JSON, los "k" primeros elementos de la lista son entradas y los "m" últimos elementos son salidas? Saber que están ordenadas de esa manera, sin necesariamente sabiendo cuantos son.

**Comment by jheysen** [comment]
No

**Comment by Arcoirisky** [comment]
@jheysen Ya pero, no habrá un output antes de su input ¿no? En plan 

{'from': not2, 'to': and3},
{'from': or5, 'to': not2}.

Osea, las compuertas son 'to' antes de ser usadas como 'from' ¿O no?

**Comment by Geeermy** [comment]
¡Hola @Arcoirisky ! :)

Depende de cómo hayas implementado tu programa, pero en la práctica el orden en el que se presentan **no debiese importar** (ya que, básicamente, estás definiendo qué cables conectarás entre qué componentes, da lo mismo si conectas primero el _output_ y luego el _input_ de un componente en particular, al final el resultado será el mismo circuito).

Los _tests_ **probablemente** seguirán un orden intuitivo (_i.e._ primero _inputs_ y luego _outputs_), pero esto **no debiese** ser un impedimento para su programa (les recomiendo no hacerlo dependiente de esto, ya que podría causar errores dependiendo de cómo se construyan los _tests_... si tienen tiempo, cámbienlo para que el resultado sea el mismo independiente del orden).

Cualquier cosa, por favor indíquenlo en el README de su repositorio para evitar problemas después.

¡Éxito! 🐘
