### ISSUE TITLE
Diagrama Entrega 1D

### ISSUE THREAD

**Issue by mvgil** [IIC2343/Syllabus#54]
Hola!
Para el diagrama, es necesario poner los flip flops en el sistema secuencial ? 
qué tanto nivel de detalle nos piden? 
Me complica la parte secuencial. 
Muchas gracias!

**Comment by jjaguillon** [comment]
Hola.

Si usaste flip flops, se requiere que uses los flip flops como cajas negras.

Si lo trabajaste todo como un registro debes tener separada la lógica combinacional de la secuencial, y trabajar la secuencial como caja negra.

Saludos
