### ISSUE TITLE
Comando Cmp

### ISSUE THREAD

**Issue by miortiz1** [IIC2343/syllabus#54]
Cuando uno ejecuta, por ejemplo, un JEQ despues en la memoria de instrucciones debe aparecer el el opcode de CMP? o simplemente se puede realizar la comparacion dentro de python?

**Comment by tomasrivera** [comment]
Hola, cuando ejecutas un comando como JEQ se salta según los valores de los registros de estado, por lo que no se debe ejecutar un CMP.
Ahora lo lógico es ejecutar un JEQ después de un CMP, pero esto no es necesario.
Saludos.

**Comment by miortiz1** [comment]
Gracias,entendido!

**Comment by cjdelacuadra** [comment]
@tomasrivera y como actualizo los registros de estado, y bajo que condiciones??
![image](https://user-images.githubusercontent.com/37161679/56446915-727e1d80-62d3-11e9-968d-adda4618270e.png)
se que estas son las condiciones, pero en ninguna parte sale donde se actualizan

**Comment by Arcoirisky** [comment]
Estos registros de estados se actualizan por cada operación que realiza la ALU, son salidas de la misma junto con el resultado que libera (incluyendo shifts)

**Comment by cjdelacuadra** [comment]
pero como obtenemos los valores, bajo que criterios?, como se cuando Z, N, C, V es 1 o 0?

**Comment by Arcoirisky** [comment]
Eso lo comenté en otra issue si no me equivoco pero puedes encontrarlo en los apuntes 05 Saltos y Subrutinas.

**Comment by cjdelacuadra** [comment]
ya lo vi, gracias!!
