### ISSUE TITLE
III - Pregunta 4 - I2

### ISSUE THREAD

**Issue by clementeross** [IIC2343/Syllabus#54]
Hola!
Es necesario respetar el orden de "guardar" el valor de la memoria como 0 y luego comparar su valor anterior con 1? O puedo cambiar ese orden?

Gracias!

**Comment by jmwielandt** [comment]
No te puedo responder con muchos detalles sobre eso, pero ten presente que las dos operaciones deberían ocurrir simultáneamente, entre un flanco de subida y el siguiente.

**Comment by nbnavarro** [comment]
Hola @jmwielandt,
cuando dices 
> entre un flanco de subida y el siguiente

es considerando el siguiente o sin considerarlo?
