### ISSUE TITLE
Recepción de placas 1D

### ISSUE THREAD

**Issue by SergioGazali** [IIC2343/Syllabus#55]
Hola! 
Mañana no hay ayudantía y avisaron que el horario de entrega de las placas es justo durante los dos módulos en que tengo clases.
Hay alguna posibilidad de entregarla antes de las 10:00, o justo después de las 12:50? 
Gracias!

**Comment by Arcoirisky** [comment]
Hola,

Deberías de mandarle un mail al ayudante jefe del área de proyecto para que vea tu caso particular.
