### ISSUE TITLE
[T02 Programada] Duda sección DATA

### ISSUE THREAD

**Issue by llloyola** [IIC2343/syllabus#55]
Hola! He estado pensando harto rato y no logro cachar cómo es la sintaxis de la sección DATA transcrita a binario (o hexadecimal, whatever) 😢 Entiendo que los espacios de memoria son incrementales acorde a las variables asignadas en el código, pero no sé cómo "escribir" DATA en binario. 

Por ejemplo:

```s
DATA:
    var 3
    foo 0
```

¿La primera línea del archivo binario sería algo así como `0x00 0x03`? ¿Y la segunda sería `0x01 0x00`? Estoy entendiendo que en el espacio `0x00` iría el valor `0x03` (y la misma lógica para `foo`, pero no sé si está correcto 😥 

Cualquier comentario o ayuda se agradece ❤️

**Comment by tomasrivera** [comment]
Hola, ¿viste el ejemplo precompilado en el repositorio del curso?
Esto debería aclarar tu duda, si no es así puedes comentar nuevamente.
Saludos.

**Comment by llloyola** [comment]
Ya lo había visto, así que le di más vueltas y, por fin, logré ver que lo que necesitaba estuvo ahí todo el tiempo jajaj Ya resolví mi duda 😄 ❤️ 👨‍💻
