### ISSUE TITLE
Entregar más de una vez

### ISSUE THREAD

**Issue by mora4** [IIC2343/Syllabus#55]
Hola, 
¿Se puede contestar el form más de una vez?

**Comment by ceosorio** [comment]
Hola @mora4,

Si puedes contestar el form más de una vez :)

Éxito! ✨

**Comment by mariana-ortega** [comment]
Pero parece que no se pueden actualizar las respuestas en el formulario no? Se tiene que enviar todo el formulario nuevamente?

**Comment by BSamilla** [comment]
No es necesario que envíes todo nuevamente, se guardará la ultima entrega que hagas para cada pregunta de manera independiente.
PD: Respondo esto de manera excepcional, el horario de preguntas ya acabo.
Exito!
