### ISSUE TITLE
Máximo líneas de código

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2343/Syllabus#56]
Hola!
¿Existe un máximo de lineas de código o de variables que soporte el emulador? Para la parte 3 me pasa que si me excedo de 50 lineas (aunque sea agregar variables que no se utilicen) me deja de funcionar. Se puede hacer algo?

Gracias!

**Comment by Allmoz** [comment]
Existe un límite de la cantidad de instrucciones que puedes tener en la ROM del computador básico. Como tiene un direccionamiento de 8 bits, el máximo es 255 palabras. El ensamblador no es consciente si las usa o no las instrucciones, el solo las traduce. Te recomiendo reducir tu código, sin quitar las variables o el código reservado para la corrección.
