### ISSUE TITLE
Pregunta Memoria de Datos

### ISSUE THREAD

**Issue by Franco1605** [IIC2343/Syllabus#56]
Hola !
en cuanto a esta pregunta, se pide describir la memoria de datos solo con componentes que hemos visto en clases, no cierto ?

Gracias !

**Comment by BSamilla** [comment]
Puedes crear tus propios componentes si lo consideras necesario, pero debes dar los detalles de su funcionamiento.

Saludos!

**Comment by Cadagan** [comment]
Que tan detallado? o basta con poner "cajas negras" y explicar qué hace con lo que entra para producir el output deseado?

**Comment by BSamilla** [comment]
Si es un componente creado por ti debes colocar el circuito interno, entradas, salidas, señales que utiliza, y la tabla de verdad.
Si es un componente visto en clases o en ayudantía, debes indicar cual es, las entradas, salidas y señales.
Recuerda que es parte de la pregunta explicar por qué el circuito es correcto y necesitarás estos datos para hacerlo.
Exito!
