### ISSUE TITLE
Número de bits de emulador

### ISSUE THREAD

**Issue by dhvasquez** [IIC2343/Syllabus#57]
Hola,
quería saber si el emulador puede trabajar con números mayores a 8 bits, ya que no los puede representar en la ram.

**Comment by pgarnham** [comment]
Hola
No se puede. El computador sólo es capaz de trabajar hasta con 8 bits, y el emulador esta hecho para (valga la redundancia) emular la ejecución de código para este mismo computador, y por ende, usa 8 bits. La idea de la pregunta es precisamente que logren, mediante un programa, manejar números más grandes.
Ánimo con la tarea y feliz 18!
