### ISSUE TITLE
Tarea 2 Compuertas NAND vs AND y NOT [Teórica] [1b]

### ISSUE THREAD

**Issue by gebalassa** [IIC2343/syllabus#57]
¿Se pueden usar las puertas NAND como una sola? El enunciado coloca la compuerta NOT y AND por separado.

**Comment by Geeermy** [comment]
¡Hola!

Sí, pero aunque sea redundante igual pon esa colocación en la pregunta, por si acaso.

¡Éxito! (Recuerda que la entrega ya fue, así que trata de subirla lo más pronto posible para que afecte menos el descuento de atraso 👀).
