### ISSUE TITLE
Relacion registros pregunta 5 - Ruta de acceso a memoria

### ISSUE THREAD

**Issue by Cadagan** [IIC2343/Syllabus#57]
En una parte de la pregunta dice 

> Debe ser genérico para una memoria de n bytes, trabaja la unidad de almacenamiento como una
memoria RAM, no como registros individuales

Esto quiere decir que la Data Memory que hagamos, debe ser capaz de almacenar una variable en varias direcciones distintas en caso de ser necesario? 

Lo digo por espacio, como se comenta en los apuntes del curso, ¿o solo se espera que pueda almacenar datos de tamaño hasta la capacidad de un solo registro nomas?

**Comment by jmwielandt** [comment]
> En una parte de la pregunta dice
> 
> > Debe ser genérico para una memoria de n bytes, trabaja la unidad de almacenamiento como una
> > memoria RAM, no como registros individuales
> 
> Esto quiere decir que la Data Memory que hagamos, debe ser capaz de almacenar una variable en varias direcciones distintas en caso de ser necesario?
> 
> Lo digo por espacio, como se comenta en los apuntes del curso, ¿o solo se espera que pueda almacenar datos de tamaño hasta la capacidad de un solo registro nomas?

No tienes tipos de datos, solo tienes __bytes__. Un __byte__ por dirección de memoria, concretamente.

**Comment by Cadagan** [comment]
perfecto! muchas gracias :)
