### ISSUE TITLE
[Tarea 2] Lectura de una dirección de RAM virgen

### ISSUE THREAD

**Issue by lucasvsj** [IIC2343/Syllabus#58]
Estoy haciendo la parte 2 de la tarea y en un momento realizo la siguiente acción

`MOV B, arreglo`
        .
        .
        .
`MOV A, (B)`
        .
        .
        .
`INC B`
`MOV (index), B`
`MOV B, (B)`

Esto funciona perfectamente como por dos iteraciones, pero después el sale el siguiente mensaje en el emulador:

`... Alerta - Ejecucion [ MOV A,(B) ] Lectura de una dirección RAM virgen.`
`... Alerta - Ejecucion [ MOV B,(B) ] Lectura de una dirección RAM virgen.`

Mi duda es: ¿Qué quiere decir éste mensaje?, ¿Se borraron los datos que estaban en el arreglo?

**Comment by pgarnham** [comment]
Hola

Lo que pasa es que el emulador te alerta cuando lees una dirección en la ram que no está inicializada (virgen). Esto quiere decir que estas leyendo una dirección cuyo valor no es conocido y por lo tanto algo que, en circunstancias normales, no es deseado. Una de las causas puede ser que te pasaste del arreglo. Te recomiendo revisar la manera en que estás recorriéndolo. 
Ánimo y feliz 18!

**Comment by lucasvsj** [comment]
Siguiendo este thread, es importante el tiempo que se demora el programa en encontrar el resultado final?
