### ISSUE TITLE
Entrega 2 | Formato entrega

### ISSUE THREAD

**Issue by nbnavarro** [IIC2343/Syllabus#58]
Hola,

Para incluir las salidas de la simulación en el informe, podemos subir las imágenes en una carpeta al repositorio? (la idea es poder referenciarlas en el .md)
En caso de que sí se pueda, hay que seguir algún formato especial?

Muchas gracias de antemano

**Comment by frvalenzuela** [comment]
Hola ! 

Si pueden incluir todo lo necesario para su informe, y no se tiene que seguir algún formato especial. La única restricción sería que no afecte el funcionamiento del .xpr 

Saludos !
