### ISSUE TITLE
Duda señales

### ISSUE THREAD

**Issue by Jaluco** [IIC2343/syllabus#58]
Existe alguna parte donde podamos ver que señales hay que activar para las distintas operaciones? He buscado y no encuentro nada que ayude

**Comment by Arcoirisky** [comment]
¿Hablas de las señales que liberan la Control Unit? 
Eso depende netamente de tu computador, si ves los apuntes podrás hacerte una idea de cómo funciona. Pero debes seguir el camino de qué activar y qué no activar con cada instrucción según las conexiones que utilizaste en tu programa.

**Comment by frvalenzuela** [comment]
Hola Jose!

Nosotros esperamos que ustedes entiendan que debería ocurrir al ejecutar cada instrucción y eso significa saber que señales deberían activarse para las distintas operaciones. Como bien menciono @Arcoirisky los apuntes en el syllabus pueden ser un gran apoyo a lo que buscas.

Saludos!
