### ISSUE TITLE
[Tarea 2] Suma negativa

### ISSUE THREAD

**Issue by josefinaijb** [IIC2343/Syllabus#59]
Buenas tardes,
En el enunciado de la tarea 2, parte 1, dice que si el resultado es menor a cero se debe guardar en dos sets de variables distintas. No logro entender en qué caso podría obtener un número negativo de la suma. Lo único que se me ocurre es que la suma supere 128, que es el máximo número alcanzable para un computador de 8 bits, y que la numeración "reinicie". Pero para el ejemplo dado, al sumar el número 255 (leído como -1 para el emulador)  con 34 el resultado es emulado como 33, no como un número negativo.
¡Muchas gracias de antemano!

**Comment by josefinaijb** [comment]
ya logré que me diera de resultado números negativos para poder entender como funciona el programa, pero ahora tengo la duda de cómo operar con esos números. En mi algoritmo trabajo con el último byte de cada número, los opero, y luego paso al primer byte siguiendo el formato de BigEndian. Solo que no logro descubrir cuál sería mi carry en caso de que la suma quede en negativo y la mayoría de las veces que he probado, una de las sumas queda en negativo pero la otra no. 

Ayudaaa

**Comment by Allmoz** [comment]
El resultado es un solo numero de 16 bits en complemento a 2. Por lo que en su totalidad es negativo, o no lo es. Por lo visto en clases debes poder distinguirlo. 

Respecto a cómo operar, cada uno de tus operandos es un número de 16 bits en complemento a 2, y el computador básico es de 8 bits, por lo tienes que lograr hacer la operación entre ellos de a 8 bits a la vez. 

Finalmente para poder almacenar variables de 16 bits en una memoria con una palabra de 8 bits tienes que dividirlas. El orden en que están las partes de estos números en la memoria, en este caso en particular, es BigEndian.

El emulador, al igual que el computador básico en el que se basa, no sabe lo que hace tu programa, sólo lo ejecuta. Lo que muestra es lo poco que puede interpretar: El hexadecimal que corresponde al binario en memoria y un decimal con signo cuando ese binario se lee como un número de 8 bits en complemento a 2. Si te es más fácil, solo considera los números en hexadecimal, e interpretarlos tu según como corresponda.
