### ISSUE TITLE
Duda With/select/when

### ISSUE THREAD

**Issue by Felipehanckes** [IIC2343/syllabus#59]
Estimados, tengo una duda en torno a la sintaxis del statement with select, ya que en vivado no me sale ningun error de sintaxis pero no he encontrado nada parecido a esto en intenet.

Es posible crear el comportamiento de una entidad utilizando with select when de la siguiente forma?

![Screenshot from 2019-04-17 19-11-36](https://user-images.githubusercontent.com/30679254/56324501-023d9380-613d-11e9-8d10-6eba4c9cd081.png)

¿o es necesario acotar cada linea para un unico vector?

**Comment by mundurragac** [comment]
En el enunciado de la Tarea hay un ejemplo de como usarlo.
with <variable_a_revisar> select <variable_para_guardar> <=
    <valor_deseado_1_para_guardar> when <valor_de_variable_a_revisar>,
    <valor_deseado_2_para_guardar> when <valor_de_variable_a_revisar>;

Espero que se entienda

**Comment by frvalenzuela** [comment]
Hola Felipe!

Primeramente, lo que escribes en tu ejemplo tiene problemas de sintaxis, por motivos de puntos y comas (cada linea de when debe tener una coma). En segundo lugar, no se logra entender bien que intentas hacer con tu entidad descrita. Como yo lo interpreto es que es que el valor de a, el valor de b y el valor de ent cambiará según que valor tome data. 

Recordando que ocupamos los stament `with/select` para representar muxes, lo que tu deberías hacer en dicho caso sería hacer tres muxes distintos eso sería algo del estilo:

```
with data select a <=
    "10" when "00000000",
    "00" when others;

with data select b <=
    "00" when "00000000",
    "11" when others;

with data select ent <=
    '0' when "00000000",
    '1' when others;

```

NOTA: Como este es un multiplexor con una señal de control llamado data, debería escribir todas las 255 combinaciones (que sucede por ejemplo cuando data toma el valor "11001100"). Pero por temas de espacio y ejemplificar ocupe `others`, que como su nombre bien lo menciona, dice que en todo otro caso no mencionado se toma dicho valor (similar como si en un lenguaje de programación escribieras `else`).

Visualmente, los tres muxes se verían de la siguiente forma:
![image](https://user-images.githubusercontent.com/20147482/56330936-3d998b80-6158-11e9-97b4-3bc309f12e7c.png)

Ahora bien respondiendo a tu primera duda, el comportamiento de una entidad puede estar relacionado con `with/select` para hacer una decisión en base a parámetros de entrada. (Como por ejemplo el caso de la ALU, que tiene un selector de operaciones). Por lo que si es eso a lo que te referías, si es posible. De no ser a lo que te referías favor de aclarar para poder responder con mejor foco.

Finalmente, no entiendo bien tu duda sobre acortar cada línea para un único vector. ¿Te refieres a que si debes acortar un `std_vector` ? Si fuese así depende netamente si la señal es más grande de las opciones que le das para seleccionar. Por ejemplo no podría poner lo siguiente:

```
signal data            : std_logic_vector(7 downto 0);

with data select a <=
    "10" when "0000000000000000", -- ESTO NO SE PUEDE HACER !!
    "00" when others;
```
Esto se debe a que data esta definido como un `std_logic_vector(7 downto 0)`, es decir solo como un bus de 8 bits, por lo que no debería acortar el valor "0000000000000000".

Nuevamente si no es a lo que te referías favor aclarar para poder responder mejor tu duda, si es que todavía prevalece.

Saludos!
