### ISSUE TITLE
Duda Tarea 3 programación 

### ISSUE THREAD

**Issue by Unknomads** [IIC2343/syllabus#59]
Hola.

¿Podemos asumir que el ejemplo del archivo de entrada JSON que nos dan es el único formato que puede tener el archivo JSON?

Saludos

**Comment by Geeermy** [comment]
¡Hola!

Como dice el enunciado, esa es la convención a utilizar (último párrafo de la parte de programación, para ambas partes).

Nunca usaremos un JSON con atributos o elementos que no sigan esa convención.

¡Éxito! :dog2:

**Comment by Unknomads** [comment]
Ok muchas gracias!

**Comment by FranLucchini** [comment]
Hola, por favor no cierren las issues.
