### ISSUE TITLE
Complemento a 2

### ISSUE THREAD

**Issue by movaldivia** [IIC2343/syllabus#6]
Hola!

En la guía de representación, en la sección complemento a 2 sale un ejemplo con 10011, aplicando el algoritmo queda el positivo 010011 y el negativo 101101 obteniendo que la suma es 1000000. Aquí me surgen dos dudas:
- Tenemos dos representaciones para cero? (1000000 y 000000)
- Para representar el cero de la forma 1000000 necesitamos un bit extra por lo que pasa de 6 bits a 7 bits con lo que muchos números se desperdician y eso me hace ruido.

Gracias de antemano

**Comment by Geeermy** [comment]
¡Hola! 😃

En el ejemplo que mencionas, trabajamos con una representación de 6 bits. Por lo tanto, 10011 en realidad para nosotros será 010011. De esta forma, por complemento a 2 nuestro número negativo será 101101 (apareciendo de forma "natural" el bit de signo).

Ahora, tienes razón con el hecho de que la suma es 1000000. El tema es que no debemos olvidar que estamos con una representación de **6 bits**. El "1" de esa secuencia de bits corresponderá a un bit de "carry", pero que en la práctica no utilizarás para la representación del número resultante de la operación. Por lo tanto, representas a tu número con los 6 bits menos significativos, esto es: 000000 (única representación que utilizaremos para el 0, por lo que "no se desperdician números"). También puedes considerar lo que dicen los apuntes de que es un bit de "signo" tal que -0 = 0, pero esto no considera la cantidad de bits que se están utilizando en la representación, lo que puede causar ruido.

Espero haber sido claro, si tienes más dudas me consultas. 😄

¡Que estés bien!

**Comment by movaldivia** [comment]
Tremenda explicación, todo muy claro, te pasaste !
