### ISSUE TITLE
RGB: Escalar a n bits

### ISSUE THREAD

**Issue by fabarros** [IIC2343/Syllabus#6]
Hola, aún no entiendo qué es lo que piden en el enunciado. Entiendo bien qué es y cómo se hace el escalar, pero no entiendo si tenemos que, por ejemplo, completar de 5 a 8 bits llenando con ceros a la izquierda y luego escalar ese valor de 8 a 16 bits, o tengo que escalar de 5 a 8 bits y luego llenar con ceros a la izquierda hasta completar los 16 bits (cosa que no cambia el valor del número).

Gracias! Saludos.

**Comment by jmwielandt** [comment]
Hola, es lo segundo que dices. Pasas de 5 a 8 bits y luego rellenas con 0.

![image](https://user-images.githubusercontent.com/37153467/78628802-48669800-7863-11ea-9188-103518b34ba0.png)

**Comment by fabarros** [comment]
Gracias!

**Comment by Franco1605** [comment]
Hola!
Yo tengo esta misma duda. Estoy intentando pasar de RGB a CYMK. En el enunciado me dicen que RGB se componen de 5 6 5 bits, respectivamente. Lo que dijiste arriba es: tomo el número anterior (5 ó 6), lo escalo a 8 bits y luego lo paso a 16 bits rellenando con ceros a la izquierda. Así es ?

**Comment by jmwielandt** [comment]
@Franco1605 mira la issue #9 
Ahí desarrollo todo el proceso con un ejemplo

**Comment by Franco1605** [comment]
Gracias !
