### ISSUE TITLE
Tarea 1: Interpreter.zip y palabras palindromas.

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2343/syllabus#6]
Dos dudas:

1) Si el interpreter.zip tira error al tratar de correr mi programa, pero el .exe funciona bien, debería preocuparme?, en caso de que me deba preocupar, aparte del uso de `//HEADER`, que condiciones hay que cumplir para que el interpreter funcione?

2) En los testeos se nos pasarán palabras que de por si son palindromas?, En caso de que asi sea, que se debería retornar?

Gracias!

**Comment by MainScientist** [comment]
Sí, deberias preocuparte de que no funcione con el zip, no porque este malo tu codigo sino porque el zip aun no es muy permisivo.  Debes escribir todo en lineas separadas, en caso de ser otro el error por favor te pido escribirme un mail con el código.

**Comment by KnowYourselves** [comment]
A qué te refieres con lineas separadas?

**Comment by MainScientist** [comment]
no pueden haber labels e instrucciones en una misma linea
