### ISSUE TITLE
[T01 Somulación] Inputs & Outputs para testear código

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2343/syllabus#6]
¿Podrían subir ejemplos como el del enunciado de la tarea para ir testeando el código?
Gracias

**Comment by Arcoirisky** [comment]
Sip, en un momento les subimos algunos tests en la carpeta de tareas pero, solo los archivos :D
Es bueno para practicar que ustedes vean si es o no la salida correcta ouo)/

**Comment by Arcoirisky** [comment]
@ignacioaraya1995 Tests subidos uwu)/ Disfruten jugando con ellos :D

**Comment by ignacioaraya1995** [comment]
Gracias!

**Comment by xariveros** [comment]
Hola!
Una preguntita:
Como se espera que sea el formato del archivo json del ejercicio de equivalencia??
Que sea de este tipo?  

{"circuit": [
    {"from":"input1","to":"nor1"},
    {"from":"nor1","to":"nor2"},
    {"from":"nor2","to":"output1"}
  ]
}
Es decir, un diccionario con un elemento "circuit" que tiene una lista de diccionarios?
Gracias!

**Comment by jmwielandt** [comment]
Hola, 
No, una lista de diccionarios, nada más. Igual que el formato del input.
Actualizaremos el enunciado, muchas gracias.

**Comment by jmwielandt** [comment]
Hola, 
Error mío, el formato de salida debe ser el mismo que el de entrada.

Saludos y ánimo :D
