### ISSUE TITLE
Vivado en Mac

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2343/Syllabus#6]
Hola! 
Para los que tenemos mac, recomiendan correr vivado en una maquina virtual? Hay alguna otra opción?

Gracias!

**Comment by Arcoirisky** [comment]
Solo está la opción de máquina virtual o instalar win/ubuntu :(

**Comment by kmhaller** [comment]
¿podrían explicar bien cómo hacer lo de la máquina virtual?
saludos

**Comment by frvalenzuela** [comment]
Hola @kmhaller !

Puedes revisar este tutorial que puede ser de ayuda [URL](https://www.youtube.com/watch?v=qba342CimdY).

Espero que te sirva !

Saludos!
