### ISSUE TITLE
Duda guardando B en memoria [Placa]

### ISSUE THREAD

**Issue by NoemiCC** [IIC2343/syllabus#60]
Para la Tarea 2 de Placas, cuando queremos guardar el registro B en memoria no sabemos que valor pasarle al Mux, el valor de B o la dirección necesaria. Que deberíamos poner? O no consideramos esa situación?

**Comment by frvalenzuela** [comment]
Hola!

Primero mostremos detenidamente el MUX B del enunciado:

<img src="https://user-images.githubusercontent.com/20147482/56331448-50ad5b00-615a-11e9-9bea-d890a3c16123.png" height="200" width="200">

Esta es la única forma que tenemos de obtener lo que sale del registro B, dado de que no existe otra conexión que salga de él. Por lo que si seleccionamos la dirección de memoria, no habrá forma de tener información de B. Por lo que para esa instrucción **es necesario que seleccionen B**.

¿Y entonces que sucede con la dirección necesaria? Esa es una pregunta que ustedes deben ser capaces de responder. Analicen bien el computador, y vean que sale y que entra en cada componente.

Saludos!
