### ISSUE TITLE
Entrega 2 | Nuevas ponderaciones y opciones de entrega

### ISSUE THREAD

**Issue by baaldana** [IIC2343/Syllabus#60]
Me quedan dudas con las ponderaciones de las entregas con los cambios que se hicieron. En el taller pre entrega 2 sale que las entregas 2 y 3 valen un 25%, y que se borra la mínima entre ellas 2. El tema es que al aplicar eso, la nota de proyecto queda en un 75% y no un 100%, claramente. ¿Es posible hacer las entregas 2 y 3, y borrar la peor? Me deja esa sensación la ponderación que sale en ese taller, pero no sé qué entrega toma el 25% restante.

**Comment by frvalenzuela** [comment]
Hola @baaldana !

Si ! Durante el taller de pre-entrega me hicieron notar ese error, el cual corregí en el taller de entrega 2. Debería ser que ambas valen el 50% y se elimina la peor.

Saludos!

**Comment by mariana-ortega** [comment]
Entonces la entrega 1 vale un 50%? O entendí mal?

**Comment by frvalenzuela** [comment]
Hola @mariana-ortega !

La entrega 1 vale un 15%, la entrega 2 vale un 50%, la entrega 3 vale un 50% y la entrega 4 vale un 35%. Se elimina la peor entre la 2 y la 3.

Saludos!
