### ISSUE TITLE
Subrutinas y Stack

### ISSUE THREAD

**Issue by ceosorio** [IIC2343/Syllabus#60]
Hola!

Quería saber si podemos usar el set de instrucciones de **subrutinas y stack** en las preguntas de la T02, o si hay restricciones dentro de las instrucciones del computador básico.

**Comment by frvalenzuela** [comment]
Hola @ceosorio!

Pueden ocupar todo el set de instrucciones del computador básico visto en clases y en los apuntes del curso.

Saludos!

**Comment by ceosorio** [comment]
@frvalenzuela Ok, gracias! 😄
