### ISSUE TITLE
[Tarea 3] No me crea el repo

### ISSUE THREAD

**Issue by norman123123** [IIC2343/syllabus#60]
Me dice que hay un error y que intente mas tarde cuando intento crear el repositorio. 
De todas formas igual me llega el mail de que se creó el repositorio pero cuando le hago click me tira error 404. 
Despues de tratar unas veces más trde me llegó un mail diciendo que estoy siguiendo a 3 repositorios iguales de tarea 3, pero me tira 404 para todos.

**Comment by FranLucchini** [comment]
Hola,

Efectivamente, no se crearon los repositorios pero igualmente manda los correos. Voy a averiguar un poco más y te aviso.

**Comment by FranLucchini** [comment]
Me puedes mostrar el error que te muestra al tratar de crear el repositorio?

**Comment by norman123123** [comment]
Intenté de nuevo y ahora funciona. El error era que no se podia crear el repositorio, pero era un error manejdo por github, no que se callera la pagina. No puedo recrearlo ahora, pero gracias igual!

**Comment by Geeermy** [comment]
¡Genial! Pero no cierres la _issue_, por si a alguien le pasa lo mismo. :smiley:
