### ISSUE TITLE
Entrega 2 | Data y variables en programas de ejemplo

### ISSUE THREAD

**Issue by diegoheg** [IIC2343/Syllabus#61]
Hola!

Nos surgió la duda de si en los programas entregados en el enunciado, en DATA, el número que está a la derecha del nombre de las variables ¿Es la dirección de memoria inicial o el valor inicial de la variable?
![image](https://user-images.githubusercontent.com/26411041/81234537-f4b4af00-8fc6-11ea-92b8-5491a494d12d.png)

**Comment by frvalenzuela** [comment]
Hola @diegoheg !

El valor inicial de la variable.

Saludos!
