### ISSUE TITLE
Ejecutando emuIIC2343.exe en Linux

### ISSUE THREAD

**Issue by jaromero6** [IIC2343/Syllabus#61]
Hola
Tengo actualmente Ubuntu 18.04 en mi computador y he estado intentando ejecutar el .exe de la tarea con wine. Sin embargo, este ha arrojado varios errores, que he ido solucionando instalando más y más cosas que recomiendan por internet y aún no logro ejecutar el .exe.
Existe una manera de poder ejecutar dicho .exe?
El tutorial que usé para instalarlo está [aquí](https://vitux.com/how-to-install-wine-on-ubuntu/)
Si es de utilidad , muestro alguno de los errores que ocurrieron al ejecutar el programa:
- wine 0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed . Dejó de aparecer cuando instalé mono, pero luego aparecía esto:
![imagen](https://user-images.githubusercontent.com/37157122/65366866-1c096800-dc00-11e9-9959-1e6ec5f2fb69.png)
- Otro error que ocurría era que al instalar mono, me pedía instalar Gecko, luego nuevamente mono y quedaba la instalación en una especie de loop (A veces pasaba esto y otras veces el error de arriba)
De antemano gracias

**Comment by frvalenzuela** [comment]
Hola @jaromero6 !

Por lo que veo del mensaje de error te falta el framework `.net` . Mi recomendación es que veas la issue #42 donde se explica los pasos a seguir.

Respecto a instalar Gecko y mono, debería mostrar el mensaje un par de veces, y luego no más (esto es porque instala una versión la primera vez y luego actualiza dicha versión).

De cualquier forma recomiendo revisar la issue citada anteriormente.

Saludos!

**Comment by jaromero6** [comment]
@frvalenzuela 
Muchas gracias
