### ISSUE TITLE
 [Tarea 3- Parte Práctica] Duda Enunciado, cantidad de latches D en serie

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2343/syllabus#61]
En la tarea dice:

> ...Debería utilizarlos para conectar 16 de estos en serie como se muestra en la figura 5....

Luego en la explicación de la figura 5 se menciona:

> Figura 5: Serie de flip-flops D conectados en serie. En este caso, N = 16.

Mi duda surge en que la figura parte con FF0, si N=16, entonces habría 17 latches D. Por lo que me surge la duda. ¿Son 17 o 16?

**Comment by Geeermy** [comment]
Ups, error básico jeje.

Se actualizará a la brevedad el enunciado, pero en definitiva: son 16 _flip-flops_ conectados (y no _latches_, no sé por qué los mencionas o.o).

¡Éxito! 🦈

**Comment by frvalenzuela** [comment]
Gracias!

Respecto a la mención, en clases el profesor definió el latch D como lo que en la figura 4 de la tarea se describe como Flip-Flop D (ruta: syllabus/Clase/3 - Almacenamiento de Datos.pdf diapositiva 8) mientras que el Flip-Flop sería los componentes que se activan sólo en una transición o flanco, que estarían compuestos por dos latches D (ruta: syllabus/Clase/3 - Almacenamiento de Datos.pdf diapositiva 11).

Yo supongo que el componente serial esta compuesto por latches D, pero ahora con la acotación que mencionas me surgió la duda. ¿Son latches D o flips-flops de flanco de subida los que esta usando el componente serial?

**Comment by Geeermy** [comment]
Usan la misma notación, pero al final se opta por hacer uso de _flip-flops_ con el mismo diagrama dado que en la práctica son los que buscamos ya que se actualizan por cada flanco de subida (como lo expliqué en la ayudantía ayer).

Fíjate en el enunciado que siempre hablamos de ellos como _flip-flops_ y no como _latches_.

¡Saludos! :camel:

**Comment by frvalenzuela** [comment]
Pero entonces cuál sería la diferencia de llamarlo latches y flip flop? 

Por lo que tenía entendido, un flip flop estaba compuesto de dos latches. Como que me produce ruido que se llamen de la misma forma, o estoy mal entendiendo algo ?

**Comment by Arcoirisky** [comment]
@frvalenzuela la diferencia no estaba en el clock? 😱

**Comment by Geeermy** [comment]
La diferencia radica en que los _flip-flops_ están pensados para funcionar con una señal **alternante** (que llamamos _clock_, como dijo @Arcoirisky).

Si le pasaras una señal de esa naturaleza a un _latch_, el resultado no sería el mismo, ya que estos funcionan según el valor determinado de la señal de control y no en **instantes**, que es lo que se busca.

Por favor, revisen las clases (no apuntes) de almacenamiento de datos. Ahí se indica la distinción e incluso se enfatiza en que el diagrama de la caja será el del _flip-flop_ y no del _latch_.

¡Espero que ahora todo esté más claro! Éxito 🐑

**Comment by frvalenzuela** [comment]
Solo para saber si entendí, ¿eso quiere decir que estos componentes deberían llamarse latch?

![image](https://user-images.githubusercontent.com/20147482/44758877-49730780-ab0d-11e8-99d3-9ad875ca810b.png)

Toda mi confusión se genera porque la tarea en la parte práctica tiene como nombre '
Descripción de los componentes de flip-flop' cuando lo que según entiendo de estas respuestas deberían llamarse latches. Perdón por ser reiterativo, pero el enunciado de la tarea me confunde que llame a todo flip-flop, y no se haga mención a los latches.

**Comment by Geeermy** [comment]
No te preocupes por preguntar, para eso estamos. 😄

Sí, tienes razón con lo que dices. Cambiaremos la descripción a _latches_ para no causar más confusiones.

Si quieres corroborar cómo se ve cada uno en formato _flip-flop_:

1. **D**

![imagen](https://user-images.githubusercontent.com/5559611/44759824-93122100-ab12-11e8-9a8e-43bbd5887aa5.png)


2. **RS**

![imagen](https://user-images.githubusercontent.com/5559611/44759805-74ac2580-ab12-11e8-8fdd-b587443b56db.png)

3. **JK:** http://www.play-hookey.com/digital/sequential/jk_nand_flip-flop.html (se veía mal la imagen)

¡Éxito! (ahora sí jeje) 🐷

**Comment by frvalenzuela** [comment]
Ahora si quedo todo claro! Muchas gracias por las respuestas !!!

**Comment by vjmoreno** [comment]
@Geeermy me produce confusión tu último comentario, creo que las imágenes que pusiste corresponden a flip flops maestro-esclavo. Tenía entendido que esto es un latch SR: 

![latch sr](https://user-images.githubusercontent.com/11396859/44929461-828bc180-ad31-11e8-8f44-99396a19fed3.PNG)
Y que esto es un flip-flop SR:

![image](https://user-images.githubusercontent.com/11396859/44929531-b6ff7d80-ad31-11e8-83d1-f98d5d98a267.png)

Donde puedo encontrar información sobre la definición de latch y flip flops? Porque en las diapositivas del curso aparece muy poca y en internet la información difiere mucho.

**Comment by FranLucchini** [comment]
Hola @vjmoreno, tienes razón en lo que dices. Efectivamente es un Flip Flop SR el ejemplo del enunciado. Igualmente, como no especificamos, puedes usar como referencia el flip flop que mostraste o el que mostró Germy.
