### ISSUE TITLE
[Tarea 2] Suma mayor a 16 bits

### ISSUE THREAD

**Issue by BFFV** [IIC2343/Syllabus#62]
Hola,
¿En la P1 de la tarea se deben ignorar los casos en los que el número resultante de la suma no se pueda representar con sólo 2 bytes (entregando los 2 bytes de resultado, aunque estos no representen la verdadera suma de ambos números)?

Ej: 32000 + 32000 = 64000 no se puede representar con 2 bytes en complemento a 2.

**Comment by pgarnham** [comment]
Hola
Lo que tu mencionas es Overflow, y puede ocurrir. Vas a perder información, pero debes entregar el numero resultante de todas maneras para esos casos.

**Comment by BFFV** [comment]
Ok, entonces cuando haya Overflow simplemente mostraré el resultado que dé en los 2 bytes.
Gracias!

**Comment by jaromero6** [comment]
Hola
Me queda una duda en esta parte. Supongamos que mi parte_a es el resultado de sumar la parte menos significativa de los inputs y parte_b es el resultado de sumar la parte más significativa.
Lo que tengo entendido es que si mi parte_b me da overflow lo debo dejar como está, ¿Pero si el overflow fuera en la parte_a (la que es menos significativa) lo debería corregir?. 
Siendo más general con la pregunta, ¿Debo dejar el resultado tal cual como está si me da overflow en cualquiera de los dos bytes?

**Comment by Tngarrido** [comment]
Hola @pgarnham 
aún no me queda claro, lo dejamos así o debemos controlar estos casos levantando excepciones ?
Saludos.

**Comment by pgarnham** [comment]
Hola @jaromero6 @Tngarrido 

La idea de la pregunta es lograr sumar dos números como si tuviéramos 16 bits. Por lo tanto, el resultado de la parte menos significativa si puede repercutir en la más significativa. Espero que esto resuelva sus dudas!
