### ISSUE TITLE
Entrega 2 | Funcionamiento de JUMP en Test

### ISSUE THREAD

**Issue by chris-carstens** [IIC2343/Syllabus#62]
Hola! Me quedó una duda respecto a cómo funcionan los JUMP. En el test 5, por ejemplo, cuando ejecute el **JMP end** de la línea 26, entraría en el label **end** (línea 14),  el cual termina con un **JMP end** también. Por lo que entiendo, ¿Aquí entraría en un loop infinito? o cuál sería el comportamiento correcto. Lo mismo en el caso del test 6.

**Comment by frvalenzuela** [comment]
Hola @chris-carstens !

Si ! Efectivamente entrarían a un loop infinito, lo que en el contexto de esta entrega no es algo incorrecto . La explicación más detallada se dio en la siguiente issue #37 

Si queda alguna duda favor comentar.

Saludos!

**Comment by chris-carstens** [comment]
Gracias! Me quedó claro en la issue.
