### ISSUE TITLE
ISA con errores - Jumps Placa

### ISSUE THREAD

**Issue by Jaluco** [IIC2343/syllabus#62]
Siguen habiendo opcodes repetidos, por favor corregir :)

**Comment by Arcoirisky** [comment]
¿Podrías decirnos cuáles son? Favor de ver el enunciado del syllabus :D

**Comment by frvalenzuela** [comment]
Hola! 

Listo fueron modificados los errores de los opcodes repetidos en la parte de placa, muchas disculpas por las molestias.

Saludos!
