### ISSUE TITLE
Tarea 3 -Programación B - output enunciado

### ISSUE THREAD

**Issue by cilopez** [IIC2343/syllabus#63]
En el resultado de la **Forma - B**  se señala el siguiente output:
```
{"output": {"ffd1": [0, 1, 1, 1, 1, 0], "out1": [0, 1, 1, 1, 1, 0]}}
```
Pero en el input existe una componente `not ` luego del `ffd1` , por lo que enrealidad el output debería ser:
```
{"output": {"ffd1": [0, 1, 1, 1, 1, 0], "out1": [1, 0, 0, 0, 0, 1]}}
```
Es decir debería negarse lo que obtuvo el `ffd1`, creo que el error es que el output que se entrega es correcto según la figura, pero no según la secuencia dada. Por favor corregirme si mi razonamiento está mal 😅

**Comment by Geeermy** [comment]
¡Hola!

Tu razonamiento está mal por lo siguiente: El estado Q de la figura va a ser **igual** a la señal de salida _out1_ ya que la componente **NOT**, si bien niega el estado actual del _flip-flop_ y permite su actualización, la señal _out1_ cambia en conjunto con el estado **Q** (pues es la salida inmediata). Si tuvieras una compuerta **NOT** antes de la salida de la señal _out1_ (_i.e._ después del punto donde se encuentra la bifurcación de la señal hacia _out1_ y hacia la compuerta **NOT** a la entrada del _flip-flop_), el _output_ sería como el segundo punto que señalas.

¡Espero haber sido claro! Éxito 🐜

**Comment by cilopez** [comment]
Entiendo ese razonamiento según **la figura** del enunciado, pero mi duda quizás va al hecho que la figura es distinta al circuito señalado en los comandos del JSON inicial. Esta es la figura que entiendo yo según el JSON entregado:
![circuito](https://user-images.githubusercontent.com/26127105/44758645-1ed47f00-ab0c-11e8-8f8d-6fade7e96339.png)
En este caso los valores siempre serán contrarios entre el `ffd` y el `out`, perdon si mi razonamiento sigue mal 😅

**Comment by Geeermy** [comment]
Oh, ahora entendí el problema.

No había visto esto:
```
{"from": "not1", "to": "out1"}
```
Debería ser:
```
{"from": "ffd1", "gate": "Q", "to": "out1"}
```
¡Gracias por la aclaración! Se corregirá de inmediato en el enunciado.

**Comment by cilopez** [comment]
¡Gracias  @Geeermy !

**Comment by CristobalHV** [comment]
hola, se corrigió en el enunciado del syllabus? de la repo de las tareas?

**Comment by cilopez** [comment]
Cambiaron el del syllabus, el del repo al parecer no

**Comment by jheysen** [comment]
Sólo podemos modificar el del syllabus
