### ISSUE TITLE
[Tarea 2] Duda input y output de bytes (Big endian)

### ISSUE THREAD

**Issue by eitandv** [IIC2343/Syllabus#63]
Hola!
Tengo una duda respecto al orden de los bytes entregados. Cuando se refieren en el codigo base al "Primer byte", este seria el mas significativo o el menos significativo? 

Me explico con un ejemplo familiar: 
num_1_1         120   // Primer byte del primer número                  //
num_1_2         34    // Segundo byte del primer número               //
¿El numero que quieren representar con esta definición de variables seria el 00100010 01111000 (34 120), o el 01111000 00100010 (120 34)?

Luego, al momento de guardar los resultados (digamos, para el caso positivo) en reg_a y reg_b, debo guardar en el reg_a el primer byte o el segundo? 

¡Gracias de antemano!

**Comment by Pipelao** [comment]
La segunda, recuerda que Big endian quiere decir que los bits más significativos se guardan en en la menor dirección de memoria.

**Comment by jmwielandt** [comment]
Hola!

Es tal como indica tu compañero.

Saludos~
