### ISSUE TITLE
[T2 - Programada][Duda Complemento 2][Duda CMP][Duda AND]

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#63]
Hola! aun me quedan dudas de cm se utiliza el complemento de 2. He revisado la issues y parece que no lo entiendo. 
Por ejemplo si tengo el numero 0xF1 este valor cuanto vale (para mi vale -15) por complemento de 2, pero cuanto vale 0x0A (para mi vale 10). 

Ahora bien en la parte de simulación en la iteración numero 5 no logro entender porq el literal sale con -1 si tiene lit = 0x01. 

Tengo una duda de cuando utilizar complemento de dos, por ejemplo si tengo 1... este numero para pasarlo a decimal utilizo complemento de 2 porq el primer digito es 1 y si tengo 01.. utilizo complemento de 2. Creo q no enitendo bien esta parte.

Por otro lado, cuando hacemos una instruccion CMP A, 2 entonces esto me genera mi Z, N , etc y con estos valores vemos lo del jump y eso o no?? Y por otro lado si tenia que A valia 3 y ejecuto CMP luego mi A sigue valiendo 3 o no!

También, tengo una duda con el AND. Si tengo el numero -15 y 10 paso cada numero a binario (-15 = 11100001 y 10 = 00001010) y luego ejecuto and y queda puros 0, esto esta bien??

Muchas gracias!

**Comment by Arcoirisky** [comment]
En primer lugar, te estás equivocando con el complemento a dos. Te sugiero repasarlo, junto con lo que significa el bit más y menos significativo (Por lo que entiendo los estas confundiendo y de ahí caes en la duda)

También échale un vistazo a los apuntes, ahí te explican cómo funcionan las instrucciones y como se trabaja con ellas en una arquitectura específica. 

Pero para que te des una idea, la gracia del Opcode es que al pasar por la Control Unit se generan señales de control, el qué provocan depende de la instrucción que se esté leyendo ¿Cómo sé las señales que libera? Para saberlo primero debes entender bien qué es lo que hace la instrucción y seguir tu arquitectura.

**Comment by shantifabri** [comment]
Tengo la misma duda sobre el complemento de 2. No logro entender porque en el ejemplo de simulación que aparece en el enunciado el literal en la linea 5 es -1 siendo que el hexadecimal que acompaña al opcode es es 0x01 y en el codigo assembly aparece como MOV A,1. Lo mismo para la linea 7 por ejemplo donde el literal  es 0xFF en el binario compilado y aparece el literal -1F.

**Comment by jmwielandt** [comment]
1. El ejemplo de simulación es para ilustrar sintaxis, no se relaciona con los demás ejemplos.

Entonces, en la línea 5 "original" (el source) del ejemplo podemos deducir que la instrucción era 
```assembly
MOV A,-1
```
Pero luego al compilar en algún momento se transforma en
```assembly
MOV A,0xFF
```
Y finalmente en las posiciones 0xA y 0xB del compilado está:
```assembly
0x02 0xFF
```
Pero como estamos cargando un literal en una variable, nada más, al mostrar el literal en la simulación lo interpretamos como `-0x01` pero sin poner el `0x`.

**Comment by shantifabri** [comment]
Entendido, muchas gracias!
