### ISSUE TITLE
Entrega 2 | Bits Adress

### ISSUE THREAD

**Issue by mariana-ortega** [IIC2343/Syllabus#64]
Hola! Tenemos una duda sobre la Figura 1 del enunciado de la entrega 2: 

![image](https://user-images.githubusercontent.com/30672931/81326371-bb804b80-9067-11ea-90cf-9e799a313d09.png)

Del DataOut salen 33 bits, de los cuales 17 se van a la Control Unit. Entendemos que los otros 16 se van hacia el PC, Mux B y RAM que son seleccionados dependiendo de las señales de control que se manden. Pero en realidad el PC y la RAM solo necesitan 12 bits para el address. Eso significa que hay 4 bits que se "pierden"? O sea que no se ocupan? 

Gracias de antemano!
Saludos

**Comment by llloyola** [comment]
Me sumo a la pregunta! No entiendo cuáles son los 12 bits que hay que usar de los 16 bits o qué relación tienen entre sí :(

**Comment by viantirreau** [comment]
Hola!

Creo que da un poco lo mismo. Nosotros usamos los 12 menos significativos de los 16 destinados para el literal, pero tal vez funcionaría igual con los más significativos, siempre que lo pongan así en el Basys.

Saludos!

**Comment by frvalenzuela** [comment]
Hola !

Efectivamente hay 4 bits que no se ocupan pues nuestra RAM solo requiere de 12 bits para dar todas las 4096 direcciones (2**12). Respecto a si fuesen los más o menos significativo, lo hace más sentido son los menos significativos porque así se rellena la memoria desde el inicio. Si ocuparán la convención de los más significativos estarán guardando en memorias muy abajo, lo que puede significar un problema para la entrega 3, donde ocupamos Stack Pointer.

Saludos!
