### ISSUE TITLE
[Tarea 3] Programación parte B

### ISSUE THREAD

**Issue by fdduarte** [IIC2343/syllabus#64]
Hola,
Me estoy complicando un poco tratando de entender el output del programa pensando en el circuito que esta de ejemplo (la figura, no el json). Lo que me pasa es que al ser la señal de control 1, el flip-flop entrega en Q el valor de D, y al haber un not circulando por D, este iría alternando a medida que se recorra el circuito. ¿Algún consejo para afrontar este ejercicio teniendo en cuenta esta complicación?
Muchas gracias.

**Comment by Arcoirisky** [comment]
holaa!! @Geeermy onda, intentando entender el ejemplo: el input es [0,1,0,0,0,1] entonces el ffd1 tiene salida [0,1,1,1,1,0] porque cambia de 0 a 1 en input[1] y de 1 a 0 en input[5]. Eso lo debo decir en mi json porque es la salida del ffd1 y luego, como conecto el ffd1 al out1 digo la salida del out1. ¿no? ignorando el not1 porque no está en ninguna salida directa. 

Si lo anterior es correcto:

1) Si luego agregara ese out1 a un and1 junto a la salida del not1 para llevarlos a un ffp2 sin la conexión del not en su entrada D la salida sería agregarle: 
```
"and1":[0,0,0,0,0,0]
"ffd2":[0,0,0,0,0,0]
```
o solo 
`"ffd2":[0,0,0,0,0,0]`
Pensando que se ignora la salida de la compuerta not :O

2) Si volviera a conectar el ffd1 con otra señal input2 = [0,1,0,1,0,1] la salida del ffd2 sería: [0,0,1,0,1,1]?

Las preguntas son muy de si o no pero quiero estar segura de entender bien lo que pasa :S 
Sorry si pregunto algo nada que ver :C

**Comment by Geeermy** [comment]
¡Hola @Arcoirisky !

¿Cambiaste el _input_ del ejemplo? El caso que pones es correcto, de todas formas. :) Ahora respondo:

1. Sería solo ```"ffd2"``` :-) nos interesan solo salidas directas y estados de _flip-flops_. Ahora, piensa que la gracia de las compuertas ```out``` es que son salidas, entonces no tienen conexiones a otras como en el ejemplo que diste, simplemente habría una conexión directa de ````ffd1``` a ```and1```.

2. No, su salida siempre será ```[0,0,0,0,0,0]``` ya que la salida de la compuerta ```not1``` siempre será la negación del estado de ```ffd1``` ya que se actualizan prácticamente al mismo tiempo, o al menos puedes asumirlo (estoy asumiendo que ```input2``` va directo a la compuerta ```C``` de ```ffd1```).
