### ISSUE TITLE
[T02][Placa] ISA vs Enunciado

### ISSUE THREAD

**Issue by jjaguillon** [IIC2343/syllabus#64]
Estimados, mi consulta:

En la ISA de Placa aparecen operaciones que el enunciado no solicita, por ejemplo que la ALU resuelva OR, pero la ISA si tiene la operación OR.

A que le hacemos caso?

Quedo atento a sus comentarios

Saludos

**Comment by Arcoirisky** [comment]
Hola!
Si sigues leyendo el enunciado se habla de que la ALU soporta 8 operaciones (en las restricciones aparecen 7, donde solo falta el or), las cuales son las que aparecen en la ISA. 

La idea es que soporten **todas** las operaciones de la ISA :D

**Comment by frvalenzuela** [comment]
Hola!

Disculpas por las discrepancias, ahí fue arreglado el enunciado.

Saludos!
