### ISSUE TITLE
Ordenar arreglos en pregunta 3

### ISSUE THREAD

**Issue by tomcan127** [IIC2343/Syllabus#64]
Hola!
En la pregunta 3;
Cuando se llama a la segunda vez a `ordenar_arreglo`, debemos solo ordenar solamente el arreglo 2 o ordenamos ambos arreglos como 1?

**Comment by Arcoirisky** [comment]
Hola~ 

Sip, cuando se llama por segunda vez a la subrutina se debería ordenar el segundo arreglo. 

Es como si todo fuera en orden, cada llamada a “ordenar_arreglo” ordena un arreglo. Y la gracia del cómo se pide el programa en el enunciado es que solo sea necesario llamarla para ordenar arreglos o: 

¿Responde a tu pregunta? 🤔

**Comment by tomcan127** [comment]
@Arcoirisky Muchas Gracias!
