### ISSUE TITLE
[T02 - PLACA] - Manejo de overflow

### ISSUE THREAD

**Issue by javierabao** [IIC2343/syllabus#65]
Hola!
Al hacer operaciones de ADD y SUB en la ALU ¿cómo tenemos que manejar overflow? O sea, entiendo que si el resultado es negativo o cero, hay que especificarlo en los outputs z y n de la ALU, pero en caso de que sea negativo siendo que es la suma de positivos ¿simplemente dejamos que el resultado de n = 1? ¿O qué se espera que hagamos?

Gracias!

**Comment by frvalenzuela** [comment]
Hola Javiera!

Para manejar overflow en operaciones de suma y resta, es necesario que **construyan un circuito que permita detectar la ocurrencia de overflow**. Para esto deben identificar los casos en los que se produce
overflow, ya sea por la adición o sustracción de dos números digamos A, B. Y en caso de ocurrir uno de esos casos activar la señal de overflow.

No es un circuito lo suficientemente complejo como para crear una entidad que sea instanciada dentro de la ALU, aunque si lo desean hacer tampoco hay una restricción que se los impida. Solo mencionar que es relativamente sencillo (no es un circuito con una complejidad como el de una ALU, así que no se asusten).

Como **hint** les puedo dar los casos donde se produce overflow (se asumirá que R es el resultado de la operación):

- Caso 1: A ≥ 0, B ≥ 0, A + B = R < 0
- Caso 2: A < 0, B < 0, A + B = R ≥ 0
- Caso 3: A ≥ 0, B < 0, A − B = R < 0
- Caso 4: A < 0, B ≥ 0, A − B = R ≥ 0

Si ocurre alguno de estos casos significa que existe overflow.

Espero que esto aclare tu duda.

Saludos!

**Comment by javierabao** [comment]
Muchísimas gracias!

**Comment by javierabao** [comment]
Sobre lo mismo, estuve investigando y hay ALUs en internet que tienen un output de overflow, pero en el dibujo del circuito del enunciado, no hay un output de la ALU para esto. ¿En qué parte del circuito tiene que salir la señal o output=1 que indique overflow?
Y en caso de que haya overflow, y por ejemplo, la suma de dos números positivos de negativa ¿el valor del output n tiene que ser 1 igualmente?

**Comment by frvalenzuela** [comment]
Hola!

Disculpa primeramente, porque no es necesario que manejen el overflow en el computador (no existe la instrucción JOV osea que salte en caso de overflow). En caso de existir se manejaría de la forma que te comente arriba, y la señal se añadiría al conjunto registro Status, para luego este ser ocupado en la control unit.

Y respondiendo a la segunda duda. La señal de números negativas sigue dándose, solo que no te interesaría a la hora de ver una instrucción como JOV.

Nuevamente, disculpa mi confusión estaba pensando en el computador básico y no en el primigenio que es que se modela para esta tarea. Edite mi respuesta anterior para que no se tengan dudas al respecto.

Saludos!

**Comment by Jiruiz2** [comment]
Hola,
Lo de que no hay overflow en el computador primigenio aplica de igual manera para la T03?

**Comment by frvalenzuela** [comment]
Hola @Jiruiz2 

En la tarea 3 el computador VonTwelve si tiene que aplicar y manejar la señal de overflow.

Saludo !

**Comment by CmPoblete** [comment]
Como podriamos obtener la señal de overflow sin usar if?

**Comment by frvalenzuela** [comment]
Hola @CmPoblete! 

A través de operaciones lógicas ! (Dígase and - not - or), y con ello una señal O (de overflow) que sea una señal resultado de dichas operaciones.

Saludos !
