### ISSUE TITLE
[Tarea 3] Programación - Flip-Flops en serie

### ISSUE THREAD

**Issue by tomasrivera** [IIC2343/syllabus#65]
Hola, pueden haber flip-flops en serie en la descripción de la máquina?

Pregunto porque se usa "gate" para las puertas de entrada y salida del JSON.

Y si hubiera un elemento que no está conectado a un flip-flop, cómo estaría representado en el JSON?

**Comment by tomasrivera** [comment]
1. Cómo se escribiría la conexión entre la salida ``Q`` de ``ffd1`` a la entrada ``D`` de ``ffd2``

**Comment by Geeermy** [comment]
¡Hola! Actualicé mi respuesta. Ahora **no se hará** dado que complejiza de sobremanera la implementación.

Ahora puedes tener dos opciones:

1. Dos _flip-flops_ que comparten una señal de control:

```
{"from": "input1", "to": "ffd1", "gate": "C"}
{"from": "input1", "to": "ffd2", "gate": "C"}
```

2. Dos _flip-flops_ con señales de control distintas:

```
{"from": "input1", "to": "ffd1", "gate": "C"}
{"from": "input2", "to": "ffd2", "gate": "C"}
```

En resumen, **ningún _flip-flop_ dependerá de la salida de otro.**

¡Éxito! (ahora sí) 🐅

**Comment by tomasrivera** [comment]
¡Gracias!

**Comment by Geeermy** [comment]
Edité de nuevo la respuesta: La dependencia hace **énfasis** en la compuerta "C", no necesariamente el dato (porque ese caso es fácil de manejar, el mismo ejemplo del enunciado lo abarca).

**Comment by miguelramirezv** [comment]
Hola! El ejercicio lo abarca no directamente de gate a gate, si no que con un NOT entremedio. Hay que hacer el caso directo? Si es que sí, cómo se escribiría la conexión entre la salida Q de ffd1 a la entrada D de ffd2?

**Comment by tomasrivera** [comment]
Lo mismo que arriba, faltaría poner un "gate_in" / "gate_out" para poder hacerlo o simplemente no poner las "gate" = Q porque son redundantes

**Comment by fdduarte** [comment]
Aprovechando este tema,
¿Como se conectan los and, xor y or? (dos inputs).
Me cuelgo del tema porque creí que podrían usar `gates` también.

**Comment by Geeermy** [comment]
¡Hola!

@tomasrivera @miguelramirezv Tienen toda la razón. Para efectos prácticos, **dos _flip-flops_ nunca se conectarán de forma directa**. Espero que esto les solucione la vida. :smiley: (edité todas mis respuestas para no causar confusión).

**Comment by Geeermy** [comment]
@fdduarte

```
...
{"from": "input1", "to": "and1"},
{"from": "input2", "to": "and1"},
{"from": "and1", "to": ...},
...
```

**Comment by Geeermy** [comment]
Y sí, pueden asumir que a las compuertas ```and, or, xor``` solo le llegan dos inputs, salvo a ```not``` que le llega uno.
