### ISSUE TITLE
Entrega 2 | Duda acerca arquitectura

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2343/Syllabus#65]
Hola , tengo una duda acerca de la instrucción inc A , dada la arquitectura mostrada en el esquema es imposible realizar está operación en un ciclo, ya que A debe ir al registro B y despues A tomar el valor 1 para sumar , o viceversa 1 ir al registro B desde A y luego A tomar el valor de su registro y sumarse.

Por lo que me ocurre un problema con esta instrucción en la señal selA ya que cómo le digo que cuando salga este opcode tome dos valores distintos :( , si me pueden ayudar porfis.

**Comment by nicoparraguez** [comment]
Se me ocurrió una solución y es que el valor 1 venga desde el literal y se lo de directamente a B es así?

**Comment by frvalenzuela** [comment]
Hola @nicoparraguez ! 

Recomiendo revisar la issue #35 , y sobre tu solución, si le das el resultado a B no incrementas A, a menos que hayas querido decir otra cosa

Saludos!
