### ISSUE TITLE
Duda Saltos Condicionales

### ISSUE THREAD

**Issue by Snorlax8** [IIC2343/Syllabus#65]
Estoy probando un trozo de código y tengo lo siguiente:
![WhatsApp Image 2019-09-23 at 13 18 07](https://user-images.githubusercontent.com/14048037/65443604-cf42ae80-de04-11e9-9756-0e2106c6980f.jpeg)

Lo que yo entiendo es que el JGT hace la comparación A>B, que en este caso no se cumple. Sin embargo, al correr el código este se queda pegado en el ciclo, volviendo a inicio una y otra vez:

![WhatsApp Image 2019-09-23 at 13 11 48](https://user-images.githubusercontent.com/14048037/65443798-221c6600-de05-11e9-81b0-849fc780a8c6.jpeg)

Después pensé que se podría tratar de que la comparación se daba al revés de cómo pensaba, pero eso no coincide con otro código que creé:

![image](https://user-images.githubusercontent.com/14048037/65444920-76c0e080-de07-11e9-8061-f54840227644.png)

Con esos números (A = 0, B = 2), obtengo los siguientes valores para los registros:
![image](https://user-images.githubusercontent.com/14048037/65444980-9ce68080-de07-11e9-8afd-ebd3d54fb6ee.png)

Eso significa que se corrió la línea MOV A, 27 y entonces se entró a la línea "mayor", Sin embargo, al hacer A = 3 y B = 2, obtengo exactamente el mismo resultado. Por lo tanto, no puedo inferir en qué orden se realiza la comparación realmente (A >B o B > A). Lo único que se me ocurre es que los saltos condicionales en mi código no están teniendo efecto, por lo que entro a la línea "mayor" sí o sí. El problema es que no tengo idea de por qué pasa esto.

Se agradece cualquier ayuda :D!

PS: en los ejemplos de Assembly subidos al repositorio no vi ninguna instancia de JLT y JGT, por lo que no tenía una referencia en código real.

**Comment by Arcoirisky** [comment]
Quizas estás confundiendo lo que hacen los Jumps condicionales, ya que no comparan nada.

Lo que hacen y como se muestra en la ISA, es revisar la salida del registro status de la ALU. 

Algo completamente diferente a lo que dices o: 

Dale unas vueltas al asunto y sigue intentando.

**Comment by Snorlax8** [comment]
Ahhh, perdón, es que me salté un paso. Por un segundo me confundí y estaba pensando en que la operación de comparar (CMP A,B) era parte de los  JGT y JLT, pero lo que en realidad ocurre es que la comparación es una operación aparte. Mi código se arregla cuando agrego CMP (A,B) antes de los saltos condicionales. Muchas gracias!
