### ISSUE TITLE
Duda falta de registros [T02 Programada]

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2343/syllabus#66]
Hola , tengo una duda acerca de que hacer si tengo que hacer un salto a una instrucción que se llama caso xx , y el programa entero hacia arriba al escribirlo en binario sobrepasa las 128 lineas no habría forma de decir 0xXX en la memoria ya que el programa no lo soportaría.

Lo otro, es que hacer en casos de overflow con mis números por que si acepto enteros negativos puedo escribir -128 al 127 , que pasa si una variable es 300 según enunciado el programa no se debe parar pero todo el desarrollo estaría malo ya que al trabajar la variable no tendría su valor real.

De antemano, muchas gracias.

**Comment by jmwielandt** [comment]
Sobre lo primero, en la issue #29 indico:
> Por lo mismo, los tamaños de ambas memorias solo admiten 256 bytes de almacenamiento. Si un programa al compilarse acaba ocupando un espacio mayor, queda a su criterio el cómo lo manejan, pero no deben pasarse. La memoria de datos también se ve restringida a ese tamaño máximo.

Sobre lo segundo, piensa que en la isa existe la instrucción `JCR`, por lo que si tienes:
```assembly
MOV A,0xFF
MOV B,0x02
ADD A,B
```
Tu valor de C en el registro status será 1 y en A quedará guardado `0x01`.

**Comment by llloyola** [comment]
Podrían explicar o hacer algún _approach_ de cómo trabajar con los valores **Z**, **N**, **C** y **V** que aparecen en la columna **Condición** en (casi) todas filas de la tabla **Saltos**? Mí no estar entendiendo 😢 
Gracias de antemano ❤️

**Comment by Arcoirisky** [comment]
Claro! 
Z,N,C y V son salidas de la ALU (a parte de la salida normal con el resultado)

Z es para Zero, es decir que la salida de la ALU es o no cero y así mismo con Negative, Carry y oVerfload. 

Para más detalles ir a los apuntes de programabilidad con saltos :D

**Comment by llloyola** [comment]
Mmm... Dándole más vueltas, creo entender la relevancia de éstos.
Sólo para salir de dudas... Vendrían a ser relevantes sólo para `basic_simulator.py`, cierto? 😮 Si juegan algún papel importante en `basic_assembler.py` o `basic_disassembler.py`, no lo estoy entendiendo 😞

**Comment by Arcoirisky** [comment]
Básicamente, sip
