### ISSUE TITLE
Instrucciones y señales de control

### ISSUE THREAD

**Issue by mvgil** [IIC2343/Syllabus#66]
Hola!
Viendo las señales de control de la instrucción: 
**MOV (B),A**, vi que la señal **La = 1**, no entiendo por qué es necesario cargar A + 0 en el registro A, si no cambia el valor. 
Sé que MOV (B),A equivale a Mem[B] = A, y que como el resultado de la ALU se conecta con el MUX data in, la señal del data in debe ser A ( A +0 ), pero no entiendo por qué se carga el resultado de la operación de la ALU  A + 0 en el Reg A.

Muchas gracias!

**Comment by Allmoz** [comment]
Es un typo, es inofensivo pero no tiene ni una razón de ser. 
¡Gracias! Queda reparado.
