### ISSUE TITLE
Tema | Duda instruccion assembly jeq y similares

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2343/Syllabus#66]
Hola, tengo una duda acerca de que valor toma la señal selA (la que va al mux de A con opciones que tome 1,0,regA) cuando se hacen instrucciones del tipo salto.
Por ejemplo JEQ necesita el valor del status z=1 pero no entiendo si el muxA toma el valor del registro A para compararar y que ver el status en un ciclo o esta información ya viene y el muxA no toma ningun valor ya que el z es obtenido de un ciclo anterior.

De antemano muchas gracias.

**Comment by jmwielandt** [comment]
Hola,

Las instrucciones de salto no comparan ningún registro. Lo que hace la control unit cunado le llega el opcode de algún jump condicional es revisar las señales N, Z, C y V del registro status que quedaron de la instrucción anterior y en base a eso, saltará o no.

Para todo el resto de señales, puedes setearlas en 0 y actuarán como un NOP y así no rompes nada.
