### ISSUE TITLE
[Tarea 3] Programacion parte A, valor inicial de Q

### ISSUE THREAD

**Issue by nmaturana97** [IIC2343/syllabus#66]
Hola,
Debemos asumir que Q se inicia en 0?

**Comment by Geeermy** [comment]
¡Hola!

**Sí.**

¡Éxito! 🐹

**Comment by eiherrera** [comment]
Hola, creo que estoy entendiendo mal el enunciado y la pregunta pero, ¿no se supone que para la parte A no importan los inputs ni tampoco los outputs, si no una descripción de una máquina combinacional que se comporte igual a la secuencial original?

**Comment by Geeermy** [comment]
¡Hola! Eso mismo es. :)

No me había fijado que esta _issue_ era de la forma A jeje. Pero sí, en su caso es irrelevante el valor de partida de Q, les interesa más qué pasa en la máquina según su valor.

¡Éxito! :duck:

**Comment by miguelramirezv** [comment]
Para la parte B debemos asumir que siempre Q se inicia con 0 en todos los ffd?

**Comment by Geeermy** [comment]
@miguelramirezv **Sí**.
