### ISSUE TITLE
[Tarea 3] Programacion Parte A: duda general

### ISSUE THREAD

**Issue by nmaturana97** [IIC2343/syllabus#67]
Hola, la verdad me entró una duda general sobre lo que nos están pidiendo y como lograrlo.
Una maquina secuencial recibe un input que se representa con un vector, los cuales son cada iteracion.
Para pasarlo a combinacional debemos descomponer este input? Me refiero a que si tengo un input de largo 4, debere crear input1, input2, input3 e input4?
Si tengo mas de 2 inputs, estos inputs se corren de manera en que cada componente representa el valor que toma el input en cada iteracion?

Además, quería saber si podian dar un ejemplo del output que deberia dar el ejemplo (o uno de los output posibles) que nos ponen en el enunciado, para hacerme una idea de lo que nos estan pidiendo.

Gracias de antemano

**Comment by Geeermy** [comment]
¡Hola!

Como **se menciona en el enunciado**, a ustedes no les interesa el atributo _input_ del JSON.

Lo que deben hacer es retornar un circuito equivalente que en vez de ser secuencial, sea combinacional, _i.e._ su circuito de _output_ **no puede hacer uso de _flip-flops_ para almacenar estados**. Entonces, ¿cómo generas un circuito equivalente que no haga uso de estos y que me retorne el mismo resultado para una misma combinación de señales de _input_ y los estados de mi máquina original? Ese **cómo** es lo que debe hacer su tarea.

No te doy un ejemplo de _output_ ya que es simplemente un JSON de la misma estructura, solo que sin _flip-flops-.

¡Éxito! :panda_face:

**Comment by pdesolminihac** [comment]
Hola, 
¿Solo nos debemos preocupar de flip-flops, o va a haber algún otro tipo de sistema secuencial que también hay que cambiar para hacer combinatorial?

**Comment by Geeermy** [comment]
Solo _flip-flops_. :smile:

**Comment by Geeermy** [comment]
Ah, pero ojo que puede haber más de uno. A lo que me refiero es que no habrán otros tipos de componentes (como _latches_ o _flip-flops_ de otros tipos).

**Comment by nmaturana97** [comment]
podemos utilizar nand? o solamente podemos usar not, or, xor y and?

**Comment by pdesolminihac** [comment]
¿Y los estados iniciales de la maquina son incluidos en el input?

**Comment by Geeermy** [comment]
@nmaturana97 Pueden hacer uso de ellos (usando la nomenclatura _nand{i}_, pero en el _input_ no les pasaremos máquinas que hagan uso de esa compuerta.

@pdesolminihac Forma A, no lo necesitan. Forma B, pueden asumir que parte en 0.

Saludoss :bug:

**Comment by JuanGalilea** [comment]
> Ah, pero ojo que puede haber más de uno. A lo que me refiero es que no habrán otros tipos de componentes (como latches o flip-flops de otros tipos).

Entonces solo habra un solo tipo de flip-flop en el input? cual es ese? (supongo que tipo D como en el ejemplo)

Por lo que te entendí tenemos que hacer un circuito "secuencial" que se comporte de la misma forma que el que nos entregan, pero sin utilizar ningun flip-flop o latch (osea ningun componente que hemos visto de circuitos secuenciales). Entendi mal? o esta bien lo que dije?

**Comment by Geeermy** [comment]
1. Sí, en el enunciado, en la parte de convención se explica toda esa parte.
2. Claro, pero eso **no es un circuito secuencial**, es combinacional porque depende **solo** de la combinación de señales de entrada (y tienes que encontrar la forma de incluir los estados de los _flip-flops_ en esa combinación, si es que estos influyen en el _output_ del circuito).

¡Salu100000! 🐍
