### ISSUE TITLE
Entrega 2

### ISSUE THREAD

**Issue by rfenzo** [IIC2343/syllabus#67]
El tamaño de los buses señalados en el diagrama del enunciado dice que al control unit entran 17 señales y solo salen 11, lo cual no me hace mucho sentido a primera vista pues estaríamos haciendo algo contrario a lo que hacen los opcode que es reducir el numero necesario de bits para representar todas las instrucciones en la ROM. Por favor haganme ver en qué me equivoco, gracias.

**Comment by Hernan4444** [comment]
@rfenzo efectivamente son 17, esto es porque la rom que le entregamos saca una señal de 33 bits, y por ello 16 son de literal y el resto es de opcode. Para el proyecto ustedes usaran muchos menos bits por lo que los demás serán solo ceros.

Saludos!!!
