### ISSUE TITLE
Archivo .bit - Placa

### ISSUE THREAD

**Issue by leolivares** [IIC2343/syllabus#67]
Hola.
Es necesario subir el archivo .bit para la entrega como dice el enunciado? O este lo generarán al momento de corregir, con instrucciones en la Rom?

**Comment by frvalenzuela** [comment]
Hola Leonardo!

Si, es necesario que suban el .bit para asegurarnos de que tu código no tiene problemas para ser compilado e importado en la placa.

Adicional a eso, también generamos otros .bit con instrucciones en la Rom.

Saludos!
