### ISSUE TITLE
Entrega 2 | Posibilidad de dar más plazo.

### ISSUE THREAD

**Issue by gatochico** [IIC2343/Syllabus#67]
Hola! Se que es una petición un poco encima de la fecha límite, pero quería preguntar por la posibilidad de dar más plazo para esta entrega.

Como venimos saliendo de la semana de ajuste (la cual fue utilizada para ponerse al día), probablemente a varios nos ocurrió que en esta semana se juntaron muchas evaluaciones que estaban planeadas para la semana pasada o esta. Por otro lado, recibimos el _feedback_ de la E1 ayer, y nos encontramos con arreglos inesperados a realizar para esta entrega en un corto plazo de tiempo, o seguiremos teniendo descuentos.

Finalmente, sé que existe la posibilidad de eliminar la peor entrega entre la 2 y la 3, pero de todas formas queríamos entregar nuestra mejor propuesta de la entrega 2, en vez de no alcanzar a terminarla a tiempo y depender únicamente de la entrega 3.

Saludos!

**Comment by mariana-ortega** [comment]
Hola,

Estoy de acuerdo. En vez de estar haciendo bien esta entrega muchos grupos la están botando porque tienen muchos trabajos y evaluaciones esta semana. Si bien se puede eliminar, esto solo provocará que se acumule más trabajo para la próxima entrega, obteniendo peores resultados. Además, dada la naturaleza acumulativa de las entregas, me parece muy complicado haber entregado recién el feedback de la Entrega 1 ayer en la noche y creo que se debe considerar que en la semana de pausa estuvimos poniéndonos al día con todos los ramos y preparando la prueba de este ramo que se entregó este martes.
Muchas gracias de antemano por su tiempo.

Saludos,
Mariana

**Comment by raespinoza4** [comment]
+1 a mis compañeros, también con mi grupo recibimos ayer el feedback de la E1 y nos enteramos que hicimos varias cosas mal (las cuales pensamos que estaban bien y por ende que nuestra base para la E2 era correcta) Discutimos que aparte de terminar la E2 debíamos corregir en muy poco tiempo lo que habíamos hecho mal en la E1 llevándonos a tomar la decisión de botar la entrega :(

**Comment by vaperez5** [comment]
Me sumo a la petición de mis compañeros, a nuestro grupo se les juntaron las evaluaciones de esta semana y las de la semana pasada que fueron corridas para esta. Nosotros como grupo deseamos aprender y lograr desarrollar nuestro proyecto, y no quedarnos con vacíos que nos costará rellenar más adelante en el curso, por lo que por más que se pueda, no queremos botar esta entrega. Se que es muy encima, pero ojala lo puedan considerar.

**Comment by frvalenzuela** [comment]
Estimad@s.

Se envío un anuncio al respecto hace unos minutos respecto al tópico en cuestión.

Saludos!
