### ISSUE TITLE
Overflow negativo

### ISSUE THREAD

**Issue by jaromero6** [IIC2343/Syllabus#67]
Hola!
Me surge una duda, en la parte 1 de la tarea . Si al sumar los dos bytes menos significativos acorde  la sección 3.4 de los apuntes 5- Saltos y Subrutinas pueden ocurrir los siguientes casos:

- La suma excede el máximo número permitido acorde a los bytes, como resultado se genera un número negativo.
- La suma es menor al menor número permitido, como resultado se tendría un número positivo.

Mi duda es, si al detectar que ocurrió overflow, debería sumar o restar un carry dependiendo del resultado. Es decir si el número que queda tras el overflow es negativo, entonces sumar 1 a la suma de más significativo (Ya que como es negativo implica que la suma fue positiva), o bien al revés, el número tras el overflow fue postivo, lo que implica que la suma real era menor a 0, por lo que tendría que restar un carry (Asumiendo que el número es negativo).
Por ejemplo 120 + 30 -> Genera un carry positivo a la siguiente suma. En cambio -120 - 30 debería generar un carry negativo o se deja positivo no más ?

**Comment by pgarnham** [comment]
Hola, como menciono en la Issue #62 , la idea es que la suma ocurra como si tuviéramos los 16 bits. Te recomiendo hacer el ejercicio en papel, y luego determines que correcciones debes hacer para obtener el resultado correcto!
Animo!
