### ISSUE TITLE
lenguaje pseudocódigo

### ISSUE THREAD

**Issue by dhvasquez** [IIC2343/Syllabus#68]
No entiendo esta parte ¿Debe haber una representación del algoritmo en cualquier lenguaje de nivel superior a Assembly? (ej. Python), o debe ser uno en particular?

**Comment by pgarnham** [comment]
Hola
La idea es que expliques tu algoritmo, y entendamos que fue lo que hiciste (o intentaste hacer) para resolver cada problema. Si usar elementos de python te ayuda, está bien. No pedimos un lenguaje específico para esto.

**Comment by dhvasquez** [comment]
Entonces basta con explicar los pasos que sigue mi código?

**Comment by jmwielandt** [comment]
Hola!

No, el pseudocódigo es más sutil que "explicar tu código". Es una forma de escribir algoritmos sin utilizar la sintaxis de ningún lenguaje de programación en específico.

Puedes mirar el [artículo de wikipedia en español](https://es.wikipedia.org/wiki/Pseudoc%C3%B3digo), pone varios ejemplos de pseudocódigo siguiendo estilos de varios lenguajes.

<details>
<summary>Este es un ejemplo de EDD del semestre pasado</summary>
<br>

![image](https://user-images.githubusercontent.com/37153467/65646742-71fc5800-dfd2-11e9-815c-3531809c0056.png)

</details>


<details>
<summary>Y este es un ejemplo de autómatas de este semestre</summary>
<br>

![image](https://user-images.githubusercontent.com/37153467/65646808-b5ef5d00-dfd2-11e9-9e25-ea8f7f11f1f2.png)

</details>

**Disclaimer: NO usen una sintaxis estilo assembler. Eso ya no es pseudocódigo.**

Saludos~
