### ISSUE TITLE
"Menos/mas significativos"

### ISSUE THREAD

**Issue by elramirezv123** [IIC2343/syllabus#68]
Hola,

Leyendo descubrimos que cuando un vector dice ej: 7 downto 0 significa que se usa la convencion "little endian". Esto nos genera la siguiente duda:

Vector = std_logic_vector(7 downto 0)
Vector <= "12345678"

¿¿ Vector(0) seria 8 o 1 ???
Y cuando hagamos por ejemplo, vector(7 downto 5) ¿nos retornaria "123"?
Y en el mismo caso, el numero mas significativo seria Vector(0) = 8 ???
Llevado al caso de la tarea, los 17 bits mas significativos del vector del rom (32 downto 0) seria rom(16 downto 0) ??? Luego, no debemos dar vuelta este vector para compararlo con el opcode cierto?

Se que son muchas preguntas pero el uso de little endian nos complicó la vida (soy un noobazo)

**Comment by frvalenzuela** [comment]
Hola!

Solo por si acaso, std_logic_vector es una arreglo (en palabras python una lista) de std_logic, por lo que solo debería contener ceros y unos (lo más probable es que lo hayas hecho para ejemplificar, pero lo menciono de cualquier forma para evitar cualquier confusión futura).

Ahora respondiendo a tus preguntas:

1. Vector(0) sería '8'.
2. En el ejemplo vector(7 downto 5) debería representar "123". Estas en lo correcto.
3. En el mismo caso, el numero mas significativo seria Vector(7) = '1'. No cero.
4. Los 17 bits más significativos del vector rom son rom(32 downto 16). Luego no es necesario dar vuelta el vector.

Ahora explicando que se refiere la notación la convención "little endian", se refiere a que lo menos significativo se guarda primero en memoria. Es por eso que cuando vemos el caso de Vector(0),  siendo cero la primera dirección de memoria del arreglo, es decir va guardado lo menos significativo que en este caso sería 8. Y siguiente la mismo lógica Vector(7) hace referencia a lo último guardado en el arreglo, osea lo más significativo, por tanto tiene que estar guardado el valor '1'.

Espero que con eso se simplifique un poco su vida.

Saludos!
