### ISSUE TITLE
[Tarea 3] Programacion parte B: Conexiones entre flip-flops

### ISSUE THREAD

**Issue by haarenas** [IIC2343/syllabus#68]
Tengo a una duda respecto a los archivos json con los que se probaran las simulaciones. Es correcto asumir que debemos construir CUALQUIER tipo de componente a partir de las secuencias entregadas? (No necesariamente la de la figura). 
De ser ese el caso, una compuerta D de un flip-flop puede estar conectada a otra compuerta D de otro flip-flop (por poner un ejemplo)?

**Comment by Geeermy** [comment]
1. ¿Construir qué exactamente? Si les pedimos simular en la parte B. :eyes:

2. Sí, lo que no puede pasar es que el _output_ de un _flip-flop_ vaya a la compuerta "C" de otro.

**Comment by fdduarte** [comment]
Tengo una duda respecto a eso.
Si se quiere conectar dos flip-flops en el archivo json se escribiría dos veces la key `gate`, es decir
`{from: ffdn, gate: x, to: ffdk, gate: j}`
¿Que se haría en un caso así?

**Comment by Geeermy** [comment]
**Actualización"** El punto 2. ya no corre. Ver #65
