### ISSUE TITLE
Entrega 2 | Instrucciones de un operando sobre variables

### ISSUE THREAD

**Issue by diegoheg** [IIC2343/Syllabus#68]
Hola! Nos surgió la duda de si para las instrucciones de un operando que involucran una variable en RAM (p.ej. INC (var1) ) requieren de uno o más ciclos, esto debido a que no estamos seguros de si la RAM siempre está sacando como output lo que efectivamente está en Address (independientemente de si estamos en un flanco de subida o del valor de W)

**Comment by frvalenzuela** [comment]
Hola @diegoheg !

El flanco de subida solo es relevante a la hora de grabar datos en memoria, para desplegar datos de la misma con solo indicar el addres dará en un mismo ciclo su resultado (de forma similar a como dando una señal de selector en un MUX este da la opción en el mismo ciclo). Así que todas las instrucciones de esta entrega que involucren a la memoria se realizan en un solo ciclo.

Saludos!
