### ISSUE TITLE
[Tarea 2] Pregunta 1

### ISSUE THREAD

**Issue by csolguin** [IIC2343/Syllabus#69]
En la pregunta 1 me ha entrado una duda con respecto a su operación, ¿Cuál de los 2 métodos sería el correcto?

&nbsp;&nbsp;&nbsp;&nbsp;1.  Sumar los 8 bit del segundo byte del número 1 (numero_1_2) y número 2 (numero_2_2) SIN COMPLEMENTO A 2, es decir, el bit más significativo no corresponde a uno de signo.

&nbsp;&nbsp;&nbsp;&nbsp;2.  Sumar los numero_1_2 y numero_2_2 con complemento a 2

Por mi parte he hecho la primera, ya que es lo más lógico si se trata finalmente de un número de 16 bits, pero no sé si es lo correcto.
De antemano muchas gracias.

**Comment by pgarnham** [comment]
"Hola
En la Issue #62 se habla acerca de este tema. No puedo darte más que esto, porque efectivamente este es el problema que queremos que resuelvan en esta pregunta. Te recomiendo revisar los apuntes y hacer cálculos en papel para verificar que estés haciendo lo correcto.
Animo!
