### ISSUE TITLE
[Tarea 3 / Programado Parte A] Duda con el enunciado

### ISSUE THREAD

**Issue by CristobalHV** [IIC2343/syllabus#69]
Hola, no entiendo a que se refieren exactamente con "Escriba un programa que, dada la descripción de una máquina secuencial, retorne la descripción de una máquina combinatorial de salidas equivalentes"

¿Qué es la descripción de la máquina, sólo los inputs y los outputs? ¿o también la lógica que hay detrás de las conexiones entre inputs y outputs? Además, ¿a qué se refiere exactamente con "salidas equivalentes", podrían detallar esto?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

No solo _inputs_ y _outputs_, sino que también la descripción de cómo se conectan todas las compuertas entre sí. En el enunciado de la tarea 2 hay un ejemplo de un _half-adder_ que puedes revisar.

Con "salidas equivalentes" queremos decir que para una misma combinación de señales de entrada, tanto la máquina secuencial como tu equivalencia combinacional otorguen el mismo resultado. Evidentemente, ya no contendrá _flip-flops_, por lo que debes ver cómo incluir cada estado Q de estos como una señal de forma que tu nuevo circuito entregue el mismo resultado de la máquina secuencial.

¡Éxito!

**Comment by Vicentevialpaul** [comment]
Hola! con respecto al input, tengo entendido que se tiene una combinación de valores, donde cada valor es ingresado en cada iteración. En ese caso, me parece que la máquina combinacional tendría que guardar el estado anterior de la máquina para determinar el valor del próximo output, pero eso ya no estaría actuando como una máquina combinacional.   Estoy confundido en el tema de como se ingresan los inputs, para luego verificar que las dos máquinas tengan los mismos outputs, ¿como seria el funcionamiento de este tema?

**Comment by Geeermy** [comment]
**Como dice el enunciado**, a ustedes **no les interesa el atributo "_input_" del JSON de entrada.** Les interesa hacer un circuito combinacional tal que para cada **combinación de señales de entrada** de el mismo resultado que su versión secuencial. Entendiendo eso, ya no te preocupas del estado anterior.

Salu10 (Salu2 en binario) :beetle:

**Comment by Vicentevialpaul** [comment]
Eso es lo que no entiendo bien,como esta formada la combinación de señales de entradas? tiene inputs de una sola iteracion? 
Muchas gracias!

**Comment by Geeermy** [comment]
Claro, solo que tienes que pensar en las combinaciones de valores de entrada y estados Q. De esta forma, te preguntas a ti mismo: ¿Qué _output_ resulta de esta combinación en específico? ¿Y qué obtengo para cada combinación de _input_ y estados? **¿Y cómo replico esto en un circuito combinacional?**

Esas son las preguntas que debes hacerte. :smile:

**Comment by Vicentevialpaul** [comment]
Ya buenísimo, entiendo entonces que se entrega la información del estado de cada Q correspondiente a cada flipflop en la combinación de señales de entrada? 
Gracias!

**Comment by Geeermy** [comment]
@Vicentevialpaul Claro, pero ojo que no siempre va a influir en el resultado del _output_, es parte de lo que debe considerar su programa.

@JuanGalilea Recuerda que estamos en la **parte A**, así que sería lo primero que dices (pero solo retornas el circuito generado según el formato expuesto en el enunciado).

¡Salu100! :bird:

**Comment by Geeermy** [comment]
1. Exactamente. Como dice **el enunciado**, solo _flip-flops_ D. :)

2. Si entendí bien, sería más que todo el primer caso. Nos importa por sobre todo que el circuito secuencial y combinacional tengan tablas de verdad equivalentes para estados Q dados (pensandos en formato _input_ para la combinacional), como dijiste al principio de tu comentario. Extender el paso de los _flip-flops_ al resto de los componentes **está mal si en el circuito original no estaban conectados.**

¡Éxito! 🦏
