### ISSUE TITLE
Port direction mismatch 

### ISSUE THREAD

**Issue by radelamaza** [IIC2343/syllabus#69]
![image](https://user-images.githubusercontent.com/37149999/56395254-e94de480-6207-11e9-83e7-109d748065c4.png)

Al compilar (Run Synthesis), nos aparece el error de la imagen, a que se debe esto?

**Comment by Taeval** [comment]
En la foto se ve el lugar donde ocurre el error. Suponemos que el problema tiene que ver con una no correspondencia output/signal, pero no encontramos mucha información.

La entidad NOT_GATE fue declarada con el output "na" y en la foto, "na" pasa a "n1" que es una señal que es input de otro componente.

**Comment by Taeval** [comment]
Encontramos que el componente NOT_GATE en el módulo de la foto tenía "na" como "in" y no como "out". Creemos que ese es el problema.

**Comment by Arcoirisky** [comment]
¿Puedes mostrar la componente Not_gate? La definición e instancia en el módulo de la foto

**Comment by frvalenzuela** [comment]
Hola!

Dicho error generalmente ocurre cuando se conecta trata un input como si fuese un output o viceversa. Por lo que dice @Taeval puede que ya hayan encontrado el problema, me comentan si se soluciona. De no  hacer lo mencionado por @Arcoirisky 

Saludos!

**Comment by Taeval** [comment]
![image](https://user-images.githubusercontent.com/37159657/56396022-0932d780-620b-11e9-898a-9099cbd27dba.png)

Era lo que mencioné, el "out" estaba escrito como "in" en la foto.

**Comment by Arcoirisky** [comment]
Ah lskdks entonces lo solucionaron (y)
