### ISSUE TITLE
Administrativa | Cálculo de nota en tareas

### ISSUE THREAD

**Issue by nbnavarro** [IIC2343/Syllabus#69]
Hola,

¿Cómo se calcula la nota final de tareas? en la t1 decía que es 70% práctico y 30% escrito, pero no entiendo si esa ponderación se hace para cada tarea (y al final se promedian las tareas) o es algo que se hace al final teniendo las tareas acumuladas. 
Por ejemplo, si la t1 tuvo 4 escritas y la t2 tiene 3 escritas, el promedio de esas 7 corresponde al 30% de la nota final de tareas?

Gracias de antemano!

**Comment by jmwielandt** [comment]
Hola,

La NT (nota de tareas) se calcula como 70% PP + 30% PT, donde PP es la nota de las preguntas programadas y PT es la nota de las preguntas escritas/teóricas.

Ahora, para cualquiera de esas dos, lo que haremos será sacar el 70% mejor de las preguntas (por ejemplo, si al final del semestre son 10 preguntas, nos quedamos con las 7 mejores) y se saca el promedio entre ellas.

**Comment by bpardobravo** [comment]
Hola, considerando que al final hay 9 preguntas programadas (6 T1 + 3 T2), El 70% mejor que se toma son las mejores 6 o 7 preguntas?

**Comment by jmwielandt** [comment]
Preguntas de programación -> 7
Preguntas teóricas -> 5

**Comment by isiguelfand** [comment]
En la tarea 1, la pregunta de los colores cuanta como una sola pregunta o como dos ?

**Comment by jmwielandt** [comment]
> En la tarea 1, la pregunta de los colores cuanta como una sola pregunta o como dos ?

@isiguelfand la conté como dos.
