### ISSUE TITLE
Virtual Vox

### ISSUE THREAD

**Issue by ninifdr** [IIC2343/Syllabus#7]
Hola! Tengo un problema con la máquina Virtual que no he podido resolver. Instalé Ubuntu pero la pantalla está con muchísimo zoom y por lo mismo cuando se abre la ventana para instalar virtual box no puedo apretar los botones porque no alcanzan a aparecer.
He buscado harto en internet y no he podido arreglaro. Gracias!

**Comment by Arcoirisky** [comment]
Hola! 
Una pregunta, creo que no entendí lo que está pasando. Instalaste ubuntu y ¿de ahí quieres instalar virtualBox? O ¿intentas instalar ubuntu en la virtualBox? O:

**Comment by ninifdr** [comment]
Perdonnn, ya instalé ubuntu y ahora quiero instalar vivado!! pero no puedo porque está tan zoomeada la pantalla que no me aparece todo! Pero no puedo arreglarlo

**Comment by ninifdr** [comment]
![Captura de Pantalla 2019-08-13 a la(s) 13 42 54](https://user-images.githubusercontent.com/42162406/62964129-652ff600-bdd0-11e9-92ac-b4d8fc76ac6f.png)

**Comment by jmwielandt** [comment]
Holaa!

Prueba [esto](https://help.ubuntu.com/stable/ubuntu-help/look-resolution.html.en) y nos dices si te funciona :D
Si no funciona, quizás [esto](https://askubuntu.com/questions/240745/how-do-i-get-a-larger-screen-resolution-in-virtualbox-on-mac-os-x) sí, pero es un post viejo. Seguiré buscando un rato, si encuentro algo más lo pongo por acá.

Saludos!

**Comment by jmwielandt** [comment]
Oh! [esta otra solución](https://exitdiscount.com/how-to-set-resolution-ubuntu-guest-os-running-in-virtualbox-on-macos/) es mucho más reciente y no requiere instalar nada, a diferencia de la segunda que puse.

Dinos si alguna te funciona :D

**Comment by ninifdr** [comment]
Muchas gracias!!! Ahí lo arreglé!
