### ISSUE TITLE
Pregunta corrección con Hackerranck

### ISSUE THREAD

**Issue by mariana-ortega** [IIC2343/Syllabus#7]
Hola!
La verdad es primera vez que me toca ocupar Hackerrank en un curso y tengo algunas dudas sobre cómo es el criterio de corrección para el código.
Se considera solo el status "wrong answer" o "accepted" ? O se consideran los test case pasados por tu código? O es de otra forma?

Gracias de antemano!

Saludos,
Mariana

**Comment by jmwielandt** [comment]
Hola,

Lo que ocurre es que cada test que pasas dentro de un challenge te suma puntaje para ese challenge. Al final cada pregunta va a tener su propio porcentaje de logro y es ese porcentaje el que irá a la nota final de tareas (parte preguntas programadas).

Saludos!
