### ISSUE TITLE
P2.a y bit

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#7]
Hola! Me enredé un poco con lo visto en clases de bits y en los apuntes, por lo que no puedo responder bien la pregunta 2.a. Mi duda es que al preguntarnos "¿cuántos bits necesita como m ́ınimo la nueva representación posicional?", se refiere cuántas posiciones más hay que agregar (refiriéndome a esto en binario como 101 tiene 3 posiciones y 1010 tiene 4 posiciones (o bits?)), o se refiere cuantas combinaciones más abran posibles (refiriéndome a esto en binario que un posición tiene 2 bits (0 y 1) y dos posiciones tiene 4 bits (01 00 10 11). 

Luego, dado lo anterior, entonces que el primer conjunto se pueda representar con n bits se refiere a n posiciones o a n combinaciones.

Muchas gracias!

**Comment by FranLucchini** [comment]
Hola, cuando habla de bits, se refiere a las posiciones, no a las combinaciones posibles. O sea, es lo primero que mencionaste.
