### ISSUE TITLE
[T01 Equivalenia] Ejemplo equivalencia

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2343/syllabus#7]
Hola, podrían subir el ejemplo del output para el caso mostrado en el enunciado de la tarea (página 2). Gracias

**Comment by Arcoirisky** [comment]
Hola!

Si deseas el .json puedes crearlo tu mismo con tu editor favorito. Igual la idea es que puedan ver el output de los circuitos por ustedes mismos para comprobar si funciona o no su programa.. Esperamos que entiendan qué es lo que está pasando. Y no hay mejor forma de hacerlo que resolviéndolo a mano :D Igualmente, recuerda que los inputs influyen en el resultado final O:! 

¡Ánimo y suerte!

**Comment by NicolasAguirre** [comment]
El circuito equivalente lo tenemos que entregar con json como asi pe:?
{"from": nand1 "to" nand2}... 

Gracias

**Comment by auirarrazaval** [comment]
@NicolasAguirre Si, debe ser un archivo .json, con los correspondientes:
```
{"circuit": [
    {"from": "nand1", "to": "nand2"}, 
    ...]
}
```

**Comment by NicolasAguirre** [comment]
Otra duda, por ejemplo si tengo:

{"circuit": [
    {"from": "input1", "to": "not1"}, 
    ...]
}

y quiero transformarlo a nand tengo que hacer:
{"circuit": [
    {"from": "input1", "to": "nand1"}, 
    ...]
}

o

{"circuit": [
    {"from": "input1", "to": "nand1"}, 
   {"from": "input1", "to": "nand1"}, 
    ...]
}

porque el nand debiese recibir dos parametros! esa es mi duda, muchas gracias!

**Comment by Arcoirisky** [comment]
Es como tu segunda opción. Cada linea es un "cable" en tu circuito :D

**Comment by ariel-m-s** [comment]
Hola @NicolasAguirre!

El circuito equivalente debe tener los mismos _inputs_ y los mismos _outputs_ que el circuito original; todo el resto queda a criterio tuyo. 

Ahora bien, tanto las compuertas _NAND_ como las compuertas _NOR_ son binarias, es decir, reciben exactamente dos _inputs_. **Ojo**: esto tiene que estar explícito en el archivo que genere su programa.

Sobre el ejemplo que das tú, como dice @Arcoirisky, en la opción 2 se ve que entran dos _inputs_ a la compuerta. Sin embargo, no necesariamente estos deben ser iguales: todo dependerá del circuito original.

Mucho éxito con la tarea!
Ariel
