### ISSUE TITLE
[Tarea 3] Programación archivo JSON

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#70]
Hola! Podrían subir el archivo JSON del enunciado (el de la maquina con el input)? Esto para ir probando la programación con un ejemplo.

Muchas gracias!

**Comment by Geeermy** [comment]
¡Hola!

Es simplemente copiar lo que está en el enunciado en un nuevo archivo de extensión ```.json``` :disappointed:, no tiene nada más.

Saludorojillos :nerd_face:

**Comment by miguelramirezv** [comment]
Hola haciendo esto con el código del enunciado me sale el error.

![captura de pantalla 2018-08-30 a las 20 36 42](https://user-images.githubusercontent.com/17711310/44885138-a8fc1f00-ac95-11e8-8eb4-998d2c80ce75.png)

El error es el siguiente:

![captura de pantalla 2018-08-30 a las 20 36 22](https://user-images.githubusercontent.com/17711310/44885167-c335fd00-ac95-11e8-868f-551e5e1dd586.png)

Creo que es porque el .json está mal escrito, podrían subir un archivo como ejemplo o ayudarme a arreglar este por favor?

Gracias!!

**Comment by eiherrera** [comment]
Hola! A mi me funciona todo bien con este:

```
{
	"sequential": [
		{"from": "input1", "to": "ffd1", "gate": "C"},
		{"from": "ffd1", "gate": "Q", "to": "not1"},
		{"from": "ffd1", "to": "out1", "gate": "Q"},
		{"from": "not1", "to": "ffd1", "gate": "D"}
	],

	"input":{
		"input1": [0,1,0,0,0,1]
	}
}

**Comment by Geeermy** [comment]
¡Gracias @eiherrera ! 😄

@miguelramirezv  Probé con ambos ejemplos y con ambos me funcionó la librería, así que no es un tema del archivo o su formato. ¿Lo copiaste y pegaste del PDF? Quizás quedaron caracteres (como tabs y cosas así) que le genera problemas a tu programa. Prueba con el ejemplo de tu compañero, quizás ahí funciona. ¡Me cuentas!

¡Salu10000! 🐺

**Comment by miguelramirezv** [comment]
Ahí sí me funcionó con el de @eiherrera ! Muchas gracias a los dos!!
