### ISSUE TITLE
Duda JMP en ejemplo precompilado

### ISSUE THREAD

**Issue by Unknomads** [IIC2343/syllabus#70]
Hola.

Tengo una duda con la ultima linea de la primera imagen del archivo ejemplo_precompilado2:
![Screen Shot 2019-04-18 at 7 35 03 PM](https://user-images.githubusercontent.com/20389726/56395511-e1427480-6208-11e9-81f0-aba3fba9dca0.png)

![Screen Shot 2019-04-18 at 7 47 53 PM](https://user-images.githubusercontent.com/20389726/56395917-90cc1680-620a-11e9-9e1a-c3bcfa0b5525.png)

Lo que no entiendo es por qué el numero de linea del label MAIN es 0x70 y no 0x39 ya que empieza en la linea 57 y hex(57)=0x39.
O sea lo que yo digo es que la ultima linea de la imagen debería ser 0x1E 0x39

Saludos!

**Comment by Arcoirisky** [comment]
Estás contando que la forma en la que están esos programas es opcode y al lado literal en la misma línea en vez de cada uno de forma independiente? (Como debería ser en un computador normal de 8bits) 

José lo explicó en Issues pasadas O:

**Comment by Unknomads** [comment]
Perfecto no me había dado cuenta. Gracias
