### ISSUE TITLE
[PLACA] Probar placa/Device is programmed with a design that has no supported debug core in it

### ISSUE THREAD

**Issue by Taeval** [IIC2343/syllabus#71]
Seguimos las instrucciones del tutorial de Vivado y pudimos programar la placa usando Program Device con el archivo .bit de Basys3. No estamos seguros de como proceder ahora... 😟 

Obtuvimos un mensaje que dice:

"Device is programmed with a design that has no supported debug core in it."

**Comment by frvalenzuela** [comment]
Hola!

Ese es un error extraño. Según busque sobre el error en este [link](https://forums.xilinx.com/t5/General-Technical-Discussion/warning-debug-core-was-not-detected/td-p/744291). El error puede deberse a que la placa este mal conectada a un puerto usb. Intenten conectarla a otro puerto y me cuentan. (No es un error regular)

Saludos!

**Comment by seba608** [comment]
Hola,

A mi grupo nos aparece el mismo error. Conectamos a otro puerto y no pasó nada.

Saludos!

**Comment by frvalenzuela** [comment]
Hola!

Necesito una captura de su ventana Sources, como muestro a continuación:
![image](https://user-images.githubusercontent.com/20147482/56398853-e90a1500-6218-11e9-9ef2-606de33b1f09.png)

Y también una captura del error en particular, para saber que muestra en especifico.

Saludos!

**Comment by frvalenzuela** [comment]
Hola! 

También agregar que intenten probar hacer un archivo .bit del código base (el que esta subido al syllabus) solo para corroborar si es problema del circuito en particular.

Saludos!

**Comment by seba608** [comment]
La foto:

![screen](https://user-images.githubusercontent.com/26118304/56399373-8cf4c000-621b-11e9-8fd8-34c811741cd8.png)

No entendí bien lo último. La verdad no entiendo bien como se prueba la placa. En teoría tengo tengo todo conectado en basys pero ¿que debo hacer después? ¿Debo darle instrucciones a la ROM?

Saludos

**Comment by Arcoirisky** [comment]
Cambias algunas de las instrucciones que ya tiene tu rom por otras que ejecuten algo, puede ser una suma simple o que guarde ciertos números en memoria. 

Esas instrucciones puedes crearlas a partir de la Isa que tienen. 

Ya de ahí deben cargar el programa en la placa, encenderla y ver si la placa hace lo que desean :D

**Comment by frvalenzuela** [comment]
Hola @seba608, lo que decía es que si podía mandar una captura del error que aparece cuando intentas hacer Program Device.

Si todo esta conectado en basys no deberías tener problemas al momento de hacer program device. Todavía no estoy complemente seguro que puede estar causando el error, por eso pido si puedes abrir un nuevo proyecto con el computador primigenio del syllabus e intentar hacer el proceso de syntesis implementation generate bitstream e intentar hacer program device. 

En última instancia suban su código a su repositorio para ver si puedo notar el error en especifico.

Saludos!

**Comment by seba608** [comment]
Hola @frvalenzuela el error me sale como una info, quizás ni si quiera sea un error:

![screen](https://user-images.githubusercontent.com/26118304/56400291-24a8dd00-6221-11e9-9ead-44b47ac758a0.png)

Lo que pasa es que no sé como probar el programa. En cualquier caso el código ya está en el repo (grupo6).

Saludos y gracias!

**Comment by seba608** [comment]
Creo que ya entendí, gracias por la ayuda!

**Comment by frvalenzuela** [comment]
@seba608  En cuanto pueda revisaré el problema. Si tu problema llega estar solucionado, por favor comentar tu solución puede que le sea de ayuda a otra persona. Gracias!

**Comment by seba608** [comment]
Oka.

Mi problema era que no entendía como pasarle intrucciones a la placa y cuando vi el error de esta issue pensé que era por eso, pero por lo que entendí eso no es un error en sí, sino que una advertencia. Sin tomar en cuenta eso fui al script de la ROM y cambié lo que estaba ahí por el código:

""000000000000010110000000000000001"

En donde los primeros 17 bits corresponden al opcode de A = A + LIT y los 16 últimos corresponden al LIT = 1. Con eso la placa muestra un contador que va sumando de a uno.

Me queda una última duda de como parar la placa porque si bien le metí 6 instrucciones (todas iguales a la descrita) pareciera ser que una vez que termina el programa parte de nuevo porque el contador no paraba de aumentar.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @seba608 !

Que bueno que hayas podido solucionar tu problema! 

Respecto a tu duda, estas manejando el caso de la operación NOP? Porque esa operación debería "detener" tu programa. El hecho de que el contador no pare de aumentar es un hecho, pues nada detiene al PC en aumentar su valor.

Saludos!
