### ISSUE TITLE
[Tarea 3]: Programacion parte A: transformacion de flip flop

### ISSUE THREAD

**Issue by nmaturana97** [IIC2343/syllabus#71]
Hola, quería saber si tengo que "recibir" el valor Q de cada flip flop en el circuito combinacional que debamos hacer.
Si la respuesta es si, puedo usar la convencion Q{s} es igual al Q del ffd{s}?

**Comment by Geeermy** [comment]
¡Hola!
1. ¿Es necesario que sea **con todos**? Piensa en el resultado que tiene que dar tu circuito combinacional... ¿importan los estados de **todos** los Q para el _output_? Piensa en eso un poco para tu implementación.
2. Independiente de lo anterior, sí, puedes usarla. La idea es que sigan una convención que se entienda (ojalá dejar claro que es un _input_, pero lo que dices es válido).

**Comment by nmaturana97** [comment]
Osea, esq por ejemplo si tengo input1 que va hacia ffd1 y ffd2, y fdd1 va a output1 y ffd2 va a output2, segun yo se necesitaria el Q de ambos para poder obtener cada output correcto. Entonces, si bien quizas hay casos en q no es relevante el Q de todos, siempre puede añadirse y eso no afectara el output.
Quizas lo estoy viendo mal, por favor dime si es asi.

**Comment by Geeermy** [comment]
Sí, tienes razón en ese aspecto, pero es más limpio no dejar _inputs_ que no aportan al resultado de tu circuito. No creo que lo controlemos si de todas formas el resultado del _output_ está bien, pero esperamos que al menos dejen la estructura lo mejor posible.

¡Ánimo! 🐕
