### ISSUE TITLE
Error no se encuentra la placa en Vivado

### ISSUE THREAD

**Issue by Mesantacruz** [IIC2343/Syllabus#71]
Hola, estoy tratando de compilar mi codigo en la placa y al correr el Run Implementation me sale el siguiente error diciendo que la placa no esta conectada cuando si lo esta. 

               General Messages
               HW Target shutdown. Closing target: localhost:3121/xilinx_tcf/Digilent/210183AA66CDA

               No devices detected on target localhost:3121/xilinx_tcf/Digilent/210183AA66CDA.
               Check cable connectivity and that the target board is powered up then use the disconnect_hw_server and connect_hw_server to re-register this hardware target.

**Comment by frvalenzuela** [comment]
Hola @Mesantacruz !

La placa se muestra operativa ? Que sistema operativo estás ocupando? 

Saludos !
