### ISSUE TITLE
Recorrección 

### ISSUE THREAD

**Issue by Bnnunez** [IIC2343/syllabus#72]
¿Como es el proceso para hacer la recorrección? 

- ¿Hay que contactarse directamente con el ayudante encargado?
-¿ Es presencial o debemos subir los archivos nuevos al Github?

**Comment by Hernan4444** [comment]
@Bnnunez para empezar suban los archivos a su repositorio y le mandan un mail a su ayudante designado avisandole que optan por recorregir.  De ahí el ayudante se contactará con su grupo decidiendo si es posible recorregir de forma presencial (tanto el ayudante como el grupo dispone del tiempo para juntarse) o él lo hará desde la casa.

Saludos
