### ISSUE TITLE
Tarea 2 | Pregunta 2 | Opciones con el arreglo ordenado

### ISSUE THREAD

**Issue by stmorales** [IIC2343/Syllabus#72]
Hola!!

Viendo la tarea 2, en la pregunta de Selection Sort, es necesario utilizar el puntero al `arreglo 2 `que nos dan? Mi duda viene porque dado que los arreglos son de largos variables, se es más lógico indicar la posición del `arreglo_ordenado` dentro de nuestras variables y trabajar solo con este, sin necesidad de tocar el puntero que nos dan ustedes. Porque tengo entendido que debemos crear la variable `arreglo_ordenado`.

Muchas gracias, quedo atento

**Comment by jmwielandt** [comment]
Hola,

Era un error en el código base, tenía que decir `arreglo_ordenado` en vez de `arreglo2`, la variable se las damos nosotros. Ya está corregido en el código base del enunciado.

Saludos y gracias!

**Comment by stmorales** [comment]
Gracias, y asumo que este `arreglo_ordenado` viene vacío en un principio?? Tenemos que ser capaces de ordenar nuestras variables para darle espacio a los números que vamos agregando? Puede venir en cualquier posición o siempre es la última variable que nos entregan?

**Comment by jmwielandt** [comment]
> Gracias, y asumo que este `arreglo_ordenado` viene vacío en un principio?? Tenemos que ser capaces de ordenar nuestras variables para darle espacio a los números que vamos agregando? Puede venir en cualquier posición o siempre es la última variable que nos entregan?

Sí, viene vacío, no necesitan ordenar sus variables y puedes verlo en el repositorio (ya está pusheado), lo dejé debajo del `//!end-data`, así que no deberían tener variables en posiciones más altas de la memoria y por tanto no necesitan hacer malabares para no pisarlas con el arreglo. Será siempre la última variable que les entreguemos.

**Comment by stmorales** [comment]
Muchas gracias!
