### ISSUE TITLE
[T2 - Programada] - Estado final disassembler

### ISSUE THREAD

**Issue by mramirez7** [IIC2343/syllabus#72]
Hola, tengo una duda del output.txt del disassembler, se espera que este archivo sea como ejemplo_codigo.s o más bien como el ejemplo_precompilado1.s? ya que no tenemos los nombres de las variables-labels.
En caso de que se espere algo estilo ejemplo_codigo.s me imagino que las variables pueden tener cualquier nombre (variable1, variable2...) y los labels igual siempre y cuando tengan un main y end.

**Comment by Arcoirisky** [comment]
Como el ejemplo_código O: 
Recuerda que lo único que sabe el Dissasembly es que tiene que leer y traducir, leer y traducir, leer y traducir... :eyes: (y sip, supones bien. Solo cuidado que la lógica y estructura deben mantenerse)
