### ISSUE TITLE
Ejemplos json

### ISSUE THREAD

**Issue by JorgeBdelaT** [IIC2343/syllabus#72]
Hola, para probar nuestro código de la parte B de programación podrían subir un par de json con ejemplos?  Gracias!

**Comment by Geeermy** [comment]
¡Hola!

La idea de las tareas en general es que ustedes sean capaces de elaborar sus propios _tests_, así que lo siento, pero no se subirán. 😢

Si tienes dudas de los _tests_ que elabores, puedes subirlos aquí y los revisamos.

¡Que estés bien! 🐩
