### ISSUE TITLE
[T02] [PLACA] Señales Address y Count In

### ISSUE THREAD

**Issue by vijuarez** [IIC2343/syllabus#73]
Hola!

Algo de lo que recién me estoy dando cuenta. En la #46 dijeron que los datos que salen desde Data Out a MUX B son los 16 bits menos significativos. Asumo que de ahí salen los datos (12 bits) de Address y Count In, pero que 12 bits en especifico? Los menos o más significativos?

Gracias.

**Comment by frvalenzuela** [comment]
Hola Vicente!

De los 16 bits menos significativos que salen de la ROM, los 12 bits menos significativos van a parar a Addres y Count In. 

Saludos!
