### ISSUE TITLE
Tarea 2 | Pregunta 2 | Arreglo vacío

### ISSUE THREAD

**Issue by stmorales** [IIC2343/Syllabus#73]
Hola!

Cuando se refieren a que un arreglo viene vacío qué significa? Cómo se instancia en Assembly? Con un 0 tal como nos pasan el `arreglo_ordenado`??

Gracias!

**Comment by jmwielandt** [comment]
Hola, para tener un arreglo vacío tienes un puntero que apunta a una cierta dirección de memoria y algo tiene que haber, puede ser un 0 o cualquier otra cosa, pero como tú estás diciendo "está vacío" lo que vas a hacer es ir escribiendo encima de lo que haya.

En esencia para efectos de la tarea, es como está en el código base, se declara la variable con algún valor random.

Saludos!

**Comment by stmorales** [comment]
Muchas gracias!
