### ISSUE TITLE
[Entrega 1E] Shift continuo por clock o por input

### ISSUE THREAD

**Issue by josefinaijb** [IIC2343/Syllabus#73]
Buenas!
Me quedó la duda del enunciado si el shift se debe realizar una sola vez cuando se presiona el botón, o si se mantiene el botón presionado para hacer un shift continuo, en base al tiempo que quede presionado. Es decir, 1input =1shift o 1clock=1shift.

Gracias de antemano!

**Comment by CristobalHV** [comment]
hola @josefinaijb 

Lo correcto sería que cuando se presione el botón una vez, se realice una sola operación shift.

Saludos y éxito en la entrega!

**Comment by josefinaijb** [comment]
@CristobalHV Perfecto, gracias!!
