### ISSUE TITLE
Tarea 3 Programación Duda General

### ISSUE THREAD

**Issue by julioag** [IIC2343/syllabus#73]
Hola, tengo una duda con el ejemplo entregado en el enunciado y como implementar mi código, puedo asumir, tal y como sale en el ejemplo, que la entrada a la compuerta D siempre dependerá de la iteración anterior del _flip-flop_?  O puede ser que en un _flip-flop_ la entrada a la compuerta D y C sea al mismo tiempo??

Gracias.

**Comment by Geeermy** [comment]
¡Hola!

Claro que sí. Ojo eso sí que no siempre lo que entra a la compuerta D va a estar asociado al estado del _flip-flop_. Por ejemplo, podrían ingresar dos señales de _input_ que pasan a través de una compuerta ```AND```, y ahí el estado del _flip-flop_ no tendrá influencia alguna.

¡Éxito! 🐤

**Comment by Nicolasvegam** [comment]
@Geeermy no entendí la respuesta (y tengo la misma pregunta). Esto quiere decir que podría ser un flip-flop conectado a dos input directo, y además, uno que dependa de la iteración anterior como en el ejemplo de la tarea?

**Comment by BSamilla** [comment]
@Nicolasvegam 
Exacto.
En el ejemplo el flip-flop recibe como "clock" a su entrada C un input,  y como "dato" a su entrada D su salida negada.

Pero podría pasar que la entrada no dependa de su salida, por ejemplo, podría llegar a su entrada D el resultado de alguna otra compuerta dentro del circuito, como también podría provenir desde otro input.

Saludos!
