### ISSUE TITLE
Duda interrogacion escrita entrega 4

### ISSUE THREAD

**Issue by roy350** [IIC2343/syllabus#73]
Hola!, disculpen pero me queda la duda con el punto de que si en la prueba mi nota es inferior a 4 repruebo el proyecto, por que en clases el profesor habia dicho que si reprobabas, simplemente tenia que hacer la entrega, es para saber si efectivamente sera asi o como esta el enunciado, muchas gracias!!

**Comment by FranLucchini** [comment]
Tienes razón, gracias por mencionarlo. Es como dices tú, voy a modificar el enunciado.
