### ISSUE TITLE
[Tarea 3] Programación parte A: Denominación conexiones

### ISSUE THREAD

**Issue by eiherrera** [IIC2343/syllabus#74]
Hola!

Al transformar el flip-flop a un circuito combinacional, la conexión entre _Q_ y _D_ la denominamos como un nuevo input en el circuito resultante? Utilizando el ejemplo del enunciado, en el caso del componente `{"from": "ffd1", "gate": "Q", "to": "not1"}`, podemos escribir su símil combinacional como `{"from": "input2", "to": "not1"}`?

**Comment by Geeermy** [comment]
¡Hola!

Sí :) pero ideal si pueden ponerle un nombre al _input_ que tenga que ver con la transformación, por ejemplo: ```input_ffd1``` o cosas de ese estilo.

¡Éxito! :fish:

**Comment by eiherrera** [comment]
Gracias!

Otra duda corta: ¿los inputs de nuestro programa van a incluir la extensión _json_ o se la agregamos nosotros?

**Comment by Geeermy** [comment]
Siempre se incluirá, en otro caso no sería un archivo JSON jejej. :smiley:
