### ISSUE TITLE
Tarea 2 | Pregunta 1 | Intervalo de los inputs

### ISSUE THREAD

**Issue by stmorales** [IIC2343/Syllabus#74]
Hola!

En el enunciado de la pregunta 1 nos piden hacer un comparador entre dos números de 8 bits. Habrán inputs que se necesiten más de 8 bits para expresarlos? En ese caso, el assembly lo toma por si solo los 8 primeros bits. No tenemos que preocuparnos de estos casos? Asumimos que los inputs siempre estarán entre [-128,127]??

Saludos,

**Comment by jmwielandt** [comment]
Hola,

El computador básico de las clases (y de la tarea) es de 8 bits por lo que solo tiene 8 bits para representar los valores dados, por tanto no habrá inputs de valores numéricos de más de 8 bits.

Saludos!

**Comment by stmorales** [comment]
Muchas gracias!!
