### ISSUE TITLE
¿MegaMental como funciona?

### ISSUE THREAD

**Issue by glbello** [IIC2343/syllabus#74]
Saludos, quise probar bin de ejemplo que han puesto para la entrega 4, pero no comprendo como funciona ni que hace... tengo conectado el LCD y no aparece nada, solo están todos los leds prendidos y el display sale solo ceros. Alguien podría explicarme este ejemplo

**Comment by Hernan4444** [comment]
@glbello te recomiendo ir siding del semestre pasado y descargar el enunciado de la entrega 4, ahí se explica como tenían que hacer el juego que les pasamos en esta ocasión. Si tienes conectado el LCD y no aparece nada, puede ser que lo contaste en el lado incorrecto. Utilizando esta imagen como referencia:
![image](https://user-images.githubusercontent.com/15641721/27525927-fa958e70-5a0f-11e7-84a7-2ce3670b8827.png)

La pantalla tiene que estar conectada en el lado derecho, donde las dos filas de pines están conectadas en los JB y la parte de la pantalla que tiene una sola fila de pines, debe ir conectada en los JC7 al JC12

Ojalá se entienda donde conectarla, en caso contrario no dudes en preguntar mas
Saludos!

**Comment by glbello** [comment]
@Hernan4444 Había conectado mal el LCD, y ahí entendí el juego gracias a la referencia del enunciado de la E4 del semestre pasado. Mil Gracias!! ʘ‿ʘ
