### ISSUE TITLE
entrega 1e repositorio en github

### ISSUE THREAD

**Issue by mplazadelosreyes** [IIC2343/Syllabus#74]
Hola!! 
No me queda tan clara la forma de subir los archivos a GitHub
En el enunciado dice: "La entrega se realizará a través de GitHub. El repositorio debe contener una carpeta con su proyecto de Vivado y el archivo .bit. En el caso de la carpeta del proyecto, deben subir solo la carpeta .srcs, el archivo .xpr y el archivo Basys3.xdc".

Para el el archivo .bit en particular, este esta dentro de mi carpeta runs del proyecto de Vivado, entonces entrego toda la carpeta runs y le borro los otros archivos o saco el archivo .bit de esa carpeta (ahi se le cambiaría el path relativo) y lo entrego dentro de mi carpeta del proyecto nomas?

**Comment by frvalenzuela** [comment]
Hola @mplazadelosreyes !

A diferencia de los archivos dentro de la carpeta `src`, el archivo .bit puede ser programado desde cualquier path. Así que sacarlo de la carpeta y ponerla dentro de tu carpeta proyecto es lo más adecuado.

Saludos!

**Comment by mplazadelosreyes** [comment]
perfecto! gracias!
