### ISSUE TITLE
[T2 PLACA] Testear

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2343/syllabus#74]
¿Podrían subir un tutorial de como probar la placa por favor?

Slds

**Comment by frvalenzuela** [comment]
Hola Ignacio!

Por temas de tiempo lo veo muy poco probable. Sin embargo, puedo dar consejos de como probar las entidades que tu vayas creando.

### Consejos para probar tu entidad en la placa

Digamos que queremos probar la entidad ALU. Para esto podrías hacer lo siguiente:

- Ocupar los cuatro switches de más a la izquierda como los 4 bits menos significativos de la primera entrada de la ALU.
- Ocupar los cuatro switches de más a la derecha como los 4 bits menos significativos de la primera entrada de la ALU.
- Ocupar los cuatro display para mostrar el resultado.
- Ocupar los botones para seleccionar la operación.
- Ocupar las leds para
Visualmente se vería algo así:
![image](https://user-images.githubusercontent.com/20147482/56400443-eb24a180-6221-11e9-8316-c656b8bf9d9d.png)


A nivel de código necesitaríamos las siguientes señales:

```
--- SIGNALS TESTER ALU

signal entrada_a            : std_logic_vector(15 downto 0);  -- esto será conectado a los switches de la derecha

signal entrada_b            : std_logic_vector(15 downto 0);  -- esto será conectado a los switches de la izquierda

signal resultado            : std_logic_vector(15 downto 0);  -- esto será lo que salga de la instancia de ALU

signal operation            : std_logic_vector(2 downto 0);  -- esto será la operación de la ALU que será conectado a los botones

signal alu_c            : std_logic; -- uno de los output de la ALU

signal alu_z            : std_logic; -- uno de los output de la ALU

signal alu_n            : std_logic; -- uno de los output de la ALU

```
Luego del begin, definiremos los siguientes comportamientos:
```
--- CONEXIONES

entrada_a(3 downto 0) <= sw(15 downto 12) -- conectamos los 4 switches de más a la derecha a los bits menos significativos de lo que entra en A

entrada_b(3 downto 0) <= sw(3 downto 0) -- conectamos los 4 switches de más a la izquierda a los bits menos significativos de lo que entra en B

dis_a  <= resultado(15 downto 12); -- los 4 bits más significativos del resultado de la ALU van al display A

dis_b  <= resultado(11 downto 8);

dis_c  <= resultado(7 downto 4);

dis_d  <= resultado(3 downto 0); -- los 4 bits menos significativos del resultado de la ALU van al display D

operation <= btn(2 downto 0); -- los 3 primeros botones serán lo que determine la operación a ejecutar

led(0) <= alu_c; -- cuando C sea 1 se prenderá la led de más a la izquierda

led(1) <= alu_z;

led(2) <= alu_n;

```
Finalmente, necesitamos la instancia de la ALU:
```
inst_ALU: ALU port map(
    a           => entrada_a,
    b           => entrada_b,
    sop         => operation,
    c           => alu_c,
    n           => alu_n,
    z           => alu_z,
    result      => resultado
    ); 
```

Luego generamos el .bit y a probar nuestro circuito!

### Comentarios adicionales:

No necesariamente tiene que tener esta estructura, por ejemplo lo que entra en la ALU podría haber sido un std_vector fijo, no necesariamente que este conectado con swithches, o podrían haber sido los botones, etc. Como ustedes vean necesario pueden ir ocupando las distintas herramientas que le da la placa para testear sus entidades. O incluso ver comportamientos completo del computador, por ejemplo los leds puede ser los primeros bits que salen de la ROM, de la RAM y de la Control Unit y que los switches sea selectores de un mux, cosa de que si yo levanto un switch los led muestran unou otro componente. O que al cambiar uno de los switches (nuevamente siendo el selector de un mux) en vez de ver en dos displays los primeros 8 bits del registro A, vea todo el registro A en los cuatro display (perdiendo la vista del registro B). Dejen volar su creatividad a la hora de testear sus componentes/entidades (a un punto que les sirva a ustedes tampoco les pido que pierdan el tiempo en hacer algo muy elaborado para testear. Esto es un apoyo para ustedes, si hicieron o no un test no será evaluado)

Espero que esto te sirva y si te quedo alguna duda no dudes en preguntar.

Saludos!

**Comment by mundurragac** [comment]
No me queda claro como implementar este código, hay que modificar lo que venía en el basys3?

**Comment by frvalenzuela** [comment]
Hola @mundurragac !

Así es ! Debes modificarlo, aunque la mejor palabra sería **agregar**. En la entidad Basys3  tu agregas esas señales, esos comportamientos y dichas instancias. Una vez que quieras dejar de testear las borras o comentas (como te sea más conveniente), y dejas todo conectado como para ser revisado en la entrega.

Espero que eso solucione tu duda. En caso de no ser así me avisas.

Saludos!

**Comment by mundurragac** [comment]
Si! Con el testeo de la ALU perfecto, pero en el caso de el CU como lo podría testear??

**Comment by frvalenzuela** [comment]
Hola @mundurragac !

Como puse en comentarios adicionales, no hay una única forma de testear algo, y depende mucho de lo que tu quieras ver de tu componente (en este caso la control unit). Una forma podría ser que los switches fuesen reemplazaran lo que recibe de la ROM, los botones lo que recibe de status y los leds fuesen el output. Sin embargo, probar cada instrucción puede ser algo tedioso, por lo que solo sería para ver que inicialmente todo este bien conectado, y cumpla el comportamiento que ustedes esperan.

Para la control unit siempre es mejor probar cargando instrucciones en la ROM y conectar todo, para ver que el comportamiento es el que se espera.

Espero que eso responda tu pregunta! Cualquier cosa me avisas.

Saludos!

**Comment by AndresGarciadelaHuerta** [comment]
Hola @frvalenzuela! Tratando de hacer el ejemplo que diste me tira el siguiente error al sintetizar:

![WhatsApp Image 2019-04-19 at 20 34 07](https://user-images.githubusercontent.com/30664883/56449235-d3622180-62e4-11e9-94be-9e64d510b103.jpeg)

Por qué podría pasar eso? No se si es error mío o no jaja

**Comment by frvalenzuela** [comment]
Hola @AndresGarciadelaHuerta !

Ese error al sintetizar normalmente se de cuando alguna señal esta conectando un input con un output, o que alguna señal esta "chocando" con otra. Mi consejo es que revises como estas conectando las señales, desde a dentro hacia afuera (revisa que los componentes de tu entidad ALU no tengan problemas de señales mal conectadas).

Saludos!

**Comment by AndresGarciadelaHuerta** [comment]
@frvalenzuela Muchas gracias por la respuesta! Revisé y encontré lo que estaba haciendo mal
