### ISSUE TITLE
Tarea 2 | Pregunta 3 | Forma de finalizar el programa

### ISSUE THREAD

**Issue by stmorales** [IIC2343/Syllabus#75]
Hola!!
Para la pregunta 3 del palíndromo, el algoritmo debe terminar porque se acabaron las instrucciones de la ROM o por el loop end para finalizar? O no importa mientras entreguemos el resultado?

Quedo atento!

**Comment by ceosorio** [comment]
Hola @stmorales!

No importa la forma en que termine tu programa, mientras termine correctamente su ejecución y no se quede en un loop infinito. El emulador reconoce el **loop end** como una forma de término de ejecución así que también puedes usarlo.

Ánimo y éxito en la tarea ✨
