### ISSUE TITLE
controlador no lee placa

### ISSUE THREAD

**Issue by kmhaller** [IIC2343/Syllabus#75]
Hola,
Tengo el siguiente problema
![placa mal](https://user-images.githubusercontent.com/48329325/65834372-9301c900-e2b0-11e9-936c-9aed8413dc63.jpg)

Que supongo es el causante de que no se conecte de manera automatica vivado a la placa.
Por eso no puedo programar la placa.
La solución que me propone es descargar los controladores. Hice esto pero no me funcionó. Quizás no eran los correctos pero era un pack de la siguiente pagina dentro de lo que debería estar.
https://driverpack.io/es/devices/massstorage
Alguna otra solución a este problema?
(Al apretar soluconar el problema sale instalar software controlador de dispositivo,
Si lo apreto despues aparece que no se pudo descargar)
Saludos

**Comment by frvalenzuela** [comment]
Hola @kmhaller !

Lo que se me ocurre es que los controladores no se instalaron o se instalaron incorrectamente. Asumiendo que tu sistema operativo es windows 7, te recomiendo revisar el siguiente URL:

https://forums.xilinx.com/t5/Design-and-Debug-Techniques-Blog/Manually-installing-Cable-Drivers-for-Xilinx-Platform-Cable-USB/ba-p/992593

Si eso no funciona, recomiendo re-instalar los controladores como indica el manual de instalación de Vivado página 36, link a continuación:

https://www.xilinx.com/support/documentation/sw_manuals/xilinx2018_3/ug973-vivado-release-notes-install-license.pdf

Si nada de eso funciona, favor hacerlo saber para buscar otras soluciones.

Saludos!

**Comment by kmhaller** [comment]
hola,
gracias por la respuesta.
me pasa que llego al final y no puedo instalar los cable drivers porque no
se encuentran el archivo install_drivers.exe en
*<Install_Location>\Xilinx\Vivado\2019.1\data\xicom\cable_drivers\nt64\digilent*
*Intente la otra opcion y tampoco funciona, no aparecen los programming
cables.*
*Nota: si me aparece el USB solo que muestra una alerta en el siempre y la
advertencia de que faltan los controladores.*

*saludos,*
*mathias*

**Comment by frvalenzuela** [comment]
Hola @kmhaller !

Aquí están los archivos que faltan. Descarga y descomprime en la ruta correspondiente donde no encuentras los archivos.

[nt64.zip](https://github.com/IIC2343/Syllabus/files/3668365/nt64.zip)

Saludos!

**Comment by kmhaller** [comment]
gracias!!
se estan descargando.
Una pregunta que varios se estan haciendo: Como puedo hacerlo para definir
8 flip flop y luego no sobreeescribir el output. tengo una señal de salida
led1 que es un std logic vector
y en cada uno el output es un led diferente por ejemplo led1(0) el primero,
led1(1) el segundo y asi,
pero dice que el problema es que tengo multiple driver nets.
Como lo corrijo? llevo mucho tiempo pegado ya.
saludos

**Comment by kmhaller** [comment]
hola,
ya tenia todos los archivos que estaban en el zip.
parece que en la explicacion hay un error. Segun esta deberia haber un
archivo
llamado install_drivers.exe
en C:\Xilinx\Vivado\2019.1\data\xicom\cable_drivers\nt64\digilent
pero no existe, tampoco en el que me mandaste.
no se que mas hacer, supongo que solamente simulaciones.

saludos

**Comment by frvalenzuela** [comment]
Hola @kmhaller !

Dicho archivo esta dentro de la carpeta dlc10_win7 del zip mandado anteriormente.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @kmhaller !

Tu duda anterior no me quedo muy clara... Si te refieres para como definir 8 flips flops, basta con instanciar ocho veces el componente en la entidad donde lo estes ocupando. El comportamiento del mismo hará que cuando exista un flanco de subida su almacenamiento cambie, que hacer para que además cumpla con lo pedido en la entrega es parte del desafió que se espera ustedes puedan lograr en esta entrega (por lo que no puedo decirte que tienes que hacer directamente).

Si tu duda es otra, con gusto responderé. Pero como dije anteriormente, eso fue lo que yo entendí al leerla.

Saludos!

**Comment by kmhaller** [comment]
claro tengo ese archivo en esa carpeta y hago lo que sale en el primer
punto y no funciona.
Mas abajo sale que hay que hacer lo mismo pero con un archivo del mismo
nombre ubicado en la carpeta digilent,
el cual no se encuentra. Bueno ya es tarde para seguir intentando con la
placa habiendo intentado tantas cosas.
Existe alguna manera de hacerlo solo con simulacion?

Mi pregunta va a que como defino la señal de salida para que no salga ese
error.
He buscado en todos los apuntes del curso y no está en la materia la forma
de hacerlo.
Algun tip que me puedas dar por lo menos? Tendria que cambiar la forma a
hacerlo sin flip flops, si este error sigue.

gracias
mathais

**Comment by frvalenzuela** [comment]
Hola @kmhaller !

El contenido de la carpeta mencionada anteriormente intenta ingresarla dentro de la carpeta digilent y correr el ejecutable.

Respondiendo a tu otra pregunta, si existe una manera de hacerlo con simulación, debes ingresar en los inputs que simulen el comportamiento de los botones y de los switches.

Ah no había captado que tu problema era de un error! Ahora entiendo mejor tu situación, una posible solución sería definir una señal que sea un `std_logic_vector`, que sirva de intermediario entre las señales de tipo `std_logic` (esto es asumiendo que tu error es por intentar conectar ambos tipos de datos, de no ser favor corregirme).

Como tip, puedo decirte que conectar si te complica mucho trabajar con los flips flops puedes otras formas de resolver el problema que se te sea más claro abordar.

Saludos!

**Comment by kmhaller** [comment]
Como copiar y pegarla en la otra carpeta?

Perfecto, pero no podria generar el bitstream o si? Ese es el otro archivo
.bit que hay que subir?

El error se debe a que defino despues del begin que todos los flip flop
tienen de salida un q <= led1(0) , despues q<= led1<(1)... siendo led1 un
str_logic_vector
entonces supongo que esto genera el error, porque los sobreescribo con cada
uno, o no?
sirve en ese caso lo propuesto? no se si lo entendi bien, se supone que
debo crear por cada flip flop una señal std_logic que sirva como
intermediario?
saludos

**Comment by frvalenzuela** [comment]
Hola @kmhaller !

Copiar lo que esta en dlc_win7 dentro de la carpeta digilent de tu computadora.

Respecto a tu duda, me causa extrañeza que estes conectando una señal llamada led1 (supongo que de salida) hacia una salida del flip flop (lo que yo pienso es que debería ser al revés), ahora eso depende mucho de lo que este conectado a tu led1. Para evitar que entregues más información de tu solución te sugiero que mandes una solución parcial a tu repositorio para entender de mejor forma tu problemática.

Lo que yo propuse, es que existe una señal auxiliar digamos `signal aux std_logic_vector(3 downto 1)` y que a esa señal le conectes por cada bit lo que quieras enviar, digamos `aux(0) <= otra_signal;`
. Y luego entregues al componente que requiera de `otra_signal` como vector le pases aux (en caso contrario es la misma lógica invirtiendo los tipos de datos).

Saludos!

**Comment by kmhaller** [comment]
subi una entrega parcial!

**Comment by kmhaller** [comment]
primera_instanciaAND4: AND4 port map(
input_and4 => sw(3 downto 0), -- Input de la entidad es conectado input de
la instancia

output_and4 => signal_and1);

despues de ver eso pense que se podia hacer input los sw y output una
señal. algo asi hice con el flip flop.

Puedes ver mi entrega parcial?

saludos

**Comment by frvalenzuela** [comment]
Hola @kmhaller !

A simple vista veo un problema con el la señal `std_vector` led1. Pues esta es una señal que recibe el output de un componente y a la vez tiene un comportamiento cambiante dentro de un process. Por lo que la led1 recibe dos señales distintas al mismo tiempo. Esto Vivado no te lo va a permitir. recomiendo ocupar señales distintas y modeles de forma distinta tu solución para evitar dicho cruce.

Saludos!

**Comment by kmhaller** [comment]
intente cambiar los led1 en el ff por los swt (otro vector de señales). y
despues en la parte del process hacer led1 <= swt en caso de que se aprete
el bot1.
me sale el siguiente error

   - [Place 30-574] Poor placement for routing between an IO pin and BUFG.
   If this sub optimal condition is acceptable for this design, you may use
   the CLOCK_DEDICATED_ROUTE constraint in the .xdc file to demote this
   message to a WARNING. However, the use of this override is highly
   discouraged. These examples can be used directly in the .xdc file to
   override this clock rule. < set_property CLOCK_DEDICATED_ROUTE FALSE
   [get_nets btn_IBUF[1]] > btn_IBUF[1]_inst (IBUF.O) is locked to IOB_X0Y15
   and btn_IBUF_BUFG[1]_inst (BUFG.I) is provisionally placed by clockplacer
   on BUFGCTRL_X0Y0
   -
      - [Place 30-99] Placer failed with error: 'IO Clock Placer failed'
      Please review all ERROR, CRITICAL WARNING, and WARNING messages during
      placement to understand the cause for failure.

**Comment by frvalenzuela** [comment]
El problema en esta issue, es que dentro del process, se revisaba el flanco de subida en dos condicionales distintos, lo que no esta permitido, pues debe ser solo un condicional.

Finalmente, el problema del controlador era por no tener el puerto 2.0 de VirtualBox activado.
