### ISSUE TITLE
[T03-B] ¿Que hacen sus flip-flops?

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#75]
**edit** 
Hola! ~~tengo algunas dudas sobre el uso de los ffd en esta tarea.~~ 
No logro entender la forma de trabajar de los flip-flops de esta tarea. Tenia entendido que los flipflops trabajaban de esta forma:
![image](https://user-images.githubusercontent.com/26121402/44948301-8b43cc80-adf1-11e8-8ffd-7839f9211d97.png)

Pero por como lo definieron en la actividad solo se encarga de cambiar el valor de la señal de salida prácticamente sin importar el valor de D. En el ejemplo del enunciado, darle a un flipflop una entrada D igual a "000000" entonces la salida siempre será "000000" porque al momento de existir flanco de subida Q copia el valor de D en ese momento, que es y siempre será 0.

Entonces ¿Cómo va la cosa? 

------
Otras dudas para intentar entender sus flip-flops
1) ¿Siempre que utilice un flip-flop **por primera vez** su entrada D es una serie de ceros del mismo largo que los inputs que utilizamos?

2)Si sucediera el caso:
```
{
  "sequential":[
    {"from": "input1","to": "ffd1","gate": "C"},
    {"from": "ffd1","to": "not1","gate": "Q"},
    {"from": "ffd1","to": "out1","gate": "Q"},
    {"from": "not1","to": "ffd1","gate": "D"},
    {"from": "input2","to":"ffd1","gate":"C"},
  ],
  "input":{
    "input1": [0,1,0,0,0,1],
    "input2": [0,1,0,1,1,0]
  }
}
```
¿Mi output sería?:
```
{
    "output":{
        "out1":[0,1,1,1,1,0],
        "ffd1": [0,1,1,1,1,0],
        "ffd1":[1,1,1,0,0,0]
     }
}
```

3) ¿Podemos suponer que los inputs tienen el mismo largo? (todos de n-bits)

~~Eso hasta ahora O: Si me pudieran aclarar esto creo que estaría lista (/>o>)/~~

**Comment by CristobalHV** [comment]
Una duda, podemos asumir que el circuito que nos entregarán tendrá un solo input? o puede tener varios? (flips flops en paralelo)

**Comment by Arcoirisky** [comment]
Vaya vaya vaya askdj puede que eso aclare muchas cosas. Entonces todo es un circuito de 1 bit de n iteraciones. con n el largo de la lista del input1.

pero si hay más de un input eso significaria que nunca un mismo flipflop puede unirse a más de un input. (como conectar ffd1 a un input1, luego hacer muchas cosas y despues reconectar el ffd1 a un input 2 en la misma entrada)

entonces cada compuerta se usa solo una vez ¿no?

**Comment by Geeermy** [comment]
@CristobalHV Puede tener varios _input_, por eso se sigue la convención ```input{i}```. Lo mismo con los _flip_flops_, se puede tener varios en paralelo (y por eso seguimos también la convención ```ffd{i}```).

@Arcoirisky Claro, recuerda que los circuitos no solo tienen _flip-flops_. Por ejemplo, puedo tener un circuito compuesto de 3 _inputs_, uno que vaya a la compuerta D del _flip-flop_, otro conectado a su compuerta C (como señal de control) y, finalmente, el tercero a una compuerta ```not```, para luego conectar la salida de ese ```not``` con una compuerta ```and``` que reciba, además, la salida del _flip-flop_ (compuerta Q). Ahí tienes un circuito que hace uso de varios _inputs_ y en el que usas el estado de tu _flip-flop_ como entrada para otra compuerta. Pero claro, no te pasaremos un circuito donde un _flip-flop_ reciba más de una señal para una misma compuerta, eso es incorrecto.

Espero que esto les aclare un poco más el panorama. 🙌

**Comment by CristobalHV** [comment]
me aclaró bastante el tema, gracias!
