### ISSUE TITLE
[T02] [PLACA] Error de Implementación con cierto valor de ROM

### ISSUE THREAD

**Issue by vijuarez** [IIC2343/syllabus#75]
Hola!

Estaba en el (terrible) proceso de debugear la placa, pero me salio algo inesperado. Intente poner una instrucción de INC B en la ROM, algo bien simple. Reemplaze las primeras dos instrucciones con `000000000001101010000000000000000`, asegurandome que la ROM siguiera teniendo el mismo tamaño. La implementación falla con el error:

`[DRC MDRV-1] Multiple Driver Nets: Net cu0/Q[1] has multiple drivers: cu0/memory_reg_0_255_0_0_i_3/O, cu0/respuesta_reg[3]/Q, cu0/respuesta_reg[3]__0/Q, cu0/respuesta_reg[3]__3/Q, cu0/respuesta_reg[3]__2/Q, and cu0/respuesta_reg[3]__1/Q.`

Esto no pasa si la ROM tiene solo 0s. Que puede ser?

Gracias

**Comment by Arcoirisky** [comment]
Por lo que estoy viendo, parece que tienes “cables cruzados” mira bien a dónde van los cables que te indica el error y encontrar dónde están chocando 😱

**Comment by frvalenzuela** [comment]
Complementado lo que dice @Arcoirisky. Revisa que las señales que declaraste y como están siendo conectadas.

El que no pase cuando la ROM tiene solo ceros puede deberse a que gran parte de las señales no están en funcionamiento (por ejemplo, el problema puede estar en mux que no fue seleccionado cuando estaba en solo ceros)

**Comment by vijuarez** [comment]
Hola! Creo que están en lo correcto, el error desapareció luego de reescribir una lógica que parecía estar enviando dos señales a la misma entrada. Gracias!
