### ISSUE TITLE
[Entrega 1E] Funcionamiento del Flip-Flop D

### ISSUE THREAD

**Issue by josefinaijb** [IIC2343/Syllabus#76]
Buenas!
Estoy intentando configurar el flip-flop entregado para poder recibir un input D de tipo STD_LOGIC_VECTOR y generar un output Q del mismo tipo, que realice el shift si se presiona el botón derecho. Logré que, al presionar el botón, los leds se movieran una posición a la derecha, pero si suelto el botón estos vuelven a su posición inicial.

- Intenté entonces definir que el output Q será el nuevo input D, pero Vivado me advierte que estoy generando un loop. 
- Otro de mis intentos fue crear un proceso en que, si se presiona el botón derecho, se sobreescribe el valor de una señal input D con la actual posición de los leds (esto indicando a los leds como puertos inout). Sin embargo, esto enciende todos los leds al mismo tiempo debido a que la arquitectura sobreescribe la señal indefinidamente.
- Finalmente, intenté agregar un rising_edge(btn(3)) (con debounced btn(3)) al código anterior para que solo se realizara a la subida de la señal, pero la placa no reconoce el input cuando presiono el botón.

Creo que no estoy interpretando bien el flip-flop que entregaron, pero aún así intenté crear uno propio dentro de la arquitectura de "shift_register", obteniendo los mismos resultados. El problema en definitiva es que no logro guardar la salida del flip-flop y modificar esta nueva salida para que sea la entrada del siguiente módulo.

por favor ayuda!

**Comment by CristobalHV** [comment]
Hola @josefinaijb !

Para las dificultades que entiendo que tienes en tu entrega, te daré los siguientes consejos:
- En la ayudantía recomendamos que utilizaran el módulo del flip flop D para ahorrarse trabajo y tiempo. La entrega puede resolverse de manera relativamente sencilla sin modificar este módulo.
- Si necesitas utilizar un componente más de una vez, te recuerdo que existe la opción de declarar múltiples instancias de un único componente.

Saludos y éxito en tu entrega!

**Comment by josefinaijb** [comment]
Gracias @CristobalHV !

Desafortunadamente no logré entender como utilizar el módulo sin modificarlo, pero logré crear el shift-register y solucionar mi problema. De cualquier forma, voy a seguir investigando con el tiempo que me queda a ver si puedo hacer un código más simplificado y que pueda utilizar el flip-flop entregado.

Muchas gracias por los consejos!
