### ISSUE TITLE
Tarea 2 | Petición de extensión de entrega.

### ISSUE THREAD

**Issue by MartinAracena** [IIC2343/Syllabus#76]
Quisiera saber si se pudiera tomar en consideración extender la entrega de la Tarea 2 dado que se traslapo con la fecha de proyecto de la entrega 2. Digamos por los mismos días que se traslaparon que son dos días.

**Comment by jmwielandt** [comment]
Hola,

Hacer que dices es complicado, ya que si movemos la entrega de la T2 va a quedar en la misma semana que la entrega 3 (sería la semana del 25 de mayo), y en ese caso si lo movemos a la semana del 1 de junio (ya sea la tarea o la entrega 3) estaría topando con la interrogación 3 y la tarea 3 (estimamos que se publicará durante esa semana).

Realmente mover la fecha de entrega de la tarea esos 2-3 días (miércoles, jueves y viernes) no los beneficia en absoluto porque genera más topes y más graves que dejándola como está, y nos da más carga de corrección a nosotros (tendríamos que estar revisando más evaluaciones en el mismo tiempo, en lugar de un poco más repartidas.

Quedo atento a tus comentarios!
