### ISSUE TITLE
[T02 Programada] Métodos en data para el Disassembler

### ISSUE THREAD

**Issue by brayanmoreno** [IIC2343/syllabus#76]
Hola, quisiera saber si el data que viene en el código binario para el disassembler solo utilizara los métodos mostrados en el ejemplo (MOV, INC, JMP) o puede utilizar cualquier otro para generar variables como por ejemplo AND, NOT, SHL, etc.

**Comment by Arcoirisky** [comment]
Considera que puede utilizar cualquier instrucción para generar sus variables. Además, piensa en el caso de que el bloque Data esté vacío y se comience inmediatamente en el main con una de esas instrucciones 🤔

**Comment by brayanmoreno** [comment]
y podría asumir que por lo menos estará el JMP a main?

**Comment by Arcoirisky** [comment]
¿Y que pasaría en el caso?

DATA:
CODE:
MAIN:
...

🤔

Respóndete estas preguntas y quizás tengas más en claro lo que deberías de estar pensando para esa parte: 

¿Qué es lo que lee mi Disassembler? 
¿Qué es lo que sabe mi Disassembler? 
¿Cual es su trabajo y como debería de ejecutarlo? 

Con eso deberías poder entender el porqué debe tomar todos los casos que puedan haber en el código binario que reciba :D 

Piénsalo, descansa un poco y recuerda que todo se ejecuta de la forma opcode-literal-opcode-literal...

**Comment by sfga** [comment]
> 
> 
> Considera que puede utilizar cualquier instrucción para generar sus variables. Además, piensa en el caso de que el bloque Data esté vacío y se comience inmediatamente en el main con una de esas instrucciones 🤔
> 
> (Edit)
> Ojo que con lo último me refiero a algo así versión binario:
> 
> DATA:
> CODE:
> ...

1-. ¿Cualquier instrucción? Considerando lo que se dijo [acá](https://github.com/IIC2343/syllabus/issues/49#issuecomment-483915739) no se pueden utilizar saltos en el bloque `DATA`, dado que la primera instrucción de salto se realiza para iniciar la ejecución de la etiqueta `MAIN`.

2-. ¿Cuál es el punto de querer utilizar cualquier instrucción en la sección `DATA`? Esta sección de código es previa a la sección `CODE` (donde se ejecuta del programa principal y sus subrutinas y donde sí es natural pensar que se utilizan instrucciones de todo tipo) y tiene como objetivo cargar variables (y no otra cosa). Por lo anterior, esperaría que en la sección `DATA` el código esté orientado a cargar valores en memoria de forma secuencial (como dice en el enunciado de la tarea) y también de forma concisa y depurada.

Por último, espero que puedan aclarar qué tipo de instrucciones se van a utilizar en la sección de "DATA".

**Comment by jmwielandt** [comment]
Hola! En el código assembly **sin compilar**, en `DATA` efectivamente no van instrucciones, solo declaración de variables.

El primer `JMP` siempre es a `MAIN`, pero este **lo coloca el assembler**.

Para cargar las variables en la memoria de datos usa las instrucciones que más te acomoden para lograrlo (mientras formen parte de la isa). Ya que esa parte se evaluará simulando y, mientras que la memoria de datos quede con los valores correctos en las posiciones correctas, todo estará bien.

**Comment by sfga** [comment]
Las dudas que puse sobre la sección `DATA` son del código "binario" recibido por el disassembler y no del código assembly de salida del disassembler (creo que tu respuesta es sobre esto último).

Pido disculpas si no se entendió esa parte.

**Comment by jmwielandt** [comment]
Ahhhh
Bueno, 
1. lo que puse en el edit de la respuesta anterior sobre los saltos, no diré más
2. que si quieren hacerlo de otra forma, sin el inc B, por ejemplo, pueden hacerlo. Podría ser usando únicamente MOVs, por decir algo. No los restringimos en este sentido.

**Comment by sfga** [comment]
> 
> 
> Las dudas que puse sobre la sección `DATA` son del código "binario" recibido por el disassembler y no del código assembly de salida del disassembler (creo que tu respuesta es sobre esto último).
> 
> Pido disculpas si no se entendió esa parte.

Agrego sobre lo anterior. ¿Vamos a tener que simular el código "binario" en el disassembler para saber los valores puestos en memoria para saber las variables declaradas?
