### ISSUE TITLE
Tope prueba proyecto

### ISSUE THREAD

**Issue by Hernan4444** [IIC2343/syllabus#76]
Hola a todos,
 Si tienes tope de examen, prueba o presentación el jueves 14:00 indicar que tienes.

Añadir también cualquier otra prueba, examen o presentación que tengas entre el miércoles y viernes durante todo el día para poder tener todos los casos en cuenta.

Para facilitar, seguir el siguiente formato:
> Dia - hora_inicio / hora_termino - Evento
> Comentario
> Ejemplo:
> Jueves 29 - 15:30 / 17:00 - Presentación del curso X
> La asistencia es obligatoria y si la prueba dura mucho no alcanzo a llegar.

Saludos!!

**Comment by jaimemiddleton** [comment]
29 C3 a las 15.30, 30 Edo a las 8.30

**Comment by mandrade2** [comment]
El jueves de 12:00 a 14:00 es la final de Innovacion ING2030. En teoría no debiese haber problema pero si hay atrasos en las presentaciones llegariamos más tarde.

Saludos

**Comment by Benespinoza** [comment]
Hola,
Tengo tope de:
Cálculo III 29 de Junio 5-6 módulo
EDO 30 de Junio 1-2 módulo

Saludos

**Comment by Zanfor** [comment]
Presentación final de ing de software

**Comment by jatrijori** [comment]
Para tener en cuenta,
Viernes 30 - 14:00: Examen Qim100a 
u_u

**Comment by Zanfor** [comment]
De 14:00  a 14:40

**Comment by IgnacioTobar** [comment]
Jueves 29 - 12:00 a 14:30: Final Innovación 

Hola, es la final de Innovación ese día, según lo que me dijo mi profesara es de 12:00 a 14:30 (mas tarde de lo que dijeron arriba, por lo que ya deben estar asumiendo que se va a tardar)

**Comment by fnmendez** [comment]
Miércoles 28 11:30/13:00 Charla Obligatoria de Intercambio
Viernes 30 15:00/17:00 Presentación Ing Software

**Comment by mromanl** [comment]
Jueves 29 - 15:30 / 18:30 - Calculo III
Viernes 30 - 8:30 / 11:30 - EDO

**Comment by nissimergas** [comment]
Miércoles 28  15:30/18:30 optimización

**Comment by ttapia** [comment]
Miércoles 28 9:00 - 11:30 Sistemas de Información

**Comment by hanavarrete** [comment]
jueves 29 - 15:30 probabilidades y estadísticas

**Comment by Onavila** [comment]
Miércoles 28 - 9:00 / 11:30 - Sistemas de Información

**Comment by Sgwa** [comment]
Jueves 29 - 15:30 Examen Probabilidades y Estadísticas.
Viernes 30 - 15:30 Examen Electricidad y Magnetismo.

**Comment by ivanwolf15** [comment]
Jueves 29 - 14.00 Presentación Ingeniería de software

**Comment by augustoal** [comment]
Miércoles 28 - 11:30 / 13:00 Charla Obligatoria de Intercambio

**Comment by jfcampos1** [comment]
Viernes 30 - 8:30 / 11:30 - tecnologías y aplicaciones web

**Comment by rorpis** [comment]
Miércoles 28 - 9:00/10:30 - Presentación Mecánica de Fluidos
Miércoles 28 - 14:00/15:30 - Presentación Ingeniería de Software

**Comment by nijulio** [comment]
Miercoles 28 - 14:00 Presentación Ing Software
