### ISSUE TITLE
[T02-Programada] Duda sobre instrucciones en el enunciado

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2343/syllabus#77]
Hola,

Quería saber si está bien que en las instrucciones NOT, SHL y SHR cuando se recibe los operandos A y B la operación es A = A ins A, como muestro en la imagen.
![image](https://user-images.githubusercontent.com/26437497/56408962-d3aae000-6244-11e9-948d-e7ef63e18c7e.png)

Saludos.

**Comment by Arcoirisky** [comment]
¿Lo dices porque B también guarda la operación con A?

**Comment by Jiruiz2** [comment]
Exacto, puedo entender el por qué sería de esa forma, pero igual quiero confirmar.

**Comment by Arcoirisky** [comment]
Realmente así son las instrucciones por cómo funciona la arquitectura de la alu que se está usando. Tal y como sólo B puede tomar literales, solo A es quién puede participar en esas operaciones que marcaste.

Esto depende de cada computador, en este caso es así :D y lo puedes encontrar en los apuntes también.
