### ISSUE TITLE
Problemas con conexion del LCD

### ISSUE THREAD

**Issue by srvasquez** [IIC2343/syllabus#77]
Hola estamos intentando conectar la LCD a la placa pero no nos funciona llevamos su buen tiempo intentando, modificamos el archivo .xcd y creamos una componente lcd_controller que recibe la señal del registro a y muxb como aparece en el enunciado y después eso bits los manda a la lcd, esta se actualiza con el clock, ahora en el xcd no ocupamos todos las conexiones ocupamos 8 en el JB para mandar los datos y 3 en el JC para las señales de control, ahora en el JC quedan señales que no ocupamos eso esta bien o no ?, de ante mano gracias

**Comment by Hernan4444** [comment]
#50 ahí se explica lo que tienes que hacer, en este caso tal como dices hay señales que no se ocupan y por lo mismo no se descomentan.

Saludos!!
