### ISSUE TITLE
Tarea 2 | Pregunta 2 | Acceder a un elemento del array

### ISSUE THREAD

**Issue by furzuadr** [IIC2343/Syllabus#77]
Hola! Estoy haciendo la pregunta 2 y no entiendo (o no me resulta) cómo acceder a un elemento dentro de un array. Lo que estaba tratando es acceder a la posición inicial + 1 (para acceder al segundo), pero por alguna razón esto no me funciona. Hay alguna forma de hacerlo?
Gracias!

**Comment by BSamilla** [comment]
Hola @furzuadr 
Si, hay una manera de hacerlo, fue explicado en la ayudantía para la tarea.

Saludos!
