### ISSUE TITLE
[T03-B] Orden json

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#77]
¿Podemos asumir que el Json estará ordenado? 
Es decir que podríamos ir armando el circuito de forma consistente linea por linea (sin componentes al aire -no conectados de alguna forma- en medio de la creación)

**Comment by JorgeBdelaT** [comment]
Hola, podemos asumir que la primera instrucción siempre tendra un input como from? Y que en caso de compuertas que necesiten dos señales (and, or, xor) los inputs estaran uno despues que el otro?

**Comment by Geeermy** [comment]
@JorgeBdelaT

1. Todos los _hashes_ de la lista del circuito tienen el atributo ```"from"```, no entiendo la pregunta. D:

2. Puedes asumirlo... pero su programa debería funcionar independiente del orden que les vamos a pasar, ya que fuerza bastante la estructura de los _tests_ (que podría beneficiar a uno y perjudicar a otros si dejamos una estructura fija...).

¡Éxito! :octopus:

**Comment by JorgeBdelaT** [comment]
@Geeermy me referia a que la primera instrucción sera de este tipo o no:

`{"from": "input1","to": "ffd1","gate": "C"}`
o
`{"from": "input1","to": "and1"}`

**Comment by jheysen** [comment]
Ah, no.

**Comment by Arcoirisky** [comment]
Llamarán componentes antes de darles valor? onda
```
{"from": "or3","to": "and2"}
{"from": "ffd8","to": "and2"}
{"from": "input3","to": "ffd8","gate": "C"}
```
siendo que ffd8 es usado recién en la tercera linea para que Q8 tenga un valor

**Comment by Geeermy** [comment]
Como dije anteriormente, su programa debería funcionar **independientemente** del orden en el que lo entreguemos. Trataremos de que quede ordenado, pero si haces que funcione independiente del orden es menos probable que falle por algo así. :eyes:

**Comment by paula-ds** [comment]
Por ejemplo esto puede ocurrir? {"from": "or3","to": "and2"} ya que según yo no sigue la estructura de los demás que contienen la llave "gate" :/

**Comment by Geeermy** [comment]
@paula-ds Sí, pueden existir, y está bien ya que ```gate``` está solamente asociado a los _flip-flops_.

Recuerda que los _flip-flops_ siguen la convención ```ffd{i}```, eso debería ser una gran guía de verificación antes de hacer uso de la llave ```gate``` (o bien ver si existe o no primero para ver qué hacer). :smile:
