### ISSUE TITLE
Foro 2: la retrocompatibilidad

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/Syllabus#78]
¡Hola a todos!

Estamos entrando en la parte del curso cuya materia da para hacer foros de discusión y pensé en aprovechar el inconveniente del emulador del computador básico en mac para traer un tema importante: la retrocompatibilidad.

### ¿Retro-qué?

A medida que vamos haciendo avances en las distintas tecnologías, protocolos y software, se van realizando cambios y por lo general hay que seguir dando soporte a versiones anteriores. ¿Dónde se ve esto? Por ejemplo, un código escrito en python 3.6 sigue funcionando en python 3.8 (por lo general). También en los computadores que son de 64 bits, podemos (o podíamos) ejecutar programas hechos para 32 bits. ¿Por qué lo digo en pasado? Por esto:

![image](https://user-images.githubusercontent.com/37153467/81766717-a743b080-94a4-11ea-960e-668320377563.png)

[Link a la noticia completa, es de octubre 2019.](https://www.genbeta.com/mac/como-revisar-todas-tu-apps-compatibles-antes-actualizar-a-macos-catalina)

ESA es la razón por la que el emulador que subimos a principios de semestre no funciona en Catalina, porque estaba compilado para 32 bits. Ahora está disponible también la versión de 64 bits. Sin embargo uno normalmente esperaría que al actualizar el sistema operativo en una de sus actualizaciones periódicas todos sus programas siguieran funcionando igual o mejor. 

A nivel de procesadores, si yo tengo un computador de 64 bits (esto es, que tiene soporte nativo para enteros de 64 bits) que soportan la ISA AMD64 (o x86-64/x64 como les gusta decirle algunos) puedo ejecutar programas que fueron compilados para la ISA x86 de 32 bits. Esta es una de las grandes gracias y por qué Intel le tuvo que "copiar" a AMD en la jugada y los Intel Itanium fracasaron al dar el salto a los 64 bits. Sin embargo, si mi procesador es de 32 bits no puedo correr programas de 64 con estas ISAs.

### Mac no está solo

Como dato, Mac no es el único que intenta eliminar la retrocompatibilidad con aplicaciones de 32 bits. Ubuntu también lo intentó para la versión 20.04 LTS pero la comunidad no se lo aceptó.

- [Ubuntu se deshace definitivamente del soporte de 32-bit](https://www.muylinux.com/2019/06/19/ubuntu-elimina-soporte-32-bit/)
- [Canonical concreta el soporte de 32-bit para Ubuntu 20.04 LTS](https://www.muylinux.com/2019/09/19/soporte-32-bit-ubuntu-20-04-lts/)

Sin embargo, en Windows 10 la retrocompatibilidad permanece y, si quisiéramos correr un programa compilado para la versión de 16 bits de x86 podríamos hacerlo a través de una máquina virtual de windows xp de 32 bits, es decir, a nivel de procesador el soporte sigue existiendo.

**Ahora les pregunto: ¿por qué creen que mac y linux intentan eliminar el soporte para aplicaciones de 32 bits? ¿Y por qué Windows no da pistas de que algo similar vaya a ocurrir? ¿Creen que la retrocompatibilidad es importante? ¡Desarrollen sus ideas! :D**

PD: este es un foro de discusión para ahondar más en la materia, si quieren aprovechar para hablar de otros temas relacionados como la retrocompatibilidad en las consolas, el smart delivery de la xbox series x o similares, pueden hacerlo ;D

**Comment by Arcoirisky** [comment]
Mucho texto
