### ISSUE TITLE
LCD texto en segunda línea

### ISSUE THREAD

**Issue by glbello** [IIC2343/syllabus#78]
Saludo a todos! Con mi grupo hemos intentado de todas la maneras posibles, pero no logramos mostrar texto en la segunda línea del LCD, solo logramos mostrar textos en primera línea con tiempo definido por nosotros de deleay, ¿cuál es el secreto de la segunda línea? :c

**Comment by Hernan4444** [comment]
el secreto está en el init donde hay que cambiar el modo
