### ISSUE TITLE
[T02- Programada] Duda Enunciado Disassembler

### ISSUE THREAD

**Issue by CmPoblete** [IIC2343/syllabus#78]
Hola, en el enunciado sale que el disassembler no debe poner el jmp al main, pero en el ejemplo que subieron si lo hace. Por lo tanto debemos poner el jmp o no?

**Comment by jmwielandt** [comment]
El output del **disassembler** es el archivo `ejemplo_código.s`, no tiene `JMP` a `main`.
Es decir, **el disassembler debe ELIMINAR** el `JMP` a `MAIN`.

**Comment by CmPoblete** [comment]
Gracias.
Otra pregunta, el disassembler tambien debe quedar separado en data y code?

**Comment by jmwielandt** [comment]
Eh... ¿te refieres al compilado o al código fuente?
El disassembler es el programa que deben hacer, al igual que el assembler.

`ejemplo_codigo.s` -[assembler]-> `ejemplo_binario.s`
`ejemplo_binario.s` -[disassembler]-> `ejemplo_codigo.s`
