### ISSUE TITLE
[T03-B] Jsons bonitos 

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2343/syllabus#79]
¿Cómo hacen para que los json les queden bonitos? :C Intenté con  "indent" pero me separa las listas y queda como:

```
{
    "output": {
        "Q1": [
            0,
            1,
            1,
            1,
            1,
            0
        ]
}
}
```

**Comment by jheysen** [comment]
A manito nomás....
O usando algo como Beautify en VSCode

**Comment by Arcoirisky** [comment]
buuu, morirán de largo mis jsons entonces sadjsadk Es mejor así que todo en una linea xD

**Comment by amartinezsilberstein** [comment]
@Arcoirisky prueba cargándolo como lista. Me parece que los archivos `.json` al final son solamente un largo `string` de caracteres, así que al cargarlo lo debería reconocer de igual manera.
