### ISSUE TITLE
Entrega Placa

### ISSUE THREAD

**Issue by glbello** [IIC2343/syllabus#79]
¿Habrá algún ayudante que me pueda recibir la placa desde la 13:00 en adelante? El profe envió mail avisando que las recibía a las 10:30 pero me atrasaré un poco mucho :(

**Comment by Hernan4444** [comment]
@glbello yo estaré en la oficina del profesor hasta las 14:00 (no más de esa hora). Despues tendrías que mandarme mail para ver si todavía estoy en la U, específicamente en el DCC.

Saludos

**Comment by glbello** [comment]
De verdad muchisimas gracias :") fijo estaré antes de esa hora
