### ISSUE TITLE
port map de un atributo std_logic a un valor fijo

### ISSUE THREAD

**Issue by FloValdes** [IIC2343/Syllabus#79]
Hola,
Cuando importo por ejemplo un registro, y hago el port map:
registroA: Reg port map(
        ...
        up => señalUpA,
        ...
    );

Si quiero que up siempre sea "1", cómo puedo hacerlo?
Hacer up => 1, me tira error, igual que up => "1". Cuando son std_logic_vector puedo hacer => "11" sin problemas, pero aquí no.

Gracias!

**Comment by FloValdes** [comment]
Ya me respondieron, se hace así por si alguien tiene la misma pregunta:
signal señalUpA : std_logic := '1';

**Comment by frvalenzuela** [comment]
Hola @FloValdes !

Aprovecho esta issue para recordar ser consistente con el tipo de dato, si una entrada o salida de algún componente es un `std_logic_vector` de un largo definido, deben asociarlo a una señal del mismo largo y también del tipo `std_logic_vector`. 

En cambio, si es el componente requiere una entrada o salida del tipo `std_logic`, la señal a ocupar debe ser un `std_logic`. En el caso de esta pregunta, el usar comillas dobles `"1"`, significa que se esta usando un `std_logic_vector` constante de largo uno, Por otro lado, con comillas simple `'1'`, se refiere a una `std_logic`, que coincide con el tipo de dato de entrada up en el componente Reg.

Saludos y éxito con la entrega!
