### ISSUE TITLE
[T01 PROG] - Ejercicio teórico: tipo de comportamiento

### ISSUE THREAD

**Issue by javierabao** [IIC2343/syllabus#8]
Hola!
Investigando sobre el ejercicio teórico, me bajó la duda de a qué se refieren exactamente con comentar sobre el tipo de comportamiento del circuito con ciclos. ¿Es describir estos circuitos en mayor profundidad? ¿o a hablar sobre algún aspecto específico? No me queda muy claro.

Gracias!

**Comment by jmwielandt** [comment]
Hola, 
Esperamos que expliquen _lo que pasa_ en ese tipo de circuitos. El **hint** debería ponerte en la línea de lo que debes desarrollar. Podrías pensarlo también desde la perspectiva de la pregunta 2 de programación.
