### ISSUE TITLE
Ambigüedad pregunta 1c (tarea 1)

### ISSUE THREAD

**Issue by amartinezsilberstein** [IIC2343/syllabus#8]
Hola!

Me parece que el enunciado es un poco ambiguo en esta parte. 

La pregunta se refiere a: **α = (10_{β})^{γ}** o **α = (10^{γ})_{β}**? Lo pregunto porque el análisis en cada uno de los casos sería totalmente distinto.

Saludos.

**Comment by FranLucchini** [comment]
O sea, te refieres a que en un caso "aplicamos la base" y después elevamos a γ, mientras que en el otro sería al revés? No me queda clara tu duda.

**Comment by amartinezsilberstein** [comment]
Exacto @FranLucchini, en el primer caso se define la base β y luego se eleva a γ, y en el segundo se eleva a γ y luego se define la base β.

**Comment by FranLucchini** [comment]
En ese sentido, debes asumir que primero viene el exponente y después se aplica la base, o más bien, que el número elevado está en la base β. La idea es trabajar sobre la secuencia: 
![codecogseqn](https://user-images.githubusercontent.com/11548573/44288323-4bec7c00-a246-11e8-98c8-aefdd86e66e1.gif), etc...

**Comment by amartinezsilberstein** [comment]
Gracias @FranLucchini. Se resolvió mi duda.
