### ISSUE TITLE
Problemas con credenciales al iniciar Vivado

### ISSUE THREAD

**Issue by ceosorio** [IIC2343/Syllabus#8]
Hola!
Tratando de hacer push a un repo en otro curso, tuve problemas con las creedenciales que guarda Windows. Al aprecer al iniciar Vivado, Windows me cambia las credenciales de GitHub.

IIC2233/Syllabus#34

Alguien sabe por qué sucede esto?

**Comment by jjaguillon** [comment]
Hola.

Es muy extraño lo que me comentas, dado que Github utiliza credenciales genéricas de Windows, y Vivado utiliza una credencial local mediante una Licence Key.

En ningún momento de la instalación ni del proceso de acreditación de la licencia de Vivado reescribe alguna credencial.

De igual manera, cuéntanos más sobre este detalle, por si se vuelve a repetir.

Saludos

**Comment by jjaguillon** [comment]
# Retirando lo dicho.

Se encontraron casos en que Vivado reescribe las credenciales Github.

Deben revisar si sus credenciales aparece **Personal token**

Si aparece lo que ocurre en la imagen, donde el usuario es: **xilinx-xhub-users**, deben eliminar esa credencial. 

![VivadoCredentials](https://user-images.githubusercontent.com/20802209/63056843-e792e580-beb6-11e9-96ca-416fb7ae67da.jpg)
