### ISSUE TITLE
Tarea 1: palabras pares e impares

### ISSUE THREAD

**Issue by IriSalazar** [IIC2343/syllabus#8]
Hola! podemos asumir que todas las palabras serán pares? Si son impares quedaría una letra solita al medio. O simplemente mostramos FFFF en el output?

Saludos!

**Comment by Hernan4444** [comment]
@IriSalazar puedes ser pares o impares. En el caso de las impares, tendrás una letra sola al medio que no afectará al palindromo puesto que tendrías que compararla a ella con ella misma.

Saludos ✌️
