### ISSUE TITLE
[T02 PLACA] Conectar placa

### ISSUE THREAD

**Issue by mundurragac** [IIC2343/syllabus#80]
Hola, estoy intentando conectar la placa a vivado desde una VM y no reconoce que esta conectada la placa.

Que puedo hacer??

**Comment by tomasrivera** [comment]
Hola, podrías especificar que SO y VM estás usando?

**Comment by mundurragac** [comment]
SO OSX y VM Ubuntu 18.10.0

**Comment by tomasrivera** [comment]
Me refiero al software que estas usando para montar la VM

**Comment by mundurragac** [comment]
Aaa VirtualBox

**Comment by tomasrivera** [comment]
Tal vez esto te podría servir:
https://www.virtualbox.org/manual/UserManual.html#usb-support

**Comment by mundurragac** [comment]
Ahi me funcionó, pero me tira este error... 
![Screen Shot 2019-04-19 at 12 51 26 PM](https://user-images.githubusercontent.com/30675023/56434284-f91a0700-62a1-11e9-9c00-cc51f58f1618.png)

**Comment by tomasrivera** [comment]
Prueba seleccioanndo el controlador de  USB 3.0 en la configuración de tu máquina virtual

**Comment by mundurragac** [comment]
> Prueba seleccionando el controlador de USB 3.0 en la configuración de tu máquina virtual

Me dice que es una configuración invalida

**Comment by tomasrivera** [comment]
Para eso tienes que instalar paquete de extensión.
Aquí muestra como hacerlo:
https://www.techrepublic.com/article/how-to-enable-usb-in-virtualbox/

**Comment by mundurragac** [comment]
Ahi funciono perfecto! Muchas gracias!

**Comment by Jj1martinez** [comment]
Hola! tampoco me reconoce la placa pero tengo particionado mi pc, estoy usando ubuntu 18.04.

**Comment by frvalenzuela** [comment]
Hola @Jj1martinez !

¿Activaste los controladores USB como se menciona en el Tutorial 1?

Saludos!

**Comment by Jj1martinez** [comment]
Grande!
