### ISSUE TITLE
Tarea 2 | Problema al instalar el emulador en Ubuntu

### ISSUE THREAD

**Issue by kdroppelmann** [IIC2343/Syllabus#80]
Hola! Llegue al paso 5. del tutorial para instalar el emulador y cuando se terminó de instalar me apareció lo siguiente:

![IMG_6162](https://user-images.githubusercontent.com/37154160/81841755-e7447b00-9518-11ea-82f3-96b87efa08cc.jpg)

Que debería hacer?

**Comment by ceosorio** [comment]
Hola @kdroppelmann!

Cuando lo hice yo, me salieron los mismos warnings, pero si das a continuar no deberías tener problemas :)

Avísame como te va

**Comment by kdroppelmann** [comment]
Muchas gracias! Apreté continuar y se finalizó la instalación. Pero ahora estoy teniendo problemas para ejecutar el emulador, porque no se cual es la ruta en donde se encuentra :( . Veo que en el tutorial está en home/<usuario>/.wine, pero no es el caso.

**Comment by kdroppelmann** [comment]
Muchas gracias! Apreté continuar y se finalizó la instalación. Pero ahora estoy teniendo problemas para ejecutar el emulador, porque no se cual es la ruta en donde se encuentra :( . Veo que en el tutorial está en home/usuario/.wine, pero no es el caso.

**Comment by ceosorio** [comment]
Que bueno que lograste instalar todo! 😄 

La carpeta `home/usuario/.wine` hace referencia a la carpeta que usa wine, y por default está oculta, ya que las modificaciones se hacen a través de wine (no queremos tocar esa carpeta, así que está bien). 
Lo que tú quieres hacer es pararte en la carpeta en donde está el ejecutable del **emulador** `emuIIC2343.exe` y sigues con el **paso 6** de la [Wiki.](../wiki/Instalaci%C3%B3n-del-emulador-del-computador-b%C3%A1sico-en-Ubuntu-18.04-LTS)

De forma alternativa puedes hacerle click derecho al ejecutable. Ahí la primera opción que te aparecerá será abrir el `.exe` con wine.

**Comment by kdroppelmann** [comment]
Bueniisimo! Muchas graciaas ya se abre el emulador y puedo probar archivos! 
Duda extra: es normal que si muevo un poco la pestaña del emulador como que se ponga negro y tenga que volver a abrirlo para que funcione?

**Comment by kdroppelmann** [comment]
Esto aparece en mi terminal:

![IMG_6166](https://user-images.githubusercontent.com/37154160/81853024-e8ca6f00-9529-11ea-8594-42d414517fbc.jpg)

**Comment by ceosorio** [comment]
@kdroppelmann, que extraño. ¿Puedes ver si te sucede el mismo error cuando tratas de agrandar la ventana?

Y también mandarme un pantallazo de como se ve la ventana también (cuando se va a negro), para intentar replicar tu problema.

Quedo atenta :)

**Comment by kdroppelmann** [comment]
Esto aparce cada vez que abro el emulador:
![IMG_6171](https://user-images.githubusercontent.com/37154160/81857193-e4a15000-952f-11ea-891b-c0a2a21d977f.jpg)
Esto pasa si agrando la ventana:
![IMG_6170](https://user-images.githubusercontent.com/37154160/81857237-f4209900-952f-11ea-8042-888ed70869f0.jpg)

Gracias!

**Comment by ceosorio** [comment]
Yap, en este caso, es normal que se te pongan esas lineas negras cuando lo agrandas hacia el lado. Lo que **no** es normal es que se te vaya a negro toda la ventana. El problema que te aparece en consola es que wine no está encontrando unos .dll que se instalan cuando haces la instalación del .NET 4.0

Ahora necesito algunas cosas para seguir:
- Tu versión de Ubuntu
- Si estás corriéndolo en una máquina virtual (Por ejemplo VirtualBox), o usando una partición
- Que corras en consola `winetricks list-installed` y me digas que sale.

**Comment by kdroppelmann** [comment]
Ok, aquí va la info:
- Mi versión de Ubuntu es 18.04.4
- No uso ni máquina virtual ni partición. Borre el sist operativo de Windows e instalé solo Ubuntu.
- Lo que me aparece es lo sgte:
![IMG_6172](https://user-images.githubusercontent.com/37154160/81859852-de14d780-9533-11ea-8e66-9d8ff01113b8.jpg)

**Comment by ceosorio** [comment]
Entonces, probaremos lo siguiente:

- Abre la terminal y corre `wine winecfg`
- Coloca que la versión a imitar de windows sea **Windows 7** (aparece abajo de la ventana).
- Anda a la pestaña **Librerías (o Libraries)**
- Revisa si en sustituciones existentes aparece  **mscoree**, y que esté en modo **native**
- Si no aparece, en la parte de nueva sustitución de librería, busca `mscoree` y coloca `Add`
- Ahora que `mscoree` aparece en la lista, seleccionalo y haz click en `Editar`.
- Selecciona el orden de carga a **native(windows)**
- Haz click en `Aplicar` y luego `Aceptar`
- Intenta correr el emulador de nuevo y me dices lo que ahora aparece en consola si sigue el error.

**Comment by kdroppelmann** [comment]
Hice todo lo anterior y resulta que la librería si estaba  y el orden de carga si estaba en  native(windows). Igualmente corrí de nuevo el emulador, pero los errores siguen siendo los mismos.

**Comment by ceosorio** [comment]
No logro replicar tu error :(
Sin tener en cuenta el problema de mover la ventana, te funciona el emulador?

**Comment by kelseyfranken** [comment]
Hola! a mi me aparece un error en mi terminal cuando abro el emulador, pero, si se me abre. Habrà algun problema cuando lo use? 
![Captura de pantalla de 2020-05-14 11-05-28](https://user-images.githubusercontent.com/42187498/81951555-4bc41080-95d3-11ea-854c-9fb1ce8efd88.png)

**Comment by ceosorio** [comment]
Hola @kelseyfranken!

Prueba corriendo uno de los ejemplos que están en el Syllabus :) si te funciona, no tendrás problema con tu tarea. 

Ánimo! ✨

**Comment by kdroppelmann** [comment]
@ceosorio hasta ahora los txt de ejemplos me funcionan bien! Asi que tienes razón, no creo que importen eso errores para la tarea.
 Muchas muchas gracias por tu ayuda!!
