### ISSUE TITLE
Trabajo en paralelo Entrega 2

### ISSUE THREAD

**Issue by Pipelao** [IIC2343/Syllabus#80]
Hola,

Quisiera hacer una pregunta acerca de cómo trabajar con github y el proyecto de Vivado en la entrega 2. Si uno de los integrantes crea el proyecto, ¿debo subir todas las carpetas adjuntas a esta incluyendo aquellas que se piden no subir en el enunciado para que los demás integrantes puedan abrir el proyecto?, ¿es posible que los demás integrantes trabajen en el mismo proyecto?, en caso que no sea así, ¿es recomendable que cada integrante cree un proyecto de Vivado?. La pregunta se resume en cómo nos recomiendan trabajar con github y los proyectos de Vivado, por ejemplo crear ramas para cada integrante, crear diferentes proyectos, etc.

Gracias de ante mano.

**Comment by frvalenzuela** [comment]
Hola @Pipelao !

Respondiendo a tus dudas:

> ¿debo subir todas las carpetas adjuntas a esta incluyendo aquellas que se piden no subir en el enunciado para que los demás integrantes puedan abrir el proyecto?

Todas las carpetas que se piden no subir en el enunciado no son necesarias para que los demás integrantes puedan abrir el proyecto. Mientras las rutas relativas y los nombres de los archivos se mantengan consistentes a la hora de creación del proyecto debería bastar para que cualquier integrante pueda abrirlo por medio del .xpr

> ¿es posible que los demás integrantes trabajen en el mismo proyecto?

Si es posible, y les recomiendo que trabajen de dicha forma.

> ¿es recomendable que cada integrante cree un proyecto de Vivado?

No lo recomiendo, puesto que el nombre de las ruta relativas y sources adicionales podría variar bastante. Sobre eso destaco  que los archivos y las entidades, así como sus componentes e instancias sean siempre consistentes, tanto en nombres, cantidad de entrada y salida, y el largo de cada una de estas, así también como sus señales.

Espero poder haber aclarado todas tus dudas.

Saludos!

**Comment by Pipelao** [comment]
Gracias @frvalenzuela
