### ISSUE TITLE
Simulación de archivo con process

### ISSUE THREAD

**Issue by SergioGazali** [IIC2343/Syllabus#81]
Hola!
Estoy tratando de hacer una simulación de un archivo en el que uso process, y por lo que he probado parece que tengo problemas en la simulación con la señal que proceso (la he cambiado para probar). Tengo cosas como esto:
![Screenshot from 2019-10-03 20-27-05](https://user-images.githubusercontent.com/42220325/66170918-a39da080-e61c-11e9-92e8-a458c50118ad.png)
Donde la señal cambia entre 0 y X (en rojo) en el tiempo en que le asigno 0, y entre 1 y X cuando debiera ser 1.
Es común que el process tenga fallas al simular o el problema debe ser otro?

Muchas gracias!

**Comment by rjdelrio** [comment]
estas usando un for en tu archivo de simulacion para generar los 0 y 1 del clock?

**Comment by rjdelrio** [comment]
sube tus archivos al repositorio de github para que pueda verlos y ayudarte :D

**Comment by SergioGazali** [comment]
No estaba simulando bien el clock! no había visto la parte del loop en `clocking: process` en el archivo de la simulación pero ya lo solucioné. Muchas gracias!
