### ISSUE TITLE
Tarea 2 | Pregunta teórica 3 | Duda sobre la alternativa 5.

### ISSUE THREAD

**Issue by nhorellana** [IIC2343/Syllabus#81]
Hola! En la pregunta 3 de las preguntas teóricas hay una alternativa que dice: "Los bytes que usa UTF-8 con BOM son ï »?". A que se refiere con "ï »?" ?

Gracias!

**Comment by jjaguillon** [comment]
Hola @nhorellana . Se refiere a que la representación obtenida de los bytes que utiliza la marca de orden de los bytes es:  ï »? 

Es decir, que si lees los bytes y los representas en UTF-8, aparecerá:  ï »?

**Comment by kelseyfranken** [comment]
Hola, da lo mismo si es: "?" o "¿" ?

**Comment by nicoparraguez** [comment]
Me uno a la pregunta de kelseyfranken

**Comment by silvamatias** [comment]
también me uno a la pregunta de kelseyfranken

**Comment by jmwielandt** [comment]
@kelseyfranken @nicoparraguez @silvamatias 
No, no da lo mismo, son carcteres distintos que tienen una codificación distinta.
