### ISSUE TITLE
[T02 Placa] Duda when

### ISSUE THREAD

**Issue by aeperalta** [IIC2343/syllabus#81]
Puedo hacer lo siguiente(?):

`a <= '1' when ([alguna condicion]) else '0'; `

Saludos!

**Comment by frvalenzuela** [comment]
Hola!

**No**, eso esta considera entre los _statments_ `if/else`. (si bien no se escribe el if propiamente tal, hace exactamente lo mismo).

Si necesitas hacer un condicional, procura ocupar muxes, con la sintaxis `with/select`. Como dice el enunciado.

Si tienes dudas en como ocupar dicha sintaxis no dudes en consultar.

Saludos!
