### ISSUE TITLE
Tarea 2 | Administrativa | Editar preguntas teoricas.

### ISSUE THREAD

**Issue by nhorellana** [IIC2343/Syllabus#82]
Hola! Las preguntas teóricas por canvas solo se pueden entregar una vez? Quise guardarlas al cerrar la pestaña y sin querer entregue el examen :(

**Comment by jmwielandt** [comment]
Hola,

Esto es importante, tienen un único intento y no hay posibilidad de modificar sus respuestas.

Saludos!

**Comment by nhorellana** [comment]
La verdad es que en ninguna parte salía esa información ni en el enunciado de la tarea ni en el cuestionario de Canvas, sobretodo cuando es parte de una tarea con largo plazo no es para nada intuitivo que haya un único intento. No hay ninguna posibilidad de poder poner mis respuestas? Ya que básicamente están en blanco.

O F no más? :(

**Comment by jmwielandt** [comment]
Hola,

Te acabo de dar un intento extra.

Saludos!

**Comment by nhorellana** [comment]
Muchas gracias! <3
