### ISSUE TITLE
[Tarea 3] [Programado - B] Inputs AND, OR, XOR

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#82]
Hola, entiendo que para el flip-flop las puertas serán C y D, y salida Q
pero para los AND, OR y XOR, cuáles son?
No quiero asumir algo y que después en los json uds usen otra nomenclatura.

**Comment by Geeermy** [comment]
¡Hola!

Como se puede ver en el ejemplo (con la compuerta ```not```) y por lo conversado en los últimos comentarios de esta _issue_: #65, no se definen puertas directas en los _hashes_ de dichas compuertas. Puedes asumir que si tienes compuertas del tipo ```and, or, xor```, siempre entrarán dos señales y saldrá una sola, y el atributo ```gate``` solo existirá si una de las componentes relacionadas es un _flip-flop_. Lo mismo aplica para la compuerta ```not```, solo que tendrá una señal de entrada y una de salida.

¡Éxito! 🐧
