### ISSUE TITLE
[PLACA] Signal a Signal

### ISSUE THREAD

**Issue by Taeval** [IIC2343/syllabus#82]
Es válido tener una señal que recibe una palabra de otra señal? 
Por ejemplo, en la foto se declaran las señales:
![image](https://user-images.githubusercontent.com/37159657/56442086-5a9b9f00-62bd-11e9-84ce-bc66f6e096d7.png)

Y más tarde hago un with/select de la forma:
![image](https://user-images.githubusercontent.com/37159657/56442118-7dc64e80-62bd-11e9-9950-e068f13091e2.png)

**Comment by frvalenzuela** [comment]
Hola!

Si eso es posible! Solo como consejo, asegúrate de que dichas señales al conectar señales entre si no se generen ciclos o se "crucen" cables (como por ejemplo dos señales se conecten a un mismo output).

Pero como esta en tu ejemplo, suponiendo que no hay problema en lo que recibe suma. Esta bien!

Saludos!
