### ISSUE TITLE
Librerías y manejo de números

### ISSUE THREAD

**Issue by SergioGazali** [IIC2343/Syllabus#82]
Hola! es legal usar librerías como
```
use IEEE.std_logic_unsigned.all;
USE IEEE.NUMERIC_STD.ALL;
```
Para hacer operaciones como
```
else
    counter <= counter + 1;
end if;
```
o no se puede??
Muchas gracias

**Comment by frvalenzuela** [comment]
Hola @SergioGazali !

Ese tipo de operaciones solo se pueden hacer dentro de componentes secuenciales dentro de un computador básico, es decir que tenga una entrada algún reloj. 

En componentes combinacionales, como la ALU o la Control Unit, esta prohibido. Ahí deben ocupar componentes hechos con compuertas lógicas para realizar sus operaciones.

Saludos!

**Comment by kmhaller** [comment]
Osea no se puede ocupar if en la ALU?

saludos

**Comment by frvalenzuela** [comment]
Hola @kmhaller !

El uso de if esta prohibido en la ALU. Debe ser realizada solo con compuertas lógicas. El uso de if solo puede ser ocupada dentro del stament de process, el cual solo se puede ocupar dentro de circuitos secuenciales, los cuales son los dependientes de clock.

Saludos!
