### ISSUE TITLE
Dudas tarea 1

### ISSUE THREAD

**Issue by lfbesa** [IIC2343/syllabus#82]
Tengo varias dudas con respecto al enunciado de la tarea 1. 
- Primero, al pasar a binario el 342 no queda el número que sale ahí, por lo que me da que en realidad deberia ser V en vez de X el resultado.
- No entiendo por que en la segunda prueba de la parte 1 (12312312313-4-int) sale que el resultado es "y" si dice que debe ser un int.
- En la parte 2 dice que se deben mostrar los resultados como señales P-C-Z-N y en el primer caso (4 + 7) dice que la señal N esta activa pero no hay ni resta de A-B ni A<B
- Para que la señal N este activa, ¿debe existir una resta y el A<B o solo uno de las dos operaciones?
- Por último, ¿A qué se refiere con el AND y OR entre 2 y 7?¿Como se aplican esas tablas de verdad con esos numeros?
Gracias

**Comment by Hernan4444** [comment]
@lfbesa en el ejemplo en el enunciado sobre el archivo resultante, los datos no son los correctos... solo son para que vean el formato.  (Eso responde a tus prguntas 1,2,3 y 4) 😅 

Sobre la señal N, precisamente, debe cumplirse ambos casos para que N se active.

Para aplicar and y or a números tienes que transformarlos a binario y aplicar a cada bit la tabla de verdad.

Ejemplo 2 AND 3 es lo mismo que "10" and "11". Por tabla de verdad comparamos el primer bit el cual dá 0 y el segundo bit da 1, así que el resultado es "10" = 2. Ahora es desafio tuyo ver que sucede con las señales 😄 

Saludos!!!
