### ISSUE TITLE
Tarea 2 | Pregunta 1,2 y 3 | ¿Qué comandos de assembly se pueden usar?

### ISSUE THREAD

**Issue by kylevon** [IIC2343/Syllabus#83]
O en su defecto, ¿cuales de estos comandos no se pueden usar? (slides clase 5)
![image](https://user-images.githubusercontent.com/46159219/81872726-4ec5ef00-9548-11ea-84d1-eb9e0a17ec11.png)
![image](https://user-images.githubusercontent.com/46159219/81872742-5d140b00-9548-11ea-9bb2-628018b29286.png)

**Comment by jmwielandt** [comment]
Hola,

Si el emulador reconoce alguna instrucción, la puedes usar.

Saludos!
