### ISSUE TITLE
Donde esta/estara Form de Evaluación

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2343/Syllabus#83]
Hola,
Donde va a estar el Form de Evaluación y cuando debe ser respondido??

Saludos!!

**Comment by frvalenzuela** [comment]
Hola Ignacio ! 

El form estará en disponible como link por en el README del syllabus el lunes en el horario de ayudantía. Y tendrán 48 horas para responderlo (ósea hasta el miércoles 9 de Octubre a las 17 horas).

Saludos !

**Comment by Snorlax8** [comment]
Hola!

Disculpa, @frvalenzuela, ¿cero posibilidad de extender el plazo de la primera evaluación? Me confundí con las fechas y no alcancé a responderla.

Quedo atenta, perdón las molestias.

**Comment by frvalenzuela** [comment]
Hola @Snorlax8 !

Lamento informar que no existe posibilidad de extender el plazo. Para las próximas evaluaciones, favor de responderlas en las fechas correspondientes.

Saludos!

**Comment by Snorlax8** [comment]
Ok, gracias!
