### ISSUE TITLE
[T02 - Programada] - Exceso de memoria

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2343/syllabus#83]
Hola,

Quería saber que debemos hacer en caso de que nuestra memoria se llene,  lanzamos una excepción o debemos sobreescribir de alguna manera o simplemente esto nunca pasará en los ejemplos con que nos corrijan.

Saludos.

**Comment by Arcoirisky** [comment]
Hola! Eso no pasará en los ejemplos que corramos para esta tarea pero tengan cuidado de no llenar su pobre memoria de 256 ranuras uou)/
