### ISSUE TITLE
Problema grupo desarmado (ex grupo 19)

### ISSUE THREAD

**Issue by SalvadorProductions** [IIC2343/syllabus#83]
Hola! Antes del último cambio eramos el grupo 19, pero luego cada integrante de nuestro grupo quedó en un grupo diferente (yo en el grupo 3, Sebastian en el 14...), somos un grupo desarmado con distintos ayudantes :(

Los integrantes del grupo somos:
- Lucas Gramsch
- Sebastián Calderon
- Diego Molina
- Nicholas Mc-Donnel
- Pablo Barría (Yo, encargado de la placa)

Ojalá se pueda solucionar el problema, saludos!

**Comment by Hernan4444** [comment]
@SalvadorProductions muchas gracias por avisar. Mañana **debe** estar resuelto el problema.

Saludos!

**Comment by FranLucchini** [comment]
@SalvadorProductions debería estar todo solucionado ahora, deberían poder acceder al repositorio correspondiente al grupo 21.

**Comment by SalvadorProductions** [comment]
@FranLucchini Al parecer ya estamos juntos :) muchas gracias por volver a unirnos. Saludos!
