### ISSUE TITLE
[Tarea 3] C = 1 y D = 1 en flip-flop

### ISSUE THREAD

**Issue by amartinezsilberstein** [IIC2343/syllabus#83]
Hola!

Podemos asumir que la los inputs de un flip-flop no serán ambos 1 a la vez?

**Comment by Geeermy** [comment]
¡Hola!

¿Por qué asumirías eso? El valor de D solo define qué es lo que entra, y la transición C = 0 a C = 1 define que entrará efectivamente (sé que lo cerraste, pero prefiero aclararlo para tus compañeros también).

¡Éxito! 🐃
