### ISSUE TITLE
[Entrega 2] Duda con entrada de la CU

### ISSUE THREAD

**Issue by ceosorio** [IIC2343/Syllabus#84]
Hola!
Estaba viendo el diagrama de la entrega y me di cuenta que la Control Unit tiene una entrada de 20 bits. Trate de entender el resto del diagrama de acuerdo al enunciado y logre hacerlo en parte, pero sigo sin entender por qué son 20 de entrada.

Se ocupan efectivamente los 20 bits (son necesarios) o podriamos llegar a ocupar menos de 20?

**Comment by frvalenzuela** [comment]
Hola @ceosorio !

Tienen 20 bits para que tengan una mayor libertad para diseñar sus opcodes y su control unit (CU). También da la posibilidad de agregar más instrucciones para futuras entregas, o implementar más de las que se piden si es que quieren probar algo en especifico.

Así que no hay problema si es que no llegan a ocupar todos los bits, sin embargo la CU debe recibir los 20 bits, aún en el caso de que no se ocupen todos (esto último solo para mantener consistencia con el diagrama).

Saludos!

**Comment by ceosorio** [comment]
@frvalenzuela Gracias! 

Ahora me quedó mas claro 😄
