### ISSUE TITLE
[Tarea 3 - Programable A] Estado inicial flipflops

### ISSUE THREAD

**Issue by amartinezsilberstein** [IIC2343/syllabus#84]
Hola!

Podemos asumir que la salida de un flip-flop (Q) se encontrará siempre en un estado conocido cuando sea utilizada como `input` para otro componente o como `output` del sistema? Es decir, que no ocurrirá que se conecte algo a dicha salida sin que el flip-flop haya sido escrito anteriormente, pues en ese caso el valor sería desconocido.

**Comment by Geeermy** [comment]
¡Hola!

No entiendo mucho tu pregunta... pero el estado Q no cambiará salvo que nos encontremos en un flanco de subida. Tampoco le puedes conectar algo a la puerta Q de un _flip-flop_ para cambiar su estado "a la fuerza", por así decirlo (que me parece es lo que piensas).

Si no es así, por favor trata de aterrizar tu pregunta para responder mejor. 😄

**Ojo:** Estamos en la parte A, no sé si te importa tanto esto dado que ustedes no van a simular y no les interesa el atributo ```input``` del JSON.

**Comment by amartinezsilberstein** [comment]
No sé muy bien como formular la pregunta. A lo que voy es que cómo sabemos el valor inicial de la entrada `C` y de la salida `Q` de los flip-flops? Al momento de que llegue el primer `input` no se sabrá si el cambio corresponde a un flanco de subida o si mantuvo su estado, y en el caso de que no fuese un flanco de subida no sabríamos el valor inicial en `Q` y no podríamos ocuparlo en el circuito.

-

**Comment by Geeermy** [comment]
Ah, entiendo.

**Como se dice aquí:** #66, los valores de Q de **todos** los _flip-flops_ se inicializan en 0. Puedes asumir lo mismo para los valores de las compuertas C.

Y vuelvo a insistir, ¿por qué necesitas esto para la parte A? no debiese ser necesario (pero si aclarar tu duda te sirve, genial c:).

¡Éxito! 🐚

**Comment by amartinezsilberstein** [comment]
Muchas gracias @Geeermy . Quizá, como dices, no tiene ninguna implicancia para la parte A, pero quería tener claridad del enunciado completo.

**Comment by ranieto** [comment]
@Geeermy, o sea que si, digamos, en el ejemplo del enunciado, el primer valor del input fuese '1', se consideraría como flanco de subida? Si este es el caso, entonces a qué valor se actualizaría Q? O en otras palabras, qué entraría por la compuerta D? Sería basado en el estado inicial de Q?

**Comment by BSamilla** [comment]
@ranieto 

No, el flanco de subida es cuando el valor de C cambia desde 0 a 1.

Si está en 1 o en 0, así como también en el flanco de bajada (desde 1 a 0), no actualiza el valor de Q.

Saludos!

**Comment by ranieto** [comment]
@BSamilla, no estoy entendiendo entonces, porque @Geeermy dijo en su comentario que los valores de las compuertas C se inicializan en 0. ¿Por qué no se consideraría un flanco de subida si es que el primer input es '1', entonces?

**Comment by BSamilla** [comment]
Si, perdón estaba respondiendo desde el lado de la teoría del funcionamiento, no lo había relacionado con el comentario de @Geeermy . (Perdón por la confusión)
Es ese caso si, dame unos minutos para confirmarte y a que valor debería actualizar.

:)

**Comment by BSamilla** [comment]
@ranieto 
Te confirmo información:
Ambas compuertas (Q y C) se inician en 0, como se dijo por @Geeermy .
Si llegara a pasar que el primer input es 1, efectivamente cuenta como flanco de subida y por ende actualiza el valor de Q.
En cuanto al valor a actualizar es el que corresponde dependendiendo del circuito. Vale decir para el caso del ejemplo seria actualizado a 1. (Dado que Q  se inicia en 0 y luego pasa por la compuerta NOT).

No dudes en consultar si no te queda claro.
Saludos!

**Comment by ranieto** [comment]
Eso responde mi duda. Muchas gracias, @BSamilla.
