### ISSUE TITLE
Tarea 2 | Pregunta 1 | "Circuitos en serie"

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2343/Syllabus#84]
Tengo dudas sobre a que se refiere con "conectar en serie" en la pregunta 1.2 y 1.4. Se refiere que el resultado de una es la entrada de la otra?

![image](https://user-images.githubusercontent.com/42476356/82133085-69e96680-97b5-11ea-884b-9a6dd609f249.png)

**Comment by bpardobravo** [comment]
Me sumo a esta pregunta y le añado: los comparadores (tanto el 1.2 y 1.4) son solo de igualdad o también de mayor-igual y menor-igual?

**Comment by jmwielandt** [comment]
@lfuenzalida2 @bpardobravo 
Hola, sí, en serie significa eso: que al menos una de las salidas de uno de los componentes sirva como entrada para el segundo.

Son comparadores como los del computador básico, lo que hacen es restar las dos entradas.
