### ISSUE TITLE
labels generales

### ISSUE THREAD

**Issue by rjdelrio** [IIC2343/syllabus#84]
los labeles puedes tener espacio entremedio por ejemplo "caso 1:" lo pregunto por que de ser asi podria existir un label que sea ADD A,3pp4

**Comment by Arcoirisky** [comment]
Puedes asumir que los labels serán de una sola palabra (“caso 1” no sería un label pero “caso1” si) 

También que serán instanciados de forma en que no le acompañe una instrucción, por ejemplo:

... ; código 
NombreLabelCualquiera: ; esto es un label
... ; código
