### ISSUE TITLE
Tarea 1 - Numeros negativos

### ISSUE THREAD

**Issue by fcgfaura** [IIC2343/syllabus#84]
Hola!, nos pueden dar números negativos en el input ??

**Comment by Hernan4444** [comment]
@fcgfaura no usaremos numeros negativos para esta tarea 👍 

Saludos!

**Comment by jpgonzalez4** [comment]
Si nos entregan solo números negativos, se mantienen los mismos bytes utilizables de la tabla o se incrementan en uno al no haber dígito de signo?

**Comment by Hernan4444** [comment]
@jpgonzalez4 **no** usaremos negativos.

Saludos.

**Comment by FranLucchini** [comment]
Lo importante es que en la parte 1 no probaremos con número que lleguen a resultados negativos.

**Comment by IriSalazar** [comment]
Hola! Ya que estamos hablando de números negativos, quisiera preguntar si un exponente puede ser negativo, ya que el resultante de este no es un numero negativo, si no un numero muy chiquitito.

**Comment by Hernan4444** [comment]
@IriSalazar en ese caso si pueden ser negativos porque necesitamos trabajar con numeros de la forma `0.xxx` y ese caso solo se dá con exponentes negativos.

Saludos!!

**Comment by vabesa** [comment]
@Hernan4444 Tengo la misma duda que @jpgonzalez4 y por lo menos a mi tu respuesta no me la aclaro mucho

**Comment by Hernan4444** [comment]
@vabesa para empezar esa pregunta fue editada despues que respondí y por lo mismo mi respuesta no ayuda mucho a esa pregunta 😞. Y si, se deberá aumentar en el rango de valores puesto que el bit de signo ya no existe y es un bit más para representar números positivos.  Por ejemplo el int ya no llegaría hasta el 32767 sino hasta el 65535. Espero haber resuelto tu duda.

Saludos! ✌️

**Comment by vabesa** [comment]
@Hernan4444 Gracias!

**Comment by cjgazali** [comment]
En TODA la tarea NINGÚN input será negativo?
En el test.txt que muestran en 3. Metodología hay una entrada '-2 || 2'...

**Comment by Hernan4444** [comment]
@cjgazali ese test era solo para que vieran el formato de input. Al final decidimos que no verán negativos en los input. (Pero puede pasar que una operación si genere negativos en la parte 2 pero ahí no nos interesa saber el resultado, solo las señales solicitadas).

Saludos!!

**Comment by Tyrell-Wellick** [comment]
Hola a todos! A partir del análisis de esta issue me surgieron un par de dudas:

1) Qué pasará con el bit de signo en float y double?, ese bit que ahora tendremos "libre" lo agregamos al significante o al exponente en la representación?. @Hernan4444 apelando a tu respuesta a @vabesa en el cambio de los límites, cuáles serían en estos casos?  

2) Qué pasa con la representación en binario en el caso que nos den un número cuyo valor en base 10 supera al 3,4*10^(38), ejemplo 5,2*10^(38)(asumiendo que los límites corresponden a los del enunciado) y cuyo tipo sea float?. Debemos asumir que dicho número posee una representación posible en el tipo double y que por lo tanto esa será la representación binaria que debemos CORTAR?. 

3) En caso de ser afirmativa la respuesta a la segunda pregunta en 2), qué pasaría por ejemplo con el número cuyo valor en base 10 supera al 1,79*10^(308)? Asumimos que existe un "Decimal triple" con 12 bytes cuyo rango orientativo admite su representación?, qué hacemos acá con el corte?

Gracias de antemano, espero ansioso sus respuestas. Saludos

**Comment by Hernan4444** [comment]
@Tyrell-Wellick 
Para evitar [caos](http://pa1.narvii.com/6366/8987fabd2767fefc1fdca53e8cdfd58e0628f1d0_hq.gif) quedando un fín de semana para la entrega (y considerando que nosotros no lo especificamos correctamente en el enunciado, me disculpo nuevamente), lo dejaremos a tu criterio. Solo recuerda especificar en el informe tu decision para que nosotros veamos si tus resultados son consistentes con la decision tomada.

En los float, cuando un número no puede ser representado con el formato dado, se tiene que buscar el mejor número que lo represente, es decir, el que tiene la menor diferencia con el buscado. Para los casos que supere el límite, nos veremos obligados a dejar el límite como respuesta. 

Espero haber respondido todas tus dudas :v:
Saludos!!
