### ISSUE TITLE
Problema con la placa

### ISSUE THREAD

**Issue by ninifdr** [IIC2343/Syllabus#85]
Hola! Creo que estamos teniendo un problema con el display de nuestra placa.
![5136ee1b-e170-43d1-b8cb-c6dc4c04b83a](https://user-images.githubusercontent.com/42162406/66322409-72f98780-e8f8-11e9-863d-cda4ab87dadb.jpg)
![2672d889-8156-4d3a-beb7-28dce1be2bc6](https://user-images.githubusercontent.com/42162406/66322416-742ab480-e8f8-11e9-9d26-21ae1ce817c3.jpg)

A pesar de que le doy dos valores distintos al display a y b, me está mostrando el mismo número (q le di al display a).

**Comment by frvalenzuela** [comment]
Hola @ninifdr ! 

Puedes hacer una entrega parcial de tu módulo para poder verificar que no hay ningún problema con la implementación?

Saludos!

**Comment by ninifdr** [comment]
Ya! Está en la branch "probando ALU"
En el módulo proyecto está se conectaron las señales del display a y b

**Comment by frvalenzuela** [comment]
Hola @ninifdr !

EL problema esta en la instanciación del DisplayController:
```
inst_display: Display_Controller Port map(
             dis_a       =>  dis_a,
             dis_b       =>  dis_a, -- aquí esta el error, debería ser dis_b
             dis_c       =>  dis_c,
             dis_d       =>  dis_d,
             clk         =>  clk,
             seg         =>  seg,
             an          =>  an
     );
```

Así que la placa esta mostrando efectivamente en el display_a y displa_b, el dis_a

Saludos!

**Comment by ninifdr** [comment]
Ups jajaja, gracias!
