### ISSUE TITLE
[T02-Programada] Archivo Binario

### ISSUE THREAD

**Issue by FelipeCampbell** [IIC2343/syllabus#85]
Si me entregaran un archivo binario en que una de las variables no tiene que ser usada con complemento de 2 (por ejemplo un puntero como en el caso del archivo ejemplo_codigo.s) cómo se podría determinar eso.  No tendría que asumir que todas las variables se utilizan con complemento de 2 en cuyo caso no podrían existir punteros que sirvan para la memoria de 250 bits?
No se si se entendio muy bien mi problema

**Comment by Arcoirisky** [comment]
Creo que te entendí y puedes asumir que solo las operaciones lógicas y de la alu pueden tener números con complemento a dos. El resto es libre (mira las otras issues sobre el tema)

**Comment by FelipeCampbell** [comment]
Entonces las variables no pueden comenzar siendo números negativos antes de realizar operaciones lógicas?
DATA:
    fk_2 -1

Por ejemplo eso no podría pasar?

**Comment by Arcoirisky** [comment]
🤔 pueden asumirlo.

Ya si se produce un cambio en medio de la ejecución haciéndolo negativo se seguirá la regla de que no será utilizado en instrucciones como las de direccionamiento.
