### ISSUE TITLE
Tarea 2 | Pregunta 3.2 | Duda sobre significado de pregunta

### ISSUE THREAD

**Issue by bpardobravo** [IIC2343/Syllabus#85]
Hola, podrían aclarar la acepción de la palabra `"incompatible"` en la 3.2? 

Además aclarar si se pregunta por compatibilidad hacia un lado (cuál) o si es bidireccional (cada uno compatible con el otro)? De la pregunta entendería que es solo para un lado, pero me quiero asegurar

**Comment by jmwielandt** [comment]
Hola, la pregunta apunta a si Latin-1 puede o no leer UTF-8 (más allá de si todos los caracteres coinciden o no).

Saludos!
