### ISSUE TITLE
Asignar botonoes

### ISSUE THREAD

**Issue by tamaralues** [IIC2343/syllabus#85]
Hola, 

que no me queda muy claro como se asignan los botones a las diferentes funciones;
1. ¿Tienen que estar todos en el mismo arhivo vhd (JK, D, SR) ?
2. ¿Cómo le asigno a un output un led?
3. ¿Cómo le asigno a una función un boton?

**Comment by jnlarrain** [comment]
Hola!!

Te recomiendo leer y ver como están organizados los diferentes componentes en el proyecto base, ve como se conectan y relacionan los componentes. Por otro lado, para ver como se asignan los botones a funciones te recomiendo pensar mas que en funciones en componentes (mux, flip-flop), acuérdate que es una lógica de programación diferente.
