### ISSUE TITLE
Duda en detalle de instrucciones

### ISSUE THREAD

**Issue by jpgonzalez4** [IIC2343/syllabus#86]

**Comment by jpgonzalez4** [comment]
![capture](https://user-images.githubusercontent.com/30642692/29673511-cf442512-88c5-11e7-9ec6-73866f04eb9c.PNG)

**Comment by jpgonzalez4** [comment]
Leímos el enunciado del último parrado de la página 3 de la tarea y todos lo interpretamos de manera diferente. ¿Podrían aclararnos la duda? Muchas gracias

**Comment by Hernan4444** [comment]
@jpgonzalez4 lamento si no se entiende. Ese parrafo dice que el input es:

"numero simbolo numero" (Es decir, primero vá un numero, luego el simbolo y finalmente el otro numero. Y siempre hay un espacio entre cada elemento).
Ejemplos:
```
2 + 2
4 - 5
```
Si la operación es de las que ocupa solo un némero (como rotate o shift), el input es "simbolo numero". Es decir, primero el símbolo y luego el número. De nuevo con un espacio entre el núero y el símbolo.
Ejemplos:
```
> 2
<< 6
```
Ojala se entienda ahora ese parrafo, cualquier duda sigue preguntando en esta issue 👍 
Saludos!!

**Comment by crabarca** [comment]
Hola, creo que deberian actualizar el enunciado de la tarea, sin este issue es bastante díficil interpretar lo que dice ese parrafo sin un ejemplo . 

Saludos !

**Comment by Hernan4444** [comment]
@crabarca en el enunciado, cada operacion tiene un ejemplo casi al final de parrafo donde se puede ver que siguen el formato indicado. Y como equipo optamos por no actualizar el enunciado puesto que eso no genera una notificación en los alumnos (a no ser que mandemos más avisos por siding) mientras que hacer una issue si lo hacen para todos quiene tienen la opción `Watching`

![image](https://user-images.githubusercontent.com/15641721/29848797-49d03974-8cf9-11e7-9a45-4acad8339bb0.png)

Saludos!

**Comment by crabarca** [comment]
Muchas gracias por la respuesta @Hernan4444. Toda la razón con el tema de no actualizar el enunciado, generaría confusiones. Logré ver que al final está mucho más claro el formato :smile:
Aún así, ojo con la redacción y las faltas ortográficas !! 
Saludos !

**Comment by Hernan4444** [comment]
@crabarca jejejeje eso no tenemos excusa 😓  lo tendremos mucho mas presente en la T02 👍 

Saludos!!
