### ISSUE TITLE
Discrepancia notas Tarea 1 entre hojas.

### ISSUE THREAD

**Issue by fgbruna** [IIC2343/syllabus#86]
Cual es el calculo que se hace al pasar desde la nota que está en el desglose de puntaje a la de la hoja principal. Pregunto esto ya que no tengo claro por que me salen notas distintas.
Gracias de antemano!

**Comment by tomasrivera** [comment]
Hola, había un problema con una coma que estaba escrita como punto en la hoja original. Ahí está arreglado!
Saludos.

**Comment by fgbruna** [comment]
Gracias!
