### ISSUE TITLE
[Tarea 3 - Programable A] - Duda general

### ISSUE THREAD

**Issue by amartinezsilberstein** [IIC2343/syllabus#86]
Hola de nuevo!

Si mal no entiendo, un _circuito secuencial_ **sí depende** del `input` anterior y un _circuito combinatorial_ **no depende** del `input` anterior. Entonces, cómo debemos modelar una máquina que depende del `input` anterior sin que dependa de este? 😕

**Comment by Jaluco** [comment]
Ideal que respondan esta duda antes de la entrega

**Comment by halobel** [comment]
Este tipo de análisis es justamente lo que esperamos de uds. con las tareas. La idea es hacer la reflexión tempranamente, junto con la primera lectura del enunciado, que debe realizarse el día martes. Así, el desarrollo de la respuesta se puede hacer con tiempo suficiente (por eso damos una semana completa, no sólo el fin de semana).

Con respecto a tu pregunta en particular, lamentablemente no podemos darte una respuesta, porque lo que preguntas es justamente lo que estamos buscando que uds solucionen.

**Comment by amartinezsilberstein** [comment]
Se agradece la respuesta profesor @halobel! Por supuesto que lo ideal sería tener la semana completa para reflexionar acerca del enunciado, pero lamentablemente no siempre es posible.

**Comment by halobel** [comment]
No cuesta nada leer el enunciado un par de veces el día martes, y hacer un primer análisis, no son más de 10-15 minutos. Creo que es bien razonable esperar que puedan hacerlo, incluso con la cargas de 50-60 créditos que tienen regularmente.

**Comment by Jaluco** [comment]
Profesor con todo respeto, el enunciado es de pocas lineas de las cuales se entiende bien poco(prueba de esto es la cantidad de issues). Además que se nos pide hacer algo muy distinto a lo que hemos visto en clases o programado para otros ramos. Le he dedicado varias horas a esta tarea y aun no estoy ni cerca de llegar a un resultado y se que el caso de muchos compañeros es similar. los primeros 10-15 minutos de leer el enunciado servirian solo para darse cuenta que no se entiende.

**Comment by halobel** [comment]
Discrepo bastante de lo que indicas, no sólo en base a mi opinión, sino también a lo que he conversado con muchos de tus compañeros. Sin entrar en detalles particulares del ejercicio, creo que no es razonable esperar que en una evaluación, y sobre todo una tarea, se les pida hacer lo mismo que en clases. La idea es justamente ponerlos en una situación fuera de su zona de confort, donde deban explorar el uso de las herramientas que se discuten en clases, para solucionar una problemática compleja y desafiante, tal como esta. Esto forma parte fundamental de las competencias de un ingeniero, especialmente de uno de computación.
Logicamente hay muchos factores que influyen en el tiempo que cada uno puede invertir en una tarea, desde la carga académica, hasta los tiempos propios para madurar las ideas. Muchas veces también este tiempo no es suficiente para entregar una solución satisfactoria, lo que implica que en una siguiente tarea, es necesario ya sea empezar antes, o dedicar más tiempo posteriormente. Este es uno de los motivos por los que hay 13 tareas y se puede borrar la peor. Así, es posible ajustar con bajo impacto en las notas, un approach que no fue efectivo anteriormente.

**Comment by amartinezsilberstein** [comment]
1. En lo personal, me parece que la tarea es muy interesante y nos pone a pensar harto, lo cual es súper bueno. Espero que la solución al problema sea igual de interesante que la pregunta que plantea.

2. Estoy de acuerdo en debería haber leído el enunciado con mayor anticipación para que dudas como estas surjan al comienzo de la semana y no al final. Por otro lado, el enunciado no es claro con lo que solicita.
