### ISSUE TITLE
Tarea 2 | Pregunta 1 | Resta

### ISSUE THREAD

**Issue by clementeross** [IIC2343/Syllabus#86]
Hola! En la pregunta 1, la alternativa que pregunta sobre la resta como método de comparación, el rango [-64, 63] hace referencia al rango del resultado de la resta? O del minuendo y sustraendo?

Muchas gracias!

**Comment by jmwielandt** [comment]
Hola, se refiere al minuendo y sustraendo. Saludos!

PD: no cierres las issues, ya lo haremos nosotros cuando sea oportuno.
