### ISSUE TITLE
[Entrega 2] Control Unit y opcodes

### ISSUE THREAD

**Issue by ceosorio** [IIC2343/Syllabus#86]
Hola!

Estaba revisando el enunciado con mi grupo y dice que par al creación de la Contol Unit, no podemos usar solo multiplexores. Nosotros tenemos una idea de tener de input el opcode y en base a eso dar un output, eso sería considerado un multiplexor?
La otra idea sería armar un mapa de Karnaugh para obtener los opcodes, pero no estamos seguros de si es posible hacerlo con tantos bits.

**Comment by frvalenzuela** [comment]
Hola @ceosorio !

Lo solicitado es que la Control Unit no sea un gran selector cuya entrada de selector sea el opcode. Lo que pedimos es que utilicen lógica combinacional para realzar la CU, lo cual el mapa de Karnaugh es una opción, **pero no es la única.**

Saludos de parte de Felipe y @jjaguillon !

**Comment by xariveros** [comment]
Hola!

¿se refieren a que no podemos usar _with selects_ gigantes? Me refiero a _with selects_ que revisen los distintos opcodes (uno por uno) y según eso se mandan distintas señales.

Espero haberme hecho entender.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @xariveros !

A lo que nos referimos es que la Control Unit no pueden usar solo declaraciones with/select. Un ejemplo de esto algo que no esta permitido  sería usar el opcode como señal selectora, y que el selector simplemente elija entre un posible conjunto de señales. Espero que con esta explicación quede más claro, de no ser así no dudes en consultarnos!

Saludos!

**Comment by ararojas** [comment]
Hola!
Se puede hacer uso de with select para algunas señales, si para otras ya hice uso de compuertas lógicas? o hay que usar compuertas lógicas en todas las señales?

**Comment by frvalenzuela** [comment]
Hola @ararojas ! 

Como ya ocupas compuertas lógicas para redireccion de algunas señales, puedes ocupar with/select para otras. Ya que no en dicho caso su CU no sería **solo** selectores y por tanto estaría correcto. 

Saludos !
