### ISSUE TITLE
Conexión Registros y Display

### ISSUE THREAD

**Issue by yoavnavon** [IIC2343/Syllabus#87]
Se pide que para ambos registros se muestren sus 8 bits menos significativos en el display. Como solo tenemos 4 digitos en el display, esto significa que hay que variar de alguna forma el registro a mostrar? Por ejemplo si tengo 255 en A y 255 en B como hago para mostrarlo en el display?

**Comment by frvalenzuela** [comment]
Hola @yoavnavon ! 

No hay que variar ninguna forma, solo debes mostrar de forma que en los primeros dos display se vea el registro A (en el ejemplo que mencionas se vería FF) y en los otros dos display el registro B (también se mostraría FF). 

Así que tu display final sería: 

FFFF

Saludos !

**Comment by yoavnavon** [comment]
@frvalenzuela , me di cuenta que el display soportaba numeros hexadecimales ahora y por eso cerré la issue. Gracias!!
