### ISSUE TITLE
Tarea 3 | Pregunta Recuperativa T1 | ¿Reemplaza preguntas teóricas?

### ISSUE THREAD

**Issue by fncabrera** [IIC2343/Syllabus#87]
Hola,

Me di cuenta que la pregunta recuperativa de la t1 es solo programada. ¿Esta puede reemplazar la peor nota de una pregunta teórica? En un correo que enviaron decía que reemplazaría la nota de alguna de las preguntas que nos hubiese ido mal, pero me queda esa duda.

Gracias!

**Comment by jmwielandt** [comment]
Hola, es solo preguntas programadas. Para las preguntas teóricas se mantiene todo igual así que no hay necesidad de hacer preguntas recuperativas.

Saludos!

**Comment by fncabrera** [comment]
Hola @jmwielandt ,

¿Cual fue la razón de ofrecer una pregunta recuperativa programada de la t1? Es que estuve buscando correos y no la encuentro. Me pasa que bacán que den la oportunidad, pero encuentro injusto que no sirva para subir una pregunta teórica (Al final algunos tienen la oportunidad de subir su nota de la t1, mientras que otros no).

Quería aprovechar de hacer otra consulta (no lo encontré en el programa ni acá). ¿Cuanto valen en % las preguntas programadas y las teóricas para la nota final de tareas?

Gracias!

**Comment by jmwielandt** [comment]
## **No es una oportunidad para que suban su nota, es para que no terminen con promedio rojo en las preguntas programadas por el desbalance de la tarea 1 frente a la tarea 3 en cuanto al número de preguntas.**

Adjunto captura de la primera parte del anuncio publicado el 15 de mayo (hace 4 días):

![image](https://user-images.githubusercontent.com/37153467/82370588-cb444c00-99e6-11ea-8445-a377b2e7696c.png)

Este después sigue con un FAQ sobre la tarea 2 y otro sobre la tarea 3. Como digo al inicio, es importante que lo lean.

**Comment by mfortiz** [comment]
Hola, estoy un poco perdido con el cálculo del promedio de tareas.
Lo que entendí es:
**Tarea 1**: 6 preguntas programadas + 4 preguntas teóricas
**Tarea 2**: 3 preguntas teóricas
**Tarea 3**: 3 preguntas programadas + preg_bonus + preg_recup(programada)

¿Habrán preguntas teóricas en la T3?
![image](https://user-images.githubusercontent.com/37163461/82374223-be2a5b80-99ec-11ea-8b62-7dfda0e28f17.png)

Con lo de "_se tomará el 70% mejor de cada bloque_" significa que el promedio final es:

**NT**= (Prom[70% mejor_programadas])***0,7** + (Prom[70% mejor_teóricas])***0,3** ?

Muchas gracias.

**Comment by jmwielandt** [comment]
Sí, es eso.

Para las preguntas programadas, en total tenemos 9 preguntas (6 tarea 1 + 3 tarea 3), tomamos el 70% mejor y eso son 7 preguntas. La pregunta recuperativa puede reemplazar la peor de las de la tarea 1 y la pregunta bonus de la tarea 3 ya se anunciará.

Luego, el promedio final de las tareas es 70% programadas + 30% teóricas.

**Comment by furzuadr** [comment]
Hola! Qué pasa si respondí sólo una de las preguntas programables de la T2?
Gracias!

**Comment by jmwielandt** [comment]
Que tienes la posibilidad de no hacer una de las preguntas de la tarea 3 (programadas) si no quieres, no puedes o lo que sea y esta pregunta te contará como parte de la tarea 3 (sale en el tercer párrafo de la foto del anuncio que puse más arriba y en el FAQ del mismo anuncio que tienen en SIDING). Esto es simplemente para que el trabajo que algunos hicieron no se perdiera. El form cerro el mismo día, 12 horas después del anuncio (como dice en el propio anuncio).

**Comment by mariana-ortega** [comment]
Entonces cuántas preguntas teóricas se toman al final para el cálculo de la nota?

**Comment by jmwielandt** [comment]
> Entonces cuántas preguntas teóricas se toman al final para el cálculo de la nota?

5 de las 7
