### ISSUE TITLE
Tarea 3 - Programación A (Dependiente o no de Q)

### ISSUE THREAD

**Issue by Bipavez** [IIC2343/syllabus#87]
¡Hola!
Dos cosas, primero, ¿es válido pensar el problema como que cada circuito es una expresión lógica?, Si es así; si es que alguno de los circuitos depende de Q{_i_} (valor inscrito en alguno de los flipflops), ¿es válido ingresar ese valor, sea cual sea mediante una constante al circuito?

**Comment by Geeermy** [comment]
¡Hola!

1. Sí. :)

2. Para no ser tan explícito, ver: #69, #71 

¡Éxito! 👹

**Comment by Bipavez** [comment]
!Muchísimas Gracias!
