### ISSUE TITLE
Pasar a int

### ISSUE THREAD

**Issue by FranciscoLarach** [IIC2343/syllabus#87]
Hola
Al pasar el numero x que nos den en base b a int, debo dejarlo en base 10 o en base b? Asumo que es base 10, pero el ejemplo calza justo con que b=10.
Gracias

**Comment by Hernan4444** [comment]
@FranciscoLarach el resultado final debe estar en base 10.

Saludos!!

**Comment by FranciscoLarach** [comment]
Gracias
