### ISSUE TITLE
[CLASES] Duda cálculo de índice de cache

### ISSUE THREAD

**Issue by Taeval** [IIC2343/syllabus#87]
En la clase de Memoria se menciona el método de _direct_ _mapping_ para calcular el índice en la cache de una palabra en memoria según su dirección en la memoria:

índice = (dirección en memoria) mod (líneas de la cache)

Respecto a esto, no me queda claro como se resuelve lo de la foto: 
![image](https://user-images.githubusercontent.com/37159657/56676516-766fbe00-668c-11e9-951d-d7e49478db39.png)

Podrían aclarar como se calcula, por favor? Muchas gracias :D

**Comment by frvalenzuela** [comment]
Hola!

Primeramente la fórmula no esta del todo correcto. La forma correcta es:

índice = (dirección del **bloque** de memoria) mod (líneas de la cache)

### ¿A qué se refiere con el bloque de memoria?
Al igual que en la cache, a la agrupación de bytes (palabras) le llamamos **líneas de cache**, a la agrupación de bytes en memoria la llamamos **bloques de memoria**. Hay que notar que una línea de cache y un bloque de memoria **tienen exactamente el mismo tamaño.** 

En el caso del ejemplo tenemos que cada línea de cache tiene 16 bytes, por lo tanto cada bloque de memoria tiene 16 bytes. Luego necesitamos calcular que bloque de memoria corresponde la dirección dada, lo que se puede lograr con la siguiente **división entera**: 

`DIRECCION_BLOQUE = DIRECCION_MEMORIA // CANTIDAD_PALABRAS_EN_BLOQUE`

La división entera sería en el ejemplo 1200 // 16 = 75.
Por lo que tenemos la dirección de bloque, y ahora si podemos aplicar la primera fórmula!

índice = (75) mod (64) = 11

Que es la respuesta dada en clases =D!

Espero que se haya entendido, si algo no te quedo claro favor hacerlo saber.

Saludos!

**Comment by Taeval** [comment]
Sí me quedó claro! Muchas gracias ^_^

**Comment by seba608** [comment]
Una duda,

Si cada bloque de la memoria tiene 16 bytes, la explicación dice que la cantidad de palabras por bloque son 16. Como sabemos si la palabra usa 1 byte o 4 bytes?

Al ver el ejemplo de las diapositivas 22 a 26 de la misma clase 8 me parece que las palabras son de 4 bytes pero no estoy del todo seguro.

Saludos!

**Comment by Arcoirisky** [comment]
A menos que se te diga lo contrario, las palabras son de 1 byte O:

Aparentemente en el ejemplo, cada valor de memoria es de 4 bytes pero, el ejercicio no lo dice en ningún lado :( Entonces, cuando guardas 2 valores en una linea, tienes guardados los 8 bytes que almacena esa linea.

Ojo que cuando guardas en las lineas, estas no siempre guardan dos palabras. Depende netamente de su tamaño O:
