### ISSUE TITLE
Entrega 3 | Duda Instrucción "IN A, Lit"

### ISSUE THREAD

**Issue by nbnavarro** [IIC2343/Syllabus#88]
Hola, 

No entiendo bien qué debemos hacer con la instrucción `IN A, Lit`, cuando el Lit es distinto a 0 o 1. Por ejemplo, cuando dice `IN A, 2` en el programa 7 del enunciado, ¿podríamos simplemente ignorar esa instrucción a través del assembly? 
En caso de que se pueda ignorar, ¿habría que cambiarla por una instrucción `NOP` o bastaría con hacer como que nunca estuvo ahí? 

Muchas gracias de antemano

**Comment by quememo** [comment]
Tengo la misma duda, cuando el enunciado dice "Nada", que es eso? Es un vector con puros 0 o es como que lo ignora simplemente?

**Comment by nbnavarro** [comment]
haz tu propia issue

**Comment by frvalenzuela** [comment]
Hola @nbnavarro !

Como dice la primera opción de @quememo , un vector de solo ceros será suficiente como interpretación de "Nada". Cabe aclara que en distintas arquitecturas y convenciones esto puede ir cambiando, para esta versión de curso se asumirá que se guardan ceros.

Saludos!
