### ISSUE TITLE
Contenidos control 3

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2343/syllabus#88]
Holaa 
Me gustaría saber cuales son los contenidos a evaluar en el control... y además confirmar si es que se borraría alguno de ellos.

Graciaas

**Comment by Arcoirisky** [comment]
Hola~
Entra Caché y Memoria virtual :D 
Los contenidos que han visto estas ultimas clases (en unos minutos estará la ultima versión de estas clases actualizada)

**Comment by seba608** [comment]
Hola,

Solo para estar seguro:

1) De las clases del repositorio entra solo la 8?
2) Qué numero sería en los apuntes? 

Gracias!

**Comment by frvalenzuela** [comment]
Hola!

1. Si, así es!
2. El número 9.

Saludos!

**Comment by Arcoirisky** [comment]
Y ya tienen los ejercicios en la carpeta propuestos.
