### ISSUE TITLE
[Tarea 3 - Parte A] Duda general

### ISSUE THREAD

**Issue by jpjoublan** [IIC2343/syllabus#88]
Hola! Entiendo que para la parte A no nos interesa el valor del input que recibimos, sino que solo queremos un circuito equivalente. Sin embargo, para esto igual tenemos que saber el output de nuestro circuito combinatorial con cada input distinto y que este output sea igual que el secuencial (para que sea equivalente). En esta linea mi duda es si tenemos que hacer que nuestro circuito combinatorial funcione para un input de un número, es decir, que recibe solo un valor (independiente de la cantidad de inputs que haya, cada uno recibe un valor) o estos pueden recibir más de un valor, en el fondo va a variar en el tiempo. En el segundo caso, pasaría que el valor de Q sería relevante para la siguiente entrada (D) en cada flipflop y, en ese caso, se hace necesario que el circuito sea secuencial para "guardar" el valor anterior. Espero que se haya entendido la pregunta.

**Comment by Geeermy** [comment]
¡Hola!

En resumen, la respuesta a tu duda es: **sí.** Para iluminarte más, ver: #69, #71.

¡Éxito! 🐣

**Comment by jpjoublan** [comment]
@Geeermy gracias! Solo una duda, tu respuesta es que si reciben más valores? No me quedó tan claro a que iba ese si jajaja

**Comment by aeperalta** [comment]
Aah ya, entonces lo que recibe sería algo como de la forma: input = [n<sub>1</sub>,...,n<sub>u</sub>] y Q = q por ejemplo? Porque ese Q es el que va cambiando a medida que uno avanza en una máquina secuencial. A lo que me refiero con recursión es: le meto por ejemplo n<sub>1</sub>, n<sub>2</sub> y el primer q, calculo como cambia el q (llamémosle q<sub>2</sub>) y después le meto n<sub>2</sub>, n<sub>3</sub>y q<sub>2</sub>, y así sucesivamente (es un ejemplo, no necesariamente tiene que ser así). Cuando dices "una combinación de estados dada" me hace un poco de ruido, como que me puedo imaginar que eso ustedes lo dan (que Q sea de la forma Q = [q<sub>1</sub>,...,q<sub>u</sub>] aunque no sé si tenga mucho sentido). No sé si me explico o si estoy escribiendo más de la cuenta. 

Muchas gracias por la respuesta!

**Comment by Geeermy** [comment]
Hablo de combinación de estados porque podemos tener más de un _flip-flop_.

¿Ahora sí? jejeje :-)

**Comment by aeperalta** [comment]
ahora si que sí jajaja, muchas gracias!
