### ISSUE TITLE
[Tarea 3] Programación Parte B - Input C Flip-Flops

### ISSUE THREAD

**Issue by tomasrivera** [IIC2343/syllabus#89]
Para el input C hay que tomar en cuenta el flanco de subida o al ser inputs discretos tener dos seguidos con valor 1 en la entrada C se toma como dos señales para cambiar datos?

**Comment by Geeermy** [comment]
¡Hola!

**No, no se consideran discretos.** Si tienes, por ejemplo, ```"input1": [0,1,1]``` conectado a la compuerta C de un _flip-flop_, este cambia de valor solo en ```input1[1]```, después sigue manteniendo su estado. Es decir, **solo consideras el flanco de subida**.

¡Éxito! 🎠

**Comment by tomasrivera** [comment]
¡Gracias! 🐶
