### ISSUE TITLE
Notas Controles

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC2343/syllabus#89]
Hola, quería saber en cuanto tiempo mas van a subir las notas de los controles. Sería ideal si los pudieran tener antes de los siguientes controles! Muchas gracias

**Comment by Arcoirisky** [comment]
Los ayudantes tienen un tiempo de 3 semanas hábiles para corregir cualquier evaluación 😢 

Recuerden que también somos alumnos que agonizan con el pasar del semestre :skull: intentamos tenerlos lo antes posible pero no se hacer nada si faltan algunos por corregir. 

De todas formas ¡eso no debería desmotivarlos de estudiar y dar su mayor esfuerzo en cada uno de los controles! ❤️

(Las 3 semanas -incluyendo no hábiles- terminan el Miércoles 1 de Mayo 👌🏼)

**Comment by Panckx** [comment]
Para evitar cualquier tipo de confusiones, 3 semanas hábiles = 15 días hábiles <3

**Comment by NicolasAguirre** [comment]
@Panckx @Arcoirisky sip, pero yo creo q han pasado más de 15 días hábiles. Cuando los subirán?? es que es para organizarme para ver cuando poder estudiar (dependiendo de la nota, si se bota o no) gracias!

**Comment by jmwielandt** [comment]
@NicolasAguirre Nop, hoy es el quinceavo día hábil, y el día no ha terminado.
Hoy en la noche se suben.

**Comment by NicolasAguirre** [comment]
@jmwielandt toda la razon! se me fue semana santa jajaj yaa muchas gracias!!
