### ISSUE TITLE
Entrega 3 | Tratamiento de Arreglos

### ISSUE THREAD

**Issue by cjones27** [IIC2343/Syllabus#89]
Hola!

Una pregunta con respecto al uso de los arreglos. Hay alguna clase de indicador que permita distinguir si una variable es una variable simple o un arreglo? Por ejemplo en el programa 2 de la entrega dice: "`arr ...`". Siempre van a decir "`arr_algo`" por ejemplo o podría decir simplemente `var1`? 

En resumen, los arreglos podrían tener cualquier nombre?
Muchas gracias!

**Comment by frvalenzuela** [comment]
Hola @cjones27 !

El manejo de arreglos no es algo que deberán preocuparse para esta entrega en particular en esta entrega (los test evaluados no los contendrán). Respondiendo a la pregunta de forma teórica, el indicativo de si algo es una arreglo se denota con la cantidad de líneas que ocupa en la DATA, así que si podría tener cualquier nombre, pero nuevamente aclaro que no es algo que tendrán que preocuparse para desarrollar los tests.

Saludos!

**Comment by quememo** [comment]
Para futuras entregas creo sería mejor que si algo no será evaluado (como en este caso manejo de arreglos), no aparezcan ejemplos que lo incluyan.

**Comment by frvalenzuela** [comment]
Hola @quememo ! 

Lo tendremos en consideración, para que no vuelva a ocurrir. 

Saludos !
