### ISSUE TITLE
[Entrega 2] ALU

### ISSUE THREAD

**Issue by csolguin** [IIC2343/Syllabus#89]
En la alu, ¿es posible usar un when/else, del tipo:
```
   <name> <= <expression> when <condition> else

             <expression>;
```
?

**Comment by jerosalazar** [comment]
@frvalenzuela podemos ocupar entonces un with/select statement dentro de la ALU?

**Comment by frvalenzuela** [comment]
Hola @jerosalazar !

Si pueden ocupar un `with/select` statement dentro de la ALU!

Saludos!

**Comment by jjaguillon** [comment]
@jerosalazar Si. La limitante del with/select es sólo en la CU.

Saludos !
