### ISSUE TITLE
Tarea 1 parte 2

### ISSUE THREAD

**Issue by sofiapacheco1** [IIC2343/syllabus#89]
El input en es pregunta van a ser números con cualquier base?? Ademas pueden ser int, float? También incluirán negativos?
Gracias

**Comment by Hernan4444** [comment]
@sofiapacheco1 el input es un número en cualquier base entre 2 y 10. Puede ser float o integer (ya saben calcularlo) pero no puede ser negativo.

Saludos!

**Comment by sofiapacheco1** [comment]
y nos van a decir en que base está?

**Comment by Hernan4444** [comment]
@sofiapacheco1 sorry, **la base es siempre 10**, me confundí con la parte 1. Solo serán int o float de base 10.

**Comment by sofiapacheco1** [comment]
Ok, muchas gracias!!

**Comment by Hernan4444** [comment]
@sofiapacheco1 porfa no cierres la issue nosotros lo haremos por ustes 👍 
Saludos!!

**Comment by lfbesa** [comment]
Finalmente en la parte 2 solo serán int según lo que entendí o no?

**Comment by Hernan4444** [comment]
@lfbesa precisamente, solo serán int (o enteros).. si implementas float te daremos bonus.

Saludos
