### ISSUE TITLE
[Tarea 1] Libreria math.h de C

### ISSUE THREAD

**Issue by mnreyes1** [IIC2343/Syllabus#9]
Se puede usar la librería math.h para la tarea? En particular la quería para usar pow(x, y) (elevar x a y)

**Comment by jmwielandt** [comment]
Hola!

Solo por curiosidad, ¿puedo preguntar para qué problema quieres utilizar esa función?
En principio no hay ningún problema con ello, pero tampoco es necesario que lo uses.

Te recomiendo ver los tutoriales de C que están en mybinder, entre eso y la materia vista en clases deberían tener casi todo lo que necesitan (hay algunas cosas que esperamos que busquen por su cuenta). También los códigos base del enunciado para las distintas preguntas.

Saludos! 😄

**Comment by mnreyes1** [comment]
La queria usar para la parte 3 de la pregunta 1. Pero voy a revisar bien lo que nos mandaron. Gracias!
