### ISSUE TITLE
RGB a CMYK

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/Syllabus#9]
Abro esta issue respondiendo a @llloyola @lfbeltran @Lfuenzalida2 @cdlepe y @furzuadr ya que cerramos canvas.

Juro solemnemente que intenté recrear el primer ejemplo del challenge de hackerrank, pero pasé el 48532 por hexa antes de ir a binario y leí 0xBD49 en lugar de 0xBD94, por lo que las fotos a continuación son con el número 48457 como input en su lugar 🤦‍♂

<details>
<summary>Primero descomponemos el número y escalamos los valores R, G 
y B (click para ver)</summary>

![image](https://user-images.githubusercontent.com/37153467/78633869-a188f880-7870-11ea-83d5-33e9a4995ef3.png)
</details>

<details>
<summary>Ahora a partir del R, G y B escalados vamos a obtener los C, M Y y K</summary>

![image](https://user-images.githubusercontent.com/37153467/78634021-f62c7380-7870-11ea-897e-ce1ff29a994c.png)

</details>

<details>
<summary>Y como último paso, escalamos los valores de C, M, Y y K para poder formar el número.</summary>

![image](https://user-images.githubusercontent.com/37153467/78634131-40155980-7871-11ea-9ba3-453c1dea5b98.png)
</details>

Sé que es un poco tarde pero la respuesta al final llega.

### Preguntas particulares:
1. Lo de los paréntesis tiene que ver con el error inducido por la cantidad de bits con la que estamos trabajando.

Primero tenemos que tener clara una cosa: estamos trabajando con valores de 8 bits en variables de 16 porque en nuestro procedimiento estamos multiplicando dos valores de 8 bits. Usar variables de 16 permiten que no haya overflow ni carry.

Ahora, al calcular `255 * ((255 - X - K) / (255 - K))` con los paréntesis en ese orden, lo que estamos haciendo es dividir dos valores de 8 bits donde el numerador es siempre menor que el denominador, haciendo que de siempre 0. Es por esto que yo, al hacerlo en la pizarra, quito el paréntesis más grande y hago primero la multiplicación y luego la división, de este modo estoy dividiendo un valor que puede llegar a ocupar 16 bits por otro que usa solo 8, obteniendo un resultado que vive en 8 bits.

2. ¿Runtime error?

Como contestamos en el foro de canvas a otra persona que tenía el mismo error, esto tiene que ver estrechamente con un caso borde muy particular y característico (no puedo decir más) pero te recomiendo que revises bien tu código y lo pruebes en el jupyter notebook, allí te va a decir el error real. **Hint:** revisa tus divisiones.

**Comment by jeharcha** [comment]
Gracias por aclarar el paso del escalamiento, era muy necesario.
