### ISSUE TITLE
Versión de Python

### ISSUE THREAD

**Issue by mundurragac** [IIC2343/syllabus#9]
En el enunciado de la tarea sale que Python debe ser 3.6.X, eso nos restringe a solo usar la versión 3.6.X, o la 3.7.X también se puede usar?

**Comment by Panckx** [comment]
Hola! Debido a que los ayudantes corrigiendo la tarea usarán una versión de Python 3.6, procura utilizar solamente funcionalidades disponibles para esa versión y no funcionalidades añadidas en la versión 3.7, ya que el corrector no podrá correrlas.
Saludos!

**Comment by Arcoirisky** [comment]
Agregando a lo que dice @Panckx, si tu tarea no funciona por utilizar un Python diferente, GG :(

No se instalará otra versión para correr una sola tarea ya que se a dicho que se debe usar la versión 3.6
