### ISSUE TITLE
[Tarea 03-parte A]

### ISSUE THREAD

**Issue by acrojas2** [IIC2343/syllabus#90]
Hola, tengo una duda con el circuito de ejemplo:
<img width="845" alt="captura de pantalla 2018-09-02 a la s 21 22 47" src="https://user-images.githubusercontent.com/26121354/44962415-6c7b2e00-aef6-11e8-9e99-ddef28aa3501.png">
Nosé si estaré equivocada, pero creo que la línea 6 debería ser {from: ffd1, to: out1, gate: Q} ya que el Q sale directo por out1 y al mismo tiempo pasa por not1 y se queda en D, es decir, not1 nunca se conecta de forma directa (sin pasar por las compuertas del flip-flop) con out1. Entonces la pregunta es si está bien descrito el circuito o no 😕 ...
Saludos!

**Comment by aeperalta** [comment]
se corrigió en el enunciado del syllabus, lo dijeron en otra issue

**Comment by acrojas2** [comment]
Ohhh! Gracias, habia hecho pull pero no cambió nada, revisaré nuevamente :)
