### ISSUE TITLE
[Entrega 2] Select, With, When en CU

### ISSUE THREAD

**Issue by lucasvsj** [IIC2343/Syllabus#90]
Bunas, tengo una duda:
Se puede utilizar el comando:
<code>
with a select b <=
	"1000" when "00",
	"0100" when "01",
	"0010" when "10",
	"0001" when "11";
</code>
en la Control Unit, incluso si tenemos varios de estos (Muxers) en vez de uno solo.
Por favor pueden ser lo más explicativo posible, ya que hemos estado discutiendo mucho este problema como grupo.
De antemano, muchas gracias.

**Comment by frvalenzuela** [comment]
Hola @lucasvsj !

Te recomiendo revisar la issue #86 , pero en resumidas cuentas si solo tienen muxers sin ninguna compuerta lógica que muestre un diseño en su palabra de control, entonces no esta permitido. 

Saludos!
