### ISSUE TITLE
problema usando operador % en python

### ISSUE THREAD

**Issue by smargozzini** [IIC2343/syllabus#90]
no pasa que cuando queremos obtener los números después de la coma usamos algo como
decimales = numero % 1

y en algunos números nos da un resto que agrega números nuevos como por ejemplo

decimales = 2.11 % 1
queda decimales = 0.1099999996

y eso nos afecta para pasar ese que puede estar en cualquier bases a base 10 y luego a binario

que podríamos hacer en ese caso?
(cuando hago esta operación en la consola me da el resultado esperado pero pycharm no)
gracias

**Comment by Hernan4444** [comment]
@smargozzini el problema es por la forma en que se presenta el float (en consola no se vé eso porque la consola acorta un poco los numeros).  Te sugiero explorar otras alternativas pero eso es parte de a tarea... no podemos darte la solucion.

Saludos!
