### ISSUE TITLE
Apuntes syllabus

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2343/syllabus#91]
Holaaaaa
Leyendo el enunciado de la T3 (Placa) recomiendan fuertemente leer el capítulo 2.4 de los apuntes, pero no lo he podido encontrar... Busqué en los otros apuntes y tampoco, no se si está mal la recomendación o hay un algún apunte con más secciones (o estoy demasiado perdido).

Graciaaas

**Comment by Arcoirisky** [comment]
¿No te estás refiriendo a los apuntes 02 sección 4? 🤔

**Comment by DanielCarrascoFalcon** [comment]
Dice capítulo 2.4 de la sección Arquitectura de Computadores en los apuntes del syllabus.
(Página 3 del enunciado superindice 4)

**Comment by frvalenzuela** [comment]
Hola Daniel!

Perdón, error al escribirlo. Fue modificado a:

> es **fuertemente recomendado** leer capitulo 2.4 de la sección Programación en Arquitectura x86 

Este se puede encontrar en el syllabus con el nombre "07 - Programación en Arquitectura x86.pdf" en la carpeta Apuntes.

Lamento la confusión, y espero que ahora si este todo más claro.

Saludos!

**Comment by DanielCarrascoFalcon** [comment]
Graciaaas
