### ISSUE TITLE
[T03 - B] Circuito ejemplo 

### ISSUE THREAD

**Issue by jmwielandt** [IIC2343/syllabus#91]
-pedrón porque se publicó vacía, ahora edito-
Hola, en el circuito del ejemplo tengo el siguiente problema: al iniciar le doy el primer valor input al flip flop en la entrada de control, pero no tengo ningún dato que darle por la entrada D y por tanto nada funciona, se queda esperando hasta el infinito.
¿Cómo se resuelve esto?

Pensé que tal vez debería usar un thread por componente y que al inicializar esté todo con 0, entonces el not registraría un 0 y mandaría un 1 a la compuerta D del flip flop, pero eso puede generar infinitos problemas. ¿O simplemente seteo D inicial en 0 y que apenas reciba el C mande la señal? .-.

**Comment by jheysen** [comment]
Yo veo bien clara la conexión que le entra al D....

**Comment by jmwielandt** [comment]
Q\_t es 0
C es el input
¿qué valor toma D al partir?

**Comment by Geeermy** [comment]
Lo que le está entrando a ```D```, independientemente del primer valor de ```C```, es un 1 (dado que es la negación de ```Q```, cuyo valor establecimos inicialmente en 0).

Lo que va a cambiar es el valor que adquirirá ```Q``` dependiendo del resultado de ```C```. Si el primer valor que ingresa a ```C``` es un 1, se genera un flanco de subida inmediatamente y cambia a ```Q = D = 1```. En otro caso, mantiene su estado, que sería ```Q = 0``` (y por ende, lo que está ingresando a ```D``` tampoco cambia).

¡Espero que se entienda!
