### ISSUE TITLE
Informe Tarea 01

### ISSUE THREAD

**Issue by IriSalazar** [IIC2343/syllabus#91]
En el informe piden que para cada tipo de dato demos un ejemplo de aplicación en la cual sea mejor ese tipo por sobre otros, justificando.
Esos ejemplos pueden ser cosas como, por ejemplo, estudio de partículas subatómicas o cantidad de productos en una tienda? o deben ser aspectos más informáticos?

**Comment by Hernan4444** [comment]
@IriSalazar no es necesario que el aspecto sea muy informatico. Solo que se aprecie que logran diferenciar las ventajas de cada tipo de dato para ciertas circunstancias.

Saludos!!
