### ISSUE TITLE
Dudas Tarea 1

### ISSUE THREAD

**Issue by vabesa** [IIC2343/syllabus#92]
Hola, tengo 2 dudas de la tarea 1:

-Primero que nada se puede usar int() para transformar un string a int()?, por ejemplo "433" en base 5 quiero cada elemento tenerlo como numero para calcular su equivalente en decimal.

-,Se puede ingresar una numero fraccionario en el input? De ser asi como se trataria? Por ejemplo si ingreso 3.42-10-int lo tengo que transformar a float y luego tomar los 32 bits de este float como si fueran un int y transformarlo a decimal? Luego si ingreso 342-5-float debo transfomar este a float en binario y de binario a decimal? La verdad es que el enunciado esta super poco claro y no se entiende nada, porfa aclarenme como debe ser las transformacion.

**Comment by Hernan4444** [comment]
@vabesa no se puede usar `int` pero te recomendamos utilizar un diccionario o una funcion que recibe el string y retorne el numero en int. Como solo trabajamos hasta base 10 usaremos un máximo de 10 digitos.

> Por ejemplo si ingreso 3.42-10-int.  lo tengo que transformar a float y luego tomar los 32 bits de este float como si fueran un int y transformarlo a decimal?

Precisamente!!

> 342-5-float debo transfomar este a float en binario y de binario a decimal?

Primero tomas el numero y como está en base 5 lo llevas a una base que sea más facil para ti (base 10 por ejemplo) luego lo transformas a float con el estandar solicitado. Luego lo vuelves a transformar a int y nos muestras ese numero. Para números pequeños transformar ese numero a float no tendrá efecto pero el estandar pierde precision con algunos números y ahí queremos ver cual es el número más cercano que se puede representar con ese tipo de dato.

Saludos!

**Comment by vabesa** [comment]
@Hernan4444 Gracias!

**Comment by crabarca** [comment]
Hola ! 
Volviendo al caso que menciona @vabesa

**Comment by crabarca** [comment]
Hola,
volviendo al caso que menciona @vabesa 

> Por ejemplo si ingreso 3.42-10-int. lo tengo que transformar a float y luego tomar los 32 bits de este float como si fueran un int y transformarlo a decimal?

En ese caso solamente deberia tomar los 16 bits menos significativos del numero y transformalo a int o no? 

Por otra parte como menciona @Hernan4444 

> Primero tomas el numero y como está en base 5 lo llevas a una base que sea más facil para ti (base 10 por ejemplo) luego lo transformas a float con el estandar solicitado. Luego lo vuelves a transformar a int y nos muestras ese numero.

Porque volverlo a interpretar como int nuevamente ? No se supone que el tipo de dato que se utiliza como input es el tipo de dato que tiene que ir en el output? 

Saludos !

**Comment by Hernan4444** [comment]
> En ese caso solamente deberia tomar los 16 bits menos significativos del numero y transformalo a int o no?


Precisamente!!

> Porque volverlo a interpretar como int nuevamente ? No se supone que el tipo de dato que se utiliza como input es el tipo de dato que tiene que ir en el output?

Porque en el primer parrafo de esa parte dice: (cito)
> ... deberán crear una funcion **en python** capáz de transformar números en cualquier base a base 10 y restringíendolo a un tipo de dato en especifico.

¿Porque solicitamos eso? Es un misterio 🙀 

Saludos!

**Comment by crabarca** [comment]
@Hernan4444 Por eso mismo !! jajaj 
El tipo de dato que se utiliza para restringir es el dato que nos dan en el input, por lo tanto si tenemos como input `342-5-float` , transformamos de alguna manera ese 342<sub>5</sub> a float y en el output representamos el número que nos resulto pero según su representación como float.

Es decir, si logramos encontrar el x tal que 342<sub>5</sub> = x<sub>2</sub> (sea del largo que sea ese x). Entonces ese x lo interpretamos como float y mostramos en el `output `el número interpretado como float o no ? . No entiendo esa transformación misteriosa de pasar nuevamente a int, siendo que nos dicen que hay restringir segun float

**Comment by Hernan4444** [comment]
siiii eso, sorry si dije int. La idea es ver cual numero queda interpretado bajo ese tipo de dato.

**Comment by crabarca** [comment]
@Hernan4444 gracias por la respuesta ! 

Otra pregunta, que hacemos con aquellos numeros racionales ( que tienen punto) que su representación en base 10 o base 2 (en especial estas dos bases , debido a que las transformaciones pasan por estas) son infinitas ?

**Comment by Hernan4444** [comment]
@crabarca queda a tu criterio, este es uno de los problemas que queremos que discutan como grupo puesto que eso es algo que pasa en el computador (Como 1.3 en float) En el informe puedes poner a que resolución quedaron (cortar el numero, aproximar al mas cerca, etc) y eso tendremos en cuenta al momento de corregir.  Esto solo es para nos números con representacion infinita, si te pasamos un número racional demasiado grande o chico para ser representado deben buscar el valor más cercano posible.

Saludos

**Comment by crabarca** [comment]
@Hernan4444 convalide el proyecto. Pregunto porque el semestre pasado tiraban comparaban con un script entonces si no resolviamos según lo que se esperaba en el script estaba malo. Me imagino que ahora si esta explicado hay un poco mas de flexibilidad.

**Comment by Hernan4444** [comment]
@crabarca owww 😢 no caché que habíás convalidado. Y no te preocupes aunque vamos a revisar los resultados en su mayoría un script, tambien revisaremos el código y el informe para cualquier detalle. 

Saludos!!

**Comment by nicovsj** [comment]
@Hernan4444 No estoy seguro de si es que entendí, dado el número y su base lo representamos SIEMPRE en IEEE 754 (32 bits) para luego interpretar esa secuencia  de bits de acuerdo al tipo dado en el input?

El problema de esto es que no tiene mucho sentido, por ejemplo para el input `342-5-int` el número 342<sub>5</sub>, en base diez es 97<sub>10</sub>, y al pasarlo al standard  IEE 754 queda 01000010110000100000000000000000<sub>IEE 754</sub>. 

Ahora si lo interpretamos como `int` de 16 bits:
0100001011000010[0000000000000000]<sub>IEE 754</sub> --->  0000000000000000<sub>int</sub> 
lo que se interpreta como 0, luego como output debiese entregar `0`.

¿Es este comportamiento es el esperado? Disculpa si es muy estúpida la pregunta o lo que asumí, pero leer el enunciado y esta issue me confunde cada vez más.

**Comment by Hernan4444** [comment]
@nicovsj no hay preguntas estupidas 😅  solo ayudantes que les cuesta expresar bien lo que se espera de la tarea 🙊 (Y eso lo tenemos en cuanto al momento de corregir xD)

El numero se pasa a IEEE 754 (32 bits) solo en las siguientes condiciones:
1. Cuando solicitamos el tipo de dato float y ahí usas el IEEE 754 (32 bits) 
2. Cuando solicitamos el tipo de dato double y ahí usas el IEEE 754 (64 bits) 
3. Cuando te llega un float como numero (Ej: 3.23-5-int)  y ahí usas el IEEE 754 (32 bits) 

Para el caso anterior, tu el 342<sub>5</sub> lo pasas a base 10, quedando 97<sub>10</sub> lo escribes en binario sin pasar por float 1100001, tomas los ultimos 16 bits y eso nos dices que representa (en este caso queda igual 1100001). Por lo tanto, la operación `342-5-int`  simplemente fue un cambio de base.

 Cuando pasan uns de las 3 condiciones anteriores, ahí convierte a float y puede que ahí el numero no dé nada de lo esperado pero queremos ver el manejo de bytes 👍.

Saludos!

**Comment by crabarca** [comment]
@Hernan4444 creo que esto último debería haber estado en el enunciado :rofl: 
Muchas gracias por las aclaraciones, ahora esta todo muuuuchisimo más claro. 
 
pd.sería bueno que le pusieras label de importante a este issue

Saludos !

**Comment by agmardones** [comment]
Hola!

Leyendo la pauta, hay varios puntos (en general) donde nombran una correcta representación, o derechamente, mostrar cierto número de bits:

> Para los 3 primeros tipos nos muestren los N bits menos significatos (Según el tipo).

Entonces, nuestro programa debiese mostrar  - además de la interpretación según el tercer argumento - la secuencia en binario de los números ingresados? En tu ejemplo Hernán, el output sería:
```
1100001
97
```
o sólo
```
97
```
Gracias!

**Comment by Hernan4444** [comment]
@agmardones solo 97, con " nos muestren los N bits menos significatos" nos referimos a que el numero final que muestren sea el generado por los N bits y no por más o menos bits.

Saludos!!

**Comment by nicovsj** [comment]
@Hernan4444 , volviendo a la respuesta que me diste:

> El numero se pasa a IEEE 754 (32 bits) solo en las siguientes condiciones:
> 
> 1.  Cuando solicitamos el tipo de dato float y ahí usas el IEEE 754 (32 bits)
> 2.  Cuando solicitamos el tipo de dato double y ahí usas el IEEE 754 (64 bits)
> 3.  Cuando te llega un float como numero (Ej: 3.23-5-int) y ahí usas el IEEE 754 (32 bits)

Entendí perfecto, la única duda que me queda es que hacer cuando ocurre 2. y 3. al mismo tiempo. Por ejemplo el input `3.23-5-double ` ¿Se debe usar IEEE 745 (32 bits), agregar 32 ceros a la izquierda (o hacer algo para que queden 64 bits) e interpretar el string de bits resultante como `double` (es decir el punto 3. es más fuerte que el punto 2.)? ¿O se debe usar IEEE 745 (64 bits) y directamente interpretar el string de bits como double (2. más fuerte que 3.)? 

Saludos!

**Comment by Hernan4444** [comment]
@nicovsj Lo dejaré a tu criterio (por si alguien ya lo programó de alguna forma que no sea la que yo diga). Solo te pido que lo indiques en un informe como "Desiciones Personales" o algo similar. Nosotros leeremos lo que decidiste y evaluaremos que seas consitente con los test que probemos.

Saludos!!
