### ISSUE TITLE
[Tarea 3 - Programada] Duda Enunciado 

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2343/syllabus#92]
En el ejemplo del enunciado se presenta un código en assembly donde despues del label "Data" se encuentran las variables, pero en los ejemplos presentados en la carpeta de la tarea no se cumple esta misma estructura. ¿Bajo cual basamos la tarea?

Tambien en el ejemplo presente en el enunciado, se presenta la compilación del código assembly a maquina, donde se puede ver que por cada linea del código assembly se generan 2 en maquina, pero no logro entender el opCode de la segunda fila, por ejemplo:

**MOV Ax , [resultado]**

Pasa a ser:

**0o0036 ; MOV Ax, Dir  # 0o0036 es el opcode asignado a Mov Ax Dir
0o0021 ; Dir=var:resultado # 0o0021 No entiendo porque**

Muchas Gracias

**Comment by ignacioaraya1995** [comment]
Tampoco queda claro el ejemplo que se encuentra en la carpeta.

**Comment by ariel-m-s** [comment]
Hola @ignacioaraya1995!

Respondiendo a tu primera pregunta. Tal como dices tú, ```data``` es una _label_ y, por lo tanto, no afecta al resultado del código compilado. Esta _label_ puede estar o no estar, siempre y cuando no sea utilizada por alguna instrucción del programa. Sin embargo, esta _label_ fue eliminada del enunciado para no causarles ninguna confusión.

Respondiendo a tu segunda pregunta. La estructura del código compilado es de la forma _opcode - literal_. ¿Qué significa esto? Significa que en memoria siempre se encontrarán guardados, de forma intercalada, el _opcode_ que representa la instrucción a ejecutar y los operandos que utiliza. Luego, en la siguiente línea, el literal (```Lit```) o dirección de memoria (```Dir```) que utiliza dicha instrucción.

Espero que te haya quedado claro,
Ariel

**Comment by NoemiCC** [comment]
Hola @ariel-m-s , 

Tuve la misma duda y me queda claro a que te refieres pero ¿Como sabemos cual es la dirección de memoria correspondiente para cada variable al hacer la conversión a código maquina? ¿Esta predeterminado o se utiliza una cualquiera?

Gracias

**Comment by Arcoirisky** [comment]
@NoemiCC la dirección de memoria viene determinada en la ubicación que tenga la variable al final de la traducción. Es posible calcularlo de muchas formas pero no es que sea una al azar O: 

Si miras bien los ejemplos puedes darte cuenta de que son las posiciones en las que están (recuerda leer en base 8 uwu)

**Comment by fgbruna** [comment]
Creo que no me queda claro lo de las posiciones en base 8 @Arcoirisky.
Por ejemplo para el caso del ejemplo de [multiplicacion](https://github.com/IIC2343/syllabus/blob/master/Tareas/T03/ejemplos%20(programada)/multip.asm).
Para la variable resultado te refieres a que hay una relación entre la línea 23 y el 36 en octal que se escribe en el archivo compilado?
Gracias de antemano!

**Comment by Arcoirisky** [comment]
Míralo de esta forma, tienes la instrucción “MOV Ax, [Dir]” cuyo opcode es 36 (en octal). 

Luego, miras la variable y te das cuenta que es “Resultado”. Si miras dónde queda esta variable al final de transcribir todo a binario, te das cuenta que es en la línea 17 (21 en octal) entonces el literal de esa instrucción es **la dirección/posición de memoria** en la que está tu variable. 

Si aún no te queda claro intenta traspasar el ejemplo a mano y piensa en lo que haces para poder transcribirlo. Realmente ayuda hacerlo :D

**Comment by fgbruna** [comment]
Pero entonces por qué en el ejemplo del enunciado se termina escribiendo 36 D:?

**Comment by jmwielandt** [comment]
`MOV Ax, [36]` escribe en Ax lo que esté en la posición de memoria 36.

**Comment by fgbruna** [comment]
Eso lo tengo claro, pero, basandome en lo que dijeron @ariel-m-s y @Arcoirisky.En el ejemplo de la multiplicación **no me queda claro** por que al compilarlo se escribe un 36 seguido de un 36 siendo que la dirección de resultado es 21 en octal, por lo que me hace sentido que sea 36 y luego 21.

**Comment by ariel-m-s** [comment]
@fgbruna fíjate en qué líneas se encuentran declaradas las variables. En el enunciado, anda al código compilado y cuenta (línea por línea, comenzando desde el cero) hasta llegar a la declaración de las variables (que se encuentra en la parte final del código).

Te darás cuenta que la variable ```x``` se encuentra declarada en la línea ```0o0034```, ```y``` en la ```0o0035```, ```resultado``` en la  ```0o0036``` y ```cont``` en la ```0o0037```.

Según esto, para compilar la instrucción ```MOV Ax, [resultado]```, debemos utilizar dos líneas, una que transcriba la instrucción ```MOV Ax, [Dir]``` y otra que nos indique a qué dirección (```Dir```) nos referimos. La instrucción corresponde al opcode ```0o0036``` y la dirección de la variable ```resultado``` es la ```0o0036```. Que sea el mismo número es únicamente una casualidad.

Ariel

**Comment by fgbruna** [comment]
Muchas gracias, ahi si me quedo claro!

**Comment by ignacioaraya1995** [comment]
Tengo una duda, puedo definir la posición de memoria de otra forma y siempre ser consistente?

**Comment by jmwielandt** [comment]
No, porque lo revisamos con tests automatizados.

**Comment by Arcoirisky** [comment]
@ignacioaraya1995 expláyate (si crees que estarías soplando puedes mandarme un correo)

**Comment by ignacioaraya1995** [comment]
> No, porque lo revisamos con tests automatizados.

Ok



> @ignacioaraya1995 expláyate (si crees que estarías soplando puedes mandarme un correo)

Gracias pero ya me quedó claro

**Comment by Felipehanckes** [comment]
Hola!

Parece que no estoy entendiendo mucho la discusión.

¿Por qué en el ejemplo subido [multiplicacion](https://github.com/IIC2343/syllabus/blob/master/Tareas/T03/ejemplos%20(programada)/precomp.asm) se saltan varias lineas de la memoria, se saltan de la linea 16 a la 20 en un Mov Ax, [y] y de la 26 a la 30 en endprog MOV Ax, [resultado], siendo que deberia avanzar de a 2, ya que solo hay un ingreso a memoria y una operación?

Tampoco entiendo por que;
MOV Ax , [resultado]

Pasa a ser:

0o0036 ; MOV Ax, Dir # 0o0036 es el opcode asignado a Mov Ax Dir
0o0021 ; Dir=var:resultado # 0o0021 No entiendo porque.

Gracias!

**Comment by Arcoirisky** [comment]
Porque las variables, al pasar al código máquina no se reemplazan por su valor definido en el assembly, sino como la posición de memoria en la que está guardado el valor que fue definido en el Assembly.

Léelo con calma y trata de transcribirlo a mano o: 

Considera la issue #117 sobre lo que significa el modo en el que pedimos valores a memoria con variables.
