### ISSUE TITLE
Flip-flop-D o latch-D? 

### ISSUE THREAD

**Issue by naquiroz** [IIC2343/syllabus#92]
Hola, en enunciado se hablan de flipflops de tipo D, sin embargo, 
en el material (Apuntes) aparece que un flip-flop tipo D es lo que vimos en clases como un _latch-D_, que no es lo mismo. Entonces cual debemos tomar? el Flip-flop de los apuntes o el flip-flop de clases?

**Comment by Geeermy** [comment]
¡Hola!

En este caso, **debes guiarte por el enunciado**, el que dice que son _flip-flops_.

Como regla general, además, te recomiendo guiarte por las clases en esos casos, dado que en estas se puede profundizar un poco más en aspectos que no necesariamente tocan los apuntes.

¡Éxito! 🦑
