### ISSUE TITLE
Código de multiplicación, Proyecto

### ISSUE THREAD

**Issue by mvgil** [IIC2343/Syllabus#92]
Hola!
En el enunciado de la entrega sale que se debe escribir en lenguaje de máquina un programa de la ROM que multiplique. Esta multiplicación debe ser también entre números negativos ? o es libre ?

Muchas gracias!

**Comment by frvalenzuela** [comment]
Hola @mvgil !

El computador básico del proyecto a diferencia del computador básico visto en clases solo soporta números positivos. Asi que no deben preocuparse de los negativos.

Saludos!
