### ISSUE TITLE
Entrega 3 | Test de simulación 

### ISSUE THREAD

**Issue by fjlopez7** [IIC2343/Syllabus#92]
Nos van a entregar archivos de simulación como la entrega pasada? Para revisar que este correcto el funcionamiento de nuestra entrega, dado que en cierto casos seria difícil generar estos.

Como nos recomiendan que testemos la entrega?

**Comment by frvalenzuela** [comment]
Hola @fjlopez7 !

Entre hoy y mañana estarán subidos los test evaluados.

Saludos!

**Comment by frvalenzuela** [comment]
Hola!

Tardo un día más de lo máximo esperado, pero ya se encuentran arriba!

Saludos!
