### ISSUE TITLE
Entrega 3 | Inicio de SP

### ISSUE THREAD

**Issue by cacosandon** [IIC2343/Syllabus#93]
Hola!

Para iniciar el SP se recomienda partir en 0 y decrementar en 1 en un comienzo. ¿Esto no retrasaría toda la simulación? Podemos "intersectar" la operación de decrementar en 1 con la primera operación de la ROM (asumiendo que esto nunca afectará al programa)?

Gracias!

**Comment by frvalenzuela** [comment]
Hola @cacosandon ! 

Partir el SP con un valor por defecto o ejecutar la primera instrucción para disminuirlo en uno son dos versiones válidas. Si utilizan la versión que requiere una instrucción adicional en su ROM **deben especificarlo en su informe**. Así como también subir los test evaluados con la modificación de tiempo necesaria para poder corregir con esa característica en mente. 

Si quedo algo confuso no dudes en preguntar.

Saludos !

**Comment by cacosandon** [comment]
Muchas gracias! me quedo claro, te pasaste!

**Comment by fncabrera** [comment]
Hola @frvalenzuela !

Según lo que dijiste, ¿sería valido modificar la primera instrucción de la ROM tal que, por ejemplo imaginemos que es un ADD A,B, y modificar su opcode tal que vaya incluido el decrementar en 1 el SP junto al ADD A,B ? (nos aseguramos que no hubiera ninguna primera instrucción que al hacer este cambio en el opcode sufriera alguna modificación el programa). 

Saludos!

**Comment by frvalenzuela** [comment]
Hola @fncabrera !

Si es una solución válida! También pueden agregar una espera más larga a los test si requieren la instrucción adicional para disminuir el SP. Siempre recordar de que todo eso **debe estar espeficado en su informe**. Pero nuevamente, la solución planteada también es válida.

Saludos!
