### ISSUE TITLE
Formato entrega Tarea 1

### ISSUE THREAD

**Issue by crabarca** [IIC2343/syllabus#93]
Hola, 
que tipo de formato de entrega para el codigo se debe seguir ? Debe ir todo en algún archivo con nombre especial por ej: nro_alumno.py. O podemos estructurar como queramos el codigo, obviamente  generando el archivo Resultados.txt

**Comment by Hernan4444** [comment]
@crabarca deben subir en su repositorio como grupo una tarea, idealmente en una carpeta de tareas para encontrarlo mas facil. Debe ser si o si el archivo python pero puede tener el nombre que desean y la cantidad que estimen conveniente mientras cumpla lo solicitado de generar un archivo Resultados.txt y que nos indiquen en el informe cual .py utilizar para darle los inputs

Saludos
