### ISSUE TITLE
With/Select + Mapa de Karnaugh

### ISSUE THREAD

**Issue by eitandv** [IIC2343/Syllabus#93]
Hola!
Trabajando en la Control Unit nos dimos cuenta que podemos codificar los opcodes para que nos den las señales solo con compuertas lógicas, mediante los mapas de Karnaugh. Sabemos como hacerlo, pero el proceso para incluir todas las señales, incluyendo las de 3 bytes, es muy mecánico y demoroso. Haciendo referencia a lo que dijo @frvalenzuela : "...su CU no sería **solo** selectores..." , ¿Podríamos definir 3 señales con Karnaugh y el resto con with/select?

**Comment by frvalenzuela** [comment]
Hola @eitandv

Si, esta bien dividir señales para facilitar el trabajo del diseño combinacional. 

Solo recordar que tienen 20 bits para trabajar de forma directa.

Saludos Juan, Cristobal y Felipe
