### ISSUE TITLE
[Tarea 3 - Programada] Duda con los []

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2343/syllabus#93]
Hola, en el ejemplo multip.asm de la carpeta de la Tarea 3, se encuentran las variables al ser definidas con [ ] al inicio al final, mientras que en el Enunciado de la Tarea siempre están con [].

¿Bajo cual de los 2 nos basamos?

**Comment by jmwielandt** [comment]
No hay ningún paréntesis cuadrado donde definimos las variables, que es en la zona de abajo del RET.

![image](https://user-images.githubusercontent.com/37153467/57049674-160ded00-6c47-11e9-8e3c-ea59c25d4974.png)

En el enunciado dice `MOV Bx, [x]`, no `MOV Bx, [ x ]`. Es una fuente monoespaciada.

**Comment by ignacioaraya1995** [comment]
Me refiero al primer momento de usarlas, por ejemplo en las lineas 11 y 12, ¿porque hay una variable entre corchetes cuadrados y la otra no?

**Comment by jmwielandt** [comment]
😭 
Fixed.
Era error de tipeo, tiene que estar con los paréntesis cuadrados.

**Comment by ignacioaraya1995** [comment]
Gracias, otra duda: ¿Que criterio se usa para definir lo opCodes marcados en negrita a continuación?

0o0036 ; MOV Ax, Dir
**0o0036** ; Dir=var:resultado
0o0037 ; MOV Bx, Dir
**0o0034** ; Dir=var:x
0o0005 ; ADD Ax, Bx
0o0000 ; ---
0o0040 ; MOV Dir, Ax
**0o0036** ; Dir=var:resultado
0o0036 ; MOV Ax, Dir
**0o0037** ; Dir=var:cont
0o0007 ; ADD Ax, Lit
0o0001 ; Lit=1
0o0040 ; MOV Dir, Ax
**0o0037** ; Dir=var:cont
0o0036 ; MOV Ax, Dir
**0o0035** ; Dir=var:y
0o0037 ; MOV Bx, Dir
**0o0037** ; Dir=var:cont
0o0027 ; CMP Ax, Bx
0o0000 ; ---
0o0033 ; JG Dir
0o0000 ; Dir=label:start
0o0036 ; MOV Ax, Dir
0o0036 ; Dir=var:resultado
0o0051 ; RET (primer ciclo)
0o0000 ; ---
0o0052 ; RET (segundo ciclo)
0o0000 ; ---
0o0003 ; x 3 (x=3 inicialmente)
0o0004 ; y 4 (y=4 inicialmente)
0o0000 ; resultado 0 (resultado=0 inicialmente)
0o0000 ; cont 0 (cont=0 inicialmente)
0o0000 ; NOP
0o0000 ; ---

**Comment by Arcoirisky** [comment]
En realidad no son opcodes, sino literales pero son las direcciones de memoria donde están guardadas esas variables.

**Comment by Felipehanckes** [comment]
Hola!

Me confundo  en como saber cuales son las direcciones de memoria en la que están guardadas esas variables :confused:  :confounded:, agradecería si me lo pueden aclarar :face_with_head_bandage: 

Gracias!

**Comment by Arcoirisky** [comment]
La forma más simple es no calcularlas inmediatamente. 

Si intentas hacer el traspaso de assembly a máquina con lápiz y papel, lo que se te hace lógico hacer es primero ir escribiendo los opcodes de las instrucciones seguido de sus literales hasta que se encuentran con su primera variable ¿Que harías si te lo preguntara en un control? :eyes:

Considera que conoces todo el archivo, no únicamente las líneas que estás leyendo (Recuerda que estamos pasando de Assembler a Machine)
