### ISSUE TITLE
[Tarea 3 - Prog. A] ¿Contradicción?

### ISSUE THREAD

**Issue by amartinezsilberstein** [IIC2343/syllabus#93]
Hola! Sigo sin poder entender completamente lo que nos están pidiendo en la parte A de programación. No sé si hay alguien que pueda intentar explicármelo. Mi duda va más o menos por lo que describo a continuación.

Si asumimos que los estados iniciales son todos `0`, se cumpliría la siguiente tabla de verdad para el circuito de ejemplo del enunciado (figura 1):

C (input) | Q (output)
------------ | -------------
`1` | `1`
`0` | `1`
`1` | `0`

En ese caso, al ingresar `1` como _input_ podríamos obtener `1` o `0` como _output_, dependiendo de lo que fue ingresado anteriormente. Si queremos modelar este comportamiento con un circuito **combinacional**, significa que dado un _input_ arbitrario, el valor del _output_ **siempre** será el mismo. Entonces, tomando `1` como _input_ pareciera haber una contradicción: cuál sería el _output_? `1` o `0`?

Por favor díganme qué estoy entendiendo mal del enunciado.

**Comment by Geeermy** [comment]
¡Hola!

Si tenemos un circuito combinacional, lógicamente no disponemos de elementos que almacenen estados (_i.e._ no tenemos _flip-flops_ y, por ende, no tenemos una noción de actualización por flanco de subida o bajada).

En definitiva, de esto se desprende que de los _flip-flops_ **solo nos interesa el efecto que causa su estado en el resultado del circuito.**

Espero que esto te ayude a aterrizar mejor lo que estamos pidiendo. 😸

**Comment by amartinezsilberstein** [comment]
Pero el "efecto que causa su estado" (del _flip-flop_) depende del estado en el que se encuentre. Es por esto que dicho efecto será distinto en distintos estados del _flip-flop_, que dependen de los _inputs_ anteriores. Entonces cómo podemos decir que "solo nos interesa el efecto que causa su estado" sin conocer su estado?

**Comment by Geeermy** [comment]
Porque tu circuito combinacional considera estos estados **como valores solamente**, ya que, efectivamente, ya no tenemos la noción del estado anterior. Si un circuito posee de entradas dos señales **A,B**, podemos conocer las posibles salidas de este circuito considerando los distintos valores que estas pueden adquirir (_... tablas de verdad_). ¿Cuál sería la diferencia, entonces?

Te recomiendo que revises **lo que se ha discutido en profundidad en otras _issues_** para entender mejor el panorama: #69, #71, #88, con eso ya deberías tener claro el panorama. 😄
