### ISSUE TITLE
Tarea 3 parte B Inputs

### ISSUE THREAD

**Issue by fmiranda22** [IIC2343/syllabus#94]
1. Podemos asumir que si hay distinta cantidad de inputs en el circuito, estos van a tener la misma cantidad de iteraciones.?
2. De que manera van a a entregar las rutas al programa, asumimos que nos van a entregar el path completo?

**Comment by Geeermy** [comment]
¡Hola!

1. Sí, no les vamos a pasar algo inconsistente, no se preocupen por eso. 😄
2. Esto se hará mediante **línea de comandos**. Algo de este estilo:

> C:\Users\Alumno\nombre_tarea.py archivo_entrada.json

Puedes asumir que el _path_ a ingresar es correcto (debiese dar lo mismo si es absoluta o no, pero no vamos a rebuscar ese tema), así que no te preocupes.

¡Éxito! 🐗

**Comment by Geeermy** [comment]
¡Hola @acrojas2 !

Pucha, no es posible levantar la restricción ya que se pide así para facilitar la restricción de sus tareas. :(

Si quieres puedes escribirme a mi correo (glcontreras@uc.cl) o bien postear en una nueva _issue_ los errores que te salen y lo resolvemos en conjunto. La mayoría ha podido añadirlo sin mayor problema, por eso me parece raro.

¡Ánimo! Aún se puede :)

**Comment by acrojas2** [comment]
Ya lo logre 😆
