### ISSUE TITLE
Tarea 1: Parte 2: Registro de 16 bits

### ISSUE THREAD

**Issue by lfbesa** [IIC2343/syllabus#94]
Cuando en la parte 2 de la tarea se nos dice que se usarán registros de 16 bits. ¿Esto significa que ningún numero que nos den para operar superará los 16 bits o que si los pasa solo trabajamos con los primeros 16 bits?

**Comment by Hernan4444** [comment]
@lfbesa Nosotros no daremos numeros mayores a 16 bits pero las operaciones si pueden superar la cantidad de bits y en ese caso deben trabajar con los 16 bits menos significativos (más de la derecha).

Saludos!
