### ISSUE TITLE
[Tarea 3 - Placa] Duda señales

### ISSUE THREAD

**Issue by danustilovsky** [IIC2343/syllabus#94]
Hola, ¿Existe alguna convencion o algo por el estilo sobre que operacion o output debe seleccionarse segun las señales que lleguen al componente? 

Por ejemplo, ¿con que combinacion de señales se debe sumar en la ALU?, y asi con el resto de los casos.

Gracias

**Comment by frvalenzuela** [comment]
Hola!

No existe ninguna convención sobre lo que debe seleccionarse.

Si tu combinación de señal para sumar la ALU es "000" o "110" no es relevante, mientras que el opcode libere las señales necesarias para ejecutar una instrucción y esta instrucción se ejecute de la manera esperada.

Saludos!
