### ISSUE TITLE
Tarea 1 Parte 2: Dudas con floats

### ISSUE THREAD

**Issue by Pyralspite** [IIC2343/syllabus#95]
Hola!
Tengo un par de dudas sobre como debemos trabajar con los floats en la segunda parte.
- Al momento de transformar un decimal a un float binario debemos ocupar el formato half o algún otro formato (o nos inventamos uno)?
- Si nos piden realizar una operación lógica (and, or, xor), puede ser entre floats, o entre un float y un int? Y en este último caso, debemos transformar el int en float o los operamos directamente?

Saludos :)

**Comment by Hernan4444** [comment]
@Pyralspite 

> Al momento de transformar un decimal a un float binario debemos ocupar el formato half o algún otro formato (o nos inventamos uno)?

Cuando no se especifica el formato del float podemos asumir que es el estandar que usamos tambien en la parte 1.

> Si nos piden realizar una operación lógica (and, or, xor), puede ser entre floats, o entre un float y un int? Y en este último caso, debemos transformar el int en float o los operamos directamente?

Como no está especificado en el enunciado, queda a tu criterio. Solo recuerda especificarlo en el informe. Lo mas sencillo sería operar directamente usando la misma cantidad de int.

Saludos ✌️

**Comment by Pyralspite** [comment]
Muchas gracias!
