### ISSUE TITLE
[Tarea-3 Placa] Testear Entidad

### ISSUE THREAD

**Issue by MrEarle** [IIC2343/syllabus#95]
Existe alguna forma, en Vivado, para probar una entidad?

Es decir, poder entregarle un input y ver cual es su output, para verificar su correctitur.

**Comment by frvalenzuela** [comment]
Hola Benjamin!

Si! existe una forma. Se llama **simulación**. Esta opción que ofrece el programa permite verificar la correctitud a través de señales **predefinidas** (que es básicamente lo que dices de entregar un input, para luego ver el output).

Ahora bien, como experiencia personal las simulaciones significa también un trabajo extra, y el análisis del mismo puede **no ser claro en ocasiones** (esto dependiendo mucho de como sea la entidad evaluada). Es por esto que **se recomienda** probar con la Basys3 las entidades que vayan creando. 

Si aún así quieres intentar simular tus entidades aquí va una breve explicación de como simular:

### COMO SIMULAR UNA ENTIDAD EN VIVADO

Paso 1: Apretar en la ventana de Sources añadir 'Add Source:'
![image](https://user-images.githubusercontent.com/20147482/57173092-ee11bb80-6df7-11e9-8169-94f75f1f2dd6.png)


Paso 2: Seleccionar 'Add or create simulation sources' y luego apretar siguiente:
![image](https://user-images.githubusercontent.com/20147482/57173114-53fe4300-6df8-11e9-80e0-50278fc009bb.png)

Paso 3: Seleccionar la opción 'Create File':
![image](https://user-images.githubusercontent.com/20147482/57173121-75f7c580-6df8-11e9-8d0a-fc0af55fbb68.png)

Paso 4: Dar el nombre de la simulación (para el caso de este ejemplo ocuparemos el Full Adder llamado FA) y apretamos en OK:
![image](https://user-images.githubusercontent.com/20147482/57173126-ac354500-6df8-11e9-8665-ee08ff87f699.png)

Paso 5: Apretar en 'Finish'
![image](https://user-images.githubusercontent.com/20147482/57173138-e3a3f180-6df8-11e9-90eb-1bf28124fb64.png)

Paso 6: Se abrirá una ventana para pedir los inputs y outputs de la entidad de la simulación. Como  entidad ya definida (no la definimos la entidad en la misma simulación) dejaremos todo en blanco y solo apretaremos en 'OK':
![image](https://user-images.githubusercontent.com/20147482/57173153-3aa9c680-6df9-11e9-8cd0-e49687712e89.png)

Paso 7: Apretamos en 'Yes' a la ventana que nos advierte que no definimos ningún input/output:
![image](https://user-images.githubusercontent.com/20147482/57173163-5e6d0c80-6df9-11e9-8114-5541a7d2a475.png)

Paso 8: Nos redirigimos a la ventana de 'Sources' y expandimos la carpeta llamada 'Simulation Sources':
![image](https://user-images.githubusercontent.com/20147482/57173181-b3108780-6df9-11e9-9d59-54b9b244f3cc.png)

Paso 9: Expandimos la carpeta sim_1 donde nos mostrará todas las entidades definidas.
![image](https://user-images.githubusercontent.com/20147482/57173189-d20f1980-6df9-11e9-9bb8-ccb7dcd96a1b.png)

Paso 10: Seleccionamos el archivo que creamos, apretamos click derecho y seleccionamos la opción Set as Top
![image](https://user-images.githubusercontent.com/20147482/57173231-a3457300-6dfa-11e9-948b-03d5be9e9236.png)

Paso 11: Pensando en la entidad simulación como una entidad cualquiera, debemos llamar como componente a la entidad que queremos simular, en este caso FA, dicho componente será instanciado más adelante:
![image](https://user-images.githubusercontent.com/20147482/57173277-51511d00-6dfb-11e9-8722-872a6fd07810.png)


Paso 12: Luego definiremos las señales, pero a diferencia de como se hace habitualmente, aquí todas las señales de entrada del componente a simular será entregado **por una sola señal**. Esta señal será un **std_vector** con una longitud igual a la suma de la cantidad de bytes de todas las señales de entrada. En este ejemplo, la señal 'test' es de largo de 3 bits porque el componente FA tiene la entrada 'a' que es de un bit, la entrada 'b' que también es de un bit y finalmente la entrada 'ci' que es de un bit. Por lo tanto la suma de todas dichas entradas de un bus de datos de 3 bits. Finalmente las señales de output pueden estar separadas (no es necesario una única señal):
![image](https://user-images.githubusercontent.com/20147482/57173346-4fd42480-6dfc-11e9-8603-a59685bd62bf.png)

Paso 13: Ahora añadiremos **el comportamiento de la simulación**. Para esto ocuparemos las lineas de comando de 'begin process' (solo permitido para simular no lo ocupen en descripción de circuitos de su tarea), junto con el comando 'wait'. Esto se vería de la siguiente forma:
![image](https://user-images.githubusercontent.com/20147482/57173368-a6d9f980-6dfc-11e9-93e2-93ebf7ccce72.png)

**NOTA: ** hay que recordar que los tres bits de la señal 'test' representan el valor de cada bit de entrada, por lo tanto lo que significa este código es que durante los primeros 100 nano segundos la señal test tomará el valor "000" lo que significará que todas las entradas del Full Adder son cero. Pasado ese tiempo test tomará el valor "001" eso quiere decir que el bit menos significativo de la señal test tomará el valor de 1. Para este ejemplo diremos que el bit menos signficativo corresponde a la entrada 'a' (esto será definido en la instancia y es arbitrario de como se implemente). Finalmente test tomará el valor "010" que significará que el segundo bit menos significativo, que para este ejemplo diremos que es la entrada 'b' tomará el valor de 1, y luego la simulación termina.

Paso 14: Instanciar el componente (este paso puede ser en conjunto con el paso 12)
![image](https://user-images.githubusercontent.com/20147482/57173405-7050ae80-6dfd-11e9-9e51-6e80b884fe0d.png)

Repasando el código de la simulación descontando los comentarios automáticos que se dan por crear el archivo sería:

``` 
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;


entity simulation_FA is
--  Port ( );
end simulation_FA;

architecture Behavioral of simulation_FA is

component FA
    Port (
         a : in STD_LOGIC;
              b : in STD_LOGIC;
              ci : in STD_LOGIC;
              s : out STD_LOGIC;
              c : out STD_LOGIC
          );
    end component;
 
signal test            : std_logic_vector(2 downto 0);
signal out1            : std_logic;
signal out2            : std_logic;

begin

process 
begin
    test <= "000";
    wait for 100 ns;
    test <= "001";
    wait for 100 ns;
    test <= "010";
    wait for 100 ns;
    wait;

end process;

inst_FA: FA port map(
    a => test(0),
    b => test(1),
    ci => test(2),
    s => out1,
    c => out2
    );


end Behavioral;
``` 
Paso 15: Simular. Para esto nos vamos a la pestaña lateral izquierda de Vivado, vamos a la opción 'Run Simulation' y luego 'Run Behavioral Simulation':
![image](https://user-images.githubusercontent.com/20147482/57173474-64192100-6dfe-11e9-95c5-a3834da05aec.png)

Paso 16: Luego de una pantalla de carga debería mostrar algo como lo siguiente:
![image](https://user-images.githubusercontent.com/20147482/57173512-fa4d4700-6dfe-11e9-9f40-f342a33f25d5.png)

Paso 17: Centrándonos en la pantalla negra, expandimos la señal que contiene los inputs, en este caso la señal test:
![image](https://user-images.githubusercontent.com/20147482/57173531-4ac4a480-6dff-11e9-9261-01c5f62532cc.png)

Paso 18: **Teniendo seleccionado la señal de inputs**  (en este caso test) apretamos los botones que se muestran en la imagen para ver estados anteriores (en nuestro caso "001" y "000") y en la columna 'Value' podemos ver como las señales de opcode van cambiando.


### Concluyendo

Como pueden ver simular también requiere tiempo y un buen entendimiento de las señales que trabaja su entidad, ademas de una buena lectura de lo que va entrando y saliendo, por esto **recomiendo el uso de la placa**. Aunque si a ustedes les hace más cómo simular, ahí están todos los pasos a seguir.

Si no queda algo claro favor de hacerlo saber. 

Espero que esto aclare tu duda!

Saludos!

**Comment by MrEarle** [comment]
Muchas Gracias!
