### ISSUE TITLE
[Tarea 3] Programación formato entrega

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2343/syllabus#96]
Hola! No entendí muy bien el formato de entrega que mandaron por mail. Lo que entendí por el enunciado es que había que entregar solo el archivo .py, sin ningún .json. Por lo que creo que hay que hacer es solo subir el .py o no?

**Comment by Geeermy** [comment]
¡Hola!

A lo que se refiere el enunciado **no es eso**, si no a cómo inicializar el programa. Esto **debe hacerse por línea de comando**, tal como se indicó en el correo y en esta _issue_: #94.

Es decir, no es válido que entregues una tarea que se ejecuta por IDLE y que va pidiendo manualmente cada _input_ 😓. Si tienes dudas de cómo hacerlo (habiendo revisado las fuentes que dejamos disponibles), escribe de nuevo para solucionarlo.

¡Éxito!
