### ISSUE TITLE
[Entrega 2] Informe y README

### ISSUE THREAD

**Issue by ceosorio** [IIC2343/Syllabus#96]
Hola! 

Estaba leyendo el enunciado y sale que debemos entregar un informe y el README.md junto con la entrega del proyecto. Mi duda es a que se refieren con el README y el informe.
Uno de esos debe ser la bitácora que se detalla en el enunciado, pero no tengo claro que sería el otro documento .md

**Comment by frvalenzuela** [comment]
Hola @ceosorio !

En el README deben poner información como integrantes del grupo, como estan organizados los directo. En general cosas básicas de la estructura de su repositorio. MIentras que el informe es referido más a el trabajo realizado.

Si algo no quedo claro favor hacerlo saber.

Saludos Felipe y Cristobal!

**Comment by ceosorio** [comment]
@frvalenzuela en el caso del repositorio, debemos mantener la carpeta modulos?

**Comment by frvalenzuela** [comment]
Hola @ceosorio !

Si lo ocuparon para ejecutar el `.xpr` entonces si.

Saludos!
