### ISSUE TITLE
INPUTS

### ISSUE THREAD

**Issue by cjgazali** [IIC2343/syllabus#96]
Insisto porque he leído cosas por separado...
Se deben recibir como inputs:
Parte 1: números positivos en base entre 2 y 10, con o sin decimales.
Parte 2: números positivos en base 10, con o sin decimales.

Esto lo he leído en otras issues. Corregir si me equivoco.

Me quedan además un par de dudas:
duda1: Para inputs y outputs, se ocupa solo PUNTO decimal, como en #92?
duda2: sobre los inputs en la parte 2: en el enunciado, en text.txt en '3. Metodología' hay una entrada '-2 || 2' con un número negativo, pero en un issue dijeron que los inputs siempre son positivos.

Gracias.

**Comment by Hernan4444** [comment]
@cjgazali estás perfecto 👍 

Duda1: Si, solo usaremos punto (si ya hiciste con comas, podemos ajustar los test pero preferimos usar punto)
Duda2: Si, en la otra issue ya respondí, eso fue solo para mostrar el formato. Pido disculpa si generó mucha confusion ese test.

Espero haber resuelto todas tus dudas.
Saludos!

**Comment by cjgazali** [comment]
Seco @Hernan4444
