### ISSUE TITLE
[Tarea-3-Placa] No aparecen todos los sources en Vivado

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2343/syllabus#97]
He ido agregando algunas entidades trabajándolas siempre con sublime, pero ahora ya no me aparecen en la sección de sources de Vivado, la ALU ya no me la reconoce y las entidades ADD o SUB que creé tampoco son reconocidas, por lo mismo no me deja hacer la síntesis 😢 
Adjunto screenshots:
![image](https://user-images.githubusercontent.com/30912090/57159243-6904b300-6db3-11e9-96fe-16b66cc78ee6.png)
Y esto es lo que contiene la carpeta:
![image](https://user-images.githubusercontent.com/30912090/57159263-7d48b000-6db3-11e9-87cd-bc350a5a3f9f.png)
Gracias.

**Comment by frvalenzuela** [comment]
Hola Daniel!

Te recomiendo revisar lo puesto en esta issue: #61

Ahí da los pasos a seguir para añadir tus componentes a la ventana Sources.

Si tienes alguna complicación estaré atento. De la misma forma si queda solucionado sería grato saberlo también.

Saludos!
