### ISSUE TITLE
decimal double / alargar con ceros / observación parte 1

### ISSUE THREAD

**Issue by cjgazali** [IIC2343/syllabus#97]
1) En las observaciones de la primera parte dicen 'los datos en concreto a analizar son' y NO mencionan decimal double. No nos pueden pedir algo así como 'double'? Ignoramos decimal double?

2) Lo otro es que piden claramente que recortemos por la derecha cualquier secuencia más grande que lo que el formato destino puede interpretar pero, ¿Qué pasa si el formato destino interpreta más bits que el de origen (ej: de int a float)? ¿Agregamos ceros a la izquierda?

3) No entiendo la primera observación de la parte 1 porque en los ejemplos pareciera que la consulta la harán ocupando la columna 'SE ESCRIBE' de la tabla de datos permitidos del enunciado (int, long, float, double, char) o no?? ¿Qué información nos da esta observación?

**Comment by Hernan4444** [comment]
@cjgazali en las observaciones solo es para que puedan guiarse. Si observamos el int, existe uno de 16 bit, 32 e incluso 64 y para evitar que usaran algún int diferente al que esperamos, hicimos esa observación para que supieran que el int (normal) es el de 16 bit mientras que el long es de 32. El double no lo mencionamos porque como su nombre indica, es el doble de un decimal. Si indicamos que el float es de 32 entonces implicamos que el double es de 64. Por lo tanto si podemos pedir double y ustedes lo interpretan como 64 bits.

Sobre tu segunda duda: Si, debes agregar 0 si es que el destino interpreta más bits.

Sobre la tercera, tal como dije en el primer parrafo, era para evitar ambiguedad de que tipo de int o de float ibamos a utilizar. Era más una aclaración para quienes vienen de un lenguaje similar a C donde existen muchos más tipos como:
```
int8_t
int16_t
int32_t
uint8_t
uint16_t
uint32_t
``` 

Saludos!
