### ISSUE TITLE
[Entrega 2] Error: Multiple Driver Nets: Net ... has multiple drivers

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2343/Syllabus#97]
Hola! 

Estamos con un error que le hemos dado muchas vueltas y no hemos encontrado solución. 

Hicimos todos los módulos y creemos que está todo bien. En la etapa de implementación, sin embargo, nos tira el siguiente error: 

![image](https://user-images.githubusercontent.com/26395403/66723169-52479b00-edec-11e9-8896-f15de1d68f43.png)

Buscando en internet encontramos que un posible error es que tengamos alguna variable definida dos veces o que tengamos dos cables conectados a la misma variable, por lo que hay conflicto. Sin embargo, revisamos varias veces nuestros módulos y no encontramos nada raro. 
Porfa ayuda!

Gracias!

**Comment by Faalfaro** [comment]
Pudieron resolverlo? nosotros estamos con el mismo.

**Comment by fedetaladriz** [comment]
@Faalfaro Aun no. Avisen si logran solucionarlo ustedes porfa!

**Comment by frvalenzuela** [comment]
Hola @fedetaladriz !

En su ALU tienen definido: 
```
-- privado 
    signal_privada(0) <= algo; -- modificado por privacidad. Línea 109

-- privado
   -- privado 
    signal_privada(0) <= otra_cosa; -- modificado por privacidad. Línea 113
```

Por tanto están haciendo mando dos señales distintas a `signal_privada` dentro de su ALU. También mencionar que su ALU recibe un clock y hace un process **ESTO NO ESTA PERMITIDO**, como fue estipulado en la issue #82 

Al sacar dicho process, y conectar la `signal_privada` a tierra no hubo problemas en la implementación, así que es probable que su error estaba en esa parte.

Saludos!

**Comment by frvalenzuela** [comment]
Hola @Faalfaro !

Revisen muy bien cada uno de sus componentes, lo más seguro es que tienen un problema del tipo conectar dos entradas a una señal, o conectar una señal de entrada a otra señal de salida en una misma entidad. 

Saludos!

**Comment by fedetaladriz** [comment]
Muchas gracias por la ayuda @frvalenzuela !!
