### ISSUE TITLE
Administrativa | Dudas generales.

### ISSUE THREAD

**Issue by nhorellana** [IIC2343/Syllabus#98]
Hola! Queria preguntar dos cosas:
1) Mas o menos desde donde hasta donde entra en la interrogacion del lunes?
2) Mas o menos cuando creen que estaran las notas de la recorreccion de la T1, la T2 y la I2?

Muchas gracias!

**Comment by jmwielandt** [comment]
Hola

1. Entra todo paralelismo a nivel de instrucción (pipeline) y la materia de arquitecturas de los computadores (ISA y microarquitecturas).

2. Estamos trabajando para ustedes, esperamos subirles las recorrecciones de la I1 y las notas de la I2 antes del lunes, y las notas de las tareas antes del miércoles.

Saludos!

**Comment by nhorellana** [comment]
Muchas gracias!
