### ISSUE TITLE
Entrega Placa

### ISSUE THREAD

**Issue by mericci** [IIC2343/Syllabus#98]
Hola! ¿la placa para el proyecto debemos entregarla? o dado que la entrega 3 es en dos semanas más nos la quedamos hasta el fin de esa entrega?

Muchas gracias!

**Comment by frvalenzuela** [comment]
Hola @mericci ! 

No deben entregar la placa, dado que seguirán con su equipo hasta final de semestre donde deberán entregarla.

Saludos!
