### ISSUE TITLE
Uso libreria ast

### ISSUE THREAD

**Issue by crabarca** [IIC2343/syllabus#98]
Se puede utilizar la libreria `ast` de python ?

Doc:
https://docs.python.org/3/library/ast.html#module-ast

Saludos !

**Comment by FranLucchini** [comment]
Si fueras tan amable de darme una idea de para qué sirve y cómo lo quieres usar, te podría dar una respuesta.

**Comment by crabarca** [comment]
@FranLucchini perdón ! 
En especifico quiero usar `ast.literal_eval()` como sustituto ~flaite~ de` float()`, pero sin las habilidades mágicas de `float()`

**Comment by FranLucchini** [comment]
Lamentablemente no se puede usar esa librería.
