### ISSUE TITLE
[Repo Tarea 03]: URGENTE

### ISSUE THREAD

**Issue by acrojas2** [IIC2343/syllabus#98]
No me ha llegado la invitación al para la creción del Repo!!!!!!! 😟 🙍

**Comment by savelozo** [comment]
En el Syllabus del curso lo publican; https://classroom.github.com/a/0yI7wc_n

Espero te sirva, saludos!

**Comment by acrojas2** [comment]
Gracias! No habia cachado que lo habían puesto en el readme 😃

**Comment by jheysen** [comment]
El syllabus se actualiza **siempre** con los enlaces relevantes, ya sea a creación de repos de entrega, enunciados de tareas, notas de las tareas, etc. Siempre revísenlo antes.
