### ISSUE TITLE
Señal C Tarea 1

### ISSUE THREAD

**Issue by mrafaeli** [IIC2343/syllabus#99]
Hola, 

No entiendo cuando se activa la señal C en la parte 2.
"Se activa cuando sumas y el resultado es menor a los sumandos."

Es decir que se activa cada vez que restamos?

**Comment by Hernan4444** [comment]
Estimado,  imaginemos que la restricción es usar 4 bits por registro en vez de 16. ¿Que sucede si sumamos 14 + 14?
En binario es 1110+ 1110 = 11100 pero como solo usamos 4 bits queda en 1100 que es doce 12

Aquí está el caso que 14 + 14 = 12... el resultado es menor a los sumandos.... en ese caso la señal C se activa.

Saludos!!

**Comment by crabarca** [comment]
Creo que hablar de sumandos confunde un poco, porque sumando se refiere solamente a uno de los numeros de la operacion `+` quizas otra forma de decirlo es: "Se activa cuando sumas y el resultado es menor al resultados de los sumandos."

Saludos !

**Comment by Hernan4444** [comment]
@crabarca tienes toda la razón. Lo que sucede es que esta señal tambien tienes que implementarla en la placa y ahí no puedes comparar el resultado de la suma con el resultado de los sumandos (porque la placa solo soporta numeros de 16 bits) pero si puedes comparar el resultado con ambos sumandos y si resulta ser menor a alguno de los dos se puede concluir que es menor a la suma "real". Lamento las confuciones causadas.

Saludos!!
