### ISSUE TITLE
Fechas proyecto

### ISSUE THREAD

**Issue by cotiravanal** [IIC2343/Syllabus#99]
Hola!, existe algún calendario con las fechas de entrega de enunciado y entrega del proyecto?

**Comment by frvalenzuela** [comment]
Hola @cotiravanal !

Si!, en SIDING en la sección calendario pueden revisar las fechas de las evaluaciones con su respectiva ponderación. De cualquier forma fue actualizado el README del Syllabus con las fechas más próximas.

Saludos!
