### ISSUE TITLE
[TAREA 3 PROGRAMADA] código assembly

### ISSUE THREAD

**Issue by chocopiano** [IIC2343/syllabus#99]
Hola! Cual va a ser el input del assemble (es decir, como en el enunciado o como alguno de los ejemplos de la carpeta)?

**Comment by jmwielandt** [comment]
Son el mismo, con un par de nombres cambiados y una label más.

**Comment by chocopiano** [comment]
Me confundí entonces con los precomp. Estos especificamente que hacen?

**Comment by jmwielandt** [comment]
Ayudarlos a entender mejor qué tienen que hacer, podríamos no ponerlos si lo prefieren, pero creemos que les pueden servir. Es meramente ilustrativo.

**Comment by Arcoirisky** [comment]
De todas formas, @chocopiano guíate por el enunciado :D o si ya es tarde, especifícalo en el readme 😱
