### ISSUE TITLE
Entrega 3 | Error en test2.txt

### ISSUE THREAD

**Issue by jiaranda** [IIC2343/Syllabus#99]
Hola!
El archivo `test2.txt` tiene las definiciones de las variables separados con tabs en lugar de espacios. ¿Esto es un error o debemos manejar ese tab?

**Comment by frvalenzuela** [comment]
Hola @jiaranda !

En la entrega no se evalua el assembler, teniendo la posibilidad que conviertan los códigos a mano, así que pueden modificar los .txt como les resulte más conveniente. Como equipo de ayudantes de proyecto solo revisaremos las ROMS y Tests simulados. 

Saludos!

**Comment by jiaranda** [comment]
Bien! Gracias 😁
